.travis.yml
etc/travis/suites/packages/before_install.sh

[Maintenance] Remove memory swap

---

features/product/managing_product_association_types/editing_product_association_type.feature
src/Sylius/Behat/Context/Api/Admin/ManagingProductAssociationTypesContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingProductAssociationTypesContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml

| Related tickets | part of #11250, improvements from #11319

[API] Association types improvements

---

src/Sylius/Bundle/AdminBundle/Resources/views/PaymentMethod/_form.html.twig

| Related tickets | fixes #11344

[ADMIN] fix closed gateway config field in payment method form

---

composer.json
etc/travis/suites/application/before_install.sh
etc/travis/suites/application/install.sh
src/Sylius/Bundle/ShopBundle/Tests/Calculator/OrderItemsSubtotalCalculatorTest.php
src/Sylius/Bundle/ShopBundle/composer.json

| Related tickets |  Replaces #11349

[HOTFIX] Travis memory upgrade & turned off composer scripts

---

docs/book/index.rst
docs/book/products/multi_source_inventory.rst

[Docs][Plus] Resolving inventory stocks after shipment

---

etc/travis/suites/common/before_install.sh
src/Sylius/Bundle/ApiBundle/CommandHandler/RegisterShopUserHandler.php
src/Sylius/Bundle/ApiBundle/Provider/CustomerProvider.php
src/Sylius/Bundle/ApiBundle/Provider/CustomerProviderInterface.php
src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/providers.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/RegisterShopUserHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/Provider/CustomerProviderSpec.php
src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/messenger.yaml

| Related tickets | fixes for review from #11356 

[API] Move messenger config to bundles + extract providing customer to a separate service

---

features/promotion/managing_promotions/filtering_promotions_by_coupon_code.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
src/Sylius/Behat/Page/Admin/Promotion/IndexPage.php
src/Sylius/Bundle/AdminBundle/Resources/config/grids/promotion.yml

| Related tickets | fixes #10208

Admin filtering promotions by coupon code

---

src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/cap.yaml
src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/dress.yaml
src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/jeans.yaml
src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/tshirt.yaml
src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml

[Fixtures] Add possibility to specify menu taxon

---

src/Sylius/Behat/Context/Transform/ProductContext.php
src/Sylius/Behat/Resources/config/services/contexts/transform.xml

| Branch?         | master / 1.5
| Related tickets | haven't created ticket for this bug, related: #11092, fixes: #11117

Fixed: Hardcoded locale at Behat product transformer

---

src/Sylius/Bundle/CoreBundle/composer.json
src/Sylius/Bundle/PayumBundle/composer.json
src/Sylius/Bundle/UserBundle/composer.json
src/Sylius/Component/Core/composer.json

Use hwi/oauth-bundle:^1.0 in packages

---

docs/cookbook/deployment/symfonycloud.rst

[Docs] Don't use $HOME in SymfonyCloud deployment cookbook

---

src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipment.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/Shipment/Show/_breadcrumb.html.twig

[Shipment] Remove shipment index and add show shipment from order button

---

.gitignore

Ignore config files used by Symfony CLI https://symfony.com/doc/current/setup/symfony_server.html#different-php-settings-per-project

Ignore Symfony CLI PHP settings files

---

UPGRADE-1.0.md
UPGRADE-1.3.md
docs/api/taxons.rst
docs/book/customers/customer_pools.rst
docs/book/installation/sylius_plus_installation.rst
docs/book/organization/backward-compatibility-promise.rst
docs/components_and_bundles/bundles/SyliusGridBundle/your_first_grid.rst
docs/cookbook/emails/mailer.rst
docs/cookbook/frontend/google-analytics.rst
docs/cookbook/images/images.rst

Hi,
This PR will fix : 
- 1 typo in `UPGRADE-1.0.md`
- 1 typo in `UPGRADE-1.3.md`
- 1 typo in `docs/api/admin_api/taxons.rst`
- 1 typo in `docs/book/customers/customer_pools.rst`
- 1 typo in `docs/book/installation/sylius_plus_installation.rst`
- 1 typo in `docs/book/organization/backward-compatibility-promise.rst`
- 1 typo in `docs/components_and_bundles/bundles/SyliusGridBundle/your_first_grid.rst`
- 1 typo in `docs/cookbook/emails/mailer.rst`
- 1 typo in `docs/cookbook/frontend/google-analytics.rst`
- 1 typo in `docs/cookbook/images/images.rst`
Cheers! :robot:

[Docs] Fix typos

---

.github/autolabeler.yml

Fix Autolabeler configuration

---

.github/autolabeler.yml

Automatically add API label

---

features/homepage/viewing_only_taxons_from_menu_taxon.feature
src/Sylius/Behat/Client/ApiPlatformClient.php
src/Sylius/Behat/Context/Api/Shop/ChannelContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/homepage/viewing_products.yml
src/Sylius/Component/Core/Test/Services/DefaultUnitedStatesChannelFactory.php
src/Sylius/Component/Core/spec/Test/Services/DefaultUnitedStatesChannelFactorySpec.php

| Related tickets | based on https://github.com/Sylius/Sylius/pull/11402

[API] Channel switching

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CustomerGroup.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ExchangeRate.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Locale.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAssociationType.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Shipment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxCategory.xml

[API] Add missing access control

---

src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig

Add a filter icon for filters in admin grids

---

docs/plugin-development-guide/naming.rst

doc : add the composer dump-autoload instruction

---

src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_inventory.html.twig

From:
To: (like other tabs in the product's form)

Fix UI in Product's inventory tab

---

composer.json

Should resolve:
```bash
PHP Fatal error:  Uncaught Psalm\Exception\TypeParseTreeException: Unterminated bracket in /home/travis/build/Sylius/Sylius/vendor/vimeo/psalm/src/Psalm/Internal/Type/ParseTree.php:571
Stack trace:
#0 /home/travis/build/Sylius/Sylius/vendor/vimeo/psalm/src/Psalm/Type.php(171): Psalm\Internal\Type\ParseTree::createFromTokens(Array)
#1 /home/travis/build/Sylius/Sylius/vendor/vimeo/psalm/src/Psalm/Internal/Visitor/ReflectorVisitor.php(2668): Psalm\Type::parseTokens(Array)
#2 /home/travis/build/Sylius/Sylius/vendor/vimeo/psalm/src/Psalm/Internal/Visitor/ReflectorV …
```

[Maintenance] Upgrade psalm version

---

composer.json
config/packages/doctrine.yaml
src/Sylius/Bundle/AdminBundle/Controller/DashboardController.php
src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_chart.html.twig
src/Sylius/Bundle/CoreBundle/Resources/config/services/dashboard.xml
src/Sylius/Component/Core/Dashboard/IntervalsConverter.php
src/Sylius/Component/Core/Dashboard/IntervalsConverterInterface.php
src/Sylius/Component/Core/Dashboard/SalesDataProvider.php
src/Sylius/Component/Core/Dashboard/SalesDataProviderInterface.php
src/Sylius/Component/Core/Dashboard/SalesSummary.php
src/Sylius/Component/Core/Dashboard/SalesSummaryInterface.php
src/Sylius/Component/Core/spec/Dashboard/IntervalsConverterSpec.php
src/Sylius/Component/Core/spec/Dashboard/SalesSummarySpec.php
symfony.lock
tests/DataFixtures/ORM/resources/year_sales.yml
tests/Functional/SalesDataProviderTest.php

| New feature?    |yes
| Related tickets?   | #11371 

[Backend] Feeding sales statistics graph with date from chosen period

---

composer.json

| Related tickets | fixes #11440

[Composer] Add conflict to doctrine/inflector ^1.4 to fix taxons

---

composer.json

| Related tickets | https://sylius.atlassian.net/browse/SYL-963

synchronise dependencies

---

features/channel/managing_channels/adding_channel.feature
features/channel/managing_channels/adding_channel_with_shop_billing_data.feature
features/channel/managing_channels/adding_new_channel_with_menu_taxon.feature
features/channel/managing_channels/browsing_channels.feature
src/Sylius/Behat/Context/Api/Admin/ManagingChannelsContext.php
src/Sylius/Behat/Context/Transform/CountryContext.php
src/Sylius/Behat/Context/Transform/LocaleContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
src/Sylius/Behat/Resources/config/services/contexts/transform.xml
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/channel/managing_channels.yml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShopBillingData.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShopBillingData.xml

| Related tickets | partially #11250 
I'll split managing channels in 3 PRs, this is the first one.
Including in this PR: 
In the second PR :
- deleting_channel.feature
- deleting_multiple_channels.feature
- editing_channel.feature
- editing_menu_taxon_on_channel.feature
- editing_shop_billing_data_on_channel.feature
And in the last one :
- channel_unique_code_validation.feature
- channel_validation.feature
- not_being_able_to_add_disabled_channel_when_no_other_exist.feature
- not_being_able_to_delete_last_available_channel.feature
- not_being_able_to_disable_last_available_channel.feature
- …

[API] adding and browsing Channel

---

docs/plugin-development-guide/naming.rst

Doc : add renaming bundle in bundles.php

---

UPGRADE-1.8.md
src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product.yml
tests/Controller/AdminProductAjaxTest.php
tests/DataFixtures/ORM/authentication/administrator.yml
tests/DataFixtures/ORM/resources/product_associations.yml
tests/Responses/ajax/product/index_response.json

| Related tickets | fixes #9364

[Admin][Product] Ajax product search fails

---

src/Sylius/Behat/Context/Setup/ZoneContext.php
src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php
src/Sylius/Bundle/CoreBundle/Fixture/GeographicalFixture.php
src/Sylius/Bundle/CoreBundle/Form/Extension/CountryTypeExtension.php
src/Sylius/Bundle/CoreBundle/Installer/Setup/CurrencySetup.php
src/Sylius/Bundle/CoreBundle/Installer/Setup/LocaleSetup.php
src/Sylius/Bundle/CoreBundle/Tests/Fixture/GeographicalFixtureTest.php
src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelper.php
src/Sylius/Component/Addressing/Converter/CountryNameConverter.php
src/Sylius/Component/Addressing/Model/Country.php
src/Sylius/Component/Currency/Converter/CurrencyNameConverter.php
src/Sylius/Component/Currency/Model/Currency.php

Remove deprecations on Symfony Intl component

---

src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php

It disappeared in the storm of refactoring ⛈️

[Behat] Add missing zone step to fix the build

---

src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShopBillingData.xml

| Related tickets | after #11417 

[API] Remove unnecessary shop billing data client + minor fixes

---

docs/book/installation/index.rst
docs/book/installation/map.rst.inc
docs/book/installation/sylius_plus_upgrading.rst

| Related tickets | should be also updated on master after #11445 

[Docs][Plus] Add Plus upgrading guide

---

UPGRADE-1.7.md
src/Sylius/Bundle/CoreBundle/Doctrine/DQL/DateFormat.php
src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
src/Sylius/Bundle/CoreBundle/Resources/config/services/dashboard.xml
src/Sylius/Component/Core/Dashboard/SalesDataProvider.php

| BC breaks?      | no?
| Related tickets | based on #11405

[Dashboard] Add DQL to sales provider

---

features/product/viewing_products/viewing_products_discounted_price.feature
psalm.xml
src/Sylius/Behat/Context/Setup/ProductContext.php
src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
src/Sylius/Behat/Page/Shop/Product/ShowPage.php
src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php
src/Sylius/Bundle/CoreBundle/Templating/Helper/PriceHelper.php
src/Sylius/Bundle/CoreBundle/Twig/PriceExtension.php
src/Sylius/Bundle/CoreBundle/spec/Templating/Helper/PriceHelperSpec.php
src/Sylius/Bundle/ShopBundle/Resources/views/Common/Macro/money.html.twig
src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_price.html.twig
src/Sylius/Component/Core/Calculator/ProductVariantPriceCalculator.php
src/Sylius/Component/Core/Calculator/ProductVariantPriceCalculatorInterface.php
src/Sylius/Component/Core/Calculator/ProductVariantPricesCalculatorInterface.php
src/Sylius/Component/Core/spec/Calculator/ProductVariantPriceCalculatorSpec.php

| Related tickets | fixes #8258
Follows up pull request #11200 by @JulienLoison , fixing backward compatibility break

[Shop][Product] Display product original price on product page (no bc break)

---

src/Sylius/Bundle/PayumBundle/Resources/config/services/action.xml

isn't it `sylius`
| Branch?         | 1.1, 1.2 or master 

typo maybe!

---

docs/_themes/sylius_rtd_theme/layout.html
docs/api/index.rst
docs/api/unified_api/authorization.rst
docs/api/unified_api/index.rst
docs/api/unified_api/introduction.rst
docs/api/unified_api/map.rst.inc

[Docs] Create an unified section about all Sylius APIs

---

config/packages/security.yaml

If you would turn off new-api firewall, shop firewall catch new-api routing

[Api]Add new-api regexp to shop firewall

---

src/Sylius/Bundle/ApiBundle/ApiPlatform/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Country.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Zone.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml

[HOTFIX][API] Resolve subresource class parameters

---

src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js

change product translation tab opening behavior

---

src/Sylius/Behat/Context/Api/Admin/ManagingCountriesContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingZonesContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml

[Api] Fix hardcoded class constraints

---

docs/customization/controller.rst

Fix route id typo

---

src/Sylius/Behat/Context/Api/Shop/HomepageContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml

[Minor] Dead code removal

---

src/Sylius/Behat/Resources/config/suites.yml

[Minor] Sort api suites

---

composer.json

Still, I suppose fixed version will be released soon 🖖

[Hot-fix] Conflict SyliusFixturesBundle 1.6.0 to fix the build

---

src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/RegisterTaxCalculationStrategiesPass.php
src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/Compiler/RegisterTaxCalculationStrategiesPassTest.php
src/Sylius/Bundle/PaymentBundle/DependencyInjection/Compiler/RegisterPaymentMethodsResolversPass.php
src/Sylius/Bundle/PaymentBundle/Tests/DependencyInjection/Compiler/RegisterPaymentMethodsResolversPassTest.php
src/Sylius/Bundle/PaymentBundle/composer.json
src/Sylius/Bundle/PaymentBundle/phpunit.xml.dist
src/Sylius/Bundle/PayumBundle/DependencyInjection/Compiler/RegisterGatewayConfigTypePass.php
src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/RegisterPromotionActionsPass.php
src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/RegisterRuleCheckersPass.php
src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/RegisterPromotionActionsPassTest.php
src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/RegisterRuleCheckersPassTest.php
src/Sylius/Bundle/ShippingBundle/DependencyInjection/Compiler/RegisterCalculatorsPass.php
src/Sylius/Bundle/ShippingBundle/DependencyInjection/Compiler/RegisterShippingMethodsResolversPass.php
src/Sylius/Bundle/ShippingBundle/Tests/DependencyInjection/Compiler/RegisterCalculatorsPassTest.php
src/Sylius/Bundle/ShippingBundle/Tests/DependencyInjection/Compiler/RegisterShippingMethodsResolversPassTest.php
src/Sylius/Bundle/ShippingBundle/composer.json
src/Sylius/Bundle/ShippingBundle/phpunit.xml.dist
src/Sylius/Bundle/TaxationBundle/DependencyInjection/Compiler/RegisterCalculatorsPass.php
src/Sylius/Bundle/TaxationBundle/Tests/DependencyInjection/Compiler/RegisterCalculatorsPassTest.php
src/Sylius/Bundle/TaxationBundle/composer.json

Make compiler passes use all tags rather than the first tag

---

.travis.yml
behat.yml.dist
composer.json
config/packages/test_cached/doctrine.yaml
etc/travis/suites/application/before_install.sh
etc/travis/suites/application/before_script.sh
etc/travis/suites/application/script/test-behat-with-javascript
src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
src/Sylius/Behat/Page/Admin/Product/CreateConfigurableProductPage.php
src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
src/Sylius/Behat/Page/Admin/ShippingMethod/CreatePage.php
src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
src/Sylius/Behat/Page/Shop/Checkout/SelectPaymentPage.php
src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
src/Sylius/Behat/Page/Shop/Product/ShowPage.php
src/Sylius/Behat/Resources/config/services/contexts/ui.xml
src/Sylius/Behat/Service/AutocompleteHelper.php
src/Sylius/Behat/Service/JQueryHelper.php
src/Sylius/Behat/Service/Setter/CookieSetter.php
src/Sylius/Behat/Service/SlugGenerationHelper.php

[1.7] Travis Bionic + Chrome Headless + PHP 7.4 support

---

.travis.yml
behat.yml.dist
composer.json
config/packages/test_cached/doctrine.yaml
etc/travis/suites/application/before_install.sh
etc/travis/suites/application/before_script.sh
etc/travis/suites/application/script/test-behat-with-javascript
src/Sylius/Behat/Context/Api/Admin/ManagingExchangeRatesContext.php
src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
src/Sylius/Behat/Page/Admin/Product/CreateConfigurableProductPage.php
src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
src/Sylius/Behat/Page/Admin/ShippingMethod/CreatePage.php
src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
src/Sylius/Behat/Page/Shop/Checkout/SelectPaymentPage.php
src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
src/Sylius/Behat/Page/Shop/Product/ShowPage.php
src/Sylius/Behat/Resources/config/services/contexts/ui.xml
src/Sylius/Behat/Service/AutocompleteHelper.php
src/Sylius/Behat/Service/JQueryHelper.php
src/Sylius/Behat/Service/Setter/CookieSetter.php
src/Sylius/Behat/Service/SlugGenerationHelper.php
symfony.lock

- Moved from Ubuntu 14.04 (Trusty) to 18.04 (Bionic).
- Replaced Selenium + Chromedriver + Chrome with Chrome Headless for running JS Behat scenarios.
- Added support for PHP 7.4.
Closes #10994.
JS suite sped up from ~13m to ~8,5m.

Travis Bionic + Chrome Headless + PHP 7.4 support

---

src/Sylius/Behat/Resources/config/services/api.xml

[Minor][DX] Using parent definition for api clients

---

psalm.xml
src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php

| Related tickets | associated with #11520 

Fix Psalm errors

---

docs/cookbook/deployment/platform-sh.rst

[Docs][Plus] Add Docs with Sylius Plus deployment

---

src/Sylius/Bundle/UiBundle/Twig/SortByExtension.php

| Branch?         |  1.7
| Related tickets | #10676

Change function that orders grid fields

---

docs/cookbook/deployment/platform-sh.rst

[Docs][Plus] Missing information about authentication

---

composer.json

[Maintenance] Temporarily extend conflict to the ^2.5.5 versions of api-platform/core

---

features/cart/shopping_cart/adding_product_to_cart.feature
features/cart/shopping_cart/adding_products_with_quantity_to_cart.feature
src/Sylius/Behat/Client/ApiClientInterface.php
src/Sylius/Behat/Client/ApiPlatformClient.php
src/Sylius/Behat/Client/ApiPlatformIriClient.php
src/Sylius/Behat/Client/Request.php
src/Sylius/Behat/Client/RequestInterface.php
src/Sylius/Behat/Client/ResponseChecker.php
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Resources/config/services.xml
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/services/contexts/setup.xml
src/Sylius/Behat/Resources/config/suites/api/cart/shopping_cart.yml
src/Sylius/Behat/Service/ApiSecurityService.php
src/Sylius/Behat/Service/SprintfResponseEscaper.php
src/Sylius/Bundle/ApiBundle/Command/Cart/AddItemToCart.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/AddItemToCartHandler.php
src/Sylius/Bundle/ApiBundle/DataTransformer/AddItemToCartInputDataTransformer.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/AddItemToCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/AddItemToCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/AddItemToCartHandlerSpec.php

| Related tickets | Related to #11250, Replaces #11528

[API] Add simple item to cart

---

docs/components_and_bundles/components/Order/processors.rst

| Related tickets | fixes #9924

[Docs] Update order processor documentation

---

composer.json

| Related tickets | associated with https://github.com/symfony/symfony/issues/37027

[Maintenance] Add conflict to the 4.4.9 version of symfony/form

---

src/Sylius/Bundle/AdminBundle/Controller/DashboardController.php

fixed url to send valid key for channel

---

.travis.yml

[Travis] Fix deprecations in the config

---

features/taxonomy/managing_taxons/reordering_taxon.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
src/Sylius/Behat/Page/Admin/Taxon/CreatePageInterface.php

Behat for reordering taxon feature

---

etc/travis/suites/application/script/test-behat-with-javascript
src/Sylius/Behat/Client/ResponseChecker.php
src/Sylius/Behat/Client/ResponseCheckerInterface.php

Fix build and improve `getError()` more usable

[HOTFIX] Fix build

---

tests/Controller/ShippingMethodApiTest.php

[AdminApi] Add ShippingMethod authorization test

---

features/shipping/managing_shipping_methods/denying_access_to_shipping_methods_for_unauthorized_users.feature
src/Sylius/Behat/Client/ApiPlatformClient.php
src/Sylius/Behat/Client/ResponseChecker.php
src/Sylius/Behat/Client/ResponseCheckerInterface.php
src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php

[Api] Add test for checking access

---

etc/travis/suites/application/script/test-behat-with-javascript

Update from : https://github.com/Sylius/Sylius/pull/11560

[Travis] Update config on 1.7 with master

---

src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-chart.js
src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-statistics.js
src/Sylius/Bundle/AdminBundle/Resources/private/sass/_ui.scss
src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/Statistics/_template.html.twig

| Deprecations?   | not sure
TODO: Block possibility to move timeframe in future after the time we have today

switch timeframe on admin dashboard

---

src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_inventory.html.twig

| Related tickets | #11151
I've seen the changes done in (https://github.com/Sylius/Sylius/commit/186c13c25009904d00e322a2fb2259065099340b), but I guess that this file was missed.

Add Sylius template event

---

features/shipping/managing_shipping_methods/denying_access_to_shipping_methods_for_unauthorized_users.feature

| Related tickets | fixes https://github.com/Sylius/Sylius/pull/11517#discussion_r437880953

[Minor][Behat] Typo fix

---

UPGRADE-1.8.md

Little forget about the documentation related to the new API.
https://github.com/Sylius/Sylius/blob/c27fe6df9b347e32415765e52982620d53e00475/config/packages/security.yaml#L4

[Doc] change sylius.security.shop_regex in doc for new api

---

composer.json

[HotFix]Add symfony/form conflict

---

composer.json

| Related tickets | fixes https://github.com/Sylius/Sylius/pull/11578/files#r440238589

[Fix] Less strict symfony form conflict

---

src/Sylius/Bundle/AdminBundle/Resources/private/js/date-object-factory.js
src/Sylius/Bundle/AdminBundle/Resources/private/js/dateObjects/month-date-object.js
src/Sylius/Bundle/AdminBundle/Resources/private/js/dateObjects/week-date-object.js
src/Sylius/Bundle/AdminBundle/Resources/private/js/dateObjects/year-date-object.js
src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-statistics.js

Limit dashboard move on future dates

---

src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-statistics.js

fix left navigation arrow double click on admin statistics

---

src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-menu-search.js
src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_menu.html.twig

| New feature?    |yes
Adds a dynamic search input for the admin sidebar menu

[Admin] Make sidebar menu searchable

---

docs/cookbook/deployment/platform-sh.rst

| Related tickets | fixes #11574

[Docs] fix sylius plus deployment

---

src/Sylius/Bundle/ShopBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/_aboutUs.html.twig
src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/_latestProductsCarousel.html.twig
src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/_newsletter.html.twig

| Branch?         |  1.7
| Related tickets | fixes #11238

[Homepage] Change lorem ipsum description and fix carousel header

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml

[Api][Cart] Fix minor bug

---

features/order/managing_orders/order_filtration/filtering_orders_by_shipping_method.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
src/Sylius/Behat/Page/Admin/Order/IndexPage.php
src/Sylius/Behat/Page/Admin/Order/IndexPageInterface.php
src/Sylius/Bundle/AdminBundle/Resources/config/grids/order.yml

I've just added this filter because it's pretty simple to have and very handy!

Filter the orders grid on shipping method

---

features/checkout/addressing_order/returning_to_addressing_step_with_a_different_shipping_address.feature
src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php
src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/checkout.xml

When shipping and billing addresses are different
| Related tickets | fixes #11348

Check different shipping address field and display shipping address form

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionValue.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Province.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShopBillingData.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ZoneMember.xml

[API] Secure subresources' endpoints

---

composer.json
psalm.xml
src/Sylius/Bundle/ApiBundle/ApiPlatform/Bridge/Doctrine/ORM/SubresourceDataProvider.php
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml

| Related tickets | associated with https://github.com/api-platform/core/issues/3585

[Composer] Remove conflict to api-platform/core

---

features/cart/shopping_cart/removing_cart_item.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Setup/CartContext.php
src/Sylius/Behat/Context/Setup/ProductContext.php
src/Sylius/Behat/Context/Ui/Shop/CartContext.php
src/Sylius/Behat/Resources/config/services/contexts/setup.xml
src/Sylius/Behat/Resources/config/suites/api/cart/shopping_cart.yml
src/Sylius/Bundle/ApiBundle/Command/Cart/RemoveItemFromCart.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/RemoveItemFromCartHandler.php
src/Sylius/Bundle/ApiBundle/DataTransformer/RemoveItemFromCartDataTransformer.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/RemoveItemFromCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/RemoveItemFromCartHandlerSpec.php
src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderItemRepository.php
src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
src/Sylius/Component/Order/Repository/OrderItemRepositoryInterface.php
src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php

[Api][Cart] Cart remove items

---

src/Sylius/Component/Core/Model/ProductVariant.php
src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php

| Related tickets | fixes #11487, like as #11329

make product variant comparable

---

.github/PULL_REQUEST_TEMPLATE.md

Just a little hint to verify BC breaks when creating a new PR.

Add link to verify BC breaks in Pull request's template

---

.symfony.insight.yaml

| Related tickets | #11635
Let's update this :)
I've decided to use 7.4 because Sylius runs well on 7.4 and we want insights, it's not running the tests.

Update .symfony.insight.yaml to latest PHP version

---

.github/CONTRIBUTING.md

I would like to get more suggestions on Crowdin. So, maybe this will help?
At least a little bit.

Add mention about translation in CONTRIBUTING.md

---

features/cart/shopping_cart/clearing_cart.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Setup/CartContext.php
src/Sylius/Behat/Resources/config/services/contexts/setup.xml

[API][Behat] Usage of proper tense in background

---

src/Sylius/Bundle/AdminBundle/Resources/views/Customer/_form.html.twig
src/Sylius/Bundle/UserBundle/Form/Type/UserType.php
src/Sylius/Bundle/UserBundle/Resources/translations/messages.en.yml
tests/Responses/admin_user/create_validation_fail_response.json
tests/Responses/admin_user/update_validation_fail_response.json
tests/Responses/customer/create_with_user_validation_fail_response.json

| Deprecations?   | not sure
| Related tickets | fixes #9582
Field is disabled when user was verified before and shows only verification date

Add field where You can verify shop user

---

src/Sylius/Bundle/AdminBundle/Resources/views/Customer/_form.html.twig
src/Sylius/Bundle/UserBundle/Form/Type/UserType.php
src/Sylius/Bundle/UserBundle/Resources/translations/messages.en.yml
tests/Responses/admin_user/create_validation_fail_response.json
tests/Responses/admin_user/update_validation_fail_response.json
tests/Responses/customer/create_with_user_validation_fail_response.json

Reverts Sylius/Sylius#11642
Due to missing tests :(

Revert "Add field where You can verify shop user"

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml

We have a **PLN** in currencies and **pl_PL** in locales. We should have **PL** in countries as well 😄 🇵🇱

[Fixtures] Add Poland to fixtures

---

src/Sylius/Bundle/ApiBundle/Command/Cart/RemoveItemFromCart.php

[Minor] Remove final keyword

---

src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/SelectAttributeType.php
src/Sylius/Bundle/AttributeBundle/Tests/Form/Type/AttributeType/SelectAttributeTypeTest.php

Add default value if no translation exist on default local
| Related tickets | fixes #11149

Add default value on default local

---

src/Sylius/Bundle/ApiBundle/Command/Cart/PickupCart.php
src/Sylius/Bundle/ApiBundle/CommandHandler/PickupCartHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/PickupCartHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/PropertyInfo/Extractor/EmptyPropertyListExtractorSpec.php

[Minor] Move pickup cart command to proper namespace

---

src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-custom-collapse.js
src/Sylius/Bundle/AdminBundle/Resources/private/sass/_ui.scss

[Admin] Added collapse menu

---

src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_attributes.html.twig

[Product] add flags to product attributes translations

---

features/product/viewing_products/viewing_product.feature
src/Sylius/Behat/Client/ResponseChecker.php
src/Sylius/Behat/Client/ResponseCheckerInterface.php
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/product/viewing_products.yml
src/Sylius/Bundle/ApiBundle/DataProvider/ProductItemDataProvider.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
src/Sylius/Bundle/ApiBundle/spec/DataProvider/ProductItemDataProviderSpec.php

[Api][Product] Product show 

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml

Small fix for https://github.com/Sylius/Sylius/pull/11665

changed place of attribute tag

---

features/checkout/paying_for_order/paying_offline_during_checkout_as_guest.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/checkout/paying_for_order.yml
src/Sylius/Bundle/ApiBundle/Command/Checkout/ChoosePaymentMethod.php
src/Sylius/Bundle/ApiBundle/Command/Checkout/ChooseShippingMethod.php
src/Sylius/Bundle/ApiBundle/Command/Checkout/CompleteOrder.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChoosePaymentMethodHandler.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChooseShippingMethodHandler.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/CompleteOrderHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChoosePaymentMethodHandler.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChooseShippingMethodHandler.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/ChoosePaymentMethodHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/ChooseShippingMethodHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/CompleteOrderHandlerSpec.php

This pr is based on https://github.com/Sylius/Sylius/pull/11670

[API] Initial checkout implementation - fixes

---

src/Sylius/Bundle/ApiBundle/Command/Checkout/AddressOrder.php
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Serializer/AddressDenormalizer.php

[Api]Add AddressDenormalizer

---

features/cart/shopping_cart/changing_quantity_of_product_in_cart.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Ui/Shop/CartContext.php
src/Sylius/Bundle/ApiBundle/Command/Cart/ChangeItemQuantityInCart.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/ChangeItemQuantityInCartHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/ChangeItemQuantityInCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/ChangeItemQuantityInCartHandlerSpec.php

[Api][Cart] change quantity on cart

---

features/cart/shopping_cart/maintaining_cart_after_authorization.feature
features/cart/shopping_cart/maintaining_previous_cart_after_authorization.feature
src/Sylius/Behat/Client/ApiPlatformClient.php
src/Sylius/Behat/Client/ApiPlatformSecurityClient.php
src/Sylius/Behat/Client/ApiSecurityClientInterface.php
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/LoginContext.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Behat/Resources/config/suites/api/cart/shopping_cart.yml
src/Sylius/Bundle/ApiBundle/Context/TokenValueBasedCartContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/contexts.xml
src/Sylius/Bundle/ApiBundle/spec/Context/TokenValueBasedCartContextSpec.php
src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php

I've added `TokenValueBasedCartContext` with higher priority than other contexts to assign cart to a logged in customer by token value in `CartBlamerListener`

[API][Cart] Maintaining cart after authorization

---

features/checkout/addressing_order/filling_billing_and_shipping_address_details.feature
features/checkout/addressing_order/filling_shipping_and_billing_address_details_as_guest.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Bundle/ApiBundle/Command/Checkout/AddressOrder.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/AddressOrderHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/AddressOrder.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/AddressOrderHandlerSpec.php

[API] Filling also shipping address during checkout

---

src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/AddressOrderHandler.php

| Related tickets | fixes for review from #11714

[API] Minor fixes for filling shipping address during checkout

---

src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml

[Api][Checkout] Add checkout:read for order api serialization configuration

---

features/checkout/paying_for_order/selecting_order_payment_method.feature
features/checkout/shipping_order/selecting_order_shipping_method.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php

[API] Implement scenarios for selecting payment and shipping methods during checkout

---

features/checkout/skipping_shipping_step_when_only_one_shipping_method_is_available.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutPaymentContext.php
src/Sylius/Behat/Context/Ui/Shop/CheckoutContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Shipment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethodTranslation.xml

| Related tickets | based on #11705 

[Api] [Checkout] skipping shipment step

---

features/checkout/seeing_order_summary/seeing_total_tax_on_order_summary_page.feature
src/Sylius/Behat/Context/Api/Shop/OrderContext.php
src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml

[API]seeing total tax on order summary 

---

docs/customization/controller.rst

Unable to customize a Resource Controller by following docs.
Read more:
https://github.com/Sylius/Sylius/issues/9353
| Branch?         | 1.7 or master 

Fix docs for custom resource controllers

---

src/Sylius/Bundle/CoreBundle/spec/EventListener/DefaultUsernameORMListenerSpec.php

| Related tickets | #10951
I added spec as request in https://github.com/Sylius/Sylius/pull/11048

[Account] Add spec to sync username with customer email

---

src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_addToCart.html.twig

[Shop] Add form in add to cart template event args

---

features/product/viewing_product_in_admin_panel/viewing_details_of_simple_product.feature
src/Sylius/Behat/Context/Ui/Admin/ProductShowPageContext.php
src/Sylius/Behat/Page/Admin/Product/ShowPage.php
src/Sylius/Behat/Page/Admin/Product/ShowPageInterface.php
src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_breadcrumb.html.twig

| Related tickets | fixes #11374 
followed the proposed solution here #11374

[Product][Admin] Unify product breadcrumb in both show and update page

---

src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Setup/CartContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/services/contexts/setup.xml
src/Sylius/Bundle/ApiBundle/Command/Cart/AddItemToCart.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/AddItemToCartHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/AddItemToCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/AddItemToCartHandlerSpec.php

| Related tickets | partially #11250

[API] Add products by variant code

---

src/Sylius/Behat/Context/Transform/TaxonContext.php
src/Sylius/Behat/Resources/config/services/contexts/transform.xml

| Related tickets | fixes #11701 

[BEHAT] Injecting locale parameter instead of having it harcdoded

---

docs/book/architecture/events.rst

| Related tickets | mentioned in #11659

Add documentation for checkout initialize events

---

src/Sylius/Behat/Page/Admin/Payment/IndexPage.php
src/Sylius/Behat/Page/Admin/Shipment/ShowPage.php

[Behat] Unfinalize some Behat pages

---

src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipments.html.twig

| Related tickets | fixes #11649 

[Admin] removed duplicated id attribute

---

docs/customization/grid.rst

Added an example to add a field using events in the grid documentation

[Documentation] Add example to the grid documentation

---

features/cart/shopping_cart/adding_product_with_variants_to_cart.feature
features/product/viewing_products/viewing_product_variants_names.feature
src/Sylius/Behat/Client/ResponseChecker.php
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Context/Transform/ProductVariantContext.php
src/Sylius/Behat/Resources/config/services/contexts/transform.xml
src/Sylius/Behat/Resources/config/suites/api/cart/shopping_cart.yml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariantTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariantTranslation.xml

[API][Shop] Add possibility to show variants from product

---

features/cart/shopping_cart/adding_product_with_variants_to_cart.feature
src/Sylius/Behat/Client/ResponseChecker.php
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Transform/ProductVariantContext.php
src/Sylius/Behat/Resources/config/services/contexts/transform.xml
src/Sylius/Behat/Resources/config/suites/api/cart/shopping_cart.yml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariantTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariantTranslation.xml

 [API] Add configurable product to cart

---

docs/contributing/code/patches.rst
docs/contributing/documentation/overview.rst

[Documentation] bumped maintenance branches in docs

---

features/checkout/shipping_order/seeing_shipping_method_when_all_units_match_to_shipping_category.feature
features/checkout/shipping_order/seeing_shipping_method_when_at_least_one_unit_match_to_shipping_method.feature
features/checkout/shipping_order/seeing_shipping_method_when_no_units_match_to_shipping_category.feature
src/Sylius/Behat/Context/Setup/CartContext.php
src/Sylius/Behat/Context/Transform/CartTokenContext.php
src/Sylius/Behat/Context/Ui/Shop/CartContext.php
src/Sylius/Behat/Resources/config/services/contexts/transform.xml
src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml
src/Sylius/Bundle/ApiBundle/Command/Cart/PickupCart.php
src/Sylius/Bundle/ApiBundle/CommandHandler/PickupCartHandler.php

Its continue: https://github.com/Sylius/Sylius/pull/11735

[Api][Checkout] ShippingMethod on Checkout - complete scenarios

---

features/checkout/placing_an_order_with_different_scopes_for_shipping_and_taxes.feature
src/Sylius/Behat/Context/Api/Shop/OrderContext.php
src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml

[Api][Checkout] Placing order with difference scopes

---

src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Api/Shop/OrderContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml

[Api][Checkout] Placing order with difference scopes - minor fixes

---

features/checkout/seeing_order_summary/seeing_items_on_order_summary_page.feature
features/checkout/seeing_order_summary/seeing_order_locale.feature
features/checkout/seeing_order_summary/seeing_shipping_total_on_order_summary_page.feature
features/checkout/seeing_order_summary/seeing_summary_order_with_free_product.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariantTranslation.xml

[Api][Checkout] Order, shipping, promotion totals and order items on checkout summary

---

features/checkout/ability_to_confirm_an_order_with_a_promotion_on_shipping.feature
features/checkout/seeing_order_summary/seeing_discount_on_order_item_on_summary_page.feature
features/checkout/seeing_order_summary/seeing_shipping_discount_on_order_summary_page.feature
features/checkout/seeing_order_summary/seeing_summary_order_with_free_product.feature
features/checkout/seeing_order_summary/seeing_total_discount_on_order_summary_page.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Api/Shop/OrderContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Bundle/ApiBundle/DataProvider/OrderAdjustmentsSubresourceDataProvider.php
src/Sylius/Bundle/ApiBundle/DataProvider/OrderItemAdjustmentsSubresourceDataProvider.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Adjustment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Adjustment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
src/Sylius/Bundle/ApiBundle/spec/DataProvider/OrderAdjustmentsSubresourceDataProviderSpec.php
src/Sylius/Bundle/ApiBundle/spec/DataProvider/OrderItemAdjustmentsSubresourceDataProviderSpec.php
src/Sylius/Component/Order/Model/Adjustment.php
src/Sylius/Component/Order/Model/AdjustmentInterface.php
src/Sylius/Component/Order/spec/Model/AdjustmentSpec.php

[API][Checkout] Cover scenarios for checking promotions

---

src/Sylius/Behat/Context/Api/Shop/OrderContext.php
src/Sylius/Bundle/ApiBundle/DataProvider/OrderItemAdjustmentsSubresourceDataProvider.php
src/Sylius/Bundle/ApiBundle/spec/DataProvider/OrderAdjustmentsSubresourceDataProviderSpec.php

| Related tickets | fixes for review from #11749 

[API] Minor fixes for adjustments

---

src/Sylius/Behat/Context/Setup/ShippingContext.php
src/Sylius/Bundle/CoreBundle/Application/Kernel.php
src/Sylius/Component/Core/Shipping/Checker/Rule/OrderTotalRuleChecker.php
src/Sylius/Component/Core/spec/Shipping/Checker/Rule/OrderTotalGreaterThanOrEqualRuleCheckerSpec.php
src/Sylius/Component/Core/spec/Shipping/Checker/Rule/OrderTotalLessThanOrEqualRuleCheckerSpec.php

The shipping method rules for order totals wasn't working because of this bug.

Fix bug in order total shipping rules

---

UPGRADE-1.8.md

Updating the UPGRADE-1.8.md to reflect this change: https://github.com/Sylius/Sylius/commit/ae6cd148209de72447a2bbb5b49c42cf2f13ec94

Reflect admin path change in UPGRADE-1.8

---

composer.json

Just a tmp solution, as this is coming back into us for the forth time.

[Maintenance][HotFix] Conflict with Symofny/Form 4.4.12

---

src/Sylius/Behat/Client/ApiPlatformClient.php
src/Sylius/Behat/Client/Request.php
src/Sylius/Behat/Client/RequestInterface.php
src/Sylius/Behat/Context/Api/Admin/ManagingExchangeRatesContext.php
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Country.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CustomerGroup.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ExchangeRate.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Locale.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAssociationType.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAssociationTypeTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Province.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShopBillingData.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxCategory.xml

| Related tickets | part of #11250, based on #11776 

Api refactor simple entities part 1

---

adr/2020_05_13_handling_non_crud_operations_in_api.md

If the decision will be accepted in the current state, all state machine transitions should be moved from PATCH operations to POST. Shipping Method archiving operation may be left with PATCH, as it is idempotent.

[ADR] Custom operation in new Sylius API

---

composer.json

Add symfony form 4.4.13 conflict

---

adr/2020_09_01_admin_and_shop_split.md

[ADR] Path prefixes in new Sylius API

---

src/Sylius/Behat/Client/Request.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PaymentMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Shipment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingCategory.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethodTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Zone.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ZoneMember.xml

[API] refactor endpoint for api resources

---

composer.json
etc/travis/suites/common/before_install.sh
src/Sylius/Bundle/ReviewBundle/Form/Type/ReviewType.php

[Maintenance][Travis] Use composer 2.0

---

composer.json
src/Sylius/Bundle/ReviewBundle/Form/Type/ReviewType.php

| Related tickets | #11578, #11796, #11584, #11782 and https://github.com/symfony/symfony/issues/38039

[Maintenance] Drop Symfony/Form conflict and fix ReviewType configuration

---

composer.json

| Related tickets | https://github.com/Sylius/Sylius/pull/11798#discussion_r482797756
This version cannot be reached, as we are supporting Symfony ^4.4 only.

[Maintenance] Remove redundant conflict

---

config/bundles.php
config/packages/dev/nelmio_alice.yaml
config/packages/prod/routing.yaml
config/packages/test/nelmio_alice.yaml
config/packages/test/twig.yaml
config/packages/test/validator.yaml
symfony.lock

[Maintenance] Update composer, bundles and symfony lock

---

src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Component/Core/Factory/ChannelFactory.php
src/Sylius/Component/Core/Factory/ChannelFactoryInterface.php
src/Sylius/Component/Core/Test/Services/DefaultChannelFactory.php
src/Sylius/Component/Core/Test/Services/DefaultUnitedStatesChannelFactory.php
src/Sylius/Component/Core/spec/Factory/ChannelFactorySpec.php
src/Sylius/Component/Core/spec/Test/Services/DefaultChannelFactorySpec.php
src/Sylius/Component/Core/spec/Test/Services/DefaultUnitedStatesChannelFactorySpec.php

| Related tickets | fixes #11414 

set default value for Channel taxCalculationStrategy

---

bin/install-package

[Maintenance] Remove dead part of travis installation script

---

src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Setup/CheckoutContext.php
src/Sylius/Behat/Resources/config/services/contexts/setup.xml
src/Sylius/Bundle/ApiBundle/Command/Checkout/ChoosePaymentMethod.php
src/Sylius/Bundle/ApiBundle/Command/Checkout/ChooseShippingMethod.php
src/Sylius/Bundle/ApiBundle/Command/CommandAwareDataTransformerInterface.php
src/Sylius/Bundle/ApiBundle/Command/SubresourceIdAwareInterface.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChoosePaymentMethodHandler.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChooseShippingMethodHandler.php
src/Sylius/Bundle/ApiBundle/DataTransformer/CommandAwareInputDataTransformer.php
src/Sylius/Bundle/ApiBundle/DataTransformer/CommandDataTransformerInterface.php
src/Sylius/Bundle/ApiBundle/DataTransformer/CommandDataTransformersChain.php
src/Sylius/Bundle/ApiBundle/DataTransformer/CommandDataTransformersChainInterface.php
src/Sylius/Bundle/ApiBundle/DataTransformer/OrderTokenValueAwareInputCommandDataTransformer.php
src/Sylius/Bundle/ApiBundle/DataTransformer/SubresourceIdAwareCommandDataTransformer.php
src/Sylius/Bundle/ApiBundle/DependencyInjection/Compiler/CommandDataTransformerPass.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChoosePaymentMethodHandler.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChooseShippingMethodHandler.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/SyliusApiBundle.php
src/Sylius/Bundle/ApiBundle/Tests/DependencyInjection/Compiler/CommandDataTransformerPassTest.php
src/Sylius/Bundle/ApiBundle/composer.json
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/ChoosePaymentMethodHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/ChooseShippingMethodHandlerSpec.php

[Api][Checkout] Modify ShippingMethod and PaymentMethod paths on Checkout

---

psalm.xml
src/Sylius/Bundle/ApiBundle/ApiPlatform/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Resources/views/SwaggerUi/index.html.twig

[Api] Add experimental warning to swagger

---

features/cart/shopping_cart/allowing_access_only_for_correctly_logged_in_users.feature
features/cart/shopping_cart/clearing_cart_after_logging_out.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Api/Shop/LoginContext.php
src/Sylius/Behat/Context/Setup/AdminSecurityContext.php
src/Sylius/Behat/Context/Setup/CartContext.php
src/Sylius/Behat/Context/Setup/ShopSecurityContext.php
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/cart/accessing_cart.yml
src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderDeleteMethodItemExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderGetMethodItemExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderPatchMethodItemExtension.php
src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderDeleteMethodItemExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderGetMethodItemExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderPatchMethodItemExtensionSpec.php

[Api][Checkout] Allowing access only for correctly logged in

---

adr/2020_09_01_admin_and_shop_split.md

| Related tickets | https://github.com/Sylius/Sylius/pull/11789#pullrequestreview-481570608

[ADR] Minor text adjustments

---

features/cart/shopping_cart/allowing_access_only_for_correctly_logged_in_users.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Setup/CartContext.php

Fixes for: https://github.com/Sylius/Sylius/pull/11806

[Api][Checkout] Allowing access only for correctly logged in - minor fixes

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml

[Api] Hide token value in create cart endpoint's body

---

config/routes/sylius_shop.yaml
features/account/resetting_password_redirect.feature
src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
src/Sylius/Behat/Page/Shop/Account/WellKnownPasswordChangePage.php
src/Sylius/Behat/Page/Shop/Account/WellKnownPasswordChangePageInterface.php
src/Sylius/Behat/Resources/config/services/contexts/ui.xml
src/Sylius/Behat/Resources/config/services/pages/shop/account.xml

It's good to have this redirect and I think since it's possible to have it… then why not?
See https://web.dev/change-password-url/ for more details.
The goal is pretty simple here. We like safety at @MonsieurBiz :).
😗

Redirect /.well-known/change-password to the right page

---

src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml

[API] Hide product review in product create endpoint

---

features/taxonomy/managing_taxons/adding_taxon_for_with_parent.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_form.html.twig
src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonType.php

| Related tickets | fixes #11777

Fixed: Parent taxon selection on taxon creation

---

features/addressing/managing_countries/province_validation.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCountriesContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Province.xml

[API] Disable province code change in PUT endpoint

---

src/Sylius/Bundle/ProductBundle/Controller/ProductSlugController.php
src/Sylius/Bundle/UserBundle/Controller/SecurityController.php

| Related tickets | partially #10928 

Bugfix | Fixed wrong Symfony controller class usage

---

src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderGetMethodItemExtension.php

[Api][Cart] Fix for OrderGetMethodItemExtension

---

features/product/managing_product_variants/removing_product_variant_price_from_disabled_channel.feature
features/product/managing_products/removing_product_price_from_disabled_channel.feature
src/Sylius/Behat/Context/Setup/ProductContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
src/Sylius/Bundle/CoreBundle/Form/Type/Product/ChannelPricingType.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml

[ChannelPricing] Ability to remove price on channel pricing when channel is disabled

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml

[API] add missing prefix to payments route

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml

[API] fix route for pickup cart

---

features/product/managing_product_variants/removing_product_variant_price_from_obsolete_channel.feature
features/product/managing_products/removing_product_price_from_obsolete_channel.feature
src/Sylius/Bundle/CoreBundle/Form/Type/Product/ChannelPricingType.php

| Related tickets | fixes #11559 

[Admin] Channel pricing removal for channels where the product is not available

---

src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml

[Minor] Sort checkout contexts

---

features/cart/shopping_cart/allowing_access_only_for_correctly_logged_in_users.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Setup/CartContext.php

Down merge for : https://github.com/Sylius/Sylius/pull/11817

[Api][Checkout] Allowing access only for correctly logged in - minor fixes(1.8)

---

symfony.lock

Nothing much to say, some entries were missing.

Update symfony.lock with a few missing entries

---

src/Sylius/Behat/Context/Setup/ProductContext.php

[Behat] Remove duplicated method from ProductContext

---

CHANGELOG-1.8.md

| Bug fix?        | yes, kind of 😅
Thanks to @blankcheck and his message on Slack.

It's been only a few days guys!

---

features/checkout/seeing_order_summary/seeing_shipping_method_and_payment_method_on_order_summary_page.feature

[API] Added behat tag for seeing shipping and payment methods on summary

---

features/checkout/seeing_order_summary/seeing_addresses_on_order_summary_page.feature
features/checkout/seeing_order_summary/seeing_province_created_manually_on_order_summary_page.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml

[API]Seeing shipping and billing addresses on order summary page

---

app/migrations/Version20200916093101.php
features/product/managing_product_variants/adding_product_variant_with_only_original_price.feature
features/product/managing_product_variants/removing_product_variant_price_from_obsolete_channel.feature
features/product/managing_products/adding_product_with_only_original_price.feature
features/product/managing_products/removing_product_price_from_obsolete_channel.feature
src/Sylius/Behat/Context/Setup/ProductContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
src/Sylius/Bundle/CoreBundle/Form/Type/Product/ChannelPricingType.php
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ChannelPricing.orm.xml

[Product] Add possibility to create product/variant without price in disabled channels

---

UPGRADE-1.8.md

[Docs] Add changes in UPGRADE-1.8.md

---

features/checkout/addressing_order/choosing_province_for_country.feature
features/checkout/addressing_order/specifying_province_manually.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Bundle/ApiBundle/DataProvider/CountryCollectionDataProvider.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Country.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Country.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Province.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
src/Sylius/Bundle/ApiBundle/spec/DataProvider/CountryCollectionDataProviderSpec.php

[API] Implement choosing province during checkout

---

features/account/customer_account/viewing_orders_history/seeing_province_created_manually_in_order_history.feature
features/account/customer_account/viewing_orders_history/viewing_order_items.feature
features/account/customer_account/viewing_orders_history/viewing_order_items_with_proper_names.feature
features/account/customer_account/viewing_orders_history/viewing_payment_status_for_an_order.feature
features/account/customer_account/viewing_orders_history/viewing_shipment_status_on_a_placed_order_show_page.feature
src/Sylius/Behat/Context/Api/Shop/OrderContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/account/customer.yml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
src/Sylius/Component/Core/Formatter/StringInflector.php

[Api][Order]Viewing order details

---

UPGRADE-1.8.md
config/packages/security.yaml
src/Sylius/Behat/Client/ApiPlatformSecurityClient.php
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Resources/config/services.xml
src/Sylius/Behat/Service/ApiSecurityService.php
src/Sylius/Bundle/ApiBundle/Resources/config/routing.yml
src/Sylius/Bundle/ApiBundle/Swagger/AdminAuthenticationTokenDocumentationNormalizer.php
src/Sylius/Bundle/ApiBundle/Swagger/ShopAuthenticationTokenDocumentationNormalizer.php

[API] Separate providers for shop and admin users

---

src/Sylius/Bundle/CoreBundle/Migrations/Version20171003103916.php

| Related tickets | fixes #11843

Use DQL instead of repository to fetch product attributes

---

features/checkout/addressing_order/choosing_province_for_country.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Transform/ProvinceContext.php
src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml
src/Sylius/Bundle/AddressingBundle/Validator/Constraints/ProvinceAddressConstraintValidator.php
src/Sylius/Bundle/AddressingBundle/spec/Validator/Constraints/ProvinceAddressConstraintValidatorSpec.php

| Related tickets | related with #11889

[Address] Improve province validation

---

features/shipping/managing_shipments/filtering_shipments_by_shipping_method.feature
src/Sylius/Behat/Context/Api/Admin/ManagingShipmentsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
src/Sylius/Behat/Page/Admin/Shipment/IndexPageInterface.php
src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml

[Admin][API][Shipment] Add filtering shipments by a shipping method

---

features/account/customer_account/address_book/viewing_addresses.feature
features/account/customer_account/address_book/viewing_addresses_created_after_checkout.feature
features/checkout/addressing_order/choosing_billing_and_shipping_address_from_address_book.feature
src/Sylius/Behat/Context/Api/Shop/AddressContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Setup/AddressContext.php
src/Sylius/Behat/Context/Setup/ShopSecurityContext.php
src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/services/contexts/setup.xml
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/account/address_book.yml
src/Sylius/Bundle/ApiBundle/DataProvider/AddressCollectionDataProvider.php
src/Sylius/Bundle/ApiBundle/DataProvider/AddressItemDataProvider.php
src/Sylius/Bundle/ApiBundle/DataProvider/CustomerItemDataProvider.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Address.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
src/Sylius/Bundle/ApiBundle/spec/DataProvider/AddressCollectionDataProviderSpec.php
src/Sylius/Bundle/ApiBundle/spec/DataProvider/AddressItemDataProviderSpec.php
src/Sylius/Component/Core/Repository/AddressRepositoryInterface.php

[Api][Address] Browsing AddressBook

---

features/account/customer_account/address_book/deleting_address.feature
features/account/customer_account/address_book/deleting_address_created_after_checkout.feature
src/Sylius/Behat/Context/Api/Shop/AddressContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Address.xml

| Related tickets | partially #11914 ( this needs to be merged first)

[API]delete address book

---

features/cart/shopping_cart/adding_product_to_cart.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddItemToCart.xml

[Api] Add validation for add to cart command

---

.github/PULL_REQUEST_TEMPLATE.md

1.8 added to the branch options
| Branch?         | 1.7 or master 

Branch update

---

.github/PULL_REQUEST_TEMPLATE.md

| Branch?         | 1.7 or master 

Brunch update vol.2

---

docs/README.md

Updated Sylius description in documentation's README

---

src/Sylius/Bundle/ApiBundle/Command/CommandAwareDataTransformerInterface.php
src/Sylius/Bundle/ApiBundle/Command/SubresourceIdAwareInterface.php

[API] Add missing experimental annotations

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml

Nothing big… The whole file is using simple quotes, so I changed these 4 double quotes.
Code quality comes from small changes.

Keep it consistent with simple quotes

---

features/account/customer_account/editing_customer_profile.feature

During up merge I've removed this feature by accident.

[API] Add removed feature

---

src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutOrderDetailsContext.php

Delete redundant steps

---

docs/book/organization/release-cycle.rst

[Docs] Announce 1.9 release period

---

src/Sylius/Bundle/AdminApiBundle/Fixture/Factory/ApiAccessTokenExampleFactory.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/AddressExampleFactory.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/OrderExampleFactory.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAssociationExampleFactory.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductReviewExampleFactory.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingMethodExampleFactory.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxRateExampleFactory.php
src/Sylius/Bundle/CoreBundle/Fixture/OptionsResolver/LazyOption.php
src/Sylius/Bundle/CoreBundle/Fixture/OptionsResolver/ResourceNotFoundException.php
src/Sylius/Bundle/CoreBundle/Tests/Fixture/OptionsResolver/LazyOptionTest.php

[Fixture] Add getOneBy method to LazyOption

---

src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
src/Sylius/Bundle/AdminApiBundle/SectionResolver/AdminApiUriBasedSectionResolver.php
src/Sylius/Bundle/AdminBundle/SectionResolver/AdminUriBasedSectionResolver.php
src/Sylius/Bundle/CoreBundle/Form/Type/Product/ChannelPricingType.php
src/Sylius/Bundle/CoreBundle/SectionResolver/SectionCannotBeResolvedException.php
src/Sylius/Bundle/CoreBundle/SectionResolver/UriBasedSectionProvider.php
src/Sylius/Bundle/ShopBundle/SectionResolver/ShopUriBasedSectionResolver.php
src/Sylius/Bundle/ShopBundle/spec/SectionResolver/ShopUriBasedSectionResolverSpec.php
src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonType.php

Minor CS fixes detected by ECS

---

src/Sylius/Bundle/CoreBundle/Resources/views/Collector/cart.html.twig
src/Sylius/Bundle/CoreBundle/Resources/views/Common/Macro/money.html.twig

| Related tickets | fixes #11918

[Core] Decouple cart collector from shop

---

features/account/customer_account/address_book/setting_default_address.feature
src/Sylius/Behat/Context/Api/Shop/AddressContext.php
src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml

[API][AddressBook] Setting default address

---

src/Sylius/Behat/Context/Api/Shop/AddressContext.php

[API][AddressBook] Minor fixes to api behats

---

composer.json

| Related tickets | partially fix #11970 

[Maintenance] Conflict symfony doctrine bridge

---

features/channel/managing_channels/adding_channel.feature
features/channel/managing_channels/channel_validation.feature
src/Sylius/Behat/Context/Api/Admin/ManagingChannelsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
src/Sylius/Behat/Page/Admin/Channel/CreatePage.php
src/Sylius/Behat/Page/Admin/Channel/CreatePageInterface.php
src/Sylius/Bundle/AdminBundle/Resources/views/Channel/_form.html.twig
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Channel.xml
src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
src/Sylius/Bundle/CoreBundle/Form/Extension/ChannelTypeExtension.php
src/Sylius/Bundle/CoreBundle/Migrations/Version20201017150005.php
src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_support.html.twig
src/Sylius/Component/Core/Model/Channel.php
src/Sylius/Component/Core/Model/ChannelInterface.php
src/Sylius/Component/Core/spec/Model/ChannelSpec.php
tests/Controller/ChannelApiTest.php
tests/Responses/channel/create_validation_fail_response.json
tests/Responses/channel/update_validation_fail_response.json

| Related tickets | mentioned in #11886
Add channel contact phone number
Duplicate of #11943 (Fucked up the rebase process 😭 )

[Core][Channel] Add contact phone number to channel

---

features/promotion/receiving_discount/applying_only_promotions_enabled_for_given_channel.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/promotion/receiving_discount.yml

[API] Seeing promotions total in cart

---

UPGRADE-1.9.md
config/packages/security.yaml
features/account/customer_account/address_book/preventing_not_logged_user_from_operations_on_address_book.feature
features/account/customer_account/address_book/viewing_addresses.feature
features/account/customer_account/address_book/viewing_empty_address_book.feature
src/Sylius/Behat/Context/Api/Shop/AddressContext.php
src/Sylius/Behat/Context/Transform/AddressContext.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Bundle/ApiBundle/DataProvider/AddressItemDataProvider.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Address.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml

[API][AddressBook] Protect addresses with new firewall

---

src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml

[Minor] Update service definition to not using depracated service

---

src/Sylius/Behat/Context/Ui/Admin/ProductShowPageContext.php
src/Sylius/Behat/Context/Ui/Shop/LocaleContext.php

[Behat] Fix argument name after upgrade Behat to v3.8.0

---

composer.json

| Related tickets | Mentioned in https://github.com/Sylius/Sylius/pull/11694#issuecomment-720369247

Remove nikic/php-parser as a conflict

---

composer.json
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Address.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml

| Related tickets | this task extends #11973

[API]added missing serialization to address editing endpoint

---

composer.json
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Address.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml

Revert "[API]added missing serialization to address editing endpoint"

---

composer.json
docs/cookbook/shipping-methods/custom-shipping-method-rule.rst
src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/OrderProductEligibilityValidator.php
src/Sylius/Component/Shipping/Checker/Eligibility/CategoryRequirementEligibilityChecker.php
src/Sylius/Component/Shipping/Checker/Eligibility/CompositeShippingMethodEligibilityChecker.php
src/Sylius/Component/Shipping/Checker/Eligibility/ShippingMethodRulesEligibilityChecker.php
src/Sylius/Component/Shipping/Checker/ShippingMethodEligibilityChecker.php
src/Sylius/Component/Shipping/Checker/ShippingMethodEligibilityCheckerInterface.php
symfony.lock

[Maintenance] Bump psalm, fix naming issues and build

---

src/Sylius/Bundle/ApiBundle/Validator/Constraints/OrderPaymentMethodEligibilityValidator.php

[Maintenance] Fix naming issues after psalm bump

---

src/Sylius/Behat/Context/Api/Admin/ManagingAdministratorsContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingCountriesContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingCurrenciesContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingCustomerGroupsContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingExchangeRatesContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingLocalesContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingProductAssociationTypesContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingProductOptionsContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingProductReviewsContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingProductVariantsContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingShipmentsContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingShippingCategoriesContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingTaxCategoriesContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingTaxonsContext.php
src/Sylius/Behat/Context/Api/Admin/ManagingZonesContext.php
src/Sylius/Behat/Context/Api/Shop/AddressContext.php
src/Sylius/Behat/Context/Api/Shop/CustomerContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml

Done: 1. changed deprecated classes
2. moved 'given' steps on top
3. fixed or improved functions
4.merged same steps in one
5.added return type to functions

[API][Behat]refactor api admin context

---

src/Sylius/Bundle/ApiBundle/Command/ChangeShopUserPassword.php
src/Sylius/Bundle/ApiBundle/CommandHandler/ChangeShopUserPasswordHandler.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/CorrectChangeShopUserConfirmPasswordValidator.php

[API] Fix names in change password command

---

UPGRADE-1.8.md

I had this issue during two upgrades. I think it's worth saying!

Note about disabled product variants and taxons

---

docs/cookbook/shipping-methods/custom-shipping-method-rule.rst

Just a little documentation fix :).

Use the correct variable

---

features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_expiration_date.feature
src/Sylius/Behat/Context/Api/Shop/PromotionContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/promotion/applying_promotion_coupon.yml
src/Sylius/Bundle/ApiBundle/Command/Cart/ApplyCouponToCart.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/ApplyCouponToCartHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/ApplyCouponToCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/ApplyCouponToCartHandlerSpec.php

[API]adding promotions with expire date

---

docs/components_and_bundles/bundles/SyliusTaxationBundle/calculating_taxes.rst

Small update to taxation's doc

[DOC] Update calculating_taxes.rst

---

UPGRADE-1.8.md
config/packages/security.yaml

Use proper parameters in access control patterns

---

.github/PULL_REQUEST_TEMPLATE.md

Update Github PR template

---

UPGRADE-1.8.md

| Bug fix?        | kind of
I really didn't know how to write such thing. It's really difficult to understand actually.
cc @Zales0123

Add some explanations about the stocks issue

---

src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderMethodsItemExtensionSpec.php

| Related tickets | after https://github.com/Sylius/Sylius/pull/11895

[API] Fix PHPSpec of order query extension after upmerge

---

adr/2020_11_12_registration_of_handlers_in_message_buses.md
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml

[Minor][ADR] Explicit bus declaration on handlers

---

docs/book/orders/orders.rst
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml

| Related tickets | fixes #10740

Introduce limit parameter for quantity modifier

---

src/Sylius/Behat/Context/Api/Shop/PromotionContext.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/ApplyCouponToCartHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/validation/ApplyCouponToCart.xml

| Related tickets | fixes to #12025

[API]fixes to `adding promotions with expire date`

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php

[Order] Change localisation of findCartByTokenValue function

---

src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/OrderContext.php
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Bundle/ApiBundle/DataProvider/ProductItemDataProvider.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/spec/DataProvider/ProductItemDataProviderSpec.php
src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php

| Related tickets | based on https://github.com/Sylius/Sylius/pull/11925

[API][Product] Change identifier for shop endpoint from slug to code

---

src/Sylius/Behat/Context/Api/Shop/OrderContext.php
src/Sylius/Behat/Context/Api/Shop/OrderItemContext.php
src/Sylius/Behat/Context/Api/Shop/PaymentContext.php
src/Sylius/Behat/Context/Api/Shop/ShipmentContext.php
src/Sylius/Bundle/ApiBundle/ApiPlatform/Bridge/Symfony/Routing/RouteNameResolver.php
src/Sylius/Bundle/ApiBundle/DataProvider/OrderItemItemDataProvider.php
src/Sylius/Bundle/ApiBundle/DataProvider/OrderItemUnitItemDataProvider.php
src/Sylius/Bundle/ApiBundle/DataProvider/PaymentItemDataProvider.php
src/Sylius/Bundle/ApiBundle/DataProvider/ShipmentItemDataProvider.php
src/Sylius/Bundle/ApiBundle/spec/DataProvider/OrderItemItemDataProviderSpec.php
src/Sylius/Bundle/ApiBundle/spec/DataProvider/OrderItemUnitItemDataProviderSpec.php
src/Sylius/Bundle/ApiBundle/spec/DataProvider/PaymentItemDataProviderSpec.php
src/Sylius/Bundle/ApiBundle/spec/DataProvider/ShipmentItemDataProviderSpec.php
src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderItemRepository.php
src/Sylius/Component/Core/Repository/OrderItemRepositoryInterface.php

| Related tickets | fixes after https://github.com/Sylius/Sylius/pull/11925

[API] Fixes after PR with resolving proper iri in different contexts

---

UPGRADE-1.9.md
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml

| Related tickets | after #12034 

[API][Product] Add note in UPGRADE file about changing identifier for shop endpoint

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Address.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Country.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml

| Related tickets | after https://github.com/Sylius/Sylius/pull/11925

[API] Add missing endpoints for address and country resources

---

src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml

[Minor] Inject proper order processor

---

docs/api/index.rst

Added info about JWT token generation required to use API.
| Branch?         | 1.8 and master

info about JWT token generation required

---

adr/2020_11_18_sending_emails_via_api.md

[ADR] Sending emails via api

---

src/Sylius/Behat/Context/Setup/PromotionContext.php

Done: add missing return types, add missing variable type, minor improvements

[Behat]refactor of setup/PromotionContext class

---

features/checkout/preventing_cart_from_being_modified_after_checkout.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php

Step was badly implemented, it was adding the items, not changing quantity. It is fixed here.

[API][Behat] fixed steps for quantity-change api test

---

composer.json

| Branch?         | master (dependency update, not sure if bug fix or new feature)
| Bug fix?        | not really
| New feature?    | not really
| Related tickets | Fixes #12072

Replace fzaninotto/faker with fakerphp/faker

---

features/promotion/receiving_discount/receiving_discount_from_promotion_with_multiple_actions.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml

[Api] Receiving discount promotion

---

src/Sylius/Bundle/AttributeBundle/DependencyInjection/Compiler/RegisterAttributeFactoryPass.php

| Related tickets | fixes https://github.com/Sylius/Sylius/issues/12051

#12051 fix attribute registry initialized twice

---

features/promotion/receiving_discount/receiving_percentage_discount_on_items_on_price_range.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php

This PR is based on https://github.com/Sylius/Sylius/pull/12081

[Api] Receiving percentage discount

---

config/packages/test/security.yaml
config/packages/test_cached/security.yaml
tests/Functional/UpdatingUserPasswordEncoderTest.php

Use sha512 to encode passwords in test environments

---

.github/workflows/application.yml

Thanks to @oallain suggestion in #12090.

[CI] Uploade Behat logs as artifacts if failed

---

.github/workflows/application.yml
.github/workflows/packages.yml

Thanks to @stof comments in #12090 and #12089.

[CI] GitHub Actions setup improvements

---

src/Sylius/Bundle/CoreBundle/Form/Type/Product/ChannelPricingType.php

Having the red star next to the label makes me crazy :p.

Original price is not required in UI

---

composer.json
src/Sylius/Component/Channel/composer.json
src/Sylius/Component/Channel/spec/Context/CachedPerRequestChannelContextSpec.php

Now I can abandon that library :tada:

Remove pamil/prophecy-common from require-dev dependencies

---

src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
src/Sylius/Behat/Resources/config/services.xml
src/Sylius/Behat/Resources/config/services/contexts/ui.xml
src/Sylius/Behat/Service/Helper/JavaScriptTestHelperInterface.php

Continuation of #12114
Looks like some tests needs more time.

[Behat] Introduce test helper for more JS tests and increase timeout

---

UPGRADE-1.8.md
config/packages/security.yaml

| Bug fix?        | no, not really
Since we had the same change in the `access_control`, I've done it in the firewalls as well.
😘
_I'm not sure about the UPGRADE-1.8.md actually. Changing the version number is maybe not the best thing to do._

Change route prefixes in security.yaml

---

src/Sylius/Bundle/AdminApiBundle/composer.json
src/Sylius/Bundle/CoreBundle/composer.json

[AdminApiBundle][CoreBundle] Update unit test versions

---

src/Sylius/Bundle/AdminApiBundle/composer.json
src/Sylius/Bundle/CoreBundle/composer.json

| Related tickets | after #12060 

[Maintenance] Move dependency from require-dev to require in CoreBundle and AdminApiBundle composers

---

src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml

Part one: changed CheckoutContext to use ApiClientInterface.
Todo: 
- refactor CartContext (if needed) 🚀 
- review and merge/split behat steps 🏎️ 
- search for code performance issues that left 🔍

[Behat] refactor of cart and checkout contexts

---

features/checkout/prevent_skipping_checkout_steps.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php

[API] prevent checkout skipping shipping step

---

features/shipping/applying_shipping_method_rules/viewing_available_shipping_methods_based_on_order_total.feature
features/shipping/applying_shipping_method_rules/viewing_available_shipping_methods_based_on_total_weight.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/shipping/applying_shipping_method_rules.yml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml

[API] show possible shipping methods for order

---

features/checkout/adding_product_with_promotion_that_makes_the_order_free.feature

| Related tickets | #11547
This is continuation of #11547

Add behat scenario with free order

---

features/checkout/prevent_skipping_checkout_steps.feature

Add tag no-api to scenario

---

features/checkout/shipping_order/seeing_shipping_fee_on_multiple_channels.feature
src/Sylius/Behat/Context/Setup/CartContext.php

[Api][Checkout] Shipping fees on multi-channel

---

UPGRADE-1.9.md

| Related tickets | This PR is related to failing build from sylius/standard https://github.com/Sylius/Sylius-Standard/pull/459 and also #12116

update upgrade file after changes with tax adjustment

---

features/currency/switching_current_currency.feature
src/Sylius/Behat/Context/Api/Shop/ChannelContext.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/currency/currencies.yml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Currency.xml

[Api] Check currency on channel

---

features/cart/shopping_cart/viewing_cart_summary.feature
features/product/viewing_products/accessing_product_wich_does_not_exist.feature
features/promotion/receiving_discount/receiving_discount_from_promotion_with_multiple_actions.feature
features/promotion/receiving_discount/receiving_fixed_discount_on_items_on_price_range.feature
features/promotion/receiving_discount/receiving_fixed_discount_on_products_from_specific_taxon.feature
features/promotion/receiving_discount/receiving_fixed_discount_on_specific_products.feature
features/promotion/receiving_discount/receiving_percentage_discount_on_items_on_price_range.feature
features/promotion/receiving_discount/receiving_percentage_discount_on_products_from_specific_taxon.feature
features/promotion/receiving_discount/receiving_percentage_discount_on_specific_products.feature
features/promotion/receiving_discount/receiving_stacked_promotions_with_changing_context.feature

[Promotions] Replace wrong names

---

features/promotion/managing_promotions/browsing_promotions.feature
src/Sylius/Behat/Context/Api/Admin/ManagingPromotionsContext.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/promotion/managing_promotions.yml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Promotion.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Promotion.xml

[API] Browsing promotions

---

src/Sylius/Bundle/CoreBundle/Twig/FilterExtension.php

[BugFix] Add missing argument in metchod

---

features/promotion/managing_promotions/deleting_promotion.feature
src/Sylius/Behat/Context/Api/Admin/ManagingPromotionsContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Promotion.xml

[API] deleting promotions

---

UPGRADE-1.8.md
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AdminUser.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AvatarImage.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Country.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/AdminUser.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/AvatarImage.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Account/ChangePasswordShopUser.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Account/RegisterShopUser.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Country.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Currency.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Province.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShopBillingData.xml

[Api][AdminUser][AvatarImage][Channel][Currency][Customer] Refactor api serialization groups

---

UPGRADE-1.8.md
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/AddItemToCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/ApplyCouponToCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/ChangeItemQuantityInCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/PickupCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/RemoveItemFromCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/AddressOrder.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChoosePaymentMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChooseShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/CompleteOrder.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Payment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PaymentMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariantTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Shipment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethodTranslation.xml

[Api][Order] Refactor api serialization groups

---

features/checkout/seeing_purchaser_identifier_in_checkout_page.feature
src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php

[Behat][Minor] Step rephrasing to decouple from UI

---

composer.json
src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
src/Sylius/Bundle/CoreBundle/Form/Extension/LocaleTypeExtension.php
src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
src/Sylius/Component/Core/Customer/Statistics/CustomerStatistics.php
src/Sylius/Component/Core/Customer/Statistics/CustomerStatisticsProvider.php
src/Sylius/Component/Taxation/Model/TaxRate.php
src/Sylius/Component/User/Model/User.php

Upgrade psalm

---

composer.json

| Related tickets | related #10928 + https://github.com/Sylius/SyliusResourceBundle/pull/135

Allow newer "doctrine/doctrine-bundle" to match upcoming ResourceBundle reqs

---

.github/workflows/application.yml
CONFLICTS.md
composer.json

Remove laminas/laminas-code conflict

---

UPGRADE-1.8.md
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductImage.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTranslation.xml

[Api][Product] Refactor api serialization groups

---

UPGRADE-1.8.md
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/OrderItemUnit.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItemUnit.xml

[Api][OrderItem][OrderItemUnit] Refactor api serialization groups

---

features/checkout/ability_to_change_email_during_checkout.feature
src/Sylius/Behat/Context/Ui/Shop/CheckoutContext.php
src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php
src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php
src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_form.html.twig

[BUG-FIX] [Checkout] Change email addressing step

---

UPGRADE-1.8.md
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Address.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Adjustment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AdminUser.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AvatarImage.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Country.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CustomerGroup.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ExchangeRate.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Locale.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PaymentMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Adjustment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ExchangeRate.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Locale.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Payment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PaymentMethod.xml

[Api][Adjustment][CustomerGrouop][ExchangeRate][Locale][Payment][PaymentMethod] Refactor api serialization groups

---

src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_breadcrumb.html.twig
src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/_horizontalMenu.html.twig

| Branch?         | 1.7, 1.8 or master 

[Bug] Add Twig verification to check is taxon is enabled

---

features/order/managing_orders/order_details/seeing_order_shipping_taxes.feature
src/Sylius/Component/Core/OrderProcessing/OrderTaxesProcessor.php
src/Sylius/Component/Core/spec/OrderProcessing/OrderTaxesProcessorSpec.php

| Related tickets | after https://github.com/Sylius/Sylius/pull/12116 and associated with https://github.com/Sylius/RefundPlugin/pull/242

[OrderProcessor] Fix clearing tax adjustments

---

UPGRADE-1.8.md

Make upgrade of serializations easier to read

---

docs/book/products/attributes.rst
src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAttributeExampleFactory.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
src/Sylius/Bundle/CoreBundle/Fixture/ProductAttributeFixture.php
src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/dress.yaml
src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/tshirt.yaml

| Related tickets | fixtures + doc for https://github.com/Sylius/Sylius/pull/12098

Ability to create non-translatable attributes fixtures + info about non-translatable attributes.

---

docs/book/products/attributes.rst

| Related tickets | https://github.com/Sylius/Sylius/pull/12256#discussion_r559579760

[Minor][Documentation] Improve attribute documentation

---

src/Sylius/Bundle/CoreBundle/Migrations/Version20201208105207.php

| Related tickets | after https://github.com/Sylius/Sylius/pull/12116
According to https://github.com/Sylius/RefundPlugin/pull/242#discussion_r559525414

[Migrations] Use adding SQL instead of query execution

---

.github/workflows/auto-merge.yml

It already works on Sylius-Standard https://github.com/Sylius/Sylius-Standard/pull/479 🎉

Auto-merge passing dependabot PRs

---

UPGRADE-1.9.md

[Docs] Add steps to upgrade jms configuration in UPGRADE-1.9 file

---

src/Sylius/Bundle/CoreBundle/EventListener/UserCartRecalculationListener.php
src/Sylius/Bundle/CoreBundle/spec/EventListener/UserCartRecalculationListenerSpec.php
src/Sylius/Bundle/UserBundle/Controller/UserController.php
src/Sylius/Bundle/UserBundle/Event/UserEvent.php
src/Sylius/Bundle/UserBundle/Security/UserLogin.php
src/Sylius/Bundle/UserBundle/spec/EventListener/UpdateUserEncoderListenerSpec.php
src/Sylius/Bundle/UserBundle/spec/EventListener/UserLastLoginSubscriberSpec.php
src/Sylius/Bundle/UserBundle/spec/Security/UserLoginSpec.php

| Related tickets | partially #10928 

Fix event deprecations

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Commands/RegisterShopUser.xml

Caused by this change https://github.com/api-platform/core/pull/3871
| Related tickets | https://github.com/api-platform/core/pull/3871

Fix no identifier defined error in ApiPlatform 2.6

---

CONFLICTS.md
composer.json

Temporary fix for all the failing installations.

Add conflict with api-platform/core:^2.6

---

docs/book/customers/admin_user.rst

[Docs] fix for admin RBAC channels

---

CONFLICTS.md
composer.json
docs/api/admin_api/locales.rst
src/Sylius/Behat/Context/Api/Admin/ManagingLocalesContext.php
src/Sylius/Bundle/CoreBundle/Command/CancelUnpaidOrdersCommand.php
src/Sylius/Bundle/CoreBundle/Command/InstallCommand.php
src/Sylius/Bundle/CoreBundle/Migrations/Version20171003103916.php
src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
tests/Responses/locale/create_validation_fail_response.json

[Psalm] Fix build by casting to string in sprintf methods

---

features/product/viewing_products/viewing_product_price_on_products_list.feature
features/product/viewing_products/viewing_products_price.feature
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/product/viewing_products.yml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ChannelPricing.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ChannelPricing.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml

[API] show product price

---

src/Sylius/Bundle/ApiBundle/DataTransformer/CommandAwareInputDataTransformer.php
src/Sylius/Bundle/ApiBundle/spec/DataTransformer/CommandAwareInputDataTransformerSpec.php

[Api] Fix CommandAwareInputDataTransformer

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml

Fix Taxon collection API name

---

docs/book/contributing/documentation/overview.rst

Its because `sensio.sphinx.configurationblock` and `sensio.sphinx.phpcode` are locked on `Sphinx v1.8.5`

[Docs] Upgrade sphinx installation guide

---

UPGRADE-1.8.md
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Shipment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingCategory.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShopBillingData.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxCategory.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxonTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Zone.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ZoneMember.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/AddItemToCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/PickupCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChoosePaymentMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Checkout/ChooseShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Shipment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingCategory.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShippingMethodTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ShopBillingData.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxCategory.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Taxon.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxonTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/View/CartShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Zone.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ZoneMember.xml

[Api][ShippingMethod][ShopBillingData][TaxCategory][Taxon][TaxonTranslation][Zone][ZoneMemberRefactor] serializations groups 

---

.github/workflows/application.yml
phpstan.neon.dist

Putting everything in the config file.

Update PHPStan configuration

---

.github/workflows/application.yml

We have no composer.lock in the repo.

Remove lock file from cache hashes in CI

---

UPGRADE-1.9.md
config/packages/security.yaml
src/Sylius/Bundle/AdminApiBundle/Resources/config/app/config.yml
src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml

[API] move security parameters to bundles

---

.github/workflows/application.yml

We don't need to trigger application build if we only change ADRs.

[CI] Ignore changes in "adr" directory

---

UPGRADE-1.9.md

Fix the appearance of the UPGRADE-1.9 file

---

UPGRADE-1.9.md

Change the order of sections in the UPGRADE-1.9 file

---

src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/CircularDependencyBreakingErrorListenerPass.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/CircularDependencyBreakingErrorListenerPassTest.php

fix problem with registered service

---

UPGRADE-1.9.md

Add note about removing Twig route config in the UPGRADE-1.9 file

---

UPGRADE-1.9.md

Reorganize UPGRADE-1.9 file to extract steps for Symfony v5.2

---

composer.json

Change package type from "project" to "library"

---

features/promotion/applying_promotion_coupon/removing_promotion_coupon.feature
src/Sylius/Behat/Context/Api/Shop/PromotionContext.php
src/Sylius/Behat/Context/Setup/CartContext.php
src/Sylius/Behat/Resources/config/suites/api/promotion/applying_promotion_coupon.yml
src/Sylius/Bundle/ApiBundle/Command/Cart/ApplyCouponToCart.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/ApplyCouponToCartHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/validation/ApplyCouponToCart.xml
src/Sylius/Bundle/ApiBundle/Validator/Constraints/PromotionCouponEligibilityValidator.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/ApplyCouponToCartHandlerSpec.php

[API] remove promotion coupon

---

UPGRADE-1.9.md

Fixes according to composer require commands in the UPGRADE-1.9 file

---

README.md

We are working on a new road mapping process and structure, so let's hide this for now and bring it back when it is ready.

Remove roadmap links for now

---

docs/cookbook/entities/custom-model.rst

[Doc] remove generator bundle info (deprecated)

---

composer.json
src/Sylius/Bundle/ApiBundle/Resources/views/SwaggerUi/index.html.twig

[Frontend] add box with info about api identifiers

---

.github/workflows/application.yml

[Maintenance] Run test suite for MySQL 8.0

---

src/Sylius/Bundle/ApiBundle/Resources/views/SwaggerUi/index.html.twig

change swagger API info color to blue

---

composer.json
symfony.lock

Remove unneeded zendframework/zend-hydrator dependency

---

src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ChannelPricing.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml

[API] change variants to iri + tests

---

src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantSerializer.php
src/Sylius/Bundle/ApiBundle/Swagger/ProductVariantDocumentationNormalizer.php

ProductVariant returns additional key "price" which is calculated with ProductVariantPriceCalculator

[API] ProductVariant serialization with new key "price"

---

features/checkout/placing_order_on_multi_channel/placing_an_order_on_a_single_channel_store.feature

First excluded scenario from API coverage, to inform that it will not be handled via API

[API] Explicitly exclude feature from API implementation

---

src/Sylius/Bundle/ApiBundle/composer.json
src/Sylius/Bundle/ApiBundle/test/config/api_resources/Taxon.xml
src/Sylius/Bundle/ApiBundle/test/config/bundles.php
src/Sylius/Bundle/ApiBundle/test/src/Tests/TaxonTest.php

[ApiBundle] Fixes in test application

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantSerializer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantSerializerSpec.php

[API] add missing spec

---

src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantSerializer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantSerializerSpec.php

Minor fixes and CS

---

docs/customization/model.rst

[Docs] Add note about doctrine migrations

---

src/Sylius/Bundle/ApiBundle/composer.json
src/Sylius/Bundle/ApiBundle/test/src/Tests/SetUpTestsTrait.php
src/Sylius/Bundle/CoreBundle/Tests/TestKernel.php

| Bug fix?        | yes, kind of

Remove duplicated entry in composer file and add return type in setup trait

---

src/Sylius/Bundle/ApiBundle/phpunit.xml.dist
src/Sylius/Bundle/ApiBundle/test/config/fixtures/foo_sylius_resource.yaml
src/Sylius/Bundle/ApiBundle/test/src/Tests/FooSyliusResourceTest.php

[ApiBundle] Improve tests for custom Sylius resource in test application

---

src/Sylius/Bundle/ApiBundle/ApiPlatform/Bridge/Symfony/Routing/RouteNameResolver.php
src/Sylius/Bundle/ApiBundle/test/config/api_resources/Foo.xml
src/Sylius/Bundle/ApiBundle/test/config/fixtures/foo.yaml
src/Sylius/Bundle/ApiBundle/test/src/Tests/FooTest.php

[ApiBundle] Improve tests for custom entity in test application

---

UPGRADE-1.10.md
UPGRADE-1.9.md
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/View/CartShippingMethod.xml
src/Sylius/Bundle/ApiBundle/View/CartShippingMethod.php
src/Sylius/Bundle/ApiBundle/View/CartShippingMethodInterface.php

Shipping method change key cost to price

---

docs/api/unified_api/custom_paths.rst
docs/api/unified_api/index.rst
docs/api/unified_api/map.rst.inc

[API][DOCS] custom path

---

docs/api/unified_api/custom_paths.rst

[API][Documentation] Fix path to security file

---

docs/api/index.rst

[API][Documentation] Fix link to jwt documentation

---

src/Sylius/Behat/Context/Api/Shop/LoginContext.php
src/Sylius/Bundle/ApiBundle/Command/ResetPassword.php
src/Sylius/Bundle/ApiBundle/CommandHandler/ResetPasswordHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ResetPassword.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
src/Sylius/Bundle/ApiBundle/Resources/config/validation/ResetPassword.xml
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ConfirmResetPassword.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/ResetPasswordHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ConfirmResetPasswordValidatorSpec.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/CorrectChangeShopUserConfirmPasswordValidatorSpec.php

Continuation of https://github.com/Sylius/Sylius/pull/12391

[API] Add missing specs and make fixes to reset password PR

---

src/Sylius/Behat/Context/Api/Shop/LoginContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ResetPassword.xml

[API] Adjust reset password requests

---

src/Sylius/Bundle/ApiBundle/composer.json
src/Sylius/Bundle/CoreBundle/composer.json

Temporarily conflict to symfony/doctrine-bridge in Core and Api bundles

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml

Add contact email in channel fixture

---

features/account/customer_account/subscribing_newsletter.feature
src/Sylius/Behat/Context/Api/Shop/CustomerContext.php
src/Sylius/Behat/Context/Setup/CustomerContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml

[Api] Subscribed to newsletter

---

src/Sylius/Bundle/ApiBundle/README.md

[ApiBundle] Fix displaying testing section in README file

---

CONFLICTS.md
composer.json

See https://github.com/doctrine/DoctrineBundle/issues/1305.

Fix the build by conflicting with doctrine/doctrine-bundle 2.3.0

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/composer.json

[API] Remove untested route on ProductVariant

---

features/account/subscribing_newsletter_during_registration.feature
src/Sylius/Behat/Context/Api/Shop/RegistrationContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Bundle/ApiBundle/Command/RegisterShopUser.php
src/Sylius/Bundle/ApiBundle/CommandHandler/RegisterShopUserHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Account/RegisterShopUser.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/RegisterShopUserHandlerSpec.php

[API] Subscribing to newsletter on account register

---

src/Sylius/Bundle/ApiBundle/CommandHandler/ResendVerificationEmailHandler.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/ResendVerificationEmailHandlerSpec.php

| Related tickets | fixes https://github.com/Sylius/Sylius/pull/12474#discussion_r600287160

Remove unnecessary logic from handler

---

src/Sylius/Component/Core/Taxation/Applicator/OrderShipmentTaxesApplicator.php
src/Sylius/Component/Core/spec/Taxation/Applicator/OrderShipmentTaxesApplicatorSpec.php

[Taxation] Fix applying shipment taxes for multiple shipments

---

src/Sylius/Bundle/ApiBundle/CommandHandler/ChangeShopUserPasswordHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/event_handlers.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml

Add few cosmetic improvements in ChangeShopUserPasswordHandler.php and xml files

---

features/product/viewing_product_reviews/viewing_product_reviews_on_product_reviews_page.feature
src/Sylius/Behat/Context/Api/Shop/ProductReviewContext.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/product/viewing_product_reviews.yml
src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/AcceptedProductReviewsExtension.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductReview.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/AcceptedProductReviewsExtensionSpec.php

[API] product review filters

---

UPGRADE-1.10.md
src/Sylius/Bundle/ApiBundle/Command/RegisterShopUser.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/RegisterShopUserHandlerSpec.php

| Related tickets | completes https://github.com/Sylius/Sylius/pull/12476

Change command constructor

---

src/Sylius/Bundle/ApiBundle/Resources/config/services.xml

Remove duplicated service

---

src/Sylius/Bundle/PromotionBundle/Command/GenerateCouponsCommand.php

Build fix Change int to string in GenerateCouponsCommand

---

features/product/viewing_products/viewing_product_average_rating.feature
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Resources/config/suites/api/product/viewing_products.yml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml

[API] Added product average rating

---

src/Sylius/Behat/Context/Api/Shop/CustomerContext.php

[Behat][Customer] Fix assertions

---

composer.json
src/Sylius/Bundle/CoreBundle/composer.json
src/Sylius/Bundle/CustomerBundle/composer.json
src/Sylius/Bundle/UserBundle/composer.json

Closes #12436. No major changes that would affect us.

Use egulias/email-validator ^3.0

---

docs/cookbook/index.rst
docs/cookbook/payments/customizing-credit-memo.rst
docs/cookbook/payments/map.rst.inc

| Related tickets | part one of @pamil's pr https://github.com/Sylius/Sylius/pull/12492

[Documentation] Customizing credit memo

---

src/Sylius/Behat/Context/Api/Shop/ProductReviewContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/AddProductReview.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Serializer/AddPRoductReviewCommandFieldItemIriToIdentifierDenormalizer.php
src/Sylius/Bundle/ApiBundle/Serializer/AddProductReviewCommandFieldItemIriToIdentifierDenormalizer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/AddProductReviewCommandFieldItemIriToIdentifierDenormalizerSpec.php

This is extension and improvement for create generic transformation command field iri's to code: https://github.com/Sylius/Sylius/pull/12487

Convert iri to code in command AddProductReview

---

features/product/adding_product_reviews/product_review_validation.feature
src/Sylius/Behat/Client/ResponseChecker.php
src/Sylius/Behat/Client/ResponseCheckerInterface.php
src/Sylius/Behat/Context/Api/Shop/ProductReviewContext.php
src/Sylius/Behat/Context/Ui/Shop/ProductReviewContext.php
src/Sylius/Bundle/ApiBundle/Command/AddProductReview.php
src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddProductReview.xml
src/Sylius/Bundle/ApiBundle/Validator/Constraints/UniqueReviewerEmail.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/UniqueReviewerEmailValidator.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/UniqueReviewerEmailValidatorSpec.php
src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml

[API][Shop] Add validation for adding a product review

---

src/Sylius/Component/Product/Model/ProductVariant.php
src/Sylius/Component/Product/Model/ProductVariantInterface.php
tests/Controller/ProductVariantApiTest.php
tests/DataFixtures/ORM/resources/product_variants.yml
tests/Responses/product_variant/create_response.json
tests/Responses/product_variant/create_tracked_response.json
tests/Responses/product_variant/create_with_channel_pricings_response.json
tests/Responses/product_variant/create_with_product_option_response.json
tests/Responses/product_variant/create_with_shipping_category_response.json
tests/Responses/product_variant/create_with_tax_category_response.json
tests/Responses/product_variant/create_with_translations_response.json
tests/Responses/product_variant/index_response.json
tests/Responses/product_variant/paginated_index_response.json
tests/Responses/product_variant/sorted_index_response.json

[BUG] Product options null value returns 400 instead of 500

---

tests/Controller/ProductVariantApiTest.php
tests/DataFixtures/ORM/resources/product_variants.yml
tests/Responses/product_variant/create_response.json
tests/Responses/product_variant/create_tracked_response.json
tests/Responses/product_variant/create_with_channel_pricings_response.json
tests/Responses/product_variant/create_with_product_option_response.json
tests/Responses/product_variant/create_with_shipping_category_response.json
tests/Responses/product_variant/create_with_tax_category_response.json
tests/Responses/product_variant/create_with_translations_response.json
tests/Responses/product_variant/index_response.json
tests/Responses/product_variant/paginated_index_response.json
tests/Responses/product_variant/sorted_index_response.json

[Admin API] Test change of product options value on product variant

---

public/.htaccess

Change app.php to index.php

---

config/packages/twig.yaml
src/Sylius/Behat/Resources/config/suites/api/account/login.yml
src/Sylius/Behat/Resources/config/suites/api/promotion/receiving_discount.yml
src/Sylius/Behat/Resources/config/suites/api/shipping/managing_shipments.yml
src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_attribute.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/dress.yaml
src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
src/Sylius/Bundle/CoreBundle/Resources/config/app/messenger.yaml
src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en.yml
src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
yaml-standards.yaml

Hello, I am glad you upgrade dependency to [yaml-standards](https://github.com/sspooky13/yaml-standards) but you changed [only version number](https://github.com/Sylius/Sylius/pull/12457) and you didn't change logic to find files 😅, now you [need to use wildcard to find files](https://github.com/sspooky13/yaml-standards/blame/master/CHANGELOG.md#L11).
I take this as feedback that changelog is not written well. I will be glad for every help how to write it better or what should I do to make sure this doesn't happen again? 🤔 
Thank you in advance 🤝

fixed find files in yaml standards

---

src/Sylius/Bundle/AdminBundle/spec/SectionResolver/AdminUriBasedSectionResolverSpec.php
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/SectionResolver/AdminApiSection.php
src/Sylius/Bundle/ApiBundle/SectionResolver/AdminApiUriBasedSectionResolver.php
src/Sylius/Bundle/ApiBundle/SectionResolver/ShopApiSection.php
src/Sylius/Bundle/ApiBundle/SectionResolver/ShopApiUriBasedSectionResolver.php
src/Sylius/Bundle/ApiBundle/spec/SectionResolver/AdminApiUriBasedSectionResolverSpec.php
src/Sylius/Bundle/ApiBundle/spec/SectionResolver/ShopApiUriBasedSectionResolverSpec.php

[API] Add admin and shop section resolvers

---

src/Sylius/Component/Product/Model/ProductVariant.php
src/Sylius/Component/Product/Model/ProductVariantInterface.php

Revert BC break in ProductVariantInterface

---

src/Sylius/Bundle/ApiBundle/EventListener/ApiCartBlamerListener.php
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/spec/EventListener/ApiCartBlamerListenerSpec.php

| Related tickets | continues #12512

Remove unused api cart blamer method add missing spec

---

UPGRADE-1.10.md
src/Sylius/Bundle/ApiBundle/Command/BlameCart.php
src/Sylius/Bundle/ApiBundle/CommandHandler/BlameCartHandler.php
src/Sylius/Bundle/ApiBundle/EventListener/ApiCartBlamerListener.php
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/BlameCartHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/EventListener/ApiCartBlamerListenerSpec.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
src/Sylius/Bundle/ShopBundle/EventListener/UserCartRecalculationListener.php
src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
src/Sylius/Bundle/ShopBundle/spec/EventListener/UserCartRecalculationListenerSpec.php

Refactor cart blaming

---

src/Sylius/Bundle/ApiBundle/Command/BlameCart.php
src/Sylius/Bundle/ApiBundle/CommandHandler/BlameCartHandler.php

| Related tickets | fixes for #12528

Minor fixes for cart blaming command

---

UPGRADE-1.10.md
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAssociationType.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionValue.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductTaxon.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxonTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductAssociationType.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductAssociationTypeTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductOption.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductOptionTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductOptionValue.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductOptionValueTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTaxon.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariantTranslation.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/TaxonTranslation.xml

| Branch?         |master
| BC breaks?      | i think it could be 

[API] Serialization groups unified

---

features/promotion/applying_promotion_rules/receiving_discount_based_on_cart_quantity.feature
features/promotion/applying_promotion_rules/receiving_discount_based_on_chosen_product.feature
features/promotion/applying_promotion_rules/receiving_discount_based_on_customer_group.feature
features/promotion/applying_promotion_rules/receiving_discount_based_on_items_from_specific_taxons.feature
features/promotion/applying_promotion_rules/receiving_discount_based_on_items_total.feature
features/promotion/applying_promotion_rules/receiving_discount_based_on_nth_order_for_guest_customer.feature
features/promotion/applying_promotion_rules/receiving_discount_based_on_total_of_items_from_specific_taxon.feature
features/promotion/complex_promotions.feature
features/promotion/reverting_discount/reverting_previously_applied_discount_on_cart.feature
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/promotion/applying_promotion_rules.yml

[API][Promotion] Test applying promotion rules

---

features/checkout/order_promotion/order_promotion_integrity_validation.feature

| New feature?    |  yes
The rest of the scenarios behave more or less properly, but requires additional code to handle 500

[API][Checkout] Add tag to promotion scenario

---

UPGRADE-1.9.md
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/OrderItem.xml

[API] Add prefix to subresource endpoint of order item's adjustments

---

docs/book/installation/sylius_plus_installation.rst

update Plus installation guide

---

docs/book/installation/sylius_plus_installation.rst

[Docs] add minor improvement to Plus installation guide

---

features/product/viewing_products/viewing_products_from_specific_taxon_and_channel.feature
src/Sylius/Behat/Context/Api/Shop/ChannelContext.php
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Context/Setup/ChannelContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/product/viewing_products.yml
src/Sylius/Bundle/ApiBundle/Filter/TaxonFilter.php
src/Sylius/Bundle/ApiBundle/spec/Filter/TaxonFilterSpec.php

[API] channel based product collection

---

src/Sylius/Bundle/CoreBundle/Migrations/Version20210408131321.php
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Order.orm.xml

| Related tickets | fixes #12517

fix: add unique index to token_value in order entity

---

config/packages/doctrine.yaml

Use 4-Byte UTF-8 Unicode Encoding

---

docs/book/architecture/resource_layer.rst

Resource layer tip - English corrections

---

docs/book/themes/themes.rst

[DOC] update theme structure documentation

---

docs/api/unified_api/index.rst
docs/api/unified_api/map.rst.inc
docs/api/unified_api/sylius_api_paths.rst
docs/customization/api.rst
docs/customization/index.rst
docs/customization/map.rst.inc

[Docs] Add and improve new api docs

---

features/checkout/preventing_adding_to_cart_disabled_products.feature
features/checkout/preventing_adding_to_cart_invalid_products.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddItemToCart.xml
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ProductOrVariantEnabled.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ProductOrVariantEnabledValidator.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ProductOrVariantEnabledValidatorSpec.php
src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml

| Related tickets | from #12579

[API] Cherry pick commits on 1.9 branch for validating if product is enabled during adding to cart

---

features/checkout/preventing_adding_to_cart_disabled_products.feature
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ProductOrVariantEnabled.php

Fixes after upmerge

---

features/checkout/preventing_adding_to_cart_disabled_products.feature
features/checkout/preventing_adding_to_cart_product_or_variant_from_another_channel.feature
src/Sylius/Behat/Context/Api/Shop/ChannelContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml
src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddItemToCart.xml
src/Sylius/Bundle/ApiBundle/Resources/translations/validators.en.yaml
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ProductAvailableInChannel.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ProductAvailableInChannelValidator.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ProductOrVariantEnabled.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ProductAvailableInChannelValidatorSpec.php
src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml

| Branch?         |  1.9
| Bug fix?        | yes (kind of)
| Related tickets | same PR as #12598 but for 1.9 branch. This branch continues #12604

Adding product from another channel bugfix

---

src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ProductAvailableInChannelValidatorSpec.php

| Related tickets | fixes after upmerge https://github.com/Sylius/Sylius/pull/12609

[API][PHPSpec] Fix validator after upmerge

---

docs/cookbook/shop/facebook-login.rst

[Documentation] Update cookbook about Facebook login

---

UPGRADE-1.10.md
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Commands/Cart/PickupCart.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml

[API] Revert locale to localeCode in pickup cart

---

features/cart/shopping_cart/adding_product_to_cart_with_prices_dependent_on_channel.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Setup/ChannelContext.php
src/Sylius/Behat/Resources/config/suites/api/cart/shopping_cart.yml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariantTranslation.xml

[Api] Adding product to cart with proper product price per channel

---

features/inventory/cart_inventory/inability_of_adding_a_product_with_insufficient_stock.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/inventory/cart_inventory.yml
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
src/Sylius/Bundle/ApiBundle/Resources/translations/validators.en.yaml
src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantSerializer.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/AddingEligibleProductVariantToCart.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/AddingEligibleProductVariantToCartValidator.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantSerializerSpec.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/AddingEligibleProductVariantToCartValidatorSpec.php

[API]Add inStock serialization to productVariant

---

docs/book/plugins/index.rst

[README] Fix link to plugin list

---

docs/customization/api.rst

Continuation of https://github.com/Sylius/Sylius-Standard/pull/555.

Improve API Platform customisation guide

---

UPGRADE-1.9.md
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantNormalizerSpec.php

| BC breaks?      | no, because it is an experimental feature
Before:
After:

[API][ProductVariant] Fix product variant response by using proper normalizer

---

src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantNormalizerSpec.php

| Related tickets | fixes #https://github.com/Sylius/Sylius/pull/12650

[API][ProductVariant] Add additional specs for product variant normalizer

---

src/Sylius/Bundle/ApiBundle/Serializer/ProductNormalizer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductNormalizerSpec.php

| Related tickets | fixes #https://github.com/Sylius/Sylius/pull/12649

[API][Product] Add additional specs for product normalizer

---

docs/cookbook/entities/custom-model-accessible-for-channel-admin.rst

| Related tickets | improvements to #12619 

[Documentation][Plus] Minor improvements in cookbook for accessing to entities by channel admins

---

docs/customization/api.rst

| Doc fix?        | yes #12599 

[Documentation] Fix Customizing API doc headers inconsistency

---

features/inventory/cart_inventory/prevent_buying_more_products_than_available_in_a_stock.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Resources/config/suites/api/inventory/cart_inventory.yml
src/Sylius/Bundle/ApiBundle/Validator/Constraints/AddingEligibleProductVariantToCartValidator.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/AddingEligibleProductVariantToCartValidatorSpec.php

[Api] Prevent product more than in stock

---

features/checkout/shipping_order/preventing_not_available_shipping_method_selection.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Setup/ProductContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
src/Sylius/Bundle/ApiBundle/Resources/config/validation/ChooseShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/translations/validators.en.yaml
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChosenShippingMethodEligibility.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChosenShippingMethodEligibilityValidator.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ChosenShippingMethodEligibilityValidatorSpec.php

[API] Preventing from choosing unavailable shipping method during checkout

---

src/Sylius/Bundle/ApiBundle/Swagger/ProductDocumentationNormalizer.php
src/Sylius/Bundle/ApiBundle/Swagger/ProductVariantDocumentationNormalizer.php

| New feature?    | yes (missed thing)
| Related tickets | Extends #12639
I forgot to add this to PR, forgive me sylius 🙏

[API] Add missing inStock field to swagger

---

features/inventory/cart_inventory/verify_inventory_quantity_when_updating_cart_summary.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Resources/config/suites/api/inventory/cart_inventory.yml
src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
src/Sylius/Bundle/ApiBundle/Resources/config/validation/ChangeItemQuantityInCart.xml
src/Sylius/Bundle/ApiBundle/Resources/translations/validators.en.yaml
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChangedItemQuantityInCart.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChangedItemQuantityInCartValidator.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ChangedItemQuantityInCartValidatorSpec.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ChangingItemQuantityInCartValidatorSpec.php

[Api] Check stock sufficient while cart update

---

features/product/viewing_products/viewing_product.feature
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
src/Sylius/Behat/Page/Shop/Product/ShowPage.php
src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTranslation.xml

[Api] Customer see description of a product

---

docs/customization/api.rst

[DOCS] Modify serialization fields in api

---

features/product/viewing_products/viewing_product_short_description_on_product_list.feature
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTranslation.xml

[API] short description on product index

---

docs/cookbook/payments/customizing-credit-memo.rst

| Related tickets | associated with changes from https://github.com/Sylius/RefundPlugin/pull/295

[Documentation] Customizing CreditMemo entity by adding a new field

---

src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml

With current behavior on sylius-standard build is failing. Path to classes is now provided as argument.

Fix for build of Sylius Standard

---

features/checkout/paying_for_order/preventing_not_available_payment_method_selection.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
src/Sylius/Bundle/ApiBundle/Resources/config/validation/ChoosePaymentMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/translations/validators.en.yaml
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChosenPaymentMethodEligibility.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChosenPaymentMethodEligibilityValidator.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ChosenPaymentMethodEligibilityValidatorSpec.php

Add Validation to chose payment method

---

src/Sylius/Bundle/ApiBundle/CommandHandler/RegisterShopUserHandler.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/RegisterShopUserHandlerSpec.php

[Minor] Return shop user after registration command to improve extendibility

---

src/Sylius/Bundle/ApiBundle/CommandHandler/RegisterShopUserHandler.php

Add missing return value

---

docs/cookbook/entities/custom-model.rst

[Docs] Fix cookbook for custom entity

---

config/packages/prod/doctrine.yaml
config/packages/test_cached/doctrine.yaml

[Doctrine] Fix problem with explicitly defining entity managers

---

tests/Api/DataFixtures/ORM/country.yaml
tests/Api/JsonApiTestCase.php
tests/Api/Responses/Expected/shop/get_countries_response.json
tests/Api/Shop/GetCountriesTest.php

[API][Country] Initialize contract tests for api/v2

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PaymentMethod.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PaymentMethod.xml
src/Sylius/Bundle/ApiBundle/Tests/ApiPlatform/Bridge/Symfony/Routing/CachedRouteNameResolverTest.php
tests/Api/DataFixtures/ORM/cart.yaml
tests/Api/DataFixtures/ORM/country.yaml
tests/Api/DataFixtures/ORM/payment_method.yaml
tests/Api/JsonApiTestCase.php
tests/Api/Responses/Expected/shop/get_payment_methods_response.json
tests/Api/Shop/GetPaymentMethodsTest.php

| Related tickets | based on https://github.com/Sylius/Sylius/pull/12689

[API][PaymentMethod] Add contract test for available payment methods endpoint

---

docs/cookbook/payments/refund-process.rst

[Documentation] Tweaks on the refunds process cookbook

---

docs/cookbook/payments/refund-process.rst

[Documentation] Fix links in the refunds process cookbook

---

docs/book/themes/themes.rst

Themes directory structure has changed: https://github.com/Sylius/SyliusThemeBundle/blob/master/UPGRADE.md#upgrade-from-1x-to-20

[Documentation] Update templates directory in Themes doc

---

src/Sylius/Bundle/ApiBundle/CommandHandler/PickupCartHandler.php

Fix typo and imporve error message

---

src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/ProductsWithEnableFlagExtension.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/ProductsWithEnableFlagExtensionSpec.php

[Dql] Add parameter instead of hardcoding it in where statement

---

.github/workflows/application.yml
.github/workflows/packages.yml
composer.json

Symfony ^5.3 causes loooooots of segfaults :/

Bring back testing for Symfony ^5.2

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductVariantRepository.php

| Related tickets | Continues https://github.com/Sylius/Sylius/pull/12720

[DQL] Change hardcoded tracked value to parameter in where statements

---

CONFLICTS.md
composer.json

Reverts Sylius/Sylius#12733 as it does not fix the issue

Revert "Bring back conflict to symfony/polyfill-mbstring"

---

docs/cookbook/index.rst
docs/cookbook/taxation/customize-tax-by-address.rst
docs/cookbook/taxation/map.rst.inc

| Related tickets | same as https://github.com/Sylius/Sylius/pull/12724 but on 1.9 branch
Opened new PR as old one was making a lot of merge conflicts.

Add cookbook with how to change tax address

---

docs/customization/api.rst

| Related tickets | docs for #12693 

[Docs] Docs customization

---

src/Sylius/Bundle/ApiBundle/ApiPlatform/ApiResourceConfigurationMerger.php
src/Sylius/Bundle/ApiBundle/ApiPlatform/ResourceMetadataPropertyValueResolver.php
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
src/Sylius/Bundle/ApiBundle/spec/ApiPlatform/ResourceMetadataPropertyValueResolverSpec.php

| Related tickets | https://github.com/Sylius/Sylius/pull/12693

[API] add final to clssess, cs fixes

---

docs/customization/api.rst

| Related tickets | https://github.com/Sylius/Sylius/pull/12700

[Docs] fix unsetting filters

---

features/checkout/shipping_order/selecting_order_shipping_method.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChooseShippingMethodHandler.php
src/Sylius/Bundle/ApiBundle/Exception/OrderCannotBeShippedWithoutAddressing.php
src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/ChooseShippingMethodHandlerSpec.php

[API] handle shipping without addressing

---

tests/Api/Responses/Expected/shop/error/jwt_token_not_found.json
tests/Api/Shop/OrdersTest.php

[API] contract test for get order collection by guest

---

docs/book/installation/sylius_plus_installation.rst

Not valid yet, but in the nearest future the newest version of Sylius Plus would recommend using Sylius 1.10 🖖

[Docs] Describe API customization requirement for SyliusPlus with Sylius 1.9

---

docs/book/installation/sylius_plus_installation.rst

[Docs] Remove redundant refund interfaces

---

docs/book/installation/sylius_plus_installation.rst

| Related tickets | fixes after https://github.com/Sylius/Sylius/pull/12751

[Documentation] Fix warning about version of Sylius in Plus installation guide

---

features/product/viewing_products/viewing_diagonal_variant_options.feature
features/product/viewing_products/viewing_different_price_for_different_product_variants_selected_with_options.feature
features/taxonomy/managing_taxons/displaying_products_in_proper_taxon_after_trying_to_delete_taxon.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
src/Sylius/Behat/Resources/config/suites/ui/taxonomy/managing_taxons.yml
src/Sylius/Bundle/CoreBundle/Doctrine/ORM/Handler/ResourceDeleteHandler.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/spec/Doctrine/ORM/Handler/ResourceDeleteHandlerSpec.php

| Related tickets | fixes https://github.com/Sylius/Sylius/issues/12422

[Taxon] Wrap resource deletion operation with a transaction to fix a problem with removing used taxon

---

src/Sylius/Bundle/ApiBundle/Validator/Constraints/ConfirmResetPassword.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/ConfirmResetPasswordValidator.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/CorrectChangeShopUserConfirmPassword.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/CorrectChangeShopUserConfirmPasswordValidator.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/PromotionCouponEligibility.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/PromotionCouponEligibilityValidator.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/UniqueReviewerEmail.php
src/Sylius/Bundle/ApiBundle/Validator/Constraints/UniqueShopUserEmail.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ConfirmResetPasswordValidatorSpec.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/CorrectChangeShopUserConfirmPasswordValidatorSpec.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/PromotionCouponEligibilityValidatorSpec.php

[ENHANCEMENT][API] Refactor Api Constraints to match rest of them

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductImage.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductImage.xml
tests/Api/Admin/ProductImageTest.php
tests/Api/DataFixtures/ORM/product_image.yaml
tests/Api/Responses/Expected/admin/get_product_image_response.json
tests/Api/Responses/Expected/admin/get_product_images_response.json
tests/Api/Responses/Expected/shop/get_product_image_response.json
tests/Api/Shop/ProductImageTest.php

[API] Add Product Image type to responses

---

docs/book/installation/sylius_plus_installation.rst

[Docs][Plus] Modify plus installation guide

---

docs/book/installation/sylius_plus_installation.rst

[Docs][Plus] Change steps order

---

adr/2021_07_05_api_providing_locales_available_in_active_channel.md
features/locale/getting_available_locales_in_current_channel.feature
src/Sylius/Behat/Context/Api/Shop/LocaleContext.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/locale/locales.yaml
src/Sylius/Bundle/ApiBundle/DataProvider/LocaleCollectionDataProvider.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Locale.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Locale.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
src/Sylius/Bundle/ApiBundle/spec/DataProvider/LocaleCollectionDataProviderSpec.php
tests/Api/Admin/LocalesTest.php
tests/Api/DataFixtures/ORM/cart.yaml
tests/Api/Responses/Expected/admin/get_locales_response.json
tests/Api/Responses/Expected/shop/get_locales_response.json
tests/Api/Shop/LocalesTest.php

[Locale]Available locales in channel by api

---

UPGRADE-1.11.md
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Address.xml
tests/Api/DataFixtures/ORM/authentication/customer.yaml
tests/Api/DataFixtures/ORM/country.yaml
tests/Api/Responses/Expected/shop/post_addresses_response.json
tests/Api/Shop/AddressesPostTest.php

[API] Remove customer and serialize posted address

---

docs/cookbook/index.rst
docs/cookbook/payments/custom-type-of-refund.rst
docs/cookbook/payments/map.rst.inc

| Related tickets | fixes https://github.com/Sylius/RefundPlugin/issues/279 and waits for https://github.com/Sylius/RefundPlugin/pull/323

[Documentation][Cookbook] How to add another type of refund?

---

UPGRADE-1.9.md
src/Sylius/Bundle/ApiBundle/DependencyInjection/Configuration.php

| Related tickets | fixes #12771 

[API] Disable API by default

---

docs/book/installation/sylius_plus_installation.rst

[Documentation] Update Plus installation guide for Sylius 1.9

---

docs/book/installation/sylius_plus_installation.rst

[Documentation] Update Plus installation guide for Sylius 1.10

---

features/shipping/applying_shipping_fee/applying_correct_shipping_fee_on_order.feature
features/shipping/applying_shipping_fee/applying_correct_shipping_fee_with_product_taxes_on_order.feature
features/shipping/applying_shipping_fee/applying_correct_shipping_fee_with_taxes_on_order.feature
features/taxation/applying_taxes/applying_correct_taxes_based_on_customer_data.feature
features/taxation/applying_taxes/applying_correct_taxes_for_items_with_different_tax_rates.feature
features/taxation/applying_taxes/applying_correct_taxes_for_items_with_the_same_tax_rate.feature
features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_an_item_in_order.feature
features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_shipping.feature
features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_whole_order.feature
features/taxation/applying_taxes/applying_correct_taxes_on_visitor_cart.feature
features/taxation/applying_taxes/not_applying_taxes_for_products_without_tax_category.feature
features/taxation/applying_taxes/rounding_taxes_on_order_item_level.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/api/taxation/applying_taxes.yml
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/AddItemToCartHandler.php

[Behat][API][Taxes] Turn on chunk of taxation related scenarios

---

features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_per_customer_usage_limit.feature
features/promotion/receiving_discount/receiving_fixed_discount_on_cart.feature
features/promotion/receiving_discount/receiving_fixed_discount_on_items_on_price_range.feature
features/promotion/receiving_discount/receiving_fixed_discount_on_products_from_specific_taxon.feature
features/promotion/receiving_discount/receiving_fixed_discount_on_specific_products.feature
features/promotion/receiving_discount/receiving_percentage_discount_on_items_on_price_range.feature
features/promotion/receiving_discount/receiving_percentage_discount_on_products_from_specific_taxon.feature
features/promotion/receiving_discount/receiving_percentage_discount_on_shipping.feature
features/promotion/receiving_discount/receiving_percentage_discount_on_specific_products.feature
features/promotion/receiving_discount/receiving_percentage_discount_promotion_on_order.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Resources/config/suites/api/promotion/receiving_discount.yml

[Behat][API][Promotion] Turn on chunk of promotion scenarios

---

UPGRADE-1.10.md

[API] Add missing note about enabling API to UPGRADE-1.10 file

---

.github/workflows/application.yml
features/account/customer_account/editing_customer_profile.feature
src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
src/Sylius/Behat/Context/Ui/Shop/RegistrationContext.php
src/Sylius/Component/Core/Formatter/StringInflector.php

| Related tickets | partially related to https://github.com/Sylius/Sylius/pull/12633

[Maintenance] Fix 1.8 build

---

src/Sylius/Component/Core/Formatter/StringInflector.php

| Related tickets | after upmerge of https://github.com/Sylius/Sylius/pull/12816

[Core] Bring back String u function

---

features/taxation/applying_taxes/applying_correct_taxes_for_shipping.feature
features/taxation/applying_taxes/applying_correct_taxes_for_shipping_with_tax_rate_included_in_price.feature
src/Sylius/Behat/Context/Ui/Shop/CartContext.php
src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_totals.html.twig

[Taxation] Add scenarios for applying proper taxes for shipping

---

docs/book/api/index.rst
docs/book/api/legacy_api.rst
docs/book/api/map.rst.inc

[Documentation] Chapter about legacy APIs

---

features/channel/products_accessibility_in_multiple_channels/products_accessibility_in_multiple_channels.feature
features/channel/theming/displaying_themed_channel_website.feature
features/channel/theming/managing_themes_per_channel.feature
features/channel/theming/overriding_plugin_template_with_theme.feature
features/currency/handling_different_currencies_on_multiple_channels.feature
features/currency/switching_current_currency.feature
features/inventory/displaying_inventory_tab_on_simple_product_edit_page.feature

[API] Exclude meaningless scenarios

---

docs/customization/api/adding_and_removing_endpoints.rst
docs/customization/api/index.rst
docs/customization/api/map.rst.inc
docs/customization/api/modifying_endpoints.rst
docs/customization/api/serialization_customization.rst
docs/customization/index.rst
docs/customization/map.rst.inc

[Docs] split api customization docs

---

src/Sylius/Bundle/ApiBundle/ApiPlatform/ApiResourceConfigurationMerger.php
src/Sylius/Bundle/ApiBundle/ApiPlatform/Factory/MergingExtractorResourceMetadataFactory.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChoosePaymentMethodHandler.php
src/Sylius/Bundle/ApiBundle/Tests/CommandHandler/SendAccountRegistrationEmailHandlerTest.php
src/Sylius/Bundle/ApiBundle/Tests/CommandHandler/SendAccountVerificationEmailHandlerTest.php
src/Sylius/Bundle/ApiBundle/spec/ApiPlatform/ApiResourceConfigurationMergerSpec.php
src/Sylius/Bundle/ApiBundle/spec/ApiPlatform/ResourceMetadataPropertyValueResolverSpec.php
src/Sylius/Bundle/ApiBundle/spec/DataProvider/CartPaymentMethodsSubresourceDataProviderSpec.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ChosenShippingMethodEligibilityValidatorSpec.php
src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/PromotionCouponEligibilityValidatorSpec.php
src/Sylius/Bundle/ApiBundle/test/src/Tests/SyliusConfigMergeTest.php

I believe we should use ECS more 😄 🐎

[ApiBundle] Small CS fixes

---

src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_summary.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_summaryWidget.html.twig

[UI] Add bottom scroll to the order summary table

---

UPGRADE-1.8.md
UPGRADE-API-1.8.md

| Related tickets | Split from #12831

[UPGRADE] Split API and non API upgrade files

---

src/Sylius/Bundle/ApiBundle/spec/Serializer/CommandNormalizerSpec.php

| Related tickets | after https://github.com/Sylius/Sylius/pull/12825/files#diff-3ab7c77a51e554f84a2a3106e19e7f303026398e721457d9e48c952d319a00e2R42

[API][PHPSpec] Improve spec for CommandNormalizer

---

docs/book/orders/checkout.rst

| Branch?         | 1.9, 1.10 or master 

Quick Typo update :)

---

UPGRADE-API-1.11.md
src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
src/Sylius/Bundle/ApiBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
src/Sylius/Bundle/ApiBundle/Serializer/ProductImageNormalizer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductImageNormalizerSpec.php
tests/Api/DataFixtures/ORM/product_image.yaml
tests/Api/Responses/Expected/admin/get_product_image_response.json
tests/Api/Responses/Expected/admin/get_product_images_response.json
tests/Api/Responses/Expected/shop/get_product_image_response.json

[API]Product image handling

---

src/Sylius/Component/Core/OrderProcessing/OrderAdjustmentsClearer.php
src/Sylius/Component/Core/OrderProcessing/OrderPricesRecalculator.php
src/Sylius/Component/Core/OrderProcessing/OrderPromotionProcessor.php
src/Sylius/Component/Core/OrderProcessing/OrderShipmentProcessor.php
src/Sylius/Component/Core/OrderProcessing/OrderTaxesProcessor.php
src/Sylius/Component/Core/OrderProcessing/ShippingChargesProcessor.php
src/Sylius/Component/Core/spec/OrderProcessing/OrderAdjustmentsClearerSpec.php
src/Sylius/Component/Core/spec/OrderProcessing/OrderPricesRecalculatorSpec.php
src/Sylius/Component/Core/spec/OrderProcessing/OrderPromotionProcessorSpec.php
src/Sylius/Component/Core/spec/OrderProcessing/OrderShipmentProcessorSpec.php
src/Sylius/Component/Core/spec/OrderProcessing/OrderTaxesProcessorSpec.php
src/Sylius/Component/Core/spec/OrderProcessing/ShippingChargesProcessorSpec.php
tests/DataFixtures/ORM/resources/year_sales.yml

[Order] Protect processors from execution if the order is in a state different than cart

---

src/Sylius/Bundle/ApiBundle/Serializer/CommandDenormalizer.php

[API] Do not check command arguments if there is an object to populate

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Country.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Country.xml
tests/Api/Responses/Expected/shop/get_countries_response.json
tests/Api/Responses/Expected/shop/get_country_response.json
tests/Api/Shop/CountriesTest.php

[API][Country] Improve endpoints serialization

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/Handler/ResourceUpdateHandler.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/spec/Doctrine/ORM/Handler/ResourceUpdateHandlerSpec.php

[Core] Wrap resource update operation with a transaction

---

UPGRADE-1.11.md
docs/customization/state_machine.rst
src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_checkout.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_payment.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_shipping.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_payment.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_product_review.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_shipment.yml

| Bug fix?        | yes (potential fix)
| New feature?    | no (extending current behavior)
| BC breaks?      | possible

[SM] Change priorities of State Machine callbacks

---

features/account/customer_account/viewing_orders_history/seeing_right_payment_amount_for_an_order.feature
features/order/managing_orders/browsing_orders/seeing_orders_payment_amount_including_all_fees.feature
src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
src/Sylius/Behat/Context/Api/Shop/OrderContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml
src/Sylius/Behat/Resources/config/suites/api/order/managing_orders.yml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Shipment.xml
src/Sylius/Bundle/ApiBundle/test/src/Tests/DisablingApiTest.php
tests/Api/Admin/OrdersTest.php
tests/Api/Admin/PaymentsTest.php
tests/Api/Responses/Expected/admin/get_order_response.json
tests/Api/Responses/Expected/admin/get_payment_response.json
tests/Api/Responses/Expected/shop/get_payment_response.json
tests/Api/Shop/PaymentsTest.php
tests/Api/Utils/AdminUserLoginTrait.php
tests/Api/Utils/OrderPlacerTrait.php
tests/Api/Utils/ShopUserLoginTrait.php

[API] Check payment amount

---

src/Sylius/Bundle/CoreBundle/Migrations/Version20210809121349.php
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Customer.orm.xml

[ORM] add created at index to customer

---

features/product/viewing_products/viewing_different_discounted_price_for_different_product_variants.feature
features/product/viewing_products/viewing_products_discounted_price.feature
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/product/viewing_products.yml
src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantNormalizerSpec.php
tests/Api/DataFixtures/ORM/product_variant_with_original_price.yaml
tests/Api/Responses/Expected/shop/get_product_variant_with_original_price_response.json
tests/Api/Responses/Expected/shop/get_product_variant_with_price_response.json
tests/Api/Shop/ProductTest.php

[API] add original price to product variant

---

src/Sylius/Bundle/ApiBundle/Checker/AppliedCouponEligibilityCheckerInterface.php
src/Sylius/Bundle/ApiBundle/CommandHandler/BlameCartHandler.php
src/Sylius/Bundle/ApiBundle/DependencyInjection/Compiler/ReflectionExtractorHotfixPass.php
src/Sylius/Bundle/ApiBundle/PropertyInfo/Extractor/ReflectionExtractor.php
src/Sylius/Bundle/ApiBundle/Serializer/ProductNormalizer.php
src/Sylius/Bundle/ApiBundle/Swagger/ProductDocumentationNormalizer.php
src/Sylius/Bundle/ApiBundle/Swagger/ProductVariantDocumentationNormalizer.php
src/Sylius/Bundle/ApiBundle/spec/ApiPlatform/ApiResourceConfigurationMergerSpec.php
src/Sylius/Bundle/ApiBundle/spec/ApiPlatform/ResourceMetadataPropertyValueResolverSpec.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/RequestResetPasswordTokenHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/ResendVerificationEmailHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/DataProvider/ChannelAwareItemDataProviderSpec.php
src/Sylius/Bundle/ApiBundle/spec/DataProvider/ResetPasswordItemDataProviderSpec.php
src/Sylius/Bundle/ApiBundle/test/src/Command/FooCommand.php
src/Sylius/Bundle/ApiBundle/test/src/CommandHandler/FooHandler.php
src/Sylius/Bundle/ApiBundle/test/src/Tests/SetUpTestsTrait.php
src/Sylius/Bundle/ApiBundle/test/src/Tests/SyliusConfigMergeTest.php
src/Sylius/Bundle/CoreBundle/EventListener/LocaleAwareListener.php
src/Sylius/Bundle/CoreBundle/Migrations/Version20201104085538.php
src/Sylius/Bundle/CoreBundle/Migrations/Version20210408131321.php
src/Sylius/Bundle/PayumBundle/DependencyInjection/Compiler/InjectContainerIntoControllersPass.php
src/Sylius/Bundle/PayumBundle/DependencyInjection/Compiler/UseTweakedDoctrineStoragePass.php
src/Sylius/Bundle/PayumBundle/Storage/DoctrineStorage.php

[Minor] Add missing license blocks

---

docs/book/installation/requirements.rst

[Minor][Docs] Bump requirements version

---

src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantNormalizerSpec.php
tests/Api/Responses/Expected/shop/get_product_variant_with_original_price_response.json
tests/Api/Responses/Expected/shop/get_product_variant_with_price_response.json

[API] Rename original_price to originalPrice in api responses

---

docs/cookbook/invoices/custom-invoice.rst

| Related tickets | fixes for https://github.com/Sylius/Sylius/pull/12879

[API] Fix formating for list in invoice cookbook

---

docs/cookbook/invoices/custom-invoice.rst

Now the list looks good 🎉 Continues https://github.com/Sylius/Sylius/pull/12888

Fix to ordered list

---

src/Sylius/Behat/Context/Api/Shop/OrderContext.php
src/Sylius/Behat/Context/Setup/CartContext.php
src/Sylius/Behat/Resources/config/services.xml
src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/services/contexts/setup.xml
src/Sylius/Behat/Service/ApiSecurityService.php
src/Sylius/Bundle/ApiBundle/Command/Cart/PickupCart.php
src/Sylius/Bundle/ApiBundle/CommandHandler/PickupCartHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/PickupCartHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/DataTransformer/LoggedInShopUserIdAwareCommandDataTransformerSpec.php
symfony.lock
tests/Api/Admin/OrdersTest.php
tests/Api/Admin/PaymentsTest.php
tests/Api/Shop/PaymentsTest.php
tests/Api/Utils/AdminUserLoginTrait.php
tests/Api/Utils/OrderPlacerTrait.php
tests/Api/Utils/ShopUserLoginTrait.php

[Behat][API] Programitically generate API autorization token

---

src/Sylius/Behat/Context/Api/Shop/ProductContext.php

| Related tickets | fixes for https://github.com/Sylius/Sylius/pull/12877
! MERGE #12883 FIRST

Original price behat fix

---

src/Sylius/Bundle/ApiBundle/Swagger/ProductVariantDocumentationNormalizer.php

Update swagger docs with product variants originalPrice

---

src/Sylius/Behat/Context/Setup/CartContext.php
tests/Api/Admin/AdminUsersTest.php
tests/Api/Responses/Expected/admin/log_in_admin_response.json
tests/Api/Responses/Expected/shop/log_in_customer_response.json
tests/Api/Shop/CustomersTest.php
tests/Api/Shop/PaymentsTest.php

| Related tickets | fixes https://github.com/Sylius/Sylius/pull/12177#pullrequestreview-730577182

[API] Log in contract tests + minor fixes

---

docs/index.rst
docs/performance/database-indexes.rst
docs/performance/index.rst
docs/performance/map.rst.inc
docs/performance/query-optimization.rst

[Docs] sylius performance boost

---

docs/performance/database-indexes.rst

[Docs] fix annotations

---

docs/performance/database-indexes.rst

[Docs] add prefix to sylius customer table

---

docs/getting-started-with-sylius/index.rst
docs/getting-started-with-sylius/map.rst.inc

| Related tickets | fixes #12884 

[Documentation] Change the order of pages in Getting Started section

---

tests/Api/Admin/ProductImagesTest.php
tests/Api/Admin/ProductVariantsTest.php
tests/Api/Shop/ProductImagesTest.php
tests/Api/Shop/ProductVariantsTest.php

[Minor] Adjust test class names to follow emerged convention

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Taxon.xml
tests/Api/DataFixtures/ORM/taxonomy.yaml
tests/Api/Responses/Expected/shop/get_taxonomy_response.json
tests/Api/Shop/TaxonsTest.php

[API] Expose taxon children as IRI in menu endpoint

---

src/Sylius/Bundle/ApiBundle/Resources/config/services/api_payment_methods.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/applicators.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/data_persisters.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/event_handlers.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/event_subscribers.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/payments.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/resolver.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/swagger.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml

[Maintenance] Make all API Bundle services public and unify public notation

---

src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
tests/Api/Admin/CatalogPromotionsTest.php
tests/Api/DataFixtures/ORM/catalog_promotion.yaml
tests/Api/Responses/Expected/admin/get_catalog_promotions_response.json

| Related tickets | fixes #12986

[CatalogPromotion][API] Minor fixes to creating simple catalog promotion

---

features/promotion/managing_catalog_promotions/browsing_catalog_promotions.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
src/Sylius/Behat/Resources/config/services/contexts/setup.xml
src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionExampleFactory.php

[CatalogPromotion][API] Add scenarios for browsing catalog promotions

---

docs/book/contributing/documentation/overview.rst

[Docs] Choosing the right branch - fix

---

features/promotion/managing_catalog_promotions/creating_catalog_promotion.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Page/Admin/CatalogPromotion/CreatePage.php
src/Sylius/Behat/Page/Admin/CatalogPromotion/CreatePageInterface.php
src/Sylius/Behat/Resources/config/services/contexts/ui.xml
src/Sylius/Behat/Resources/config/services/pages/admin/catalog_promotion.xml
src/Sylius/Behat/Resources/config/suites/api/promotion/managing_catalog_promotions.yml
src/Sylius/Behat/Resources/config/suites/ui/promotion/managing_catalog_promotions.yml
src/Sylius/Bundle/AdminBundle/Resources/config/grids/catalog_promotion.yaml
src/Sylius/Bundle/AdminBundle/Resources/config/routing/catalog_promotion.yaml
src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/_form.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/Grid/Field/_channels.html.twig
src/Sylius/Bundle/CoreBundle/Form/Extension/CatalogPromotionTypeExtension.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionTranslationType.php
src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionType.php
src/Sylius/Bundle/PromotionBundle/Resources/config/services/forms.xml
src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml

[CatalogPromotion][Admin] Add creating catalog promotion

---

features/promotion/managing_catalog_promotions/editing_catalog_promotion.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElement.php
src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElementInterface.php
src/Sylius/Behat/Page/Admin/CatalogPromotion/UpdatePage.php
src/Sylius/Behat/Page/Admin/CatalogPromotion/UpdatePageInterface.php
src/Sylius/Behat/Resources/config/services/contexts/ui.xml
src/Sylius/Behat/Resources/config/services/elements/admin.xml
src/Sylius/Behat/Resources/config/services/pages/admin/catalog_promotion.xml
src/Sylius/Behat/Resources/config/suites/ui/promotion/managing_catalog_promotions.yml
src/Sylius/Bundle/AdminBundle/Resources/config/grids/catalog_promotion.yaml
src/Sylius/Bundle/AdminBundle/Resources/config/routing/catalog_promotion.yaml

[CatalogPromotion][Admin] Add editing catalog promotions

---

features/promotion/managing_catalog_promotions/creating_catalog_promotion.feature
features/promotion/managing_catalog_promotions/validating_catalog_promotion.feature
features/promotion/managing_catalog_promotions/validating_catalog_promotion_creation.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml
src/Sylius/Bundle/CoreBundle/Resources/config/validation/CatalogPromotion.xml
src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
src/Sylius/Bundle/CoreBundle/Validator/Constraints/CatalogPromotionRules.php
src/Sylius/Bundle/CoreBundle/Validator/Constraints/CatalogPromotionRulesValidator.php
src/Sylius/Bundle/CoreBundle/spec/Validator/Constraints/CatalogPromotionRulesValidatorSpec.php

Add validation for Catalog Promotion Rules

---

docs/cookbook/frontend/webpack.rst

I wrote the path I have with the 1.8
<del>I forget to change also :
`{{ asset('build/shop/images/logo.png', 'shop') }}`
instead of `{{ asset('assets/shop/img/logo.png') }}`</del> ~fixed by @CoderMaggie 🖖🏼 

logo path corrected

---

docs/book/plugins/guide/naming.rst

Missing Behat directory on the path to be excluded

---

features/promotion/managing_catalog_promotions/creating_catalog_promotion.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php

[Behat] move actions redirect to different step

---

docs/book/contributing/documentation/overview.rst

Note about simple docker builder. No need to install python and pip for this 🎉 
https://github.com/arti0090/SyliusDocumentationBuilder

[DOCS] Add note about docker builder

---

docs/book/themes/themes.rst

| Branch?         | 1.10 
| Related tickets | mentioned in https://github.com/Sylius/Sylius/issues/12783

[Documentation] Fixed Incorrect Theme Directory And Incorrect Import Paths

---

features/promotion/applying_catalog_promotions/seeing_applied_catalog_promotion_on_variant.feature
src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php

Scenario that will extend https://github.com/Sylius/Sylius/pull/13035

[CP] Add scenario for `Inform about promotions applied on variant`

---

features/promotion/managing_catalog_promotions/editing_catalog_promotion.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php

[UI][Behat] tests for editing catalog promotion with rule and action

---

features/promotion/applying_catalog_promotions/applying_catalog_promotions_for_variant.feature
features/promotion/applying_catalog_promotions/seeing_applied_catalog_promotion_on_variant.feature
features/promotion/applying_catalog_promotions/seeing_applied_catalog_promotions_on_variants_list.feature
src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
src/Sylius/Bundle/CoreBundle/Applicator/CatalogPromotionApplicator.php
src/Sylius/Bundle/CoreBundle/EventListener/CatalogPromotionEventListener.php

| Bug fix?        | kind of (fix bug for feature)

Fix persisting of Catalog Promotion data on create

---

features/promotion/managing_catalog_promotions/creating_catalog_promotion.feature
features/promotion/managing_catalog_promotions/editing_catalog_promotion.feature
features/promotion/managing_catalog_promotions/validating_catalog_promotion_creation.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php

[CatalogPromotion][Behat] Improve steps names

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml

| Related tickets | fixes https://github.com/Sylius/Sylius/pull/13055

[CatalogPromotion] Fix configuration of fixtures for actions and rules

---

src/Sylius/Bundle/CoreBundle/Resources/config/services.xml

| Bug fix?        | ?
Small fix/improvement for better autowiring support

[Minor][DI] Add interface alias to UriBasedSectionProvider

---

docs/getting-started-with-sylius/shop-customizations.rst

| Branch?         | 1.9 
Fixed path to logo template file

[Documentation] Fixed logo customization 

---

docs/book/orders/adjustments.rst
docs/book/orders/cart-promotions.rst
docs/book/orders/coupons.rst
docs/book/orders/index.rst
docs/book/orders/map.rst.inc
docs/components_and_bundles/bundles/SyliusPromotionBundle/action_applicator.rst
docs/components_and_bundles/bundles/SyliusPromotionBundle/index.rst
docs/components_and_bundles/components/Promotion/index.rst

[DOCS] Rename promotions to cart promotions

---

features/promotion/managing_catalog_promotions/validating_catalog_promotion_creation.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElement.php
src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElementInterface.php
src/Sylius/Behat/Resources/config/services/contexts/ui.xml
src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/_form.html.twig

[CatalogPromotions][Api] Add test for creation rule

---

features/promotion/managing_catalog_promotions/validating_catalog_promotion_creation.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en.yml
src/Sylius/Bundle/PromotionBundle/Validator/CatalogPromotionActionValidator.php
src/Sylius/Bundle/PromotionBundle/Validator/Constraints/CatalogPromotionAction.php
src/Sylius/Bundle/PromotionBundle/spec/Validator/CatalogPromotionActionValidatorSpec.php
tests/Api/Admin/CatalogPromotionsTest.php
tests/Api/Responses/Expected/admin/catalog_promotion/post_catalog_promotion_with_invalid_actions_response.json

[API] [Catalog Promotion] validate action amount

---

src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
src/Sylius/Bundle/CoreBundle/Formatter/AppliedPromotionInformationFormatter.php
src/Sylius/Bundle/CoreBundle/Formatter/AppliedPromotionInformationFormatterInterface.php
src/Sylius/Bundle/CoreBundle/Processor/CatalogPromotionProcessor.php
src/Sylius/Bundle/CoreBundle/spec/Formatter/AppliedPromotionInformationFormatterSpec.php

[CatalogPromotions] Modify AppliedPromotionInformationFormatter

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CatalogPromotion.xml

[CatalogPromotion][API] Add examples of rules and actions to Swagger

---

src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
src/Sylius/Bundle/CoreBundle/Formatter/AppliedPromotionInformationFormatter.php
src/Sylius/Bundle/CoreBundle/spec/Formatter/AppliedPromotionInformationFormatterSpec.php

Missing part of #13035 Pull request

[CatalogPromotions] Add missing description to applied promotions

---

docs/book/products/catalog_promotions.rst
docs/book/products/index.rst
docs/book/products/map.rst.inc

[DOCS]Add Catalog Promotion documentation

---

features/promotion/applying_catalog_promotions/applying_catalog_promotions_for_variant.feature

[CatalogPromotions] Add api behat for multiple catalog promotions

---

features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_after_editing_its_channels.feature
src/Sylius/Behat/Client/ApiClientInterface.php
src/Sylius/Behat/Client/ApiPlatformClient.php
src/Sylius/Behat/Client/Request.php
src/Sylius/Behat/Client/RequestInterface.php
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Context/Setup/ChannelContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/promotion/applying_catalog_promotions.yml

[CatalogPromotion][Behat] Add scenarios for reapplying catalog promotions after editing its channels

---

docs/cookbook/payments/custom-payment-gateway.rst

In my projects I tend to use YAML for the configuration files so I thought it might be helpful to others to add configuration examples in the YAML format
| Branch?         | 1.9, 1.10 or master 

Add yaml configuration examples to the "Custom Payment Gateway" cookbook

---

docs/book/products/catalog_promotions.rst

[Catalog Promotions][Docs] Add a section about how promotions are applied

---

features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_after_editing_its_channels.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ChannelPricingRepository.php
src/Sylius/Bundle/CoreBundle/EventListener/CatalogPromotionEventListener.php
src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionCreateListener.php
src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionUpdateListener.php
src/Sylius/Bundle/CoreBundle/Processor/CatalogPromotionClearer.php
src/Sylius/Bundle/CoreBundle/Processor/CatalogPromotionClearerInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
src/Sylius/Bundle/CoreBundle/spec/EventListener/CatalogPromotionEventListenerSpec.php
src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionCreateListenerSpec.php
src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionUpdateListenerSpec.php
src/Sylius/Bundle/CoreBundle/spec/Processor/CatalogPromotionClearerSpec.php
src/Sylius/Bundle/CoreBundle/spec/Processor/CatalogPromotionProcessorSpec.php
src/Sylius/Component/Core/Model/ChannelPricing.php
src/Sylius/Component/Core/Model/ChannelPricingInterface.php
src/Sylius/Component/Core/Repository/ChannelPricingRepositoryInterface.php
src/Sylius/Component/Core/spec/Model/ChannelPricingSpec.php
src/Sylius/Component/Promotion/Event/CatalogPromotionCreated.php

[CatalogPromotion] Clear applied catalog promotions after updating

---

features/cart/shopping_cart/adding_product_with_discounted_catalog_price_to_cart.feature
features/cart/shopping_cart/adding_product_with_variants_with_discounted_catalog_price_to_cart.feature
features/product/viewing_products/viewing_different_discounted_price_for_different_product_variants.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Resources/config/suites/api/cart/shopping_cart.yml
src/Sylius/Behat/Resources/config/suites/ui/cart/shopping_cart.yml

[CatalogPromotions] Add product to cart with discounted catalog price

---

features/cart/shopping_cart/adding_product_with_discounted_catalog_price_to_cart.feature
features/cart/shopping_cart/adding_product_with_variants_with_discounted_catalog_price_to_cart.feature
src/Sylius/Behat/Context/Ui/Shop/CartContext.php
src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
src/Sylius/Behat/Resources/config/suites/ui/cart/shopping_cart.yml
src/Sylius/Bundle/ShopBundle/Resources/config/services/twig.xml
src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_item.html.twig
src/Sylius/Bundle/ShopBundle/Twig/OrderItemOriginalPriceToDisplayExtension.php

[UI][Catalog Promotion] Add discounted product to cart

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ChannelPricingRepository.php

| Related tickets | fixes https://github.com/Sylius/Sylius/pull/13100#discussion_r708061317

[ChannelPricing] Improve query for finding discounted pricings

---

src/Sylius/Bundle/ApiBundle/Command/Account/RegisterShopUser.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Account/RegisterShopUserHandler.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Account/RegisterShopUserHandlerSpec.php
tests/Api/Shop/CustomersTest.php

| BC breaks?      | no (kind of)

[API] Remove phoneNumber from Customer command and handler

---

UPGRADE-API-1.11.md
src/Sylius/Behat/Client/Request.php
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
tests/Api/Responses/Expected/shop/add_item_response.json
tests/Api/Shop/OrdersTest.php

[API] Use POST action to add new item to cart

---

src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_breadcrumb.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Index/_breadcrumb.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_breadcrumb.html.twig

Feat: Add breadcrumb var in CRUD template for AdminBundle

---

features/promotion/applying_catalog_promotions/reapplying_multiple_catalog_promotions_after_editing_their_channels.feature
features/promotion/applying_catalog_promotions/reapplying_single_catalog_promotion_after_editing_its_channels.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
src/Sylius/Behat/Resources/config/suites/api/promotion/applying_catalog_promotions.yml
src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionUpdateListener.php
src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionUpdateListenerSpec.php

[CatalogPromotion][API] Reapplying catalog promotions after update its channel

---

.github/workflows/application.yml
config/packages/doctrine.yaml

| Bugfix?        | no
🖖 Hello, Sylius community,
We want to be better at supporting DB like Postgresql & MariaDB. So our first step in this direction is running our test suite on these DBs. To see what is not working correctly. Next steps -> fix these errors one by one. Stay tuned! 🖖

[Maintenance] Configure builds on postgressql & mariadb

---

src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml
tests/Api/Responses/Expected/shop/update_customer_response.json
tests/Api/Responses/Expected/shop/updated_gender_customer_response.json
tests/Api/Shop/CustomersTest.php

[API] Add gender field to customer

---

phpstan.neon.dist

[Build] ignore string inflector phpstan

---

features/promotion/managing_catalog_promotions/creating_catalog_promotion.feature
features/promotion/managing_catalog_promotions/editing_catalog_promotion.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElement.php
src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElementInterface.php
src/Sylius/Behat/Resources/config/suites/api/promotion/managing_catalog_promotions.yml
src/Sylius/Behat/Resources/config/suites/ui/promotion/managing_catalog_promotions.yml
src/Sylius/Bundle/AdminBundle/Resources/config/grids/catalog_promotion.yaml
src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/_form.html.twig
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CatalogPromotion.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/CatalogPromotion.xml
src/Sylius/Bundle/CoreBundle/Migrations/Version20210921093619.php
src/Sylius/Bundle/CoreBundle/Processor/CatalogPromotionProcessor.php
src/Sylius/Bundle/CoreBundle/spec/Processor/CatalogPromotionProcessorSpec.php
src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionType.php
src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/CatalogPromotion.orm.xml
src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
src/Sylius/Component/Promotion/Model/CatalogPromotion.php
src/Sylius/Component/Promotion/Model/CatalogPromotionInterface.php
tests/Api/Admin/CatalogPromotionsTest.php
tests/Api/DataFixtures/ORM/catalog_promotion.yaml
tests/Api/Responses/Expected/admin/catalog_promotion/get_catalog_promotion_response.json
tests/Api/Responses/Expected/admin/catalog_promotion/get_catalog_promotions_response.json
tests/Api/Responses/Expected/admin/catalog_promotion/post_catalog_promotion_response.json
tests/Api/Responses/Expected/admin/catalog_promotion/put_catalog_promotion_response.json

[API][UI] Toggle catalog promotion

---

features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_after_editing_its_action.feature
features/promotion/applying_catalog_promotions/reapplying_multiple_catalog_promotions_after_editing_their_channels.feature
features/promotion/applying_catalog_promotions/reapplying_single_catalog_promotion_after_editing_its_channels.feature
src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Ui/Admin/ProductShowPageContext.php
src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElement.php
src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElementInterface.php
src/Sylius/Behat/Page/Shop/Product/ShowPage.php
src/Sylius/Behat/Resources/config/services/contexts/ui.xml
src/Sylius/Behat/Resources/config/suites/ui/promotion/applying_catalog_promotions.yml
src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_price.html.twig
src/Sylius/Component/Core/Model/ChannelPricing.php

[CatalogPromotion][Behat] Cover scenarios for reapplying catalog promotions

---

src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml

[GUS] Update gus url

---

src/Sylius/Bundle/ApiBundle/Resources/config/services/swagger.xml
src/Sylius/Bundle/ApiBundle/Swagger/PathHiderDocumentationNormalizer.php

| New feature?    | 
The great comeback of admin authentication route 🎉 
🎉

[API] Fix admin path in swagger

---

src/Sylius/Bundle/CoreBundle/Provider/CatalogPromotionVariantsProvider.php
src/Sylius/Bundle/CoreBundle/Provider/ForVariantsRuleVariantsProvider.php
src/Sylius/Bundle/CoreBundle/Provider/VariantsProviderInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/spec/Provider/CatalogPromotionVariantsProviderSpec.php
src/Sylius/Bundle/CoreBundle/spec/Provider/ForVariantsRuleVariantsProviderSpec.php
src/Sylius/Component/Core/Model/CatalogPromotionRuleInterface.php

[API][CatalogPromotion] refactor Variants Provider to strategy Pattern

---

adr/2021_06_15_api_platform_config_customization.md
docs/customization/api/customizing_endpoints_using_yaml.rst
src/Sylius/Bundle/ApiBundle/ApiPlatform/ApiResourceConfigurationMerger.php
src/Sylius/Bundle/ApiBundle/spec/ApiPlatform/ApiResourceConfigurationMergerSpec.php
src/Sylius/Bundle/ApiBundle/spec/ApiPlatform/ResourceMetadataPropertyValueResolverSpec.php
src/Sylius/Bundle/ApiBundle/test/config/api_platform/config.yaml

[API] Refactor path removal with (unset)

---

features/checkout/seeing_order_summary/seeing_current_prices_of_products_after_catalog_promotion_becomes_ineligible.feature
src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
src/Sylius/Behat/Resources/config/services/contexts/setup.xml
src/Sylius/Bundle/ApiBundle/EventSubscriber/CatalogPromotionEventSubscriber.php
src/Sylius/Bundle/ApiBundle/spec/EventSubscriber/CatalogPromotionEventSubscriberSpec.php
src/Sylius/Bundle/CoreBundle/EventListener/CatalogPromotionEventListener.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionExampleFactory.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
src/Sylius/Bundle/CoreBundle/spec/EventListener/CatalogPromotionEventListenerSpec.php

[CatalogPromotion] Refactor to not listen on Doctrine events

---

features/promotion/applying_catalog_promotions/applying_all_available_types_catalog_promotions.feature
features/promotion/applying_catalog_promotions/applying_catalog_promotions_for_taxon.feature
features/promotion/managing_catalog_promotions/creating_catalog_promotion.feature
features/promotion/managing_catalog_promotions/editing_catalog_promotion.feature
features/promotion/managing_catalog_promotions/validating_catalog_promotion_creation.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php
src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
src/Sylius/Behat/Context/Setup/ChannelContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/promotion/managing_catalog_promotions.yml
src/Sylius/Behat/Resources/config/suites/ui/promotion/managing_catalog_promotions.yml
src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductVariantRepository.php
src/Sylius/Bundle/CoreBundle/Provider/CatalogPromotionVariantsProvider.php
src/Sylius/Bundle/CoreBundle/Provider/ForTaxonsRuleVariantsProvider.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml
src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
src/Sylius/Bundle/CoreBundle/Validator/Constraints/CatalogPromotionRule.php
src/Sylius/Bundle/CoreBundle/Validator/Constraints/CatalogPromotionRuleValidator.php
src/Sylius/Bundle/CoreBundle/spec/Provider/ForTaxonsRuleVariantsProviderSpec.php
src/Sylius/Bundle/CoreBundle/spec/Validator/Constraints/CatalogPromotionRuleValidatorSpec.php
src/Sylius/Component/Core/Model/CatalogPromotionRuleInterface.php
src/Sylius/Component/Core/Repository/ProductVariantRepositoryInterface.php

Based on https://github.com/Sylius/Sylius/pull/13137

[Api] CatalogPromotionRule per taxon

---

src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/_form.html.twig

[CatalogPromotion] change change channel with toggle in UI

---

CONFLICTS.md
composer.json

[HotFix] Add conflict to doctrine/orm to fix the problem with creating taxons

---

docs/bdd/how-to-use-transformers.rst
docs/book/architecture/emails.rst
docs/book/orders/returns.rst
docs/book/themes/themes.rst
docs/customization/model.rst

Just cleaning up some typos in the docs

[docs] typofixes

---

src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml

| Related tickets | fixes https://github.com/Sylius/Sylius/pull/13161
Before:
After:

[CatalogPromotion] Minor fixes after renaming rule to scope

---

features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_on_taxon_once_its_data_changes.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php

[Catalog Promotions] Reapply CP after changing its taxons

---

composer.json

Fix composer.json file after rebase

---

docs/book/organization/team.rst
docs/requirements.txt

Long time, no update :) 
We've said goodbye this year to some of our core team members (@pamil, @Tomanhez and @arti0090 very soon 👋🏼 😿 ) and we've welcomed @Arminek back!
P.S. [We're recruiting](https://sylius.com/company/join/)!

[Docs][The Book] Update the Core Team members

---

features/promotion/applying_catalog_promotions/applying_catalog_promotions_in_proper_time_range.feature
features/promotion/managing_catalog_promotions/editing_catalog_promotion.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Setup/AdminSecurityContext.php
src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Page/Admin/CatalogPromotion/CreatePage.php
src/Sylius/Behat/Page/Admin/CatalogPromotion/UpdatePage.php
src/Sylius/Behat/Page/Admin/CatalogPromotion/UpdatePageInterface.php
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/CatalogPromotion.xml
src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionType.php
src/Sylius/Bundle/PromotionBundle/Resources/config/validation/CatalogPromotion.xml
src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en.yml
tests/Api/Admin/CatalogPromotionsTest.php
tests/Api/Responses/Expected/admin/catalog_promotion/post_catalog_promotion_with_invalid_dates_response.json

[CatalogPromotion] dates are editable and validated

---

CONFLICTS.md

| Related tickets | https://github.com/Sylius/Sylius/pull/13252#issuecomment-953665585

[Maintenance] Add note about doctrine/dbal requirement

---

.github/workflows/application.yml
src/Sylius/Behat/Resources/config/suites/api/account/email_verification.yml
src/Sylius/Behat/Resources/config/suites/api/inventory/cart_inventory.yml
src/Sylius/Behat/Resources/config/suites/api/inventory/checkout_inventory.yaml
src/Sylius/Behat/Resources/config/suites/api/locale/locales.yaml
src/Sylius/Behat/Resources/config/suites/api/product/adding_product_review.yml
src/Sylius/Behat/Resources/config/suites/api/product/viewing_product_reviews.yml
src/Sylius/Behat/Resources/config/suites/api/promotion/applying_catalog_promotions.yml
src/Sylius/Behat/Resources/config/suites/api/promotion/applying_promotion_rules.yml
src/Sylius/Behat/Resources/config/suites/api/promotion/managing_catalog_promotions.yml
src/Sylius/Behat/Resources/config/suites/api/taxation/applying_taxes.yml
src/Sylius/Behat/Resources/config/suites/ui/promotion/applying_catalog_promotions.yml
src/Sylius/Behat/Resources/config/suites/ui/promotion/managing_catalog_promotions.yml

| Related tickets | continuation of #13278

[Behat] Remove deprecated whitespace from behat tags on master

---

src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php

| Related tickets | revert changes from https://github.com/Sylius/Sylius/pull/13244

[API] Revert changes of checked keys in cart and checkout responses to fix the build

---

features/currency/switching_current_currency.feature
src/Sylius/Behat/Context/Api/Shop/CurrencyContext.php
src/Sylius/Behat/Resources/config/services/api.xml
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/currency/currencies.yml
src/Sylius/Bundle/ApiBundle/DataProvider/CurrencyCollectionDataProvider.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
src/Sylius/Bundle/ApiBundle/spec/DataProvider/CurrencyCollectionDataProviderSpec.php

List of channel currencies endpoint

---

features/product/viewing_products/viewing_products_sorted_by_their_discounted_price.feature
features/product/viewing_products/viewing_sorted_products.feature
src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
src/Sylius/Behat/Resources/config/suites/api/product/viewing_products.yml
src/Sylius/Behat/Resources/config/suites/ui/product/viewing_products.yml
src/Sylius/Bundle/ApiBundle/Doctrine/Filter/ProductPriceOrderFilter.php
src/Sylius/Bundle/ApiBundle/Filter/TaxonFilter.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
src/Sylius/Bundle/ApiBundle/spec/Filter/TaxonFilterSpec.php

[API][UI] Sort products by their discounted price

---

adr/2021_06_15_api_platform_config_customization.md

Fix `adr/2021_06_15_api_platform_config_customization.md` documentation link

[Adr] Fix customization api documentation url

---

src/Sylius/Bundle/ApiBundle/CommandHandler/Account/ResetPasswordHandler.php

| Branch?         | 1.9, 1.10 or master 
This line is always true, since we are getting user by password token

Code cleanup - user password reset

---

src/Sylius/Behat/Context/Api/Shop/CurrencyContext.php

| Related tickets | https://github.com/Sylius/Sylius/pull/13287#discussion_r751150305

[Minor][Behat] Style and type refactor

---

src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/AdminUserExampleFactory.php
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/AdminUser.orm.xml
src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
src/Sylius/Component/Core/Model/AvatarImageInterface.php

| Related tickets | fixes #11163 

[Core] added default factory for avatar image

---

src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/CoreBundle/Fixture/Factory/AdminUserExampleFactory.php

| Related tickets | fixes to https://github.com/Sylius/Sylius/pull/11751

[Minor] Removal of additional spaces and deprecation version fix

---

features/checkout/addressing_order/changing_address_during_checkout.feature
features/checkout/being_able_to_modify_remaining_steps.feature
features/checkout/preventing_starting_checkout_with_empty_cart.feature
features/checkout/shipping_order/returning_from_shipping_step_to_addressing_step.feature
features/checkout/skipping_shipping_and_payment_step_when_order_does_not_require_any_shipping_and_its_total_is_zero.feature

[Behat] Skip ui based checkout steps in api coverage

---

docs/book/installation/requirements.rst

| Related tickets | after https://github.com/Sylius/Sylius/pull/13338

[Documentation] Update required version of PHP

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Adjustment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/OrderItem.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Adjustment.xml
tests/Api/Responses/Expected/shop/get_order_adjustments_response.json
tests/Api/Responses/Expected/shop/get_order_item_adjustments_response.json
tests/Api/Responses/Expected/shop/get_order_items_response.json
tests/Api/Shop/OrdersTest.php

| Related tickets | https://github.com/Sylius/Sylius/issues/13023

Order items list and order/item adjustments serialization groups

---

src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/AcceptedProductReviewsExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/AddressesExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/CountryCollectionExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/CurrencyCollectionExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/LocaleCollectionExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/OrdersByLoggedInUserExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/ProductsByChannelAndLocaleCodeExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/ProductsWithEnableFlagExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/TaxonCollectionExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/AddressItemExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderGetMethodItemExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderMethodsItemExtension.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/AcceptedProductReviewsExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/AddressesExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/CountryCollectionExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/CurrencyCollectionExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/LocaleCollectionExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/OrdersByLoggedInUserExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/ProductsByChannelAndLocaleCodeExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/ProductsWithEnableFlagExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/TaxonCollectionExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/AddressItemExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderGetMethodItemExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderMethodsItemExtensionSpec.php

Use QueryNameGenerator for extension query parameters

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Shipment.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
src/Sylius/Bundle/ApiBundle/Serializer/ShippingMethodNormalizer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ShippingMethodNormalizerSpec.php
tests/Api/Responses/Expected/shop/get_order_shipping_methods_response.json
tests/Api/Shop/ShippingMethodsTest.php

Shipments and order shipments endpoints serializations made consistent

---

docs/customization/api/serialization_customization.rst

I was implementing my own ProductNormalizer and found some issues in the docs:
1. The example used the NormalizerAwareTrait, but for autowiring constructor injection might be easier.
2. It was not clear in the example which service I had to inject for the normalizer, turns out it was `@api_platform.serializer.normalizer.item`
3. The example referenced a `defaultProductVariantResolver`, but that property did not exist, so I added it.

Corrections for adding a field to the response

---

docs/book/products/pricing.rst

[Minimum Price] documentation

---

docs/getting-started-with-sylius/installation.rst
src/Sylius/Bundle/CoreBundle/Command/InstallCommand.php
src/Sylius/Bundle/CoreBundle/Command/JwtConfigurationCommand.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/commands.xml

[Command] add command to generate jwt

---

features/promotion/receiving_discount/receiving_discounts_with_product_minimum_price_specified.feature
features/promotion/receiving_discount/receiving_fixed_discount_from_cart_promotions_only_on_non_discounted_products.feature
features/promotion/receiving_discount/receiving_percentage_discount_from_cart_promotions_only_on_non_discounted_products.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Setup/PromotionContext.php
src/Sylius/Behat/Context/Ui/Shop/CartContext.php
src/Sylius/Behat/Resources/config/suites/api/promotion/receiving_discount.yml
src/Sylius/Behat/Resources/config/suites/ui/promotion/receiving_discount.yml
src/Sylius/Component/Core/Distributor/MinimumPriceDistributor.php
src/Sylius/Component/Core/Distributor/MinimumPriceDistributorInterface.php
src/Sylius/Component/Core/Distributor/ProportionalIntegerDistributor.php
src/Sylius/Component/Core/Model/Order.php
src/Sylius/Component/Core/Model/OrderInterface.php
src/Sylius/Component/Core/Promotion/Action/FixedDiscountPromotionActionCommand.php
src/Sylius/Component/Core/Promotion/Action/PercentageDiscountPromotionActionCommand.php
src/Sylius/Component/Core/Promotion/Action/UnitDiscountPromotionActionCommand.php
src/Sylius/Component/Core/spec/Distributor/MinimumPriceDistributorSpec.php
src/Sylius/Component/Core/spec/Distributor/ProportionalIntegerDistributorSpec.php
src/Sylius/Component/Core/spec/Model/OrderSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/FixedDiscountPromotionActionCommandSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/PercentageDiscountPromotionActionCommandSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/UnitFixedDiscountPromotionActionCommandSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/UnitPercentageDiscountPromotionActionCommandSpec.php

| Related tickets | based on #13328

[CartPromotion][CatalogPromotion] Receiving discount only on non discounted products

---

CONFLICTS.md

| Related tickets | Leftover from https://github.com/Sylius/Sylius/pull/13357 and https://github.com/Sylius/Sylius/pull/13358

[Docs] Add missing references in CONFLICT.md

---

src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_channelPricings.html.twig

You can find new note about minimum price here:

Explanation note about minimum price in product variant creation form

---

.github/PULL_REQUEST_TEMPLATE.md

[Minor] Update possible branch version in GitHub PR template

---

config/packages/test_cached/_sylius.yaml
config/packages/test_cached/fidry_alice_data_fixtures.yaml
config/packages/test_cached/framework.yaml
config/packages/test_cached/security.yaml
config/packages/test_cached/swiftmailer.yaml
config/packages/test_cached/sylius_theme.yaml
config/packages/test_cached/twig.yaml

Remove duplications in test_cached config

---

src/Sylius/Bundle/ApiBundle/Doctrine/Filter/ExchangeRateFilter.php
src/Sylius/Bundle/ApiBundle/Doctrine/Filter/ProductVariantOptionValueFilter.php
src/Sylius/Bundle/ApiBundle/Doctrine/Filter/TranslationOrderNameAndLocaleFilter.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderMethodsItemExtension.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderMethodsItemExtensionSpec.php

[API] Doctrine extension parameter names and aliases refactor

---

features/promotion/managing_catalog_promotions/editing_catalog_promotion.feature
features/promotion/managing_catalog_promotions/validating_catalog_promotion_creation.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
src/Sylius/Bundle/CoreBundle/Validator/CatalogPromotionAction/FixedDiscountActionValidator.php
src/Sylius/Bundle/CoreBundle/spec/Validator/CatalogPromotionAction/FixedDiscountActionValidatorSpec.php
src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionActionType.php
src/Sylius/Component/Core/Model/CatalogPromotionInterface.php
tests/Api/Responses/Expected/admin/catalog_promotion/post_catalog_promotion_with_invalid_actions_response.json

[BUG] Check action type for fixed promotion

---

tests/Api/DataFixtures/ORM/address_with_customer.yaml
tests/Api/JsonApiTestCase.php
tests/Api/Responses/Expected/shop/create_address_response.json
tests/Api/Responses/Expected/shop/get_addresses_response.json
tests/Api/Responses/Expected/shop/get_an_address_response.json
tests/Api/Shop/AddressesGetTest.php
tests/Api/Shop/AddressesPostTest.php

[Shop][API] Contract tests for an Address resource, customer authorization refactor

---

src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
tests/Api/Shop/ProductVariantsTest.php

[Test][API][Refactor] CardContext, ProductVariant and Taxon resource 

---

UPGRADE-API-1.11.md
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Taxon.xml
src/Sylius/Component/Core/Model/Product.php
tests/Api/Responses/Expected/shop/get_taxonomy_response.json
tests/Api/Responses/Expected/shop/product/get_product_with_default_locale_translation.json

[Shop][Api] Translatable resources api docs, included slug field in a Taxon and Product responses

---

UPGRADE-API-1.11.md
src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PaymentMethod.xml
tests/Api/Responses/Expected/shop/get_order_payment_methods_response.json
tests/Api/Shop/PaymentMethodsTest.php

[API][SHOP] serialization of Payment and PaymentMethod - dynamic translation refactor

---

config/preload.php

Add support for [OPCache class preloading](https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading). The file has been copied from the Flex recipe.

feat: add support for OPcache class preloading

---

docs/book/products/catalog_promotions.rst

[Minor] Lineup documentation

---

src/Sylius/Bundle/AttributeBundle/README.md
src/Sylius/Bundle/ChannelBundle/README.md
src/Sylius/Bundle/CoreBundle/README.md
src/Sylius/Bundle/CurrencyBundle/README.md
src/Sylius/Bundle/CustomerBundle/README.md
src/Sylius/Bundle/InventoryBundle/README.md
src/Sylius/Bundle/LocaleBundle/README.md
src/Sylius/Bundle/MoneyBundle/README.md
src/Sylius/Bundle/OrderBundle/README.md
src/Sylius/Bundle/PaymentBundle/README.md
src/Sylius/Bundle/PaymentBundle/SyliusPaymentBundle.php
src/Sylius/Bundle/ProductBundle/README.md
src/Sylius/Bundle/PromotionBundle/README.md
src/Sylius/Bundle/ShippingBundle/README.md
src/Sylius/Bundle/TaxationBundle/README.md
src/Sylius/Bundle/TaxonomyBundle/README.md
src/Sylius/Bundle/UserBundle/README.md

Symfony2 is no more 💃

---

src/Sylius/Bundle/OrderBundle/Tests/DependencyInjection/SyliusOrderExtensionTest.php

[Maintenance] Do not skip auto-configuration tests

---

.github/workflows/application.yml
composer.json
phparkitect.php
symfony.lock

This is my first try to use [PHPArkitect](https://github.com/phparkitect/arkitect) tool - but it seems promising! I believe with this library we could ensure some architectural conventions and proper dependencies. Let me know what you think about it 🖖 🚀 🏗️

Architecture tests initialization 

---

tests/Api/Admin/CatalogPromotionsTest.php
tests/Api/Responses/Expected/admin/catalog_promotion/post_catalog_promotion_response.json

[CatalogPromotion] Fix dates in contract tests

---

src/Sylius/Behat/Context/Api/Admin/ManagingTaxonsContext.php

| Related tickets | fixes #13434

[Behat] [Taxons] Fixed issue with asserting Taxons

---

src/Sylius/Bundle/CoreBundle/Resources/config/services.xml

Before and after code changes:

Applied promotion information formatter service configuration cleanup

---

src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteSubscriber.php
src/Sylius/Bundle/ApiBundle/Context/TokenValueBasedCartContext.php
src/Sylius/Bundle/ApiBundle/spec/Context/TokenValueBasedCartContextSpec.php
src/Sylius/Bundle/ChannelBundle/Context/FakeChannel/FakeChannelContext.php
src/Sylius/Bundle/ChannelBundle/spec/Context/FakeChannel/FakeChannelContextSpec.php
src/Sylius/Bundle/CoreBundle/Checkout/CheckoutResolver.php
src/Sylius/Bundle/LocaleBundle/Context/RequestBasedLocaleContext.php
src/Sylius/Bundle/LocaleBundle/spec/Context/RequestBasedLocaleContextSpec.php
src/Sylius/Bundle/ShopBundle/EventListener/NonChannelLocaleListener.php
src/Sylius/Bundle/ShopBundle/EventListener/SessionCartSubscriber.php
src/Sylius/Bundle/ShopBundle/spec/EventListener/NonChannelLocaleListenerSpec.php
src/Sylius/Component/Channel/Context/CachedPerRequestChannelContext.php
src/Sylius/Component/Channel/Context/RequestBased/ChannelContext.php
src/Sylius/Component/Channel/spec/Context/CachedPerRequestChannelContextSpec.php
src/Sylius/Component/Channel/spec/Context/RequestBased/ChannelContextSpec.php

| Deprecations?   | removing deprecations
For now, it should accept both until Symfony <5.3 support is dropped

Change all MasterRequest calls to MainRequest

---

docs/book/products/catalog_promotions.rst
features/promotion/managing_catalog_promotions/browsing_catalog_promotions.feature
features/promotion/managing_catalog_promotions/prioritizing_catalog_promotions.feature
features/promotion/managing_catalog_promotions/seeing_catalog_promotion_details.feature
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/CatalogPromotion.orm.xml
tests/Api/Responses/Expected/admin/catalog_promotion/put_catalog_promotion_response.json

Catalog promotion priority

---

docs/book/products/catalog_promotions.rst
src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php
src/Sylius/Bundle/ApiBundle/EventSubscriber/CatalogPromotionEventSubscriber.php
src/Sylius/Bundle/ApiBundle/spec/EventSubscriber/CatalogPromotionEventSubscriberSpec.php
src/Sylius/Bundle/CoreBundle/EventListener/CatalogPromotionEventListener.php
src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionCreatedListener.php
src/Sylius/Bundle/CoreBundle/Resources/config/app/messenger.yaml
src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
src/Sylius/Bundle/CoreBundle/spec/EventListener/CatalogPromotionEventListenerSpec.php
src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionCreatedListenerSpec.php
src/Sylius/Component/Promotion/Event/CatalogPromotionCreated.php

[CatalogPromotion] Introduce CatalogPromotionCreated event

---

.github/workflows/application.yml

[CI] bin/console lint:container - command added to workflow

---

docs/cookbook/promotions/custom-catalog-promotion-action.rst
docs/cookbook/promotions/custom-catalog-promotion-scope.rst

Inform about hardcoded keys in catalog promotion scopes/actions translations

[Docs] add info about hardcoded translations

---

features/promotion/managing_catalog_promotions/toggling_catalog_promotion.feature

[Minor][Behat] Change feature name to reflect convention and reality

---

.github/workflows/application.yml

Using phparkitect github actions

---

CHANGELOG-1.10.md

Unify latest CHANGELOGs format with the previous ones

---

docs/book/organization/team.rst

I've updated our current Core Team list and removed obsolete or low level roles from the list

[Documentation] Update Core Team in our documentation

---

src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionActionType.php

[CatalogPromotion] refactor action type

---

docs/cookbook/payments/customizing-credit-memo.rst

images should be in the public catalog.

change suggested path in refund docs

---

composer.json

Use sylius-labs/coding-standards 4.2

---

docs/book/plugins/guide/implementation.rst

| Related tickets | fixes #13508 

[Docs] Change the template path in customization

---

.github/workflows/packages.yml

| Related tickets | leftovers after https://github.com/Sylius/Sylius/pull/13515

[Build fix] Remove unneeded test package binary step

---

.github/workflows/packages.yml

| Related tickets | Comments from https://github.com/Sylius/Sylius/pull/13515

[Minor] Typo fixes in github packages config

---

src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-catalog-promotion-actions.js
src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-catalog-promotion-scopes.js

| Related tickets | fixes #13447

[Promotion] Fix js errors associated with actions/rules/scopes

---

docs/bdd/basic-usage.rst
docs/book/customers/admin_user.rst
docs/book/installation/sylius_plus_installation.rst
docs/book/orders/orders.rst
docs/book/plugins/creating-plugin.rst
docs/components_and_bundles/bundles/SyliusOrderBundle/installation.rst
docs/components_and_bundles/bundles/SyliusShippingBundle/custom_calculators.rst
docs/components_and_bundles/bundles/SyliusTaxationBundle/custom_calculators.rst
docs/components_and_bundles/components/User/services/canonicalizing.rst
docs/components_and_bundles/components/User/services/updating_password.rst
docs/cookbook/api/add_to_cart_product_chosen_by_product_options.rst
docs/cookbook/entities/custom-model-accessible-for-channel-admin.rst
docs/cookbook/frontend/google-analytics.rst
docs/cookbook/taxation/customize-tax-by-address.rst
docs/customization/api/index.rst
docs/customization/api/modifying_endpoints.rst
docs/customization/fixtures.rst
docs/getting-started-with-sylius/custom-business-logic.rst
docs/performance/database-indexes.rst

| Related tickets | related to #13523
As mentioned in here: https://github.com/Sylius/Sylius/pull/13523#issuecomment-1019740530 the documentation should have been fixed for 1.10 as well. So here is the merge request.
This might make trouble when trying to upmerge though.

Fixing the documentation (1.10)

---

composer.json
src/Sylius/Bundle/ApiBundle/SyliusApiBundle.php
src/Sylius/Bundle/CoreBundle/Doctrine/ORM/AvatarImageRepository.php
src/Sylius/Bundle/CoreBundle/Fixture/BookProductFixture.php
src/Sylius/Bundle/CoreBundle/Form/DataTransformer/ProductTaxonToTaxonTransformer.php
src/Sylius/Bundle/CoreBundle/Form/DataTransformer/ProductVariantsToCodesTransformer.php
src/Sylius/Bundle/CoreBundle/Form/DataTransformer/ProductsToCodesTransformer.php
src/Sylius/Bundle/CoreBundle/Form/DataTransformer/TaxonsToCodesTransformer.php
src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasEnabledEntityValidator.php
src/Sylius/Bundle/ProductBundle/Form/DataTransformer/ProductsToProductAssociationsTransformer.php
src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionCouponToCodeType.php
src/Sylius/Bundle/UserBundle/Form/UserVerifiedAtToBooleanTransformer.php
src/Sylius/Bundle/UserBundle/Provider/EmailProvider.php
src/Sylius/Bundle/UserBundle/Provider/UsernameOrEmailProvider.php
src/Sylius/Bundle/UserBundle/Provider/UsernameProvider.php
src/Sylius/Component/Core/Model/Channel.php
src/Sylius/Component/Core/Model/OrderItem.php
src/Sylius/Component/Core/Model/PaymentMethod.php
src/Sylius/Component/Core/Model/ProductVariant.php
src/Sylius/Component/Core/Promotion/Filter/TaxonFilter.php
src/Sylius/Component/Core/Resolver/ChannelBasedPaymentMethodsResolver.php
src/Sylius/Component/Core/Resolver/DefaultPaymentMethodResolver.php
src/Sylius/Component/Order/Model/OrderItem.php
src/Sylius/Component/Payment/Resolver/CompositeMethodsResolver.php
src/Sylius/Component/Payment/Resolver/PaymentMethodsResolver.php
src/Sylius/Component/Product/Model/ProductOption.php
src/Sylius/Component/Promotion/Model/Promotion.php
src/Sylius/Component/Shipping/Resolver/CompositeMethodsResolver.php
src/Sylius/Component/Taxonomy/Model/Taxon.php
src/Sylius/Component/User/Model/User.php

Bump Psalm version to 4.19 (php 8.1 support)

---

src/Sylius/Bundle/PromotionBundle/Doctrine/ORM/CatalogPromotionRepository.php
src/Sylius/Component/Promotion/Repository/CatalogPromotionRepositoryInterface.php

[Catalog Promotion] Removal of unused function

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/messenger.yaml

[Catalog Promotion] add update variant event to messenger routing

---

src/Sylius/Bundle/CoreBundle/Checker/InForProductScopeVariantChecker.php
src/Sylius/Bundle/CoreBundle/Checker/InForTaxonsScopeVariantChecker.php
src/Sylius/Bundle/CoreBundle/Checker/InForVariantsScopeVariantChecker.php
src/Sylius/Bundle/CoreBundle/Checker/VariantInScopeCheckerInterface.php

[Catalog Promotion] remove redundant method

---

docs/cookbook/promotions/custom-catalog-promotion-scope.rst

[Catalog Promotion][Docs] update CP scopes docs

---

docs/cookbook/promotions/custom-catalog-promotion-scope.rst

| Related tickets | resolves comments from https://github.com/Sylius/Sylius/pull/13591

[Cookbook] Minor fixes in custom catalog promotion scope

---

src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/ConfigurationTest.php

Additional validation in configuration tree with related tests. Based on #13587

[Catalog Promotion][Test] Assert proper batch size configuration

---

src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/CircularDependencyBreakingErrorListenerPassTest.php
src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/CircularDependencyBreakingExceptionListenerPassTest.php
src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/ConfigurationTest.php
src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php

Applying comments from https://github.com/Sylius/Sylius/pull/13594, I've also enabled some tests that were not run at all :dancer:

Core Configuration style and tests improvements

---

UPGRADE-1.11.md
src/Sylius/Bundle/AdminBundle/Resources/config/services/form.xml
src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
src/Sylius/Bundle/PayumBundle/Resources/config/services/form.xml

| BC breaks?      | potentially
| Related tickets | fixes #13450 
I'm making the PR against 1.11, because it hasn't been released yet, but you're free to retarget it against master if you don't feel like accepting it into the release train this late.

Specify explicit priorities for all form type extensions

---

docs/book/products/catalog_promotions.rst

[Docs][Catalog Promotion] Warning added to docs

---

src/Sylius/Behat/Context/Transform/ProductOptionValueContext.php
src/Sylius/Behat/Context/Ui/Shop/ProductContext.php

[CatalogPromotion] Code improvements

---

psalm.xml
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/LocaleFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/LocaleFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
src/Sylius/Bundle/CoreBundle/Tests/DataFixtures/LocaleFactoryTest.php
src/Sylius/Bundle/CoreBundle/composer.json
tests/DataFixtures/Factory/LocaleFactoryTest.php

[Fixtures] Locale factory

---

src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/CountryFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/CountryFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/CountryFactoryTest.php

[Fixtures] Country factory

---

UPGRADE-1.11.md
UPGRADE-API-1.11.md

[Maintenance] Minor clean up of UPGRADE files for Sylius 1.11

---

psalm.xml
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/CurrencyFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/CurrencyFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/CurrencyFactoryTest.php

[Fixtures] Currency factory

---

src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/CustomerGroupFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/CustomerGroupFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/CustomerGroupFactoryTest.php

[Fixtures] Customer group factory

---

psalm.xml
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ShopUserFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ShopUserFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/ShopUserFactoryTest.php

[Fixtures] Customer factory

---

docs/book/installation/sylius_plus_installation.rst
docs/book/installation/sylius_plus_upgrading.rst

[Documentation] Update installation guide for Plus

---

src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ShippingCategoryFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ShippingCategoryFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/ShippingCategoryFactoryTest.php

[Fixtures] Shipping category factory

---

src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/TaxCategoryFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/TaxCategoryFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/TaxCategoryFactoryTest.php

[Fixtures] Tax category factory

---

features/cli/cancel_unpaid_orders.feature
src/Sylius/Behat/Context/Cli/CancelUnpaidOrdersContext.php
src/Sylius/Behat/Context/Domain/ManagingOrdersContext.php
src/Sylius/Behat/Context/Setup/OrderContext.php
src/Sylius/Behat/Resources/config/services/contexts/cli.xml
src/Sylius/Behat/Resources/config/suites.yml
src/Sylius/Behat/Resources/config/suites/cli/canceling_unpaid_orders.yml
src/Sylius/Behat/Resources/config/suites/cli/showing_available_plugins.yml
src/Sylius/Bundle/CoreBundle/Command/CancelUnpaidOrdersCommand.php
src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php

| Related tickets | fixes https://github.com/Sylius/Sylius/issues/13442

[CLI] Cancel unpaid orders command

---

UPGRADE-1.11.md
UPGRADE-1.12.md

| Related tickets | fixes https://github.com/Sylius/Sylius/pull/13488

[Maintenance] Move note about asset management changes from 1.11 to 1.12 UPGRADE file

---

src/Sylius/Behat/Context/Api/Shop/ProductContext.php

| Related tickets | after merge #13684 

[Behat][API] Remove duplicated steps in ProductContext

---

psalm.xml
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ZoneFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ZoneFactoryInterface.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ZoneMemberFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ZoneMemberFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/ZoneFactoryTest.php
tests/DataFixtures/Factory/ZoneMemberFactoryTest.php

[Fixtures] Zone factory

---

.github/workflows/application.yml

[Maintenance] Test Sylius with node 16.x

---

src/Sylius/Bundle/ShopBundle/EventListener/ShopCartBlamerListener.php
src/Sylius/Bundle/ShopBundle/spec/EventListener/ShopCartBlamerListenerSpec.php
src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
src/Sylius/Component/Core/Model/Order.php
src/Sylius/Component/Core/Model/OrderInterface.php
src/Sylius/Component/Core/spec/Cart/Context/ShopBasedCartContextSpec.php

| Related tickets | fixes https://github.com/Sylius/Sylius/pull/13676

[Order] Change getters and setters to use a proper flag name

---

src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/TaxonFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/TaxonFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/TaxonFactoryTest.php

[Fixtures] Taxon factory

---

src/Sylius/Component/Order/Model/AdjustableInterface.php

[DX] add correct return type to getAdjustments method

---

docs/book/orders/checkout.rst

| Related tickets | after #13691 

[Documentation] Add reference to the cookbook about forcing login in API

---

src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ProductAssociationTypeFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ProductAssociationTypeFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/ProductAssociationTypeFactoryTest.php

[Fixtures] Product association type factory

---

composer.json
phparkitect.php

| Related tickets | partially #13621

Add PHPArkitect rule for factories

---

src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ProductAttributeFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ProductAttributeFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/ProductAttributeFactoryTest.php

[Fixtures] Product attribute factory

---

docs/book/organization/release-cycle.rst

[Documentation] Fix start date of development 1.12 version

---

CHANGELOG-1.11.md
docs/book/products/pricing.rst
src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml

[Docs] [AdminBundle] fix minor typo

---

docs/book/api/index.rst
docs/book/api/map.rst.inc
docs/book/api/translations.rst
src/Sylius/Bundle/LocaleBundle/Context/RequestHeaderBasedLocaleContext.php
src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
src/Sylius/Bundle/LocaleBundle/spec/Context/RequestHeaderBasedLocaleContextSpec.php
tests/Api/Responses/Expected/shop/product/get_product_with_de_DE_locale_translation.json
tests/Api/Shop/ProductsTest.php

[Locale] Add header based locale context

---

docs/book/installation/installation.rst

| Branch?         | 1.11, master
Update PHP version on installation doc from 7.3 to 8.0

Update PHP Version in installation doc

---

.github/workflows/application.yml
CONFLICTS.md
composer.json
src/Sylius/Bundle/ApiBundle/composer.json
src/Sylius/Bundle/UserBundle/spec/Provider/UsernameOrEmailProviderSpec.php
symfony.lock

[Maintenance] Fix 1.9 build

---

CONFLICTS.md
composer.json

[Maintenance] Add conflict to symfony/framework-bundle to fix problem with solving path prefix in API scenarios

---

composer.json

Definitely still not a proper solution (https://github.com/Sylius/Sylius/pull/13715 was not one either), but a hot-fix for making the build 🟢 again 🖖

[Hot-fix] Conflict with symfony/dependency-injection even more

---

src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php
src/Sylius/Bundle/PayumBundle/spec/Action/Paypal/ExpressCheckout/ConvertPaymentActionSpec.php

[PaypalExpress] Dont take shipping tax adjustment to shipping cost

---

docs/book/products/catalog_promotions.rst

Synchronous messenger transport explained.

[Docs] Synchronous messenger transport

---

docs/book/products/catalog_promotions.rst

[Docs] Blank line removed

---

features/taxation/managing_tax_rates/tax_rate_validation.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxRateContext.php
src/Sylius/Bundle/TaxationBundle/Resources/config/validation/TaxRate.xml
src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.en.yml
src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.pl.yml

[Taxation] Add validation of negative tax rate

---

docs/book/api/translations.rst

[Docs] add note to translation

---

src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ProductOptionFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/ProductOptionFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/ProductOptionFactoryTest.php

[Fixtures] Product option factory

---

psalm.xml
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/AddressFactory.php
src/Sylius/Bundle/CoreBundle/DataFixtures/Factory/AddressFactoryInterface.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/data_fixtures.xml
tests/DataFixtures/Factory/AddressFactoryTest.php

[Fixtures] Address factory

---

adr/2020_03_03_api_product_option_values.md
adr/2020_03_03_api_translations.md
adr/2020_03_03_feature_coverage_in_api.md
adr/2020_11_12_registration_of_handlers_in_message_buses.md
adr/2020_11_18_sending_emails_via_api.md
adr/2021_04_15_using_iri_as_api_resource_identifier_in_request_instead_of_code_id.md

[ADR] Clean up existing ADRs mostly by updating their statuses

---

UPGRADE-API-1.12.md

| Related tickets | PR https://github.com/Sylius/Sylius/pull/13659 https://github.com/Sylius/Sylius/pull/13636
There was a wrong parameter names provided in our API UPGRADE file that could cause misunderstanding of the new endpoints

[API] UPGRADE file parameter names fixed

---

UPGRADE-API-1.12.md
src/Sylius/Bundle/ApiBundle/CommandHandler/Account/ResetPasswordHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Account/ResetPasswordHandlerSpec.php
src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
src/Sylius/Bundle/UserBundle/Tests/DependencyInjection/SyliusUserExtensionTest.php

[Maintenance][API] Decouple resource metadata from ResetPasswordHandler

---

docs/book/installation/sylius_plus_installation.rst

[Plus] Fix Sylius installation guide

---

UPGRADE-1.10.md
features/shipping/applying_shipping_method_rules/seeing_estimated_shipping_cost_based_on_order_total.feature
features/shipping/applying_shipping_method_rules/seeing_estimated_shipping_cost_based_on_total_weight.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml
src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreConfigurationTest.php
src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php

| Related tickets | fixes https://github.com/Sylius/Sylius/issues/12554, https://github.com/Sylius/Sylius/issues/13123, related to https://github.com/Sylius/Sylius/pull/13126

[Core][Shipping] Fix estimated shipping costs

---

adr/2021_07_05_api_providing_locales_available_in_active_channel.md
adr/2022_03_15_api_providing_locales_available_in_active_channel.md

| Related tickets | https://github.com/Sylius/Sylius/pull/12766 and https://github.com/Sylius/Sylius/pull/13333

[ADR][API] Update ADR for providing locales after changing the approach

---

UPGRADE-API-1.12.md

| Related tickets | fixes https://github.com/Sylius/Sylius/pull/13778#discussion_r829428853

[Upgrade] Add more details to UPGRADE-API-1.12.md

---

UPGRADE-1.11.md

| Related tickets | https://github.com/Sylius/Sylius/pull/13769

[Maintenance] Update UPGRADE-1.11.md

---

src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php

| Related tickets | https://github.com/Sylius/Sylius/pull/13769

[Core][Shipping] Deprecate processing shipments before recalculating prices

---

adr/2022_03_18_raw_data_in_command_and_events.md

[ADR] Use raw data in commands and events

---

adr/2022_03_24_remove_flush_from_handlers.md

[ADR] Remove flush() from handlers.

---

features/product/viewing_products/redirecting_to_products_when_there_is_a_trailing_slash_in_path.feature
src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
src/Sylius/Bundle/ShopBundle/Resources/config/routing/product.yml

Fix redirection when there is a trailing slash in the products list path

---

docs/requirements.txt

[Documentation] Fix build by specifying jinja2 version requirement

---

docs/cookbook/payments/custom-invoice.rst
docs/cookbook/payments/customizing-credit-memo.rst

| Related tickets | https://github.com/Sylius/RefundPlugin/pull/361, https://github.com/Sylius/InvoicingPlugin/pull/272

[Docs] Add a guide on how to deal with file access problems in the wkhtmltopdf

---

docs/book/installation/sylius_plus_installation.rst
docs/book/installation/sylius_plus_upgrading.rst

[Documentation][Plus] Adjust installation guide after entities refactor

---

docs/cookbook/entities/custom-model-accessible-for-channel-admin.rst

I'm marking that PR as a draft, because it can be merged after the next release of Plus.

[Documentation][Plus] Update cookbook about restricting access to the entity

---

CHANGELOG-1.11.md

| Related tickets | fixes https://github.com/Sylius/Sylius/issues/13800#issuecomment-1079773033

[Maintenance] Fix a misleading description

---

README.md

Add some images to the readme file

Add images to the Readme file

---

UPGRADE-API-1.12.md
src/Sylius/Bundle/ApiBundle/CommandHandler/Account/RequestResetPasswordTokenHandler.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Account/VerifyCustomerAccountHandler.php
src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Account/RequestResetPasswordTokenHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Account/VerifyCustomerAccountHandlerSpec.php

[API] Use the Calendar component in command handlers

---

docs/book/installation/installation.rst

[DOC] Bump minimal PHP version needed to install Sylius

---

docs/index.rst

[DOCS] Update index tip

---

UPGRADE-API-1.12.md

Fix mistake after rebase

---

features/locale/handling_different_locales_on_multiple_channels.feature
features/locale/redirect_to_default_locale.feature
features/locale/switching_current_locale.feature
src/Sylius/Behat/Context/Api/Shop/ChannelContext.php
src/Sylius/Behat/Context/Api/Shop/LocaleContext.php
src/Sylius/Behat/Context/Transform/LocaleContext.php
src/Sylius/Behat/Context/Ui/ChannelContext.php
src/Sylius/Behat/Context/Ui/Shop/LocaleContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/services/contexts/transform.xml
src/Sylius/Behat/Resources/config/services/contexts/ui.xml
src/Sylius/Behat/Resources/config/suites/api/locale/locales.yaml

[Behat][API] Browsing channels using their default locales

---

features/locale/browsing_shop_in_different_than_default_locale.feature
features/locale/handling_different_locales_on_multiple_channels.feature
features/locale/redirecting_to_default_locale.feature
features/locale/switching_current_locale.feature
features/product/viewing_products/viewing_product_variants_names.feature
src/Sylius/Behat/Client/ApiPlatformClient.php
src/Sylius/Behat/Context/Api/Shop/ChannelContext.php
src/Sylius/Behat/Context/Api/Shop/LocaleContext.php
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Behat/Context/Transform/LocaleContext.php
src/Sylius/Behat/Context/Ui/ChannelContext.php
src/Sylius/Behat/Context/Ui/Shop/LocaleContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/locale/locales.yaml
src/Sylius/Behat/Resources/config/suites/api/product/viewing_products.yml
src/Sylius/Behat/Service/SharedStorage.php
src/Sylius/Behat/Service/SharedStorageInterface.php
src/Sylius/Behat/spec/Service/SharedStorageSpec.php

| Related tickets | after #13708, similar to #13823

[API][Shop][Behat] Implement scenarios for switching and handling multiple locales

---

features/product/viewing_product_in_admin_panel/viewing_details_of_product_with_variants.feature
src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/VariantItem/_item.html.twig

Show variant name instead of the product name.

[Template] Variant name instead of product name

---

src/Sylius/Behat/Client/ApiClientInterface.php
src/Sylius/Behat/Client/ApiPlatformClient.php
src/Sylius/Behat/Context/Api/Shop/ProductContext.php

Sometimes there is a need to resend a request if the last response has been overwritten.

[HotFix][Behat][API] Fix suddenly failing tests

---

docs/book/orders/shipments.rst

| Related tickets | after https://github.com/Sylius/Sylius/pull/13870

[Documentation] Fix the description of items total shipping rules

---

ecs.php

Nowadays computers and PIPELINES have more than one core - this simple trick will speed up checking coding standard

[maintenance]Run ECS in parallel

---

ecs.php

[maintenance]Fix ECS HeaderCommentFixer

---

src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml
src/Sylius/Bundle/ApiBundle/Swagger/AcceptLanguageHeaderDocumentationNormalizer.php
src/Sylius/Bundle/ApiBundle/spec/Swagger/AcceptLanguageHeaderDocumentationNormalizerSpec.php

[Swagger] Enum with available locale codes in Accept-Language header

---

docs/getting-started-with-sylius/shop-customizations.rst

After:
@CoderMaggie I added the hint about yaml files, if it does not fit I can remove it 🚀

Using Sylius template event to change logo

---

docs/book/installation/sylius_plus_installation.rst

| Related tickets | https://github.com/Sylius/Plus/pull/1032

[Docs] Updated Sylius Plus installation guide - optional PDF Generator

---

.docker/test/php.ini
.github/workflows/docker.yml
Makefile
docker-compose.test.yml

| Branch?         | 1.10, 1.11 or master 

[docker]Run Catalog Promotion via SYNC messenger transport

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

[maintenance]Unify markdown tables

---

.github/workflows/refactor.yml

| Related tickets | https://github.com/Sylius/Sylius/pull/13819                 |
"Refactor" workflow creates pull requests with code refactor for `1.10`, `1.11` and `master` branches within the schedule if there is something to clean up.

[Maintenance][CI] Add "Refactor" workflow

---

.github/workflows/application.yml
composer.json
src/Sylius/Bundle/AddressingBundle/spec/Twig/CountryNameExtensionSpec.php
src/Sylius/Bundle/UiBundle/spec/Twig/PercentageExtensionSpec.php
src/Sylius/Bundle/UiBundle/spec/Twig/SortByExtensionSpec.php

I was wondering, is it worth running builds on both Twig 2 and 3 🤔 But we already have a lot of them, so I decided to skip it for now. Maybe we should have one additional build with Twig 2 (as with the current `composer update` we will always use Twig 3)? 🤷‍♂️ Nevertheless, it's nice we can finally support Twig 3 🖖

Support Twig 3

---

features/taxation/applying_taxes/applying_correct_taxes_based_on_customer_data.feature
features/taxation/applying_taxes/applying_correct_taxes_for_items_with_the_same_tax_rate.feature
features/taxation/applying_taxes/applying_correct_taxes_for_products_with_different_tax_rates_for_different_zones.feature
features/taxation/applying_taxes/applying_correct_taxes_on_visitor_cart.feature
features/taxation/applying_taxes/applying_different_taxes_for_variants_with_different_tax_category.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/PickupCartHandler.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/PickupCartHandlerSpec.php

[API][Behat] Cover scenarios for applying correct taxes

---

features/promotion/receiving_discount/receiving_percentage_discount_on_shipping.feature

| Branch?         | master|
| Bug fix?        | no                                                     |
| Deprecations?   | |

[API][Behat] Cover scenarios for receiving discount on shipping after changing product's quantity

---

src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/PickupCartHandler.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/PickupCartHandlerSpec.php

| Branch?         | master|
| Related tickets | after https://github.com/Sylius/Sylius/pull/13930                      |

[API] Add additional PHPSpec for PickupCartHandler when the logged in user has no default address + minor refactor

---

features/promotion/complex_promotions.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Behat/Context/Ui/Shop/CartContext.php

[API][Behat] Cover scenarios for receiving a discount from one promotion based on items total

---

features/promotion/receiving_discount/receiving_fixed_discount_dependent_on_channel.feature
src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php
src/Sylius/Behat/Context/Setup/ChannelContext.php
src/Sylius/Behat/Context/Setup/ProductContext.php
src/Sylius/Behat/Context/Setup/PromotionContext.php
src/Sylius/Behat/Context/Ui/Shop/CartContext.php
yarn.lock

API scenarios covered and some code maintenance

[API] This same cart promotion discount in different channels

---

docs/customization/api/customizing_endpoints_using_yaml.rst

| New feature?    | no                                                     |

[Docs] add info about subresources

---

features/promotion/complex_promotions.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php

| Branch?         |  master         |
| Bug fix?        | no                                                    |
| BC breaks?      | no                                                     |

[API] cover complex promotion with api

---

features/account/receiving_email_after_registration.feature
src/Sylius/Behat/Context/Api/EmailContext.php
src/Sylius/Behat/Context/Api/Shop/RegistrationContext.php
src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
src/Sylius/Behat/Resources/config/suites/api/account/customer_registration.yml

[API] Cover scenarios for receiving email after registration

---

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAssociationType.xml
src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductAssociationType.xml
tests/Api/Admin/ProductAssociationTypesTest.php
tests/Api/DataFixtures/ORM/product/product_with_many_locales.yaml
tests/Api/Responses/Expected/admin/get_product_association_type_collection_response.json
tests/Api/Responses/Expected/admin/get_product_association_type_response.json
tests/Api/Responses/Expected/admin/post_product_association_type_response.json
tests/Api/Responses/Expected/admin/put_product_association_type_response.json
tests/Api/Responses/Expected/shop/product/get_product_association_type_response.json
tests/Api/Shop/ProductAssociationTypesTest.php

changes:
- new shop `get` `ProductAssociationType` endpoint created

[API][Shop] ProductAssociationType endpoint created

---

Makefile

| Related tickets | no                      |

[maintenance][docker]Rerun behat pipelines

---

.github/workflows/application.yml

This PR is meant to produce an easily readable diff of dependencies changed between PR and branch into which the PR is opened. 
PoC: https://github.com/lchrusciel/Sylius/pull/56

[GH] Store composer lock and generate diff

---

docker-compose.test.yml
docker-compose.yml

| Related tickets | none                      |

[docker]Run tests in test_cached environment

---

.docker/Dockerfile
.docker/dev/php.ini
Makefile
docker-compose.yml

Let's expand the development environment with Blackfire to enable faster performance testing

[docker]Configure Blackfire service in dev environment

---

.github/workflows/application.yml

| Related tickets | none                      |

[maintenance]Update setup-node action and add node version to the action name

---

UPGRADE-1.12.md
features/cart/shopping_cart/clearing_cart_after_logging_out.feature
features/checkout/ability_to_checkout_as_guest_with_a_registered_email.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/BlameCartHandler.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/PickupCartHandler.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderGetMethodItemExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderMethodsItemExtension.php
src/Sylius/Bundle/ApiBundle/EventListener/ApiCartBlamerListener.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/BlameCartHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/PickupCartHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderGetMethodItemExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderMethodsItemExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/EventListener/ApiCartBlamerListenerSpec.php
src/Sylius/Bundle/ShopBundle/EventListener/ShopCartBlamerListener.php
src/Sylius/Bundle/ShopBundle/spec/EventListener/ShopCartBlamerListenerSpec.php
src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
src/Sylius/Component/Core/Model/Order.php
src/Sylius/Component/Core/Model/OrderInterface.php
src/Sylius/Component/Core/spec/Cart/Context/ShopBasedCartContextSpec.php
src/Sylius/Component/Core/spec/Model/OrderSpec.php

| Branch?         | master|
| Related tickets | https://github.com/Sylius/Sylius/pull/13962#discussion_r872159904 |

[Customer] Extract authorized user assignment to separate method

---

features/cart/shopping_cart/clearing_cart_after_logging_out.feature
features/checkout/ability_to_checkout_as_guest_with_a_registered_email.feature
src/Sylius/Behat/Context/Api/Shop/CartContext.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/BlameCartHandler.php
src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/PickupCartHandler.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderGetMethodItemExtension.php
src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderMethodsItemExtension.php
src/Sylius/Bundle/ApiBundle/EventListener/ApiCartBlamerListener.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/BlameCartHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Cart/PickupCartHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderGetMethodItemExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderMethodsItemExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/EventListener/ApiCartBlamerListenerSpec.php

[API] Checkout as guest with registered account

---

features/currency/viewing_exchange_rates/viewing_exchange_rates_based_on_current_channel.feature

| Related tickets | https://github.com/Sylius/Sylius/pull/13997#discussion_r877021584                      |

[Behat] Explicitly define channel base currency in viewing exchange rates scenario

---

features/product/viewing_products/viewing_products_from_specific_taxon.feature
src/Sylius/Behat/Context/Api/Shop/ProductContext.php
src/Sylius/Bundle/ApiBundle/Filter/Doctrine/TaxonFilter.php
src/Sylius/Bundle/ApiBundle/spec/Filter/Doctrine/TaxonFilterSpec.php

| Branch?         | master         |
| Related tickets |                    |

[API] cover scenarios for non existing taxon filter

---

phparkitect.php
src/Sylius/Bundle/AdminBundle/spec/Provider/StatisticsDataProviderSpec.php
src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/UpdateCartHandlerSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/AcceptedProductReviewsExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/OrdersByLoggedInUserExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/ProductsByChannelAndLocaleCodeExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/ProductsWithEnableFlagExtensionSpec.php
src/Sylius/Bundle/ApiBundle/spec/Provider/CustomerProviderSpec.php
src/Sylius/Bundle/ApiBundle/spec/Provider/LiipProductImageFilterProviderSpec.php
src/Sylius/Bundle/CoreBundle/spec/Fixture/Factory/TaxonExampleFactorySpec.php
src/Sylius/Bundle/CoreBundle/spec/Form/EventSubscriber/AddBaseCurrencySubscriberSpec.php
src/Sylius/Bundle/CoreBundle/spec/Validator/Constraints/LocalesAwareValidAttributeValueValidatorSpec.php
src/Sylius/Component/Core/spec/Model/AdjustmentSpec.php
src/Sylius/Component/Core/spec/Model/AdminUserSpec.php
src/Sylius/Component/Locale/spec/Context/CompositeLocaleContextSpec.php
src/Sylius/Component/Product/spec/Resolver/AvailableProductOptionValuesResolverSpec.php

| Related tickets |             |

Specifications should be final

---

src/Sylius/Bundle/TaxationBundle/spec/DependencyInjection/Compiler/RegisterCalculatorsPassSpec.php
src/Sylius/Bundle/TaxationBundle/test/app/AppKernel.php
src/Sylius/Bundle/TaxationBundle/test/app/config/config.yml

Trying to fix https://github.com/Sylius/Sylius/runs/6454899241?check_suite_focus=true#step:14:16 …

[Symfony 6] Fix Taxation test app

---

docs/_themes/sylius_rtd_theme/breadcrumbs.html

Should be tested after the merge as on `dev` it is different.

[DOCS] Fix github link on search doc

---

rector.php

| BC breaks?      | no/s                                                       |
| Related tickets | based on https://github.com/Sylius/Sylius/pull/14038

[Rector] Configure PHP version up to 8.0

---

src/Sylius/Bundle/UiBundle/Tests/Functional/Kernel.php
src/Sylius/Bundle/UiBundle/Tests/Functional/TemplateEventTest.php
src/Sylius/Bundle/UiBundle/Tests/Functional/config/packages/framework.yaml
src/Sylius/Bundle/UiBundle/Tests/Functional/config/packages/security.yaml

| Related tickets | partially #13274                     |
Trying to fix https://github.com/Sylius/Sylius/runs/6455324516?check_suite_focus=true#step:14:15 …

[Symfony 6] Fix PHPUnit tests for UI bundle

---

src/Sylius/Bundle/ApiBundle/Swagger/ProductSlugDocumentationNormalizer.php

Fix on master after https://github.com/Sylius/Sylius/pull/14000 merge 🖖

Fix ProductSlugDocumentationNormalizer

---

features/addressing/managing_zones/editing_zone.feature
src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml
src/Sylius/Bundle/ApiBundle/Serializer/ZoneDenormalizer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ZoneDenormalizerSpec.php

| Related tickets | fixes https://github.com/Sylius/Sylius/issues/13701                      |
This PR should be merged after https://github.com/Sylius/Sylius/pull/14061.

[Addressing] Fix adding and removing zone members again (with API coverage only)

---

src/Sylius/Behat/Context/Transform/ZoneMemberContext.php
src/Sylius/Bundle/ApiBundle/Serializer/ZoneDenormalizer.php
src/Sylius/Bundle/ApiBundle/spec/Serializer/ZoneDenormalizerSpec.php

| Branch?         | 1.11          |
| New feature?    | no                                           |
| BC breaks?      | no                                                     |
| Related tickets |  refactoring of https://github.com/Sylius/Sylius/pull/14061, https://github.com/Sylius/Sylius/pull/14067                     |

[Addressing] Minor refactor

---

src/Sylius/Component/User/Model/User.php
src/Sylius/Component/User/Model/UserInterface.php
src/Sylius/Component/User/composer.json

This is fixed here https://github.com/Sylius/Sylius/runs/6826413589?check_suite_focus=true

[Symfony 6] Fix user component

---

docs/getting-started-with-sylius/deployment.rst

| BC breaks?      | no/yes                                                       |
Created unordered list of files as in tip it otherwise does not break lines between links

[DOCS] Add docs about deploy platforms

---

src/Sylius/Bundle/CoreBundle/Migrations/Version20220407131547.php

| Branch?         | 1.11 |
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/13988                      |

[Maintenance] Fix Version20220407131547 migration

---

phpstan.neon.dist

Change deprecated PHPStan config

---

docs/book/installation/sylius_plus_installation.rst

| Branch?         | 1.11          |
| Related tickets |                      |
Added warning to docs about the order of importing resources when installing Sylius Plus.

[Docs] Upgrade Plus installation guide

---

.github/workflows/packages.yml
src/Sylius/Bundle/ReviewBundle/composer.json
src/Sylius/Bundle/ReviewBundle/test/app/AppKernel.php
src/Sylius/Bundle/ReviewBundle/test/app/config/config.yml
src/Sylius/Bundle/UserBundle/.gitignore
src/Sylius/Bundle/UserBundle/Authentication/AuthenticationSuccessHandler.php
src/Sylius/Bundle/UserBundle/DependencyInjection/Compiler/RemoveUserPasswordEncoderPass.php
src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php
src/Sylius/Bundle/UserBundle/Security/UserLogin.php
src/Sylius/Bundle/UserBundle/Security/UserPasswordHasher.php
src/Sylius/Bundle/UserBundle/SyliusUserBundle.php
src/Sylius/Bundle/UserBundle/Tests/DependencyInjection/Compiler/RemoveUserPasswordEncoderPassTest.php
src/Sylius/Bundle/UserBundle/Tests/Functional/app/AppKernel.php
src/Sylius/Bundle/UserBundle/Tests/Functional/app/config/config.yml
src/Sylius/Bundle/UserBundle/composer.json
src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationSuccessHandlerSpec.php
src/Sylius/Bundle/UserBundle/spec/EventListener/UpdateUserEncoderListenerSpec.php
src/Sylius/Bundle/UserBundle/spec/Security/UserPasswordHasherSpec.php
src/Sylius/Component/User/composer.json

| Bug fix?        | yes  (for Symfony 6)                                                     |
This is fixed here https://github.com/Sylius/Sylius/runs/6904269684?check_suite_focus=true

Fix Review bundle

---

src/Sylius/Bundle/AdminBundle/Resources/config/app/events.yaml
src/Sylius/Bundle/UiBundle/Resources/config/app/config.yml
src/Sylius/Bundle/UiBundle/Resources/config/app/events.yaml

| Related tickets | fixes https://github.com/Sylius/Sylius/pull/14101|

[Templates] Move grid events to UI bundle

---

docs/book/installation/sylius_plus_installation.rst
docs/book/installation/sylius_plus_upgrading.rst

[Documentation][Plus] Add missing step for updating security file during installation

---

features/admin/resetting_password.feature
features/admin/resetting_password_validation.feature

Scenarios covering `Admin password reset` feature.

[Admin][Behat] Cover scenarios for admin password reset

---

docs/book/installation/index.rst
docs/book/installation/installation_with_docker.rst
docs/book/installation/map.rst.inc
docs/cookbook/deployment/docker.rst
docs/cookbook/deployment/map.rst.inc
docs/cookbook/index.rst
docs/getting-started-with-sylius/deployment.rst
docs/getting-started-with-sylius/installation.rst

Wait for https://github.com/Sylius/Sylius/pull/14023

[docker][docs]Deploy Sylius with Docker

---

src/Sylius/Bundle/AdminBundle/Resources/config/app/events.yaml
src/Sylius/Bundle/UiBundle/Resources/config/app/events.yaml

| Related tickets |                |

Move login events on Ui bundle

---

docs/getting-started-with-sylius/installation.rst

| Branch?         | master      |
No need to specify the version here IMHO, since `composer create-project` will always use the latest stable.

Removed version specification
