src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Checkout/Step/finalize.html.twig

| Bug fix?      | [yes]
| Deprecations? | no]
| Fixed tickets | None
If you have a checkout process consisting of only one step there is no previous step.  Hence the view gives an error.   A simple test is introduced to mitigate this problem

[WebBundle] Fix error in finalize step

---

src/Sylius/Bundle/ShippingBundle/Resources/config/validation.xml

Removed constraints for ``name`` property from ``ShippingMethod`` since it is moved to ``ShippingMethodTranslation``.
This was preventing creation of new ShippingMethod from backend.

Fixed ShippingMethod validation

---

src/Sylius/Component/Core/Model/Order.php

While working with Sylius I ran into an error on the order page. It turns out that because getLastShipment returns false when there are no shipments but isInvoiceAvailable tests for null, the if is entered and getState is executed on a non-object.
In an earlier version the docblock actually said getLastShipment would return null (but it did return false). I've updated isInvoiceAvailable to reflect the docblock and behaviour.

getLastShipment returns false, not null. fixed in isInvoiceAvailable

---

src/Sylius/Bundle/ResourceBundle/DependencyInjection/Compiler/ObjectToIdentifierServicePass.php
src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml

Allow to use Doctrine MongoDB registry if default Doctrine is not available

---

src/Sylius/Bundle/WebBundle/Resources/translations/menu.en.yml
src/Sylius/Bundle/WebBundle/Resources/translations/menu.fr.yml
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/layout.html.twig

Also, add the "Links" header to the translation mapping (en and fr).
I'm not sure how to add the `'sylius.frontend.menu.sidebar.links'` translation to other languages, especially given that their mappings' indentations are inconsistent (sometimes 2 spaces, sometimes 4).
This PR is mostly a paper-cut fix, but I'm new to Sylius so... low hanging fruit and such...
Also, maybe the Links widget should be in his own block, to ease overriding ? I'm not sure how you envision this ; I'm new ! :)
Do tell me if you think this needs more work, I plan to spend some time on Sylius in the next couple of months.

Hide the "Links" sidebar widget when there are no links.

---

src/Sylius/Bundle/ProductBundle/Generator/VariantGenerator.php
src/Sylius/Bundle/ProductBundle/Resources/config/services.xml
src/Sylius/Component/Variation/Generator/VariantGenerator.php
src/Sylius/Component/Variation/SetBuilder/CartesianSetBuilder.php
src/Sylius/Component/Variation/SetBuilder/SetBuilderInterface.php
src/Sylius/Component/Variation/spec/Sylius/Component/Variation/Generator/VariantGeneratorSpec.php
src/Sylius/Component/Variation/spec/Sylius/Component/Variation/SetBuilder/CartesianSetBuilderSpec.php

Q | A
---|---
Bug fix? | no
New feature? | yes
BC breaks? | yes
License | MIT
Doc PR |  https://github.com/Sylius/Sylius-Docs/pull/232
Whilst working on writing specs for the `VariantGenerator`, I could see why there weren't any to begin with.
Now the most complicated logic has been extracted out to a new class `CartesianSetBuilder`, which implements `SetBuilderInterface`, so this has the added benefit of allowing developers to define their own strategies for generating variants.
Unfortunately, the disadvantage of this being that the set builder has to be explicitly passed to the constructor of `VariantGenerator`, and only math boffins would be aware of what a _set builder_ and the _Cartesian product_ are.

[Variation] Reusable Set Builders for generating variants + VariantGenerator spec coverage

---

app/AppKernel.php
src/Sylius/Bundle/CoreBundle/Kernel/Kernel.php

Ran into this being a problem since for local development I use the environment 'local'.
What do you think?
| Improvement | yes

Remove hardcoded environment names where isDebug switch is good enough

---

app/config/deploy.rb.dist

| Bug fix?      | kind of
Hi there,
Just made a few changes to the `deploy.rb.dist` script : 
- Set update_vendors to true cause it's a potential problem if you deploy in production and one of your lib gets updated. Normally you have to commit your `composer.lock` file so that all your environment vendors are the same.
- Following this update, I decided to remove the copy vendor task which is, IMHO, not needed anymore.
- I also removed a few variables which are set by default by capifony (webserver_user, model_manager)
- The script now relies on capifony variables (log_path, cache_path, web_path) instead of hardcoded …

Enhance deploy script

---

behat.yml.dist
src/Sylius/Bundle/CoreBundle/Behat/HookContext.php
src/Sylius/Bundle/ResourceBundle/Behat/DefaultContext.php

BeforeScenario is defined in DefaultContext, so for every context that inherits from it, the hook is run once.
In a suite with multiple contexts that extend the DefaultContext the hook is run once for every context.
I've separated the BeforeScenario in a separate context, it's placed in CoreBundle, if you believe Resource bundle is a better place I'll change it.
I've only added the HookContext for the inventory suite for now, if this PR is ok I will add it to the other suites.
In our suites this has reduced behat execution times dramatically. I've run a few sylius tests and there is a reduction in overall times, but nothing drastic.

[WIP] BeforeScenario is running multiple times slowing behat tests

---

src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductsData.php

Not really a bugfix nor a feature but had this problem when trying to create my own fixtures : sometimes it's a dot, others a hyphen.
I have rationalized the behavior to use dots everywhere and it breaks the BC for those using the hyphen.
What I can do is add another `setReference` call so that there are 2 references pointing to the same object.
What do you guys prefer ?

[FixturesBundles] Rationalizes product references

---

src/Sylius/Bundle/VariationBundle/DependencyInjection/Configuration.php

| Fixed tickets | #2348
As reported in the Fix Ticket, the following code in `SyliusVariationExtension` would error when `$driver` is set to null by default. This PR requires `driver` to be configured (though, only one value is supported at present).
```php
$choiceTypeClasses = array(
SyliusResourceBundle::DRIVER_DOCTRINE_ORM => 'Sylius\Bundle\VariationBundle\Form\Type\OptionEntityChoiceType'
);
$optionChoiceFormType = new Definition($choiceTypeClasses[$driver]);
```

[VariationBundle] Require driver node definition

---

src/Sylius/Bundle/WebBundle/Menu/FrontendMenuBuilder.php

I notices that from UX side it is better to show getTotalQuantity then countItems in cart header

Cart header small update

---

composer.json

The CMF bundle installation script seems to have changed. Without running the correct one, assets will be missing during the asset installation step.
See also #2053.

Fixed missing theme CSS during sylius:install

---

src/Sylius/Bundle/WebBundle/Menu/BackendMenuBuilder.php
src/Sylius/Bundle/WebBundle/Resources/config/services.xml

| Fixed tickets | #2387 
Fixes minor issue in backend sidebar menu - the active item wasn't highlighted so it was hard to see where you now.

[WebBundle] Backend side menu not highlighted fix #2387

---

src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Product/_variant.html.twig
src/Sylius/Component/Core/Model/ProductVariant.php
src/Sylius/Component/Core/Model/ProductVariantInterface.php

| Fixed tickets | #2332
This PR aims to display variant image instead of product master variant image in cart. In case no variant image is available, it displays product master variant image.

Display variant image in cart

---

src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadImagesData.php

Hey!
Instead of instantiating the product variant image manually, the fixture should rely on the repository as it is done elsewhere.

[Fixture][ProductVariantImage] Rely on repository createNew instead of constructor

---

src/Sylius/Bundle/ResourceBundle/Controller/Configuration.php
src/Sylius/Bundle/ResourceBundle/Controller/DomainManager.php

| New feature?  | [yes]
| Fixed tickets | [#2378]
| Doc PR        | [#2378]
Hi, this PR adds the ability to use new pre and post events, not only the pre and post create, update and delete.
To configure a custom event, only need add a event parameter on the route configuration like show below
<pre>
route:
path: /{id}
methods: [GET]
defaults:
_controller: controller:action
_sylius:
template: template.html.twig
method: method
arguments: [$id]
event: eventName
</pre>
Until now, the updateAction and UpdateStateAction actions, calls the update method from DomainManager, so in both action the pre and post update event are fired (yes, same events, different …

[ResourceBundle] Simple modification to change the events fired by the domain manager.

---

src/Sylius/Bundle/ResourceBundle/Controller/Configuration.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/ConfigurationSpec.php

Attempt at https://github.com/Sylius/Sylius/issues/2206
Not sure how you guys want to handle this in regards to using array_merge / array_replace_recursive etc. I still feel like it should always default to what is in _sylius, and then if filterable / sortable is enabled it will replace with values from the request. Going to wait to see if this works with travis as well and may make some adjustments.

Fix sorting / criteria use _sylius information by default

---

src/Sylius/Bundle/VariationBundle/Form/DataTransformer/VariantToCombinationTransformer.php
src/Sylius/Bundle/VariationBundle/spec/Form/DataTransformer/VariantToCombinationTransformerSpec.php

Hey!
This PR fixes an issue I encounter when I extend the cart item form with my own. Basically, my use case allows an empty value for option value choices. Then, the option values in the cart item can be null if the user does not select a value or try to send an unknown/maliscious value in the form. So, in multiple cases, it can result to a fatal error due to the typehint of the `ProductVariant::hasOption` method. 
This PR adds an extra check about the option validity before checking the option availability. Additionally, I have improved the performance by continuing the two loops with a `continue`.

Improve + Handle null option in variant to combination transformer

---

src/Sylius/Bundle/SearchBundle/Finder/ElasticsearchFinder.php

This is a minor correction that fixes the use of deprecated "setFilter" method in Elastica query.

Fix Elastica deprecated call to setFilter

---

src/Sylius/Bundle/ResourceBundle/Resources/views/forms.html.twig

| Fixed tickets | n/a
If you specify `allow_add` to false when building a form collection property, this will result in a Twig error:
> Variable "prototype" does not exist
In the same form theme template, a check is done to see `prototype` is defined and `allow_add` is true on part of the template, so this same has been done here to fix this issue.
```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
$builder ->add('attributes', 'collection', [
'required'     => false,
'type'         => 'sylius_advertisement_attribute_value',
'allow_add'    => false,
'allow_delete' => false,
'by_reference' => …
```

[ResourceBundle] Check if collection form prototype is defined

---

src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php

Right now in API, if developer want to change the number of result per page, they have to use "paginate":
```
http://example.com/products?paginate=10
```
This PR will change it to default, which is "limit", a more common term for such parameter:
```
http://example.com/products?limit=10
```
Reference:
- http://docs.sylius.org/en/latest/api/products.html

Use "limit" instead of "paginate" for limit parameter.

---

src/Sylius/Bundle/SearchBundle/DependencyInjection/Configuration.php

Hey!
This PR fixes an issue introduced in #2418. Using `cannotBeEmpty` on a boolean node seems to not allow us to use false as value.

[SearchBundle] Allow false value for enabled pre search filter field

---

src/Sylius/Bundle/ResourceBundle/Controller/DomainManager.php
src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
src/Sylius/Component/Resource/Event/ResourceEvent.php

My bad for the PR on splitted repo ...
Related to https://github.com/Sylius/Sylius/issues/2022 and https://github.com/Sylius/SyliusResourceBundle/pull/75
Is it OK ?

Catch event stop during create/update

---

src/Sylius/Bundle/InstallerBundle/Command/InstallDatabaseCommand.php

| Fixed tickets | #2454
The check done on PDOException message when dealing with an unknown database is too strict.
For example, it won't match `SQLSTATE[42000] [1049] Unknown database 'xxxx'` given on certain installation

[Installer] Fix isDatabasePresent

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/main.yml
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadApiData.php
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php
src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php

When ROLE_API is assigned the csrf token is disabled and it causes exception in the backend.
```
Method "_token" for object "Symfony\Component\Form\FormView" does not exist
```
Removed csrf token disable from config, it is handled by ResourceController.
Added fixtures to create new user with ROLE_API for api tests.

Correct api fixtures

---

src/Sylius/Component/Currency/Importer/AbstractImporter.php

We have to check if is true that this code exist in the array to avoid duplicated entries.
Error found: Without this change if you run "sylius:currency:update ecb" more than one time, fatal error occurs because finOneBy (CurrencyConverter.php line 65) its returning more than one.

Fix incorrect negation

---

src/Sylius/Component/Shipping/Calculator/FlatRateCalculator.php
src/Sylius/Component/Shipping/Calculator/FlexibleRateCalculator.php
src/Sylius/Component/Shipping/Calculator/PerItemRateCalculator.php

Fix for shipping calculators to return integers because of error thrown during checkout caused by #2427

Fix for shipping calculators to return integers

---

app/migrations/Version20150206094603.php
features/backend/taxonomies.feature
features/backend/taxonomies_i18n.feature
src/Sylius/Bundle/TaxonomyBundle/Behat/TaxonomyContext.php
src/Sylius/Bundle/TaxonomyBundle/Resources/config/doctrine/model/TaxonTranslation.orm.xml
src/Sylius/Bundle/TaxonomyBundle/Resources/config/validation.xml
src/Sylius/Bundle/TranslationBundle/GedmoHandler/TranslationSlugHandler.php

This fixes the permalink generation TODO in taxons.
I've basically added some customization to the TreeHander. I couldn't extend that class as it has private attributes, so I had to copy the whole class.
The handler is located in ``src/Sylius/Bundle/TranslationBundle/GedmoHandler``, if there is a better place to put it just let me know.

Permalinks for taxons

---

src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php

If ``sylius.classes.promotion_subject`` is not set, ``DoctrineTargetEntitiesResolver`` will throw an exception:
The class sylius.model.promotion_subject.class does not exist.

[PromotionBundle] Force 'classes' configuration

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml

Product translations form in backend lacked shortDescription added in corebundle.

[Core] added correct form type for product translations to config

---

src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php

Here is the use case. I am creating custom repository and function to join and apply some criteria, like this:
```php
<?php
namespace Umpirsky\Bundle\TildaBundle\Repository;
use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;
use Sylius\Component\Core\Model\UserInterface;
class FooRepository extends EntityRepository
{
public function getUsersFoos(UserInterface $user)
{
$queryBuilder = $this->getCollectionQueryBuilder()
->select($this->getAlias().', foo')
->join($this->getAlias().'.foo', 'foo')
;
$this->applyCriteria($queryBuilder, ['foo.deleted' => false]);
$this->applySorting($queryBuilder, ['foo.updatedAt' => 'DESC', 'foo.startTime' => 'DESC']);
return $this->getPaginator($queryBuilder);
}
}
```
I get error:
```
QueryException: [Syntax Error] line 0, col 130: Error: Expected …
```

Make applyCriteria() more flexible

---

src/Sylius/Bundle/WebBundle/Menu/FrontendMenuBuilder.php
src/Sylius/Bundle/WebBundle/Menu/LocaleMenuBuilder.php

It's weird the menu's are shown when there is no option to cycle through. Currency is shown in many places so you don't need a weird sign on the top to tell you the current currency. Same goes with the language.
This is a clean pr from my last pr: https://github.com/Sylius/Sylius/pull/2485

[WebBundle] Locale and Currency menu shouldn't be renderd when only 1 exists

---

src/Sylius/Bundle/MailerBundle/Sender/Adapter/TwigSwiftMailerAdapter.php

[MailerBundle] Don't use deprecated Twig functionality

---

src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php

[InstallerBundle] Prevent exception if `intl` extension is not installed

---

src/Sylius/Bundle/LocaleBundle/Controller/LocaleController.php

Q  | A
License | MIT
Doc PR | -
I needed to change locale using `PATCH` like below:
```yml
acme_api_locale_current_put:
path: /current
methods: [PUT, PATCH]
defaults:
_controller: sylius.controller.locale:changeAction
```
But `changeAction` threw an error:
```
Controller "Sylius\Bundle\LocaleBundle\Controller\LocaleController::changeAction()"
requires that you provide a value for the "$locale" argument
(because there is no default value or because there is a non optional argument after this one).
```

fix(LocaleBundle): Changing locale using PUT, PATCH works now.

---

src/Sylius/Component/Product/Builder/ProductBuilder.php

I came across some documentation in the ProductBuilder class on how to use the service. Found out that the servicename used in the example differs from the actual service name. So I made this minor typo fix.

Fix typo in example in docblock

---

src/Sylius/Bundle/ResourceBundle/EventListener/KernelControllerSubscriber.php

Q  | A
License | MIT
Doc PR | -
Before this patch followoing header would not work as expected:   
`Accept: application/json; groups=Details, form_type_sylius_product`
* Spaces were not allowed between group names.
* You could not have underline in a group name.

Allow underline in group names for API `groups` header

---

src/Sylius/Bundle/CoreBundle/Resources/config/templating.xml
src/Sylius/Bundle/CoreBundle/Templating/Helper/MoneyHelper.php
src/Sylius/Bundle/CurrencyBundle/Resources/config/templating.xml
src/Sylius/Bundle/CurrencyBundle/Templating/Helper/MoneyHelper.php
src/Sylius/Bundle/MoneyBundle/Templating/Helper/MoneyHelper.php
src/Sylius/Bundle/MoneyBundle/Twig/MoneyExtension.php

| Fixed tickets | #2352
For the MoneyHelper:
* MoneyBundle is standalone and uses fixed locale and currency
* CurrencyBundle extends the one from MoneyBundle and adds currencyContext
* CoreBundle extends the one from CurrencyBundle and adds localeContext

Use LocaleContext in MoneyHelper fix #2352

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php

Guest orders were not displayed on /admin/orders

Leftjoin because order.user can be null

---

src/Sylius/Bundle/FlowBundle/Process/Coordinator/Coordinator.php

Due the the way FlowBundle works, it always perform a redirection before the first step.
I have a use case where my first step require some GET parameters (`/step?status=success`), but it is being removed during the redirection. This PR fix that.

[FlowBundle][Bug] Query parameters removed at first step

---

src/Sylius/Bundle/CoreBundle/Checkout/Step/AddressingStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/PaymentStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/PurchaseStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/SecurityStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/ShippingStep.php
src/Sylius/Bundle/CoreBundle/spec/Checkout/Step/PurchaseStepSpec.php
src/Sylius/Bundle/FlowBundle/Process/Context/ProcessContext.php
src/Sylius/Bundle/FlowBundle/Process/Coordinator/Coordinator.php
src/Sylius/Bundle/FlowBundle/Process/Process.php

Don't use deprecated `getRequest()` method in flow

---

src/Sylius/Bundle/TranslationBundle/EventListener/ODMTranslatableListener.php

The translations are stored as EmbeddedDocument in MongoDB as a key-value, where the key is the locale and the value is the Translation document, then we don't need to store the locale field inside the Translation document and neither is needed an unique Index [field, locale] because it is already unique.

[TranslationBundle] removed unnecessary ODM Index

---

src/Sylius/Component/Order/Model/Order.php
src/Sylius/Component/Order/spec/Model/OrderSpec.php

Fluent interface for  calculateAdjustmentsTotal()

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/main.yml
src/Sylius/Bundle/SettingsBundle/DependencyInjection/SyliusSettingsExtension.php

This change make it consistent with RBAC configuration.

Move declaration of settings cache to extension

---

src/Sylius/Bundle/InstallerBundle/Command/AbstractInstallCommand.php
src/Sylius/Bundle/InstallerBundle/Command/CommandExecutor.php
src/Sylius/Bundle/InstallerBundle/Command/InstallDatabaseCommand.php
src/Sylius/Bundle/InstallerBundle/Command/InstallSampleDataCommand.php
src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
src/Sylius/Bundle/RbacBundle/Command/InitializeCommand.php
src/Sylius/Bundle/RbacBundle/Doctrine/RbacInitializer.php

Q  | A
License | MIT
Doc PR | -
Here is a list of improvements, let's discuss if they're good or not.
1. [Allow `--no-interaction`](https://github.com/Sylius/Sylius/pull/2599/files#diff-b337bb2bae6f6c79cdda641893ca9abbR101) option on sylius:install commands.
2. When using `sylius:install` commands and/or fixtures, if you've already initialized RBAC data it will throw a `Doctrine\ORM\NonUniqueResultException` exception. [Line 64](https://github.com/Sylius/Sylius/pull/2599/files#diff-f8ad521889bf078a95f5ae0043792a6aR64) Is it safe if we just ignore this exception?

fix(InstallerBundle): Allow --no-interaction with some fixtures and database improvements

---

src/Sylius/Bundle/LocaleBundle/Controller/LocaleController.php

[LocaleBundle] Added check if locale is available before setting in context

---

src/Sylius/Bundle/WebBundle/Controller/Frontend/Account/AddressController.php
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Account/Address/index.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Account/Profile/index.html.twig

It's better to use `user` variable (in profile and address pages) just like other controllers and templates.
Also replaces: #2618.
@pjedrzejewski @aRn0D ping ;)

Use 'user' variable and fix Profile page 'buttons' error

---

src/Sylius/Bundle/CoreBundle/Checkout/Step/SecurityStep.php

I'm using SyliusCoreBundle inside my application (for handling only commerce parts of my site) and I have my own user bundle, so I just wanted to override `saveUser` to make it compatible with my own logic.
P.S
I have a `ProfileBundle` to decouple commerce-related user fields to a dedicated `CommerceProfile` and have my own `UserBundle` which has a simple clean `User` model - each User can have many `Profile`s.

Use FOS UserInterface for easier extending

---

src/Sylius/Bundle/WebBundle/Controller/Frontend/Account/AddressController.php

| Bug fix?      | kind of
If you want to override the AddressController, you can't reuse some of its methods because they are private so I switched their visibility to protected.
Are you all right with that @pjedrzejewski ?

Fix AddressController methods visibility

---

src/Sylius/Component/Cart/Context/CartContextInterface.php
src/Sylius/Component/Currency/Context/CurrencyContextInterface.php
src/Sylius/Component/Locale/Context/LocaleContextInterface.php

Unfortunately PHP will convert **dot**s into underscore when parsing cookie names! So we have to remove dots in our `STORAKE_KEY`s so that is possible to use a CookieStorage.
[The full list of field-name characters that PHP converts to _ .](http://ca.php.net/manual/en/language.variables.external.php#81080)
[A random blog post .](http://harrybailey.com/2009/04/dots-arent-allowed-in-php-cookie-names/)

Fix STORAGE_KEY bug when using CookieStorage

---

features/pricing/volume_based_pricing.feature
src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
src/Sylius/Component/Pricing/Calculator/VolumeBasedCalculator.php

Look at https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php#L295
If the range is `30+` then the generated pricing configuration for `setPricingConfiguration()` is
``` php
array(
'min' => null,
'max' => 30,
// ...
)
```
whereas it should be :
``` php
array(
'min' => 30,
'max' => null,
// ...
)
```
What am I missing ?

Volume-based setPricingConfiguration parameter is counterintuitive

---

src/Sylius/Bundle/PricingBundle/Form/Extension/PriceableTypeExtension.php

@pjedrzejewski @stloyd I'm working on a AngularJS admin and now that I'm working on field prototypes this portion of code is breaking my code.
I expect `prototypes` var to contain an associative array in which the keys are **exactly** equal to the values that the "value provider" field generates (in this `PricingBundle` case, the `pricingCalculator` is the "value provider").
So that I can find appropriate calculator `prototype` based on current `pricingCalculator` value on my forms.
I took a quick look around the whole source code and couldn't find any use of `$group` prefix for `prototypes` array.

[PricingBundle] Remove unnecessary complexity

---

src/Sylius/Bundle/AttributeBundle/Form/EventListener/BuildAttributeFormChoicesListener.php
src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeValueType.php
src/Sylius/Bundle/ResourceBundle/Resources/views/forms.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/Form/_attributes.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductAttribute/_form.html.twig

Hopefully fixes #2575 and also a little bug in `collection_widget` that could not work with collections which have only a single form type such as a collection of `text` types.

[AttributeBundle] Fix CollectionType and AttributeChoices form type

---

src/Sylius/Bundle/AttributeBundle/Form/EventListener/BuildAttributeFormChoicesListener.php

Should not save 'choices' in attribute configuration when type is not choice, otherwise when user selects `choice` as attribute type then he changes back to `text` we're going to have `Unknown option [choices]` when rendering the form.

[AttributeBundle] Do not save unnecessary 'choices' in attribute configuration

---

src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/DoctrineODMDriver.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/DoctrinePHPCRDriver.php
src/Sylius/Bundle/ResourceBundle/spec/DependencyInjection/Driver/DoctrineODMDriverSpec.php
src/Sylius/Bundle/ResourceBundle/spec/DependencyInjection/Driver/DoctrinePHPCRDriverSpec.php

| Fixed tickets |  -
Its my mistake. MongoODM document managers called like `doctrine_mongodb.odm.%s_document_manager` but now its `doctrine.odm.mongodb.%_document_manager`. And `%s` missed.

Fix Mongo and PHPCR document managers service names

---

src/Sylius/Bundle/InventoryBundle/DependencyInjection/SyliusInventoryExtension.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/AbstractResourceExtension.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php
src/Sylius/Bundle/ResourceBundle/EventListener/LoadODMMetadataSubscriber.php
src/Sylius/Bundle/ResourceBundle/EventListener/LoadORMMetadataSubscriber.php
src/Sylius/Bundle/SettingsBundle/DependencyInjection/SyliusSettingsExtension.php

When two applications have the two resources with the same name one on them is going to be overridden in `sylius.config.classes`, so I have stored resources' classes under their application names in `sylius.config.classes`.

[ResourceBundle] Fix conflict of resource names in sylius.config.classes

---

src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
src/Sylius/Bundle/MailerBundle/Renderer/Adapter/TwigAdapter.php
src/Sylius/Bundle/MailerBundle/Sender/Adapter/SwiftMailerAdapter.php
src/Sylius/Component/Mailer/Event/EmailRenderEvent.php
src/Sylius/Component/Mailer/Event/EmailSendEvent.php
src/Sylius/Component/Mailer/Renderer/Adapter/AdapterInterface.php
src/Sylius/Component/Mailer/Sender/Adapter/AdapterInterface.php
src/Sylius/Component/Mailer/Sender/Sender.php
src/Sylius/Component/Mailer/SyliusMailerEvents.php
src/Sylius/Component/Mailer/spec/Sender/SenderSpec.php

```
```
In our app we need to add custom headers before sending emails, and thought this might be something other people could need.
Also in `` src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php`` the mailer services where not being loaded (don't know if this is on purpose or not).

Throw event before and after sending email

---

src/Sylius/Bundle/ResourceBundle/EventListener/LoadORMMetadataSubscriber.php

Hey!
We have some trouble with the translation repositories. Given you want to put a custom repository on a model, then this one will be used for model/translation instead of using the model one for the model and the translation one for the translation. Then, this PR splits the logic between model and translation repositories in order to fix the issue.

Fix translation

---

src/Sylius/Component/Mailer/Provider/EmailProvider.php

Hi,
This PR allow to overwrite the `getEmailFromConfiguration` method of the `EmailProvider`.

Change visibility of getEmailFromConfiguration

---

src/Sylius/Bundle/WebBundle/Menu/FrontendMenuBuilder.php

Change visibility of createTaxonomiesMenuNode because if you override method createTaxonomiesMenu, then can't call method createTaxonomiesMenuNode

Change visibility of createTaxonomiesMenuNode

---

src/Sylius/Bundle/RbacBundle/DependencyInjection/Configuration.php

Q  | A
Bug fix?  | no
BC breaks? | yes
License | MIT
Doc PR | -
I needed to append some roles under `administrator` in my project. In fact I have a plugin system so that every bundle has its own `config.yml`, hence they might try to add addtional roles under adminstrator. 
Since currently there is no way to dynamically modify `Rbac` information I thought I can use symfony's config merging as an easy way to extend `rbac` in my plugins, but to be able to do that I need to remove `performNoDeepMerging` from `roles_hierarchy`.
Do you guys think it's safe and right to do this on original `RbacBundle`?
/cc @pjedrzejewski @stloyd

[RbacBundle] Allow deep merging for roles_hierarchy

---

src/Sylius/Bundle/AttributeBundle/Form/EventListener/BuildAttributeValueFormListener.php
src/Sylius/Component/Attribute/Model/AttributeValue.php

Merge PR #2674 and #2675
Q | A
------------ | -------------
Bug fix? | yes
Fixed tickets | #2575
Tests pass? | yes
License | MIT

fix attribute choice value

---

src/Sylius/Bundle/SettingsBundle/DependencyInjection/SyliusSettingsExtension.php

| Fixed tickets | #2684
SyliusSettingsBundle currently requires %sylius_cache% to be set, but
this variable doesn't exist when using it standalone. I am providing
this PR based on @stloyd's comments in #2684

[SettingsBundle] default to file_system cache if %sylius.cache% is not set

---

src/Sylius/Bundle/SettingsBundle/Event/SettingsEvent.php
src/Sylius/Bundle/SettingsBundle/Manager/SettingsManager.php
src/Sylius/Bundle/SettingsBundle/Resources/config/services.xml
src/Sylius/Bundle/SettingsBundle/spec/Manager/SettingsManagerSpec.php

Q  | A
Bug fix?  | no
License | MIT
Doc PR | -

[SettingsBundle] Add post and pre save events on settings persistance

---

src/Sylius/Bundle/ResourceBundle/DependencyInjection/AbstractResourceExtension.php

Q  | A
License | MIT
Doc PR | -
If `sylius.config.classes` is not defined before first loaded bundle, its config classes will not be added in `sylius.config.classes`.

[ResourceBundle] Classes of first extension may get lost

---

src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php

I tried to override the order number generator. But, I got an exception saying something like Parse error, unexpected * etc. I changed it to this and it worked.

fix query select for order number

---

src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php

Without this change, in API returns, it will generate prev / next page route without get parameter, and it can be a problem sometimes.
```
"next": {
"href": "http://example.com/search?page=2"
}
```
```
"next": {
"href": "http://example.com/search?page=2&keyword=foo"
}
```

Create routes with GET parameters.

---

src/Sylius/Bundle/ContentBundle/Form/Type/ImagineBlockType.php
src/Sylius/Bundle/ContentBundle/Resources/config/services.xml

Q  | A
Bug fix?  | no
License | MIT
Doc PR | -

[ContentBundle] Show all available filters in imagine block form

---

src/Sylius/Bundle/RbacBundle/Provider/SecurityIdentityProvider.php
src/Sylius/Bundle/RbacBundle/spec/Provider/SecurityIdentityProviderSpec.php

Q  | A
License | MIT
Doc PR | -
Because of this line:
https://github.com/symfony/Security/blob/master/Http/Firewall/AnonymousAuthenticationListener.php#L54

[RbacBundle] Do not throw exception when user is anonymous

---

src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/Variant.orm.xml

Q  | A
Bug fix?  | no
License | MIT
Doc PR | -
If it's really not a BC I think it should allow null value.

[ProductBundle] Allow nullable availableOn field for product varaints

---

src/Sylius/Bundle/InstallerBundle/Command/CommandExecutor.php
src/Sylius/Bundle/InstallerBundle/spec/Command/CommandExecutorSpec.php

| Fixed tickets | #2736 
There are no BC breaks in the class API but as this does change behaviour it's possible people are relying on the existing (broken) behaviour which could cause a BC break.

2736 fix issues with command parameters

---

src/Sylius/Bundle/CoreBundle/EventListener/MailerListener.php
src/Sylius/Bundle/CoreBundle/Mailer/Emails.php
src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
src/Sylius/Bundle/CoreBundle/Resources/config/mailer.xml
src/Sylius/Bundle/ShippingBundle/Controller/ShipmentController.php
src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/WebBundle/Resources/views/Email/shipmentConfirmation.html.twig

| Fixed tickets | [#413]
Hey ya! This triggers a shipping confirmation E-Mail once you click "Ship" on an order.

Added Shipping confirmation E-Mail

---

src/Sylius/Bundle/TranslationBundle/Provider/RequestLocaleProvider.php

Implements the solution proposed by @pjedrzejewski in #2748.

Return default locale if request has not been injected (Fixes #2748)

---

src/Sylius/Bundle/SearchBundle/DependencyInjection/Configuration.php

Fixes #2742 
| Fixed tickets | #2742 
This is a potential BC-break as people may have been relying on the behaviour that has changed, e.g. they had added their own extra price ranges to the faceted search (on top of the provided ones). This would be relatively easy to fix in that they could just add the default ranges from the bundle to their own config.

[Search] Allow override of price facet ranges

---

src/Sylius/Bundle/AttributeBundle/EventListener/LoadMetadataSubscriber.php

| Fixed tickets | Unkown
| Doc PR        | N/A
In this case the `referencedColumnName` was hardcoded is 'id', so the
listener couldn't support any entities that do not follow this naming
convention.  That pretty much made AttributeOverride and
AssociationOverride powerless, so I've changed this.

[AttributeBundle] Improve AssociationOverride support by inferring column names

---

src/Sylius/Bundle/UserBundle/Controller/SecurityController.php

| New feature?  | kind of
This is to enable easy customization of login action, as it is already done in FOSUB.

Use same mechanism as FOSUB for SecurityController

---

src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php

This fixes an issue when running php app/console sylius:install:setup
```
Please enter list of locale codes, separated by commas or just hit ENTER to use "en_US". For example "en_US, de_DE".
In which language your customers can browse the store?
Adding English (United States).
Please enter list of currency codes, separated by commas or just hit ENTER to use "USD". For example "USD, EUR, GBP".
In which currency your customers can buy goods?
Adding US Dollar.
Please enter list of country codes, separated by commas or just hit ENTER to use "US". For example "US, PL, DE".
To which countries you are going to …
```

[InstallerBundle] Fixed setup command

---

src/Sylius/Bundle/PromotionBundle/Controller/CouponController.php

The entity instance is already injected.

Remove unnecessary new instance of Instruction

---

src/Sylius/Bundle/InstallerBundle/Command/CommandExecutor.php
src/Sylius/Bundle/InstallerBundle/spec/Command/CommandExecutorSpec.php

| Fixed tickets | #2762
`--no-interaction` default param must be absent if input option value !== `true`.
Otherwise the `sylius:install` sub-commands are non-interactive, the questions get skipped and it ends up in the endless while loop trying to validate the non-present user input.
This is because `--no-intercation` is a `InputOption::VALUE_NONE` option which does not require a value. If the `--no-interaction` key is present in Sylius default parameters (even if value is `false`!), then the subcommands are always non-interactive, skipping the questions, see `Symfony\Component\Console\Application::configureIO()` – it does …

[InstallerBundle] fix 'no-interaction' default param

---

src/Sylius/Bundle/CoreBundle/EventListener/OrderPaymentListener.php

I noticed that if you are using CreditCard for payment and if you change your mind on page where you need to enter your credit card, jump back to payment methods and pick something else for example offline that there is bug and you cannot complete payment. This PR fix it

Fixed bug in payment flow

---

src/Sylius/Bundle/WebBundle/Resources/public/js/form-collection.js
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/Form/_volume_based_config.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductVariant/Form/_volume_based_config.html.twig

Getting an item's name from collection's children count is unreliable and caused data loss when items got deleted and shuffled around or when there were other child elements in the collection element. This fixes that issue by actually checking if the items are present.
Inspired by [Bootstrap's solution](https://github.com/braincrafted/bootstrap-bundle/blob/v2.1.2/Resources/js/bc-bootstrap-collection.js#L42-L50).
It's still very fast even with thousands of items in a collection.

Fixes collection name deciding script causing item overwriting

---

src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/ZoneMemberZone.orm.xml

A zone cannot be deleted if it has a member. Deleting a zone should delete members as well.

Zones cannot be deleted if they have members

---

src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Account/layout.html.twig

This applies essentially the same patch as ffdf42d0 to a template that they forgot to patch in PR #1229.
This fixes an issue where flash messages would be displayed inconsistently (in our experience the *success* messages after successful payment didn't show up while the *error* ones did).

fixes flash message in overriding template

---

src/Sylius/Bundle/ResourceBundle/Form/Extension/DateExtension.php
src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml
src/Sylius/Bundle/ResourceBundle/spec/Sylius/Bundle/ResourceBundle/Form/Extension/DateExtensionSpec.php

[ResourceBundle] The date type has been improved

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php

When coupon has `expiresAt` date set, this error may occur:
```
Error: Object of class DateTime could not be converted to string
…//vendor/doctrine/dbal/lib/Doctrine/DBAL/
Connection.php (694)
…81352/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/
SingleSelectExecutor.php (50)
/vendor/doctrine/orm/lib/Doctrine/ORM/
Query.php (286)
…/vendor/doctrine/orm/lib/Doctrine/ORM/
AbstractQuery.php (794)
…/vendor/doctrine/orm/lib/Doctrine/ORM/
AbstractQuery.php (646)
…/vendor/doctrine/orm/lib/Doctrine/ORM/
AbstractQuery.php (674)
…or/sylius/sylius/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/
OrderRepository.php (198) …
```

Fix: Object of class DateTime could not be converted to string

---

src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadApiData.php

In order to have access to resources we should have proper authorization role assigned.

[FixturesBundle] Allow access to resources for api user on fixtures load

---

src/Sylius/Bundle/CoreBundle/OrderProcessing/TaxationProcessor.php

Methods processTaxes and addAdjustments are private.
This PR change the visibility of these methods to protected.

Allow to overwrite TaxationProcessor

---

src/Sylius/Bundle/ShippingBundle/Form/Type/Calculator/WeightRateConfigurationType.php
src/Sylius/Bundle/ShippingBundle/Resources/translations/messages.en.yml
src/Sylius/Component/Shipping/Calculator/WeightRateCalculator.php
src/Sylius/Component/Shipping/spec/Calculator/WeightRateCalculatorSpec.php

Add the ability to use a linear function for the weight shipping charges (`a + b*x`, here the `a` is added).

Add a fixed parameter in WeightCalculator

---

src/Sylius/Bundle/CoreBundle/Authorization/ToggleableAuthorizationChecker.php
src/Sylius/Bundle/CoreBundle/Context/CurrencyContext.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/spec/Context/CurrencyContextSpec.php
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadZonesData.php
src/Sylius/Bundle/RbacBundle/Behat/RbacContext.php
src/Sylius/Bundle/SettingsBundle/spec/Factory/SettingsFormFactorySpec.php
src/Sylius/Bundle/SettingsBundle/spec/Schema/SchemaRegistrySpec.php
src/Sylius/Bundle/SettingsBundle/spec/Templating/Helper/SettingsHelperSpec.php
src/Sylius/Bundle/TaxationBundle/Behat/TaxationContext.php
src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/settings.yml
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/layout.html.twig

Q  | A
Bug fix?  | no
BC breaks? | yes
License | MIT
Doc PR | -

[CoreBundle] Use more specific names for settings namespaces

---

src/Sylius/Bundle/SettingsBundle/DependencyInjection/SyliusSettingsExtension.php

Now it cause exception:
```
[Symfony\Component\Debug\Exception\ContextErrorException]                    
Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineCacheBu  
ndle\DependencyInjection\Configuration::resolveNodeType() must be of the ty  
pe array, string given
```

[SettingsBundle] fix for fix default to file_system cache

---

src/Sylius/Bundle/WebBundle/Resources/public/js/backend.js

| BC breaks?    | no (I think)
| Fixed tickets | [comma separated list of tickets fixed by the PR]
| Doc PR        | [The reference to the documentation PR if any]
The motivation here is to allow the datetime comparison operators in the
database layer to was done so that native database comparisons can do
their job.

[WebBundle] Change $.fn.datepicker format to yyyy-mm-dd.

---

src/Sylius/Bundle/ResourceBundle/Controller/Configuration.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/ConfigurationSpec.php
src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/country.yml

If specify default sorting order in config:
```yml
sylius_backend_country_index:
path: /
methods: [GET]
defaults:
_controller: sylius.controller.country:indexAction
_sylius:
template: SyliusWebBundle:Backend/Country:index.html.twig
sortable: true
paginate: 50
sorting:
name: asc
```
and trying sort table manually GET /administration/countries/?sorting%5BisoName%5D=asc
Query will contain:
```SQL
ORDER BY o.name ASC, o.isoName ASC
```
but should be
```SQL
ORDER BY o.isoName ASC, o.name ASC
```

[ResourceBundle] fix merging request and config sorting parameters

---

src/Sylius/Bundle/CoreBundle/EventListener/MailerListener.php

Q  | A
License | MIT
Doc PR | -
Is it correct to get email from customer model? Because there's no `getEmail()` method on `Order` model.

[CoreBundle] Fix shipment confirmation email to correctly get email

---

src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_variant.yml

ProductVariant has no field "product" - it has "object". The "id"
criteria was useless since it is ignored by the API route controller
which takes the parameter directly.
Fixes this error:
[Semantical Error] line 0, col 112 near 'product = :product': Error: Class ...\ProductVariant has no field or association named product
It appeared when accessing `/api/products/<productId>/variants/<variantId>`.

fixes API routes for product_variant actions

---

README.md
behat.yml.dist

This PR adds an ability to test JS scenarios of given suite. `@javascript` meta-tag was deleted and replaced with `javascript` profile.

Improved Behat configuration

---

src/Sylius/Bundle/InstallerBundle/Command/AbstractInstallCommand.php

| Fixed tickets | #2810, https://github.com/Sylius/Sylius-Standard/issues/64
Prevents 'NoSuchMetadataException' for Symfony versions > 2.5

[InstallerBundle] Fix setup command

---

src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/country.yml

Fix the exception on `sylius_backend_country_index` page:
RuntimeException: Cannot select distinct identifiers from query with LIMIT and ORDER BY
on a column from a fetch joined to-many association. Use output walkers.
cf. http://demo.sylius.org/administration/countries/

Fix country sorting

---

src/Sylius/Bundle/ResourceBundle/Controller/Configuration.php
src/Sylius/Bundle/ResourceBundle/Controller/RedirectHandler.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/RedirectHandlerSpec.php

Q | A
Bug fix? | no
New feature? | kind of
License | MIT
Doc PR | -
Add the ability to intercept a redirection. Use case: an xhr request. In javascript it is not possible to catch a redirection, so this way enable the JS to get this HTTP 200 response, and read the defined `X-SYLIUS-LOCATION` header, so that it can decide to redirect or not.

Enable header redirection in RedirectHandler

---

src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php

| New feature?  | kind of
Just add the ability to pass options when creating form from ResourceController.

Add optional $options parameters to getForm method

---

src/Sylius/Bundle/AttributeBundle/Form/EventListener/BuildAttributeValueFormListener.php
src/Sylius/Bundle/AttributeBundle/spec/Form/EventListener/BuildAttributeValueFormListenerSpec.php

Q | A
Bug fix? | yes
License | MIT
Doc PR | -
In product attribute value form, there an event listener which tries to remove `attribute` field. But when we're using this form in APIs removing this field is going to raise some issues. (Form serialization, extra fields, etc)
So if removing this field is only for a better view, IMO it's better to keep than make the form unsable in some situations.
What do you think?

[AttributeBundle] Product attribute value is not API friendly

---

src/Sylius/Bundle/ResourceBundle/Controller/Configuration.php

Q | A
Bug fix? | no
License | MIT
Doc PR | -
So that with the same route, you can choose to have an header redirection only when the request is done by XmlHttpRequest. Very useful!
I was wondering if this should be the default behavior, but at the end with these values (true, false or 'xhr') we can let the developer choose.

Add xhr option to header redirection

---

src/Sylius/Bundle/CoreBundle/Controller/LocaleController.php
src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/LocaleBundle/Controller/LocaleController.php
src/Sylius/Bundle/WebBundle/Resources/config/services.xml

Q  | A
Bug fix?  | no
Fixed tickets | Fixes #2944
License | MIT
Doc PR | -
This change allows the admin to see all enabled locales (not only current channel available ones) when editing translations. 
Translations form type is using [LocaleBundle provider](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/main.yml#L160) so it selects all enabled locales.

[CoreBundle] Decouple original locale provider and channel-aware locale provider

---

src/Sylius/Bundle/TranslationBundle/GedmoHandler/TranslationSlugHandler.php

`empty()` is a safer check in the case that somehow the `$this->parentSlug` got set to NULL.

Fixed Bad Refactor in transliterate

---

src/Sylius/Bundle/CoreBundle/Context/CurrencyContext.php
src/Sylius/Bundle/FlowBundle/Storage/SessionFlowsBag.php
src/Sylius/Component/Core/Locale/LocaleContext.php

Bug fix: yes
BC break: no
Dots are replaced by underscores in PHP, so we should avoid using dot in parameter name. (ie: cookie name)
Without this fix, `CookieStorage` will not be able to retrieve what it set.
See more discussion in Symfony: https://github.com/symfony/symfony/issues/9009

Replace dot with underscore in parameter name.

---

src/Sylius/Component/Taxonomy/Model/Taxonomy.php
src/Sylius/Component/Taxonomy/spec/Model/TaxonomySpec.php

Q | A
Bug fix? | yes
License | MIT
Doc PR | -
Sometimes (e.g. submitting forms) entity's `Translation`s current locale is not set so we need to set it manually. 
Our current issue is that after creating `Taxonomy` from API `$resource` is going to be serialized for the response, because `$currentLocale` on root Taxon is not set we're going to have a `No current locale` exception.

[Taxonomy] Set root taxon locale based on current taxonomy locale

---

app/autoload.php

I tried running Sylius with PHP7 last weekend, and I had issues getting it to run. After reading https://github.com/doctrine/phpcr-odm/pull/412, it seems like this line is no longer necessary, and it will stop including the String class.
This should probably stop the PHP7 travis tests from breaking where it does now.
A separate pull request is also required for the Sylis/Standard, as it's autoload also has the same line.

Stop registering PHPCR ORM annotations in autoload

---

src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php

Removed side effect.
| Bug fix?      | yes (a little bit)
| BC breaks?    | yes (event listeners will get Doctrine with enabled  `softdeleteable` filter)

[ResourceBundle] Turning on back softdeleteable filter just after necessary operations

---

src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductAttribute/_form.html.twig

Fixed setting choices for product attribute by removing bootstrap "hide" class which does not work with jQuery show(). Visibility is now handled by JS only.
Also .hide class is deprecated.

[WebBundle] Fixed showing ProductAttribute choices

---

src/Sylius/Bundle/PayumBundle/Payum/Offline/Action/CapturePaymentAction.php

Status field is not set which results in a cancelled order when processing an order with the offline gateway

Status field not set on offline gateway

---

src/Sylius/Bundle/UserBundle/Resources/config/serializer/Model.User.yml

The title nearly says it all.  `int` simply isn't a valid JMS serialization type, it should be `integer`.

[UserBundle] Fix invalid serialization type 'int' to 'integer'.

---

src/Sylius/Component/Rbac/Authorization/CachedPermissionMap.php

Caching infinitely requires invalidating the cache entries whenever
roles or permissions are modified.  We could use a "sane" default TTL,
or make it configurable, or figure out an invalidation strategy, or...
But I think infinite by default is pretty unexpected behavior.

[RFC][Rbac] Use a finite default ttl in CachedPermissionMap.

---

src/Sylius/Bundle/TranslationBundle/GedmoHandler/TranslationSlugHandler.php

This fixes some backward compability issues with PHP7. See https://wiki.php.net/rfc/uniform_variable_syntax for more info.

Compatibility with PHP7 beta (Uniform Variable Syntax issue)

---

src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
src/Sylius/Bundle/ApiBundle/Resources/config/routing/setting.yml
src/Sylius/Bundle/SettingsBundle/Controller/SettingsController.php

Q  | A
License | MIT
Doc PR | -
* Add showAction for Settings schema's for API consumers. `/api/settings/{namespace}`
* `showAction` and `updateAction` now will not throw `MissingOptions` exception which is annoying when it's the first to read/update a Settings schema through an API call. (If there's a better way than ignoring this exception that'd be nice to guide me on that)

[Settings] Add API routes for SettingsController and some improvements

---

src/Sylius/Bundle/RbacBundle/Doctrine/RbacInitializer.php

| BC breaks?    | unlikely
Previously, you could basically only use the RbacInitializer once, to
create roles with their permissions. If you add new permissions to
existing roles (e.g. via configuration like rbac.yml) these won't be
added by the initializer.
This commit makes the initializer always try to add new permissions to
roles, new or old, and updates the console output a bit to reflect the
behavior.

[RbacBundle] Teach the RbacInitializer to append new permissions

---

src/Sylius/Bundle/RbacBundle/EventListener/CacheListener.php
src/Sylius/Bundle/RbacBundle/Resources/config/driver/doctrine/orm.xml

Add postUpdate event to CacheListener to ensure that the cache is cleared when permissions are added to and removed from roles through the admin.

[Rbac] Clear permissions cache on postUpdate fix

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php

| BC breaks?    | yes, if users are currently anticipating the bug and changing behavior to work around
| Fixed tickets | #3122 
It was using the updatedAt column instead of the expiresAt column.  Big difference!

[CoreBundle] Fix findExpired orders method query

---

src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php

Q  | A
Bug fix?  | no
License | MIT
Doc PR | -
When using ResourceBundle standalone, the classes defined under `sylius_resource.resources` config are not added to the `sylius.config.classes` parameter (cf [SyliusResourceExtension.php#L49](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php#L49)).
But it is this parameter that is injected in the ORMMetadataListener, for assigning repository to their model in Doctrine for example (cf [LoadORMMetadataSubscriber.php#L76](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/EventListener/LoadORMMetadataSubscriber.php#L76)).
This PR fixes this :)

[ResourceBundle] Include sylius_resource classes in metadatalistener

---

src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
src/Sylius/Bundle/CoreBundle/EmailManager/OrderEmailManager.php
src/Sylius/Bundle/CoreBundle/EmailManager/ShipmentEmailManager.php
src/Sylius/Bundle/CoreBundle/EventListener/MailerListener.php
src/Sylius/Bundle/CoreBundle/Resources/config/email.xml
src/Sylius/Bundle/CoreBundle/Resources/config/state-machine.yml

| Fixed tickets | https://github.com/Sylius/Sylius/issues/2915, https://github.com/Sylius/Sylius/issues/2514
Pretty simple PR, just moves the order and shipment confirmation email listeners to use the state machine instead of the event listener. In that process, it also fixes a bug. (Order email confirmation listener was bound to the wrong event).

[CoreBundle] Use state machine for order and shipment email confirmation

---

features/frontend/products.feature
src/Sylius/Bundle/CoreBundle/Routing/RouteProvider.php
src/Sylius/Bundle/WebBundle/Behat/WebContext.php

| Fixed tickets | #3011 
After passing empty string as product slug, NonUniqueResultException was thrown, due to "findOneBy" method. Now it simply does not generate route, as for invalid slug.
However, it should be considered to generate some "invalidate product" page, rather than "No route found" exception :)

Fixed empty product slug bug

---

src/Sylius/Bundle/WebBundle/Event/MenuBuilderEvent.php
src/Sylius/Bundle/WebBundle/Menu/FrontendMenuBuilder.php

The [docs state](http://docs.sylius.org/en/latest/cookbook/extending-menu.html) that extending the menus via events is "available only for the backend at the moment."  This PR hopes to fix that for everyone.  I'll update the docs accordingly if we get that far.

[WebBundle] Dispatch events after building frontend menus.

---

src/Sylius/Bundle/CoreBundle/Kernel/Kernel.php
src/Sylius/Bundle/CoreBundle/Resources/config/state-machine.yml
src/Sylius/Bundle/InventoryBundle/Resources/config/state-machine.yml
src/Sylius/Bundle/OrderBundle/Resources/config/state-machine.yml
src/Sylius/Bundle/PaymentBundle/Resources/config/state-machine.yml
src/Sylius/Bundle/ShippingBundle/Resources/config/state-machine.yml

| New feature?  | refactor
But `SyliusResourceBundle` should be registered before `winzouStateMachineBundle`...

Use unused parameter %sylius.state_machine.class%

---

src/Sylius/Component/Promotion/Generator/CouponGenerator.php
src/Sylius/Component/Promotion/Generator/CouponGeneratorInterface.php

Hello there,
I had to use coupon generator and afterwards send out an email with the generated codes.
Doesn't it make more sense to return a structure containing the coupons instead of having to query back the
db for those?
This change works great for me but maybe it affects sylius in a way I cannot see at the moment. Please let me 
know in case this can be achieved in any other way.
Cheers,
Argiris

generate function to return generated coupons

---

src/Sylius/Bundle/ResourceBundle/Behat/DefaultContext.php
src/Sylius/Bundle/ResourceBundle/Behat/WebContext.php

**TL;DR**: You can add `%` at the beginning and the end of searched string and it will work just like SQL `LIKE` statement (no support for one-side `%` yet).
- `I should see resource with name containing "value"` is equal to `I should see resource with name "%value%"` (same comes with negation)
- `I should see the following rows: | name | %value% |` (same comes with negation)

[Behat] Steps for checking whether row contains given value (not starts with)

---

src/Sylius/Bundle/UserBundle/Controller/UserController.php

The immediate fix for #3167 while more complete fix is baked.

[UserBundle] Dispatch user event *before* persisting user, so side effects persist too.

---

src/Sylius/Bundle/ArchetypeBundle/EventListener/LoadMetadataSubscriber.php
src/Sylius/Bundle/ArchetypeBundle/spec/EventListener/LoadMetadataSubscriberSpec.php

Q | A
Bug fix? | yes
License | MIT
Doc PR | -
When I want to delete a product option, because of the foreign key constraint of `CASCADE` all related records will also get deleted from tables below:
- sylius_product_option
- sylius_product_option_translation
- sylius_product_option_value
but product option relation to product archetype (`sylius_product_archetype_option`) does not have a `CASCADE` constraint (It's currently `RESTRICT`) so a constraint violation occurs.
Is it correct to add `CASCADE ON DELETE` relation constraint?

[ArchetypeBundle] Add ON DELETE CASCADE constraint on archetype

---

src/Sylius/Bundle/CoreBundle/EventListener/MailerListener.php
src/Sylius/Bundle/CoreBundle/spec/EventListener/MailerListenerSpec.php

| New feature?  | enhancement
- Adding specs for OrderMailerListener class
- Refactoring conditions to send the email

[CoreBundle] Adding MailerListenerSpec, fixing CS, small refactor

---

src/Sylius/Bundle/UserBundle/Controller/UserController.php
src/Sylius/Bundle/UserBundle/Resources/config/services.xml
src/Sylius/Bundle/UserBundle/UserEvents.php

More info about this PR here: https://github.com/Sylius/Sylius/issues/3167
I'm happy to change the events description if anyone has better ideas.

Fixed user reset events

---

src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php

| Fixed tickets | #2892, #3004, #3027 
Even by setting false, Paginator didn't use output walkers, because of comparing set value to ``null``.

[Resource] Fix sorting bugs

---

app/migrations/Version20150629123648.php

Changed the fee_calculator & fee_calculator_configuration `CHANGE` queries to `ADD`, since both columns do not exist at that point yet.

Fee_calculator migration fix

---

src/Sylius/Bundle/InstallerBundle/Command/AbstractInstallCommand.php
src/Sylius/Bundle/InstallerBundle/Command/InstallAssetsCommand.php
src/Sylius/Bundle/InstallerBundle/Command/InstallSampleDataCommand.php

- Fixed critical error (checking permissions for unexisting file/directory `web/assets/*`, it stopped `sylius:install:assets` before anything can happen)
- Developer experience:
- Better messages (one for unexisting directory, one for bad permissions)
- Trying to create directory or set permissions on its own

[Installer] Fixed directory permission checks and improved DX

---

src/Sylius/Bundle/InstallerBundle/Command/InstallDatabaseCommand.php

Q  | A
License | MIT
Doc PR | -
On first installation we need to add currently in-place migration files in migrations table to prevent them from running when new ones are available on a production site.

[InstallerBundle] Add current migration versions to database on first installation

---

src/Sylius/Bundle/CoreBundle/OrderProcessing/TaxationProcessor.php
src/Sylius/Bundle/TaxationBundle/DependencyInjection/Compiler/RegisterCalculatorsPass.php
src/Sylius/Bundle/TaxationBundle/Form/Type/TaxCategoryChoiceType.php
src/Sylius/Bundle/TaxationBundle/Resources/config/services.xml
src/Sylius/Bundle/TaxationBundle/composer.json
src/Sylius/Bundle/TaxationBundle/spec/DependencyInjection/Compiler/RegisterCalculatorsPassSpec.php
src/Sylius/Component/Taxation/Calculator/DelegatingCalculator.php
src/Sylius/Component/Taxation/spec/Calculator/DelegatingCalculatorSpec.php

@Sylius/core-team what do you think ?

[TaxationBundle] DelegatingCalculator use the ServiceRegistry

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php

When asking for items in a group, I believe it makes sense to consider the group's hierarchy at the same time and return a list that includes implicitly-included items.
Would be nice if we could extend the [NestedTreeRepository](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Entity/Repository/NestedTreeRepository.php) as it has some methods already to deal with this, but I don't see a way to hack that in  since it already must extend the ResourceRepository.
As a less flexible but simpler compromise, I'm interested to hear any thoughts on whether we could do something like the example in this PR.

[RFC][ProductBundle] When finding products in a given taxon, consider the whole tree.

---

features/backend/product_archetypes_i18n.feature
features/backend/products_i18n.feature
features/backend/taxonomies_i18n.feature
features/channels/channel_management.feature
features/frontend/cart_inclusive_tax.feature
features/frontend/cart_tax_categories.feature
features/frontend/cart_taxation.feature
features/frontend/checkout_addressing_i18n.feature
features/frontend/checkout_shipping_i18n.feature
features/frontend/products_i18n.feature
src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
src/Sylius/Bundle/PaymentBundle/Behat/PaymentContext.php
src/Sylius/Bundle/ProductBundle/Behat/ProductContext.php
src/Sylius/Bundle/ShippingBundle/Behat/ShippingContext.php
src/Sylius/Bundle/TaxonomyBundle/Behat/TaxonomyContext.php
travis/suites/suite-1
travis/suites/suite-2

There were 4 suites missing: `i18n`, `channels`, `search_orm_only` and `contact`. Added only three of them, because `contact` is currently under refactoring by @GSadee in #3164.
There were also 3 feature missing in `checkout` suite: `features/frontend/cart_taxation.feature`, `cart_tax_categories.feature` and `features/frontend/cart_inclusive_tax.feature`.

[Travis] Added missing Behat tests to Travis

---

src/Sylius/Bundle/CoreBundle/DataFetcher/NumberOfOrdersDataFetcher.php
src/Sylius/Bundle/CoreBundle/DataFetcher/SalesTotalDataFetcher.php
src/Sylius/Bundle/CoreBundle/DataFetcher/UserRegistrationDataFetcher.php
src/Sylius/Bundle/ReportBundle/Controller/ReportController.php
src/Sylius/Bundle/ReportBundle/DataFetcher/TimePeriod.php
src/Sylius/Bundle/ReportBundle/Renderer/ChartRenderer.php
src/Sylius/Bundle/ReportBundle/Renderer/TableRenderer.php
src/Sylius/Bundle/ReportBundle/spec/Renderer/ChartRendererSpec.php
src/Sylius/Bundle/ReportBundle/spec/Renderer/TableRendererSpec.php
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Dashboard/main.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Report/show.html.twig
src/Sylius/Component/Report/DataFetcher/DataFetcherInterface.php
src/Sylius/Component/Report/DataFetcher/DelegatingDataFetcher.php
src/Sylius/Component/Report/DataFetcher/DelegatingDataFetcherInterface.php
src/Sylius/Component/Report/Model/Report.php
src/Sylius/Component/Report/Model/ReportInterface.php
src/Sylius/Component/Report/Renderer/DelegatingRenderer.php
src/Sylius/Component/Report/Renderer/DelegatingRendererInterface.php
src/Sylius/Component/Report/Renderer/RendererInterface.php
src/Sylius/Component/Report/composer.json

Changeset:
* Fixed typo in method ReportController::embed**d**Action - BC Break
* Fixed typo in method TimePeriod::fillEmptyReco**dr**s
* Dependency for `TableRenderer` and `ChartRenderer` is lowered from Symfony FrameworkBundle to Symfony Templating. These renderers could be moved from the ReportBundle to the Report component.
* Added docblocks that were missing and fixed incorrect ones.

[Report] Decouple from Symfony FrameworkBundle; fix typos and docblocks

---

src/Sylius/Bundle/UserBundle/Form/EventListener/UserRegistrationFormListener.php
src/Sylius/Bundle/UserBundle/Resources/config/services.xml
src/Sylius/Bundle/UserBundle/Security/Authentication/AuthenticationUtils.php
src/Sylius/Bundle/UserBundle/Security/UserPasswordEncoder.php
src/Sylius/Bundle/UserBundle/spec/Security/UserPasswordEncoderSpec.php
src/Sylius/Component/User/Security/PasswordUpdater.php
src/Sylius/Component/User/Security/UserPasswordEncoderInterface.php
src/Sylius/Component/User/Security/UserPbkdf2PasswordEncoder.php
src/Sylius/Component/User/spec/Security/PasswordUpdaterSpec.php
src/Sylius/Component/User/spec/Security/UserPbkdf2PasswordEncoderSpec.php

| BC breaks?    | no (component hasn't been released yet :smile:)

[User] Remove Symfony security component dependecy

---

src/Sylius/Component/User/composer.json

Unfortunately we have to add this, because of `Symfony\Component\Security\Core\User\AdvancedUserInterface` dependency and PHP 5.3 limitations...

[User] Add temporary required dependency

---

src/Sylius/Bundle/PricingBundle/Form/EventListener/BuildPriceableFormSubscriber.php
src/Sylius/Bundle/PricingBundle/spec/Form/EventListener/BuildPriceableFormSubscriberSpec.php

Q | A
Bug fix? | yes
License | MIT
Doc PR | -
When using API, I had to post `pricingCalculator` in order to save product. Now with this change, it is not necessary to post it and it will use `standard` as default calculator.

[PricingBundle] Consider standard pricing calculator in priceable form types

---

src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/ReportBundle/Resources/config/services.xml
src/Sylius/Bundle/ReportBundle/composer.json

Thanks for merging the [other pull request](https://github.com/Sylius/Sylius/pull/3212), now the real issue - The ReportBundle is completely unusable because of the following error:
> Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'The service "sylius.form.type.report" has a dependency on a non-existent service "sylius.registry.report.data_fetcher"
These missing services are registered by the CoreBundle, so I've moved them to the ReportBundle.
Additionally, I've grouped and sorted the service definitions in alphabetical order (it …

[ReportBundle] Remove bi-directional dependency on the CoreBundle

---

features/backend/inventory.feature
features/backend/product_variants.feature
src/Sylius/Bundle/VariationBundle/Form/Type/OptionValueCollectionType.php
src/Sylius/Bundle/VariationBundle/spec/Form/Type/OptionValueCollectionTypeSpec.php
src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductVariant/macros.html.twig

Using option's presentation instead of name while displaying product variant on the list.

[WebBundle] Changed the way of displaying product variant's options

---

src/Sylius/Component/User/Security/UserPbkdf2PasswordEncoder.php

Removed plain PHP duplication of `hash_pbkdf2()`.

[User] Removed unnecessary method due to PHP version bump

---

src/Sylius/Bundle/UserBundle/Controller/UserController.php

Replaced `validateAccess()` with `denyAccessUnlessGranted()` shortcut inroduced in Symfony 2.6

[UserBundle] Refactored method due to Symfony version bump

---

src/Sylius/Bundle/UserBundle/Resources/config/serializer/Model.Customer.yml
src/Sylius/Bundle/UserBundle/Resources/config/serializer/Model.User.yml

| Fixed tickets | #3259
I have added Customer serialization definition and change slightly current User serialization. Email and emailCanonical fields removal from User, resulted in is small BC break.

[User] Serialization update

---

src/Sylius/Bundle/SettingsBundle/Manager/SettingsManager.php

I tried to find any previous issues / PRs regarding this. Is this not something you guys wanted to do? The only issue I could see with this is if someone is using `file_system` cache or another persistent cache in dev mode that default value changes to their schemas wouldn't be reflected (Edit: actually maybe not, this only caches parameters from the database, so default values would change). This could easily be solved by using `array` cache in dev mode. As I see it right now the settings only get cached when saved but if you clear caches you'd have to go to your settings after warmup and save them again to benefit from any caching.

[Settings] Cache parameters after fetching as well as saving.

---

src/Sylius/Bundle/WebBundle/Resources/views/Backend/Customer/macros.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Customer/show.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Macros/misc.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/_details.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/show.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Promotion/macros.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/menu.html.twig

[WebBundle] use of twig deprecated sameas

---

src/Sylius/Component/Inventory/Model/InventoryUnit.php
src/Sylius/Component/Inventory/Model/InventoryUnitInterface.php
src/Sylius/Component/Inventory/Model/StockableInterface.php

[Inventory] Removed fluent interfaces

---

src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentMethodChoiceType.php

Those dependencies aren't used in code or comments.

Remove unused dependencies

---

src/Sylius/Bundle/UserBundle/Context/CustomerContext.php

In one part of our site we don't need sylius autentication, just basic http with a generic username and password (which by default uses a Symfony user), so the Customer context fails when calling `->getCustomer()`.
Adding this check allows us to use basic http autentication.

Add check to customer context

---

src/Sylius/Component/Translation/Model/AbstractTranslatable.php
src/Sylius/Component/Translation/Model/AbstractTranslation.php
src/Sylius/Component/Translation/Model/TranslatableInterface.php
src/Sylius/Component/Translation/Model/TranslationInterface.php
src/Sylius/Component/Translation/spec/Model/AbstractTranslatableSpec.php
src/Sylius/Component/Translation/spec/Model/AbstractTranslationSpec.php

[Translation] Remove fluent interfaces

---

src/Sylius/Component/Product/Builder/ProductBuilder.php
src/Sylius/Component/Product/Builder/ProductBuilderInterface.php
src/Sylius/Component/Product/Model/Archetype.php
src/Sylius/Component/Product/Model/ArchetypeTranslation.php
src/Sylius/Component/Product/Model/Attribute.php
src/Sylius/Component/Product/Model/AttributeInterface.php
src/Sylius/Component/Product/Model/AttributeTranslation.php
src/Sylius/Component/Product/Model/AttributeTranslationInterface.php
src/Sylius/Component/Product/Model/AttributeValue.php
src/Sylius/Component/Product/Model/AttributeValueInterface.php
src/Sylius/Component/Product/Model/Option.php
src/Sylius/Component/Product/Model/OptionInterface.php
src/Sylius/Component/Product/Model/OptionTranslation.php
src/Sylius/Component/Product/Model/OptionTranslationInterface.php
src/Sylius/Component/Product/Model/OptionValue.php
src/Sylius/Component/Product/Model/OptionValueInterface.php
src/Sylius/Component/Product/Model/Product.php
src/Sylius/Component/Product/Model/ProductInterface.php
src/Sylius/Component/Product/Model/ProductTranslation.php
src/Sylius/Component/Product/Model/ProductTranslationInterface.php
src/Sylius/Component/Product/Model/Variant.php
src/Sylius/Component/Product/Model/VariantInterface.php
src/Sylius/Component/Product/spec/Model/ProductSpec.php

[Product] Removed fluent interfaces

---

src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php

[Core] Delete commented line in CoreContext

---

src/Sylius/Bundle/PromotionBundle/Form/Type/CouponGenerateInstructionType.php
src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Coupon/_form.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Coupon/_generateForm.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Coupon/macros.html.twig
src/Sylius/Component/Promotion/Generator/CouponGenerator.php
src/Sylius/Component/Promotion/Generator/Instruction.php
src/Sylius/Component/Promotion/spec/Generator/CouponGeneratorSpec.php

| Fixed tickets | #3302
I wasn't able to reproduce the fact that a newly created coupon cannot be used with the error message "coupon alread expired".

[Coupon] Add missing expiration date in the view

---

src/Sylius/Component/Core/Promotion/Action/AddProductAction.php
src/Sylius/Component/Order/Model/AdjustableInterface.php
src/Sylius/Component/Order/Model/Adjustment.php
src/Sylius/Component/Order/Model/AdjustmentInterface.php
src/Sylius/Component/Order/Model/Comment.php
src/Sylius/Component/Order/Model/CommentAwareInterface.php
src/Sylius/Component/Order/Model/CommentInterface.php
src/Sylius/Component/Order/Model/Identity.php
src/Sylius/Component/Order/Model/IdentityInterface.php
src/Sylius/Component/Order/Model/Order.php
src/Sylius/Component/Order/Model/OrderAwareInterface.php
src/Sylius/Component/Order/Model/OrderInterface.php
src/Sylius/Component/Order/Model/OrderItem.php
src/Sylius/Component/Order/Model/OrderItemInterface.php
src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php
src/Sylius/Component/Order/spec/Model/AdjustmentSpec.php
src/Sylius/Component/Order/spec/Model/OrderItemSpec.php
src/Sylius/Component/Order/spec/Model/OrderSpec.php
src/Sylius/Component/Originator/Originator/Originator.php
src/Sylius/Component/Sequence/Model/Sequence.php
src/Sylius/Component/Sequence/Model/SequenceInterface.php
src/Sylius/Component/Sequence/Model/SequenceSubjectInterface.php

[Order] Remove fluent interfaces

---

src/Sylius/Bundle/CoreBundle/Form/Type/Api/OrderType.php
src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.ProductVariant.yml
src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.Product.yml
src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php

Added new line in UserBundle configuration to auto generate customer choice type and Api OrderType fix.
Depends on #3332

Api order type fix

---

composer.json
composer.lock
phpspec.yml
src/Sylius/Bundle/MoneyBundle/spec/Templating/Helper/MoneyHelperSpec.php
src/Sylius/Bundle/ResourceBundle/composer.json
src/Sylius/Bundle/ResourceBundle/phpspec.yml
src/Sylius/Bundle/ResourceBundle/spec/Doctrine/ODM/MongoDB/DocumentRepositorySpec.php
src/Sylius/Bundle/TranslationBundle/composer.json
src/Sylius/Bundle/TranslationBundle/phpspec.yml
src/Sylius/Bundle/TranslationBundle/spec/Doctrine/ODM/MongoDB/TranslatableResourceRepositorySpec.php

This PR is updated part of #3356 which fixes broken specs, add missing dependecies & extension to the phpspec cofiguration files.
Also contains re-hashed `composer.lock` (no real updates), to not moan that lock files is outdated.

Add "akeneo/phpspec-skip-example-extension" dependency & fix broken specs

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml

Rbac permisions for managing order items was missing. They are only required during api calls probably.
Depends on #3338

[Order] [RBAC] Order item permission fix

---

src/Sylius/Bundle/WebBundle/Resources/public/css/backend.css
src/Sylius/Bundle/WebBundle/Resources/public/js/form-upload.js
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/Form/_images.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/layout.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Common/forms.html.twig

| Enhancement? | yes
| New feature? | no
| Fixed tickets | #3263
Styled upload button area is now fully clickable
Changes where also made in product image prototype html, for it to be consistent/working
Will also fix bugs with translated messages for upload button, as there is no need for the fixed width, that was present before
Filename of file that would be uploaded is shown, next to upload button.
Works with multiple file upload fields also if browser supports [HTML5 File API](http://caniuse.com/#feat=fileapi)

[Web][Form] - fixed unclickable upload buttons issue 3263

---

src/Sylius/Bundle/ResourceBundle/Behat/DefaultContext.php
src/Sylius/Bundle/ResourceBundle/Behat/FixtureContext.php
src/Sylius/Bundle/ResourceBundle/Behat/WebContext.php

Added controlled timeouts to "I am on specific page" and "resource should be created" steps.

[Behat] [Travis] Made Behat waiting for resources to appear

---

src/Sylius/Bundle/WebBundle/Resources/views/Backend/Customer/macros.html.twig

Correct keys available at https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml#L972

Fix translation keys for backend customer macro

---

src/Sylius/Bundle/WebBundle/Resources/views/Backend/Customer/show.html.twig

Single difference, that label "yes" would rendered as "YES", which is default behaviour for `Backend/Customer:index.html.twig`. So I consider this as fix in consistency.

Replace twig code with labe_state macro at backend customer show template

---

src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/User.orm.xml

While not exactly a bug, it have a great chance to become one. :)
Note that CoreBundle:Customer.orm.xml is correct and doesn't have softdeleteable duplication of mapping.

Remove unnessary softdeleteable in CoreBundle User mappings

---

src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadChannelData.php

When executing doctrine:fixtures:load (or any superset like sylius:install), channels would be without any associated taxonomies.
This would result in missing taxonomies on frontend, and possibly other important places.
PR adds all taxonomies for all channels.

[FixturesBundle] - added missing taxonomies associations for channels sample data

---

src/Sylius/Bundle/UserBundle/Resources/config/routing/registration.yml

It went unnoticed, because SyliusWebBundle rewrites registration route.

[UserBundle] Fix mistype in registration route

---

src/Sylius/Bundle/CoreBundle/EventListener/OrderPricingListener.php
src/Sylius/Bundle/CoreBundle/spec/EventListener/OrderPricingListenerSpec.php

In a condition we expect instance of `Sylius\Component\Core\Model\OrderInterface` but exception has message about  `Sylius\Component\`**Order**`\Model\OrderInterface`.

[Order] OrderListener exception message fix

---

src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php

While creating new administrator account in Sylius installer, it is not required to confirm password, which should be obvious, in my opinion ;)

[Installer] Added new administrator password confirmation

---

app/AppKernel.php

Enable debugBundle for dev/test environment by default
Many SF developers are used for the shorthand dump() function provided by debugBundle, and will register the bundle anyway.
This makes the DX better, as people will be able to use what they are used to.

[Sylius] - register DebugBundle by default in appKernel dev/test

---

src/Sylius/Bundle/ShippingBundle/Resources/config/state-machine.yml

Q  | A
Bug fix?  | no
License | MIT
Doc PR | -
I'm not very familiar with how state machines work, is this a correct way to add this transition?

[Shipping] Allow prepare transition from backordered state to ready state

---

src/Sylius/Bundle/InstallerBundle/Requirement/SettingsRequirements.php

Recommended version of was php lower then required,
required -> 5.5.9 
recommended -> 5.3.8
Also added constant for php recommended version RECOMMENDED_PHP_VERSION
set to 5.6.13, just because its current.
If anyone got suggestion what the recommended version should be, drop it here and I'll change it.

[InstallerBundle] - fixed recommended version of php lower then required

---

src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentType.php
src/Sylius/Bundle/PaymentBundle/Resources/translations/messages.en.yml

Payment has [authorization state](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Payment/Model/PaymentInterface.php#L27) which was not reachable from [PaymentFormType](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentType.php#L39). I have added this state to form type choices.

[Payment] Missing payment state added

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/main.yml

If you don't ask for the field "email" on facebook graph, sylius will crash trying to "INSERT INTO sylius_customer" with an empty e-mail where the field is required.

[Core] Fix problem authenticating with facebook

---

features/user/user_reset_password.feature
src/Sylius/Bundle/UserBundle/Controller/UserController.php
src/Sylius/Bundle/UserBundle/Form/EventListener/CustomerRegistrationFormListener.php
src/Sylius/Bundle/UserBundle/Resources/translations/flashes.en.yml
src/Sylius/Bundle/WebBundle/Resources/config/routing/frontend/user.yml

Hi, this PR fix some issues when user change, request or reset password.
Now, two flash messages are shown, <code>User has been successfully updated</code> and another message depending of the action, this PR avoid the apparition of the first message and change some translations related to these actions.

[UserBundle] Fix flash messages on UserController

---

features/frontend/checkout_shipping.feature
src/Sylius/Bundle/ResourceBundle/Form/DataTransformer/ObjectToIdentifierTransformer.php
src/Sylius/Bundle/ResourceBundle/spec/Form/DataTransformer/ObjectToIdentifierTransformerSpec.php
src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodChoiceType.php

| Fixed tickets | https://github.com/Sylius/Sylius/issues/2979
While fixing https://github.com/Sylius/Sylius/issues/2979 I realized, that ``ObjectToIdentifierTransformer`` has inversely implemented methods! It caused mentioned bug, but also some others. There is open PR for this issue (https://github.com/Sylius/Sylius/pull/3085) with implemented custom transformer, but I think it will be not necessary after accepting this one ;)

[Resource] Fix ObjectToIdentifierTransformer bad implementation

---

src/Sylius/Bundle/AddressingBundle/Form/Type/AddressType.php
src/Sylius/Bundle/AddressingBundle/Form/Type/CountryChoiceType.php
src/Sylius/Bundle/AddressingBundle/Form/Type/ProvinceChoiceType.php
src/Sylius/Bundle/CoreBundle/Checkout/CheckoutProcessScenario.php
src/Sylius/Bundle/CoreBundle/Form/Type/Action/AddProductConfigurationType.php
src/Sylius/Bundle/CoreBundle/Form/Type/CartType.php
src/Sylius/Bundle/CoreBundle/Form/Type/CountryType.php
src/Sylius/Bundle/CoreBundle/Form/Type/LocaleType.php
src/Sylius/Bundle/CoreBundle/Form/Type/Rule/ContainsProductConfigurationType.php
src/Sylius/Bundle/CoreBundle/Form/Type/Rule/CustomerGroupType.php
src/Sylius/Bundle/CoreBundle/Form/Type/Shipping/ShippingMethodChoiceType.php
src/Sylius/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php
src/Sylius/Bundle/LocaleBundle/spec/Form/Type/LocaleChoiceTypeSpec.php
src/Sylius/Bundle/ResourceBundle/Form/Type/ResourceChoiceType.php
src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodChoiceType.php
src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonChoiceType.php
src/Sylius/Bundle/UserBundle/Form/Type/UserType.php

Remove old closures compatibility code

---

features/backend/product_archetypes.feature
src/Sylius/Bundle/ArchetypeBundle/Form/EventListener/ParentArchetypeListener.php
src/Sylius/Bundle/ArchetypeBundle/Form/Type/ArchetypeType.php
src/Sylius/Bundle/ArchetypeBundle/spec/Form/EventListener/ParentArchetypeListenerSpec.php
src/Sylius/Bundle/ArchetypeBundle/spec/Form/Type/ArchetypeTypeSpec.php

[Archetype] Parent archetype choices list should not contain current archetype

---

src/Sylius/Bundle/InstallerBundle/Command/AbstractInstallCommand.php
src/Sylius/Bundle/InstallerBundle/Command/InstallCommand.php

It uses previously implemented service to check ``app/cache`` permissions - unwritable cache caused fatal error.

[Installer] Check cache permissions to avoid exception

---

src/Sylius/Bundle/ReportBundle/Resources/translations/messages.en.yml

Hi,
Remove wrong translation from report bundle.
It's promotion bundle ones, but they already exists in this bundle.
So I remove them.

[ReportBundle] Remove wrong translation

---

src/Sylius/Bundle/CoreBundle/Controller/CheckoutController.php

[Core] Uncomment CheckoutController adressingAction for empty order

---

src/Sylius/Component/Core/spec/Promotion/Checker/ContainsProductRuleCheckerSpec.php

| Fixed tickets | []
| Doc PR        | [missing Specs for RuleChecker]

[Core] Add missing spec for ContainsProductRuleChecker

---

app/migrations/Version20151024153713.php
src/Sylius/Bundle/UserBundle/Resources/config/doctrine/model/Customer.orm.xml

Import a million users to your database and you'll really need this index...
user.username and usernameCanonical seem to be nullable? so I haven't added any to this, although customer.email will be where db queries are mainly run against anyway.

[User] Added missing unique indexes on customer.email and emailCanonical

---

src/Sylius/Bundle/CoreBundle/Context/ChannelContext.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml

The app was crashing if there were Sylius bundles loaded whereas there was no channel in the database. Made `ChannelContext`-related computations lazy-loaded.

Made ChannelContext-related computations lazy-loaded

---

src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php

I know that the ResourceBundle refactor is going to add this, but it's killing us at the moment with a 60 second page load and with no ETA on that refactor this is a quick fix.

[Resource] Fix DoctrineORMPaginator instantiation to set OutputWalker to false 

---

src/Sylius/Bundle/ApiBundle/Resources/config/routing/adjustment.yml
src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.Order.yml
src/Sylius/Bundle/OrderBundle/Controller/AdjustmentController.php
src/Sylius/Component/Order/Model/Adjustment.php

Configure adjustments api and permissions

---

src/Sylius/Bundle/UserBundle/Security/UserPasswordEncoder.php
src/Sylius/Bundle/UserBundle/spec/Security/UserPasswordEncoderSpec.php
src/Sylius/Component/User/Model/CredentialingInterface.php
src/Sylius/Component/User/Model/CredentialsHolderInterface.php
src/Sylius/Component/User/Model/UserInterface.php
src/Sylius/Component/User/Security/PasswordUpdater.php
src/Sylius/Component/User/Security/PasswordUpdaterInterface.php
src/Sylius/Component/User/Security/UserPasswordEncoderInterface.php
src/Sylius/Component/User/Security/UserPbkdf2PasswordEncoder.php
src/Sylius/Component/User/spec/Security/PasswordUpdaterSpec.php
src/Sylius/Component/User/spec/Security/UserPbkdf2PasswordEncoderSpec.php

Introduced `CredentialingInterface` which implementation needs to be passed to password encoders and updaters instead of `UserInterface` with methods like `setCustomer()` etc.

[User] Decoupled password encoders and updaters from UserInterface

---

src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Country.orm.xml
src/Sylius/Component/Addressing/Model/Country.php

Provinces for a country ordered by name by default
Ensure __toString() won't break on Country. I may have an old DB, but some countries in my db couldn't retrieve a translation so blew up when used in a country dropdown.

[Addressing] Country fixes

---

src/Sylius/Bundle/UserBundle/Form/Type/CustomerProfileType.php
src/Sylius/Bundle/UserBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/UserBundle/spec/Form/Type/CustomerProfileTypeSpec.php

From:
To:
NOTE: There's an underlying theme bug here which doesn't render 'default' labels properly. Ideally you shouldn't have to do this to make your widget render the same as every other, but it's still worth merging to make it consistent.
I will open a separate issue for this one, but don't have time to fix it right now.

[UserBundle] Fix customer gender layout on backend admin form

---

src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/WebBundle/Resources/translations/messages.lt.yml
src/Sylius/Bundle/WebBundle/Resources/translations/messages.sk.yml
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/macros.html.twig

Fixes actions undelete button
http://demo.sylius.org/administration/products/?deleted=1
Let me know, if I should rename translation string from `sylius.product.delete_revert` to `sylius.product.delete_restore`.

Fix translation for backend product undelete btn

---

app/config/config_test.yml
app/config/parameters.yml.dist
features/frontend/cart_promotions_dates.feature
features/frontend/cart_promotions_fixed.feature
features/frontend/cart_promotions_percentage.feature
features/frontend/cart_promotions_usage_limit.feature
src/Sylius/Bundle/CoreBundle/EventListener/OrderPromotionListener.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/spec/EventListener/OrderPromotionListenerSpec.php

| Deprecations? | yes, if some was using that flag
| Fixed tickets | [https://github.com/Sylius/Sylius/issues/1810]
According to the https://github.com/Sylius/Sylius/issues/1810 first step to further improve promotion is remove `promotion.item_based` from parameters and OrderPromotionListener.

[Core] Promotion item based flag removal

---

src/Sylius/Bundle/WebBundle/Resources/views/Backend/Promotion/_form.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Common/forms.html.twig

This fixes the layout for checkboxs and radio buttons as part of a compound form widget as per the bootstrap spec: http://getbootstrap.com/css/#forms
Eventually it might be worth looking at the official symfony bootstrap theme (http://symfony.com/blog/new-in-symfony-2-6-bootstrap-form-theme), but for now this fix helps:
Also fixed use on promo form with channels
BEFORE:
AFTER:
Also fine on smaller breakpoints:

Form theming fix for sublabels on expanded compound widgets 

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
src/Sylius/Component/Core/Accessor/ProductAccessor.php
src/Sylius/Component/Core/composer.json
src/Sylius/Component/Product/composer.json

ProductAccessor class is located in the Product component, but it doesn't have any connection to it. Although it uses the ProductInterface it's not the one from Product component, but from Core.

[Product][Core] Moved ProductAccessor from Product to Core

---

src/Sylius/Bundle/ResourceBundle/Form/Type/EntityHiddenType.php

#3406 PR fixed problem with reversed logic of `ObjectToIdentifierTransformer`. But unfortunately we forgot that *EntityHiddenType* use this transformer. I changed the name of method used by *EntityHiddenType* to avoid problems like this:
`Expected argument of type "AppBundle\Entity\ProductVariant", "string" given`

[Resource] EntityHiddenType fix

---

src/Sylius/Bundle/FlowBundle/Process/Context/ProcessContext.php
src/Sylius/Bundle/FlowBundle/Validator/ProcessValidator.php
src/Sylius/Bundle/FlowBundle/Validator/ProcessValidatorInterface.php
src/Sylius/Bundle/FlowBundle/spec/Process/Context/ProcessContextSpec.php
src/Sylius/Bundle/FlowBundle/spec/Validator/ProcessValidatorSpec.php

This can be useful when you want to implement some advanced process validation that need to be aware of the some process context data, such as current step.

[Flow] Allow ProcessValidator to access ProcessContext

---

composer.json
composer.lock
src/Sylius/Bundle/InstallerBundle/Requirement/ExtensionsRequirements.php
src/Sylius/Bundle/InstallerBundle/Resources/translations/requirements.en.yml

Some extensions (so far I've discoverd: `exif`, `fileinfo`, `gd`, `intl`) are necessary for tests to run, so they should be listed in the `require-dev` part of the `composer.json`
They gave me hard time during #3501 because every build takes a few minutes because of the Composer dependencies :clock1:

Add required PHP extensions to composer.json

---

src/Sylius/Bundle/SearchBundle/Behat/SearchContext.php

| Fixed tickets | none, related to #3501
`Behat/SearchContext` executes the SearchBundle - `IndexCommand`
When the code was ran on Windows, the app/console did not exists:
`'app/console' is not recognized as an internal or external command...`
This change makes the code portable, so it runs on Linux and Windows

[SearchBundle] Behat/SearchContext is portable

---

appveyor.yml
travis/appveyor/parameters.test.yml
travis/appveyor/suite-1a.cmd
travis/appveyor/suite-1b.cmd
travis/appveyor/suite-2a.cmd
travis/appveyor/suite-2b.cmd
travis/appveyor/suite-phpspec.cmd

This PR adds a config file for AppVeyor which is a CI similar to travis, except they run the builds on Windows machines. Therefore any possible incompatibilites can be easily discovered (ref #2604)
~~**It is still very WIP, I just want to:
1) prevent possibly duplicate work, if someone starts working on the same thing
2) get feedback as early as possible**~~
You can see the build output here https://ci.appveyor.com/project/mhujer/sylius
To integrate it with this project, it is necessary to login to https://ci.appveyor.com/ using github account and enable the build for this repo.
(Symfony has …

CI AppVeyor

---

CHANGELOG.md
app/migrations/Version20151019160305.php
src/Sylius/Bundle/CoreBundle/OrderProcessing/TaxationProcessor.php
src/Sylius/Bundle/OrderBundle/Form/Type/AdjustmentType.php
src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Adjustment.orm.xml
src/Sylius/Bundle/OrderBundle/Resources/config/validation.xml
src/Sylius/Bundle/OrderBundle/spec/Form/Type/AdjustmentTypeSpec.php
src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/adjustments.html.twig
src/Sylius/Component/Core/OrderProcessing/PaymentChargesProcessor.php
src/Sylius/Component/Core/OrderProcessing/ShippingChargesProcessor.php
src/Sylius/Component/Core/Promotion/Action/DiscountAction.php
src/Sylius/Component/Core/spec/Model/OrderSpec.php
src/Sylius/Component/Core/spec/OrderProcessing/PaymentChargesProcessorSpec.php
src/Sylius/Component/Core/spec/OrderProcessing/ShippingChargesProcessorSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/FixedDiscountActionSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/PercentageDiscountActionSpec.php
src/Sylius/Component/Order/Model/Adjustment.php
src/Sylius/Component/Order/Model/AdjustmentInterface.php
src/Sylius/Component/Order/Model/Order.php
src/Sylius/Component/Order/Model/OrderItem.php
src/Sylius/Component/Order/spec/Model/AdjustmentSpec.php

| BC breaks?    | [yes]
| Deprecations? | [yes, if someone was extending adjustments]
| Doc PR        | [https://github.com/Sylius/Sylius-Docs/pull/356]
This 'label' field is using type of adjustments specified in 'Sylius\Component\Core\Model\AdjustmentInterface', so I've renamed it to the type.

[Order,Core,Web] Rename of label on adjustment to type

---

README.md

Related to #3501, please merge it after the first AppVeyor build finishes
cc @pjedrzejewski

AppVeyor CI - build status badge

---

.travis.yml
composer.json
composer.lock
src/Sylius/Bundle/ApiBundle/spec/Command/CreateClientCommandSpec.php
src/Sylius/Bundle/CurrencyBundle/spec/Command/ImportExchangeRateCommandSpec.php
src/Sylius/Bundle/CurrencyBundle/spec/Command/UpdateExchangeRateCommandSpec.php
travis/prepare/prepare-phpspec-php7

PhpSpec does not need typehints transformer no more.
Updated `composer.lock`, fixed specifications due to Symfony's `Command` class changes.

Updated PhpSpec to 2.4@alpha, native PHP7 support

---

app/migrations/Version20151110183626.php
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Product.orm.xml

[CoreBundle] Set proper cascade behaviour on one-to-many product references

---

src/Sylius/Bundle/FixturesBundle/DataFixtures/DataFixture.php
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadLocalesData.php

I have discussed this problem with @pjedrzejewski and for now, I have reverted changes from #3531.
In future, we should consider a better solution for loading fakers locales in fixtures.

[FixturesBundle] Reverted loading fakers with the available locales

---

src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php

A POST, PUT or PATCH request like this:
```
{
"country_code": "FR",
"first_name": "First name",
"last_name": "Last name",
"slug": "my-slug"
}
```
throws a 404 response because the slug became a default search criteria.

[ResourceBundle] Search id or slug in request query strings

---

src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPaymentMethodsData.php

This line was removed in PR associated with upgrading Payum (#3380). I am not sure what the idea was, but this payment method is used in loaded by fixtures channels.

[FixturesBundle] Fixed problem with not existing payment method

---

src/Sylius/Bundle/WebBundle/Resources/views/Common/forms.html.twig

| Fixed tickets | 3512
Affects label placement on large resolutions.
Use the correct check for whether a label is not being used as per the default form_label block rather than checking only for a user-entered label.
Fixes #3512 
BEFORE:
AFTER:

[WebBundle] Form theming fix for when no label is explicitly specified 

---

src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDatabaseDriver.php

Actually this is more of a workaround.
I ran into the issue while trying to make the `Order` entity translatable, but it actually applies to any sylius bundle exposing semantic configuration that contains untranslated resources.
The database driver adds method calls to `setLocaleProvider` and `setTranslatableFields` to any repository implementing `TranslatableResourceRepositoryInterface`.
However, a lot of sylius bundles include resources that are not initially translated.
For instance, `Order` comes from the `OrderBundle` and no `translation` can be added to the bundle config in `sylius.yml`. As a …

[Resource] Bundle resources can not be translated if they were not intended to

---

src/Sylius/Bundle/PayumBundle/Action/ConvertPaymentToPaypalExpressAction.php

[PayumBundle] Added payment total to Paypal Express Checkout request

---

src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Cart/_item.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Cart/summary.html.twig

| Bug fix?      | [yes, possibly]
We were using cart.item's values rather than values that were available in the form itself. Strange looking loop.index0 in loop has been removed. I found this one while trying to add 'recalculate' on summary page. Error was:
```Key "1" in object with ArrayAccess of class "Symfony\Component\Form\FormView" does not exist in SyliusWebBundle:Frontend/Cart:_item.html.twig at line 8```
because cart items are not reindexed while recalculating.

WebBundle: using form variables that are available, not extra params

---

src/Sylius/Bundle/SearchBundle/Indexer/OrmIndexer.php

| Q | A |
|-----|-----|
| Deprecations? | no |
| Fixed tickets |	none, related to #2305 |
| Doc PR | none |
Prevent indexer from throwing the "Attempted to call an undefined method named "get0" of class ..." error when extending classes. This behaviour also truncates entire search index table in the database.

[SearchBundle] OrmIndexer minor patch

---

src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.ProductVariant.yml
src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.ProductVariantImage.yml
src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.Taxon.yml
src/Sylius/Bundle/TaxonomyBundle/Resources/config/serializer/Model.Taxon.yml

Fixed wrong serialization config and expose image paths in the config. Useful when you need to get the images via API. :)

Tweak serialization configs for all image aware resources

---

src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/User.orm.xml

I was getting:
```
MappingException: Property "oauthAccounts" in "Sylius\Component\Core\Model\User" was already declared, but it must be declared only once
```
Does not belong to this model, already defined in [User.orm.xml#L55](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/Resources/config/doctrine/model/User.orm.xml#L55).

Removed oauthAccounts since it is already defined in user bundle

---

.travis.yml
composer.json
travis/prepare/mongodb/1-before
travis/prepare/mongodb/2-rebuild-cache
travis/prepare/prepare-cached-composer

- Travis now does not implicitly run `cache:clear` / `assets:install`  while installing packages by Composer
- Fixed composer.lock caching (while requiring `doctrine/mongodb-odm`)
- Removed `~/.composer` from Travis cache
Doing these things makes that every build, that does not change `composer.json` or `composer.lock`, will not have to upload new cache archive, which usually takes about 40-60s. Moreover, cache archives will be smaller so we will save another second or two here.

[Travis] Composer-related performance optimzations

---

src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
src/Sylius/Bundle/CoreBundle/Behat/HookContext.php
src/Sylius/Bundle/ResourceBundle/Behat/DefaultContext.php

- Longer timeouts for accessing database (half of fails, timeout was set to 1s, increased to 3s)
- Shorter timeouts for loading page by Selenium (another half of fails, timeout was set to 10min [equal to Travis no-output timeout :/], decreased to 30s)
I hope the second change will give us insight about the issue and help to fix it.

[Behat] [Travis] Investigating failing JS builds

---

features/security/permission_management.feature
features/security/role_management.feature
travis/suites/suite-javascript
travis/suites/suite-no-javascript

- Added `security` suite, which was missing
- Updated `security` scenarios (new table matching)
- Ordered Behat suites in `travis/suites/*` alphabetically

[Behat] Missing security suite added, ordered alphabetically

---

composer.json
composer.lock

Doing so, packages dependent on `sylius/sylius` can use `"minimal-stability": "rc"` instead of `"minimal-stability": "alpha"`.

[Composer] Updated phpspec requirement from 2.4@alpha to 2.4@rc

---

src/Sylius/Bundle/FlowBundle/Process/Process.php

At the moment Process.php throws ```\InvalidArgumentException``` however the code which uses this class (```Sylius\Bundle\FlowBundle\Controller\ProcessController```) catches ```Sylius\Bundle\FlowBundle\Process\Coordinator\InvalidArgumentException``` instead resulting in 5xx error where 404 is expected

Throwing correct exception if step is unknown

---

src/Sylius/Component/Product/spec/Builder/ProductBuilderSpec.php

Doubled definition in `it_creates_attribute_if_it_does_not_exist` removed.
Also ordered the parameters in the same way as they are in `let` :)

[Product] Fixed ProductBuilderSpec on PHP7

---

.travis.yml
travis/prepare/opcache.ini

This should prevent `zend_mm_heap corrupted` errors happening sometimes while running `phpspec` and `composer`.

[Travis] OPCache optimizations

---

.travis.yml
composer.json
composer.lock
src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/LazyCacheWarmupPass.php
src/Sylius/Bundle/CoreBundle/Resources/config/templating.xml
src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
src/Sylius/Bundle/CurrencyBundle/Resources/config/templating.xml
src/Sylius/Bundle/MoneyBundle/Resources/config/templating.xml
travis/prepare/prepare-javascript
travis/suites/suite-default
travis/suites/suite-javascript
travis/suites/suite-no-javascript

[Travis] Javascript suites on every PHP version, lazy cache:warmup

---

composer.json
composer.lock
src/Sylius/Component/Product/composer.json
src/Sylius/Component/User/composer.json

| Fixed tickets | #3590
This replaces #3591.
- `iconv` is used in `Sylius\Component\Product\Sluggable\ProductTranslationSlugEventListener`,
- `mbstring` is used in i.e.: `Sylius\Component\User\Canonicalizer\Canonicalizer`

Add usage of Symfony Polyfill components

---

src/Sylius/Bundle/CartBundle/Provider/CartProvider.php
src/Sylius/Bundle/CartBundle/Resources/config/services.xml
src/Sylius/Bundle/CartBundle/spec/Provider/CartProviderSpec.php
src/Sylius/Bundle/CoreBundle/EventListener/OrderCurrencyListener.php
src/Sylius/Bundle/CoreBundle/spec/EventListener/OrderCurrencyListenerSpec.php

Services should be stateless. CartProvider holding cart was just premature optimisation and just wrong.

Stateless cart provider

---

src/Sylius/Bundle/CartBundle/spec/Provider/CartProviderSpec.php

Build was failing on PHP7 due to doubled `$cart` in methods definitions.
Fixed formatting, renamed `$context` to `$cartContext`, changed order in specification methods to be the same as in `let`.

[Cart] Fixed and polished CartProviderSpec on PHP7

---

src/Sylius/Bundle/TranslationBundle/GedmoHandler/TranslationSlugHandler.php

[Translation] Fixed how TranslationSlugHandler works, if slug is set on mapped superclass

---

.travis.yml
composer.json
composer.lock

It looks like Symfony 2.8 does not include `symfony/proxy-manager-bridge` and changes made in #3643 related to lazy `cache:warmup` aren't working in that case.
Also moved `cache:warmup` above creating schema in Travis, to ensure that cache warming up does not require database schema.

[Composer] Added explicit dependency symfony/proxy-manager-bridge

---

src/Sylius/Bundle/WebBundle/Resources/views/Frontend/StaticContent/show.html.twig

No BC breaks, bug fixed. Variable named `cmfMainContent` did not exist in that template.

[WebBundle] Fixed showing static content by route sylius_static_content_show

---

composer.lock
travis/prepare/prepare-javascript

Prevents failing on the first scenarios, while Selenium2 is unavailable (added waiting for Chromedriver's port 9515).
.

[Travis] Improved waiting for port while executing JS scenarios

---

src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php

Fixes the situation in which the domain manager returns an event because the propagation was stopped.
Closes #3676

Update action refreshes the resource when updated

---

src/Sylius/Bundle/UserBundle/Resources/views/User/resetPassword.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/User/resetPassword.html.twig

The reset password page was referring to 'newPassword' which was never defined anywhere.
This should probably be tested, but I am not very familiar with Behat / BDD yet. Perhaps if I get some time tonight I'll try taking a stab at it.

Fix password reset forms

---

src/Sylius/Bundle/FlowBundle/Process/Builder/ProcessBuilderInterface.php

The ProcessBuilder:validate implementation supports ProcessValidatorInterface instances to be passed, but the PHPDoc @param declaration in it's interface said otherwise.

Updated PHPDoc to allow ProcessValidatorInterface instances to be passed

---

src/Sylius/Bundle/FlowBundle/Process/Coordinator/Coordinator.php

ProcessValidators return ActionResult instances by default, which needs to be transformed to regular responses by the Coordinator.

Responses generated by ProcessValidators now get processed.

---

features/backend/shipping_categories.feature
features/backend/shipping_methods.feature
features/currencies/currency_management.feature
src/Sylius/Bundle/CurrencyBundle/Form/Type/CurrencyType.php
src/Sylius/Bundle/CurrencyBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/CurrencyBundle/spec/Form/Type/CurrencyTypeSpec.php
src/Sylius/Bundle/ResourceBundle/Form/EventSubscriber/AddCodeFormSubscriber.php
src/Sylius/Bundle/ResourceBundle/spec/Form/EventSubscriber/AddCodeFormSubscriberSpec.php
src/Sylius/Bundle/WebBundle/Behat/WebContext.php
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Currency/macros.html.twig
src/Sylius/Component/Currency/Model/CurrencyInterface.php

[Currency] Introduce immutable code for Currency

---

app/migrations/Version20151209104639.php
features/backend/payment_methods.feature
features/backend/shipping_methods.feature
features/channels/channel_management.feature
features/frontend/checkout_finalize.feature
features/frontend/checkout_inventory.feature
features/frontend/checkout_payment.feature
features/frontend/checkout_security.feature
features/frontend/checkout_shipping.feature
features/frontend/checkout_taxation.feature
src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPaymentMethodsData.php
src/Sylius/Bundle/PaymentBundle/Behat/PaymentContext.php
src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentMethodType.php
src/Sylius/Bundle/PaymentBundle/Resources/config/doctrine/model/PaymentMethod.orm.xml
src/Sylius/Bundle/PaymentBundle/Resources/config/serializer/Model.PaymentMethod.yml
src/Sylius/Bundle/PaymentBundle/Resources/config/validation.xml
src/Sylius/Bundle/PaymentBundle/Resources/translations/validators.en.yml
src/Sylius/Bundle/PaymentBundle/spec/Form/Type/PaymentMethodTypeSpec.php
src/Sylius/Bundle/WebBundle/Resources/views/Backend/PaymentMethod/_form.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/PaymentMethod/macros.html.twig
src/Sylius/Component/Payment/Model/PaymentMethod.php
src/Sylius/Component/Payment/Model/PaymentMethodInterface.php
src/Sylius/Component/Payment/spec/Model/PaymentMethodSpec.php

| Fixed tickets |  #3639,  #3617

[Payment][PaymentBundle] Add immutable code to Payment entities

---

src/Sylius/Bundle/CoreBundle/Form/Type/CartType.php

| Fixed tickets | ~
Allows to use form extension to modify 'sylius_cart' if promotion coupons are removed from the form itself. It is throwing 'A new entity was found through the relationship' because we are having detached entity from form.

CoreBundle: checker for promotion coupons added

---

app/migrations/Version20151129155421.php
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/InventoryUnit.orm.xml
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Order.orm.xml
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/OrderItem.orm.xml
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Payment.orm.xml
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Shipment.orm.xml
src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Adjustment.orm.xml
src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/OrderItem.orm.xml

Setup onDelete=CASCADE foreign keys for Order and OrderItem relations so that orders can be deleted directly in the DB along with their relevant relations:
* Order => OrderItem
* Order => Payment
* Order => Shipment
* Order => InventoryUnit
* Order => Adjustment
* Order => OrderPromotion (m2m)
* OrderItem => OrderItemPromotion (m2m)
* OrderItem => InventoryUnit
* OrderItem => Adjustment

[DB] Allow orders to be deleted directly through DB with correct onDelete=CASCADEs

---

src/Sylius/Bundle/FlowBundle/README.md

Former name (ContainerAwareStep) was still used in SyliusFlowBundle README.md.

[Flow] Use AbstractContainerAwareStep in README.md

---

src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/ShipmentType.php

I used to get:
```
The option "channel" does not exist. Known options are: "action", "attr", "auto_initialize", "block_name", "by_reference", "cascade_validation", "choice_list", "choices", "compound", "constraints", "criteria", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_provider", "data", "data_class", "delete_button_render", "disabled", "empty_data", "empty_value", "error_bubbling", "error_mapping", "expanded", "extra_fields_message", "inherit_data", "intention", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_render", "mapped", "max_length", "method", "multiple", "pattern", …
```

ShippingMethodChoiceType is not channel aware

---

src/Sylius/Bundle/SettingsBundle/Manager/SettingsManager.php
src/Sylius/Bundle/SettingsBundle/Templating/Helper/SettingsHelper.php
src/Sylius/Bundle/SettingsBundle/Twig/SettingsExtension.php

Q  | A
License | MIT
Doc PR | -
There are a lot of times and loading a settings schema fails because we had a previous deprecated value in the database which we didn't want anymore and since it's not easy to create migrations for settings schema's I thought maybe it's safe to ignore missing options **ONLY** when loading from database.

[Settings] Missing parameters issues in twig templates and settings loading

---

behat.yml.dist

Introduced by #3711, causes errors while handling errors :)
Failed builds looks like: https://travis-ci.org/Sylius/Sylius/jobs/96761126

[Behat] Renamed build path

---

src/Sylius/Bundle/CoreBundle/Checkout/Step/SecurityStep.php
src/Sylius/Bundle/CoreBundle/EventListener/CartBlamerListener.php
src/Sylius/Bundle/CoreBundle/spec/EventListener/CartBlamerListenerSpec.php
src/Sylius/Bundle/UserBundle/EventListener/UserLastLoginSubscriber.php
src/Sylius/Bundle/UserBundle/spec/EventListener/UserLastLoginSubscriberSpec.php

If you only flush a single resource it's possible that you can lose other important entity flushes - especially as Sylius uses Sequences called on preFlush.
We just had an issue where a Customer Sequence was not being flushed in checkout because only the single Customer resource was being flushed. The sequence therefore didn't change and it was impossible to register because the sequence had not incremented and the value was not unique next time around...
Unless there's a really particular reason not to flush everything, I think we always should.

Avoid flushing only a single resource when not required

---

src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/DocumentRepository.php

Fix bug where you could not select phpcr documents with criteria "name" (it would throw: `Cannot use nodename property "name" of class "Xyz" as a dynamic operand use "localname()"` instead.)

[BugFix][PHPCR] Fix criteria "name" for DocumentRepository

---

src/Sylius/Bundle/WebBundle/Resources/views/Frontend/StaticContent/show.html.twig

As @psyray noticed in #3664, we have two endpoints that can show static content. In that PR I wasn't aware of `ContentController` and it resulted in BC change, this one reverts it and adds compatibility layer. Possibly related to #3672.

[CMF Integration] StaticContent/show template can be used with both ContentController and ResourceController

---

src/Sylius/Bundle/WebBundle/Menu/BackendMenuBuilder.php

User see emails menu item in back-end even if he hasn't permission (sylius.manage.email) for it. This happens due to wrong isGranted parameter in BackendMenuBuilder.

[Permissions] Fixed permission for emails back-end menu item

---

CHANGELOG.md
web/app_dev.php

A few people have asked for this (although I can find any open issues to reference), a way of using sylius on Vagrant without having to comment out half of app_dev.php.

Permit access to app_dev.php through system environment variable 

---

src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadZonesData.php

Fix for fixtures to prevent US being added to Rest of World zone as intended.
Currently you can't calculate Tax for the US with demo data because US addresses resolve to RoW

Zone Fixtures - Fix US being added to Rest of World zone

---

src/Sylius/Bundle/FlowBundle/Process/Step/AbstractContainerAwareStep.php

| Deprecations? | [yes]
| Fixed tickets | [#3698]
| Doc PR        | [n/a]
What bothers me is that even if I remove "implements ContainerAwareInterface" from Sylius\Bundle\FlowBundle\Process\Step\AbstractContainerAwareStep phpspec still tells me everything is fine.
Is this the expected behaviour?

using ContainerAwareTrait

---

src/Sylius/Bundle/ResourceBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php

I am not using translations in my application, and an error is thrown here as I've not configured translations for my resources.
This was introduced by https://github.com/Sylius/Sylius/pull/3721.
Also, it seems it is not not possible to disable translations per resource, see [here](https://github.com/Sylius/Sylius/pull/3721/files#r48045552).

[ResourceBundle] check translations are possible before configuration them

---

src/Sylius/Bundle/WebBundle/Resources/translations/menu.en.yml

There's another issue here of double-translations because translate() is called in the MenuBuilder (for separation of messages into menu domain) and also when it's rendered, so you get a lot of translation errors on the backend.
I might look at this again soon but here's the missing messages to start with.

Missing menu translations and alphabetized

---

src/Sylius/Bundle/ResourceBundle/AbstractResourceBundle.php
src/Sylius/Bundle/ResourceBundle/Form/Type/ResourceChoiceType.php
src/Sylius/Bundle/ResourceBundle/spec/Form/Type/ResourceChoiceTypeSpec.php

Added a test to prevent regression for `ResourceChoiceType`.
`AbstractResourceBundle` isn't covered by a test so no test added there.

fix incorrect import

---

src/Sylius/Component/Taxonomy/Model/Taxon.php

Q  | A
License | MIT
Doc PR | -
We an issue with our version of Monolog I suppose.

[Taxonomy] Cast Taxon::__toString() to string to prevent Monolog exception

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ShipmentRepository.php

It could be specific to our app that shipments are created before addresses sometimes, but there's no point in this query being a left-join anyway since the `Backend/Shipment/macros.html.twig` file requires an address (and an order) for displaying shipments:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Backend/Shipment/macros.html.twig#L33

[Shipment] Fix join on ShipmentRepository for Shipment Admin page

---

app/migrations/Version20151228175507.php
features/backend/product_variants.feature
src/Sylius/Bundle/CoreBundle/Controller/ProductController.php
src/Sylius/Bundle/CoreBundle/Form/Type/ProductVariantType.php
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
src/Sylius/Bundle/CoreBundle/Resources/config/validation.xml
src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
src/Sylius/Bundle/WebBundle/Resources/public/css/backend.css
src/Sylius/Bundle/WebBundle/Resources/public/css/frontend.css
src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/Form/_main.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/macros.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/show.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductVariant/_form.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductVariant/macros.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Product/_singleBox.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Product/macros.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Product/show.html.twig
src/Sylius/Component/Core/Model/ProductVariant.php
src/Sylius/Component/Core/Model/ProductVariantInterface.php
src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php
src/Sylius/Component/Pricing/Model/PriceableInterface.php

Continuation of PR <a href="https://github.com/Sylius/Sylius/pull/3373">#3373</a>

[Product] added original price

---

app/migrations/Version20151228175507.php

It seems that doctrine migration classname was generated incorrectly in #3783

[Product] Fix invalid migration classname

---

src/Sylius/Bundle/TaxonomyBundle/Behat/TaxonomyContext.php
src/Sylius/Bundle/TaxonomyBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/TaxonomyBundle/DependencyInjection/SyliusTaxonomyExtension.php
src/Sylius/Bundle/TaxonomyBundle/SyliusTaxonomyBundle.php
src/Sylius/Component/Core/Model/Taxonomy.php
src/Sylius/Component/Core/spec/Model/TaxonomySpec.php
src/Sylius/Component/Taxonomy/Factory/TaxonomyFactory.php
src/Sylius/Component/Taxonomy/Model/Taxonomy.php
src/Sylius/Component/Taxonomy/spec/Factory/TaxonomyFactorySpec.php

| Fixed tickets | #2884 #2557 
While using component independently, if we wanted to use ``$taxonomy = new Taxonomy()`` we would get an error, because we are not setting the root taxon while creating a new Taxonomy. Therefore I suppose we need a constructor.

[Taxonomy] [RFC] Constructor for the Taxonomy model

---

app/migrations/Version20151221084137.php
src/Sylius/Bundle/ProductBundle/Form/Type/VariantType.php
src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/Product.orm.xml
src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/Variant.orm.xml
src/Sylius/Bundle/ProductBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/Form/_main.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/show.html.twig
src/Sylius/Component/Product/Model/DateRange.php
src/Sylius/Component/Product/Model/Product.php
src/Sylius/Component/Product/Model/ProductInterface.php
src/Sylius/Component/Product/Model/Variant.php
src/Sylius/Component/Product/Model/VariantInterface.php
src/Sylius/Component/Product/spec/Model/DateRangeSpec.php

Sometimes except availableOn product parameter we need also availableTo one. This is especially usefull when You selling something like concert or training tickets which events take place at particular day and it is useless to selling them after that day. When You leave this parameter blank nothing new happens but when You set a date, Sylius will validate it with availableOn in isAvailable method.
This is my first bigger commit to Sylius so any tips how to improve my code are highly appreciated. Hope it will be usefull for community.

[Product] added availableTo parameter

---

features/reports/reports.feature
src/Sylius/Bundle/CoreBundle/Form/Type/DataFetcher/UserRegistrationType.php

| Fixed tickets | https://github.com/Sylius/Sylius/issues/3800
To prevent this issue occurrence after every year change (:smile:), I've set default date on ``UserRegistrationDataFetcher`` to "now" and given possibility to choose year even 100 years before current date.
Improvement:
- it would be good to change date selecting steps in scenarios, as ``And I select "2010" from "sylius_report_dataFetcherConfiguration_start_year"`` is really not easy to read :)

[Report] Fixed year-change issue with reports

---

src/Sylius/Bundle/ApiBundle/Resources/config/routing/customer.yml
src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml

| Bug fix?      | [yes]
| Fixed tickets |  
`sylius_api_customer_show` route doesn't exist, should we create it or just use `sylius_api_user_show`?

[API] Add customer show api path

---

app/migrations/Version20160104133517.php
features/backend/products.feature
src/Sylius/Bundle/ProductBundle/Behat/ProductContext.php
src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/Product.orm.xml
src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/product.yml
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/show.html.twig
src/Sylius/Component/Product/Model/Product.php
src/Sylius/Component/Product/Model/ProductInterface.php
src/Sylius/Component/Product/spec/Model/ProductSpec.php

[Product] Implement Toggleable interface on Product

---

src/Sylius/Bundle/CartBundle/Resources/config/templating.xml
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/Resources/config/templating.xml
src/Sylius/Bundle/RbacBundle/Resources/config/templating.xml
src/Sylius/Bundle/SettingsBundle/Resources/config/services.xml
src/Sylius/Bundle/UserBundle/Resources/config/services.xml

This is so bad and annoying. It is obviously a workaround for now, but I marked some services as lazy so that it does not connect to the db during cache warmup.

Mark some services as lazy to prevent db connection

---

src/Sylius/Bundle/RbacBundle/Form/EventSubscriber/AddParentFormSubscriber.php
src/Sylius/Bundle/RbacBundle/Form/Type/PermissionType.php
src/Sylius/Bundle/RbacBundle/Form/Type/RoleType.php
src/Sylius/Bundle/RbacBundle/spec/Form/EventSubscriber/AddParentFormSubscriberSpec.php
src/Sylius/Bundle/RbacBundle/spec/Form/Type/PermissionTypeSpec.php
src/Sylius/Bundle/RbacBundle/spec/Form/Type/RoleTypeSpec.php
src/Sylius/Component/Rbac/Model/Permission.php
src/Sylius/Component/Rbac/Model/PermissionInterface.php
src/Sylius/Component/Rbac/Model/Role.php
src/Sylius/Component/Rbac/Model/RoleInterface.php

Q 	|A
-------|-------
Bug fix?| 	no
New feature?| 	yes
BC breaks?| 	no
Deprecations?| 	no
Fixed tickets| 	-
License| 	MIT
Doc PR| 	-

[Rbac][RbacBundle] Introduce code for Rbac

---

src/Sylius/Component/Archetype/Builder/ArchetypeBuilder.php
src/Sylius/Component/Archetype/spec/Builder/ArchetypeBuilderSpec.php
src/Sylius/Component/Attribute/Model/AttributeSubjectInterface.php
src/Sylius/Component/Product/Model/Product.php

`name` is now translated so this no longer makes sense

[Attribute] Update *AttributeByName => *AttributeByCode inline with updated model

---

src/Sylius/Bundle/CartBundle/Controller/CartController.php
src/Sylius/Bundle/CartBundle/Controller/CartItemController.php
src/Sylius/Component/Cart/Event/CartEvent.php

| Bug fix?      |no
| Deprecations? | yes
| Fixed tickets | #3820
In older versions of Sylius the cart totals were recalculated (aka the cart was "refreshed") via setting the CartEvent to fresh and checking if it is fresh on the right places. If the event was fresh, the cart was recalculated. Now that is solved via triggering the SyliusCartEvents::CART_CHANGE event. The isFresh() method is removed (it was only set, resulting in a more convoluted code, but never checked for after the switch to event listeners).

[Cart] remove deprecated isFresh() method from CartEvent

---

features/backend/products.feature
src/Sylius/Bundle/AttributeBundle/Form/EventSubscriber/BuildAttributeValueFormSubscriber.php
src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeValueType.php
src/Sylius/Bundle/AttributeBundle/Resources/public/js/sylius-attribute.js
src/Sylius/Bundle/AttributeBundle/Resources/views/attributeValueForms.html.twig
src/Sylius/Bundle/AttributeBundle/spec/Form/EventSubscriber/BuildAttributeValueFormSubscriberSpec.php
src/Sylius/Bundle/AttributeBundle/spec/Form/Type/AttributeValueTypeSpec.php
src/Sylius/Bundle/ProductBundle/Form/Type/ProductType.php
src/Sylius/Bundle/ResourceBundle/Behat/WebContext.php
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/Form/_attributes.html.twig

| Fixed tickets | https://github.com/Sylius/Sylius/issues/3798

[AttributeBundle] Fix bug with the attribute value form subscriber

---

app/config/config.yml
app/config/config_test.yml
src/Sylius/Bundle/CoreBundle/Controller/VerboseExceptionController.php
src/Sylius/Bundle/CoreBundle/Resources/config/twig.xml

Reverted #3827, as we don't use default Twig's exception handler but the FOSRestBundle one.

[Travis] [Core] Improved showing exceptions in test environment

---

.travis.yml

It allows us to define `GITHUB_OAUTH_TOKEN` secret variable in Travis CI so we shouldn't get as many "Could not authenticate against github.com" error messages as before.
To use this feature:
- merge this changes to your all branches on Sylius fork (unpatched `php -i` can cause the leak)
- go to `https://travis-ci.org/<your user name>/Sylius/settings`
- create environment variable with name `GITHUB_OAUTH_TOKEN` and your OAuth token as value
- be sure to have "Display value in build log" option **disabled**
It only works for branches builds, does not run on PRs for security reasons, but it should be enough, as PRs cache uses `master` branch cache first, with all the dependencies already downloaded.

[Travis] Ability to add Github OAuth token to Composer configuration

---

src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/Promotion.orm.xml

When updating promotions through the API, it leaves orphans in the database. Right now it only disconnects the relationship, but when you leave out an action, you want it to be gone completely. With this PR they are correctly removed when they are disconnected from their promotion.

[Promotions] Orphan removal on actions and rules

---

src/Sylius/Bundle/ArchetypeBundle/Form/EventListener/ParentArchetypeListener.php

The previous implementations overrode `$parentOptions` defined above with *query_builder* option.

[Archetype] Fix ParentArchetypeListener

---

app/migrations/Version20160112145643.php
src/Sylius/Bundle/CurrencyBundle/Resources/config/doctrine/model/Currency.mongodb.xml
src/Sylius/Bundle/CurrencyBundle/Resources/config/doctrine/model/Currency.orm.xml
src/Sylius/Component/Currency/Model/Currency.php
src/Sylius/Component/Currency/Model/CurrencyInterface.php
src/Sylius/Component/Currency/spec/Model/CurrencySpec.php

Added all methods required to set a Currency as a base one. This PR is connected with #3814, because now during the installation we get only one currency from the user, and we want to set it as the base one.

[Currency] Add isBase flag on CurrencyInterface

---

src/Sylius/Bundle/ContentBundle/DependencyInjection/SyliusContentExtension.php

The issue described in #3897 was introduced in #3721 
I didnt find a better way to fix it so i just put the missing lines back for now.
Here is latest Travis build job for ContentBundle to illustrate the problem: https://travis-ci.org/Sylius/SyliusContentBundle/jobs/102600357
Let me know what you guys think.
P.S.
Maybe it makes sence to tag a patch release after this fix?

[ContentBundle] Imagine block fix

---

src/Sylius/Bundle/FlowBundle/Process/Coordinator/Coordinator.php

In case when one directly navigate to forward step instead of 404 it is being redirected to last valid step. Forward action is now consistent with display action.

[Flow] Go to last valid step if forward not found

---

src/Sylius/Component/Currency/Model/Currency.php
src/Sylius/Component/Currency/spec/Model/CurrencySpec.php

[Currency] Base currency's enabled status and exchange rate should not be editable

---

src/Sylius/Bundle/AttributeBundle/Resources/config/doctrine/model/AttributeValue.orm.xml
src/Sylius/Bundle/AttributeBundle/Resources/views/attributeChoice.html.twig
src/Sylius/Component/Attribute/Model/AttributeValue.php
src/Sylius/Component/Attribute/spec/Model/AttributeValueSpec.php

| Fixed tickets | https://github.com/Sylius/Sylius/issues/3914, https://github.com/Sylius/Sylius/issues/3913
- changed ``dateTime`` field to ``datetime``
- removed weird ``oldhref`` from attribute choice element
- removed broken ``__toString()`` from ``AttributeValue``

[Attribute] Fixed some minor issues with attributes

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml

Without this change you cannot impersonate users, you will get a `403` even though you are an administrator.
I've added the `ROLE_ALLOWED_TO_SWITCH` security role to:
- Administrators
- Account managers
- Support

[Bug Fix] Impersonate user fix, added ROLE_ALLOWED_TO_SWITCH to rbac roles

---

.travis.yml
composer.lock

The current `composer.lock` hash is out out date, so `composer install` shows a warning.
Fix that, and prevent from happening again.

Validate composer

---

src/Sylius/Bundle/CoreBundle/EventListener/CustomerAwareListener.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/spec/EventListener/CustomerAwareListenerSpec.php
src/Sylius/Bundle/UserBundle/composer.json
src/Sylius/Bundle/UserBundle/spec/EventListener/CustomerAwareListenerSpec.php

<code>UserBundle</code> requires <code>Cart</code>, <code>Cart</code> requires <code>Order</code>, so <code>UserBundle</code> is not usable in standalone mode... This PR move the <code>Cart</code> related code to <code>Core</code> to fix that.

[User][Cart][Dependency] Extract Cart dependencies from UserBundle

---

src/Sylius/Bundle/AttributeBundle/Controller/AttributeController.php
src/Sylius/Bundle/AttributeBundle/DependencyInjection/Compiler/RegisterAttributeFactoryPass.php
src/Sylius/Bundle/AttributeBundle/Resources/config/services.xml
src/Sylius/Bundle/AttributeBundle/spec/DependencyInjection/Compiler/RegisterAttributeFactoryPassSpec.php
src/Sylius/Component/Attribute/Factory/AttributeFactory.php

[Attribute] Fix decoupling issues in AttributeBundle

---

src/Sylius/Bundle/CoreBundle/Resources/config/api_form.xml

The service definition for `sylius.form.type.api.order_item` was incorrect.

Order item api form

---

composer.json
composer.lock
src/Sylius/Bundle/CoreBundle/Resources/config/app/cmf.yml

Fixes #3963, Sylius/Sylius-Standard#78
Based on @pamil's symfony-cmf/RoutingBundle#318
Should be ok to merge once stable version of RoutingBundle is tagged.

[Core] Initialize cmf_routing by default

---

UPGRADE.md
app/migrations/Version20160114113257.php
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPromotionsData.php
src/Sylius/Bundle/OrderBundle/Form/Type/AdjustmentType.php
src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Adjustment.orm.xml
src/Sylius/Bundle/OrderBundle/spec/Form/Type/AdjustmentTypeSpec.php
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/_form.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/adjustments.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/show.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Cart/summary.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Checkout/Step/finalize.html.twig
src/Sylius/Component/Core/OrderProcessing/ShippingChargesProcessor.php
src/Sylius/Component/Core/Promotion/Action/DiscountAction.php
src/Sylius/Component/Core/spec/OrderProcessing/ShippingChargesProcessorSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/FixedDiscountActionSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/PercentageDiscountActionSpec.php
src/Sylius/Component/Order/Aggregator/AdjustmentsByLabelAggregator.php
src/Sylius/Component/Order/Factory/AdjustmentFactory.php
src/Sylius/Component/Order/Model/Adjustment.php
src/Sylius/Component/Order/Model/AdjustmentInterface.php
src/Sylius/Component/Order/spec/Aggregator/AdjustmentsByLabelAggregatorSpec.php
src/Sylius/Component/Order/spec/Factory/AdjustmentFactorySpec.php
src/Sylius/Component/Order/spec/Model/AdjustmentSpec.php

| Fixed tickets | https://github.com/Sylius/Sylius/issues/3849
| Doc PR        | https://github.com/Sylius/Sylius-Docs/pull/396

[Order] Change Adjustment description to label

---

src/Sylius/Bundle/AddressingBundle/Form/Type/ProvinceCodeChoiceType.php
src/Sylius/Bundle/AddressingBundle/Resources/config/services.xml
src/Sylius/Bundle/AddressingBundle/Validator/Constraints/ProvinceAddressConstraintValidator.php
src/Sylius/Bundle/AddressingBundle/spec/Validator/Constraints/ProvinceAddressConstraintValidatorSpec.php

- ProvinceAddressConstraintValidator passing object correctly to country->hasProvince instead of string
- ProvinceCodeChoiceType no longer typehints array as this doesn't handle PersistentCollection

[Addressing] Province fixes

---

UPGRADE.md
app/migrations/Version20160118140609.php
behat.yml.dist
features/reports/reports.feature
src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/FinalizeStep.php
src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
src/Sylius/Bundle/CoreBundle/EventListener/OrderCurrencyListener.php
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Order.orm.xml
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/spec/DataFetcher/SalesTotalDataFetcherSpec.php
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadOrdersData.php
src/Sylius/Bundle/ReportBundle/Behat/ReportContext.php
src/Sylius/Bundle/ReportBundle/Controller/ReportController.php
src/Sylius/Component/Core/Currency/ChannelAwareCurrencyProvider.php
src/Sylius/Component/Currency/Provider/CurrencyProvider.php
src/Sylius/Component/Currency/Provider/CurrencyProviderInterface.php

| Fixed tickets | #3715
- Added field exchange_rate to sylius_order in order to save the exchange rate for the time the order was placed
- Updated query for reports in order to count check the exchange rate (o.total * o.exchange_rate)
- Behat for reports feature "Getting the correct sum with exchange rate"
- Table label: if there's a base currency it will show it. For e.g. TOTAL SUM IN GBP
- Created method for getting the channel base currency (getBaseCurrency)
- Behats and PHPSpec updated

Reports correct sum with currencies and label

---

features/frontend/checkout_finalize.feature
features/frontend/checkout_inventory.feature
features/frontend/checkout_security.feature
features/frontend/checkout_shipping.feature
features/frontend/checkout_taxation.feature
src/Sylius/Behat/Context/Setup/PaymentContext.php
src/Sylius/Bundle/CoreBundle/Resources/config/app/payum.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPaymentMethodsData.php

| Fixed tickets | #3685
Replaced `dummy` gateway with `offline` as it always succeed. Probably later we can think of introducing requirement to approve the offline payment manually by admin and then we can introduce some `dummy` gateway just for tests.

[Payment] Replace dummy payment gateway with offline

---

features/backend/orders.feature

It causes false negatives on Travis (and it does not even work correctly :)).

[Behat] Fixed sorting orders by customers' last names scenario

---

src/Sylius/Bundle/AttributeBundle/Controller/AttributeController.php
src/Sylius/Bundle/AttributeBundle/Resources/views/attributeTypes.html.twig
src/Sylius/Bundle/AttributeBundle/Resources/views/attributeValueForms.html.twig

| Fixed tickets | https://github.com/Sylius/Sylius/issues/3984

[Attribute] Fix hardcoded strings in attribute templates

---

features/reports/reports.feature

In https://github.com/Sylius/Sylius/pull/3802 it has been fixed issue with reports scenarios after year change. Sadly, setting default date as current date occurred in different bug, after *month* change :)
Now each day, month and year are set manually in scenario to prevent such issues in the future.

[Report] Quick fix after month change

---

src/Sylius/Component/Rbac/Model/Permission.php
src/Sylius/Component/Rbac/Model/PermissionInterface.php

Softdelete is not necessary here, what is more it can introduce unwanted behavior (after removing the permission you can't create permission with the same code). In addition the `deletedAt` field was not even included in the doctrine mapping.

[Rbac] Remove softdelete interface and trait from Permission entity

---

src/Sylius/Bundle/CoreBundle/Checkout/Step/AddressingStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/CheckoutStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/FinalizeStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/PaymentStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/SecurityStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/ShippingStep.php
src/Sylius/Bundle/CoreBundle/Controller/CheckoutController.php
src/Sylius/Bundle/CoreBundle/Resources/config/state-machine.yml
src/Sylius/Component/Core/Model/Order.php
src/Sylius/Component/Core/Model/OrderInterface.php
src/Sylius/Component/Core/OrderCheckoutStates.php
src/Sylius/Component/Core/OrderCheckoutTransitions.php
src/Sylius/Component/Core/spec/Model/OrderSpec.php

Hello everybody! This PR is the result of recent brainstorm with @pjedrzejewski and @michalmarcinkowski about cart checkout flow. We've decided to refactor *Cart* state machine and, finally, use it to handle whole checkout logic to get rid of these nasty cart/checkout events and listeners.
And this is the first step. ``sylius_order_checkout`` state machine has ben reworked to have better named states and transitions. Whole checkout workflow now looks like this:
Besides, there are proper transitions applied on ``Cart`` object in checkout steps. In the nearest future, *cart* and *checkout* events and …

[Core] Refactor order checkout state machine

---

features/shop/round_taxes_on_order_item_level.feature
src/Sylius/Behat/Context/Setup/ProductContext.php

Added scenario that ensures proper taxes on order and order item units.

[Cart][Behat] Properly rounded taxes on order

---

features/shop/apply_correct_shipping_fee_with_product_taxes_on_order.feature

Based on https://github.com/Sylius/Sylius/pull/4010. Added scenario for cart with taxed shipments and taxed products.
Hopefully, after merges of one or two previous PR's, review of this one will be... possible :)

[Cart] Cart with shipping fee and product taxes

---

UPGRADE.md
app/migrations/Version20160118160103.php
etc/behat/suites/ui-cart.yml
etc/behat/suites/ui-checkout.yml
features/shop/apply_different_taxes_for_variants_with_different_tax_category.feature
src/Sylius/Behat/Context/Setup/ProductContext.php
src/Sylius/Behat/Context/Ui/CartContext.php
src/Sylius/Behat/Page/Product/ProductShowPage.php
src/Sylius/Bundle/CoreBundle/Form/Type/ProductType.php
src/Sylius/Bundle/CoreBundle/Form/Type/ProductVariantType.php
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Product.orm.xml
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/CoreBundle/spec/Form/Type/ProductTypeSpec.php
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductsData.php
src/Sylius/Bundle/ProductBundle/Behat/ProductContext.php
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/Form/_main.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/show.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductVariant/_form.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Product/show.html.twig
src/Sylius/Component/Core/Model/Product.php
src/Sylius/Component/Core/Model/ProductInterface.php
src/Sylius/Component/Core/Model/ProductVariant.php
src/Sylius/Component/Core/Model/ProductVariantInterface.php
src/Sylius/Component/Core/Taxation/OrderItemsTaxesByZoneApplicator.php
src/Sylius/Component/Core/spec/Model/ProductSpec.php
src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php
src/Sylius/Component/Core/spec/Taxation/OrderItemsTaxesByZoneApplicatorSpec.php

| Fixed tickets | #3829
To improve taxes management and make it more flexible, relation to ``TaxCategory`` has been moved from ``Product`` to ``ProductVariant``.

[Core] Taxable variant

---

.travis.yml

Fatal errors does not allow Behat to recognize which scenarios were already executed & passed and all tests are rerun, which results in twice as long build times, failing anyway.

[Travis] Do not rerun tests on fatal errors

---

src/Sylius/Bundle/ChannelBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Component/Channel/Context/CachedPerRequestChannelContext.php
src/Sylius/Component/Channel/spec/Context/CachedPerRequestChannelContextSpec.php

[Channel] Cached per request channel context

---

features/user/users.feature
src/Sylius/Bundle/ApiBundle/Resources/config/routing/customer.yml
src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.Customer.yml
src/Sylius/Bundle/CoreBundle/Tests/Controller/CustomerApiTest.php
src/Sylius/Bundle/CoreBundle/Tests/DataFixtures/ORM/resources/customers.yml
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/create_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/create_validation_fail_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/create_with_user_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/create_with_user_validation_fail_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/index_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/partial_update_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/show_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/show_with_user_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/update_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/update_validation_fail_response.json
src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
src/Sylius/Bundle/UserBundle/Form/EventSubscriber/AddUserFormSubscriber.php
src/Sylius/Bundle/UserBundle/Form/Type/CustomerType.php
src/Sylius/Bundle/UserBundle/Resources/config/serializer/Model.Customer.yml
src/Sylius/Bundle/UserBundle/Resources/config/serializer/Model.User.yml
src/Sylius/Bundle/UserBundle/Resources/config/services.xml
src/Sylius/Bundle/UserBundle/Resources/config/validation.xml
src/Sylius/Bundle/UserBundle/Resources/public/js/sylius-user.js
src/Sylius/Bundle/UserBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/UserBundle/Resources/translations/validators.en.yml
src/Sylius/Bundle/UserBundle/spec/Form/EventSubscriber/AddUserFormSubscriberSpec.php
src/Sylius/Bundle/UserBundle/spec/Form/Type/CustomerTypeSpec.php
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Customer/_form.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Customer/create.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Customer/update.html.twig

| Fixed tickets | partially #3549 
| Doc PR        | [#409](https://github.com/Sylius/Sylius-Docs/pull/409)
This PR contains tested Customer CRUD. During tests I've had to update User/Customer serialization, add Customer serialization to CoreBundle. I wasn't able to force HatoasBundle to serialize User and Customer bidirectional, because of [#136 issue](https://github.com/willdurand/Hateoas/issues/136). If you have any thoughts for some workaround or even better for some solution, please share or contribute. Current solution is to embed User into Customer, but Customer cannot be embedded into User. 
I had to update CustomerType, what …

[API] [User] Customers CRUD tests

---

src/Sylius/Bundle/CoreBundle/EventListener/OrderChannelListener.php
src/Sylius/Bundle/CoreBundle/OrderProcessing/PromotionProcessor.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/spec/EventListener/OrderChannelListenerSpec.php
src/Sylius/Component/Promotion/Processor/PromotionProcessor.php

| Fixed tickets | https://github.com/Sylius/Sylius/issues/4094
After last updates, problem with fixtures occurred, with ``ChannelNotFoundException``. There were two sources of this evil:
- ``OrderChannelListener`` which got channel from ``ChannelContext`` (which led to exception) and set it on order
- ``PromotionProcessor`` which found active promotions by channel (the same case as above)
Quick fixes for these problems are:
- set channel on ``Order`` in ``OrderChannelListener`` only if it is not set yet (we're setting channel on each order in ``LoadOrdersData``
- pass order's channel to ``findActiveByChannel`` repository …

[Fixture] Quick fixes for channel not found bug

---

etc/behat/suites/ui-cart.yml
features/shop/apply_correct_taxes_based_on_customer_data.feature
src/Sylius/Behat/Context/Setup/TaxContext.php
src/Sylius/Behat/Context/Setup/UserContext.php
src/Sylius/Behat/Context/Ui/CheckoutContext.php
src/Sylius/Behat/Context/Ui/UserContext.php
src/Sylius/Behat/Page/Checkout/CheckoutSecurityStep.php
src/Sylius/Behat/Page/User/LoginPage.php
src/Sylius/Behat/spec/Context/Setup/TaxContextSpec.php
src/Sylius/Behat/spec/Context/Setup/UserContextSpec.php
src/Sylius/Behat/spec/Context/Ui/UserContextSpec.php
src/Sylius/Behat/spec/Page/Checkout/CheckoutSecurityStepSpec.php
src/Sylius/Behat/spec/Page/User/LoginPageSpec.php

Based on https://github.com/Sylius/Sylius/pull/4035. Again, please, don't review this until previous PR's will be merged.

[Cart][Behat] Logging customer's cart

---

src/Sylius/Component/Core/Test/Services/SharedStorage.php
src/Sylius/Component/Core/Test/Services/SharedStorageInterface.php
src/Sylius/Component/Core/spec/Test/Services/SharedStorageSpec.php

After a conversation with @Zales0123 and @Arminek a few days ago we came to conclusion that overriding protection in `SharedStorage` is useless for now and causes unnecessary complexity.

[Sylius/Behat] SharedStorage refactored without overriding protection

---

UPGRADE.md
app/migrations/Version20160210132042.php
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/OrderItem.orm.xml
src/Sylius/Component/Core/Model/OrderItem.php
src/Sylius/Component/Core/Model/OrderItemInterface.php
src/Sylius/Component/Core/Promotion/Checker/ContainsProductRuleChecker.php
src/Sylius/Component/Core/spec/Promotion/Checker/ContainsProductRuleCheckerSpec.php

In favor of upcoming changes with promotions system, it's time to clean up a little bit :) Here I remove some residues of ``OrderItem``-based promotions.

[Core] Removed OrderItem based promotions

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentMethodRepository.php
src/Sylius/Bundle/CoreBundle/Form/Type/Payment/PaymentMethodChoiceType.php
src/Sylius/Bundle/CoreBundle/spec/Doctrine/ORM/PaymentMethodRepositorySpec.php
src/Sylius/Bundle/PaymentBundle/Doctrine/ORM/PaymentMethodRepository.php
src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentMethodChoiceType.php
src/Sylius/Bundle/PaymentBundle/spec/Doctrine/ORM/PaymentMethodRepositorySpec.php
src/Sylius/Component/Payment/Repository/PaymentMethodRepositoryInterface.php

Obvious typo in the word 'builder', all methods specifications for the PaymentMethodRepository were typed 'buidler'.

Fix typo in PaymentMethodRepository method getQueryBuilderForChoiceType

---

src/Sylius/Component/Core/Model/ProductVariant.php
src/Sylius/Component/Core/Model/ProductVariantInterface.php

Original price can be set to null with the setOriginalPrice() method.
Previously if you had original price set lets say to 100$, only way to reset/remove it was with filling in 0.
If you tried setting it with empty value, on saving the product an error 500 would be shown.
The error was thrown from the setter method.

[product] - originalPrice allow null, fix error 500 on save

---

src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
src/Sylius/Bundle/ResourceBundle/Controller/ResourceFormFactory.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/RequestConfigurationSpec.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceFormFactorySpec.php

| Doc PR        | [#412](https://github.com/Sylius/Sylius-Docs/pull/412)
This PR handle the form options from routing configuration.
Now we can pass options using this syntax:
<pre><code>some_route:
path: /new
methods: [GET, POST]
defaults:
_controller: ...
_sylius:
template: ...
form:
type: some_sylius_form
options:
validation_groups: some_validation_groups
another_option: ...
...
redirect: ...
</pre></code>
The previous syntas is allow too:
<pre><code>some_route:
path: /new
methods: [GET, POST]
defaults:
_controller: ...
_sylius:
template: ...
form: some_sylius_form
redirect: ...
</pre></code>

[ResourceBundle] Pass form options in route configuration

---

.travis.yml

It's quite annoying when you need to push once again because empty line has 4 spaces instead of none, some original licensing header needs to be changed or coding standard is enforced even on copied files. It causes a lot of false-negatives.

[Travis] Removed CS checker from Travis build

---

features/shop/apply_correct_shipping_fee_on_order.feature
features/shop/apply_correct_shipping_fee_with_product_taxes_on_order.feature
features/shop/apply_correct_shipping_fee_with_taxes_on_order.feature
features/shop/apply_correct_taxes_for_products_with_different_tax_rates_for_different_zones.feature
src/Sylius/Behat/Context/Ui/CheckoutContext.php

* Do not enforce to always select payment method when proceeding with checkout since in most scenarios we do not need to
* Explicitly choose payment method when proceeding with checkout (right now the taxes to shipping fee are only applied after choosing payment method, but it should be applied at the moment the shipping method is chosen, so let's be explicitly aware of that)

[Behat] Decouple checkout steps in context

---

src/Sylius/Bundle/PaymentBundle/Doctrine/ORM/PaymentMethodRepository.php

PaymentMethodRepository : check if array key exists before checking if value is false

---

etc/behat/suites.yml
etc/behat/suites/ui_cart.yml
etc/behat/suites/ui_checkout.yml

Running `bin/behat -s ui-cart` returns:

[Behat] Renamed ui-* suites to ui_*

---

src/Sylius/Bundle/CoreBundle/Controller/PaymentController.php

[Core] Fixed payment history issue

---

src/Sylius/Bundle/ThemeBundle/Form/ThemeChoiceType.php
src/Sylius/Bundle/ThemeBundle/Resources/config/services/services.xml

[ThemeBundle] Add theme choice form type

---

.travis.yml
composer.json
composer.lock

No more failing PRs caused by not being authenticated by Github. Please do not use this key in other projects than Sylius. Also updates `lakion/mink-debug-extension` version to `^1.0.3`.

[Travis] Added default Github Oauth Token for Composer

---

.travis.yml
etc/travis/run-behat

I've just had a build, that was passing even if there was a fatal error thrown. This PR fixes it.
No rerun if fatal error occurs: https://travis-ci.org/pamil/Sylius/jobs/109561460#L1501
No rerun if tests pass: https://travis-ci.org/pamil/Sylius/jobs/109561185#L1633

[Travis] New approach to running Behat tests (no rerun if fatal error, correct exit code)

---

src/Sylius/Bundle/ThemeBundle/Collector/ThemeDataCollector.php
src/Sylius/Bundle/ThemeBundle/Context/SettableThemeContext.php
src/Sylius/Bundle/ThemeBundle/Context/ThemeContext.php
src/Sylius/Bundle/ThemeBundle/Context/ThemeContextInterface.php
src/Sylius/Bundle/ThemeBundle/HierarchyProvider/ThemeHierarchyProvider.php
src/Sylius/Bundle/ThemeBundle/HierarchyProvider/ThemeHierarchyProviderInterface.php
src/Sylius/Bundle/ThemeBundle/Resources/config/services/services.xml
src/Sylius/Bundle/ThemeBundle/Resources/config/services/templating.xml
src/Sylius/Bundle/ThemeBundle/Resources/config/services/translations.xml
src/Sylius/Bundle/ThemeBundle/Templating/Locator/TemplateFileLocator.php
src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/DefaultTestCase/RequestListener.php
src/Sylius/Bundle/ThemeBundle/Translation/Translator.php
src/Sylius/Bundle/ThemeBundle/spec/Context/SettableThemeContextSpec.php
src/Sylius/Bundle/ThemeBundle/spec/Context/ThemeContextSpec.php
src/Sylius/Bundle/ThemeBundle/spec/Templating/Locator/TemplateFileLocatorSpec.php
src/Sylius/Bundle/ThemeBundle/spec/Translation/TranslatorSpec.php

| BC breaks?    | yes (within master)
`ThemeContextInterface` has only a `getTheme()` method now, which will be a lot easier to implement and maintain.

[Theme] Context interface cleanup

---

features/shop/checkout/checkout_with_offline_payment.feature
features/shop/shipping/apply_correct_shipping_fee_on_order.feature
features/shop/shipping/apply_correct_shipping_fee_with_product_taxes_on_order.feature
features/shop/shipping/apply_correct_shipping_fee_with_taxes_on_order.feature
features/shop/taxation/apply_correct_taxes_based_on_customer_data.feature
features/shop/taxation/apply_correct_taxes_for_items_with_different_tax_rates.feature
features/shop/taxation/apply_correct_taxes_for_items_with_the_same_tax_rate.feature
features/shop/taxation/apply_correct_taxes_for_products_with_different_tax_rates_for_different_zones.feature
features/shop/taxation/apply_correct_taxes_on_visitor_cart.feature
features/shop/taxation/apply_different_taxes_for_variants_with_different_tax_category.feature
features/shop/taxation/not_applying_taxes_for_products_without_tax_category.feature
features/shop/taxation/round_taxes_on_order_item_level.feature
src/Sylius/Behat/Context/Setup/ChannelContext.php
src/Sylius/Behat/spec/Context/Setup/ChannelContextSpec.php

[Behat] Structural and semantic changes

---

features/shop/checkout/checkout_with_offline_payment.feature
src/Sylius/Behat/Context/Setup/ShippingContext.php
src/Sylius/Behat/spec/Context/Setup/ShippingContextSpec.php

[Behat] Rename store ships step

---

src/Sylius/Bundle/ProductBundle/DependencyInjection/Compiler/ServicesPass.php
src/Sylius/Bundle/ProductBundle/DependencyInjection/SyliusProductExtension.php
src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/product_variant.yml
src/Sylius/Component/Product/Factory/ProductVariantFactory.php
src/Sylius/Component/Product/Factory/ProductVariantFactoryInterface.php
src/Sylius/Component/Product/spec/Factory/ProductVariantFactorySpec.php

- changed ``VariantFactory`` into ``ProductVariantFactory``, as it's placed in *Product* component and creates only ``ProductVariant`` objects
- changed ``createForProduct`` method into ``createBasedOnProductId``
- change invalid parameter names in factory and factory interface

[Product] VariantFactory naming changes

---

etc/behat/suites.yml
etc/behat/suites/ui_promotion.yml
features/shop/apply_fixed_discount_promotion_on_order.feature
features/shop/promotion/apply_fixed_discount_promotion_on_order.feature

First portion of new scenarios for *Promotion*, describing simple fixed discount on customer's cart.
It uses "@todo" tag introduced by @pamil in https://github.com/Sylius/Sylius/pull/4169.

[Behat][Promotions] Promotions with fixed discount scenarios

---

src/Sylius/Bundle/ResourceBundle/.gitignore
src/Sylius/Bundle/ResourceBundle/.travis.yml
src/Sylius/Bundle/ResourceBundle/composer.json
src/Sylius/Bundle/ResourceBundle/phpunit.xml.dist
src/Sylius/Bundle/ResourceBundle/test/app/AppKernel.php
src/Sylius/Bundle/ResourceBundle/test/app/autoload.php
src/Sylius/Bundle/ResourceBundle/test/app/config/config.yml
src/Sylius/Bundle/ResourceBundle/test/app/config/parameters.yml.dist
src/Sylius/Bundle/ResourceBundle/test/app/config/resources.yml
src/Sylius/Bundle/ResourceBundle/test/app/config/routing.yml
src/Sylius/Bundle/ResourceBundle/test/app/console
src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/AppBundle.php
src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Entity/Book.php
src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Form/Type/BookType.php
src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Resources/config/doctrine/Book.orm.yml
src/Sylius/Bundle/ResourceBundle/test/src/Tests/Configuration/ConfigurationTest.php
src/Sylius/Bundle/ResourceBundle/test/src/Tests/Controller/BookApiTest.php
src/Sylius/Bundle/ResourceBundle/test/src/Tests/DataFixtures/ORM/books.yml
src/Sylius/Bundle/ResourceBundle/test/src/Tests/DependencyInjection/RegisterResourcesPassTest.php
src/Sylius/Bundle/ResourceBundle/test/src/Tests/DependencyInjection/SyliusResourceExtensionTest.php
src/Sylius/Bundle/ResourceBundle/test/src/Tests/Responses/Expected/books/create_response.json
src/Sylius/Bundle/ResourceBundle/test/src/Tests/Responses/Expected/books/index_response.json
src/Sylius/Bundle/ResourceBundle/test/src/Tests/Responses/Expected/books/show_response.json

Q 	|A
-----|-----
Bug fix? |	no
New feature?| 	no
BC breaks? 	|no
Deprecations? 	|no
Fixed tickets 	|-
License 	|MIT
Doc PR 	|-

[WIP][ResourceBundle] Create integration tests

---

src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPromotionsData.php

Promotions where missing channel assiations and priority ordering.
It is important for priority to have set non equal values (eg. all 0), as gedmo sortable isn't able properly set the values then, and the sorting won't change.

[fixtures][promotion] - add channels and priority to fixtures

---

src/Sylius/Bundle/ResourceBundle/Resources/views/layout.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Security/login.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/layout.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/layout.html.twig

From the [W3C documentation][1] :
> The declaration should fit completely within the first 1024 bytes at
> the start of the file, so it's best to put it immediately after the
> opening head tag.
If the Twig title blocks exceed this (which would be rare), it's possible
for pages using those templates to not be encoded as UTF-8 when sent.
[1]: https://www.w3.org/International/questions/qa-html-encoding-declarations.en#quickanswer

Always declare HTML encoding immediately after the opening head tag.

---

src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
src/Sylius/Bundle/CoreBundle/EventListener/OrderPaymentListener.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/spec/EventListener/OrderPaymentListenerSpec.php
src/Sylius/Bundle/PaymentBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/PaymentBundle/DependencyInjection/SyliusPaymentExtension.php
src/Sylius/Component/Core/OrderProcessing/PaymentProcessor.php
src/Sylius/Component/Core/OrderProcessing/PaymentProcessorInterface.php
src/Sylius/Component/Core/spec/OrderProcessing/PaymentProcessorSpec.php
src/Sylius/Component/Payment/Factory/PaymentFactory.php
src/Sylius/Component/Payment/Factory/PaymentFactoryInterface.php
src/Sylius/Component/Payment/spec/Factory/PaymentFactorySpec.php

[Payment] Adding PaymentFactory 

---

etc/behat/services/contexts.xml
etc/behat/suites/ui_promotion.yml
features/shop/promotion/apply_fixed_discount_promotion_on_order.feature
src/Sylius/Behat/Context/Setup/PromotionContext.php
src/Sylius/Behat/Context/Ui/CartContext.php
src/Sylius/Behat/Page/Cart/CartSummaryPage.php
src/Sylius/Behat/spec/Context/Setup/PromotionContextSpec.php
src/Sylius/Behat/spec/Context/Ui/CartContextSpec.php
src/Sylius/Bundle/CoreBundle/Resources/config/test_services.xml
src/Sylius/Component/Core/Test/Factory/TestPromotionFactory.php
src/Sylius/Component/Core/Test/Factory/TestPromotionFactoryInterface.php
src/Sylius/Component/Core/spec/Test/Factory/TestPromotionFactorySpec.php

Based on https://github.com/Sylius/Sylius/pull/4170
First portion of new promotion scenarios, for very simple cases - receiving fixed discount without any rules and receiving discount equal to cart items total.

[Behat][Promotion] Fixed discount promotion scenarios

---

app/TestKernel.php

[Behat] No more weird fatal errors calling getMasterRequest() on null

---

src/Sylius/Bundle/ResourceBundle/Controller/ResourcesCollectionProvider.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourcesCollectionProviderSpec.php

`Paginator` on `Resource` now respects and sets number of items to paginate on page, set in route configuration. eg:
```yml
sylius_backend_product_index:
path: /
methods: [GET]
defaults:
_controller: sylius.controller.product:indexAction
_sylius:
template: SyliusWebBundle:Backend/Product:index.html.twig
sortable: true
paginate: 5 # works now
repository:
method: createFilterPaginator
arguments: [$criteria, $sorting, $deleted]
```

[Resource][Pagination] - respect paginate parameter from config

---

src/Sylius/Bundle/ResourceBundle/Controller/ResourcesCollectionProvider.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourcesCollectionProviderSpec.php

| BC breaks?    | no|
Fixing yesterday fix, sorry -1:
MaxPerPage needs to be set before current page, so proper number of pages is calculated and current page would be set successfully.

[Resource][Paginator] - setMaxPerPage is set before setCurrentPage to get proper results

---

etc/behat/suites/ui_promotion.yml
features/promotion/receiving_fixed_discount_on_cart.feature
src/Sylius/Behat/Context/Setup/PromotionContext.php
src/Sylius/Component/Core/Promotion/Action/FixedDiscountAction.php
src/Sylius/Component/Core/Test/Factory/TestPromotionFactory.php
src/Sylius/Component/Core/spec/Promotion/Action/FixedDiscountActionSpec.php
src/Sylius/Component/Core/spec/Test/Factory/TestPromotionFactorySpec.php

Based on previous https://github.com/Sylius/Sylius/pull/4199.
Two last scenarios in these feature implemented, also some changes in code to fit them.

[Behat][Promotion] Fixed discount promotion scenarios vol 2

---

features/promotion/receiving_percentage_discount_promotion_on_order.feature
src/Sylius/Behat/Context/Setup/PromotionContext.php
src/Sylius/Behat/spec/Context/Setup/PromotionContextSpec.php
src/Sylius/Component/Promotion/Factory/ActionFactory.php
src/Sylius/Component/Promotion/Factory/ActionFactoryInterface.php
src/Sylius/Component/Promotion/spec/Factory/ActionFactorySpec.php

PR based on https://github.com/Sylius/Sylius/pull/4208 and https://github.com/Sylius/Sylius/pull/4176.
Implementation of percentage discount scenarios.

[Behat][Promotion] Percentage discount scenarios implementation

---

src/Sylius/Bundle/AddressingBundle/Resources/config/services.xml

Fixed problem in Sylius-Standard.

Changed ProvinceNamingProvider to lazy service

---

src/Sylius/Bundle/CartBundle/Form/Type/CartItemType.php
src/Sylius/Bundle/CartBundle/Resources/translations/messages.en.yml

| BC breaks?    | no|
added missing translation for quantity on cart item form type

[cart] - added missing translation for quantity on cart item form type

---

src/Sylius/Bundle/ReviewBundle/EventListener/ReviewChangeListener.php
src/Sylius/Bundle/ReviewBundle/Remover/ReviewerReviewsRemover.php
src/Sylius/Bundle/ReviewBundle/Resources/config/services.xml
src/Sylius/Bundle/ReviewBundle/spec/EventListener/ReviewChangeListenerSpec.php
src/Sylius/Bundle/ReviewBundle/spec/Remover/ReviewerReviewsRemoverSpec.php
src/Sylius/Component/Review/Model/ReviewInterface.php

Average rating on `review subject` (Product) was only recalculated when approved (state machine).
This PR adds events and fixes remover code to recalculate also when:
* `review` is deleted
* `review` rating was changed - its possible in administration
* `customer` was removed and associated `reviews` where deleted.
There is still one problem with recalculation when updating `review` in administration and `review subject `is changed. In that situation, average rating on previous `review subject` is not modified.
Possibility to change the subject is in my opinion pretty weird one so there are two solutions:
* disable change of subject on review …

[Review] - average rating recalculation on change, decouple model

---

src/Sylius/Component/Core/Taxation/OrderItemsTaxesByZoneApplicator.php
src/Sylius/Component/Core/spec/Taxation/OrderItemsTaxesByZoneApplicatorSpec.php

[Taxation] - reset pointer for orderUnits collection before each call

---

etc/behat/services/contexts.xml
src/Sylius/Behat/Context/Setup/GeographicalContext.php
src/Sylius/Behat/spec/Context/Setup/GeographicalContextSpec.php
src/Sylius/Bundle/AddressingBundle/Resources/config/services.xml
src/Sylius/Component/Addressing/Converter/CountryNameConverter.php
src/Sylius/Component/Addressing/Converter/CountryNameConverterInterface.php
src/Sylius/Component/Addressing/spec/Converter/CountryNameConverterSpec.php

[Addressing] Country name to code converter extraction

---

UPGRADE.md
features/legacy/backend/promotions.feature
features/legacy/frontend/cart_promotions_complex.feature
features/legacy/frontend/cart_promotions_coupons.feature
features/legacy/frontend/cart_promotions_fixed.feature
features/legacy/frontend/cart_promotions_percentage.feature
features/legacy/frontend/cart_promotions_usage_limit.feature
src/Sylius/Bundle/CoreBundle/Form/Type/Rule/ContainsProductConfigurationType.php
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPromotionsData.php
src/Sylius/Bundle/PromotionBundle/Form/Type/Rule/CartQuantityConfigurationType.php
src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/PromotionBundle/spec/Form/Type/Rule/CartQuantityConfigurationTypeSpec.php
src/Sylius/Bundle/PromotionBundle/spec/Form/Type/RuleChoiceTypeSpec.php
src/Sylius/Component/Core/Model/Order.php
src/Sylius/Component/Core/spec/Model/OrderSpec.php
src/Sylius/Component/Promotion/Checker/CartQuantityRuleChecker.php
src/Sylius/Component/Promotion/Model/RuleInterface.php
src/Sylius/Component/Promotion/spec/Checker/CartQuantityRuleCheckerSpec.php

It's quite misleading to have "item count" promotion which checks how many different items are inside cart. At the first it looks as it uses cart quantity, but it does not. Moreover, new behat scenarios will operate on quantity, not items count (see [here](https://github.com/Sylius/Sylius/blob/master/features/promotion/receiving_discount_based_on_cart_quantity.feature)). Furthermore, I think that using "cart quantity" to promotion rather than "items count" is more suitable for most of cases. However, I know it can be a big change and BC break, that's because I **request for comments** ;)

[RFC][Promotion] Change "item count" promotion to "cart quantity"

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
src/Sylius/Component/Order/Model/AdjustmentInterface.php

[OrderBundle] Adjustment resource

---

etc/behat/services/contexts.xml
features/promotion/receiving_discount_based_on_cart_quantity.feature
src/Sylius/Behat/Context/Setup/PromotionContext.php
src/Sylius/Behat/Context/Ui/CartContext.php
src/Sylius/Behat/spec/Context/Setup/PromotionContextSpec.php
src/Sylius/Behat/spec/Context/Ui/CartContextSpec.php
src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
src/Sylius/Component/Core/Factory/RuleFactory.php
src/Sylius/Component/Core/Factory/RuleFactoryInterface.php
src/Sylius/Component/Core/spec/Factory/RuleFactorySpec.php
src/Sylius/Component/Promotion/Checker/CartQuantityRuleChecker.php
src/Sylius/Component/Promotion/spec/Checker/CartQuantityRuleCheckerSpec.php

Based on https://github.com/Sylius/Sylius/pull/4249.
There is few things done in this PR connected with implementation of ``receiving_discount_based_on_cart_quantity`` feature:
- implementation of custom ``RuleFactory`` - as it have been done with ``ActionFactory`` but already in proper namespace
- added new promotions-checking step definition - changed ``my cart promotions`` to ``my discount``, changes in other scenarios will be done in separate PR
- set ``CartQuantityRuleChecker`` to always check ``>=`` condition - this change should be done for all checkers and it will be proposed and explained in …

[Behat][Promotion] Discount based on cart quantity

---

app/migrations/Version20160205083520.php
src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Product.orm.xml

[review] - migration fix to be consistent with model

---

etc/travis/run-behat

[Checkout] Quick fix behat command on travis

---

features/legacy/frontend/cart_promotions_complex.feature
features/legacy/frontend/cart_promotions_fixed.feature
features/legacy/frontend/cart_promotions_percentage.feature
features/legacy/frontend/cart_promotions_usage_limit.feature
src/Sylius/Bundle/PromotionBundle/Behat/PromotionContext.php
src/Sylius/Bundle/PromotionBundle/Form/Type/Rule/CartQuantityConfigurationType.php
src/Sylius/Bundle/PromotionBundle/Form/Type/Rule/ItemTotalConfigurationType.php
src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/PromotionBundle/spec/Form/Type/Rule/CartQuantityConfigurationTypeSpec.php
src/Sylius/Bundle/PromotionBundle/spec/Form/Type/Rule/ItemTotalConfigurationTypeSpec.php
src/Sylius/Component/Core/Promotion/Checker/ContainsProductRuleChecker.php
src/Sylius/Component/Promotion/Checker/CartQuantityRuleChecker.php
src/Sylius/Component/Promotion/Checker/ItemTotalRuleChecker.php
src/Sylius/Component/Promotion/spec/Checker/CartQuantityRuleCheckerSpec.php
src/Sylius/Component/Promotion/spec/Checker/ItemTotalRuleCheckerSpec.php

| Doc PR        | https://github.com/Sylius/Sylius-Docs/pull/418
Flag "equal" on promotions rules is redundant. For example, ``count: 5`` with ``equal: true`` is equivalent to ``count: 4`` without this flag. Moreover, in my opinion it's more natural to set promotion for "sth or more" rather than "for more than sth".

[Promotion] Removed "equal" flag from rules

---

src/Sylius/Bundle/AssociationBundle/composer.json

Shouldn't the AssociationBundle bundle depent on the component? Like with must of the Sylius bundles?

[AssociationBundle ] Added Association component dependecy in the AssociationBundle

---

src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineODMDriver.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineORMDriver.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrinePHPCRDriver.php

It will save a lot of our time when we inject a repository to a service that does not use it, but is used while there is no database, eg. repositories injected to Twig extensions or cache warmers.

[Resource] Lazy resource repositories

---

app/config/security.yml
src/Sylius/Bundle/CoreBundle/Tests/DataFixtures/ORM/authentication/api_administrator.yml
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadApiData.php
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadGroupsData.php

I guess we need to change the security role ROLE_API with ROLE_API_ACCESS in order to allow the manage of this permission from the Sylius backend

use ROLE_API_ACCESS instead of ROLE_API

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php

Add enabled is true on findLatest productRepository function.
I think we have to hide "disabled" products in frontend.
This PR will only "filter" results, so, we have to control access in ProductController:detailsAction.
The simplier would be to throw an exception "NotEnabled" or something like this. What do you think ?

[CoreBundle] Add enabled is true when retrieve latest products

---

src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/show.html.twig

| New feature?  | no|yes
| BC breaks?    | no|yes
| Deprecations? | no|yes
IMO this is not only redundant but also could(and will) explode if you have too many values attached to an option.

[WebBundle] Hide option values on product show page in backend

---

src/Sylius/Bundle/CoreBundle/Controller/ProductController.php

Fix browse products by archetype error

[CoreBundle] Update renderArchetypeResults with configuration

---

README.md
composer.json
composer.lock

[Behat] Add selenium server standalone in require-dev

---

app/config/config.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/main.yml

FOSRestBundle's `format_listener.rules` configuration can not be overwritten, ref. [configuration](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/DependencyInjection/Configuration.php#L290).

[Core] FOSRest format rules can not be overwritten

---

features/legacy/reports/reports.feature
src/Sylius/Bundle/ReportBundle/Form/EventListener/BuildReportRendererFormSubscriber.php
src/Sylius/Bundle/ReportBundle/Form/Type/ReportType.php
src/Sylius/Bundle/ReportBundle/Resources/config/services.xml
src/Sylius/Bundle/ReportBundle/spec/Form/EventListener/BuildReportRendererFormSubscriberSpec.php
src/Sylius/Bundle/ReportBundle/spec/Form/Type/ReportTypeSpec.php
src/Sylius/Component/Report/Renderer/DefaultRenderers.php

| Fixed tickets | #4196
Remove prefix in renderer configuration type

[ReportBundle] Remove prefix on configurationType type

---

etc/travis/prepare-javascript

[Travis] Use Selenium downloaded by Composer

---

src/Sylius/Bundle/SearchBundle/Finder/ElasticsearchFinder.php

Indead, when you select two values in facets like price "from 0 to 20" and "from 20.01 to 50" the results can't find the correct results.
In fact, it seems to keep the last request :/
I also fix the missing $termFilters variable initialization

[SearchBundle] Add boolOr filter for range filters for elasticsearch engine

---

src/Sylius/Bundle/AttributeBundle/Form/EventSubscriber/BuildAttributeValueFormSubscriber.php

| Fixed tickets | #4295 
Remove requirement for a submitted value in processing attribute form submissions to support unticked checkboxes

[Attribute] Allow saving of unchecked checkboxes

---

src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/inventory.yml
src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/payment.yml

I know that you are refactoring state machines but for now in Order backend there is some bugs, so I added graphs to routings to solve this issues.

[WebBundle] Added graph to routing to solving state machine update issue.

---

src/Sylius/Bundle/SearchBundle/Finder/ElasticsearchFinder.php

| Deprecations?   | no|yes
I noticed that even though some filters are hidden if empty some are still being shown(like price ranges, for example) even if there are no matches found.

[SearchBundle] Hide empty filters for elasticsearch engine

---

src/Sylius/Bundle/SearchBundle/DependencyInjection/Configuration.php

| New feature?  | no|yes
| BC breaks?    | no|yes
| Deprecations? | no|yes
Just got stuck with inability to add any new mapping w/o this fix.

[SearchBundle] Make orm_indexes node properly overridable

---

features/promotion/receiving_percentage_discount_on_products_from_specific_taxon.feature

| Fixed tickets | https://github.com/Sylius/Sylius/issues/3368
This is next portion of scenarios about promotions - however this time it would finally require some more coding :smile: However, for now there is only feature, which describes new promotions case - applying promotions only to product from specific taxon.

[Behat][Promotion] Percentage discount on products from specific taxon

---

src/Sylius/Component/Core/Accessor/ProductAccessor.php

| New feature?  | no|yes
| BC breaks?    | no|yes
| Deprecations? | no|yes
At this moment this class only used in SearchBundle and it is wrong to match option by presentation since it might contain non-latin characters that cannot be used in YAML. 
It is better to use code field in this case.
This PR is based on #4237

[Core][ProductAccessor] Use option code instead of name

---

src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/MongoDB/DocumentRepository.php

| Related tickets | fixes #3533 #4072
when paginate is disabled for MongoODM it breaks return of indexAction because `findAll` or `findBy` methods returns a Cursor object instead array or iterator

[ResourceBundle] fix return from MongoDB Document Repository

---

src/Sylius/Bundle/CoreBundle/Routing/RouteProvider.php

| BC breaks?    | maybe!?
We've created a custom slug `Transliterator` to have Persian characters in URL but when visit a Taxon URI needs to be decoded.
Do you think this a right place to decode it?

[CoreBundle] Decode url when finding entity based on request URI

---

src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductArchetypeData.php
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductOptionData.php
src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductsData.php

| Related tickets | fixes #4411 

Fix invalid references to options in fixtures

---

src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php

ResourceController was missing update event and flush for move actions. Consequently resources order/sorting wasn't changed. (promotions priority)

Resource movement sort persistance

---

src/Sylius/Bundle/CoreBundle/Routing/RouteProvider.php

This is a fix for regression of #4242 caused by #3854

[CoreBundle] Decode escaped characters of url in repository-based route provider

---

app/config/config_test_cached.yml

| Related tickets | #4410
As it defaults to `%kernel.debug%`, we don't get any error if referencing unexisting variable / attribute in Twig.

[Behat] Set "twig.strict_variables" to true in test_cached

---

etc/behat/services/contexts.xml
etc/behat/services/pages.xml
features/user/renewing_account_after_deletion.feature
src/Sylius/Behat/Context/Setup/UserContext.php
src/Sylius/Behat/Context/Ui/UserContext.php
src/Sylius/Behat/Page/User/RegisterPage.php
src/Sylius/Behat/Page/User/RegisterPageInterface.php
src/Sylius/Behat/spec/Context/Setup/UserContextSpec.php
src/Sylius/Behat/spec/Context/Ui/UserContextSpec.php
src/Sylius/Behat/spec/Page/User/RegisterPageSpec.php

[User] Account renewal feature scenarios

---

src/Sylius/Component/Core/Taxation/OrderShipmentTaxesByZoneApplicator.php
src/Sylius/Component/Core/spec/Taxation/OrderShipmentTaxesByZoneApplicatorSpec.php

| Related tickets | fixes #4452
The shipment tax adjustment will not be added if the resulting tax amount calculated for it is 0.

[RFC][Taxation] Skip 0 value tax adjustment on shipping.

---

.gitignore
bin/install
bin/sylius-cs-fixer
etc/bash/common.lib.sh
etc/bin/fix-coding-standards

| Bug fix?        | yes (can call `etc/bin/fix-coding-standards` from any directory)
| BC breaks?      | yes (removed `bin/install`, moved `bin/sylius-cs-fixer` to `etc/bin/fix-coding-standards`)

[DX] Moved custom scripts from bin/ to etc/bin/, fixed relative paths issues, removed bin/install

---

src/Sylius/Bundle/CoreBundle/Tests/Controller/CountryApiTest.php
src/Sylius/Bundle/CoreBundle/Tests/DataFixtures/ORM/resources/countries.yml
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/country/create_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/country/create_validation_fail_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/country/index_response.json
src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/country/show_response.json

Country api tests

---

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php

I changed condition from value "1" (integer) to boolean (true).
Indeed, in mysql, there is no problem, but with more strict sgbd (as postgresql), that need to be casted.

[CoreBundle] Change enabled = 1 in ProductRepository to true

---

src/Sylius/Bundle/ResourceBundle/Form/DataTransformer/ObjectToIdentifierTransformer.php

| Related tickets | fixes #4468, #4373 
When rendering checkout **shipping** step if Product does not have a shipping category an `Internal Server Error` happens; because `sylius_shipping_method_choice` cannot be rendered, I don't exactly know why.
What happens is inside the transformer passed `$value` in not `null` (it is `""` empty string) so the transformer enters into an exception point.
It can also be a mis-configuration in shipping method choice, but I'm not sure.

[ResourceBundle] Fix ObjectToIdentifierTransformer to check for an empty value

---

app/config/security.yml
src/Sylius/Bundle/UserBundle/OAuth/UserProvider.php
src/Sylius/Bundle/UserBundle/spec/OAuth/UserProviderSpec.php

This fix the oauth login/registration

[OAuth][Login] Fix oauth login

---

src/Sylius/Bundle/FixturesBundle/DataFixtures/DataFixture.php

Throw an exception when a method in Datafixture class does not exists.
Currently I get segmentation faults when calling a "wrong" function.

[FixtureBundle] Throw exception when method does not exists

---

src/Sylius/Bundle/VariationBundle/Form/Type/OptionValueType.php
src/Sylius/Bundle/VariationBundle/Form/Type/VariantMatchType.php
src/Sylius/Bundle/VariationBundle/Resources/config/validation.xml
src/Sylius/Bundle/VariationBundle/spec/Form/Type/VariantMatchTypeSpec.php
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Inventory/macros.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductOption/macros.html.twig

| Related tickets | fixes #4449
Fixed:
* in inventory, where the script will throw an exception,
* cyrilc translations referenced in #4449 
* translation and validation strings and keys
Maybe for consistency all mentions of `presentation` should be changed to `name` in OptionValue and probably in productVariant. As it is proxied to the name anyway.
```php
// OptionValue.php
/**
* {@inheritdoc}
*/
public function getPresentation()
{
if (null === $this->option) {
throw new \BadMethodCallException('The option have not been created yet so you cannot access proxy methods.');
}
return $this->option->getName();
}
```

[OptionValue][Core] - various fixes after option value model changes

---

src/Sylius/Bundle/WebBundle/Controller/Frontend/Account/OrderController.php

Desktop view for bootstrap needs viewport width > 1200px (`A4 print`) so for better PDF format I added some options to the controller

Changing viewport of backend invoice PDF generation.

---

features/promotion/receiving_fixed_discount_on_items_on_price_range.feature
src/Sylius/Behat/Context/Setup/PromotionContext.php
src/Sylius/Behat/spec/Context/Setup/PromotionContextSpec.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Component/Core/Promotion/Action/ItemFixedDiscountAction.php
src/Sylius/Component/Core/Promotion/Action/ItemPercentageDiscountAction.php
src/Sylius/Component/Core/Promotion/Filter/FilterInterface.php
src/Sylius/Component/Core/Promotion/Filter/PriceRangeFilter.php
src/Sylius/Component/Core/Promotion/Filter/TaxonFilter.php
src/Sylius/Component/Core/spec/Promotion/Action/ItemFixedDiscountActionSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/ItemPercentageDiscountActionSpec.php
src/Sylius/Component/Core/spec/Promotion/Filter/PriceRangeFilterSpec.php
src/Sylius/Component/Core/spec/Promotion/Filter/TaxonFilterSpec.php

Based on https://github.com/Sylius/Sylius/pull/4391 and https://github.com/Sylius/Sylius/pull/4453, highly recommend to wait with merge for everybody good health ;)

[Behat][Promotion] Fixed discount on items in price range

---

src/Sylius/Bundle/CoreBundle/Checkout/Step/AddressingStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/CheckoutStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/PaymentStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/SecurityStep.php
src/Sylius/Bundle/CoreBundle/Checkout/Step/ShippingStep.php
src/Sylius/Component/Core/Exception/InvalidTransitionException.php
src/Sylius/Component/Core/spec/Exception/InvalidTransitionExceptionSpec.php

- previous implementation led to confusion; if transition is invalid, then state machine is wrongly configured or wrongly used and it should be shown
- added checking order state before applying some transitions

[Core] Checkout flow and errors improvements

---

src/Sylius/Bundle/ResourceBundle/Controller/RequestConfigurationFactory.php
src/Sylius/Bundle/ResourceBundle/Controller/RequestConfigurationFactoryInterface.php
src/Sylius/Bundle/ResourceBundle/Resources/config/controller.xml
src/Sylius/Bundle/ResourceBundle/spec/Controller/RequestConfigurationFactorySpec.php

| Related tickets | fixes #4524
| Doc PR          | no  need
Since v0.17.0 the settings in sylius_resource in `sylius.yml` are not taken in account anymore.
This PR 
- fills the `defaultParameters `of `RequestConfigurationFactory` in `controller.xml` by adding an argument `%sylius.resource.settings%`
- then merge the `defaultParameters` in `create` method 
- two news tests are added to `RequestConfigurationFactorySpec`
- it indicates as deprecated the `KernelControllerSubscriber` methods since it doesn't seems to be call anymore

[ResourceBundle] fixed #4524 resource.settings not taken in account

---

src/Sylius/Behat/Context/Transform/SharedStorageContext.php
src/Sylius/Behat/spec/Context/Transform/SharedStorageContextSpec.php

It is more natural to use snake_cased words as a key in shared storage. With this fix `this tax category` will be translated to last `tax_category` resource.

[DX] Imporve SharedStorage transformator

---

etc/bash/packages.lib.sh
etc/bin/install-package
etc/bin/install-packages

Eg. if ResourceBundle adds a new dependency, and ThemeBundle depends on ResourceBundle, ThemeBundle cache should be invalidated just as ResourceBundle one

[Travis] Reset all composer.lock caches on composer.json update

---

features/addressing/managing_countries/editing_country.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php
src/Sylius/Behat/Page/Admin/Country/UpdatePage.php
src/Sylius/Behat/Page/Admin/Country/UpdatePageInterface.php
src/Sylius/Behat/spec/Context/Ui/Admin/ManagingCountriesContextSpec.php

[Admin] Country code immutability

---

UPGRADE.md
features/legacy/frontend/cart_promotions_fixed.feature
src/Sylius/Bundle/CoreBundle/Form/DataTransformer/TaxonsToCodesTransformer.php
src/Sylius/Bundle/CoreBundle/Form/Type/Rule/TaxonConfigurationType.php
src/Sylius/Bundle/CoreBundle/Resources/config/form.xml
src/Sylius/Bundle/CoreBundle/spec/Form/DataTransformer/TaxonsToCodesTransformerSpec.php
src/Sylius/Bundle/ResourceBundle/Behat/DefaultContext.php
src/Sylius/Component/Core/Promotion/Checker/TaxonRuleChecker.php
src/Sylius/Component/Core/spec/Promotion/Checker/TaxonRuleCheckerSpec.php

| Related tickets | partially https://github.com/Sylius/Sylius/issues/4544
* fix ``taxon`` promotion rule (change taxons collection to taxons' codes array)
* removed "exclude" option for ``taxon`` rule
* modify ``taxon`` rule configuration type to handle multiple taxons
Known issues:
* while editing promotion with existing ``taxon`` rule, picked taxons are not checked - I suppose it can be skipped for now, as in the nearest future it will be rewrite into new backend layout

[Core][Promotion] Fix taxon based promotions

---

src/Sylius/Bundle/ResourceBundle/Controller/EventDispatcherInterface.php

| Doc PR          | no
The only reason I added this is because the implementation for this interface does return the event

[ResourceBundle] Added return doc statement

---

etc/behat/services/contexts/setup.xml
etc/behat/services/contexts/ui.xml
etc/behat/services/pages.xml
features/taxation/managing_tax_categories/adding_tax_category.feature
features/taxation/managing_tax_categories/editing_tax_category.feature
features/taxation/managing_tax_categories/tax_category_unique_code_validation.feature
features/taxation/managing_tax_categories/tax_category_validation.feature
src/Sylius/Behat/Behaviour/ChecksCodeImmutability.php
src/Sylius/Behat/Behaviour/DescribesIt.php
src/Sylius/Behat/Behaviour/NamesIt.php
src/Sylius/Behat/Behaviour/SpecifiesItsCode.php
src/Sylius/Behat/Context/Setup/TaxationContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxCategoryContext.php
src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
src/Sylius/Behat/Page/Admin/Crud/CreatePageInterface.php
src/Sylius/Behat/Page/Admin/TaxCategory/CreatePage.php
src/Sylius/Behat/Page/Admin/TaxCategory/CreatePageInterface.php
src/Sylius/Behat/Page/Admin/TaxCategory/UpdatePage.php
src/Sylius/Behat/Page/Admin/TaxCategory/UpdatePageInterface.php
src/Sylius/Behat/spec/Context/Setup/TaxationContextSpec.php
src/Sylius/Behat/spec/Context/Ui/Admin/ManagingTaxCategoryContextSpec.php

[Admin] Tax category creation

---

docs/bundles/SyliusReportBundle/installation.rst

I just fixed wrong namespace usage in bundle registration (@ AppKernel) for ReportBundle.
| Doc PR        | http://docs.sylius.org/en/latest/bundles/SyliusReportBundle/installation.html 1.1

Fixed wrong namespace in Bundle registration for ReportBundle

---

features/locale/managing_locales/locale_unique_code_validation.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingLocalesContext.php
src/Sylius/Behat/Page/Admin/Locale/CreatePage.php
src/Sylius/Behat/Page/Admin/Locale/CreatePageInterface.php
src/Sylius/Behat/spec/Context/Ui/Admin/ManagingLocalesContextSpec.php

[Admin] Locale unique code validation feature

---

etc/behat/services/contexts/transform.xml
etc/behat/services/contexts/ui.xml
etc/behat/services/pages.xml
etc/behat/suites.yml
etc/behat/suites/ui/taxation/managing_tax_rates.yml
features/taxation/managing_tax_rates/adding_tax_rate.feature
features/taxation/managing_tax_rates/deleting_tax_rate.feature
features/taxation/managing_tax_rates/editing_tax_rate.feature
features/taxation/managing_tax_rates/tax_rate_unique_code_validation.feature
src/Sylius/Behat/Context/Setup/TaxationContext.php
src/Sylius/Behat/Context/Transform/TaxRateContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxRateContext.php
src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
src/Sylius/Behat/Page/Admin/TaxRate/CreatePage.php
src/Sylius/Behat/Page/Admin/TaxRate/CreatePageInterface.php
src/Sylius/Behat/Page/Admin/TaxRate/UpdatePage.php
src/Sylius/Behat/Page/Admin/TaxRate/UpdatePageInterface.php
src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
src/Sylius/Bundle/AdminBundle/Resources/config/grids.yml
src/Sylius/Bundle/AdminBundle/Resources/config/grids/tax_rate.yml
src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
src/Sylius/Bundle/AdminBundle/Resources/config/routing/tax_rate.yml
src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/AdminBundle/Resources/views/TaxRate/Field/amount.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/TaxRate/_form.html.twig
src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml

[Admin] Adding tax rate feature

---

etc/behat/services.xml
etc/behat/services/contexts/ui.xml
src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingLocalesContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxCategoryContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxRateContext.php
src/Sylius/Behat/Exception/NotificationExpectationMismatchException.php
src/Sylius/Behat/Service/Accessor/NotificationAccessor.php
src/Sylius/Behat/Service/Accessor/NotificationAccessorInterface.php
src/Sylius/Behat/Service/NotificationChecker.php
src/Sylius/Behat/Service/NotificationCheckerInterface.php
src/Sylius/Behat/spec/Context/Ui/Admin/ManagingCountriesContextSpec.php
src/Sylius/Behat/spec/Context/Ui/Admin/ManagingLocalesContextSpec.php
src/Sylius/Behat/spec/Context/Ui/Admin/ManagingTaxCategoryContextSpec.php
src/Sylius/Behat/spec/Service/NotificationCheckerSpec.php

Just a thought. Because of usage of NotificationAccessor we had to duplicate some line, so I just extracted it to separated service, just to keep DRY. I haven't coupled it with NotificationAccessor, because it can be useful somewhere else and writing test for it is pretty painful also.
_Edit_
After introducing new Exception output for developer will look like this:

[RFC][DX] Introduce NotificationChecker

---

composer.json
composer.lock

[Composer] Add missing dependency + alphabetically sorting

---

src/Sylius/Bundle/AdminBundle/Resources/views/Country/_form.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/Crud/create.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/Crud/update.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/Locale/_form.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/TaxCategory/_form.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/TaxRate/_form.html.twig

As ``{{ form_end(form) }}`` has been added at the end of every form, it was impossible to render only part of form's fields. I've changed it into ``{{ form_end(form, {'render_rest': false}) }}`` and added {{ form_row(form._token) }} (as token is always needed) to prevent such a inconvenience.

[Admin] Don't render whole form by default on create/update page

---

.travis.yml

`--strict` ensures that package is ready for releasing.

[Travis] Use strict Composer validation for the main composer.json / composer.lock

---

src/Sylius/Bundle/CoreBundle/Form/Type/CartType.php

Shouldn't the promotion coupon be optional in cart?

Set promotion coupon in cart to not required

---

src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Checkout/Step/finalize.html.twig

```getPromotionsTotalRecursively``` exists on the Order model, not the Cart model.

[WebBundle] Fix finalize page

---

src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelper.php
src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelperInterface.php
src/Sylius/Bundle/CurrencyBundle/Twig/CurrencyExtension.php
src/Sylius/Bundle/CurrencyBundle/spec/Templating/Helper/CurrencyHelperSpec.php
src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig

This widget rendering:
will be changed to this one:
_Update_
Currency extension was extended to provide current currency instead of hardcoded _$_

[Twig] Sematic money widget

---

features/legacy/backend/metadata/metadata_customization.feature
src/Sylius/Bundle/CoreBundle/Behat/MetadataContext.php
src/Sylius/Bundle/MetadataBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/MetadataBundle/Model/MetadataContainer.php
src/Sylius/Bundle/MetadataBundle/Resources/config/doctrine/model/MetadataContainer.orm.xml

| Related tickets | fixes #4472
Metadata cannot be stored as `object` ORM type, because objects are
compared (===) by reference, not by value, what means that changes
would not be persisted.
The only working way I have found is to store metadata as `text`
type and serialize it on MetadataContainer::setMetadata() method
call. However, after every metadata modification we have to use that
method once again, if not - changes won't be persisted.

[Metadata] Fix modifying metadata by serializing it early

---

src/Sylius/Bundle/GridBundle/Doctrine/ORM/DataSource.php

| Related tickets | #3775
This matches the behaviour in the [EntityRepository](https://github.com/Sylius/Sylius/blob/710b8b4f2c0fecae03d71b19d977527602118c55/src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php#L60-L69)

[Grid] do not use output walkers in orm driver

---

src/Sylius/Bundle/AttributeBundle/EventListener/LoadMetadataSubscriber.php
src/Sylius/Bundle/AttributeBundle/spec/EventListener/LoadMetadataSubscriberSpec.php

fix mapping error:
```
$ app/console doctrine:schema:validate
[Mapping]  FAIL - The entity-class 'Sylius\Component\Product\Model\Attribute' mapping is invalid:
* The mappings Sylius\Component\Product\Model\Attribute#values and Sylius\Component\Product\Model\AttributeValue#subject are inconsistent with each other.
```

[AttributeBundle] Fix attribute metadata

---

src/Sylius/Bundle/CoreBundle/Form/DataTransformer/TaxonsToCodesTransformer.php
src/Sylius/Bundle/CoreBundle/spec/Form/DataTransformer/TaxonsToCodesTransformerSpec.php

| Related tickets | https://github.com/Sylius/Sylius/issues/4544
Fixed the TaxonsToCodesTransformer by adjusting the array check to allow for ArrayCollection.
This is the same change as https://github.com/Sylius/Sylius/pull/4651 - except that I screwed up the rebase pretty bad in the previous branch.

Fix TaxonsToCodesTransformer

---

src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml

I also fixed indent (I think it should be 4 spaces, here and in some other files). We should definitely keep this order, as it's not hard but makes file much more readable ;)

[Ui][Critical] Sort messages keys

---

src/Sylius/Bundle/CoreBundle/Sitemap/Model/SitemapUrl.php

Fixed the setter so that it maches the exception. Previously a priority of 1.0 would not be allowed.

[CoreBundle] Sitemap - Fix priority setter

---

src/Sylius/Component/Promotion/Checker/CouponsEligibilityChecker.php
src/Sylius/Component/Promotion/spec/Checker/CouponsEligibilityCheckerSpec.php

| Related tickets | partially https://github.com/Sylius/Sylius/issues/4544
There was a bug introduced in https://github.com/Sylius/Sylius/pull/4645 that basically threw flash messages when a user added an item to the cart because it was checking for coupon eligibility even when there was none specified.
@Zales0123: Hope this is an appropriate solution.

[Promotion] do not check for eligibility if no coupon is specified

---

src/Sylius/Behat/Service/Accessor/TableAccessor.php

This one fix problem with accessing a `TableAccessor` when working on Selenium

[Behat] TableAccessor fix

---

src/Sylius/Bundle/ShippingBundle/Controller/ShipmentController.php
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Macros/misc.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/show.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Shipment/show.html.twig

Now when shipments are in one of `hold`, `release`, `backorder`, `prepare`, `cancel` or `return` transition states, it will show the transition buttons, and if in **ship** transition state it will show a tracking form.

[WebBundle] Improve shipment transitions and tracking form

---

src/Sylius/Bundle/CoreBundle/Checkout/CheckoutProcessScenario.php
src/Sylius/Component/Core/Model/Order.php
src/Sylius/Component/Core/Model/OrderInterface.php
src/Sylius/Component/Core/OrderProcessing/PaymentProcessor.php
src/Sylius/Component/Core/spec/OrderProcessing/PaymentProcessorSpec.php

Because of this bug customers would see an exception due to `lastPayment->method` was not set (`null`) correctly.

[Core] Get last payment's method also from failed payments

---

app/migrations/Version20151203134947.php
app/migrations/Version20151209104639.php
app/migrations/Version20151209104827.php
app/migrations/Version20151210134607.php
app/migrations/Version20151216125201.php
app/migrations/Version20151221121710.php
app/migrations/Version20151228162916.php
app/migrations/Version20160112154949.php

Automatically add incremental code based on the db name.
eg: for sylius_shipping_category, generate SC1, SC2, SC3 .....
This is to prevent migration fails due to the UNIQUE INDEX statement.
When the migration fails you have to manually add code to db for each line, comment SQL query already ran and run migration script again... :(
Tested and fully working
Enjoy

[Migration] Auto-generate code in db field while running migration

---

src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig

| Deprecations?   | no|yes
Just UI change. Instead of something like this:
we will receive something like this:
Based on #4683 and #4729

[Twig] Percentage twig widget

---

src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/UiBundle/Resources/views/Form/_create.html.twig
src/Sylius/Bundle/UiBundle/Resources/views/Form/_saveChanges.html.twig

It was annoying, that it wasn't possible to just go back on create/update form. It is not the prettiest solution, but I wasn't able to find a better one. Also I have not add second parameter as a fallback, because I didn't want to add parameter to this templates. But on the other hand I don't have any good idea, how to solve this. 
Before:
After:

[RFC] [Ui] Cancel button

---

src/Sylius/Bundle/ResourceBundle/Form/DataTransformer/ObjectToIdentifierTransformer.php
src/Sylius/Bundle/ResourceBundle/spec/Form/DataTransformer/ObjectToIdentifierTransformerSpec.php
src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodChoiceType.php
src/Sylius/Bundle/ShippingBundle/spec/Form/Type/ShippingMethodChoiceTypeSpec.php

Ok, 7th and 8th of October were bad days for the Republic :smile: These days I've fixed ``ObjectToIdentifierTransformer`` in https://github.com/Sylius/Sylius/pull/3406... but *de facto* I ruined it :( It has been written good, as in ``reverseTransform`` method value is object from form and in ``transform`` it's identifier - not otherwise. The reason why it was working is that if we pass object to ``findOneBy`` method instead of id, doctrine would return object based on passed object id :boom: Now it should be good, I really hope :)

[Resource] Fixed proviously spoiled transformer

---

src/Sylius/Bundle/MailerBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/MailerBundle/Form/Type/EmailTemplateChoiceType.php
src/Sylius/Bundle/MailerBundle/spec/Form/Type/EmailTemplateChoiceTypeSpec.php

- configuration for templates uses keys now, and new templates can be properly added. Before the fix new templates from the configuration would be resolved only with number index instead of actual key.
- choiceform deprecation fixed.

[mailer] - fix mailer configuration to allow adding new templates

---

src/Sylius/Bundle/UserBundle/Resources/config/services.xml
src/Sylius/Bundle/UserBundle/Resources/config/validation.xml
src/Sylius/Bundle/UserBundle/Validator/Initializer/CustomerInitializer.php
src/Sylius/Bundle/UserBundle/spec/Validator/Initializer/CustomerInitializerSpec.php

| Related tickets | fixes #4733 
Added customer validator initializer that sets email canonical on initialisation. Customer object is now also validating against `emailCanonical` and uses `email` as it's error path.

[Bug Fix] Added customer validator initializer to set canonical email

---

src/Sylius/Component/Core/Taxation/Applicator/OrderItemUnitsTaxesApplicator.php
src/Sylius/Component/Core/Taxation/Applicator/OrderItemsTaxesApplicator.php
src/Sylius/Component/Core/Taxation/Strategy/AbstractTaxCalculationStrategy.php
src/Sylius/Component/Core/composer.json
src/Sylius/Component/Core/spec/Taxation/Applicator/OrderItemUnitsTaxesApplicatorSpec.php
src/Sylius/Component/Core/spec/Taxation/Applicator/OrderItemsTaxesApplicatorSpec.php
src/Sylius/Component/Registry/PrioritizedServiceRegistry.php
src/Sylius/Component/Registry/composer.json
src/Sylius/Component/Registry/spec/PrioritizedServiceRegistrySpec.php

Few minor enhancements to #4406:
* Removed check for `0` quantity because order item with this quantity shouldn't ever exist
* Reveal invalid order items (with quantity `0`) passed to order items taxes applicator
* Removed PHPUnit dependency from specs
* Replaced manual assertions with Webmozart library

[Taxation] Tax calculation minor enhancements

---

src/Sylius/Bundle/ResourceBundle/Controller/SingleResourceProvider.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/SingleResourceProviderSpec.php

Currently the `SingleResourceProvider` uses the `findBy` method of the repository in order to locate an item by ID - this works fine with the ORM but will fail with the Doctrine PHPCR ODM which does not map the `id` to a field.
This PR changes the behavior to call the `find` method when an ID is given rather than `findBy`

[SingleResourceProvider] Use repository find() method.

---

src/Sylius/Bundle/UserBundle/Doctrine/ORM/UserRepository.php

Allows the use of extended User entities.

[Reporting] Fix UserRepository coupling with sylius default table naming structure

---

src/Sylius/Behat/NotificationType.php
src/Sylius/Behat/Service/NotificationChecker.php

[Behat][Notification] Flyweight pattern

---

src/Sylius/Bundle/SearchBundle/DependencyInjection/SyliusSearchExtension.php
src/Sylius/Bundle/SearchBundle/Listener/ElasticaProductListener.php

| Related tickets | mentioned in #4525
Because the object persister was called on `postFlush` the ids of the objects are `null` and so the elastic search bulk operation fails. By calling the object persister at the `onFlush` event, everything works nicely.

[Bug Fix] Fix elastic search "[ActionRequestValidationException] id is missing" error

---

src/Sylius/Bundle/GridBundle/Resources/config/field_types.xml
src/Sylius/Component/Grid/FieldTypes/DatetimeFieldType.php
src/Sylius/Component/Grid/spec/FieldTypes/DatetimeFieldTypeSpec.php

It could be useful for fields like ``createdAt`` etc.

[Grid] Introduced grid datetime field type

---

src/Sylius/Bundle/CoreBundle/Resources/config/templating.xml
src/Sylius/Bundle/CoreBundle/Templating/Helper/MoneyHelper.php
src/Sylius/Bundle/CoreBundle/spec/Templating/Helper/MoneyHelperSpec.php
src/Sylius/Bundle/CurrencyBundle/Resources/config/templating.xml
src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelper.php
src/Sylius/Bundle/CurrencyBundle/Templating/Helper/MoneyHelper.php
src/Sylius/Bundle/CurrencyBundle/spec/Templating/Helper/CurrencyHelperSpec.php
src/Sylius/Bundle/CurrencyBundle/spec/Templating/Helper/MoneyHelperSpec.php
src/Sylius/Bundle/MoneyBundle/Formatter/MoneyFormatter.php
src/Sylius/Bundle/MoneyBundle/Formatter/MoneyFormatterInterface.php
src/Sylius/Bundle/MoneyBundle/Resources/config/services.xml
src/Sylius/Bundle/MoneyBundle/Resources/config/templating.xml
src/Sylius/Bundle/MoneyBundle/Templating/Helper/MoneyHelper.php
src/Sylius/Bundle/MoneyBundle/Templating/Helper/MoneyHelperInterface.php
src/Sylius/Bundle/MoneyBundle/Twig/MoneyExtension.php
src/Sylius/Bundle/MoneyBundle/composer.json
src/Sylius/Bundle/MoneyBundle/spec/Formatter/MoneyFormatterSpec.php
src/Sylius/Bundle/MoneyBundle/spec/Templating/Helper/MoneyHelperSpec.php

[Twig] Currency and Money helpers clean up

---

src/Sylius/Bundle/TaxationBundle/Resources/config/doctrine/model/TaxCategory.orm.xml

There is a bug now where you cannot remove existing tax rates from a tax category instance. It will try to set the tax rates category to `null`. We want to remove the tax rate entirely when it's not connected to a tax category anymore. This PR fixes this.

[Bug Fix] Make sure doctrine removes orphan tax rates

---

src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig

**Enlarge selectbox with ``multiple`` option to make it easier to use**
Before:
After:
**Delete nasty grey line on empty form collection**
Before:
After:

[Ui] Quick form display fixes

---

app/migrations/Version20160420113900.php
src/Sylius/Bundle/ThemeBundle/Configuration/ThemeConfiguration.php
src/Sylius/Bundle/ThemeBundle/Controller/ThemeScreenshotController.php
src/Sylius/Bundle/ThemeBundle/Factory/ThemeScreenshotFactory.php
src/Sylius/Bundle/ThemeBundle/Factory/ThemeScreenshotFactoryInterface.php
src/Sylius/Bundle/ThemeBundle/Hydrator/ThemeHydrator.php
src/Sylius/Bundle/ThemeBundle/Loader/ThemeLoader.php
src/Sylius/Bundle/ThemeBundle/Model/Theme.php
src/Sylius/Bundle/ThemeBundle/Model/ThemeInterface.php
src/Sylius/Bundle/ThemeBundle/Model/ThemeScreenshot.php
src/Sylius/Bundle/ThemeBundle/Resources/config/doctrine/model/Theme.orm.xml
src/Sylius/Bundle/ThemeBundle/Resources/config/services/services.xml
src/Sylius/Bundle/ThemeBundle/Tests/Configuration/ThemeConfigurationTest.php
src/Sylius/Bundle/ThemeBundle/composer.json
src/Sylius/Bundle/ThemeBundle/spec/Controller/ThemeScreenshotControllerSpec.php
src/Sylius/Bundle/ThemeBundle/spec/Factory/ThemeScreenshotFactorySpec.php
src/Sylius/Bundle/ThemeBundle/spec/Fixtures/screenshot/0-amazing.jpg
src/Sylius/Bundle/ThemeBundle/spec/Hydrator/ThemeHydratorSpec.php
src/Sylius/Bundle/ThemeBundle/spec/Loader/ThemeLoaderSpec.php
src/Sylius/Bundle/ThemeBundle/spec/Model/ThemeScreenshotSpec.php
src/Sylius/Bundle/ThemeBundle/spec/Model/ThemeSpec.php

[Theme] Support for screenshots

---

src/Sylius/Bundle/AttributeBundle/Resources/config/services.xml
src/Sylius/Bundle/GridBundle/Resources/config/services.xml
src/Sylius/Bundle/PricingBundle/Resources/config/services.xml
src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
src/Sylius/Bundle/ReportBundle/Resources/config/services.xml
src/Sylius/Bundle/SettingsBundle/Resolver/ResolverServiceRegistry.php
src/Sylius/Bundle/SettingsBundle/Resources/config/services.xml
src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
src/Sylius/Bundle/TaxationBundle/Resources/config/services.xml
src/Sylius/Component/Registry/ExistingServiceException.php
src/Sylius/Component/Registry/NonExistingServiceException.php
src/Sylius/Component/Registry/PrioritizedServiceRegistry.php
src/Sylius/Component/Registry/ServiceRegistry.php
src/Sylius/Component/Registry/spec/ExistingServiceExceptionSpec.php
src/Sylius/Component/Registry/spec/NonExistingServiceExceptionSpec.php
src/Sylius/Component/Registry/spec/ServiceRegistrySpec.php

| Related tickets | #4814 
Added additional argument to the service registry indicating the context in
order to give more helpful exception messages.
So instead of:
```
Service of type "boolean" does not exist.
```
You get:
```
Grid field of type "boolean" does not exist.
```
The context is optional in order to preserve BC (I would personally consider making it mandatory).

[Registry] Added service registry context

---

src/Sylius/Bundle/ProductBundle/Resources/config/driver/doctrine/orm.xml
src/Sylius/Bundle/VariationBundle/Doctrine/ORM/OptionRepository.php
src/Sylius/Component/Variation/Repository/OptionRepositoryInterface.php

[VariationBundle] Added option repository

---

src/Sylius/Component/Registry/ServiceRegistry.php
src/Sylius/Component/Registry/ServiceRegistryInterface.php

[Registry] Update docblocks

---

src/Sylius/Component/Core/Pricing/AbstractCalculator.php
src/Sylius/Component/Core/Pricing/GroupBasedCalculator.php
src/Sylius/Component/Core/Pricing/ZoneBasedCalculator.php

| BC breaks?      | yes, in userland code (`AbstractCalculator::calculate()` made final)

[Core] Refactored AbstractCalculator

---

etc/travis/suites/application/before_install.sh
etc/travis/suites/application/before_script.sh
etc/travis/suites/application/install.sh
etc/travis/suites/application/script/test-behat-without-javascript
etc/travis/suites/common/before_install.sh
etc/travis/suites/common/install.sh
etc/travis/suites/packages/script.sh

[Travis] Bunch of build fixes

---

etc/behat/profiles/default.yml

Running Symfony-based commands inside Behat registers an error handler that mutes fatal errors

[Behat] Do not test "cli" suites by default

---

src/Sylius/Bundle/SettingsBundle/Transformer/ObjectToIdentifierTransformer.php

Q  | A
License | MIT
Doc PR | -
In Phpcr document repository `findOneBy` will look for properties and not document `id` or `path`. So if `ObjectToIdentifierTransformer`'s job is find the object by real document/entity (not user provided) identifier it's more universal to use `find()` method.
Anyway right now `ObjectToIdentifierTransformer` does not work with [Phpcr document repository](https://github.com/doctrine/phpcr-odm/blob/master/lib/Doctrine/ODM/PHPCR/DocumentRepository.php).

[SettingsBundle] Use find() in ObjectToIdentifierTransformer

---

src/Sylius/Bundle/SearchBundle/Listener/ElasticaProductListener.php

Fixes bug where a "product aware" object that has it's product detached (such as an attribute value) throwed an error when updating ES product index.
If you would for example remove an attribute value object from a product and save that product the listener will fail, since the `ProductAttributeValue` has been orphaned (ready to be deleted).

[Bug Fix] Elastica product listener orphaned objects throws error

---

src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
src/Sylius/Bundle/WebBundle/Controller/Frontend/Account/OrderController.php
src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php

Currently used repository methods in `.../Frontend/OrderController` also find carts. That is not a desired behavior since they are used in "My account" section where only placed orders should appear. When a user has a cart the page breaks because carts don't have `number` which is required by order details route.

[Order] Add custom repository methods to obtain only placed orders

---

src/Sylius/Component/Grid/FieldTypes/StringFieldType.php
src/Sylius/Component/Grid/spec/FieldTypes/StringFieldTypeSpec.php

[Grid] Escape values of the string field type

---

.travis.yml

The cache from "application" suite was overwritten and saved as the same from "packages" suite. Joining them all may use more space, but it will be faster (~1min on "application" builds).

[Travis] Improve caching

---

docs/bundles/SyliusArchetypeBundle/installation.rst

VariationBundle and ArchetypeBundle namespaces were wrong

Fixed typo in ArchetypeBundle installation docs

---

features/order/managing_orders/deleting_order.feature
features/product/managing_products/prevent_deletion_of_purchased_product.feature
features/product/managing_products/prevent_deletion_of_purchased_product_variant.feature
features/promotion/managing_promotions/preventing_deletion_of_coupons_in_use.feature
features/promotion/managing_promotions/preventing_deletion_of_promotions_in_use.feature
features/shipping/managing_shipping_methods/preventing_deletion_of_used_shipping_method.feature
src/Sylius/Behat/Context/Setup/OrderContext.php

[Setup][Order] Fixed names of some steps in OrderContext

---

src/Sylius/Bundle/SettingsBundle/Resolver/ResolverServiceRegistry.php
src/Sylius/Bundle/SettingsBundle/Resources/config/services.xml

Schema or resolvers depending on the Doctrine repositories throws an exception about unexisting database during cache warmup.

[Settings] Make schema & resolver registries lazy

---

src/Sylius/Bundle/ResourceBundle/Behat/FixtureContext.php

fix set data to object

---

src/Sylius/Bundle/CoreBundle/Controller/ProductController.php

| Related tickets | --
Exception when product has no image

[Product] fix ProductController::searchAction

---

src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/AbstractDoctrineDriver.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineODMDriver.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineORMDriver.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrinePHPCRDriver.php

Currently the ResourceBundle uses the entity manager named "default" by default - this is wrong as the "default" entity manager can be called anything and it
is only "default" by default.
This PR changes the logic to use the alias of the default manager (e.g. `doctrine.entity_manager`) 
when no object manager name has been explicitly configured.

[ResourceBundle] Use default manager as configured by Doctrine

---

src/Sylius/Behat/Context/Ui/Admin/ManagingProductOptionsContext.php

[Behat][ProductOption] Delete unused parameter in context method

---

src/Sylius/Bundle/AddressingBundle/Form/Type/CountryChoiceType.php
src/Sylius/Bundle/AddressingBundle/Form/Type/ProvinceChoiceType.php
src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneCodeChoiceType.php
src/Sylius/Bundle/AddressingBundle/spec/Form/Type/ZoneCodeChoiceTypeSpec.php
src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeTypeChoiceType.php
src/Sylius/Bundle/AttributeBundle/spec/Form/Type/AttributeTypeChoiceTypeSpec.php
src/Sylius/Bundle/CurrencyBundle/Form/Type/CurrencyCodeChoiceType.php
src/Sylius/Bundle/CurrencyBundle/spec/Form/Type/CurrencyCodeChoiceTypeSpec.php
src/Sylius/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php
src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonChoiceType.php
src/Sylius/Bundle/VariationBundle/Form/Type/OptionValueChoiceType.php
src/Sylius/Bundle/VariationBundle/Form/Type/VariantChoiceType.php

| Related tickets | fixes #4995 
Disable choice_translation_domain on choice form types that do not need translation (e.g. entity names that are translated at source)

Do no translate choice form type values that do not need it

---

src/Sylius/Bundle/GridBundle/Doctrine/ORM/ExpressionBuilder.php
src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/DataSource.php
src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/Driver.php
src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExpressionBuilder.php
src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExpressionVisitor.php
src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExtraComparison.php
src/Sylius/Bundle/GridBundle/Resources/config/driver/doctrine/phpcr-odm.xml
src/Sylius/Bundle/GridBundle/Tests/Doctrine/PHPCRODM/ExpressionVisitorTest.php
src/Sylius/Bundle/GridBundle/Tests/Doctrine/PHPCRODM/QueryBuilderWalker.php
src/Sylius/Bundle/GridBundle/composer.json
src/Sylius/Bundle/GridBundle/phpunit.xml.dist
src/Sylius/Bundle/GridBundle/spec/Doctrine/PHPCRODM/DataSourceSpec.php
src/Sylius/Bundle/GridBundle/spec/Doctrine/PHPCRODM/DriverSpec.php
src/Sylius/Bundle/GridBundle/spec/Doctrine/PHPCRODM/ExpressionBuilderSpec.php

| Deprecations?   | no|yes
This PR would introduce a PHPCR-ODM driver.
The main problem is building the query builder - the PHPCR-ODM query builder uses a [different design](https://gist.github.com/dantleech/298c9618b5889bddeb87) than that of the standard Doctrine Query Builder, which makes building the query more difficult.
In order to solve this this PR uses the Doctrine Commons expresion builder and implements a visitor for that to build the PHPCR-ODM query.
If this approach seems reasonable I will finish this off and add the tests (PHPSpec or PHPUnit?)

[GridBundle] [WIP] PHPCR-ODM Driver

---

src/Sylius/Bundle/VariationBundle/Form/DataTransformer/VariantToCombinationTransformer.php
src/Sylius/Bundle/VariationBundle/spec/Form/DataTransformer/VariantToCombinationTransformerSpec.php

| Related tickets | partially #4791
As described in #4791 - when changes are made on `Option` returned from the transformer, it can have side effects - eg. `Variant` option values will change upon persist
Returning options as array will, remove reference of the persistent collection and no side effects will occur.

[Variation] - return transformed options as array to avoid side-effects

---

etc/travis/suites/docs/script.sh

`-W` turns on error code returning on warnings, but shows only the first one

[Travis] More verbose docs build

---

etc/travis/suites/application/is_suitable.sh
etc/travis/suites/docs/is_suitable.sh
etc/travis/suites/packages/is_suitable.sh

| Related tickets | #5020 
Tests are executing too fast on `master` branch.
Rome wasn't build in a single PR :)

[Travis] Always run full test suite on master branch

---

src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
src/Sylius/Bundle/UserBundle/Resources/config/integration/hwi_oauth.xml
src/Sylius/Bundle/UserBundle/Resources/config/services.xml
src/Sylius/Bundle/UserBundle/composer.json

There's still some room for improvements e.g. the configuration defines `user_oauth` resource, but HWIOAuthBundle isn't required now.

[User] Make HWIOAuthBundle a little bit more optional

---

.travis.yml

| Related tickets | #5020
Since documentation is build only while it was changed, caching, that may cause some serious issues while building (like hiding previous warnings, not regenerating the root toctree), is disabled as it will no longer affect the performance of non-documentation builds.

[Travis] Disable documentation cache

---

src/Sylius/Component/Product/Model/Product.php
src/Sylius/Component/Product/spec/Model/ProductSpec.php

| Related tickets | somehow related to #4980 
Stumbled upon this issue while debugging for ticket https://github.com/Sylius/Sylius/issues/4980, this bug was introduced in 3b35136919e9ede77cb38ea595c78d19ae97668c.

Make sure no master variants are returned in the getAvailableVariants method

---

src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Account/Order/_detail.html.twig

The promotion total was not recursive, and thus incorrect when you had item level promotions.

[WebBundle] Fix account order detail page

---

src/Sylius/Bundle/CoreBundle/Controller/ProductController.php
src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelper.php
src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelperInterface.php
src/Sylius/Bundle/CurrencyBundle/spec/Templating/Helper/CurrencyHelperSpec.php

It crashes when `ext-intl` is not available. Anyway, `false` and `true` does not look like a valid locales :)

[Currency] Do not use booleans as money formatter's locales

---

src/Sylius/Bundle/SearchBundle/DependencyInjection/SyliusSearchExtension.php

If you have two search indexes, eg. 'sylius' and 'site', this patch prevents sylius from loading an event listener for site.product if the product type doesn't exists.   It is not the ideal patch, but at least now you can use multiple FOS indexes.

Allow multiple search indexes

---

etc/travis/suites/application/before_script.sh

Makes debugging easier; especially these ones, that happens during container compilation and only if there's no database.

[Travis] More verbose Symfony setup

---

src/Sylius/Bundle/ResourceBundle/spec/Controller/SingleResourceProviderSpec.php

It should be deeply investigated, why this nasty bug has not been caught by **Travis** build.

[Resource] Fix broken spec in ResourceBundle

---

src/Sylius/Bundle/ResourceBundle/EventListener/AbstractDoctrineSubscriber.php
src/Sylius/Bundle/ResourceBundle/EventListener/ODMMappedSuperClassSubscriber.php
src/Sylius/Bundle/ResourceBundle/EventListener/ODMRepositoryClassSubscriber.php
src/Sylius/Bundle/ResourceBundle/EventListener/ORMMappedSuperClassSubscriber.php
src/Sylius/Bundle/ResourceBundle/EventListener/ORMRepositoryClassSubscriber.php
src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml
src/Sylius/Bundle/ResourceBundle/spec/EventListener/ODMRepositoryClassSubscriberSpec.php
src/Sylius/Bundle/ResourceBundle/spec/EventListener/ORMRepositoryClassSubscriberSpec.php

| Bug fix?      |  yes
| Related tickets | fixes #5040
I've split the `Load*MetadataSubscriber` out into two different subscribers.
`*MappedSuperClassSubscriber`, which should only run on Sylius entities.
`*RepositoryClassSubscriber`, which should run on all entities.
Unfortunately there are no existing specs for mapped super class stuff.

Fix and refactor Load*MetadataSubscriber 

---

src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/RequestConfigurationSpec.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceControllerSpec.php

| Related tickets | fixes #4800 
Fixes errors raised for a new resource with custom template path different than a default one (with colons, e.g. `SyliusAdminBundle:Product`).  
Now the template is being found also under `app/Resources/views` directory.
I've noticed also a `.html` part was lost during one of the last commits in `ResourceController`. That's fixed as well.
All configurations should work now assuming correct twig files in place:
```
sylius_resource:
resources:
app.book:
templates: book/Backend
classes:
model: AppBundle\Entity\Book
app.artist:
templates: AppBundle:artist
classes:
model: AppBundle\Entity\Artist
app.author:
classes:
model: …
```

[ResourceBundle] Fix template not found issue

---

src/Sylius/Component/Cart/Model/Cart.php
src/Sylius/Component/Cart/Model/CartItem.php
src/Sylius/Component/Core/Model/Order.php
src/Sylius/Component/Core/Model/OrderItemUnit.php
src/Sylius/Component/Order/Model/AdjustableInterface.php
src/Sylius/Component/Order/Model/Order.php
src/Sylius/Component/Order/Model/OrderInterface.php
src/Sylius/Component/Order/Model/OrderItem.php
src/Sylius/Component/Order/Model/OrderItemInterface.php
src/Sylius/Component/Order/Model/OrderItemUnit.php
src/Sylius/Component/Order/Model/OrderItemUnitInterface.php
src/Sylius/Component/Order/spec/Model/OrderItemSpec.php
src/Sylius/Component/Order/spec/Model/OrderItemUnitSpec.php
src/Sylius/Component/Order/spec/Model/OrderSpec.php

[Order] Cleanups in Order component

---

docs/bundles/SyliusThemeBundle/important_changes.rst

Command `sylius:assets:install` does not exist when using ThemeBundle in a standalone mode. Thus, `sylius:theme:assets:install` should be used.

[Doc][ThemeBundle] renamed theme assets command

---

features/legacy/frontend/cart_promotions_complex.feature
features/legacy/frontend/cart_promotions_percentage.feature
src/Sylius/Bundle/AdminBundle/Resources/views/Order/_items.html.twig
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Cart/_item.html.twig
src/Sylius/Component/Core/Distributor/ProportionalIntegerDistributor.php
src/Sylius/Component/Core/Distributor/ProportionalIntegerDistributorInterface.php
src/Sylius/Component/Core/Promotion/Action/DiscountAction.php
src/Sylius/Component/Core/Promotion/Action/FixedDiscountAction.php
src/Sylius/Component/Core/Promotion/Action/PercentageDiscountAction.php
src/Sylius/Component/Core/Promotion/Action/ShippingDiscountAction.php
src/Sylius/Component/Core/Promotion/Applicator/UnitsPromotionAdjustmentsApplicator.php
src/Sylius/Component/Core/Promotion/Applicator/UnitsPromotionAdjustmentsApplicatorInterface.php
src/Sylius/Component/Core/spec/Distributor/ProportionalIntegerDistributorSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/FixedDiscountActionSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/PercentageDiscountActionSpec.php
src/Sylius/Component/Core/spec/Promotion/Applicator/UnitsPromotionAdjustmentsApplicatorSpec.php
src/Sylius/Component/Order/Factory/AdjustmentFactory.php
src/Sylius/Component/Order/Factory/AdjustmentFactoryInterface.php

To fulfill new order units approach, we should distribute promotions into units not only in ``item`` promotions, but also in those applied on ``Order`` level. Therefore, in ``fixed_discount`` and ``percentage_discount`` promotions, ``order_promotion`` adjustments are added on order units (while applying percentage discount distribution is equal, while applying fixed discount - promotion amount is distributed on order's items proportionally and then equally on units).

[Core][Promotion] Distribute promotions on units

---

src/Sylius/Component/Core/Metadata/HierarchyProvider/ProductHierarchyProvider.php
src/Sylius/Component/Core/spec/Metadata/HierarchyProvider/ProductHierarchyProviderSpec.php

| Related tickets | fixes #4483 
Allows you to define and use product metadata at any level of the Archetype hierarchy.

[Metadata] Add hierarchical archetype support to Product Metadata

---

src/Sylius/Component/Core/Metadata/HierarchyProvider/ProductVariantHierarchyProvider.php
src/Sylius/Component/Core/spec/Metadata/HierarchyProvider/ProductVariantHierarchyProviderSpec.php

The same as #5069, but for ProductVariant - keeping them consistent.
Could consider injecting the Product in here and using that at some point in future to stop the duplication but this should be fine for now.

[Metadata] Add hierarchical archetype support to ProductVariant Metadata

---

src/Sylius/Component/Promotion/Generator/CouponGenerator.php

| Related tickets | mentioned in [comment](https://github.com/Sylius/Sylius/pull/3339/files#r64144189)

Coupon generation fix

---

src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
src/Sylius/Bundle/ResourceBundle/Controller/StateMachine.php
src/Sylius/Bundle/ResourceBundle/Controller/StateMachineInterface.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDriver.php
src/Sylius/Bundle/ResourceBundle/Resources/config/controller.xml
src/Sylius/Bundle/ResourceBundle/composer.json
src/Sylius/Bundle/ResourceBundle/spec/Controller/RequestConfigurationSpec.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceControllerSpec.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/StateMachineSpec.php
src/Sylius/Bundle/ResourceBundle/test/app/AppKernel.php
src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/DefaultTestCase/bundles.php
src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/inventory.yml
src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/payment.yml
src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/product_review.yml
src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/shipment.yml

Summary:
* Renamed ``updateStateAction`` to ``applyStateMachineTransitionAction`` in ResourceController;
* Extracted logic to separate service;
* Reimplemented the action from scratch BDD wayyy;
* Added ability to execute transition during updateAction :tada: 
The most important is the last point. Use cases:
Any action that needs to edit something on the resource and apply transition. Simplest example: shipping a shipment. We want to specify tracking code and apply "ship" transition - doable with routing configuration alone now.
More crazy use-case: simplified checkout process. Our …

[ResourceBundle] Allow applying transition when updating resources

---

features/account/customer_account/changing_password.feature
features/account/customer_account/changing_password_validation.feature
features/account/customer_account/customer_profile_validation.feature
features/account/customer_account/editing_customer_profile.feature
src/Sylius/Behat/Context/Setup/CustomerContext.php
src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
src/Sylius/Behat/Page/Shop/Account/ChangePasswordPage.php
src/Sylius/Behat/Page/Shop/Account/ChangePasswordPageInterface.php
src/Sylius/Behat/Page/Shop/Account/DashboardPage.php
src/Sylius/Behat/Page/Shop/Account/ProfileUpdatePage.php
src/Sylius/Behat/Resources/config/services/contexts/ui.xml
src/Sylius/Behat/Resources/config/services/pages/shop/account.xml
src/Sylius/Bundle/ShopBundle/Resources/config/routing/account.yml
src/Sylius/Bundle/ShopBundle/Resources/views/Account/changePassword.html.twig
src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/UserBundle/Controller/UserController.php
src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/UserBundle/Form/Type/UserChangePasswordType.php
src/Sylius/Bundle/UserBundle/Resources/config/services.xml
src/Sylius/Bundle/UserBundle/spec/Form/Type/UserChangePasswordTypeSpec.php
src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml

[Shop][Account] Changing customer password

---

src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadCurrencyData.php

While loading fixtures (without *Sylius* installation) none of currencies has been set as **base**, which led to some nasty bugs like this one:

[Fixture] Set EUR as base currency in fixtures

---

src/Sylius/Bundle/CoreBundle/Form/Type/LegacyProductType.php
src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonChoiceType.php
src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php

Taxon choice list is badly sorted by id.
To keep tree consistent I've made this PR
**My taxon list**
**Before PR**
**After PR**
I've also enlarge the choice list height on product page, it's more readable whan you have a lot of taxons
Enjoy ;)

[TaxonomyBundle] Fix display bug in choice list and enlarge area

---

src/Sylius/Component/Rbac/Authorization/CachedPermissionMap.php
src/Sylius/Component/Rbac/spec/Authorization/CachedPermissionMapSpec.php

Most caching uses prefixes for namespacing, you can see below before this is applied how you can't easily identify the RBAC role cache keys in my redis example (87, 91, 96):
```
86) "sylius[nodes:_/cms/routes/shop/mediache/resolve/product/244984/rc,_default][1]"
87) "sylius[reiss_offline_marketer][18]"
88) "sylius[workspace:_default][7]"
89) "sylius[nodes:_/cms/routes/shop/mediache/resolve/product/237852/rc/2,_default][1]"
90) "sylius[nodes:_/cms/routes/ui/prod/js,_default][7]"
91) "sylius[reiss_super_admin][18]"
92) "sylius[nodes:_/cms/routes/shop/mediache/resolve/product/222392,_default][1]"
93) "sylius[nodes:_/cms/routes/dresses,_default][7]"
94) …
```

[RBAC] Use a cache-key prefix for improved namespacing

---

src/Sylius/Bundle/GridBundle/Renderer/TwigGridRenderer.php

When filtering by entities, we get the ids, not objects, so passing the criteria as data was not enough to preselect values properly.

[Grid] Submit the data to fill the form properly

---

UPGRADE.md
features/order/managing_orders/seeing_order_item_detailed_data.feature
src/Sylius/Behat/Context/Setup/PromotionContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
src/Sylius/Behat/Page/Admin/Order/ShowPage.php
src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_item.html.twig
src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_summary.html.twig
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Component/Core/Factory/ActionFactory.php
src/Sylius/Component/Core/Factory/ActionFactoryInterface.php
src/Sylius/Component/Core/Model/AdjustmentInterface.php
src/Sylius/Component/Core/Model/OrderItem.php
src/Sylius/Component/Core/Model/OrderItemInterface.php
src/Sylius/Component/Core/Promotion/Action/UnitDiscountAction.php
src/Sylius/Component/Core/Promotion/Action/UnitFixedDiscountAction.php
src/Sylius/Component/Core/Promotion/Action/UnitPercentageDiscountAction.php
src/Sylius/Component/Core/Remover/AdjustmentsRemover.php
src/Sylius/Component/Core/spec/Factory/ActionFactorySpec.php
src/Sylius/Component/Core/spec/Model/OrderItemSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/UnitFixedDiscountActionSpec.php
src/Sylius/Component/Core/spec/Promotion/Action/UnitPercentageDiscountActionSpec.php
src/Sylius/Component/Core/spec/Remover/AdjustmentsRemoverSpec.php
src/Sylius/Component/Order/Model/OrderItemUnitInterface.php

- changed ``item promotions`` to ``unit promotions`` as they're applied on unit level
- changed ``UnitPercentageDiscountAction`` to count discount on unit level, rather than on item
- implement ``getDiscountedUnitPrice`` method on ``OrderItem``, which consist of unit price lowered by ``ORDER_UNIT_PROMOTION``s on one unit

[Promotion][Core] Discounted unit price feature

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/parameters.yml

| Related tickets | #5058 
The parameters where moved to Core [in this commit](https://github.com/Sylius/Sylius/commit/03ca4609da4d33c4d18693f6d500967b7810dada), but were skipped during configuration changes in #5058. You can't move through the checkout without this parameter.

[Core] Add missing configuration parameters

---

features/product/managing_product_attributes/adding_checkbox_product_attribute.feature
features/product/managing_product_attributes/adding_integer_product_attribute.feature
features/product/managing_product_attributes/adding_percent_product_attribute.feature
features/product/managing_product_attributes/adding_text_product_attribute.feature
features/product/managing_product_attributes/adding_textarea_product_attribute.feature
features/product/managing_product_attributes/edit_text_product_attribute.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingProductAttributesContext.php
src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
src/Sylius/Behat/Page/Admin/Crud/IndexPageInterface.php
src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_attribute.yml

Currently, all created in new *Admin* attributes had ``text`` type.

[Behat][Admin] Fix attributes creation on new admin

---

src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig

Using twig form type rendering we couldn't overwrite the class of Choice Types' rows. Now it will append the class.

[UiBundle] Fix choice type hardcoded class

---

src/Sylius/Bundle/ResourceBundle/EventListener/ResourceDeleteSubscriber.php

500 is totally wrong. 409 seems to make the most sense to me.  
https://httpstatuses.com/409

[Resource] use a more appropriate response code on foreign key constraint violation exception

---

src/Sylius/Bundle/TaxonomyBundle/composer.json

TaxonRepository need Webmozart assertion on findChildrenByRootCode method. This PR adds the dependency on composer.json for sylius/taxonomy-bundle

[TaxonomyBundle] adding webmozart/assert on composer.json in sylius/taxonomy-bundle

---

features/legacy/user/users.feature
features/user/managing_customers/adding_customer.feature
features/user/managing_customers/adding_customer_account.feature
features/user/managing_customers/customer_unique_email_validation.feature
features/user/managing_customers/customer_validation.feature
features/user/managing_customers/editing_customer.feature
src/Sylius/Behat/Context/Setup/CustomerContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/UserBundle/Resources/config/validation.xml
tests/Responses/Expected/customer/create_validation_fail_response.json
tests/Responses/Expected/customer/create_with_user_validation_fail_response.json
tests/Responses/Expected/customer/update_validation_fail_response.json

**The issue:**
The `CustomerType` should allow for empty first and last name since we can have customers without first or last name e.g. guest customers. When enforcing first and last name to be always filled we can't edit customers that didn't specify these values.
**What has been done:**
**Notice**
`CurrentPageResolver` should be used in `ManagingCustomersContext` to ensure we always operate on a correct page.

[User] Customer validation fix

---

src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceControllerSpec.php

| BC breaks?      | no?
When updating resources, either 200 `OK` or 204 `No Content` can be returned. But we were mixing them, returning content with 204.

[Resource] Updating resources response code

---

src/Sylius/Bundle/SettingsBundle/composer.json

looks like caching support was removed in a refactor.

remove unused doctrine/doctrine-cache-bundle

---

src/Sylius/Bundle/ChannelBundle/Resources/views/FakeChannelCollector/layout.html.twig
src/Sylius/Bundle/CoreBundle/DataCollector/SyliusDataCollector.php
src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
src/Sylius/Bundle/CoreBundle/Resources/config/context.xml
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/Resources/views/Collector/sylius.html.twig
src/Sylius/Component/Core/Context/ShopperContext.php
src/Sylius/Component/Core/Context/ShopperContextInterface.php
src/Sylius/Component/Core/spec/Context/ShopperContextSpec.php

All services, form types, etc. should be stateless, but sometimes we need to have access (in routing, or other contexts) to currently active channel, currency, locale and customer. This service simplifies this and I have also added this info to the web debug toolbar. So as a developer, you can always check the currently selected context.
This is the first step to clean up all the contexts together and unify their behavior and usage.

[Core] Implement simple ShopperContext

---

src/Sylius/Bundle/ThemeBundle/Translation/Provider/TranslatorResourceProvider.php

`$resources` is an array, but it defaults to NULL.
If no resources are available, an `array_merge` action is later performed and an error occurs.
This PR changes the default to an empty array.

Default to empty array on translator resource provider

---

src/Sylius/Component/Core/Model/Product.php

| Related tickets | relates to #3773

Use getRoot on taxons (replacing the remove getTaxonomy)

---

src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/RequestConfigurationSpec.php

Default redirect route parameters are useful, but sometimes can lead to errors (for example with ``isOpen()`` method on *Behat* ``Page``) and it should be possible to define them as empty array.

[Resource] Allow to redirect to route without default query parameters

---

src/Sylius/Bundle/WebBundle/Resources/views/Backend/Shipment/show.html.twig

Accessing administration/shipments/{shipmentId} currently triggers an exception :
Neither the property "sku" nor one of the methods "sku()", "getsku()"/"issku()" or "__call()" exist and have public access in class "Proxies\__CG__\Sylius\Component\Core\Model\ProductVariant" in SyliusWebBundle:Backend/Shipment:show.html.twig at line 113

[WebBundle] Fix SKU Refactoring

---

features/shipping/managing_shipping_methods/adding_shipping_method.feature
src/Sylius/Behat/Context/Ui/Admin/ManagingShippingMethodsContext.php
src/Sylius/Behat/Page/Admin/ShippingMethod/CreatePage.php
src/Sylius/Behat/Page/Admin/ShippingMethod/CreatePageInterface.php
src/Sylius/Bundle/AdminBundle/Resources/views/ShippingMethod/_form.html.twig
src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodTranslationType.php
src/Sylius/Bundle/ShippingBundle/Resources/config/doctrine/model/ShippingMethodTranslation.orm.xml
src/Sylius/Bundle/ShippingBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/ShippingBundle/spec/Form/Type/ShippingMethodTranslationTypeSpec.php
src/Sylius/Component/Shipping/Model/ShippingMethod.php
src/Sylius/Component/Shipping/Model/ShippingMethodTranslation.php
src/Sylius/Component/Shipping/Model/ShippingMethodTranslationInterface.php
src/Sylius/Component/Shipping/spec/Model/ShippingMethodSpec.php
src/Sylius/Component/Shipping/spec/Model/ShippingMethodTranslationSpec.php

While working on https://github.com/Sylius/Sylius/pull/5220, we've come up with an idea, that it would be nice to have translatable description on ``ShippingMethod`` (as, for example, on ``PaymentMethod``).

[Shipping] Add translatable description to ShippingMethod

---

src/Sylius/Bundle/AdminBundle/Resources/views/Product/Attribute/attributesCollection.html.twig

Confirmed for textarea and checkbox attribute types. For the proper fix the JS code should be improved.

[Admin] Quick fix for deleting attributes 

---

src/Sylius/Bundle/SettingsBundle/Resources/config/doctrine/model/Settings.orm.xml

| BC breaks?      |yes
I'm overriding this in my own app, because:
1. json is easily manually manipulated in the db directly. serialized data is not. (not recommended i know, but a use case nonetheless) 
2. json is easily query-able by RDBMS engines that support json natively, i.e postgres and mysql 5.7.
Opening it up here for RFC to see if it might be thought useful.

[RFC] [Settings] Change Settings parameters type to json_array

---

README.md
docs/book/installation.rst
etc/travis/suites/application/before_script.sh
package.json

It is not always suitable to install a gulp globally. If it is not installed globally, the following command had to be called:
```bash
$ ./node_modules/.bin/gulp
```
This change allows to use more developer friendly command:
```bash
$ npm run gulp
```

[JS] Run gulp script

---

package.json

Proper version in package.json file

[JS] Upgrade a npm package version

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/parameters.yml
src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php

[Core] Cleanup inventory and guest order paramaters

---

docs/bundles/SyliusFixturesBundle/architecture.rst
docs/bundles/SyliusFixturesBundle/builtin_listeners.rst
docs/bundles/SyliusFixturesBundle/commands.rst
docs/bundles/SyliusFixturesBundle/custom_fixture.rst
docs/bundles/SyliusFixturesBundle/custom_listener.rst
docs/bundles/SyliusFixturesBundle/index.rst
docs/bundles/SyliusFixturesBundle/installation.rst
docs/bundles/SyliusFixturesBundle/summary.rst
docs/bundles/index.rst
docs/bundles/map.rst.inc

| Related tickets | bundle introduced in #5219, core fixtures in #5285

[Documentation] Fixtures bundle

---

src/Sylius/Component/Attribute/Model/AttributeValue.php

| BC breaks?      | yes (uses setter method, changes visibility)
`AttributeValue` is currently using getter to get the value and does not use setter to set the value. 
Moreover, it changes visibility of `get%type%()` methods from public to protected and their properties from protected to private (all modifications should be done through setter methods).

[Attrbiute] Use value setter & fix properties visibility

---

app/migrations/Version20160516131553.php

Introduced by @lchrusciel in PR #4947 
Same problem as PR #4688 
This is to prevent migration fails due to the UNIQUE INDEX statement.

[Migration] Auto-generate product code in db field while running doctrine

---

src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/order.yml
src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/product.yml
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/history.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/history.html.twig
src/Sylius/Bundle/WebBundle/Resources/views/Backend/_history_table.html.twig

| Related tickets | fixes #5320
Remove revert and restore actions of products and orders.
I do not remove sylius.ui.revert in translations.*.yml

[Product][Order] Remove Revert and Restore action

---

src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductVariant/generate.html.twig

| Related tickets | fixes #5325
Just add form error for class constraint in product variant generation

[WebBundle][ProductVariant] Add form errors for class constraints

---

src/Sylius/Bundle/FixturesBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/ConfigurationTest.php

[Fixtures] Allow options to be an array only

---

src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
src/Sylius/Bundle/ResourceBundle/Controller/StateMachine.php
src/Sylius/Bundle/ResourceBundle/Controller/StateMachineInterface.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceControllerSpec.php
src/Sylius/Bundle/ResourceBundle/spec/Controller/StateMachineSpec.php

At the moment, the `applyStateMachineTransitionAction` endpoint will throw a `500` Internal Server Error if a transition cannot be applied. This isn't very nice at all.
Propose returning a `400` Bad Request instead.

[Resource] gracefully handle state machine transitions that cannot be applied

---

src/Sylius/Bundle/AdminBundle/Resources/views/Customer/_form.html.twig

[Admin][Customer] Remove unused toggle on update action

---

src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCurrenciesContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentMethodsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingProductAttributesContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingProductOptionsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingShippingMethodsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxCategoriesContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxRateContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
src/Sylius/Behat/Context/Ui/Admin/ManagingZonesContext.php
src/Sylius/Behat/Page/Admin/Country/UpdatePage.php
src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
src/Sylius/Behat/Page/Admin/Crud/CreatePageInterface.php
src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
src/Sylius/Behat/Page/Admin/Crud/UpdatePageInterface.php

There are assertions like:
```php
Assert::true(
$this->updatePage->checkValidationMessageFor('code', 'This code is already in use.'),
'Unique code violation message should appear on page, but it does not.'
);
```
We are getting "Unique code violation message should appear on page, but it does not." when the validation message differs from "This code is already in use.". If the validation message gets changed, we will get an exception, that there is no unique code violation on the page, but there will be.
I've changed it to:
```php
Assert::same($this->updatePage->getValidationMessage('code'), 'This code is already in use.');
``` …

[Behat] Refactor checkValidationMessageFor to getValidationMessage

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine.yml
src/Sylius/Bundle/OrderBundle/Resources/config/app/state_machine.yml

| Related tickets | #5274
After changes in https://github.com/Sylius/Sylius/pull/5274 the inventory is not updated after payment is completed. This PR fixes that and temporary removes "pending" state as it is currently not used anymore. The whole state machine will be reworked soon (see https://github.com/Sylius/Sylius/issues/4060).

[Core] Fix Order's state machine

---

src/Sylius/Bundle/CoreBundle/DataCollector/SyliusDataCollector.php
src/Sylius/Bundle/CoreBundle/Resources/views/Collector/sylius.html.twig

Built-in server can't be run on `dev` environment if channel was not found.

[CRITICAL] Prevent SyliusDataCollector from breaking the whole app if channel cannot be found

---

src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
src/Sylius/Bundle/PayumBundle/DependencyInjection/SyliusPayumExtension.php

[Core][Payment] Populate gateway choices based on payum configuration

---

docs/customization/model.rst

[Documentation] Customization Guide: Models - fix

---

features/account/customer_account/viewing_orders_history/viewing_only_my_orders.feature
features/account/customer_account/viewing_orders_history/viewing_order.feature
features/account/customer_account/viewing_orders_history/viewing_order_items.feature
features/account/customer_account/viewing_orders_history/viewing_orders.feature
features/order/managing_orders/browsing_orders.feature
features/order/managing_orders/cancelling_order.feature
features/order/managing_orders/deleting_order.feature
features/order/managing_orders/finalizing_order_payment.feature
features/order/managing_orders/seeing_order.feature
features/order/managing_orders/seeing_order_aggregated_discounts.feature
features/order/managing_orders/seeing_order_discounts.feature
features/order/managing_orders/seeing_order_with_items.feature
features/order/managing_orders/shipping_order.feature
features/product/managing_product_variants/prevent_deletion_of_purchased_product_variant.feature
features/product/managing_products/prevent_deletion_of_purchased_product.feature
features/promotion/managing_coupons/preventing_deletion_of_coupons_in_use.feature
features/promotion/managing_promotions/preventing_deletion_of_promotions_in_use.feature
features/shipping/managing_shipping_methods/preventing_deletion_of_used_shipping_method.feature
src/Sylius/Behat/Context/Setup/OrderContext.php
src/Sylius/Behat/Resources/config/services/contexts/setup.xml

[Behat] Add state transitions to creating orders programmatically

---

src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/macros.html.twig

When you define a channel color in the backend order list we need add a right space:
```
<spanstyle="color: Green;">default</span>
```

Remove right trim in order list

---

src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/macros.html.twig

I found that implementation confusing, so there's the one without usage of `{%-` or `-%}`.

[Web] Refactor space trim in Order macro

---

src/Sylius/Bundle/ResourceBundle/Command/DebugResourceCommand.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php
src/Sylius/Bundle/ResourceBundle/Resources/config/console.xml
src/Sylius/Bundle/ResourceBundle/Tests/Command/DebugResourceCommandTest.php
src/Sylius/Component/Resource/Metadata/Metadata.php
src/Sylius/Component/Resource/Metadata/MetadataInterface.php

| Related tickets | fixes #5191
This PR adds a command to debug resources:
```bash
~/w/s/sylius ❯❯❯ ./app/console sylius:debug:resource
Select a resource to debug: 
[0 ] sylius.order
[1 ] sylius.order_item
[2 ] sylius.order_item_unit
...
[84] sylius.api_refresh_token
[85] sylius.api_auth_code
[86] sylius.payment_security_token
[87] sylius.gateway_config
> 42
+--------------------+------------------------------------------------------------+
| name               | promotion                                                  |
| application        | sylius                                                     |
| driver             | doctrine/orm …
```

Added resource debug command

---

docs/bundles/SyliusResourceBundle/installation.rst

``winzouStateMachineBundle`` is also required, as ``ResourceController`` depends on ``sm.factory`` service.

[Docs] Added missing bundle in SyliusResourceBundle installation docs

---

src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php

When run sylius:install step 3 fails because tax_calculation_strategy is null.
Step 1: It appears that your database already exists. Would you like to reset it? (y/N) y
Step 2: Load sample data? (y/N) N
Step 3: fails because tax_calculation_strategy is null

fix SetupCommand 'tax_calculation_strategy' should not be null

---

src/Sylius/Bundle/ChannelBundle/Collector/ChannelCollector.php

Right now, it always has `null` as channel.

Fix showing channel in the collector

---

src/Sylius/Bundle/CoreBundle/Context/CurrencyContext.php
src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
src/Sylius/Bundle/CoreBundle/spec/Context/CurrencyContextSpec.php
src/Sylius/Component/Currency/Context/CurrencyContext.php
src/Sylius/Component/Currency/Context/CurrencyContextInterface.php
src/Sylius/Component/Currency/spec/Context/CurrencyContextSpec.php

BC breaks:
- currency contexts made final
- core currency context no longer extends the one from component
- constant `STORAGE_KEY` removed from the interface
- default currency is taken from the `%currency%` parameter, not from the settings

Make CurrencyContext work correctly without channel

---

src/Sylius/Bundle/GridBundle/DependencyInjection/Configuration.php
src/Sylius/Bundle/ResourceBundle/DependencyInjection/Configuration.php

Updated driver detection to work with Windows file paths, which have "\" instead of "/".

Windows path compatibility:
