- features/backend/users.feature
- src/Sylius/Bundle/CoreBundle/Controller/OrderController.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/UserRepository.php
- src/Sylius/Bundle/WebBundle/Behat/WebContext.php
> [Core] Fixed #2286 accessing deleted user details page

- src/Sylius/Bundle/InstallerBundle/Command/InstallCommand.php
|Q            |A  |
|---          |---|
|Bug Fix?     |n  |
|New Feature? |n  |
|BC Breaks?   |n  |
|Deprecations?|n  |
|Tests Pass?  |n  |
|Fixed Tickets|   |
|License      |MIT|
|Doc PR       |   |
Sent using [Gush](https://github.com/gushphp/gush)
> add cache:clear for second pass to avoid error from cmf

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
> Enabled softdeleteable filter at the end of "findForDetailsPage" method

- src/Sylius/Bundle/SearchBundle/Indexer/OrmIndexer.php
OrmIndexer isObjectIndexable was not checking the correct engine configuration
> Update OrmIndexer with correct indexable case

- src/Sylius/Bundle/VariationBundle/Form/Type/OptionType.php
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductOption/_form.html.twig
> [VariationBundle] The collection form type uses the new CollectionExtension

- features/backend/orders.feature
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/WebBundle/Behat/WebContext.php
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/macros.html.twig
> Sorting order by name

- src/Sylius/Bundle/ContentBundle/Form/Type/MenuType.php
- src/Sylius/Bundle/ContentBundle/Form/Type/SlideshowBlockType.php
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Content/Block/Slideshow/_form.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Content/Menu/_form.html.twig
I need to find a way to customize the macro which render the form...
> [CMFBundle] Some forms do not use the CollectionExtension

- src/Sylius/Component/Core/Promotion/Checker/PromotionEligibilityChecker.php
- src/Sylius/Component/Core/spec/Promotion/Checker/PromotionEligibilityCheckerSpec.php
Also added another test and tweek to the per_user_usage_limit on promotions
that allows guest checkouts as well as restricting coupon usage per user
> The namespace for a spec was incorrect and thus the spec was never run.

- src/Sylius/Bundle/InstallerBundle/Requirement/ExtensionsRequirements.php
- src/Sylius/Bundle/InstallerBundle/Resources/translations/requirements.en.yml
The installer passes normally but then errors during cache clear.
>  EXIF requirement for imagine >1.0.4

- src/Sylius/Bundle/TranslationBundle/composer.json
| BC breaks?    |  no
| Deprecations? |  no
> Translation bundle composer.json fixed

- src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
| Fixed tickets | []
| Doc PR        | [The reference to the documentation PR if any]
> Duplicated setFirstname & setLastname 

- src/Sylius/Component/Product/Accessor/ProductAccessor.php
> [Product] fixed attributes comparison

- composer.json
| Q                     | A
| ------------------- | ---
| Bug fix?           | yes
| BC breaks?     | no
| Fixed tickets    | 2425
| License            | MIT
| Doc PR            |
> Fixing dependency crash #2425

- src/Sylius/Bundle/TranslationBundle/.travis.yml
- src/Sylius/Bundle/TranslationBundle/CHANGELOG.md
- src/Sylius/Bundle/TranslationBundle/DependencyInjection/AbstractTranslationExtension.php
- src/Sylius/Bundle/TranslationBundle/DependencyInjection/Compiler/TranslationListenerPass.php
- src/Sylius/Bundle/TranslationBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/TranslationBundle/EventListener/LocaleListener.php
- src/Sylius/Bundle/TranslationBundle/EventListener/TranslatableListener.php
- src/Sylius/Bundle/TranslationBundle/README.md
- src/Sylius/Bundle/TranslationBundle/SyliusTranslationBundle.php
- src/Sylius/Bundle/TranslationBundle/composer.json
- src/Sylius/Bundle/TranslationBundle/phpspec.yml
> Translation bundle enhancements

- src/Sylius/Component/Core/composer.json
> [Core] Fixed typo in composer.json file for variation component

- src/Sylius/Bundle/CoreBundle/EventListener/UserUpdateListener.php
> Fix user password editing in the backend

- src/Sylius/Bundle/ApiBundle/Model/Client.php
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/taxon.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.Taxon.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.Taxonomy.yml
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php
- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
> Correct serializer for taxons and taxonomies, add ROLE_API to admins

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadApiData.php
> Create demo oauth client fixtures

- src/Sylius/Component/Report/composer.json
Just one really simple change, hope this wonderful PR table is unnecessary this time ;)
> Fixed report component composer.json for packagist.

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/checkout.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/country.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/order_item.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/payment.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/payment_method.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_archetype.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_attribute.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_option.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/promotion.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/promotion_coupon.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/shipment.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/shipping_category.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/shipping_method.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/tax_category.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/tax_rate.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/taxon.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/taxonomy.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/user.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/zone.yml
Limit parameter changes now the pagination limit.
> Few api routing corrections

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/payment.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/shipment.yml
Add filterability to payments and shipments for api requests
> Add filterability to payments and shipments api requests

- src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/DoctrineODMDriver.php
- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/MongoDB/TranslatableDocumentRepository.php
- src/Sylius/Bundle/ResourceBundle/spec/Doctrine/ODM/MongoDB/TranslatableDocumentRepositorySpec.php
- src/Sylius/Bundle/ResourceBundle/spec/Fixture/Document/Foo.php
- src/Sylius/Bundle/ResourceBundle/spec/Fixture/Document/FooInterface.php
- src/Sylius/Bundle/ResourceBundle/spec/Fixture/Document/TranslatableFoo.php
- src/Sylius/Bundle/TranslationBundle/DependencyInjection/Compiler/TranslationListenerPass.php
- src/Sylius/Bundle/TranslationBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/TranslationBundle/DependencyInjection/SyliusTranslationExtension.php
- src/Sylius/Bundle/TranslationBundle/EventListener/LocaleListener.php
- src/Sylius/Bundle/TranslationBundle/EventListener/ODMTranslatableListener.php
- src/Sylius/Bundle/TranslationBundle/EventListener/TranslatableListener.php
- src/Sylius/Bundle/TranslationBundle/EventListener/TranslatableListenerInterface.php
- src/Sylius/Bundle/TranslationBundle/Resources/config/services.xml
- src/Sylius/Bundle/TranslationBundle/SyliusTranslationBundle.php
Added support for mongodb document translation, setting the translations as embedded document.
> added MongoDB Translation support

- app/config/config.yml
> Fix Doctrine Migrations issue #2465

- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/_navbar.html.twig
Hi.
Replace hardcoded string in the backend
> [WebBundle] Fix missing translation string

- src/Sylius/Bundle/InstallerBundle/Requirement/ExtensionsRequirements.php
> [InstallerBundle] Replace class check with extension check

- src/Sylius/Component/Payment/spec/Model/CreditCardSpec.php
> [Payment] small typo fix

- src/Sylius/Bundle/PayumBundle/Payum/Be2bill/Action/NotifyAction.php
- src/Sylius/Bundle/PayumBundle/Payum/Paypal/Action/NotifyOrderAction.php
- src/Sylius/Bundle/PayumBundle/Resources/config/services.xml
- src/Sylius/Bundle/PayumBundle/spec/Payum/Paypal/Action/NotifyOrderActionSpec.php
| Fixed tickets | None
| Doc PR        | None
> Remove un-used EventDispatcher

- src/Sylius/Bundle/ResourceBundle/AbstractResourceBundle.php
- src/Sylius/Bundle/ResourceBundle/ResourceBundleInterface.php
> [ResourceBundle] AbstractResourceBundle::build has been reworked

- src/Sylius/Component/Archetype/Model/ArchetypeInterface.php
- src/Sylius/Component/Attribute/Model/AttributeInterface.php
- src/Sylius/Component/Variation/Model/OptionInterface.php
to:
archetype interface
attribute interface
option interface
| BC breaks?    | [yes]
> Add id getter

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/Form/_main.html.twig
> [Product] Return SKU field for editing and creating products

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/Form/_main.html.twig
Changed order of SKU field.
Did it wrong in first time.
> [Product] Change order of SKU field for editing and creating products

- src/Sylius/Bundle/ResourceBundle/ResourceBundleInterface.php
> bug fix #2504

- src/Sylius/Bundle/AddressingBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ApiBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/AttributeBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ContactBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ContentBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/CurrencyBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/InventoryBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/LocaleBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/MailerBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/PaymentBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/PayumBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/RbacBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ReportBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/SequenceBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/SettingsBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ShippingBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/TaxationBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/TaxonomyBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/VariationBundle/DependencyInjection/Configuration.php
> Set default driver in bundle configuration

- src/Sylius/Bundle/SettingsBundle/Manager/SettingsManager.php
Right now if you have settings with transformed parameters which you modify, save and then try to use straight away it, SettingsManager::loadSettings will return non transformed version of parameters.
> Fixing bug with transformed parameters stored internally in non transformed state after settings were saved

- src/Sylius/Bundle/WebBundle/Menu/BackendMenuBuilder.php
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ApiClient/update.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ContactRequest/create.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ContactRequest/index.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ContactRequest/show.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ContactRequest/update.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ContactTopic/create.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ContactTopic/index.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ContactTopic/update.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Email/create.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Email/index.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Email/update.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Locale/update.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Permission/create.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Permission/index.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Permission/update.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Promotion/create.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Promotion/index.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Promotion/update.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Role/create.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Role/index.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Role/update.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ShippingCategory/update.html.twig
Hi,
Title is enough to describe this PR ;)
Replaced icons
> [WebBundle] Fix wrong breadcrumbs, add translation and change icons

- src/Sylius/Bundle/ContentBundle/Form/Type/StringBlockType.php
- src/Sylius/Bundle/ContentBundle/Resources/config/validation.xml
- src/Sylius/Bundle/ContentBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Content/Block/String/_form.html.twig
Hi,
Fix various bug in displaying and saving imagine and string blocks.
> [ContentBundle] Fix string block and imagine form bugs

- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonTranslationType.php
- src/Sylius/Bundle/TaxonomyBundle/spec/Form/Type/TaxonTranslationTypeSpec.php
> Change taxon description field to a textarea

- src/Sylius/Bundle/RbacBundle/Command/InitializeCommand.php
Without this change it will end i.e. with error:
```
Notice: undefined index sylius.manage.user
> [RbacBundle] Prevent fatal errors when calling initialize more than once

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php
- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
- src/Sylius/Bundle/RbacBundle/Command/InitializeCommand.php
- src/Sylius/Bundle/RbacBundle/Doctrine/RbacInitializer.php
- src/Sylius/Bundle/RbacBundle/Resources/config/services.xml
> Refactor Sylius RBAC initialize code to allow calling it in fixtures

- src/Sylius/Bundle/RbacBundle/Resources/config/services.xml
> [RbacBundle] Fix stupid typo

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php
> [FixturesBundle] Faker not always generates unique results

- src/Sylius/Bundle/RbacBundle/Doctrine/RbacInitializer.php
n/c how stupid I'm without coffee...
> [RbacBundle] Fix even more stupid copy&paste typo

- src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php
> [CoreBundle] OAuth provider should call parent class

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php
> [FixturesBundle] Correct check for uniqueness when loading users data

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/_history_table.html.twig
And deal with it instead of trying to display an array.
> Check if history value is an array

- src/Sylius/Bundle/LocaleBundle/composer.json
| Fixed tickets | #2594
Composer.json was missing a2lix/translation-form-bundle
> [LocaleBundle][composer] Add missing dependency

- src/Sylius/Component/Core/OrderProcessing/ShipmentFactory.php
- src/Sylius/Component/Core/spec/OrderProcessing/ShipmentFactorySpec.php
I just didn't like comparing like `if (!$shipment)`.
> Minor shipment factory update

- src/Sylius/Bundle/CoreBundle/EventListener/PurchaseListener.php
> Add canceled case in PurchaseListener

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/CoreBundle/Settings/SecuritySettingsSchema.php
- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
- src/Sylius/Bundle/ResourceBundle/composer.json
- src/Sylius/Bundle/SettingsBundle/Controller/SettingsController.php
- src/Sylius/Bundle/WebBundle/Menu/BackendMenuBuilder.php
- src/Sylius/Bundle/WebBundle/Menu/FrontendMenuBuilder.php
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/settings.yml
- src/Sylius/Bundle/WebBundle/Resources/translations/menu.en.yml
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Settings/security.html.twig
> Add missing configuration for Sylius RBAC Security in backend

- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
| Fixed tickets | #2025 
Please do let me know if I have to adjust anything to comply to your standards although I've made sure I comply. Love to be a contributor to this project although this is a minor fix.
> [ProductVariant] Added versioning for all product variant details

- src/Sylius/Bundle/RbacBundle/DependencyInjection/Configuration.php
Hopefully this is going to fix  #2632 and #2624.
@pjedrzejewski /cc
> [RbacBundle] Fix permissions and roles config merging.

- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
> Fix redirect on API calls to revert, move and updateState actions.

- src/Sylius/Bundle/CoreBundle/Form/Type/AdvancedOrderType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/form.xml
- src/Sylius/Bundle/OrderBundle/Form/Type/OrderStateChoiceType.php
- src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
Add `sylius_order_state_choice` form type and also simplify `sylius_advanced_order` fields.
> [CorceBundle] Add sylius_order_state_choice form type

- src/Sylius/Bundle/AttributeBundle/Form/EventListener/BuildAttributeValueFormListener.php
- src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeValueType.php
- src/Sylius/Bundle/AttributeBundle/spec/Form/EventListener/BuildAttributeValueFormListenerSpec.php
- src/Sylius/Bundle/AttributeBundle/spec/Form/Type/AttributeValueTypeSpec.php
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
Each attribute subject can have its own labels
> [AttributeBundle] Add attribute and value labels

- phpspec.yml
It permit to generate classes with phpspec from the root of the projet.
> [PhpSpec] The source path has been added for each suite

- src/Sylius/Bundle/CoreBundle/Resources/config/app/payum.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPaymentMethodsData.php
- src/Sylius/Bundle/PayumBundle/Payum/Dummy/Action/PaymentStatusAction.php
- src/Sylius/Bundle/PayumBundle/Payum/Offline/Action/CapturePaymentAction.php
- src/Sylius/Bundle/PayumBundle/Resources/config/services.xml
> Add support for offline payment methods to PayumBundle

- src/Sylius/Bundle/ResourceBundle/Resources/public/js/form-collection.js
This PR correct the events triggered when used form collections.
> [ResourceBundle] Fix triggered events on forms collections

- src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Account/Order/_detail.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Account/Order/_list.html.twig
| Fixed tickets  | #2526
| Tests pass?   | yes
> [account order][sylius_money] use order currency.

- src/Sylius/Bundle/SettingsBundle/Controller/SettingsController.php
- src/Sylius/Bundle/SettingsBundle/Form/Factory/SettingsFormFactory.php
- src/Sylius/Bundle/SettingsBundle/Form/Factory/SettingsFormFactoryInterface.php
Q  | A
Bug fix?  | no
License | MIT
Doc PR | -
> [SettingsBundle] Add API support to SettingsController

- src/Sylius/Bundle/SearchBundle/Finder/ElasticsearchFinder.php
termsFilter needs to be instantiated on each loop or it will crash on multiple terms search
> Fix multiple terms filter

- src/Sylius/Bundle/ResourceBundle/Resources/views/Macros/actions.html.twig
> [WebBundle] Fix to show icons in buttons

- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
Q | A
------------ | -------------
Bug fix? | yes
Fixed tickets | #2732
Tests pass? | yes
License | MIT
> add findOneByPermalink missing method

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
- src/Sylius/Bundle/ResourceBundle/Resources/translations/flashes.en.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/product.yml
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/macros.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/show.html.twig
- src/Sylius/Component/Order/Model/Order.php
- src/Sylius/Component/Product/Model/Product.php
- src/Sylius/Component/Promotion/Model/Coupon.php
- src/Sylius/Component/Resource/Model/SoftDeletableInterface.php
- src/Sylius/Component/Taxonomy/Model/Taxon.php
- src/Sylius/Component/Variation/Model/Variant.php
I added option to revert soft deleted resource and add feature for undeleting product. Also I separated listing of deleted and not deleted products in product index in backend.
> Added option to undelete resource (product) 

- src/Sylius/Bundle/SettingsBundle/DependencyInjection/SyliusSettingsExtension.php
> [SettingsBundle] Fix default to %sylius.cache%

- src/Sylius/Bundle/AttributeBundle/Form/EventListener/BuildAttributeFormChoicesListener.php
- src/Sylius/Bundle/AttributeBundle/spec/Form/EventListener/BuildAttributeFormChoicesListenerSpec.php
- src/Sylius/Bundle/WebBundle/Resources/public/js/sylius-attribute-choices.js
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductAttribute/_form.html.twig
> Attribute choices management

- app/config/routing.yml
- app/config/security.yml
- src/Sylius/Bundle/UserBundle/OAuth/UserProvider.php
- src/Sylius/Bundle/UserBundle/Resources/config/services.xml
- src/Sylius/Bundle/UserBundle/spec/OAuth/UserProviderSpec.php
> Fix HWIO OAuth login

- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
| Fixed tickets | #2764
This will create a default channel on sylius:install as sylius currently don't work without at least one channel.
> [InstallerBundle] Setup command to create channels

- src/Sylius/Bundle/UserBundle/OAuth/UserProvider.php
> [UserBundle] Remove dependency from Core component

- app/migrations/Version20150531210410.php
- src/Sylius/Bundle/UserBundle/Resources/config/doctrine/model/Customer.orm.xml
Initial migration script for SyliusUserBundle. It creates customers based on users and guest orders and also preserves addresses, groups and orders by associating them with appropriate customers.
TODO:
Permissions should be initialized using command ```sylius:rbac:initialize```
> [UserBundle] Migration script

- src/Sylius/Bundle/ResourceBundle/Controller/ConfigurationFactory.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDatabaseDriver.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/DoctrineODMDriver.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/DoctrineORMDriver.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/DoctrinePHPCRDriver.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ConfigurationFactorySpec.php
| Fixed tickets | []
| Doc PR        | []
> [ResourceBundle] Move hardcoded classes to DI-parameters

- src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Country.orm.xml
> Index country on ISO code

- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/MongoDB/DocumentRepository.php
- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/DocumentRepository.php
- src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php
- src/Sylius/Bundle/TranslationBundle/Doctrine/ODM/MongoDB/TranslatableResourceRepository.php
- src/Sylius/Bundle/TranslationBundle/Doctrine/ORM/TranslatableResourceRepository.php
- src/Sylius/Bundle/TranslationBundle/spec/Doctrine/ORM/TranslatableResourceRepositorySpec.php
Check if properties are translated when sorting (as it's already done when filtering).
> [ResourceBundle][TranslationBundle] Fix sorting on translated properties

- src/Sylius/Bundle/ResourceBundle/spec/Fixture/Document/TranslatableFoo.php
- src/Sylius/Bundle/ResourceBundle/spec/Fixture/Entity/TranslatableFoo.php
- src/Sylius/Component/Addressing/Model/Country.php
- src/Sylius/Component/Archetype/Model/Archetype.php
- src/Sylius/Component/Attribute/Model/Attribute.php
- src/Sylius/Component/Core/Model/Product.php
- src/Sylius/Component/Core/Model/ShippingMethod.php
- src/Sylius/Component/Core/Model/Taxon.php
- src/Sylius/Component/Core/Model/Taxonomy.php
- src/Sylius/Component/Product/Model/Archetype.php
- src/Sylius/Component/Product/Model/Attribute.php
- src/Sylius/Component/Product/Model/Option.php
- src/Sylius/Component/Product/Model/Product.php
- src/Sylius/Component/Shipping/Model/ShippingMethod.php
- src/Sylius/Component/Taxonomy/Model/Taxon.php
- src/Sylius/Component/Taxonomy/Model/Taxonomy.php
- src/Sylius/Component/Translation/Model/AbstractTranslatable.php
- src/Sylius/Component/Translation/spec/Model/AbstractTranslatableSpec.php
- src/Sylius/Component/Variation/Model/Option.php
@pjedrzejewski Squashed commits.
Replaces and closes https://github.com/Sylius/Sylius/pull/2648.
> [Translation] Make translatable translation class retrieval static

- src/Sylius/Bundle/PricingBundle/DependencyInjection/SyliusPricingExtension.php
- src/Sylius/Bundle/PricingBundle/Form/EventListener/BuildPriceableFormSubscriber.php
- src/Sylius/Bundle/PricingBundle/Form/Extension/PriceableTypeExtension.php
- src/Sylius/Bundle/PricingBundle/Form/Type/CalculatorChoiceType.php
- src/Sylius/Bundle/PricingBundle/Form/Type/VolumeBasedConfigurationType.php
- src/Sylius/Bundle/PricingBundle/Form/Type/VolumePriceConfigurationType.php
- src/Sylius/Bundle/PricingBundle/Resources/config/services.xml
- src/Sylius/Bundle/PricingBundle/spec/Form/EventListener/BuildPriceableFormSubscriberSpec.php
- src/Sylius/Bundle/PricingBundle/spec/Form/Extension/PriceableTypeExtensionSpec.php
- src/Sylius/Bundle/PricingBundle/spec/Form/Type/CalculatorChoiceTypeSpec.php
- src/Sylius/Bundle/PricingBundle/spec/Form/Type/VolumeBasedConfigurationTypeSpec.php
- src/Sylius/Bundle/PricingBundle/spec/Form/Type/VolumePriceConfigurationTypeSpec.php
> [PricingBundle] CS fixes and missing specs

- src/Sylius/Bundle/MailerBundle/Behat/MailerContext.php
- src/Sylius/Bundle/MailerBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/MailerBundle/Form/Type/EmailTemplateChoiceType.php
- src/Sylius/Bundle/MailerBundle/Form/Type/EmailType.php
- src/Sylius/Bundle/MailerBundle/Renderer/Adapter/TwigAdapter.php
- src/Sylius/Bundle/MailerBundle/Sender/Adapter/SwiftMailerAdapter.php
- src/Sylius/Bundle/MailerBundle/spec/Form/Type/EmailTemplateChoiceTypeSpec.php
- src/Sylius/Bundle/MailerBundle/spec/Renderer/Adapter/TwigAdapterSpec.php
- src/Sylius/Bundle/MailerBundle/spec/Sender/Adapter/SwiftMailerAdapterSpec.php
> [MailerBundle] CS fixes and missing specs

- src/Sylius/Bundle/SettingsBundle/Resources/config/doctrine/model/Parameter.orm.xml
> [SettingsBundle] added missing unique index for table sylius_settings_parameter

- src/Sylius/Component/Mailer/Event/EmailSendEvent.php
| Q | A |
---- | -----
| Bug fix?	| no |
| New feature?	| refactoring |
| BC breaks?	| no |
| Deprecations? | no |
| Fixed tickets	| no |
| License	| MIT |
| Doc | PR |
> [MailerComponent]: Removing unused dependecy and fixing cs

- src/Sylius/Bundle/SequenceBundle/DependencyInjection/Compiler/RegisterGeneratorsPass.php
- src/Sylius/Bundle/SequenceBundle/DependencyInjection/SyliusSequenceExtension.php
- src/Sylius/Bundle/SequenceBundle/Doctrine/ORM/NumberListener.php
- src/Sylius/Bundle/SequenceBundle/spec/DependencyInjection/Compiler/RegisterGeneratorsPassSpec.php
> [SequenceBundle] CS fixes and missing specs

- src/Sylius/Bundle/ShippingBundle/spec/DependencyInjection/Compiler/RegisterCalculatorsPassSpec.php
- src/Sylius/Bundle/ShippingBundle/spec/DependencyInjection/Compiler/RegisterRuleCheckersPassSpec.php
- src/Sylius/Bundle/ShippingBundle/spec/Form/EventListener/BuildRuleFormSubscriberSpec.php
- src/Sylius/Bundle/ShippingBundle/spec/Form/EventListener/BuildShippingMethodFormSubscriberSpec.php
- src/Sylius/Bundle/TaxationBundle/spec/DependencyInjection/Compiler/RegisterCalculatorsPassSpec.php
- src/Sylius/Bundle/TaxonomyBundle/spec/Doctrine/ORM/TaxonRepositorySpec.php
- src/Sylius/Bundle/TaxonomyBundle/spec/Form/EventListener/BuildTaxonFormSubscriberSpec.php
- src/Sylius/Bundle/TaxonomyBundle/spec/Form/Type/TaxonChoiceTypeSpec.php
- src/Sylius/Bundle/TaxonomyBundle/spec/Form/Type/TaxonSelectionTypeSpec.php
- src/Sylius/Bundle/UserBundle/spec/Doctrine/ORM/CustomerRepositorySpec.php
- src/Sylius/Bundle/UserBundle/spec/Doctrine/ORM/GroupRepositorySpec.php
- src/Sylius/Bundle/UserBundle/spec/Event/UserEventSpec.php
- src/Sylius/Bundle/UserBundle/spec/EventListener/DefaultUsernameORMListenerSpec.php
- src/Sylius/Bundle/UserBundle/spec/EventListener/UserLastLoginSubscriberSpec.php
- src/Sylius/Bundle/UserBundle/spec/Form/Type/CustomerProfileTypeSpec.php
- src/Sylius/Bundle/UserBundle/spec/Form/Type/CustomerRegistrationTypeSpec.php
- src/Sylius/Bundle/UserBundle/spec/Form/Type/GenderTypeSpec.php
- src/Sylius/Bundle/UserBundle/spec/Form/Type/GroupTypeSpec.php
- src/Sylius/Bundle/VariationBundle/spec/Form/ChoiceList/VariantChoiceListSpec.php
- src/Sylius/Bundle/VariationBundle/spec/Form/EventListener/BuildVariantFormSubscriberSpec.php
- src/Sylius/Bundle/VariationBundle/spec/Form/Type/OptionValueCollectionTypeSpec.php
- src/Sylius/Bundle/VariationBundle/spec/Form/Type/VariantChoiceTypeSpec.php
- src/Sylius/Bundle/VariationBundle/spec/Form/Type/VariantMatchTypeSpec.php
> Missing licence

- src/Sylius/Bundle/InstallerBundle/Command/InstallDatabaseCommand.php
- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
> Fix installer, add check for existing channel

- src/Sylius/Bundle/FixturesBundle/DataFixtures/DataFixture.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadChannelData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadContactRequestData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadContactTopicData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadCountriesData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadCurrencyData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadImagesData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadOrdersData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductArchetypeData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductOptionData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductsData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadTaxonomiesData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadZonesData.php
> [FixturesBundle] CS fixes

- src/Sylius/Bundle/UserBundle/Controller/UserController.php
> Fix token typo in UserController

- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
> Improve security exception message

- src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Country.orm.xml
- src/Sylius/Bundle/AddressingBundle/Resources/config/validation.xml
- src/Sylius/Bundle/CurrencyBundle/Resources/config/doctrine/model/Currency.orm.xml
- src/Sylius/Bundle/LocaleBundle/Resources/config/doctrine/model/Locale.orm.xml
| Bug fix?      | future bugs fix
> Add unique constraints on codes

- src/Sylius/Bundle/ResourceBundle/spec/Form/Extension/DateExtensionSpec.php
> The spec was not PSR4 compatible

- src/Sylius/Bundle/UserBundle/Controller/UserController.php
> [UserBundle] Improve reset password action

- app/migrations/Version20150616155405.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
> [CoreBundle] Fix invalid channel mapping

- phpspec.yml
- src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
- src/Sylius/Bundle/ApiBundle/Model/ClientManager.php
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/spec/Model/ClientManagerSpec.php
- src/Sylius/Bundle/ApiBundle/spec/Model/ClientSpec.php
Related discussion https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/328
> [ApiBundle] Change api client public id to be simply random id

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadApiData.php
> [FixturesBundle] Ensure Rbac roles are initialized

- src/Sylius/Bundle/CartBundle/Doctrine/ORM/CartRepository.php
- src/Sylius/Bundle/CartBundle/EventListener/CartSubscriber.php
- src/Sylius/Bundle/CartBundle/EventListener/FlashSubscriber.php
- src/Sylius/Bundle/CartBundle/Purger/ExpiredCartsPurger.php
- src/Sylius/Bundle/CartBundle/Resources/config/services.xml
- src/Sylius/Bundle/CartBundle/spec/Command/PurgeCartsCommandSpec.php
- src/Sylius/Bundle/CartBundle/spec/Doctrine/ORM/CartRepositorySpec.php
- src/Sylius/Bundle/CartBundle/spec/EventListener/CartSubscriberSpec.php
- src/Sylius/Bundle/CartBundle/spec/EventListener/FlashSubscriberSpec.php
- src/Sylius/Bundle/CartBundle/spec/EventListener/RefreshCartListenerSpec.php
- src/Sylius/Bundle/CartBundle/spec/Purger/ExpiredCartsPurgerSpec.php
- src/Sylius/Bundle/CoreBundle/EventListener/OrderPromotionListener.php
- src/Sylius/Component/Cart/Repository/CartRepositoryInterface.php
> [CartBundle] CS fixes and missing specs

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadApiData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadChannelData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadContactRequestData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadCountriesData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadCurrencyData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadGroupsData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadImagesData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadLocalesData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadOrdersData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPaymentMethodsData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductArchetypeData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductAttributeData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductOptionData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductsData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPromotionsData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadRbacData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadShippingData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadTaxationData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadTaxonomiesData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadZonesData.php
- src/Sylius/Bundle/InstallerBundle/Command/InstallSampleDataCommand.php
| Bug fix?      | future bugs connected with uninitialized Rbac
> Improve fixtures order and add Rbac fixtures

- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/channel.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/content/block/imagine_block.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/content/block/slideshow_block.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/content/menu.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/content/menu_node.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/content/redirect_route.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/content/route.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/content/static_content.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/frontend/static_content.yml
Q  | A
Bug fix?  | no
License | MIT
Doc PR | -
Just want to remove a few deprecation notices.
> Replace pattern with path

- src/Sylius/Bundle/ChannelBundle/Resources/config/validation.xml
Q  | A
License | MIT
Doc PR | -
> [ChannelBundle] Fix wrong class name in channels validation.xml

- src/Sylius/Component/Order/Model/Order.php
| Fixed tickets | #2882
| Doc PR        | https://github.com/Sylius/Sylius-Docs/pull/300
> [Order] Removed unused fields in Order model

- features/frontend/products.feature
- src/Sylius/Bundle/ChannelBundle/Behat/ChannelContext.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/WebBundle/Resources/config/routing/partial/product.yml
> [Core] [Web] Display homepage products only for current channel

- src/Sylius/Bundle/AddressingBundle/Validator/Constraints/ShippableAddressConstraintValidator.php
> [AddressingBundle] Fixes from scrutinizer - cannot override without Runtime Notice

- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/Product.orm.xml
Q  | A
Bug fix?  | no
License | MIT
Doc PR | -
> [ProductBundle] Allow null in available_on field

- src/Sylius/Bundle/AddressingBundle/Form/Type/ProvinceChoiceType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Api/TaxonType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Shipping/ShippingMethodChoiceType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodChoiceType.php
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonChoiceType.php
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonSelectionType.php
- src/Sylius/Bundle/TaxonomyBundle/spec/Form/Type/TaxonSelectionTypeSpec.php
- src/Sylius/Bundle/VariationBundle/Form/Type/OptionValueChoiceType.php
Q  | A
Bug fix?  | no
New feature?  | refactor
License | MIT
Doc PR | -
> Make choice form types API friendly

- src/Sylius/Bundle/CoreBundle/Resources/config/app/main.yml
- src/Sylius/Bundle/UserBundle/Resources/config/serializer/Model.User.yml
| Q	                       | A     |
|--------------------------|------ |
| Bug Fix?        	| y     |
| New Feature?	| n     |
| BC Breaks?	       | n     |
| Deprecations?	| n     |
| Tests Pass?	       | n     |
| Fixed Tickets	       |        |
| License	               | MIT |
| Doc PR                  |        |
> Fix wrong user serializer config.

- src/Sylius/Component/Shipping/Model/ShippingMethod.php
> Removed ShippingMethod name property

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Extension/AbstractResourceExtension.php
- src/Sylius/Bundle/ResourceBundle/spec/DependencyInjection/AbstractResourceExtensionSpec.php
| Fixed tickets | https://github.com/Sylius/Sylius/issues/2970
> [BUG][ResourceBundle] Default validation group if not found

- src/Sylius/Bundle/RbacBundle/DependencyInjection/Configuration.php
Q | A
Bug fix? | yes
License | MIT
Doc PR | -
Related to #2632 and #2624.
> [RbacBundle] Fix security_roles config merging.

- src/Sylius/Bundle/VariationBundle/Form/Type/OptionValueCollectionType.php
- src/Sylius/Bundle/VariationBundle/spec/Form/Type/OptionValueCollectionTypeSpec.php
Q  | A
Bug fix?  | no
New feature?  | refactor
License | MIT
Doc PR | -
> [VariationBundle] Make option value collection to be api-friendly

- src/Sylius/Bundle/ContentBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ContentBundle/Form/Type/StaticContentChoiceType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
> [Content] fixed the __toString() exception for static content

- src/Sylius/Bundle/SearchBundle/Query/SearchStringQuery.php
Escaping slashes in search queries because of elasticsearch behavior, more here https://github.com/elastic/elasticsearch/issues/2980
> Escaping slashes in search queries because of elasticsearch behavior

- UPGRADE.md
Added instructions for UserBundle and API.
> v0.15.0 Upgrade instructions

- src/Sylius/Bundle/AddressingBundle/composer.json
| Doc PR        | https://github.com/Sylius/Sylius-Docs/pull/305
> [AddressingBundle] Added SyliusTranslationBundle to required

- src/Sylius/Bundle/CoreBundle/Behat/HookContext.php
- src/Sylius/Bundle/CoreBundle/Checkout/Step/AddressingStep.php
- src/Sylius/Bundle/CoreBundle/Checkout/Step/PurchaseStep.php
- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
- src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentMethodChoiceType.php
- src/Sylius/Bundle/PayumBundle/Payum/Be2bill/Action/CapturePaymentUsingCreditCardAction.php
- src/Sylius/Bundle/PricingBundle/Form/Extension/PriceableTypeExtension.php
- src/Sylius/Bundle/TranslationBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/TranslationBundle/EventListener/ODMTranslatableListener.php
- src/Sylius/Component/Archetype/Model/Archetype.php
- src/Sylius/Component/Payment/Calculator/DefaultFeeCalculators.php
- src/Sylius/Component/Payment/Model/PaymentMethod.php
After merging #2978 @michalmarcinkowski rightly noticed some CS issues that could and should be fixed. Here they are. I have also deleted some "return" statements in other ``PaymentMethod`` functions (which may cause some potential BC breaks) and some irritating unused use statements introduced by Scrutinizer.
> General CS fixes

- src/Sylius/Component/Mailer/Provider/EmailProvider.php
- src/Sylius/Component/Mailer/spec/Model/EmailSpec.php
| Q | A |
---- | -----
| Bug fix?	| no |
| New feature?	| refactoring |
| BC breaks?	| no |
| Deprecations? | no |
| Fixed tickets	| no |
| License	| MIT |
| Doc | PR |
- Adding specs for Email model
- Removing unused check for email provider
> [MailerComponent] Removing unused check, Adding more specs to Email model

- src/Sylius/Bundle/InstallerBundle/Command/AbstractInstallCommand.php
- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
| Fixed tickets | #2881 
Changed administrator password request field to hidden in sylius:install:setup command.
> [InstallerBundle] Hide password in installation

- src/Sylius/Bundle/InstallerBundle/Command/InstallDatabaseCommand.php
We override this command in our project, this makes it easier.
> Make InstallDatabaseCommand easyer to extend

- src/Sylius/Bundle/FixturesBundle/DataFixtures/DataFixture.php
> [FixturesBundle] Fixed loading sample data while intl extension not installed

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPaymentMethodsData.php
> [FixturesBundle] fix fixture percent payment method

- src/Sylius/Bundle/TaxonomyBundle/Behat/TaxonomyContext.php
- src/Sylius/Component/Taxonomy/Model/Taxonomy.php
- src/Sylius/Component/Taxonomy/spec/Model/TaxonomySpec.php
Continued PR #2786, originally written by @ahmadrabie, thanks! :)
| Fixed tickets | #2734, #2740, #2786
> [Taxonomy] Update root taxon after taxonomy translation is added

- src/Sylius/Bundle/UserBundle/Security/UserLogin.php
- src/Sylius/Bundle/UserBundle/spec/Security/UserLoginSpec.php
> [UserBundle] Improve login method

- features/backend/countries.feature
- features/backend/products.feature
- features/currencies/currency_management.feature
- features/currencies/currency_switching.feature
- features/frontend/cart.feature
- features/localization/locale_management.feature
- src/Sylius/Bundle/ResourceBundle/Behat/DefaultContext.php
- src/Sylius/Bundle/ResourceBundle/Behat/WebContext.php
- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml
- src/Sylius/Bundle/ResourceBundle/Resources/translations/flashes.en.yml
- src/Sylius/Bundle/ResourceBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/ResourceBundle/Resources/views/Macros/buttons.html.twig
- src/Sylius/Bundle/ResourceBundle/Validator/Constraints/Disabled.php
- src/Sylius/Bundle/ResourceBundle/Validator/Constraints/Enabled.php
- src/Sylius/Bundle/ResourceBundle/Validator/DisabledValidator.php
- src/Sylius/Bundle/ResourceBundle/Validator/EnabledValidator.php
- src/Sylius/Bundle/ResourceBundle/spec/Validator/Constraints/DisabledSpec.php
- src/Sylius/Bundle/ResourceBundle/spec/Validator/Constraints/EnabledSpec.php
- src/Sylius/Bundle/ResourceBundle/spec/Validator/DisabledValidatorSpec.php
- src/Sylius/Bundle/ResourceBundle/spec/Validator/EnabledValidatorSpec.php
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Resource/Model/ToggleableInterface.php
> [ResourceBundle] Toggleable interface & useful Behat steps and methods

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Country/macros.html.twig
> [WebBundle] Removed ID column from the list

- src/Sylius/Bundle/CoreBundle/Resources/config/form.xml
- src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
> [UserBundle] Moved customer registration type definition to UserBundle

- src/Sylius/Bundle/LocaleBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/LocaleBundle/DependencyInjection/SyliusLocaleExtension.php
- src/Sylius/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php
- src/Sylius/Component/Locale/Provider/LocaleProviderInterface.php
Fixes issues introduced by #3104, noticed by @gperdomor in a [comment](https://github.com/Sylius/Sylius/pull/3104#issuecomment-132040566).
> [Locale] Fixed errors thrown while editing channel with LocaleChoiceType

- src/Sylius/Bundle/CoreBundle/spec/EventListener/OrderChannelListenerSpec.php
| New feature?  | enhancement
- Adding specs for OrderChannelListener class
> [CoreBundle] Adding OrderChannelListener spec

- src/Sylius/Bundle/ResourceBundle/AbstractResourceBundle.php
| Bug fix?      | yes #2488
Annotation mapping compiles pass is broke, Because method createAnnotationMappingDriver have different signature:
``` php
public static function createXmlMappingDriver(array $namespaces, array $managerParameters = array(), $enabledParameter = false, array $aliasMap = array())
public static function createYamlMappingDriver(array $namespaces, array $managerParameters = array(), $enabledParameter = false, array $aliasMap = array())
public static function createAnnotationMappingDriver(array $namespaces, array $directories, array $managerParameters = array(), $enabledParameter = false, array $aliasMap = …
```
> [ResourceBundle] fix reworking of AbstractResourceBundle::build

- vagrant/Vagrantfile
- web/app_dev.php
- web/app_test.php
> add Vagrant Vmware provider

- src/Sylius/Bundle/CoreBundle/EventListener/OrderPricingListener.php
- src/Sylius/Bundle/CoreBundle/spec/EventListener/OrderPricingListenerSpec.php
| New feature?  | enhancement
- Adding specs for OrderPricingListener class
- Fixing CS
> [CoreBundle] Adding OrderPricingListener spec and fixing CS

- src/Sylius/Bundle/CoreBundle/EventListener/InsufficientStockExceptionListener.php
- src/Sylius/Bundle/CoreBundle/spec/EventListener/InsufficientStockExceptionListenerSpec.php
| New feature?  | enhancement
- Adding specs for InsufficientStockExceptionListener class
- Fixing CS
> [CoreBundle] Adding specs for InsufficientStockExceptionListener

- src/Sylius/Bundle/ContentBundle/composer.json
Hi,
A fix for the https://github.com/Sylius/Sylius/issues/2962 bug
> [Content Bundle] Fix #2962 - Update symfony-cmf to ~1.2 in composer.json

- app/config/parameters.yml.dist
- src/Sylius/Bundle/CoreBundle/Resources/config/app/main.yml
> [CoreBundle] Make path to wkhtmltopdf configurable

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/payment.yml
Uncommented payment routes in ApiBundle.
> Api bundle payment route fix

- src/Sylius/Bundle/InstallerBundle/Command/AbstractInstallCommand.php
- src/Sylius/Bundle/InstallerBundle/Command/CommandExecutor.php
- src/Sylius/Bundle/InstallerBundle/Command/InstallAssetsCommand.php
- src/Sylius/Bundle/InstallerBundle/Command/InstallCommand.php
- src/Sylius/Bundle/InstallerBundle/Command/InstallSampleDataCommand.php
| Fixed tickets | #3168 
While installing Sylius, installer should check if required directories have write permissions, to avoid fatal error.
> [Installer] Install check permissions

- src/Sylius/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.xml
- src/Sylius/Component/Payment/Model/Payment.php
- src/Sylius/Component/Payment/Model/PaymentInterface.php
- src/Sylius/Component/Payment/spec/Model/PaymentSpec.php
| Fixed tickets | #3153
| Doc PR        | https://github.com/Sylius/Sylius-Docs/pull/314
Payments are softdeleted cascadingly with order to prevent fatal error on list.
> [Payment] Softdeleteable Payments

- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
| Fixed tickets | #2891
Set currencies and locales at channels created while installation, to be able to use them immediately.
> [Installer] Fix installation channels creation

- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductTranslation.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation.xml
Q  | A
Bug fix?  | no
License | MIT
Doc PR | -
> [CoreBundle] Remove product short description validation and use text type

- src/Sylius/Bundle/ContentBundle/Form/Type/MenuNodeType.php
- src/Sylius/Bundle/ContentBundle/Form/Type/MenuType.php
- src/Sylius/Bundle/ContentBundle/Form/Type/RouteType.php
- src/Sylius/Bundle/ContentBundle/Form/Type/SlideshowBlockType.php
- src/Sylius/Bundle/ContentBundle/Form/Type/StaticContentType.php
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Content/StaticContent/_form.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Content/StaticContent/macros.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Frontend/layout.html.twig
Hi,
Fix for this issue https://github.com/Sylius/Sylius/issues/2895
Tested and approved ;)
> [ContentBundle] Fix cascade validation of collection form (issue #2895)

- app/migrations/Version20150901113105.php
Q  | A
Bug fix?  | no
License | MIT
Doc PR | -
> [CoreBundle] Add migration for production short description change in PR #3188

- app/migrations/Version20150901104436.php
Added missing migration for softdeletable Payments, according to @michalmarcinkowski comment in https://github.com/Sylius/Sylius/pull/3194
> [Payment] Added migration for softdeleteable Payments

- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
Q | A
Bug fix? | yes
License | MIT
Doc PR | -
> [ResourceBundle] Enable max depth check on API serialization

- src/Sylius/Component/Core/Model/UserInterface.php
- src/Sylius/Component/Core/spec/Model/UserSpec.php
| Fixed tickets | https://github.com/Sylius/Sylius/issues/2935
> [Core] Missing methods in UserInterface added

- src/Sylius/Bundle/InstallerBundle/Requirement/ExtensionsRequirements.php
Fixes #3054, no BC, no new features :)
> [Installer] Added Zend Optimizer+ to recognized accelelators

- src/Sylius/Bundle/AttributeBundle/spec/Form/Type/AttributeValueTypeSpec.php
Solves #3191, no BC, no features :)
> [AttrbiuteBundle] Decoupled spec from Product component

- src/Sylius/Component/Product/composer.json
> [Product] Add required dependency to Product component

- src/Sylius/Component/User/Model/Customer.php
- src/Sylius/Component/User/Model/CustomerAwareInterface.php
- src/Sylius/Component/User/Model/CustomerInterface.php
- src/Sylius/Component/User/Model/Group.php
- src/Sylius/Component/User/Model/GroupInterface.php
- src/Sylius/Component/User/Model/GroupableInterface.php
- src/Sylius/Component/User/Model/User.php
- src/Sylius/Component/User/Model/UserAwareInterface.php
- src/Sylius/Component/User/Model/UserInterface.php
- src/Sylius/Component/User/Model/UserOAuth.php
- src/Sylius/Component/User/Model/UserOAuthInterface.php
| BC breaks?    | no (component hasn't been released yet :smile:)
> [User] Remove fluent interfaces from User component

- CHANGELOG.md
> Updated changelog v0.16

- src/Sylius/Component/Addressing/composer.json
Correct resource component version.
> [Addressing] Fix addressing composer

- features/user/account/account_addresses.feature
> [Behat] Account suite - fixed undefined scenario

- behat.yml.dist
- travis/suites/suite-1
There's no scenarios within that suite, so nothing is changes, except for less code :)
> [Behat / Travis] Removed "search_orm_only" suite

- src/Sylius/Bundle/WebBundle/Resources/config/services.xml
> [WebBundle] Remove empty services

- src/Sylius/Bundle/CoreBundle/Templating/Helper/MoneyHelper.php
> [Core] Fixed MoneyHelper providing current locale instead of default one

- src/Sylius/Component/Channel/Context/ChannelContext.php
- src/Sylius/Component/Channel/Context/ChannelContextInterface.php
- src/Sylius/Component/Channel/Model/Channel.php
- src/Sylius/Component/Channel/Model/ChannelAwareInterface.php
- src/Sylius/Component/Channel/Model/ChannelInterface.php
- src/Sylius/Component/Channel/Model/ChannelsAwareInterface.php
- src/Sylius/Component/Channel/Repository/ChannelRepositoryInterface.php
- src/Sylius/Component/Channel/spec/Sylius/Component/Channel/Model/ChannelSpec.php
> [Channel] Removed fluent interfaces

- src/Sylius/Component/Cart/Model/Cart.php
- src/Sylius/Component/Cart/Model/CartInterface.php
> [Cart] remove all fluent interfaces in Cart models

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadCountriesData.php
- src/Sylius/Component/Addressing/Model/Address.php
- src/Sylius/Component/Addressing/Model/AddressInterface.php
- src/Sylius/Component/Addressing/Model/CountryInterface.php
- src/Sylius/Component/Addressing/Model/Province.php
- src/Sylius/Component/Addressing/Model/ProvinceInterface.php
- src/Sylius/Component/Addressing/Model/Zone.php
- src/Sylius/Component/Addressing/Model/ZoneInterface.php
- src/Sylius/Component/Addressing/Model/ZoneMember.php
- src/Sylius/Component/Addressing/Model/ZoneMemberCountry.php
- src/Sylius/Component/Addressing/Model/ZoneMemberInterface.php
- src/Sylius/Component/Addressing/Model/ZoneMemberProvince.php
- src/Sylius/Component/Addressing/Model/ZoneMemberZone.php
- src/Sylius/Component/Addressing/spec/Model/AddressSpec.php
- src/Sylius/Component/Addressing/spec/Model/ZoneMemberCountrySpec.php
- src/Sylius/Component/Addressing/spec/Model/ZoneMemberProvinceSpec.php
- src/Sylius/Component/Addressing/spec/Model/ZoneMemberZoneSpec.php
- src/Sylius/Component/Addressing/spec/Model/ZoneSpec.php
> [Addressing] Removed fluent interfaces

- src/Sylius/Component/Core/Model/Taxon.php
- src/Sylius/Component/Core/Model/TaxonInterface.php
- src/Sylius/Component/Taxonomy/Model/Taxon.php
- src/Sylius/Component/Taxonomy/Model/TaxonInterface.php
- src/Sylius/Component/Taxonomy/Model/TaxonTranslation.php
- src/Sylius/Component/Taxonomy/Model/TaxonTranslationInterface.php
- src/Sylius/Component/Taxonomy/Model/TaxonomiesAwareInterface.php
- src/Sylius/Component/Taxonomy/Model/Taxonomy.php
- src/Sylius/Component/Taxonomy/Model/TaxonomyInterface.php
- src/Sylius/Component/Taxonomy/Model/TaxonomyTranslation.php
- src/Sylius/Component/Taxonomy/Model/TaxonomyTranslationInterface.php
- src/Sylius/Component/Taxonomy/Model/TaxonsAwareInterface.php
> [Taxonomy] Remove fluent interfaces

- src/Sylius/Bundle/ProductBundle/Behat/ProductContext.php
- src/Sylius/Component/Attribute/Model/Attribute.php
- src/Sylius/Component/Attribute/Model/AttributeInterface.php
- src/Sylius/Component/Attribute/Model/AttributeSubjectInterface.php
- src/Sylius/Component/Attribute/Model/AttributeTranslation.php
- src/Sylius/Component/Attribute/Model/AttributeTranslationInterface.php
- src/Sylius/Component/Attribute/Model/AttributeTypes.php
- src/Sylius/Component/Attribute/Model/AttributeValue.php
- src/Sylius/Component/Attribute/Model/AttributeValueInterface.php
- src/Sylius/Component/Attribute/spec/Model/AttributeSpec.php
- src/Sylius/Component/Attribute/spec/Model/AttributeTranslationSpec.php
> [Attribute] Removed fluent interfaces

- src/Sylius/Bundle/UserBundle/composer.json
- src/Sylius/Component/User/Model/User.php
- src/Sylius/Component/User/Model/UserInterface.php
- src/Sylius/Component/User/composer.json
> [User] Update requirements and minor fixes

- src/Sylius/Component/Currency/Context/CurrencyContext.php
- src/Sylius/Component/Currency/Context/CurrencyContextInterface.php
- src/Sylius/Component/Currency/Converter/CurrencyConverter.php
- src/Sylius/Component/Currency/Converter/UnavailableCurrencyException.php
- src/Sylius/Component/Currency/Importer/AbstractImporter.php
- src/Sylius/Component/Currency/Importer/EuropeanCentralBankImporter.php
- src/Sylius/Component/Currency/Importer/OpenExchangeRatesImporter.php
- src/Sylius/Component/Currency/Model/CurrenciesAwareInterface.php
- src/Sylius/Component/Currency/Model/Currency.php
- src/Sylius/Component/Currency/Model/CurrencyInterface.php
- src/Sylius/Component/Currency/Provider/CurrencyProvider.php
- src/Sylius/Component/Currency/Provider/CurrencyProviderInterface.php
> [Currency] Remove fluent interfaces

- src/Sylius/Component/Mailer/Model/Email.php
- src/Sylius/Component/Mailer/Model/EmailInterface.php
> [Mailer] Removed fluent interfaces

- src/Sylius/Component/Taxation/Calculator/CalculatorInterface.php
- src/Sylius/Component/Taxation/Calculator/DefaultCalculator.php
- src/Sylius/Component/Taxation/Model/TaxCategory.php
- src/Sylius/Component/Taxation/Model/TaxCategoryInterface.php
- src/Sylius/Component/Taxation/Model/TaxRate.php
- src/Sylius/Component/Taxation/Model/TaxRateInterface.php
- src/Sylius/Component/Taxation/Model/TaxableInterface.php
- src/Sylius/Component/Taxation/Resolver/TaxRateResolver.php
- src/Sylius/Component/Taxation/Resolver/TaxRateResolverInterface.php
> [Taxation] Remove fluent interfaces

- src/Sylius/Component/Core/Model/Promotion.php
- src/Sylius/Component/Core/Model/PromotionInterface.php
- src/Sylius/Component/Promotion/Model/Action.php
- src/Sylius/Component/Promotion/Model/ActionInterface.php
- src/Sylius/Component/Promotion/Model/Coupon.php
- src/Sylius/Component/Promotion/Model/CouponInterface.php
- src/Sylius/Component/Promotion/Model/Promotion.php
- src/Sylius/Component/Promotion/Model/PromotionCountableSubjectInterface.php
- src/Sylius/Component/Promotion/Model/PromotionCouponAwareSubjectInterface.php
- src/Sylius/Component/Promotion/Model/PromotionCouponsAwareSubjectInterface.php
- src/Sylius/Component/Promotion/Model/PromotionInterface.php
- src/Sylius/Component/Promotion/Model/PromotionSubjectInterface.php
- src/Sylius/Component/Promotion/Model/Rule.php
- src/Sylius/Component/Promotion/Model/RuleInterface.php
- src/Sylius/Component/Resource/Model/TimestampableInterface.php
> [Promotion] Remove all fluent interfaces

- src/Sylius/Bundle/CoreBundle/Behat/HookContext.php
> [Core] Delete commented code in HookContext

- src/Sylius/Component/Addressing/Model/Country.php
- src/Sylius/Component/Addressing/Model/Province.php
- src/Sylius/Component/Addressing/Model/Zone.php
- src/Sylius/Component/Addressing/Model/ZoneInterface.php
- src/Sylius/Component/Core/Model/Address.php
> [Adressing] Remove fluent interfaces

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductArchetypeData.php
- src/Sylius/Bundle/ProductBundle/Behat/ProductContext.php
- src/Sylius/Component/Archetype/Model/Archetype.php
- src/Sylius/Component/Archetype/Model/ArchetypeInterface.php
- src/Sylius/Component/Archetype/Model/ArchetypeTranslation.php
- src/Sylius/Component/Archetype/Model/ArchetypeTranslationInterface.php
- src/Sylius/Component/Archetype/spec/Model/ArchetypeSpec.php
- src/Sylius/Component/Archetype/spec/Model/ArchetypeTranslationSpec.php
- src/Sylius/Component/Product/spec/Model/ArchetypeSpec.php
- src/Sylius/Component/Product/spec/Model/ArchetypeTranslationSpec.php
> [Archetype] Removed fluent interfaces

- features/user/account/account_password.feature
- src/Sylius/Bundle/WebBundle/Behat/WebContext.php
> Added behat scenario for logging in after changing password

- src/Sylius/Component/Payment/Calculator/DefaultFeeCalculators.php
- src/Sylius/Component/Payment/Calculator/DelegatingFeeCalculator.php
- src/Sylius/Component/Payment/Model/CreditCard.php
- src/Sylius/Component/Payment/Model/CreditCardInterface.php
- src/Sylius/Component/Payment/Model/Payment.php
- src/Sylius/Component/Payment/Model/PaymentInterface.php
- src/Sylius/Component/Payment/Model/PaymentMethod.php
- src/Sylius/Component/Payment/Model/PaymentMethodInterface.php
- src/Sylius/Component/Payment/Model/PaymentMethodsAwareInterface.php
- src/Sylius/Component/Payment/Model/PaymentSubjectInterface.php
- src/Sylius/Component/Payment/Model/PaymentsSubjectInterface.php
- src/Sylius/Component/Payment/spec/Model/PaymentSpec.php
> [Payment] Remove fluent interfaces

- src/Sylius/Component/Variation/Model/Option.php
- src/Sylius/Component/Variation/Model/OptionInterface.php
- src/Sylius/Component/Variation/Model/OptionTranslation.php
- src/Sylius/Component/Variation/Model/OptionTranslationInterface.php
- src/Sylius/Component/Variation/Model/OptionValue.php
- src/Sylius/Component/Variation/Model/OptionValueInterface.php
- src/Sylius/Component/Variation/Model/VariableInterface.php
- src/Sylius/Component/Variation/Model/Variant.php
- src/Sylius/Component/Variation/Model/VariantInterface.php
- src/Sylius/Component/Variation/SetBuilder/SetBuilderInterface.php
- src/Sylius/Component/Variation/spec/Model/OptionTranslationSpec.php
> [Variation] Remove fluent interfaces

- src/Sylius/Bundle/SettingsBundle/Controller/SettingsController.php
- src/Sylius/Bundle/SettingsBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/SettingsBundle/DependencyInjection/SyliusSettingsExtension.php
- src/Sylius/Bundle/SettingsBundle/Event/SettingsEvent.php
- src/Sylius/Bundle/SettingsBundle/Form/Factory/SettingsFormFactory.php
- src/Sylius/Bundle/SettingsBundle/Form/Factory/SettingsFormFactoryInterface.php
- src/Sylius/Bundle/SettingsBundle/Manager/SettingsManager.php
- src/Sylius/Bundle/SettingsBundle/Manager/SettingsManagerInterface.php
- src/Sylius/Bundle/SettingsBundle/Model/Parameter.php
- src/Sylius/Bundle/SettingsBundle/Model/ParameterInterface.php
- src/Sylius/Bundle/SettingsBundle/Model/Settings.php
- src/Sylius/Bundle/SettingsBundle/Schema/SchemaInterface.php
- src/Sylius/Bundle/SettingsBundle/Schema/SchemaRegistry.php
- src/Sylius/Bundle/SettingsBundle/Schema/SchemaRegistryInterface.php
- src/Sylius/Bundle/SettingsBundle/Schema/SettingsBuilder.php
- src/Sylius/Bundle/SettingsBundle/Schema/SettingsBuilderInterface.php
- src/Sylius/Bundle/SettingsBundle/Templating/Helper/SettingsHelper.php
- src/Sylius/Bundle/SettingsBundle/Transformer/ObjectToIdentifierTransformer.php
- src/Sylius/Bundle/SettingsBundle/Transformer/ParameterTransformerInterface.php
- src/Sylius/Bundle/SettingsBundle/Twig/SettingsExtension.php
- src/Sylius/Bundle/SettingsBundle/spec/Model/ParameterSpec.php
> [SettingsBundle] Remove all fluent interfaces

- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Frontend/layout.html.twig
> [Web] Fix frontend side menu translation

- src/Sylius/Bundle/VariationBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/VariationBundle/EventListener/LoadMetadataSubscriber.php
- src/Sylius/Bundle/VariationBundle/Form/ChoiceList/VariantChoiceList.php
- src/Sylius/Bundle/VariationBundle/Form/DataTransformer/VariantToCombinationTransformer.php
- src/Sylius/Bundle/VariationBundle/Form/EventListener/BuildVariantFormSubscriber.php
- src/Sylius/Bundle/VariationBundle/Form/Type/OptionTranslationType.php
- src/Sylius/Bundle/VariationBundle/Form/Type/OptionType.php
- src/Sylius/Bundle/VariationBundle/Form/Type/OptionValueChoiceType.php
- src/Sylius/Bundle/VariationBundle/Form/Type/OptionValueCollectionType.php
- src/Sylius/Bundle/VariationBundle/Form/Type/OptionValueType.php
- src/Sylius/Bundle/VariationBundle/Form/Type/VariantChoiceType.php
- src/Sylius/Bundle/VariationBundle/Form/Type/VariantMatchType.php
- src/Sylius/Bundle/VariationBundle/Form/Type/VariantType.php
- src/Sylius/Bundle/VariationBundle/Validator/Constraint/VariantUnique.php
- src/Sylius/Bundle/VariationBundle/Validator/VariantUniqueValidator.php
> [VariationBundle] CS fixes

- src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
| Fixed tickets | #2878
| Doc PR        | Sylius/Sylius-Docs#325
> [OrderBundle] Fixed controller config

- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.ProductVariant.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.Product.yml
| Bug fix?      | yes (probably)
Updated new fields on Product and ProductVariant to expose them via API.
> [Product] Updated product and product variant serialization

- features/backend/payment_methods.feature
- src/Sylius/Bundle/PaymentBundle/Resources/config/validation.xml
- src/Sylius/Bundle/PaymentBundle/Resources/translations/validators.en.yml
> [PaymentBundle] Fixed fee calculator validation

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductOption/create.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductOption/update.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductVariant/create.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductVariant/update.html.twig
> [WebBundle] Remove some duplicated form error messages

- app/config/config.yml
> Fix session config

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/checkout.yml
Little change to make sylius more api-friendly.
> Fixed checkout api route

- app/config/parameters.yml.dist
> Deleted duplicated Stripe publishable key parameter

- src/Sylius/Component/Registry/ServiceRegistry.php
I was impossible to find which class injected into registry was causing error. Not it will be easier and direct.
> [Registry] more info for invalid interface given

- src/Sylius/Component/Archetype/composer.json
> [Archetype] sylius/translation added to require in composer.json

- src/Sylius/Bundle/SearchBundle/Finder/OrmFinder.php
> [Search] Removed ucfirst From OrmFinder Facets Comparison

- src/Sylius/Bundle/WebBundle/Resources/views/Email/passwordReset.html.twig
> [WebBundle] Fixed generating url to reset password in email

- src/Sylius/Component/Attribute/composer.json
> [Attribute] Updated composer dependencies

- src/Sylius/Bundle/UserBundle/Controller/UserController.php
"prepere" should read "prepare".
> Fix small typo on method name

- app/migrations/Version20151015181310.php
> Fix payment method error by generating migrations for Fee calculator

- src/Sylius/Component/Variation/composer.json
> [Variation] sylius/translation added to require in composer.json

- features/frontend/products.feature
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/ProductBundle/Behat/ProductContext.php
- src/Sylius/Component/Core/Pricing/ChannelBasedCalculator.php
- src/Sylius/Component/Core/spec/Pricing/ChannelBasedCalculatorSpec.php
| Fixed tickets | https://github.com/Sylius/Sylius/issues/3253
There is another PR fixing this issue, but I think this fixes real source of the problem, which was bad ``ChannelBasedCalculator`` implementation. However, I know that @pjedrzejewski was thinking about some more generic solution, so I would appreciate some feedback ;)
> [Core] Fixed improper ChannelBasedCalculator implementation

- src/Sylius/Component/Taxonomy/composer.json
> [Taxonomy] sylius/translation added to require in composer.json

- features/currencies/currency_management.feature
- src/Sylius/Bundle/CurrencyBundle/Form/Type/CurrencyType.php
- src/Sylius/Bundle/CurrencyBundle/spec/Form/Type/CurrencyTypeSpec.php
- src/Sylius/Bundle/MoneyBundle/Behat/MoneyContext.php
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/currency.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Currency/_form.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Currency/macros.html.twig
- src/Sylius/Component/Currency/Model/Currency.php
- src/Sylius/Component/Currency/Model/CurrencyInterface.php
- src/Sylius/Component/Currency/spec/Model/CurrencySpec.php
Implement toggleable interface on currencies.
Fix phpspec directory on currencies component.
The currencies cannot be deleted.
> [Currency] Implement toggleable interface on currencies.

- src/Sylius/Bundle/UserBundle/Command/CreateUserCommand.php
- src/Sylius/Bundle/UserBundle/Command/DeleteUserCommand.php
Q  | A
Bug fix?  | no
License | MIT
Doc PR | -
> [User] Add user:create and user:delete commands

- composer.json
Now using \NumberFormatter in PHP.
> Remove unused mathiasverraes/money dependency in composer.json

- src/Sylius/Bundle/ResourceBundle/Behat/DefaultContext.php
> Fixed waitFor function

- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.Product.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.Option.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.OptionValue.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.Product.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.Variant.yml
- src/Sylius/Bundle/VariationBundle/Resources/config/serializer/Model.Option.yml
- src/Sylius/Bundle/VariationBundle/Resources/config/serializer/Model.OptionValue.yml
- src/Sylius/Bundle/VariationBundle/Resources/config/serializer/Model.Variant.yml
> [Product] Improve products serialization

- features/backend/shipping_methods.feature
- src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
- src/Sylius/Bundle/ResourceBundle/Behat/WebContext.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodType.php
- src/Sylius/Bundle/ShippingBundle/spec/Form/Type/ShippingMethodTypeSpec.php
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/shipping_method.yml
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ShippingMethod/_form.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ShippingMethod/macros.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ShippingMethod/show.html.twig
- src/Sylius/Component/Shipping/Model/ShippingMethod.php
- src/Sylius/Component/Shipping/Model/ShippingMethodInterface.php
- src/Sylius/Component/Shipping/spec/Model/ShippingMethodSpec.php
Implement toggleable interface on shipping methods.
Disable hability to delete shipping methods.
Fix some CS with PHPCS Fixer
> [Shipping Method] Implement toggleable interface on shipping methods.

- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/taxonomy.yml
> [Taxonomy] Sort taxonomies index list on backend by name

- src/Sylius/Bundle/FixturesBundle/DataFixtures/DataFixture.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadLocalesData.php
> [Fixtures] Load fakers with the available locales

- src/Sylius/Component/Shipping/composer.json
> [Shipping] Updated composer dependencies

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/show.html.twig
Hotfix for fa4d0f6ce93afc62b0d7e0da8ee046c7437a15bf
> Fix translation for backend product undelete btn, take 2

- src/Sylius/Bundle/SearchBundle/Indexer/ElasticsearchIndexer.php
| BC breaks?    |  no
| Fixed tickets | none, related to #3534
`ElasticsearchIndexer` executed `fos:elastica:populate` command with incorrect path to `console` on Windows. This PR changes the `ElasticsearchIndexer` so it calls the `PopulateCommand` directly without using the console.
I couldn't test it completely, but at least I changed the config.yml to use elasticsearch engine in the search and now the `php app\console sylius:search:index` gives me same result as `php app\console fos:elastica:populate` (missing setup for `fos_elastica`)
```
sylius_search:
engine: elasticsearch
```
> [SearchBundle] ElasticsearchIndexer is portable

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/order_item.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.OrderItem.yml
> [API] Fix order items endpoint

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/order_item.yml
> Allow for filtering the order items

- .php_cs
- bin/sylius-cs-fixer
@pjedrzejewski 
Cherry-pick with the fix for the sylius-cs-fixer
> Fix for sylius-cs-fixer

- vagrant/manifests/default.pp
- install php 5.5 on vagrant environment
- don't install phpunit from pear channel (phpunit is installed through composer)
- resolves #3544
- resolves #2311
> fixed puppet manifest

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/order_item.yml
> [API] Allow for updating order item

- src/Sylius/Component/Channel/composer.json
> [Channel] Updated composer dependencies

- src/Sylius/Component/Payment/composer.json
Inb4 questions:
**ServiceRegistry** from **Registry** component is used by the **DelegatingFeeCalculator**.
**Translation** component is used all over the place.
> [Payment] Updated composer dependencies

- src/Sylius/Component/Core/composer.json
> [Core] Removed FOS UserBundle dependency

- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
> [Core][Channel] Make hard coded channel resolver class a configurable parameter

- src/Sylius/Bundle/FlowBundle/README.md
> Fix SyliusFlowBundle readme bug with completing step

- app/migrations/Version20151118223453.php
- src/Sylius/Bundle/PaymentBundle/Resources/config/doctrine/model/PaymentMethodTranslation.orm.xml
No reason to limit it to 255 characters and I actually got an exception during fixtures loading, when lorem ipsum was too long for the database.
> Change payment method description field to text doctrine type

- src/Sylius/Component/Promotion/Model/Promotion.php
- src/Sylius/Component/Promotion/Model/PromotionInterface.php
> Fix issue when promotion couldn't be "restored"

- src/Sylius/Component/Product/Sluggable/ProductTranslationSlugEventListener.php
- src/Sylius/Component/Product/spec/Sluggable/ProductTranslationSlugEventListenerSpec.php
Not the best code quality, but it works for now :)
> [Product] Quick fix for duplicated product slugs after #3576

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
> [Core] Removed duplicate block permission definitions

- app/config/security.yml
- src/Sylius/Bundle/WebBundle/Controller/Backend/SecurityController.php
> [Core] Fixed user switch role

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
> Added CMF role allowing to preview unpublished content in frontend

- src/Sylius/Component/Report/Model/Report.php
I need to overwrite `unique` property of `Report::$code` in my project and I'm getting `Property MyComponent\Model\Report::$code does not exist` exception.
> [Report] Replace private variable declarations with protected ones

- CHANGELOG.md
- UPGRADE.md
- src/Sylius/Bundle/PayumBundle/DependencyInjection/Configuration.php
**BC Break**, related to changes in #3380.
> [Payum] Renamed payment_config configuration key to gateway_config

- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonChoiceType.php
This is a bit nicer list than just all taxons together. :)
> Group Taxons by Taxonomy for sylius_taxon_choice form

- composer.json
- composer.lock
http://symfony.com/blog/symfony-2-7-7-released
> Bumping symfony/symfony to 2.7.7 due to security issues

- features/frontend/cart_promotions_product.feature
- src/Sylius/Bundle/PromotionBundle/Behat/PromotionContext.php
Sometimes, "Ubu" was matched from "Newest products" sidebar.
> [Promotion] Made scenarios for product promotions more specific

- app/TestKernel.php
- behat.yml.dist
- src/Sylius/Bundle/CoreBundle/Behat/HookContext.php
- src/Sylius/Bundle/ResourceBundle/Behat/DefaultContext.php
- src/Sylius/Bundle/SearchBundle/Behat/SearchContext.php
- travis/suites/suite-javascript
- travis/suites/suite-no-javascript
Based on #3627.
Eg. `checkout` suite dropped form 1.6GB to 250MB, now we can run whole Behat in one command! :)
> [Behat] Drastically reduced memory usage

- src/Sylius/Bundle/WebBundle/Controller/Frontend/Account/OrderController.php
According to this PR #3601 and to this issue #3453
> [Security] Fix remaining ROLE_SYLIUS_ADMIN

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Payment/filterForm.html.twig
> Fix filter form cancel route for backend payment

- features/backend/locales.feature
- src/Sylius/Bundle/LocaleBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Locale/macros.html.twig
- src/Sylius/Component/Locale/Model/LocaleInterface.php
> [Locale]Add immutable code

- src/Sylius/Component/Channel/composer.json
> [Channel] Revert Doctrine ORM 2.5 dependency to 2.4

- src/Sylius/Bundle/CoreBundle/Form/Type/Rule/ContainsProductConfigurationType.php
- src/Sylius/Component/Core/Model/OrderItem.php
- src/Sylius/Component/Core/Model/OrderItemInterface.php
- src/Sylius/Component/Core/Promotion/Checker/ContainsProductRuleChecker.php
- src/Sylius/Component/Core/spec/Promotion/Checker/ContainsProductRuleCheckerSpec.php
> [Promotion] Allow to set required amount of items when using "contains product" rule

- app/migrations/Version20151208100841.php
- src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
- src/Sylius/Bundle/CoreBundle/Form/Type/ChannelType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Channel/macros.html.twig
- src/Sylius/Component/Core/Model/Channel.php
- src/Sylius/Component/Core/Model/ChannelInterface.php
> #3671 add defaultLocale and defaultCurrency to Channel model

- features/backend/shipping_categories.feature
- features/backend/shipping_methods.feature
- features/reports/reports.feature
- src/Sylius/Bundle/ReportBundle/Form/Type/ReportType.php
- src/Sylius/Bundle/ReportBundle/Resources/config/validation.xml
- src/Sylius/Bundle/ReportBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/ReportBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/ReportBundle/spec/Form/Type/ReportTypeSpec.php
- src/Sylius/Bundle/WebBundle/Behat/WebContext.php
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Report/macros.html.twig
- src/Sylius/Component/Report/Model/Report.php
- src/Sylius/Component/Report/Model/ReportInterface.php
- src/Sylius/Component/Report/spec/Model/ReportSpec.php
> [Report] Introduce immutable code for Report

- features/email/email_management.feature
- src/Sylius/Bundle/MailerBundle/Form/Type/EmailType.php
- src/Sylius/Bundle/MailerBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/MailerBundle/spec/Form/Type/EmailTypeSpec.php
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Email/macros.html.twig
- src/Sylius/Component/Mailer/Model/EmailInterface.php
> [Mailer] Introduce code to Mailer

- features/channels/channel_management.feature
- src/Sylius/Bundle/ChannelBundle/Form/Type/ChannelType.php
- src/Sylius/Bundle/ChannelBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/ChannelBundle/spec/Form/Type/ChannelTypeSpec.php
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Channel/macros.html.twig
- src/Sylius/Component/Channel/Model/ChannelInterface.php
> [Channel] Introduce code for channel

- features/backend/product_archetypes.feature
- src/Sylius/Bundle/ArchetypeBundle/Form/Type/ArchetypeType.php
- src/Sylius/Bundle/ArchetypeBundle/Resources/config/validation.xml
- src/Sylius/Bundle/ArchetypeBundle/spec/Form/Type/ArchetypeTypeSpec.php
- src/Sylius/Bundle/ProductBundle/Behat/ProductContext.php
- src/Sylius/Bundle/ProductBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductArchetype/macros.html.twig
- src/Sylius/Component/Archetype/Model/ArchetypeInterface.php
> [Archetype] Introduce code for archetype

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadCountriesData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadLocalesData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductsData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadZonesData.php
Q  | A
Bug fix?  | no
License | MIT
Doc PR | -
> [FixturesBundle]: Make some properties and methods protected for easier override

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDatabaseDriver.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/DoctrineODMDriver.php
` ->setFactory('sylius.controller.configuration_factory::createConfiguration') ` would also work.
> 2.7 Defintion deprecation fix

- app/TestKernel.php
The best solution I came into, however the following issues are still present:
- stateful classes that are not registered as services are stateful between scenarios
- `Sylius\Bundle\CoreBundle\Tests\MySqlDriver::$connection` is nulled at each kernel shutdown, forcing to create over a thousand of connections
> TestKernel restores default values on services' properties

- src/Sylius/Bundle/WebBundle/Menu/BackendMenuBuilder.php
Menu items for:
* General Settings
* Security Settings 
* Taxation Settings 
were checking for wrong(old) permissions
> [WebBundle][Admin] - correct permissions checks for backend menu

- src/Sylius/Bundle/ProductBundle/DependencyInjection/Compiler/ServicesPass.php
- src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ProductBundle/DependencyInjection/SyliusProductExtension.php
- src/Sylius/Bundle/ProductBundle/SyliusProductBundle.php
- src/Sylius/Component/Core/Model/Product.php
- src/Sylius/Component/Core/spec/Model/ProductSpec.php
- src/Sylius/Component/Product/Factory/ProductFactory.php
- src/Sylius/Component/Product/spec/Factory/ProductFactorySpec.php
> [Product] ProductFactory with variant setting in createNew()

- features/backend/taxonomies.feature
- src/Sylius/Bundle/ResourceBundle/Behat/WebContext.php
- src/Sylius/Bundle/TranslationBundle/GedmoHandler/TranslationSlugHandler.php
| Fixed tickets | https://github.com/Sylius/Sylius/issues/1624
> [Translation] Fixed bug while editing taxon permalink

- src/Sylius/Bundle/ResourceBundle/Form/DefaultFormFactory.php
| Fixed tickets | #3486 
Doctrine ORM and ODM have implementation divergences for ClassMetadata class
Is related to #2255
> workaround to fix DefaultFormFactory with ODM

- src/Sylius/Bundle/ShippingBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/Calculator/FlatRateConfigurationType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/Calculator/FlexibleRateConfigurationType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/Calculator/PerItemRateConfigurationType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/Calculator/VolumeRateConfigurationType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/Calculator/WeightRateConfigurationType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/Rule/ItemCountConfigurationType.php
- src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
- src/Sylius/Bundle/ShippingBundle/spec/Form/Type/Calculator/FlatRateConfigurationTypeSpec.php
- src/Sylius/Bundle/ShippingBundle/spec/Form/Type/Calculator/FlexibleRateConfigurationTypeSpec.php
- src/Sylius/Bundle/ShippingBundle/spec/Form/Type/Calculator/PerItemRateConfigurationTypeSpec.php
- src/Sylius/Bundle/ShippingBundle/spec/Form/Type/Calculator/VolumeRateConfigurationTypeSpec.php
- src/Sylius/Bundle/ShippingBundle/spec/Form/Type/Calculator/WeightRateConfigurationTypeSpec.php
- src/Sylius/Bundle/ShippingBundle/spec/Form/Type/Rule/ItemCountConfigurationTypeSpec.php
> [Shipping] [WIP] Remove configuration form validation groups

- composer.json
- composer.lock
- src/Sylius/Bundle/CoreBundle/composer.json
- src/Sylius/Bundle/ResourceBundle/composer.json
> Update composer to support jms/serializer-bundle 1.0+

- src/Sylius/Bundle/CoreBundle/Controller/ProductController.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/product_archetype.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductArchetype/macros.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductArchetype/productIndex.html.twig
Added browsing products from archetypes both via id and archetype code.
> [Archetype] Browse products via archetypes

- app/config/config.yml
- app/config/config_test.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/twig.xml
Logs and screenshots on `test` and `test_cached` environment should be easily viewed now on Travis.
> [Travis] Improved error reporting on Travis

- composer.json
- composer.lock
- src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php
- src/Sylius/Component/Channel/composer.json
See #3775 for reasoning behind this change.
Reverts #3726.
> [Core] Dropped support for Doctrine ORM 2.5

- src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/ValidAttributeValueValidatorSpec.php
- src/Sylius/Bundle/FixturesBundle/.travis.yml
- src/Sylius/Bundle/PaymentBundle/Form/Type/Calculator/FixedFeeCalculatorConfigurationType.php
- src/Sylius/Bundle/PaymentBundle/spec/Form/Type/Calculator/FixedFeeCalculatorConfigurationTypeSpec.php
> Last fixes to individual bundle dependencies

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineODMDriver.php
| Fixed tickets | #3859 
* fix argument to create Class Metada Definition
* add repository service definition in container
> [ResourceBundle] fix repository definition for odm driver

- src/Sylius/Bundle/AttributeBundle/DependencyInjection/SyliusAttributeExtension.php
> [Attribute] Removed commented code

- app/migrations/Version20160112125003.php
- src/Sylius/Bundle/CartBundle/Form/Type/CartType.php
- src/Sylius/Bundle/CartBundle/spec/Form/Type/CartTypeSpec.php
- src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Order.orm.xml
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/macros.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Cart/summary.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Checkout/Step/finalize.html.twig
- src/Sylius/Component/Order/Model/Order.php
- src/Sylius/Component/Order/Model/OrderInterface.php
Added posibility for user to input type some text (like some information about his order to the seller) before checkout this cart. Handled in finalize table and current orders. I'm not sure if the parameter name is correct so any suggestion are higly appreciated.
> [Order] added order additionalInformation

- src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
Allow people to use a custom repository for OrderItemUnit (which we have).
> Add support for custom repository to OrderItemUnit

- src/Sylius/Component/Core/README.md
- src/Sylius/Component/Pricing/README.md
- src/Sylius/Component/User/README.md
> Docs links in User, Pricing and Core components READMEs fix

- src/Sylius/Component/Order/Model/Adjustment.php
- src/Sylius/Component/Order/Model/Order.php
- src/Sylius/Component/Order/Model/OrderItem.php
- src/Sylius/Component/Order/Model/OrderItemUnit.php
- src/Sylius/Component/Order/spec/Model/AdjustmentSpec.php
Improvements on Adjustment model to ensure proper relation handling and totals on Adjustable entities.
PR based on #3842.
> [Order] Adjustment model improvement

- src/Sylius/Bundle/ThemeBundle/Resources/config/services.xml
- src/Sylius/Bundle/ThemeBundle/Translation/DependencyInjection/Compiler/ThemeAwareSourcesPass.php
- src/Sylius/Bundle/ThemeBundle/Translation/Finder/OrderingTranslationFilesFinder.php
- src/Sylius/Bundle/ThemeBundle/Translation/Finder/TranslationFilesFinder.php
- src/Sylius/Bundle/ThemeBundle/Translation/Finder/TranslationFilesFinderInterface.php
- src/Sylius/Bundle/ThemeBundle/spec/Translation/DependencyInjection/Compiler/ThemeAwareSourcesPassSpec.php
- src/Sylius/Bundle/ThemeBundle/spec/Translation/Finder/OrderingTranslationFilesFinderSpec.php
- src/Sylius/Bundle/ThemeBundle/spec/Translation/Finder/TranslationFilesFinderSpec.php
> [ThemeBundle] Ensuring that translation files are loaded in correct order

- src/Sylius/Component/Promotion/Generator/CouponGenerator.php
- src/Sylius/Component/User/Security/Generator/GeneratorInterface.php
- src/Sylius/Component/User/Security/Generator/PinGenerator.php
- src/Sylius/Component/User/Security/Generator/TokenGenerator.php
- src/Sylius/Component/User/Security/PasswordUpdater.php
- src/Sylius/Component/User/Security/TokenProvider.php
> Don't disable & enable Doctrine filters in loop while generating tokens/coupons

- features/user/users.feature
- src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
- src/Sylius/Bundle/UserBundle/EventListener/DefaultUsernameORMListener.php
- src/Sylius/Bundle/UserBundle/Resources/config/services.xml
- src/Sylius/Bundle/UserBundle/spec/EventListener/DefaultUsernameORMListenerSpec.php
> [UserBundle] Fix default username orm listener

- features/user/users.feature
- src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
- src/Sylius/Bundle/UserBundle/EventListener/DefaultUsernameORMListener.php
- src/Sylius/Bundle/UserBundle/Resources/config/services.xml
- src/Sylius/Bundle/UserBundle/spec/EventListener/DefaultUsernameORMListenerSpec.php
Seems like PR was green but only Scrutinizer passed and Travis was not run at all and I merged this PR at ~1AM today, oups. :) I will make Travis required in GitHub configuration which is possible now since some time already.
Reverts Sylius/Sylius#3970.
> Revert "[UserBundle] Fix default username orm listener"

- behat.yml.dist
- features/shop/cart_without_taxes.feature
- features/shop/checkout_with_offline_payment.feature
- src/Sylius/Behat/Context/Setup/ChannelContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Ui/CartContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Cart/CartSummaryPage.php
- src/Sylius/Behat/Page/Product/ProductShowPage.php
- src/Sylius/Behat/spec/Context/Setup/ChannelContextSpec.php
- src/Sylius/Behat/spec/Context/Ui/CartContextSpec.php
- src/Sylius/Behat/spec/Page/Cart/CartSummaryPageSpec.php
- src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Cart/summary.html.twig
According to scenarios for cart proposed in https://github.com/Sylius/Sylius/pull/3941, I open PR with first, simplest feature and it's implementation.
> [Cart] Cart without taxes scenario

- src/Sylius/Bundle/CoreBundle/Form/Type/CountryType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/LocaleType.php
| Fixed tickets | #3952 #3869 
Change from Symfony: https://github.com/symfony/symfony/pull/16681
> [CoreBundle] Locale and Country choices_as_values fix

- features/user/users.feature
- src/Sylius/Bundle/UserBundle/EventListener/DefaultUsernameORMListener.php
- src/Sylius/Bundle/UserBundle/Resources/config/services.xml
- src/Sylius/Bundle/UserBundle/spec/EventListener/DefaultUsernameORMListenerSpec.php
- src/Sylius/Bundle/WebBundle/Behat/WebContext.php
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Customer/show.html.twig
| Fixed tickets | #3939
Replaces #3970.
> [UserBundle] Fix default username listener

- src/Sylius/Bundle/AttributeBundle/Resources/config/serializer/Model.AttributeValue.yml
- src/Sylius/Component/Attribute/Model/AttributeValue.php
- src/Sylius/Component/Attribute/Model/AttributeValueInterface.php
- src/Sylius/Component/Attribute/spec/Model/AttributeValueSpec.php
| Fixed tickets | https://github.com/Sylius/Sylius/issues/3969
> Fix AttributeValue serialization config and add getCode()

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Payment/macros.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Shipment/macros.html.twig
> Fix updated twig method of getting country name on address

- src/Sylius/Component/Core/Taxation/OrderItemsTaxesByZoneApplicator.php
- src/Sylius/Component/Core/spec/Taxation/OrderItemsTaxesByZoneApplicatorSpec.php
| Fixed tickets | #4005 
Fixed taxes to units distribution. This will be covered by behat in #3993.
> [Order] Fixed order items taxes applicator

- etc/phpcs/common.php
- src/Sylius/Behat/Page/Product/ProductShowPage.php
- src/Sylius/Bundle/CoreBundle/Purger/QueryLoggerInterface.php
Since we use `-empty_return` we should use `-phpdoc_no_empty_return` too.
see https://github.com/Sylius/Sylius/pull/3784#issuecomment-176914186
> Code Style: no phpdoc_no_empty_return

- src/Sylius/Bundle/ChannelBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/MetadataBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ThemeBundle/spec/DependencyInjection/Compiler/ThemeRepositoryPassSpec.php
- src/Sylius/Bundle/UserBundle/Command/CreateUserCommand.php
- src/Sylius/Component/Archetype/Model/Archetype.php
- src/Sylius/Component/Archetype/Model/ArchetypeInterface.php
> Run "optimize imports" by PHPStorm

- etc/behat/suites/ui-cart.yml
- etc/behat/suites/ui-checkout.yml
- features/shop/cart_with_single_tax_rate.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Setup/TaxContext.php
- src/Sylius/Behat/Context/Setup/UserContext.php
- src/Sylius/Behat/Context/Setup/ZoneContext.php
- src/Sylius/Behat/Context/Ui/CartContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Cart/CartSummaryPage.php
- src/Sylius/Behat/spec/Context/Setup/TaxContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/UserContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/ZoneContextSpec.php
- src/Sylius/Bundle/AddressingBundle/DependencyInjection/Compiler/RegisterZoneFactoryPass.php
- src/Sylius/Bundle/AddressingBundle/Factory/ZoneFactory.php
- src/Sylius/Bundle/AddressingBundle/Factory/ZoneFactoryInterface.php
- src/Sylius/Bundle/AddressingBundle/spec/Factory/ZoneFactorySpec.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadZonesData.php
Next feature added for cart with single tax rate.
> [Cart] Scenarios for cart with single tax rate

- src/Sylius/Bundle/UserBundle/Form/EventSubscriber/CustomerRegistrationFormSubscriber.php
- src/Sylius/Bundle/UserBundle/Form/EventSubscriber/UserRegistrationFormSubscriber.php
- src/Sylius/Bundle/UserBundle/Form/Type/CustomerGuestType.php
- src/Sylius/Bundle/UserBundle/Form/Type/CustomerSimpleRegistrationType.php
- src/Sylius/Bundle/UserBundle/spec/Form/Type/CustomerRegistrationTypeSpec.php
Small renaming in order to be consistent.
> [User] Renaming form listeners to form subscribers

- src/Sylius/Behat/Context/Setup/UserContext.php
- src/Sylius/Behat/spec/Context/Setup/UserContextSpec.php
Change default username in ``UserContext`` favor of [this comment](https://github.com/Sylius/Sylius/pull/3993#discussion_r51475714).
> [Cart][Behat] Set default username to email

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrinePHPCRDriver.php
> [ResourceBundle] Add translation to DoctrinePHPCRDriver

- features/shop/apply_correct_tax_for_items_with_the_same_tax_rate.feature
- features/shop/not_applying_taxes_for_products_without_tax_category.feature
> [Cart][Behat] Fix cart features names

- features/shop/apply_correct_shipping_fee_on_order.feature
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Ui/CartContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Checkout/CheckoutAddressingStep.php
- src/Sylius/Behat/Page/Checkout/CheckoutPaymentStep.php
- src/Sylius/Behat/Page/Checkout/CheckoutShippingStep.php
- src/Sylius/Behat/spec/Context/Setup/ShippingContextSpec.php
This PR is based on https://github.com/Sylius/Sylius/pull/3999. I adds scenarios about shipment taxes in cart.
> [Cart] Cart with shipping fee scenarios

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/main.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Metadata/macros.html.twig
> [Metadata] Permissions fix, macros fix

- behat.yml
Added `behat.yml` boilerplate to make customizing Behat even easier!
> [Behat] Added default behat.yml extending behat.yml.dist

- features/shop/apply_correct_taxes_for_products_with_different_tax_rates_for_different_zones.feature
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/spec/Context/Setup/ShippingContextSpec.php
Based on https://github.com/Sylius/Sylius/pull/4032 and everything before. Please, hold on with review until it will be reasonable (for the psychical health of all of us :smile:)
> [Cart][Behat] Products with different rates for different zones

- src/Sylius/Component/Core/Model/ProductInterface.php
| BC breaks?    | yes (in fact not implementing these methods on your Product crashes Sylius :))
> [Core] Added price getters and setters to ProductInterface

- .travis.yml
- composer.json
- composer.lock
Added the feature files style check as discussed on #4006
> [WIP] Added feature files cs check on travis build

- src/Sylius/Component/Attribute/composer.json
According to this:
https://github.com/Sylius/Attribute/blob/master/Model/AttributeSubjectInterface.php#L14
Doctrine collections must be present ...
> Add  "doctrine/collections"

- etc/behat/suites/ui-cart.yml
- etc/behat/suites/ui-checkout.yml
- src/Sylius/Behat/Context/Setup/ChannelContext.php
- src/Sylius/Behat/Context/Setup/GeographicalContext.php
- src/Sylius/Behat/spec/Context/Setup/ChannelContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/GeographicalContextSpec.php
> [Behat] Extracted countries creating logic from ChannelContext to GeographicalContext

- features/backend/orders.feature
- src/Sylius/Bundle/WebBundle/Behat/WebContext.php
> Fix for #4098, applying #3978 again

- features/shop/apply_correct_shipping_fee_on_order.feature
- features/shop/apply_correct_shipping_fee_with_product_taxes_on_order.feature
- features/shop/apply_correct_shipping_fee_with_taxes_on_order.feature
- features/shop/apply_correct_tax_for_items_with_different_tax_rates.feature
- features/shop/apply_correct_tax_for_items_with_the_same_tax_rate.feature
- features/shop/apply_correct_taxes_based_on_customer_data.feature
- features/shop/apply_correct_taxes_for_products_with_different_tax_rates_for_different_zones.feature
- features/shop/apply_different_taxes_for_variants_with_different_tax_category.feature
- features/shop/checkout_with_offline_payment.feature
- features/shop/not_applying_taxes_for_products_without_tax_category.feature
- features/shop/round_taxes_on_order_item_level.feature
- src/Sylius/Behat/Context/Setup/GeographicalContext.php
- src/Sylius/Behat/Context/Setup/PaymentContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Setup/TaxContext.php
Added "the" to all "store" steps in new behat scenarios ;)
> [Behat] Minor semantic changes in cart features

- features/shop/apply_correct_shipping_fee_on_order.feature
- features/shop/apply_correct_shipping_fee_with_product_taxes_on_order.feature
- features/shop/apply_correct_tax_for_items_with_the_same_tax_rate.feature
- features/shop/apply_correct_taxes_based_on_customer_data.feature
- features/shop/not_applying_taxes_for_products_without_tax_category.feature
- src/Sylius/Behat/Context/Ui/CartContext.php
| Deprecations? | yes
* Removed redundant steps from scenarios
* Enhanced few scenarios
> [Behat] Remove redundant steps and enhance scenarios

- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourcesCollectionProviderSpec.php
Not worth creating an issue imo :)
Used a proper namespace so Travis build can run successfully. (See the [build](https://travis-ci.org/Sylius/SyliusResourceBundle/jobs/106633548#L567))
> [ResourceBundle] fixed Request class namespace in spec file

- behat.yml
It does not work as expected (tracking still applies) and causes much more mess and stress.
> Removed behat.yml

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php
> [Resource] Added missing use statement on translatable configuration

- src/Sylius/Component/Channel/Model/ChannelInterface.php
Fix incorrect parameter in doc block
> [Channel] Fix docs of setChannel function

- src/Sylius/Bundle/AddressingBundle/Form/EventListener/BuildAddressFormSubscriber.php
Q  | A
License | MIT
Doc PR | -
> [Addressing] Fix provinceCode field of AddressForm.

- src/Sylius/Bundle/AssociationBundle/composer.json
…dev for there is no 0.17 released version for SyliusResourceBundle, see https://github.com/videni/SyliusAssociationBundle/commit/850e9615d8164be045581fe897edd55c6ff65de0
> change the dependency package SyliusResourceBundle version to 0.17.*@dev

- etc/behat/services/contexts.xml
- features/shop/apply_correct_taxes_on_visitor_cart.feature
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Checkout/CheckoutSecurityStep.php
- src/Sylius/Behat/spec/Context/Setup/ShippingContextSpec.php
I've closed https://github.com/Sylius/Sylius/pull/4045 with the same changes, as it will be easier to me (with rebase) and for everybody else (with waiting for "Awaiting Review") ;)
This is the last episode of "Taxes and shipment scenarios" series, hope you'll enjoy it.
> [Cart][Behat] Scenarios for visitor's cart taxes

- features/shop/checkout_with_offline_payment.feature
- src/Sylius/Behat/Context/Setup/ShippingContext.php
> [Behat] Removed not perfect shipping step

- composer.json
- composer.lock
- src/Sylius/Component/Channel/composer.json
Fixes #4160 (related discussion there).
> Added zendframework/zend-stdlib:^2.0|^3.0 dependency for Sylius and Channel component

- app/migrations/Version20160216172655.php
- src/Sylius/Bundle/AssociationBundle/EventListener/LoadMetadataSubscriber.php
> [Association] Fix table name and add migration

- src/Sylius/Bundle/ThemeBundle/Form/Type/ThemeChoiceType.php
- src/Sylius/Bundle/ThemeBundle/Resources/config/services/services.xml
- src/Sylius/Bundle/ThemeBundle/spec/Form/Type/ThemeChoiceTypeSpec.php
Q | A
Bug fix? | yes
License | MIT
Doc PR | -
> [ThemeBundle] Fix theme choice form type class name

- src/Sylius/Behat/Context/Setup/SecurityContext.php
> [Behat] Fix user repository type hint in SecurityContext

- src/Sylius/Bundle/ChannelBundle/Context/FakeChannel/FakeChannelCollector.php
- src/Sylius/Bundle/ChannelBundle/Resources/views/FakeChannelCollector/layout.html.twig
> Catch the ChannelNotFoundException in WDT

- app/config/parameters.yml.dist
- src/Sylius/Bundle/CoreBundle/Resources/config/app/payum.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadPaymentMethodsData.php
> Remove payment methods configuration

- features/order/deleting_an_order.feature
Feature file with scenarios for deleting an order (#4153).
> [RFC][Behat] Deleting order feature file

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadChannelData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadOrdersData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductsData.php
| Fixed tickets | https://github.com/Sylius/Sylius/issues/4198, https://github.com/Sylius/Sylius/issues/4192
- removed getting unexisting reference ``Sylius.PaymentMethod.StripeCheckout``
- create only one channel in ``LoadChannelsData`` to avoid ``ChannelNotFoundException``
> [Fixtures] Fixed channel and payment errors

- src/Sylius/Behat/Context/Setup/ChannelContext.php
- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Setup/PaymentContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Setup/SecurityContext.php
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Setup/UserContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/spec/Context/Setup/ShippingContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/UserContextSpec.php
- src/Sylius/Component/Core/Test/Services/SharedStorage.php
- src/Sylius/Component/Core/Test/Services/SharedStorageInterface.php
- src/Sylius/Component/Core/spec/Test/Services/SharedStorageSpec.php
| Fixed tickets | https://github.com/Sylius/Sylius/issues/4193
> [Behat] Simplify SharedStorage methods

- src/Sylius/Bundle/UserBundle/Command/ChangePasswordCommand.php
- src/Sylius/Bundle/UserBundle/Command/DeleteUserCommand.php
Based on FosUserBundle command "fos:user:change-password"
> [UserBundle] Add command to change the password of a user

- src/Sylius/Bundle/ResourceBundle/.travis.yml
- src/Sylius/Bundle/ResourceBundle/Controller/ResourcesCollectionProvider.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourcesCollectionProviderSpec.php
- src/Sylius/Bundle/ResourceBundle/test/app/config/config.yml
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/Controller/BookApiTest.php
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/DataFixtures/ORM/more_books.yml
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/Responses/Expected/books/paginated_index_response.json
| Fixed tickets | https://github.com/Sylius/Sylius/issues/4211
> Add test for pagination in ResourceBundle (via API)

- features/promotion/reapplying_promotion_on_cart_change.feature
- features/promotion/receiving_discount_based_on_cart_quantity.feature
- features/promotion/receiving_discount_based_on_items_total.feature
- features/promotion/receiving_percentage_discount_on_shipping.feature
> [Behat] Fix features formating

- features/shop/checkout/checkout_with_paypal_payment.feature
- features/shop/checkout/checkout_with_paypal_payment_changing_the_payment_method.feature
- features/shop/checkout/checkout_with_paypal_payment_retrying_to_pay.feature
> [Checkout] More advance paypal checkout scenario

- features/shop/checkout/checkout_with_paypal_payment.feature
> [Checkout] Fix paypal express checkout scenario

- src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/SyliusPromotionExtension.php
- src/Sylius/Component/Promotion/Factory/ActionFactory.php
- src/Sylius/Component/Promotion/Factory/ActionFactoryInterface.php
- src/Sylius/Component/Promotion/spec/Factory/ActionFactorySpec.php
According to discussion about [promotion scenarios](https://github.com/Sylius/Sylius/pull/4199#issuecomment-185731781), there should be a custom promotion action factory with specialized methods.
> [Promotion] Implement custom promotion action factory

- src/Sylius/Bundle/CoreBundle/EventListener/OrderPaymentListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/spec/EventListener/OrderPaymentListenerSpec.php
| Fixed tickets | [comment](https://github.com/Sylius/Sylius/pull/4214#issuecomment-185824249) 
> [Payment][Core] PaymentProcessor clean up

- src/Sylius/Bundle/SearchBundle/DependencyInjection/Configuration.php
| New feature?  | no|yes
| BC breaks?    | no|yes
| Deprecations? | no|yes
| Fixed tickets | #2626 
Disabling filter tree merging as per @pjedrzejewski proposal.
Aside from this, how to configure a new facet? There are no docs on this bundle AFAIK.
I'm fighing trough this bundle on my current project.
> Allow override of search filters

- features/shop/promotion/apply_percentage_discount_promotion_on_order.feature
- features/shop/promotion/receiving_percentage_discount_promotion_on_order.feature
> [Behat][Promotion] Percentage discount promotions scenarios

- src/Sylius/Bundle/AddressingBundle/Controller/ProvinceController.php
- src/Sylius/Bundle/WebBundle/Resources/public/js/province-choices.js
> [AddressingBundle] Fixed rendering of province choice field in frontend checkout proccess

- app/migrations/Version20160212150554.php
- features/legacy/backend/products.feature
- src/Sylius/Bundle/CoreBundle/spec/Form/Type/ProductTranslationTypeSpec.php
- src/Sylius/Bundle/ProductBundle/Behat/ProductContext.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductTranslationType.php
- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/ProductTranslation.orm.xml
- src/Sylius/Bundle/ProductBundle/Resources/config/validation.xml
- src/Sylius/Bundle/ProductBundle/Resources/translations/validators.en.yml
> [Product] Removed the need of description

- features/promotion/receiving_fixed_discount_on_cart.feature
- features/promotion/receiving_percentage_discount_promotion_on_order.feature
- src/Sylius/Behat/Context/Ui/CartContext.php
- src/Sylius/Behat/spec/Context/Ui/CartContextSpec.php
Changes proposed according to newest promotion scenarios ([here](https://github.com/Sylius/Sylius/blob/master/features/promotion/receiving_percentage_discount_on_shipping.feature#L21) or [here](https://github.com/Sylius/Sylius/blob/master/features/promotion/receiving_discount_based_on_items_total.feature#L17)).
> [Behat][Promotion] Changed promotions total step

- features/promotion/receiving_discount_based_on_items_total.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/spec/Context/Setup/PromotionContextSpec.php
- src/Sylius/Component/Core/Factory/RuleFactory.php
- src/Sylius/Component/Core/Factory/RuleFactoryInterface.php
- src/Sylius/Component/Core/spec/Factory/RuleFactorySpec.php
Further promotion scenarios - this time for ``item count`` rule.
> [Behat][Promotion] Discount based on items total

- src/Sylius/Component/Cart/Event/CartEvent.php
- src/Sylius/Component/Cart/Event/CartItemEvent.php
> [Cart] Set subject in CartEvent and CartItemEvent

- features/promotion/receiving_percentage_discount_on_shipping.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/spec/Context/Setup/PromotionContextSpec.php
- src/Sylius/Component/Promotion/Factory/ActionFactory.php
- src/Sylius/Component/Promotion/Factory/ActionFactoryInterface.php
- src/Sylius/Component/Promotion/spec/Factory/ActionFactorySpec.php
> [Behat][Promotion] Shipping discount promotions

- src/Sylius/Bundle/WebBundle/Menu/BackendMenuBuilder.php
Add missing check on product association link
> [BackendMenu] Add check on product association link

- .travis.yml
Makes it running faster and prevents from trying to reach database.
> [Travis] No debug while calling app/console

- src/Sylius/Bundle/WebBundle/Menu/BackendMenuBuilder.php
Add missing check on product review association link. 
I also check the entire backend menu. That was the last.
> [BackendMenu] Add check on product review link

- features/promotion/reapplying_promotion_on_cart_change.feature
- src/Sylius/Behat/Context/Ui/CartContext.php
- src/Sylius/Behat/spec/Context/Setup/PromotionContextSpec.php
- src/Sylius/Behat/spec/Context/Ui/CartContextSpec.php
PR is based on https://github.com/Sylius/Sylius/pull/4270.
> [Behat][Promotion] Reapplying promotion on cart change

- etc/behat/services/contexts.xml
- etc/behat/suites.yml
- etc/behat/suites/domain_order.yml
- features/order/deleting_an_order.feature
- src/Sylius/Behat/Context/Domain/OrderContext.php
- src/Sylius/Behat/Context/Setup/AddressingContext.php
- src/Sylius/Behat/Context/Setup/CustomerContext.php
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Setup/PaymentContext.php
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/spec/Context/Domain/OrderContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/AddressingContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/CustomerContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/OrderContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/PaymentContextSpec.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/payum.yml
> [Behat] [Order] Deleting an order

- src/Sylius/Behat/Context/Setup/ProductContext.php
> [Behat] ProductContext redundatnt line

- etc/behat/services/contexts.xml
- src/Sylius/Behat/Context/Setup/UserContext.php
- src/Sylius/Behat/spec/Context/Setup/UserContextSpec.php
> [Behat] UserSetupContext refactoring

- etc/behat/services/contexts.xml
- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Setup/PaymentContext.php
- src/Sylius/Behat/Context/Setup/SecurityContext.php
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Setup/UserContext.php
- src/Sylius/Behat/spec/Context/Setup/ShippingContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/UserContextSpec.php
| Fixed tickets | [comment](https://github.com/Sylius/Sylius/pull/4235#discussion_r54007885)
> [Behat] [DX] Injecting shared storage as a first argument

- features/product/deleting_a_product_variant.feature
- features/product/prevent_deletion_of_purchased_product_variant.feature
> [Product] Deleting product variant features

- PULL_REQUEST_TEMPLATE.md
| Fixed tickets | If I had an issue to fix I would put it here with 'fixes #IT'
> Update PR template for autoclosing issues

- src/Sylius/Bundle/ThemeBundle/Translation/Translator.php
Take a look: https://blackfire.io/profiles/compare/cffdc8f6-e8d6-40e9-9357-af13642092ba/graph
Warming up translations: 5 min 36 s → 11.7 s
> [Theme] Translator was loading resources way too many times

- src/Sylius/Bundle/UserBundle/Doctrine/ORM/CustomerRepository.php
- src/Sylius/Bundle/UserBundle/Doctrine/ORM/UserRepository.php
- src/Sylius/Bundle/UserBundle/spec/Doctrine/ORM/CustomerRepositorySpec.php
- src/Sylius/Bundle/UserBundle/spec/Doctrine/ORM/UserRepositorySpec.php
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/customer.yml
> [User] Clean-up remaining references to soft-deletable for User and Customer

- app/migrations/Version20160229091707.php
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/create_validation_fail_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/create_with_user_validation_fail_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer/update_validation_fail_response.json
- src/Sylius/Bundle/UserBundle/Form/Type/CustomerProfileType.php
- src/Sylius/Bundle/UserBundle/Resources/config/doctrine/model/Customer.orm.xml
- src/Sylius/Bundle/UserBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/UserBundle/spec/Form/Type/CustomerProfileTypeSpec.php
- src/Sylius/Bundle/UserBundle/spec/Form/Type/CustomerTypeSpec.php
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Customer/_form.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Customer/show.html.twig
- src/Sylius/Component/User/Model/Customer.php
- src/Sylius/Component/User/Model/CustomerInterface.php
> [Customer] Added phone number to customer

- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
> [Core] Fix IntegerDistributor service name

- src/Sylius/Bundle/ThemeBundle/SyliusThemeBundle.php
- src/Sylius/Bundle/ThemeBundle/Tests/Translation/DependencyInjection/Compiler/TranslatorAliasingPassTest.php
- src/Sylius/Bundle/ThemeBundle/Tests/Translation/DependencyInjection/Compiler/TranslatorFallbackLocalesPassTest.php
- src/Sylius/Bundle/ThemeBundle/Tests/Translation/DependencyInjection/Compiler/TranslatorLoaderProviderPassTest.php
- src/Sylius/Bundle/ThemeBundle/Tests/Translation/DependencyInjection/Compiler/TranslatorResourceProviderPassTest.php
- src/Sylius/Bundle/ThemeBundle/Translation/DependencyInjection/Compiler/TranslatorFallbackLocalesPass.php
| Related tickets | fixes #4343
> [Theme] Support for fallback locales; integration tests for translation compiler passes

- src/Sylius/Bundle/WebBundle/Menu/BackendMenuBuilder.php
Move association types menu definition above child removal check and fix name typo
> [Admin Menu] Product association types definition fix 

- features/taxation/managing_tax_categories/adding_tax_category.feature
- features/taxation/managing_tax_categories/deleting_tax_category.feature
- features/taxation/managing_tax_categories/editing_tax_category.feature
- features/taxation/managing_tax_categories/tax_category_unique_code_validation.feature
- features/taxation/managing_tax_categories/tax_category_validation.feature
> Add initial admin CRUD scenarios for tax category

- features/product/deleting_a_product_variant.feature
| Related tickets | partially #4140
> [Behat] Remove redundant steps in product

- features/product/deleting_product.feature
| Related tickets | partially #4140 
> [Behat][Product] Product deletion scenarios

- features/promotion/deleting_coupon.feature
- features/promotion/preventing_deletion_of_coupons_in_use.feature
| Related tickets | partially #4140
> [Behat][Promotion] Added domain scenarios for coupon deletion

- app/migrations/Version20160226092329.php
- src/Sylius/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.xml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Payment/history.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Payment/macros.html.twig
- src/Sylius/Component/Payment/Model/Payment.php
- src/Sylius/Component/Payment/Model/PaymentInterface.php
- src/Sylius/Component/Payment/spec/Model/PaymentSpec.php
> [Payment] Remove softdeletable from Payment

- src/Sylius/Component/Core/Taxation/OrderItemsTaxesByZoneApplicator.php
- src/Sylius/Component/Core/spec/Taxation/OrderItemsTaxesByZoneApplicatorSpec.php
> [Core] Simplify adding adjustments to units in applicator

- features/legacy/reports/reports.feature
- src/Sylius/Bundle/CoreBundle/Resources/config/reports.xml
- src/Sylius/Bundle/CoreBundle/spec/Form/Type/DataFetcher/DataFetcherChoiceTypeSpec.php
- src/Sylius/Bundle/ReportBundle/Controller/ReportController.php
- src/Sylius/Bundle/ReportBundle/Form/EventListener/BuildReportDataFetcherFormSubscriber.php
- src/Sylius/Bundle/ReportBundle/Form/Type/ReportType.php
- src/Sylius/Bundle/ReportBundle/spec/Form/EventListener/BuildReportDataFetcherFormSubscriberSpec.php
- src/Sylius/Bundle/ReportBundle/spec/Form/Type/ReportTypeSpec.php
- src/Sylius/Component/Report/DataFetcher/DefaultDataFetchers.php
> [ReportBundle] Remove sylius_data_fetcher prefix

- etc/behat/services/contexts.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
| Related tickets | mentioned in [comment](https://github.com/Sylius/Sylius/pull/4315#issuecomment-190742690)
> [DX] Consistent service name

- composer.json
- composer.lock
| Related tickets | fixes #3928
> [Composer] Added webmozart/assert assertion library as a dependency

- src/Sylius/Bundle/AddressingBundle/Form/Type/CountryCodeChoiceType.php
> [AddressingBundle] Added sorting countries by name in form type

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductOptionData.php
| Doc PR          | Sylius/Sylius-Docs#X
Renamed for consistency
> [FixturesBundle] Update LoadProductOptionData presentation -> name

- src/Sylius/Bundle/UserBundle/Form/Type/CustomerRegistrationType.php
- src/Sylius/Bundle/UserBundle/spec/Form/Type/CustomerRegistrationTypeSpec.php
> [UserBundle] Add phone number to customer registration form.

- src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Product/show.html.twig
> [WebBundle]: Displaying product associations in frontend product page

- app/migrations/Version20160226091855.php
- etc/behat/services/contexts.xml
- etc/behat/suites/domain_order.yml
- features/order/deleting_an_order.feature
- src/Sylius/Behat/Context/Domain/OrderContext.php
- src/Sylius/Behat/Context/Domain/PaymentContext.php
- src/Sylius/Behat/Context/Domain/ShippingContext.php
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Transform/PaymentContext.php
- src/Sylius/Behat/spec/Context/Domain/OrderContextSpec.php
- src/Sylius/Behat/spec/Context/Domain/PaymentContextSpec.php
- src/Sylius/Behat/spec/Context/Domain/ShippingContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/OrderContextSpec.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Order.orm.xml
- src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Order.orm.xml
- src/Sylius/Component/Order/Model/Order.php
- src/Sylius/Component/Order/Model/OrderInterface.php
| Fixed tickets | #4140
Depends on #4235
> [Behat] Delete objects related to order during order deletion

- src/Sylius/Bundle/ThemeBundle/composer.json
> [Theme] [Composer] Updated ResourceBundle version

- UPGRADE.md
> update UPGRADE.md to add content migration instructions for v0.17.0

- src/Sylius/Component/Contact/Model/Request.php
Fix InvalidArgumentException throwing in `ResourceFormFactory`.
> Fix missing ResourceInterface in Contact Request model

- src/Sylius/Bundle/ResourceBundle/Resources/public/js/form-collection.js
> [ResourceBundle] Initialize form collection when DOM is ready

- src/Sylius/Behat/Context/Domain/ShippingContext.php
- src/Sylius/Behat/Context/Transform/LexicalContext.php
- src/Sylius/Behat/Context/Transform/SharedStorageContext.php
- src/Sylius/Behat/Context/Ui/CustomerContext.php
- src/Sylius/Behat/Context/Ui/PaypalContext.php
> [Behat] [DX] Missing final keyword

- src/Sylius/Bundle/UserBundle/Controller/UserController.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/4429
| Doc PR          | --
> [UserBundle] Fix UserController

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/macros.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/show.html.twig
| Related tickets | mentioned in #4410 
It doesn't solve the problem mentioned in #4410, but fixes problem which reveal that issue.
> [Orders] Fix order templates

- src/Sylius/Bundle/TaxonomyBundle/Resources/config/serializer/Model.Taxon.yml
> [TaxonomyBundle] Remove serialization relation to the obsolete taxonomy entity.

- etc/docker/README.md
- etc/docker/docker-compose.yml
- etc/docker/nginx/default.conf
- etc/docker/php/Dockerfile
- etc/docker/php/default.conf
- etc/docker/php/php.ini
With this Docker setup it's very easy to test drive all kind of services like Elasticsearch, Redis etc..
| Doc PR        | https://github.com/jverdeyen/Sylius/blob/feature-docker-development-environment/docker/README.md
> A Docker Compose configuration to develop in Docker containers.

- features/legacy/backend/taxonomy.feature
| Related tickets | fixes #4436
Sorry guys my bad when working on taxonomy removal!
> [Behat][Taxonomy] Add legacy tag and fix taxonomy feature file

- app/migrations/Version20160229145014.php
- etc/behat/services/contexts.xml
- etc/behat/suites.yml
- etc/behat/suites/domain_product.yml
- features/product/managing_products/deleting_product_variant.feature
- features/product/managing_products/prevent_deletion_of_purchased_product_variant.feature
- src/Sylius/Behat/Context/Domain/ProductContext.php
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/spec/Context/Domain/ProductContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/OrderContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/ProductContextSpec.php
- src/Sylius/Bundle/VariationBundle/Resources/config/doctrine/model/Variant.orm.xml
- src/Sylius/Component/Product/Model/Product.php
- src/Sylius/Component/Product/spec/Model/ProductSpec.php
- src/Sylius/Component/Variation/Model/Variant.php
- src/Sylius/Component/Variation/Model/VariantInterface.php
- src/Sylius/Component/Variation/spec/Model/VariantSpec.php
| Related tickets | partially #4140, resolves #2326
> [Behat] [Product] New behat for product feature

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductVariant/macros.html.twig
| Related tickets | fixes #4443 
> [Behat] Fix build

- src/Sylius/Bundle/WebBundle/Resources/translations/menu.en.yml
> Add missing translations

- features/promotion/receiving_fixed_discount_on_products_from_specific_taxon.feature
Scenarios are based on *Receiving fixed discount on cart* and *Receiving percentage discount on products from specific taxon*.
> [Behat][Promotion] Fixed discount on taxon scenarios

- etc/bin/build-package
- etc/bin/build-packages
- etc/bin/clean-package
- etc/bin/clean-packages
- etc/bin/install-package
- etc/bin/install-packages
- etc/bin/test-package
- etc/bin/test-packages
- etc/bin/validate-package
- etc/bin/validate-packages
Docs are coming (with these features included!) :tada:
> [DX] Improved developer experience while using etc/bin/* commands

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/locale.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/CoreBundle/Tests/Controller/LocaleApiTest.php
- src/Sylius/Bundle/CoreBundle/Tests/DataFixtures/ORM/resources/locales.yml
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/locale/create_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/locale/create_validation_fail_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/locale/index_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/locale/show_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/locale/update_response.json
- src/Sylius/Bundle/LocaleBundle/Resources/config/serializer/Model.Locale.yml
> Locale API: Routing + tests

- src/Sylius/Bundle/CoreBundle/Settings/GeneralSettingsSchema.php
- src/Sylius/Bundle/CoreBundle/Settings/TaxationSettingsSchema.php
> [CoreBundle] Fix some small deprecated calls

- src/Sylius/Bundle/CoreBundle/Tests/Controller/CountryApiTest.php
- src/Sylius/Bundle/CoreBundle/Tests/Controller/ProvinceApiTest.php
- src/Sylius/Bundle/CoreBundle/Tests/DataFixtures/ORM/resources/countries.yml
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/country/index_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/province/show_response.json
> Province api tests

- etc/behat/services.xml
- src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePageInterface.php
Rename edit page interface to update page interface.
> [Admin] Rename edit page interface

- Gulpfile.js
> [GULP] Remove coffee references in gulpfile

- app/migrations/Version20160310181749.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Order.orm.xml
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/4456
| Doc PR          | --
I know @gonzalovilaseca said he would submit a PR, but I just came across this and needed the fix.
> [CoreBundle] Fix coupon association

- src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Admin] Country translation

- app/migrations/Version20160212150554.php
- app/migrations/Version20160216172655.php
- app/migrations/Version20160225115200.php
- app/migrations/Version20160226091855.php
- app/migrations/Version20160229091707.php
- app/migrations/Version20160229125721.php
- app/migrations/Version20160229145014.php
- app/migrations/Version20160310181749.php
We should definitely keep in mind to check this in every PR, to avoid such a trivial pull request in the future ;)
> [Migration] Added missing license blocks to migrations

- src/Sylius/Bundle/UiBundle/Resources/views/Macro/common.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Menu/sidebar.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Metadata/show.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Common/forms.html.twig
| Doc PR          | Sylius/Sylius-Docs#X
> Twig "sameas" replaced by "same as"

- src/Sylius/Bundle/CoreBundle/Form/Type/LocaleType.php
- src/Sylius/Bundle/CoreBundle/Tests/Controller/LocaleApiTest.php
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/locale/create_validation_fail_response.json
- src/Sylius/Bundle/LocaleBundle/Form/Type/LocaleType.php
- src/Sylius/Bundle/LocaleBundle/spec/Form/Type/LocaleTypeSpec.php
> [Core] LocaleType fix

- etc/behat/services/contexts/ui.xml
- etc/behat/services/pages.xml
- etc/behat/suites.yml
- etc/behat/suites/ui/localization.yml
- features/localization/managing_locales/adding_locale.feature
- features/localization/managing_locales/locale_unique_code_validation.feature
- features/localization/managing_locales/locale_validation.feature
- features/localization/managing_locales/toggling_locale.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingLocaleContext.php
- src/Sylius/Behat/Page/Admin/Locale/CreatePage.php
- src/Sylius/Behat/Page/Admin/Locale/CreatePageInterface.php
- src/Sylius/Behat/spec/Context/Ui/Admin/ManagingLocaleContextSpec.php
- src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/locale.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/locale.yml
- src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Locale/Field/name.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Locale/_form.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Based on #4444,  #4395 and #4467
> [Admin] Locale feature

- etc/bash/common.lib.sh
- etc/bin/test-package
| Related tickets | phpspec/phpspec#886
> [Travis] Retry phpspec / phpunit package tests on failure

- app/migrations/Version20160308211004.php
> [taxon] - added missing migration for taxonomy to taxon change

- features/promotion/receiving_fixed_discount_on_products_from_specific_taxon.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/spec/Context/Setup/PromotionContextSpec.php
- src/Sylius/Behat/spec/Context/Setup/TaxonomyContextSpec.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Component/Core/Factory/ActionFactory.php
- src/Sylius/Component/Core/Factory/ActionFactoryInterface.php
- src/Sylius/Component/Core/Promotion/Action/ItemDiscountAction.php
- src/Sylius/Component/Core/Promotion/Action/ItemFixedDiscountAction.php
- src/Sylius/Component/Core/Promotion/Action/ItemPercentageDiscountAction.php
- src/Sylius/Component/Core/spec/Factory/ActionFactorySpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/ItemFixedDiscountActionSpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/ItemPercentageDiscountActionSpec.php
PR introduced new promotion action - ``item fixed discount``, which applies discount on all products (that could be also filtered with ``TaxonFilter``)
> [Promotion][Behat] Fixed discount on specific taxon

- .travis.yml
- etc/bin/test-package
- etc/travis/before-install-php.ini
- etc/travis/install-php.ini
> [Travis] Disabling OPCache while running phpspec

- src/Sylius/Bundle/ShippingBundle/Controller/ShipmentController.php
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/shipment.yml
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Macros/misc.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/_details.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/_paymentState.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/_shippingState.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Review/_form.html.twig
> [WebBundle] Show shipment transitions, Random fixes in displaying shipment and payment states

- src/Sylius/Bundle/UiBundle/Resources/private/js/app.js
> [Ui] Missing closing bracket in app.js

- src/Sylius/Component/Core/Promotion/Action/ItemDiscountAction.php
> [Core] Remove unnecessary methods

- src/Sylius/Bundle/InstallerBundle/Command/InstallDatabaseCommand.php
> [Installer] Improve display while installing Sylius

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductVariant/_form.html.twig
The field was missing.
In order to be more consistent, i rework just a little the form to match the masterVariant one.
Also, i added form_rest() at the end of form to prevent any missing fields (in usage, we will see them quickly)
> [WebBundle] Add missing field availableUntil

- features/installer/load_sample_data_command.feature
- src/Sylius/Behat/Context/Cli/InstallerContext.php
- src/Sylius/Bundle/InstallerBundle/Checker/CommandDirectoryChecker.php
- src/Sylius/Bundle/InstallerBundle/Command/InstallSampleDataCommand.php
| Fixed tickets | #4265 
Based on: #3814 waiting for merge
> [DX] Describe fixtures loading command with Behat scenarios

- src/Sylius/Bundle/ShippingBundle/Controller/ShipmentController.php
> [ShippingBundle] Fix shipAction to new resource bundle conventions

- features/localization/managing_locales/locale_unique_code_validation.feature
> [Behat] [Critical] Localization unique code validation feature fix

- .travis.yml
See https://github.com/composer/composer/issues/4884#issuecomment-195229989 :tada:
> [Travis] Remove setting Github OAuth Token in Composer as it is no longer needed

- src/Sylius/Bundle/OrderBundle/Controller/CommentController.php
> [Order] comment controller redirection broken

- etc/behat/services/contexts/ui.xml
- src/Sylius/Behat/Context/Ui/Admin/ManagingLocalesContext.php
- src/Sylius/Behat/spec/Context/Ui/Admin/ManagingLocalesContextSpec.php
> [Behat] Consistent context naming

- src/Sylius/Behat/Behaviour/ChoosesName.php
- src/Sylius/Behat/Behaviour/DocumentAccessor.php
- src/Sylius/Behat/Page/Admin/Country/CreatePage.php
In order to reduce code duplication we agreed to give traits a try, to check if they would fit our needs
> [RFC] [DX] [Behat] Traits usage in new behats

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/currency.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/CoreBundle/Tests/Controller/CurrencyApiTest.php
- src/Sylius/Bundle/CoreBundle/Tests/DataFixtures/ORM/resources/currencies.yml
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/currency/create_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/currency/create_validation_fail_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/currency/index_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/currency/show_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/currency/update_response.json
- src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/currency/update_validation_fail_response.json
- src/Sylius/Bundle/CurrencyBundle/Form/Type/CurrencyType.php
- src/Sylius/Bundle/CurrencyBundle/Resources/config/serializer/Model.Currency.yml
- src/Sylius/Bundle/CurrencyBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/CurrencyBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/CurrencyBundle/spec/Form/Type/CurrencyTypeSpec.php
> [API] Test currency

- etc/behat/services/contexts/domain.xml
- etc/behat/services/contexts/setup.xml
- etc/behat/services/contexts/ui.xml
- etc/behat/services/pages.xml
Started in #4540, but it was not enough. Added alphabetical sorting of pages and contexts.
> [Behat] Pages alphabetical ordering and fixes

- src/Sylius/Bundle/AddressingBundle/Resources/config/validation.xml
- src/Sylius/Bundle/AddressingBundle/Resources/translations/validators.en.yml
> Added min length message in zone form

- etc/behat/suites/ui/addressing.yml
- features/localization/managing_countries/country_unique_code_validation.feature
- src/Sylius/Behat/Context/Setup/GeographicalContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php
- src/Sylius/Behat/spec/Context/Ui/Admin/ManagingCountriesContextSpec.php
| Related tickets | partially #4374
> [Admin] Country code uniquness validation

- etc/behat/services/contexts/transform.xml
- etc/behat/suites/domain/order.yml
- etc/behat/suites/domain/product.yml
- etc/behat/suites/domain/promotion.yml
- etc/behat/suites/ui/addressing.yml
- etc/behat/suites/ui/cart.yml
- etc/behat/suites/ui/shipping.yml
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Transform/AddressingContext.php
- src/Sylius/Behat/Context/Transform/CountryContext.php
- src/Sylius/Behat/Context/Transform/CouponContext.php
- src/Sylius/Behat/Context/Transform/ProductContext.php
- src/Sylius/Behat/Context/Transform/ProductVariantContext.php
- src/Sylius/Behat/Context/Transform/PromotionContext.php
- src/Sylius/Behat/Context/Transform/ShippingContext.php
- src/Sylius/Behat/Context/Transform/ShippingMethodContext.php
- src/Sylius/Behat/Context/Transform/TaxCategoryContext.php
- src/Sylius/Behat/Context/Transform/TaxContext.php
- src/Sylius/Behat/Context/Transform/TaxonContext.php
- src/Sylius/Behat/Context/Transform/ThemeContext.php
- src/Sylius/Behat/Context/Transform/ZoneContext.php
- src/Sylius/Behat/spec/Context/Transform/AddressingContextSpec.php
- src/Sylius/Behat/spec/Context/Transform/CountryContextSpec.php
- src/Sylius/Behat/spec/Context/Transform/CouponContextSpec.php
- src/Sylius/Behat/spec/Context/Transform/ProductContextSpec.php
- src/Sylius/Behat/spec/Context/Transform/ProductVariantContextSpec.php
- src/Sylius/Behat/spec/Context/Transform/PromotionContextSpec.php
- src/Sylius/Behat/spec/Context/Transform/ShippingContextSpec.php
- src/Sylius/Behat/spec/Context/Transform/TaxCategoryContextSpec.php
> [Behat] [DX] Transformers cleanup

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/locale.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Country/Field/name.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Locale/Field/name.html.twig
> [UI] Critical improvement to new locales and countries interface

- features/addressing/managing_countries/adding_country.feature
- features/addressing/managing_countries/country_unique_code_validation.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php
| Related tickets | [comment] (https://github.com/Sylius/Sylius/pull/4539#discussion_r56791634) and changed localization introduced in #4533
> [Behat] Addressing features typo and localization fixes

- src/Sylius/Behat/Context/Domain/PromotionContext.php
- src/Sylius/Behat/Context/Transform/SharedStorageContext.php
- src/Sylius/Behat/spec/Context/Domain/PromotionContextSpec.php
- src/Sylius/Behat/spec/Context/Transform/SharedStorageContextSpec.php
This transformer could generate some strange behaviour, so I decide to remove it
> [DX] SharedStorage clean-up

- src/Sylius/Bundle/AttributeBundle/EventListener/LoadMetadataSubscriber.php
- src/Sylius/Bundle/AttributeBundle/spec/EventListener/LoadMetadataSubscriberSpec.php
| Related tickets | fixes #4578
> [Bug Fix] Add values one-to-many relationship on attribute model

- src/Sylius/Behat/spec/Context/Domain/PromotionContextSpec.php
> [DX] Removed redundant lines

- src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php
> [Behat] Semantic fix in ManagingCountriesContext

- features/addressing/managing_countries/adding_country.feature
- features/addressing/managing_countries/country_unique_code_validation.feature
- features/addressing/managing_countries/editing_country.feature
- features/channel/managing_themes_per_channel.feature
- features/locale/managing_locales/adding_locale.feature
- features/locale/managing_locales/locale_unique_code_validation.feature
- features/locale/managing_locales/locale_validation.feature
- features/locale/managing_locales/toggling_locale.feature
- features/product/managing_products/deleting_product.feature
- features/shipping/managing_shipping_methods/deleting_shipping_method.feature
- features/shipping/managing_shipping_methods/prevent_deletion_of_used_shipping_method.feature
- features/taxation/managing_tax_categories/adding_tax_category.feature
- features/taxation/managing_tax_categories/deleting_tax_category.feature
- features/taxation/managing_tax_categories/editing_tax_category.feature
- features/taxation/managing_tax_categories/tax_category_validation.feature
- features/user/managing_users/deleting_account.feature
- src/Sylius/Behat/Context/Setup/SecurityContext.php
> [DX] Add 'an' to administrator log in step

- etc/behat/suites.yml
> [Behat][Critical] Sort suites imports alphabetically

- etc/behat/services/contexts/setup.xml
- etc/behat/services/contexts/ui.xml
- etc/behat/services/pages.xml
- etc/behat/suites.yml
- etc/behat/suites/ui/cart.yml
- etc/behat/suites/ui/taxation.yml
- features/taxation/managing_tax_categories/deleting_tax_category.feature
- src/Sylius/Behat/Context/Setup/TaxationContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxCategoryContext.php
- src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
- src/Sylius/Behat/Page/Admin/Crud/IndexPageInterface.php
- src/Sylius/Behat/Service/Accessor/NotificationAccessor.php
- src/Sylius/Behat/spec/Context/Setup/TaxationContextSpec.php
- src/Sylius/Behat/spec/Context/Ui/Admin/ManagingTaxCategoryContextSpec.php
> [Admin] Tax category deletion

- src/Sylius/Component/Core/Provider/ActivePromotionsByChannelProvider.php
- src/Sylius/Component/Core/spec/Provider/ActivePromotionsByChannelProviderSpec.php
> [Core] Throw proper exception in ActivePromotionsByChannelProvider

- etc/bash/packages.lib.sh
- etc/bin/install-package
- etc/bin/install-packages
> [Critical] Caching Composer dependencies at Travis

- src/Sylius/Behat/Service/Accessor/NotificationAccessor.php
> [DX] NotificationAccessor fix

- src/Sylius/Bundle/ResourceBundle/Controller/NewResourceFactoryInterface.php
> [ResourceBundle] Fix use statement for doc comment

- src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
Adjust #4573 to changes introduced in #4545
> [Critical] Fix behat build

- PULL_REQUEST_TEMPLATE.md
- docs/PULL_REQUEST_TEMPLATE.md
- docs/README.md
- docs/contributing/documentation/overview.rst
> [ci skip] Clean up documentation merged into main repo

- composer.json
- composer.lock
After merging [ApiTestCase #58](https://github.com/Lakion/ApiTestCase/pull/58) we can finally removed this dependency
> [Composer] Update ApiTestCase dependency

- features/shipping/apply_correct_shipping_fee_with_product_taxes_on_order.feature
- features/shipping/apply_correct_shipping_fee_with_taxes_on_order.feature
- features/taxation/apply_correct_taxes_based_on_customer_data.feature
- features/taxation/apply_correct_taxes_for_products_with_different_tax_rates_for_different_zones.feature
- features/taxation/apply_correct_taxes_on_visitor_cart.feature
- src/Sylius/Behat/Context/Setup/ZoneContext.php
- src/Sylius/Behat/spec/Context/Setup/ZoneContextSpec.php
> [Behat] [DX] Zones sematical fixes

- features/promotion/receiving_discount_based_on_items_from_specific_taxons.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Context/Transform/TaxonContext.php
- src/Sylius/Behat/spec/Context/Setup/PromotionContextSpec.php
- src/Sylius/Behat/spec/Context/Transform/TaxonContextSpec.php
- src/Sylius/Component/Core/Factory/RuleFactory.php
- src/Sylius/Component/Core/Factory/RuleFactoryInterface.php
- src/Sylius/Component/Core/Promotion/Checker/TaxonRuleChecker.php
- src/Sylius/Component/Core/spec/Factory/RuleFactorySpec.php
Fix from separate PR: https://github.com/Sylius/Sylius/pull/4595
> [Promotion] Discount based on items from specific taxons

- etc/behat/services.xml
- etc/behat/services/contexts/ui.xml
- etc/behat/services/pages.xml
I have moved out page services from services.xml and also renamed `NotificationAccessor` to keep current convention. Any better idea for service naming?
> [RFC] [DX] Behat services clean up

- features/promotion/receiving_discount_based_on_number_of_items_from_specific_taxon.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Context/Setup/TaxonomyContext.php
- src/Sylius/Behat/spec/Context/Setup/PromotionContextSpec.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Component/Core/Factory/RuleFactory.php
- src/Sylius/Component/Core/Factory/RuleFactoryInterface.php
- src/Sylius/Component/Core/Promotion/Checker/ContainsTaxonRuleChecker.php
- src/Sylius/Component/Core/spec/Factory/RuleFactorySpec.php
- src/Sylius/Component/Core/spec/Promotion/Checker/ContainsTaxonRuleCheckerSpec.php
| Bug fix?        | np
| Related tickets | partially https://github.com/Sylius/Sylius/issues/4194
> [Behat][Promotion] Discount based on number of products from taxon

- features/taxation/managing_tax_rates/editing_tax_rate.feature
| Related tickets | [comment](https://github.com/Sylius/Sylius/pull/4624#discussion_r57720395)
> [DX] [Behat] Tax rate sematic fix

- etc/behat/services.xml
- src/Sylius/Behat/Service/Accessor/NotificationAccessor.php
- src/Sylius/Behat/Service/NotificationChecker.php
- src/Sylius/Behat/spec/Service/NotificationCheckerSpec.php
| Related tickets | [comment about class parameter](https://github.com/Sylius/Sylius/pull/4622#discussion_r58011001) and [comment about asserted sentence](https://github.com/Sylius/Sylius/pull/4622#discussion_r58010104)
> [Behat] Fix notification checker

- etc/behat/services/contexts/setup.xml
- src/Sylius/Behat/Context/Setup/LocaleContext.php
- src/Sylius/Behat/spec/Context/Setup/LocaleContextSpec.php
- src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
- src/Sylius/Bundle/ResourceBundle/Behat/DefaultContext.php
- src/Sylius/Component/Locale/Converter/LocaleNameConverter.php
- src/Sylius/Component/Locale/Converter/LocaleNameConverterInterface.php
- src/Sylius/Component/Locale/spec/Converter/LocaleNameConverterSpec.php
| New feature?    | https://github.com/Sylius/Sylius/issues/4614
| Related tickets | https://github.com/Sylius/Sylius/issues/4614
> [Locale] Locale name converter

- etc/behat/services.xml
- etc/behat/services/contexts/ui.xml
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxCategoryContext.php
- src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
- src/Sylius/Behat/Page/Admin/Crud/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/Crud/PageWithFormInterface.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePageInterface.php
- src/Sylius/Behat/Service/CurrentPageResolver.php
- src/Sylius/Behat/Service/CurrentPageResolverInterface.php
- src/Sylius/Behat/spec/Context/Ui/Admin/ManagingTaxCategoryContextSpec.php
- src/Sylius/Behat/spec/Service/CurrentPageResolverSpec.php
> [Behat] Current page resolver

- etc/behat/services/contexts/ui.xml
- features/taxation/managing_tax_rates/tax_rate_validation.feature
- src/Sylius/Behat/Context/Setup/TaxationContext.php
- src/Sylius/Behat/Context/Setup/ZoneContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxRateContext.php
- src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
- src/Sylius/Behat/Page/Admin/TaxRate/CreatePage.php
- src/Sylius/Bundle/CoreBundle/Resources/config/validation.xml
- src/Sylius/Bundle/TaxationBundle/Resources/translations/validators.en.yml
> [Admin] Tax rate validation features

- composer.json
- composer.lock
- src/Sylius/Bundle/CoreBundle/Kernel/Kernel.php
- src/Sylius/Bundle/CoreBundle/composer.json
- src/Sylius/Bundle/LocaleBundle/composer.json
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/create.html.twig
> [Composer] Removed A2lix/TranslationFormBundle dependency

- src/Sylius/Behat/Page/Admin/TaxCategory/UpdatePage.php
- src/Sylius/Behat/Page/Admin/TaxRate/CreatePage.php
- src/Sylius/Behat/Page/Admin/TaxRate/UpdatePage.php
> [DX] [Behat] Optimize imports

- src/Sylius/Bundle/CoreBundle/Checkout/CheckoutProcessScenario.php
> [Checkout] Changed method to protected to be able to inherit

- src/Sylius/Bundle/ReviewBundle/Doctrine/ORM/ReviewRepository.php
- src/Sylius/Bundle/WebBundle/Resources/config/routing/partial/main.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/partial/product_review.yml
- src/Sylius/Component/Review/Repository/ReviewRepositoryInterface.php
I've fixed reviews limit on product page and also added review repository interface
> [Review] Fixed reviews limit

- src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
> [Behat] Element not found exception fix

- src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelper.php
- src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelperInterface.php
- src/Sylius/Bundle/LocaleBundle/Twig/LocaleExtension.php
- src/Sylius/Bundle/LocaleBundle/spec/Templating/Helper/LocaleHelperSpec.php
- src/Sylius/Bundle/LocaleBundle/spec/Twig/LocaleExtensionSpec.php
Rendering of translation has never been prettier 
||
\/
> [Twig] Locale extension refactoring + introducing locale name filter

- app/migrations/Version20160405103129.php
- src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionType.php
- src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/Promotion.orm.xml
- src/Sylius/Bundle/PromotionBundle/Resources/config/validation.xml
- src/Sylius/Component/Core/Promotion/Action/DiscountAction.php
- src/Sylius/Component/Core/Promotion/Action/ItemDiscountAction.php
- src/Sylius/Component/Core/spec/Promotion/Action/FixedDiscountActionSpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/ItemFixedDiscountActionSpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/ItemPercentageDiscountActionSpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/PercentageDiscountActionSpec.php
> [Promotion] Make description not required

- src/Sylius/Bundle/AttributeBundle/spec/DependencyInjection/Compiler/RegisterAttributeFactoryPassSpec.php
- src/Sylius/Bundle/AttributeBundle/spec/DependencyInjection/Compiler/RegisterAttributeTypePassSpec.php
- src/Sylius/Bundle/RbacBundle/spec/Form/EventSubscriber/AddParentFormSubscriberSpec.php
- src/Sylius/Bundle/ReportBundle/spec/DependencyInjection/Compiler/RegisterDataFetcherPassSpec.php
- src/Sylius/Bundle/ReportBundle/spec/DependencyInjection/Compiler/RegisterRenderersPassSpec.php
- src/Sylius/Bundle/ResourceBundle/Form/EventSubscriber/AddCodeFormSubscriber.php
- src/Sylius/Bundle/ResourceBundle/spec/Form/EventSubscriber/AddCodeFormSubscriberSpec.php
> fix some specs that where not testing anything

- features/promotion/managing_promotions/preventing_deletion_of_promotions_in_use.feature
- features/promotion/reapplying_promotion_on_cart_change.feature
- features/promotion/receiving_discount_based_on_cart_quantity.feature
- features/promotion/receiving_discount_based_on_items_total.feature
- features/promotion/receiving_fixed_discount_on_cart.feature
- features/promotion/receiving_percentage_discount_on_shipping.feature
- features/promotion/receiving_percentage_discount_promotion_on_order.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
> [Behat] Remove unnecessary "fixed" and "discount" words from steps

- src/Sylius/Bundle/MetadataBundle/Form/Type/Custom/PageMetadataType.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/4734
> [Metadata] reverse transform keywords properly

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadShippingData.php
> [FixturesBundle]: Added enable/disable status to shipping data fixture.

- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/promotion.yml
Just fixes a minor "yml starting with @" deprecation we face in our application.
> Fix yml deprecation

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/4712
> [CoreBundle] Fix usage of getAlias()

- src/Sylius/Bundle/UiBundle/Resources/private/js/app.js
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
> [Semantic Ui] [RFC] Fix problematic dropdown generation

- src/Sylius/Bundle/CoreBundle/EventListener/CartBlamerListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/spec/EventListener/CartBlamerListenerSpec.php
| BC breaks?      | yes (changed public methods names)
Improved specs, naming and made it dry.
> [Core] Refactor cart blamer listener

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/history.html.twig
| Related tickets | fixes #4720 
> [Order] Remove 'deleted' twig call in order history

- src/Sylius/Bundle/CurrencyBundle/Resources/config/templating.xml
- src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelper.php
- src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelperInterface.php
- src/Sylius/Bundle/CurrencyBundle/spec/Templating/Helper/CurrencyHelperSpec.php
| Related tickets | [comment](https://github.com/Sylius/Sylius/pull/4681#issuecomment-208202704)
> [Currency] Show base instead of current currency

- src/Sylius/Bundle/SettingsBundle/Doctrine/EventListener/ParameterTransformerListener.php
When transforming our theme settings I expected to see ID to be saved but instead we saw,
```
You cannot serialize or unserialize PDO instances
```
It was because you have to tell doctrine to re-compute the entity's change-set!
> [SettingsBundle] Recompute doctrine change-set after transforming settings

- etc/behat/services/contexts/transform.xml
- etc/behat/suites/ui/promotion.yml
- features/promotion/receiving_discount_based_on_nth_order.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Context/Transform/UserContext.php
- src/Sylius/Bundle/ResourceBundle/Behat/DefaultContext.php
- src/Sylius/Component/Core/Factory/RuleFactory.php
- src/Sylius/Component/Core/Factory/RuleFactoryInterface.php
- src/Sylius/Component/Core/Promotion/Checker/NthOrderRuleChecker.php
- src/Sylius/Component/Core/spec/Factory/RuleFactorySpec.php
- src/Sylius/Component/Core/spec/Promotion/Checker/NthOrderRuleCheckerSpec.php
| Related tickets | mentioned in https://github.com/Sylius/Sylius/issues/4194
> [Behat][Promotion] Discount based on nth order

- src/Sylius/Bundle/ReviewBundle/Resources/public/js/sylius-review.js
- src/Sylius/Bundle/WebBundle/Resources/views/Frontend/layout.html.twig
Remove hardcoded selector for flash message
> [ProductReview] flash message fix

- app/migrations/Version20160203224648.php
| Related tickets | fixes #4753 introduced by PR #4237
Tested and working in my project (up & down)
> [OptionValue] Update translation migrations to copy data between tables

- src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
> [Behat] Allowing to check validation for nested children

- src/Sylius/Component/Order/Model/Order.php
| Related tickets | fixes #4727
> [Order] Fix bug in Order model

- src/Sylius/Bundle/CurrencyBundle/Templating/Helper/CurrencyHelper.php
- src/Sylius/Bundle/CurrencyBundle/Twig/CurrencyExtension.php
- src/Sylius/Bundle/CurrencyBundle/spec/Templating/Helper/CurrencyHelperSpec.php
> [Currency] Fix wrong twig helper call

- src/Sylius/Component/Core/Accessor/ProductAccessor.php
> [Search] fixed search indexing

- etc/behat/suites/cli/installer.yml
- etc/behat/suites/domain/order.yml
- etc/behat/suites/domain/product.yml
- etc/behat/suites/domain/promotion.yml
- etc/behat/suites/ui/addressing.yml
- etc/behat/suites/ui/cart.yml
- etc/behat/suites/ui/channel.yml
- etc/behat/suites/ui/checkout.yml
- etc/behat/suites/ui/locale.yml
- etc/behat/suites/ui/product.yml
- etc/behat/suites/ui/promotion.yml
- etc/behat/suites/ui/shipping.yml
- etc/behat/suites/ui/theme.yml
- etc/behat/suites/ui/user.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/country.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/locale.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/tax_category.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/tax_rate.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
> [DX] Yaml cleanup

- src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
- src/Sylius/Behat/Page/Admin/Crud/IndexPageInterface.php
- src/Sylius/Behat/Service/Accessor/TableAccessor.php
- src/Sylius/Behat/Service/Accessor/TableAccessorInterface.php
> [Behat] [DX] Table row counter on index page

- src/Sylius/Bundle/UserBundle/Command/CreateUserCommand.php
Remove Rbac roles from CreateUserBundle. It removes coupling with SyliusRbacBundle.
> [UserBundle] remove Rbac roles from create user command

- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
> [Core] - added missing email template translation keys

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/country.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/locale.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/create.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/update.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Form/_cancelButton.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Form/_create.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Form/_saveChanges.html.twig
> [Admin] Redirect to index when cancelling action

- src/Sylius/Behat/Exception/NotificationExpectationMismatchException.php
- src/Sylius/Behat/NotificationType.php
- src/Sylius/Behat/Service/Accessor/NotificationAccessor.php
- src/Sylius/Behat/Service/Accessor/NotificationAccessorInterface.php
- src/Sylius/Behat/Service/NotificationChecker.php
- src/Sylius/Behat/Service/NotificationCheckerInterface.php
- src/Sylius/Behat/spec/NotificationTypeSpec.php
- src/Sylius/Behat/spec/Service/NotificationCheckerSpec.php
> [Behat] Notification checker refactoring

- features/promotion/complex_promotions.feature
- features/promotion/receiving_percentage_discount_on_shipping.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Context/Setup/TaxonomyContext.php
- src/Sylius/Behat/Context/Transform/ProductContext.php
- src/Sylius/Behat/Context/Transform/TaxonContext.php
- src/Sylius/Behat/Context/Ui/CartContext.php
| Related tickets | mentioned in https://github.com/Sylius/Sylius/issues/4194
Part of scenarios written in *Promotion examples*. Next will be added when new promotions features will be implemented.
> [Behat][Promotion] Complex promotions scenarios

- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
> Fix the installer setup command

- .travis.yml
- etc/travis/prepare-memcached-extension
- src/Sylius/Bundle/ThemeBundle/Resources/config/services/translations.xml
| Related tickets | fixes every build
Needs Travis cache to be cleared.
> [Travis] Use Trusty beta (in order to install Chrome)

- src/Sylius/Component/Core/Promotion/Checker/NthOrderRuleChecker.php
- src/Sylius/Component/Core/spec/Promotion/Checker/NthOrderRuleCheckerSpec.php
> [Core] Quick fixes in NthOrderRuleChecker

- composer.json
- composer.lock
- src/Sylius/Behat/Service/CurrentPageResolver.php
- src/Sylius/Behat/spec/Service/CurrentPageResolverSpec.php
> [Composer] Use stable symfony-cmf/routing-bundle dependency

- src/Sylius/Bundle/AdminBundle/Resources/config/grids.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
> [DX] [Admin] Routing and grids sorted alphabetically

- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadOrdersData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadProductsData.php
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php
Speed up fixtures by reducing the number of data being loaded since it does not need to be so big.
> [Fixtures] Speed up fixtures

- src/Sylius/Bundle/ContentBundle/Resources/rdf-mappings/Sylius.Bundle.ContentBundle.Document.StringBlock.xml
| Related tickets | fixes #4699
> [Content] Add missing RDF mapping for StringBlock

- Gulpfile.js
- features/promotion/managing_promotions/adding_promotion_with_action.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Behat/Page/Admin/Promotion/CreatePage.php
- src/Sylius/Behat/Page/Admin/Promotion/CreatePageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Promotion/_form.html.twig
- src/Sylius/Bundle/PromotionBundle/Form/Type/ActionType.php
For now, implemented scenario for adding promotion with simple, fixed discount action.
> [Admin][Promotion] Adding promotion with action feature

- src/Sylius/Bundle/CoreBundle/Resources/config/app/cmf.yml
| Related tickets | fixes #4716
Solution proposed by @Niiko [here](https://github.com/Sylius/Sylius/issues/4716#issuecomment-206865930).
> [Content] Enable persistance in cmf to prevent from uninitialized service

- src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePageInterface.php
- src/Sylius/Behat/Page/Admin/TaxCategory/UpdatePage.php
- src/Sylius/Behat/Page/Admin/TaxCategory/UpdatePageInterface.php
> [Behat] Relocate hasResourceValues method

- .travis.yml
- etc/travis/suites/application/script/test-behat-with-javascript
- etc/travis/suites/application/script/test-behat-without-javascript
> [Travis] Bunch of improvements

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
| Related tickets | fixes #3815, #4707
Replaces https://github.com/Sylius/Sylius/pull/3885.
> [User] Add missing users permissions

- src/Sylius/Bundle/CartBundle/DependencyInjection/SyliusCartExtension.php
| Related tickets | fixes ##4710
> [Cart] Fix Cart repository reference

- docs/book/installation.rst
- docs/contributing/code/patches.rst
> [Docs] Bump PHP version also in the documentation

- etc/behat/services/contexts/ui.xml
- etc/behat/suites/ui/promotion/managing_promotions.yml
- features/promotion/managing_promotions/adding_promotion.feature
- features/promotion/managing_promotions/adding_promotion_with_action.feature
- features/promotion/managing_promotions/adding_promotion_with_rule.feature
- features/promotion/managing_promotions/deleting_promotion.feature
- features/promotion/managing_promotions/editing_promotion.feature
- features/promotion/managing_promotions/preventing_deletion_of_promotions_in_use.feature
- features/promotion/managing_promotions/promotion_validation.feature
- src/Sylius/Behat/Context/Domain/PromotionContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Behat/Page/Admin/Promotion/CreatePage.php
- src/Sylius/Behat/Page/Admin/Promotion/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/Promotion/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Promotion/UpdatePageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/promotion.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Promotion/Field/codeExclusiveAndCouponBased.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Promotion/Field/usedWithUsageLimit.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Promotion/_form.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
> [Admin] Promotion features

- src/Sylius/Bundle/WebBundle/Resources/public/css/backend.css
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Common/forms.html.twig
| Related tickets | fixes #4857 
> Legacy admin tabbed translations form theme

- src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/RegisterPromotionActionsPass.php
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/RegisterRuleCheckersPass.php
> [Promotion][UX] Sort promotion rules and actions in selectbox

- src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCurrenciesContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingLocalesContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentMethodsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxCategoriesContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxRateContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingZonesContext.php
- src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
- src/Sylius/Behat/Page/Admin/Crud/IndexPageInterface.php
> [Behat][Page][Crud] Rename isResourceOnPage to isSingleResourceOnPage 

- src/Sylius/Bundle/VariationBundle/EventListener/LoadMetadataSubscriber.php
- src/Sylius/Bundle/VariationBundle/spec/EventListener/LoadMetadataSubscriberSpec.php
> [ProductOption] Fixed problem with removing values from product option

- etc/behat/services/contexts/transform.xml
- etc/behat/suites/ui/promotion/managing_promotions.yml
- features/promotion/managing_promotions/adding_promotion.feature
- features/promotion/managing_promotions/editing_promotion.feature
- features/promotion/managing_promotions/promotion_validation.feature
- src/Sylius/Behat/Context/Transform/DateTimeContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Behat/Page/Admin/Promotion/CreatePage.php
- src/Sylius/Behat/Page/Admin/Promotion/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/Promotion/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Promotion/UpdatePageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Promotion/_form.html.twig
- src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionType.php
- src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
- src/Sylius/Bundle/PromotionBundle/Resources/config/validation.xml
- src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/PromotionBundle/Validator/Constraints/PromotionDateRange.php
- src/Sylius/Bundle/PromotionBundle/Validator/PromotionDateRangeValidator.php
> [Admin] Promotions start and end date validation

- PULL_REQUEST_TEMPLATE.md
```
Commit title
Commit description
```
Then the commit description will be copied below the table with only one blank line between them.
> Tweak pull request template

- etc/behat/services/contexts/setup.xml
- etc/behat/suites/ui/product/managing_product_options.yml
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Setup/ProductOptionContext.php
> [Admin] Extracted ProductOptionContext in setup

- src/Sylius/Bundle/ChannelBundle/DependencyInjection/SyliusChannelExtension.php
- src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/LazyCacheWarmupPass.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineODMDriver.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineORMDriver.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrinePHPCRDriver.php
- src/Sylius/Bundle/ThemeBundle/DependencyInjection/SyliusThemeExtension.php
Generated container for environment **prod** with debug **false** gets smaller by 33%, from 3MiB to 2MiB.
> [Resource] Do not make repositories lazy by default

- src/Sylius/Bundle/ResourceBundle/Form/EventSubscriber/ResourceTranslationsSubscriber.php
- src/Sylius/Bundle/ResourceBundle/spec/Form/EventSubscriber/ResourceTranslationsSubscriberSpec.php
> [ResourceBundle] Fix bug with adding product option value translations

- src/Sylius/Bundle/ThemeBundle/Repository/FailsafeThemeRepository.php
- src/Sylius/Component/Resource/Repository/InMemoryRepository.php
- src/Sylius/Component/Resource/Repository/RepositoryInterface.php
| Bug fix?      | sorta
This works around a bug in php i just encountered in php 7.0.6: https://bugs.php.net/bug.php?id=72119
> synchronize RepositoryInterface method signatures

- features/installer/install_command.feature
- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
Based on #4782, please wait with the review. :)
> [Installer] Tweak installation currency and locale settings

- src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Cart/summary.html.twig
> [Web] Fix typo in cart summary

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment_method.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentMethodRepository.php
- src/Sylius/Bundle/GridBundle/Doctrine/ORM/Driver.php
- src/Sylius/Bundle/ResourceBundle/Controller/ParametersParser.php
- src/Sylius/Bundle/ResourceBundle/Controller/ParametersParserInterface.php
- src/Sylius/Bundle/ResourceBundle/Grid/View/ResourceGridViewFactory.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/grid.xml
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ParametersParserSpec.php
- src/Sylius/Bundle/ResourceBundle/spec/Grid/View/ResourceGridViewFactorySpec.php
- src/Sylius/Component/Grid/Definition/Grid.php
- src/Sylius/Component/Grid/spec/Definition/GridSpec.php
> [Grid] Parse parameters of grid driver configuration

- features/promotion/managing_promotions/adding_promotion.feature
- features/promotion/managing_promotions/editing_promotion.feature
- features/promotion/managing_promotions/promotion_validation.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
| Related tickets | [comment](https://github.com/Sylius/Sylius/pull/4876#discussion_r61070917)
> [Behat] Typo fix in promotion features

- src/Sylius/Component/Inventory/Model/StockableInterface.php
- src/Sylius/Component/Inventory/spec/Fixtures/SampleStockable.php
> [Inventory] Remove sku from stockable interface

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/form.xml
> [CoreBundle] Fixed overriding of ShippingMethodChoiceType

- src/Sylius/Bundle/UserBundle/Resources/translations/validators.en.yml
> [User] Add missing translations to UserBundle

- etc/behat/services/pages.xml
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductAttributesContext.php
- src/Sylius/Behat/Page/Admin/ProductAttribute/CreatePage.php
- src/Sylius/Behat/Page/Admin/ProductAttribute/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/ProductAttribute/UpdatePage.php
- src/Sylius/Behat/Page/Admin/ProductAttribute/UpdatePageInterface.php
> [Behat] [DX] Moving attributes page to keep consistency

- src/Sylius/Bundle/FlowBundle/Process/Builder/ProcessBuilderInterface.php
| Related tickets | fixes Sylius/SyliusFlowBundle#27
> Add fluent interface to PHPDoc

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/zone.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/create.html.twig
> [Behat] Fix passing route params to form in create action

- src/Sylius/Bundle/GridBundle/Renderer/TwigGridRenderer.php
- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonChoiceType.php
- src/Sylius/Bundle/TaxonomyBundle/spec/Form/Type/TaxonChoiceTypeSpec.php
- src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
Fix options passing to the filter.
> [Taxonomy] Allow passing code in the taxon choice type

- features/product/managing_product_attributes/adding_checkbox_product_attribute.feature
- features/product/managing_product_attributes/adding_integer_product_attribute.feature
- features/product/managing_product_attributes/adding_percent_product_attribute.feature
- features/product/managing_product_attributes/adding_text_product_attribute.feature
- features/product/managing_product_attributes/adding_textarea_product_attribute.feature
- features/product/managing_product_attributes/product_attribute_unique_code_validation.feature
- features/product/managing_product_attributes/text_product_attribute_validation.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductAttributesContext.php
> [Behat] Product attribute typo

- docs/book/environments.rst
> [Docs] Remove outdated information about staging environment

- docs/api/users.rst
Both https://github.com/Sylius/Sylius/pull/3601 and https://github.com/Sylius/Sylius/pull/3638 ignored the documentation.
> Update the ADMIN role in the documentation

- src/Sylius/Component/Resource/spec/Metadata/MetadataSpec.php
> Remove semantic coupling in metadata spec

- src/Sylius/Bundle/PayumBundle/Model/GatewayConfig.php
| Q	                       | A     |
|--------------------------|------ |
| Bug Fix?        	| Y     |
| New Feature?	| n     |
| BC Breaks?	       | n     |
| Deprecations?	| n     |
| Tests Pass?	       | n     |
| Fixed Tickets	       |        |
| License	               | MIT |
| Doc PR                  |        |
> [PayumBundle] Fix missing `ResourceInterface`

- src/Sylius/Component/Core/Test/Services/SharedStorage.php
- src/Sylius/Component/Core/Test/Services/SharedStorageInterface.php
- src/Sylius/Component/Core/spec/Test/Services/SharedStorageSpec.php
> [Tests] Add has method to shared storage

- src/Sylius/Bundle/ResourceBundle/EventListener/ResourceDeleteSubscriber.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml
> [Resource] catch foreing key deletion error

- composer.json
- composer.lock
- src/Sylius/Component/Channel/Context/CachedPerRequestChannelContext.php
- src/Sylius/Component/Channel/composer.json
- src/Sylius/Component/Channel/spec/Context/CachedPerRequestChannelContextSpec.php
It caused ~200-300 database requests sent while being in store administration panel with undefined channel.
> [Channel] Cache channel not found exceptions in CachedPerRequestChannelContext

- features/channel/managing_channels/deleting_channel.feature
- features/channel/managing_channels/editing_channel.feature
- features/channel/managing_channels/selecting_currencies_available_for_channel.feature
- features/channel/managing_channels/selecting_payment_methods_available_for_channel.feature
- features/channel/managing_channels/selecting_shipping_methods_available_for_channel.feature
- features/currency/managing_currency/browsing_currencies.feature
- features/currency/managing_currency/editing_currency.feature
- features/product/managing_product_attributes/edit_text_product_attribute.feature
- features/product/managing_product_options/editing_product_option.feature
- features/promotion/managing_promotions/editing_promotion.feature
- features/shipping/managing_shipping_methods/editing_shipping_method.feature
- features/shipping/managing_shipping_methods/shipping_method_validation.feature
- features/taxation/managing_tax_rates/editing_tax_rate.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCurrenciesContext.php
> [Behat] [DX] Fix steps beginnings

- docs/bundles/SyliusGridBundle/column_configuration.rst
- docs/bundles/SyliusGridBundle/column_types.rst
- docs/bundles/SyliusGridBundle/custom_filter.rst
- docs/bundles/SyliusGridBundle/installation.rst
- docs/bundles/SyliusGridBundle/your_first_grid.rst
> [Docs] Improve GridBundle documentation

- app/config/config_test.yml
- docs/bundles/SyliusThemeBundle/configuration_sources.rst
- docs/bundles/SyliusThemeBundle/configuration_sources/test.rst
- etc/behat/services/contexts/hook.xml
- etc/behat/services/contexts/setup.xml
- etc/behat/suites/ui/channel/theming.yml
- src/Sylius/Behat/Context/Hook/TestThemeContext.php
- src/Sylius/Behat/Context/Setup/ThemeContext.php
- src/Sylius/Bundle/ThemeBundle/Configuration/Test/TestConfigurationProvider.php
- src/Sylius/Bundle/ThemeBundle/Configuration/Test/TestConfigurationSourceFactory.php
- src/Sylius/Bundle/ThemeBundle/Configuration/Test/TestThemeConfigurationManager.php
- src/Sylius/Bundle/ThemeBundle/Configuration/Test/TestThemeConfigurationManagerInterface.php
- src/Sylius/Bundle/ThemeBundle/DependencyInjection/SyliusThemeExtension.php
- src/Sylius/Bundle/ThemeBundle/SyliusThemeBundle.php
- src/Sylius/Bundle/ThemeBundle/spec/Configuration/Test/TestConfigurationProviderSpec.php
- src/Sylius/Bundle/ThemeBundle/spec/Configuration/Test/TestThemeConfigurationManagerSpec.php
> [Theme] Easier way to test themes

- composer.json
- composer.lock
> Update gherkin checker utilitary

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/Form/_main.html.twig
> [WebBundle] Add missing bootstrap tag for date in product form

- src/Sylius/Bundle/CoreBundle/Form/Type/CountryType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/LocaleType.php
| Q	                       | A     |
|--------------------------|------ |
| Bug Fix?        	| Yes     |
| New Feature?	| n     |
| BC Breaks?	       | n     |
| Deprecations?	| n     |
| Tests Pass?	       |      |
| Fixed Tickets	       |        |
| License	               | MIT |
| Doc PR                  |        |
Fix wrong locale & country choice display in edit page.
> [BUG][CoreLocaleType] Add locale choice for edit mode.

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Security/login.html.twig
Remove CDN CSS dependencies from assetic filter, include as stylesheets in their own right
> [Legacy Admin] Fix login assetic dependencies

- docs/bundles/SyliusPromotionBundle/summary.rst
| Related tickets | fixes docs
Fixes documentation, see https://github.com/Sylius/Sylius/blob/master/UPGRADE.md#from-0150-to-016x
> Reflect 0.15 resources configuration upgrade

- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
- src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePage.php
- src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePageInterface.php
Two PR was merged together, what results in a wrong method declaration.
> [Behat] Fix master build

- src/Sylius/Bundle/ThemeBundle/DependencyInjection/SyliusThemeExtension.php
- src/Sylius/Bundle/ThemeBundle/Resources/config/services/services.xml
> [Theme] Remove sylius.theme.repository aliasing, rename to sylius.repository.theme

- tests/Controller/CountryApiTest.php
- tests/Controller/CurrencyApiTest.php
- tests/Controller/CustomerApiTest.php
- tests/Controller/LocaleApiTest.php
- tests/Controller/ProvinceApiTest.php
- tests/Controller/ShippingCategoryApiTest.php
- tests/Controller/SitemapControllerApiTest.php
- tests/Controller/TaxCategoryApiTest.php
> [DX] Change tests namespace

- docs/bundles/SyliusOrderBundle/services.rst
> Reflect changes from c9ead52a36a49fe2c1a4ea

- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Channel/macros.html.twig
| Related tickets | fixes issue introduced by #4897
> [Channel] channel.theme.title -> channel.themeName

- src/Sylius/Bundle/ResourceBundle/Controller/RedirectHandler.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/RedirectHandlerSpec.php
> [ResourceBundle] Pass $resource in redirectToIndex parameters

- src/Sylius/Bundle/ResourceBundle/Controller/SingleResourceProvider.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/SingleResourceProviderSpec.php
| Doc PR          | no
Before the introduction of the new ResourceController this was the expected behaviour.
This is still reflected in the documentation
> [ResourceBundle] Merge request criteria in SingleResourceProvider

- app/migrations/Version20160401100530.php
- app/migrations/Version20160427100800.php
| Related tickets | #
Added missing migrations - file names are based on when relevant PR was merged.
https://github.com/Sylius/Sylius/pull/4246
https://github.com/Sylius/Sylius/pull/4897
> [migrations] - added missing settings and theme migrations 

- features/legacy/backend/promotions.feature
- features/promotion/managing_coupons/coupon_generate_validation.feature
- features/promotion/managing_coupons/generating_coupon.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
- src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePage.php
- src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/_generateForm.html.twig
- src/Sylius/Bundle/PromotionBundle/Doctrine/ORM/CouponRepository.php
- src/Sylius/Bundle/PromotionBundle/Form/Type/CouponGenerateInstructionType.php
- src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
- src/Sylius/Bundle/PromotionBundle/Resources/config/validation.xml
- src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/PromotionBundle/Validator/Constraints/CouponPossibleGenerationAmount.php
- src/Sylius/Bundle/PromotionBundle/Validator/CouponGenerationAmountValidator.php
- src/Sylius/Bundle/PromotionBundle/spec/Validator/CouponGenerationAmountValidatorSpec.php
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Coupon/_generateForm.html.twig
- src/Sylius/Component/Promotion/Exception/FailedGenerationException.php
- src/Sylius/Component/Promotion/Generator/CouponGenerator.php
- src/Sylius/Component/Promotion/Generator/CouponGeneratorInterface.php
- src/Sylius/Component/Promotion/Generator/GenerationPolicyInterface.php
- src/Sylius/Component/Promotion/Generator/Instruction.php
- src/Sylius/Component/Promotion/Generator/InstructionInterface.php
- src/Sylius/Component/Promotion/Generator/PercentageGenerationPolicy.php
- src/Sylius/Component/Promotion/Repository/CouponRepositoryInterface.php
- src/Sylius/Component/Promotion/spec/Exception/FailedGenerationExceptionSpec.php
- src/Sylius/Component/Promotion/spec/Generator/CouponGeneratorSpec.php
- src/Sylius/Component/Promotion/spec/Generator/InstructionSpec.php
- src/Sylius/Component/Promotion/spec/Generator/PercentageGenerationPolicySpec.php
Rebased PR from @Richtermeister https://github.com/Sylius/Sylius/pull/2389
> [Promotion] Making coupon code length configurable.

- src/Sylius/Behat/Context/Transform/LexicalContext.php
> add Chinese currency symbol to LexicalContext class

- src/Sylius/Bundle/ResourceBundle/EventListener/ODMMappedSuperClassSubscriber.php
- src/Sylius/Bundle/ResourceBundle/EventListener/ORMMappedSuperClassSubscriber.php
| New feature?    |yes
| BC breaks?      |yes
| Related tickets | fixes #5040 (again)
I think this is correct now.
1. Convert MappedSuperClass to Entity if the class is the configured Sylius resource.
2. If class is not a MappedSuperClass, move associations  from MappedSuperClass parents, but only if parent is a Sylius entity.
3. If Class is MappedSuperClass, remove associations, but only if class is a Sylius entities.
cc @liverbool
> fix mapped superclass subscribers for overidden resources

- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Component/Core/OrderProcessing/OrderRecalculator.php
- src/Sylius/Component/Core/Remover/AdjustmentsRemover.php
- src/Sylius/Component/Core/Remover/AdjustmentsRemoverInterface.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderRecalculatorSpec.php
- src/Sylius/Component/Core/spec/Remover/AdjustmentsRemoverSpec.php
- src/Sylius/Component/Order/Model/Order.php
- src/Sylius/Component/Order/Model/OrderInterface.php
- src/Sylius/Component/Order/spec/Model/OrderSpec.php
> [Core] Remove promotion and tax adjustments before recalculation

- UPGRADE.md
> [UPGRADE] Added info about order promotion distribution

- src/Sylius/Behat/Extension/MultiContainerExtension/ServiceContainer/MultiContainerExtension.php
> [Behat] Perform no deep merging on sylius_multi_container.imports

- src/Sylius/Bundle/ResourceBundle/EventListener/AbstractDoctrineSubscriber.php
- src/Sylius/Bundle/ResourceBundle/EventListener/ODMRepositoryClassSubscriber.php
- src/Sylius/Bundle/ResourceBundle/EventListener/ORMRepositoryClassSubscriber.php
- src/Sylius/Bundle/ResourceBundle/spec/EventListener/ODMRepositoryClassSubscriberSpec.php
- src/Sylius/Bundle/ResourceBundle/spec/EventListener/ORMRepositoryClassSubscriberSpec.php
> fix my email

- src/Sylius/Bundle/ReportBundle/Form/Type/ReportType.php
- src/Sylius/Component/Report/DataFetcher/DelegatingDataFetcherInterface.php
- src/Sylius/Component/Report/Model/Report.php
- src/Sylius/Component/Report/spec/DataFetcher/DataSpec.php
- src/Sylius/Component/Report/spec/DataFetcher/DelegatingDataFetcherSpec.php
- src/Sylius/Component/Report/spec/Model/ReportSpec.php
- src/Sylius/Component/Report/spec/Renderer/DelegatingRendererSpec.php
Inspired by #5080, #5081 and #5082  I also decided to make some crucial fixes in Sylius.
> [CRUCIAL] Fix mail

- src/Sylius/Bundle/CoreBundle/EventListener/CustomerReviewsDeleteListener.php
- src/Sylius/Bundle/CoreBundle/Form/Type/ProductReviewType.php
- src/Sylius/Bundle/ReviewBundle/EventListener/LoadMetadataSubscriber.php
- src/Sylius/Bundle/ReviewBundle/EventListener/ReviewChangeListener.php
- src/Sylius/Bundle/ReviewBundle/Updater/AverageRatingUpdater.php
- src/Sylius/Bundle/ReviewBundle/Validator/Constraints/UniqueReviewerEmail.php
- src/Sylius/Bundle/ReviewBundle/Validator/Constraints/UniqueReviewerEmailValidator.php
- src/Sylius/Component/Core/Model/ProductReview.php
- src/Sylius/Component/Review/Model/Reviewer.php
Inspired by awesome work of @bendavies in https://github.com/Sylius/Sylius/pull/5080, I also decided to make some crucial fixes in *Sylius*.
> [Core][Review] Email fixes

- src/Sylius/Component/Promotion/Generator/CouponGenerator.php
- src/Sylius/Component/Promotion/Generator/CouponGeneratorInterface.php
| Related tickets | mentioned in [comment](https://github.com/Sylius/Sylius/pull/5087#issuecomment-220919677)
Based on #5087
> [Promotion] Coupon generation refactoring

- docs/behat/basic-usage.rst
- docs/behat/index.rst
- docs/behat/map.rst.inc
Add some example usage of our new behat. feat @TheMadeleine
> [Doc][Behat] Add basic usage for behat guide

- docs/behat/basic-usage.rst
> fix small typo

- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion.yml
> [Promotion] Move coupon routing import to main file

- src/Sylius/Bundle/OrderBundle/Controller/CommentController.php
> [OrderBundle] Fixed sending emails for order comments

- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
| Related tickets | fixes #5107
> [WebBundle] Add missing shipment state translations

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
> [UserBundle] Deleted unused email configuration

- src/Sylius/Behat/Context/Ui/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxCategoriesContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxRateContext.php
- src/Sylius/Behat/Page/Admin/Country/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
- src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePage.php
- src/Sylius/Behat/Page/Shop/Account/ProfileUpdatePage.php
> Fixed typo

- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
> [WebBundle] Add missing translations for payment & shipping state in admin

- docs/bundles/SyliusOrderBundle/services.rst
> Fix typo in OrderItemQuantityModifier usage doc

- src/Sylius/Bundle/CoreBundle/DataCollector/SyliusDataCollector.php
> [HOTFIX] Fix core data collector

- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Action/manageVariants.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Breadcrumb/_index.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Missing translation and variants button has been added.
> [Admin] Product variant cleanup

- app/config/config.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/parameters.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/InstallerBundle/Command/CommandExecutor.php
- src/Sylius/Bundle/InstallerBundle/Command/InstallCommand.php
> [Sylius] Fixes for changes from #5058

- app/AppKernel.php
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
- src/Sylius/Bundle/CoreBundle/DataCollector/SyliusDataCollector.php
| Related tickets | #5058, #5128, #5127
> [Sylius] Extract CoreBundle's Kernel once again

- src/Sylius/Bundle/AttributeBundle/Doctrine/ORM/AttributeRepository.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentRepository.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ShipmentRepository.php
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/payment.yml
- src/Sylius/Bundle/WebBundle/Resources/config/routing/backend/product_attribute.yml
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Inventory/macros.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Payment/macros.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Product/macros.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductAttribute/macros.html.twig
- src/Sylius/Bundle/WebBundle/Resources/views/Backend/Shipment/macros.html.twig
- src/Sylius/Component/Attribute/Repository/AttributeRepositoryInterface.php
> [Backend] Fixed sorting translatable fields in backend

- src/Sylius/Bundle/PayumBundle/Action/ConvertPaymentToPaypalExpressAction.php
> [Payum] Fix order amounts that are sent to Paypal

- features/order/managing_orders/cancelling_order.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
- src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/show.html.twig
> [Admin][Order] Cancelling an order

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_payment.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipment.html.twig
> [Shop][Fix] Fix order payment and shipment route parameters

- docs/contributing/documentation/format.rst
- docs/contributing/documentation/overview.rst
- docs/contributing/documentation/standards.rst
> [Documentation] Docs Contribution Guide update

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/WebBundle/Controller/Backend/DashboardController.php
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
> [Backend] Fix displaying orders on dashboard

- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Form/_ship.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_actions.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_payment.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipment.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/shipmentShip.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/show.html.twig
- src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadOrdersData.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/ShipmentShipType.php
- src/Sylius/Bundle/UiBundle/Resources/private/js/app.js
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
> [Admin] Rework the UI of completing a payment, cancelling and shipping an order

- src/Sylius/Behat/Context/Setup/OrderContext.php
| Related tickets | mentioned in #5173
> [Behat] Quick fix in OrderContext

- docs/book/installation.rst
> [Documentation] The Book - Installation

- features/order/managing_orders/seeing_order_aggregated_taxes.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
- src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
- src/Sylius/Component/Order/Aggregator/AdjustmentsByLabelAggregator.php
- src/Sylius/Component/Order/spec/Aggregator/AdjustmentsByLabelAggregatorSpec.php
> [Behat] Order taxes aggregation scenarios

- src/Sylius/Component/Resource/Repository/InMemoryRepository.php
- src/Sylius/Component/Resource/Repository/RepositoryInterface.php
> [Resource] Repository interface fix

- features/product/managing_products/adding_product_with_attributes.feature
- features/product/managing_products/adding_product_with_text_attribute.feature
- src/Sylius/Behat/Context/Setup/ProductAttributeContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPageInterface.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/product/managing_products.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_attribute.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Attribute/attributeChoice.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Attribute/attributeValues.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Attribute/attributesCollection.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_attributes.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/_menu.html.twig
- src/Sylius/Bundle/AttributeBundle/Controller/AttributeController.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductType.php
- src/Sylius/Bundle/UiBundle/Resources/private/js/product-attributes.js
- src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml
> [Admin][Behat] Adding a text attribute to product

- features/order/managing_orders/seeing_order_aggregated_discounts.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
> [Behat] Order promotions aggregation scenarios

- docs/README.md
- docs/contributing/documentation/overview.rst
| Related tickets | mentioned in #5174 
> [Documentation] README update - Installation

- docs/book/payments.rst
| Doc fix?	           | yes
Fix link to file in github.
> Update link documentation about state machine

- docs/book/architecture.rst
> [Documentation] The Book - Architecture

- src/Sylius/Bundle/SearchBundle/README.md
| Related tickets | fixes #5146
Update searchbundle doc according to #4525
> [SearchBundle][Documentation] Update elasticsearch product mapping

- src/Sylius/Bundle/ResourceBundle/Controller/FlashHelper.php
> [ResourceBundle] Ignore flash message if set to false

- src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
> [Promotion] Add missed translation

- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Setup/TaxationContext.php
- src/Sylius/Behat/Context/Transform/SharedStorageContext.php
- src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
- src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php
- src/Sylius/Bundle/ProductBundle/Behat/ProductContext.php
- src/Sylius/Bundle/ResourceBundle/Behat/DefaultContext.php
- src/Sylius/Component/Core/Formatter/StringInflector.php
- src/Sylius/Component/Core/Test/Factory/TestPromotionFactory.php
There are many places where we need to format string to some *code-like* form and it is nice to have an object with such a responsibility. I encourage you all to talk about this class name. I've had many ideas like:
- ``SpacesToUnderscoreFormatter``
- ``SnakeCaseFormatter``
- ``Snaker`` (:smile:)
but finally I decided to something more neutral. I would appreciate brainstorm about that ;)
> [Core] Implement object usefull for string formatting

- src/Sylius/Bundle/CoreBundle/EventListener/ImageUploadListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/spec/EventListener/ImageUploadListenerSpec.php
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
> [Admin] Fix image upload on product create and update

- src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/ShipmentType.php
- src/Sylius/Bundle/ShopBundle/Resources/private/scss/style.scss
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Form/_shipping.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/shipping.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Shop] Quick tweaks to the shipping step template

- UPGRADE.md
- app/config/config_test.yml
- composer.json
- composer.lock
- src/Sylius/Behat/Service/Mocker/PaypalApiMocker.php
- src/Sylius/Behat/spec/Service/Mocker/MockerSpec.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/PayumBundle/Resources/config/services.xml
- src/Sylius/Bundle/WebBundle/Controller/Frontend/Account/OrderController.php
| Related tickets | mentioned in #3564 
Upgrade to payumBundle v2.1 and add a mention to Upgrade.md
There is a BC Break because of configuration, take a look at [Payum/PayumBundle/UPGRADE.md](https://github.com/Payum/PayumBundle/blob/master/UPGRADE.md)
> [Composer][PayumBundle] Upgrade to 2.1

- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/taxon.yml
> [Shop] Break infinite loop

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
| New feature?    | noes
Bug reported in [this comment](https://github.com/Sylius/Sylius/pull/4377#issuecomment-225816197);
> [Promotion][Core] Decouple Promotion configuration from Core

- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/CoreBundle/Resources/views/Email/orderComment.html.twig
- src/Sylius/Bundle/CoreBundle/Resources/views/Email/orderConfirmation.html.twig
- src/Sylius/Bundle/CoreBundle/Resources/views/Email/passwordReset.html.twig
- src/Sylius/Bundle/CoreBundle/Resources/views/Email/shipmentConfirmation.html.twig
- src/Sylius/Bundle/CoreBundle/Resources/views/Email/userConfirmation.html.twig
> [Mail] Update mail templates

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/driver/doctrine/odm.xml
- src/Sylius/Bundle/ResourceBundle/Resources/config/driver/doctrine/orm.xml
- src/Sylius/Bundle/ResourceBundle/Resources/config/driver/doctrine/phpcr-odm.xml
- src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml
This PR allows the explicit enabling of drivers for the ResourceBundle, in the same way that has been done for the GridBundle (https://github.com/Sylius/Sylius/pull/4972).
> [Resource] Allow explicit enabling of drivers

- src/Sylius/Bundle/ShopBundle/Resources/config/routing/account.yml
> [Shop] Routing typo fix

- app/config/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_item.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_addresses.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/show.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Field/image.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/_mainImage.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Field/image.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Field/name.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/_mainImage.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_item.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_images.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_mainImage.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_simpleBox.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
- src/Sylius/Component/Core/Model/Product.php
- src/Sylius/Component/Core/Model/ProductInterface.php
> [Shop] Add initial images support

- src/Sylius/Bundle/CoreBundle/EventListener/OrderItemInventoryListener.php
| BC breaks?      | yes (listeners do execute on that flush now)
| Related tickets | fixes #5270 (and failing build on master)
> [Core] Do not remove onFlush listeners in OrderItemInventoryListener

- features/account/customer_account/viewing_only_my_orders.feature
- features/account/customer_account/viewing_orders.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
- src/Sylius/Behat/Page/Shop/Account/Order/IndexPage.php
- src/Sylius/Behat/Page/Shop/Account/Order/IndexPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/shop/account.xml
- src/Sylius/Behat/Resources/config/suites/ui/account/customer.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/account/order.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/account.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/account/order.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Field/channel.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Field/customer.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Field/number.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Field/state.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Field/total.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/_grid.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/index.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/_menu.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
> [Shop][Account] Orders on my account page

- src/Sylius/Bundle/CoreBundle/EventListener/OrderInventoryListener.php
> [Core] Remove usage of PropertyAccess for simple array manipulation

- src/Sylius/Bundle/FixturesBundle/.gitignore
- src/Sylius/Bundle/FixturesBundle/Listener/AbstractListener.php
- src/Sylius/Bundle/FixturesBundle/Listener/LoggerListener.php
- src/Sylius/Bundle/FixturesBundle/README.md
- src/Sylius/Bundle/FixturesBundle/composer.json
> [Fixtures] Update readme.md / composer.json & small improvements

- features/checkout/addressing_order/filling_shipping_and_billing_address_details.feature
- features/checkout/addressing_order/shipping_and_billing_address_validation.feature
- features/checkout/paying_for_order/paying_offline_during_checkout.feature
- features/checkout/shipping_order/preventing_not_available_shipping_method_selection.feature
- features/checkout/shipping_order/selecting_order_shipping_method.feature
- features/promotion/applying_promotion_rules/reapplying_promotion_on_cart_change.feature
- features/promotion/applying_promotion_rules/receiving_discount_based_on_nth_order.feature
- features/promotion/complex_promotions.feature
- features/promotion/receiving_discount/receiving_fixed_discount_on_cart.feature
- features/promotion/receiving_discount/receiving_percentage_discount_on_shipping.feature
- features/promotion/receiving_discount/receiving_percentage_discount_promotion_on_order.feature
- features/shipping/applying_shipping_fee/applying_correct_shipping_fee_on_order.feature
- features/shipping/applying_shipping_fee/applying_correct_shipping_fee_with_product_taxes_on_order.feature
- features/shipping/applying_shipping_fee/applying_correct_shipping_fee_with_taxes_on_order.feature
- features/taxation/applying_taxes/applying_correct_taxes_based_on_customer_data.feature
- features/taxation/applying_taxes/applying_correct_taxes_for_products_with_different_tax_rates_for_different_zones.feature
- src/Sylius/Behat/Context/Setup/SecurityContext.php
> [Behat] Fix typo in scenario step

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Grid/Field/label.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Grid/Field/state.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/PaymentState/completed.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/PaymentState/new.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/ShippingState/ready.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/ShippingState/shipped.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/State/cancelled.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_addresses.html.twig
- src/Sylius/Bundle/GridBundle/FieldTypes/TwigFieldType.php
- src/Sylius/Bundle/GridBundle/spec/FieldTypes/TwigFieldTypeSpec.php
- src/Sylius/Bundle/UiBundle/Resources/private/sass/_variables.scss
- src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
- src/Sylius/Bundle/UiBundle/Resources/views/Label/_default.html.twig
> [Admin] Allow for customizable labels

- src/Sylius/Bundle/ShopBundle/DependencyInjection/SyliusShopExtension.php
- src/Sylius/Bundle/ShopBundle/Menu/AccountMenuBuilder.php
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/account/order.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/menu.xml
- src/Sylius/Bundle/ShopBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Field/channel.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Field/customer.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Field/number.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Field/shippingAddress.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/index.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/_menu.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/layout.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Menu/simple.html.twig
> [Shop] Use menu builder for my account section + small tweaks

- src/Sylius/Component/Attribute/Model/AttributeValue.php
> [Attribute] Remove unused AttributeValue::$value

- src/Sylius/Bundle/CoreBundle/Controller/CheckoutController.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/ShippingStepType.php
| Related tickets | fixes #5317 
Missing criteria option definition
> Fix issue 5317

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
| Related tickets | fixes #5322
Add following permissions : 
- sylius.inventory_unit.update
- sylius.promotion_rule.delete
- sylius.promotion_action.delete
> [Rbac] Add missing permissions

- features/checkout/seeing_order_summary/seeing_discount_on_order_item_on_summary_page.feature
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/SummaryPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SummaryPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/checkout/checkout.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/checkout.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_address.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/summary.html.twig
> [Shop][Checkout] Seeing discount on order item

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/create.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/update.html.twig
> [Admin][Taxon] create partial routing for taxons

- features/checkout/seeing_order_summary/seeing_total_tax_on_order_summary_page.feature
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/SummaryPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SummaryPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/checkout/checkout.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/summary.html.twig
> [Shop][Behat] Seeing total tax on order summary

- features/checkout/seeing_order_summary/seeing_shipping_method_and_payment_method_on_order_summary_page.feature
- features/checkout/seeing_order_summary/seeing_shipping_total_on_order_summary_page.feature
- features/checkout/seeing_order_summary/seeing_total_discount_on_order_summary_page.feature
- src/Sylius/Behat/Context/Setup/PaymentContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/SummaryPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SummaryPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/checkout/checkout.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_promotion.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_shipping.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/summary.html.twig
> [Shop][Checkout] Seeing shipping and payment methods on order summary

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/UserExampleFactory.php
> [Core] [Fixtures] Do not create admin users by default

- src/Sylius/Bundle/CoreBundle/Fixture/BookProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/MugProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/ProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/StickerProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/TshirtProductFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/fixtures_factories.xml
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/ProductFixtureTest.php
> [Core] [Fixtures] Add images to product fixtures

- features/checkout/seeing_order_summary/seeing_shipping_method_and_payment_method_on_order_summary_page.feature
- features/checkout/seeing_order_summary/seeing_shipping_total_on_order_summary_page.feature
- features/checkout/seeing_order_summary/seeing_total_discount_on_order_summary_page.feature
- features/order/placing_an_order/adding_notes_for_customer_service.feature
- src/Sylius/Behat/Context/Setup/UserContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/summary.html.twig
> [Shop][Checkout] Quick fixes

- src/Sylius/Bundle/UserBundle/EventListener/DefaultUsernameORMListener.php
- src/Sylius/Bundle/UserBundle/spec/EventListener/DefaultUsernameORMListenerSpec.php
- tests/Responses/Expected/customer/create_with_user_response.json
| BC breaks?      | yes (listener made final)
| Related tickets | fixes #5287
> [User] Synchronize User::usernameCanonical with Customer::emailCanonical

- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/CoreBundle/Resources/views/Email/passwordReset.html.twig
- src/Sylius/Bundle/CoreBundle/Resources/views/Email/userConfirmation.html.twig
> [Email] Fix resetting password

- docs/api/authorization.rst
> Update link to API data fixtures

- docs/api/checkouts.rst
> [Documentation] Fix API endpoint

- docs/bundles/SyliusFlowBundle/installation.rst
I wanted to make this bundle more Symfony 2.8 / 3.0 friendly. Also, as a beginner, I wanted to make it easier to copy paste from docs to my services.yml|xml file. 
hence, the small docs updates.
> Improve SyliusFlow Docs

- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_payment.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/summary.html.twig
> [Shop] Fix rendering shipping and payment method on summary page

- features/checkout/addressing_order/returning_from_addressing_step_to_shop_homepage.feature
- features/checkout/paying_for_order/returning_from_payment_step_to_one_of_previous_steps.feature
- features/checkout/returning_from_order_summary_page_to_one_of_previous_steps.feature
- features/checkout/shipping_order/returning_from_shipping_step_to_addressing_step.feature
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressingPage.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressingPageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/PaymentPage.php
- src/Sylius/Behat/Page/Shop/Checkout/PaymentPageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/ShippingPage.php
- src/Sylius/Behat/Page/Shop/Checkout/ShippingPageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/SummaryPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SummaryPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/checkout.yml
- src/Sylius/Bundle/ShopBundle/Resources/private/js/remote-form.js
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_steps.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/payment.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/shipping.html.twig
> [Behat][Shop] Allow to go back in checkout

- features/user/managing_customers/seeing_customer_details.feature
- src/Sylius/Behat/Context/Setup/CustomerContext.php
- src/Sylius/Behat/Context/Transform/AddressingContext.php
- src/Sylius/Behat/Context/Transform/CustomerContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPage.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPageInterface.php
- src/Sylius/Behat/Page/SymfonyPage.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
- src/Sylius/Behat/Resources/config/services/contexts/transform.xml
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites/ui/user/managing_customers.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/customer.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Breadcrumb/_show.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/_header.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/show.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Admin][Behat] Customer show page basic info and addresses

- features/checkout/shipping_order/seeing_shipping_fee.feature
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/ShippingPage.php
- src/Sylius/Behat/Page/Shop/Checkout/ShippingPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Form/_shipping.html.twig
> [Shop][Checkout] Displaying detailed shipping fee

- features/checkout/addressing_order/choosing_province_for_country.feature
- features/checkout/addressing_order/choosing_province_for_country_with_provinces.feature
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressingPage.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressingPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/checkout/checkout.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing.yml
- src/Sylius/Bundle/ShopBundle/Resources/private/js/province-choices.js
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Form/_address.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_provinces.html.twig
> [Shop] Allow to choose province on addressing step

- src/Sylius/Behat/Resources/config/services.xml
- src/Sylius/Behat/Resources/config/services/contexts/cli.xml
- src/Sylius/Behat/Resources/config/services/contexts/domain.xml
- src/Sylius/Behat/Resources/config/services/contexts/hook.xml
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
- src/Sylius/Behat/Resources/config/services/contexts/transform.xml
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages.xml
> [Behat] Remove *.class parameters to improve readability

- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
Bug mentioned [in this comment](https://github.com/Sylius/Sylius/pull/5375#discussion_r69268834).
> [Behat] Small fixes in assert messages

- src/Sylius/Bundle/ShopBundle/Resources/config/routing/checkout.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/taxon.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/security.yml
> [Shop] Remove default "permission: false" parameter from routes configurations

- src/Sylius/Bundle/UserBundle/Controller/CustomerController.php
missing request configuration parameter for  viewHandler
> missing request configuration parameter

- features/promotion/applying_promotion_rules/receiving_discount_based_on_nth_order_for_guest_customer.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Transform/AddressingContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Resources/config/suites/ui/promotion/applying_promotion_rules.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
- src/Sylius/Bundle/UserBundle/Form/EventSubscriber/SetCustomerFormSubscriber.php
- src/Sylius/Bundle/UserBundle/Form/Type/CustomerGuestType.php
- src/Sylius/Bundle/UserBundle/Resources/config/services.xml
- src/Sylius/Bundle/UserBundle/spec/Form/EventSubscriber/SetCustomerFormSubscriberSpec.php
- src/Sylius/Component/Core/Promotion/Checker/NthOrderRuleChecker.php
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
- src/Sylius/Component/Core/spec/Promotion/Checker/NthOrderRuleCheckerSpec.php
> [Promotion] Apply promotion on nth order for a Guest 

- composer.json
- composer.lock
References:
https://github.com/doctrine/data-fixtures/issues/227
https://github.com/doctrine/data-fixtures/pull/231
https://github.com/doctrine/data-fixtures/issues/236
https://github.com/doctrine/data-fixtures/issues/237
> [Composer] Lock doctrine/data-fixtures at 1.1.*

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Bundle/FixturesBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/FixturesBundle/Suite/SuiteFactory.php
- src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/ConfigurationTest.php
- src/Sylius/Bundle/FixturesBundle/spec/Suite/SuiteFactorySpec.php
| Related tickets | fixes #5401
TODO:
TODO after merge:
- Create an issue about logging executed suites (they should show fixture aliases, not the actual fixture names)
> [Fixtures] Ability to reuse a fixture in the same suite

- docs/bundles/SyliusFixturesBundle/architecture.rst
| Related tickets | implemented in #5422
> [Documentation] Use a fixture multiple times in a single suite

- features/account/customer_account/viewing_orders_history/viewing_order.feature
- src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
> [Shop][Order] Fix typo

- src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/route.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/static_content.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/route.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/static_content.yml
- src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Grid/Field/truncate.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Route/Breadcrumb/_update.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Route/Field/content.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/StaticContent/Breadcrumb/_update.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/StaticContent/_form.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Admin] Enhance CMF integration (frontend fixes)

- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/checkout.yml
> [Core][Shop] Apply proper transitions on checkout summary

- src/Sylius/Bundle/ThemeBundle/Resources/views/Collector/theme.html.twig
Didn't tested it too well earlier :)
> [Theme] Fix collector if there are themes found

- src/Sylius/Bundle/CoreBundle/Collector/SyliusCollector.php
> Prevent SyliusCollector crash if not in a channel

- src/Sylius/Bundle/ShopBundle/Resources/config/routing/verification.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/dashboard.html.twig
- src/Sylius/Component/User/Model/Customer.php
> [Shop][Customer] Fixed verification rendering + Customer's trim

- src/Sylius/Bundle/ChannelBundle/Collector/ChannelCollector.php
- src/Sylius/Bundle/ChannelBundle/Resources/views/Collector/channel.html.twig
> Prevent ChannelCollector crash if not in a channel

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/customer.yml
> [Admin] Added missing "show" button on customers list

- features/channel/managing_channels/adding_channel.feature
> [Behat][CRITICAL] Fix typo in adding channel scenario

- features/channel/managing_channels/selecting_default_tax_zone_for_channel.feature
- src/Sylius/Behat/Context/Setup/ChannelContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
- src/Sylius/Behat/Page/Admin/Channel/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Channel/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/channel/managing_channels.yml
- src/Sylius/Component/Core/Model/Channel.php
> [Admin] Allow to remove default tax zone from existing channel

- docs/book/index.rst
- docs/book/map.rst.inc
- docs/book/requirements.rst
> [Documentation] System requirements

- docs/book/requirements.rst
> [Documentation] System requirements quick fix

- docs/book/architecture.rst
> [Documentation] Architecture - Divisions

- docs/book/architecture.rst
> [Documentation] Third party libraries

- docs/book/installation.rst
> [Documentation] Installation update

- docs/book/architecture.rst
> [Docs] Typo in architecture

- src/Sylius/Bundle/UserBundle/OAuth/UserProvider.php
- src/Sylius/Bundle/UserBundle/Resources/config/doctrine/model/UserOAuth.orm.xml
- src/Sylius/Bundle/UserBundle/spec/OAuth/UserProviderSpec.php
- src/Sylius/Component/User/Model/UserOAuth.php
- src/Sylius/Component/User/Model/UserOAuthInterface.php
> save refresh token when oauth login

- src/Sylius/Bundle/AddressingBundle/Controller/ProvinceController.php
> [Addressing] ProvinceController clean up

- src/Sylius/Bundle/CoreBundle/Controller/CheckoutController.php
- src/Sylius/Bundle/OrderBundle/Controller/CommentController.php
- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
- src/Sylius/Bundle/SettingsBundle/Controller/SettingsController.php
- src/Sylius/Bundle/UserBundle/Controller/CustomerController.php
- src/Sylius/Bundle/UserBundle/Controller/UserController.php
- src/Sylius/Bundle/WebBundle/Controller/Frontend/Account/OrderController.php
| BC breaks?      | maybe (2nd commit)
> Response status codes

- features/promotion/receiving_discount/receiving_fixed_discount_on_cart_from_coupon.feature
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
> [Behat] Receiving discount on cart from coupon scenario

- features/cart/shopping_cart/maintaining_cart_after_authorization.feature
- src/Sylius/Behat/Resources/config/suites/ui/cart/shopping_cart.yml
This is a port from old to new Behat scenarios of ``cart_maintenance.feature``.
> [Behat] Maintaining cart after authorization scenarios

- features/checkout/seeing_order_summary/seeing_items_on_order_summary_page.feature
> [Behat] fix typo in seeing_items_on_order_summary_page.feature

- docs/book/countries.rst
- docs/book/index.rst
- docs/book/map.rst.inc
> [Documentation] Concepts: Countries

- features/account/resetting_password.feature
- features/account/verification/email_verification.feature
- src/Sylius/Behat/Context/Hook/EmailSpoolContext.php
- src/Sylius/Behat/Context/Ui/Shop/RegistrationContext.php
- src/Sylius/Behat/Resources/config/services/contexts/hook.xml
- src/Sylius/Behat/Resources/config/suites/ui/account/customer.yml
- src/Sylius/Behat/Resources/config/suites/ui/account/verification.yml
- src/Sylius/Bundle/UserBundle/Controller/UserController.php
- src/Sylius/Bundle/UserBundle/UserEvents.php
- src/Sylius/Component/Core/Test/Services/EmailChecker.php
- src/Sylius/Component/Core/Test/Services/EmailCheckerInterface.php
> [Shop][Behat] Upgraded EmailChecker and fixed verification on registration

- src/Sylius/Bundle/InstallerBundle/Requirement/ExtensionsRequirements.php
- src/Sylius/Bundle/InstallerBundle/Requirement/FilesystemRequirements.php
- src/Sylius/Bundle/InstallerBundle/Requirement/Requirement.php
- src/Sylius/Bundle/InstallerBundle/Requirement/SettingsRequirements.php
- src/Sylius/Bundle/InstallerBundle/Resources/config/requirements.xml
- src/Sylius/Bundle/InstallerBundle/Resources/config/services.xml
- src/Sylius/Bundle/InstallerBundle/Resources/translations/requirements.en.yml
- src/Sylius/Bundle/InstallerBundle/spec/Requirement/RequirementSpec.php
The first thing I have come into as I have started was the incorrect 'short_open_tag` warning. Finally, after over a year, it gets fixed! (removed, to be honest :tada:)
> [Installer] A small cleanup

- composer.json
- composer.lock
- src/Sylius/Behat/Resources/config/profiles/default.yml
~8% (~40s) speedup on `~@javascript` suite, one second every ~114 steps :)
Performance comparison: https://blackfire.io/profiles/compare/185a658c-0e6f-42cd-982c-2030aba45f33/graph
> [Behat] Use FriendsOfBehat/PerformanceExtension in order to speed up Behat execution

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentMethodRepository.php
- src/Sylius/Bundle/PaymentBundle/Doctrine/ORM/PaymentMethodRepository.php
- src/Sylius/Component/Payment/Repository/PaymentMethodRepositoryInterface.php
> [Payment] Cleanup in payment method repository

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ShippingMethodRepository.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Component/Core/Repository/ShippingMethodRepositoryInterface.php
- src/Sylius/Component/Core/Resolver/ShippingMethodsByZonesAndChannelResolver.php
- src/Sylius/Component/Core/spec/Resolver/ShippingMethodsByZonesAndChannelResolverSpec.php
> [Optimization] Enhance shipping methods resolver

- docs/bundles/general/basic_crud.rst
Use factory instead of repository to create model resource
> Use factory to create model resource

- tests/Responses/Expected/sitemap/show_sitemap.xml
Test fails if machine timezone doesn't match the one on Travis.
> Fix sitemap test response

- features/currency/handling_disabled_currencies.feature
- src/Sylius/Bundle/ShopBundle/Resources/views/Currency/selector.html.twig
| Related tickets | related to #5497 
> [Shop] Hide selector if there are no other available currencies

- src/Sylius/Bundle/ThemeBundle/DependencyInjection/SyliusThemeExtension.php
- src/Sylius/Bundle/ThemeBundle/Resources/config/services/integration/twig.xml
- src/Sylius/Bundle/ThemeBundle/Resources/config/services/support/templating.xml
- src/Sylius/Bundle/ThemeBundle/Templating/TemplateNameParser.php
- src/Sylius/Bundle/ThemeBundle/Tests/Functional/TemplatingTest.php
- src/Sylius/Bundle/ThemeBundle/Tests/Functional/ThemeBundleTestCase.php
- src/Sylius/Bundle/ThemeBundle/Twig/ThemeFilesystemLoader.php
- src/Sylius/Bundle/ThemeBundle/spec/Templating/TemplateNameParserSpec.php
| Related tickets | fixes #5560
> [Theme] Support namespaced paths

- features/order/managing_orders/cancelling_order.feature
- features/order/managing_orders/placing_an_order_with_shipment.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine.yml
- src/Sylius/Bundle/ShippingBundle/Form/Type/ShipmentType.php
- src/Sylius/Bundle/ShippingBundle/Resources/config/app/state_machine.yml
- src/Sylius/Component/Core/Model/OrderItemUnit.php
- src/Sylius/Component/Core/OrderProcessing/StateResolver.php
- src/Sylius/Component/Core/spec/OrderProcessing/StateResolverSpec.php
- src/Sylius/Component/Shipping/Model/Shipment.php
- src/Sylius/Component/Shipping/Model/ShipmentInterface.php
- src/Sylius/Component/Shipping/ShipmentTransitions.php
- src/Sylius/Component/Shipping/ShipmentUnitTransitions.php
- src/Sylius/Component/Shipping/spec/Model/ShipmentSpec.php
> [Shipping] Refactor shipment state machine

- docs/book/products.rst
> [Documentation] Concepts: Products

- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Just as a note, there are more keys to delete, when we would remove a WebBundle.
> Remove duplicated keys

- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> Added notes translation

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
> [API] Surround resources with double quote

- src/Sylius/Component/Grid/Filter/StringFilter.php
- src/Sylius/Component/Grid/spec/Filter/StringFilterSpec.php
> [Grid] Fixes for StringFilter

- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
- src/Sylius/Bundle/TaxonomyBundle/composer.json
> [TaxonomyBundle] Remove Webmozart useless dependency

- features/order/managing_orders/seeing_order_shipment_state_after_checkout.feature
- features/order/managing_orders/shipping_order.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine.yml
- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/Model/OrderShippingStates.php
- src/Sylius/Component/Core/OrderProcessing/StateResolver.php
- src/Sylius/Component/Core/OrderShippingTransitions.php
- src/Sylius/Component/Core/spec/Model/OrderSpec.php
- src/Sylius/Component/Core/spec/OrderProcessing/StateResolverSpec.php
- src/Sylius/Component/Shipping/ShipmentTransitions.php
| Related tickets | https://github.com/Sylius/Sylius/pull/5606
> [Core][Order] Refactor order shipment state

- src/Sylius/Bundle/CoreBundle/Collector/SyliusCollector.php
> [Core] Make SyliusCollector catch correct exceptions

- src/Sylius/Component/Channel/Context/ChannelContextInterface.php
- src/Sylius/Component/Core/Context/ShopperContextInterface.php
> [Core] Make shopper context extend nested context interfaces

- src/Sylius/Bundle/CoreBundle/Resources/config/context.xml
- src/Sylius/Bundle/LocaleBundle/Context/RequestBasedLocaleContext.php
- src/Sylius/Bundle/LocaleBundle/spec/Context/RequestBasedLocaleContextSpec.php
| Related tickets | fixes #5649
> [Locale] Add request based locale context

- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
> [TaxonomyBundle] Add typehints on TaxonRepository

- src/Sylius/Bundle/UserBundle/Resources/config/services.xml
| Fixed tickets | #X
| Doc PR        | ~
This service moved to CustomerBundle.
> [UserBundle] Remove unused service.

- src/Sylius/Bundle/InstallerBundle/Command/InstallSampleDataCommand.php
> [Installer] Remove PHPCR fixtures from installing sample data

- docs/behat/how-to-add-new-context.rst
- docs/behat/how-to-add-new-page.rst
- docs/behat/introduction-to-containers-and-scopes.rst
- docs/contributing/documentation/overview.rst
Hey guys,
I was reading your documentation on how you use behat in your project and found some minor typos. Here are the fix suggestions.
I found inspiring ideas in the reading ;)
Congratz for the great job you do and take care!
> Fix various typos in documentation

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
| Related tickets | fixes #5561
> issue_5561

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/payment.yml
| Related tickets | fixes #5678
> Fixes 5678

- app/migrations/Version20160729162224.php
- features/channel/managing_channels/channel_validation.feature
- src/Sylius/Behat/Page/Admin/Channel/CreatePage.php
- src/Sylius/Bundle/CoreBundle/Form/Type/ChannelType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
> [Channel] Make default locale required

- src/Sylius/Bundle/AttributeBundle/Validator/Constraints/ValidAttributeValueValidator.php
- src/Sylius/Bundle/GridBundle/Renderer/TwigGridRenderer.php
- src/Sylius/Bundle/PricingBundle/Form/EventListener/BuildPriceableFormSubscriber.php
- src/Sylius/Bundle/PromotionBundle/Form/EventListener/AbstractConfigurationSubscriber.php
- src/Sylius/Bundle/ReportBundle/Form/EventListener/BuildReportDataFetcherFormSubscriber.php
- src/Sylius/Bundle/ReportBundle/Form/EventListener/BuildReportRendererFormSubscriber.php
- src/Sylius/Bundle/ReportBundle/Form/Type/ReportType.php
- src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php
- src/Sylius/Bundle/ResourceBundle/Routing/ResourceLoader.php
- src/Sylius/Bundle/SettingsBundle/Doctrine/EventListener/ParameterTransformerListener.php
- src/Sylius/Bundle/ShippingBundle/Form/EventListener/BuildRuleFormSubscriber.php
- src/Sylius/Bundle/ShippingBundle/Form/EventListener/BuildShippingMethodFormSubscriber.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodType.php
- src/Sylius/Component/Attribute/Factory/AttributeFactory.php
- src/Sylius/Component/Cart/Context/CompositeCartContext.php
- src/Sylius/Component/Grid/Data/DataSourceProvider.php
- src/Sylius/Component/Grid/Filtering/FiltersApplicator.php
- src/Sylius/Component/Payment/Resolver/CompositeMethodsResolver.php
- src/Sylius/Component/Pricing/Calculator/DelegatingCalculator.php
- src/Sylius/Component/Promotion/Checker/RulesEligibilityChecker.php
- src/Sylius/Component/Report/DataFetcher/DelegatingDataFetcher.php
- src/Sylius/Component/Report/Renderer/DelegatingRenderer.php
- src/Sylius/Component/Shipping/Calculator/DelegatingCalculator.php
- src/Sylius/Component/Shipping/Checker/ShippingMethodEligibilityChecker.php
- src/Sylius/Component/Shipping/Resolver/CompositeMethodsResolver.php
- src/Sylius/Component/Taxation/Calculator/DelegatingCalculator.php
Also, added a bunch of `FIXME` commands, I'll make the issues on Github as soon as it gets merged (so no additional description will be needed).
> Add typehints for objects taken from registries

- docs/bundles/SyliusShippingBundle/resolving_available_methods.rst
- docs/components/Shipping/basic_usage.rst
- docs/components/Shipping/interfaces.rst
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentMethodChoiceType.php
- src/Sylius/Bundle/PaymentBundle/Resources/config/services.xml
- src/Sylius/Bundle/PaymentBundle/spec/Form/Type/PaymentMethodChoiceTypeSpec.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodChoiceType.php
- src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
- src/Sylius/Bundle/ShippingBundle/spec/Form/Type/ShippingMethodChoiceTypeSpec.php
- src/Sylius/Component/Core/Resolver/ZoneAndChannelBasedShippingMethodsResolver.php
- src/Sylius/Component/Core/spec/Resolver/ZoneAndChannelBasedShippingMethodsResolverSpec.php
- src/Sylius/Component/Payment/Resolver/CompositeMethodsResolver.php
- src/Sylius/Component/Payment/Resolver/PaymentMethodsResolver.php
- src/Sylius/Component/Payment/Resolver/PaymentMethodsResolverInterface.php
- src/Sylius/Component/Payment/spec/Resolver/CompositeMethodsResolverSpec.php
- src/Sylius/Component/Payment/spec/Resolver/PaymentMethodsResolverSpec.php
- src/Sylius/Component/Shipping/Resolver/CompositeMethodsResolver.php
- src/Sylius/Component/Shipping/Resolver/ShippingMethodsResolver.php
- src/Sylius/Component/Shipping/Resolver/ShippingMethodsResolverInterface.php
- src/Sylius/Component/Shipping/spec/Resolver/CompositeMethodsResolverSpec.php
- src/Sylius/Component/Shipping/spec/Resolver/ShippingMethodsResolverSpec.php
> [Core][Shipping][Payment] Rename resolvers

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion_coupon.yml
- src/Sylius/Bundle/ProductBundle/DependencyInjection/Compiler/ServicesPass.php
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/SyliusPromotionExtension.php
- src/Sylius/Component/Product/Factory/ProductVariantFactory.php
- src/Sylius/Component/Product/Factory/ProductVariantFactoryInterface.php
- src/Sylius/Component/Product/spec/Factory/ProductVariantFactorySpec.php
- src/Sylius/Component/Promotion/Factory/CouponFactory.php
- src/Sylius/Component/Promotion/Factory/CouponFactoryInterface.php
- src/Sylius/Component/Promotion/spec/Factory/CouponFactorySpec.php
Thanks to #5559 we are able to decouple factories from repositories 🎉
> [Factory] Decouple ProductVariantFactory and CouponFactory from repositories

- etc/travis/suites/application/script/test-behat-with-javascript
- etc/travis/suites/application/script/test-behat-without-javascript
> [Maintenance] Remove unused @legacy tag

- features/promotion/managing_promotions/adding_promotion_with_rule.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Promotion/_form.html.twig
- src/Sylius/Bundle/CoreBundle/Form/Type/Rule/ContainsProductConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/form.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
> [CoreBundle] Unplugged 'loyalty', 'group', 'product' rules and 'add_product' action

- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Address.orm.xml
- src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Comment.orm.xml
> [CoreBundle][OrderBundle] Cascade delete addresses and comments

- src/Sylius/Behat/Context/Domain/OrderContext.php
> Bugfix test order domain context

- docs/customization/form.rst
> Namespace does not match

- composer.json
- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
| Related tickets | fixes #5709 
> fixes for #5709

- features/taxation/applying_taxes/applying_correct_taxes_for_product_with_tax_rate_included_in_price.feature
- features/taxation/managing_tax_rates/adding_tax_rate.feature
- features/taxation/managing_tax_rates/deleting_tax_rate.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxRateContext.php
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Page/Admin/TaxRate/CreatePage.php
- src/Sylius/Behat/Page/Admin/TaxRate/CreatePageInterface.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
- src/Sylius/Bundle/AdminBundle/Resources/views/TaxRate/_form.html.twig
> [Shop][Admin] Include tax rate in product price

- features/promotion/revert_discount/reverting_previously_applied_discount_on_cart.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
> [Behat][Promotion] Added reverting item based promotion scenario

- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
> [Command] Fix setup command

- etc/travis/suites/application/script.sh
- etc/travis/suites/application/script/test-behat-with-cli
> [Travis] Run cli tagged Behat scenarios

- docs/book/index.rst
- docs/book/map.rst.inc
- docs/book/taxons.rst
> [Documentation] Concepts: Taxons

- docs/book/architecture.rst
- docs/book/installation.rst
| Related tickets | partially #5275, #5746 
> [Documentation] Installation and Architecture fix

- docs/book/taxons.rst
| Related tickets | partially #5275
> [Documentation] Concepts: taxons - mainTaxon

- composer.json
- composer.lock
- src/Sylius/Bundle/ResourceBundle/composer.json
> [Composer] Use stable ApiTestCase

- src/Sylius/Bundle/CartBundle/Controller/CartController.php
- src/Sylius/Bundle/CartBundle/EventListener/CartSubscriber.php
- src/Sylius/Bundle/CartBundle/EventListener/FlashSubscriber.php
- src/Sylius/Bundle/CartBundle/spec/EventListener/CartSubscriberSpec.php
- src/Sylius/Component/Cart/SyliusCartEvents.php
> [Cart] Refactor clearing cart

- src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/Show/_breadcrumb.html.twig
Added missing quotes to the home anchor
> Added missing quotes

- docs/behat/how-to-add-new-context.rst
- docs/behat/how-to-add-new-page.rst
- docs/behat/how-to-define-new-suite.rst
- docs/behat/how-to-use-transformers.rst
> [Docs] Adjust a Behat guide to latest changes

- docs/bundles/SyliusGridBundle/installation.rst
| Related tickets | fixes #5794
> [Docs] Remove AttributeBundle from installation of GridBundle

- src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
| Related tickets | https://github.com/Sylius/Sylius/pull/5539
> [User] Get metadata definition from registry

- src/Sylius/Bundle/InstallerBundle/Command/InstallDatabaseCommand.php
| Related tickets | fixes #5764, #5790
This fix will finally allow to load fixtures even if database doesn't exist, schema exist and we don't want to reset it, if we decide to reset it, or if we have database without any schema.
> [Installer] Install database fixes

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/customer.yml
Add missing permission = true on customer show route
> [Rbac][AdminBundle] Add missing check permission on admin customer show route

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
Check lines 444. The settings were duplicated
> Removed duplicate setting

- app/config/routing.yml
In #5547 this routing has been added, but it is unnecessary, because I have fix it already in #5632
> [API] Remove unneeded routing

- docs/bundles/SyliusRbacBundle/installation.rst
| Related tickets | fixes #5793 
Update doc for RbacBundle installation
> [Docs][RbacBundle] Add sylius.cache parameter config

- src/Sylius/Bundle/CoreBundle/EventListener/AddAdministratorRoleListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/spec/EventListener/AddAdministratorRoleListenerSpec.php
> [Core][User] Add administrator role

- src/Sylius/Behat/Context/Hook/DoctrineORMContext.php
This class cannot exist without EntityManager defined.
> [Behat] Remove unnecessary check

- composer.json
- composer.lock
- src/Sylius/Bundle/UiBundle/composer.json
> [Composer] Update KnpMenuBundle to ^2.0

- src/Sylius/Behat/Context/Domain/ManagingOrdersContext.php
- src/Sylius/Behat/Context/Domain/ManagingPaymentsContext.php
- src/Sylius/Behat/Context/Domain/ManagingProductsContext.php
- src/Sylius/Behat/Context/Domain/ManagingPromotionCouponsContext.php
- src/Sylius/Behat/Context/Domain/ManagingPromotionsContext.php
- src/Sylius/Behat/Context/Domain/ManagingShipmentsContext.php
- src/Sylius/Behat/Context/Domain/OrderContext.php
- src/Sylius/Behat/Resources/config/services/contexts/domain.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/domain/order/managing_orders.yml
- src/Sylius/Behat/Resources/config/suites/domain/product/managing_product_variants.yml
- src/Sylius/Behat/Resources/config/suites/domain/product/managing_products.yml
- src/Sylius/Behat/Resources/config/suites/domain/promotion/managing_promotion_coupons.yml
- src/Sylius/Behat/Resources/config/suites/domain/promotion/managing_promotions.yml
> [Behat][Domain] Minor refactor domain contexts

- src/Sylius/Bundle/UiBundle/Resources/views/Menu/sidebar.html.twig
| Related tickets | fixes #5866
> remove duplicated sidebar in admin

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/user.yml
| Q                        | A
| --------------------- | ---
| Bug fix?             | yes
| BC breaks?       | yes
| Related tickets  | fixes #5874 
| License             | MIT
> Fix on users service routing file

- src/Sylius/Bundle/AdminBundle/Gulpfile.js
- src/Sylius/Bundle/ShopBundle/Gulpfile.js
| Related tickets | fixes #5871
> [Gulp] Fix path to theme icons

- features/user/managing_administrators/administrator_unique_email_and_name_validation.feature
- features/user/managing_administrators/browsing_administrator.feature
- features/user/managing_administrators/deleting_administrators.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingAdministratorsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
- src/Sylius/Bundle/UserBundle/Resources/config/services.xml
> [Behat][Admin] Create delete admin feature

- docs/book/checkout.rst
- docs/book/index.rst
- docs/book/map.rst.inc
> [Documentation] Concepts: Checkout

- src/Sylius/Bundle/InstallerBundle/Command/InstallDatabaseCommand.php
| Related tickets | fixes #5890 
> [Rbac] Removing rbac from Sylius installer - Fixes- #5890

- features/user/managing_users/deleting_account.feature
- src/Sylius/Behat/Page/Admin/Customer/ShowPage.php
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/user.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/show.html.twig
> [Admin] Removing shop user account

- features/cart/shopping_cart/viewing_cart_summary_in_many_channels.feature
- src/Sylius/Behat/Context/Transform/ChannelContext.php
- src/Sylius/Behat/Context/Ui/ChannelContext.php
- src/Sylius/Behat/Resources/config/suites/ui/cart/shopping_cart.yml
- src/Sylius/Bundle/CartBundle/EventListener/SessionCartSubscriber.php
- src/Sylius/Bundle/CoreBundle/Context/SessionAndChannelBasedCartContext.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/CartRepository.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/CoreBundle/Resources/config/context.xml
- src/Sylius/Bundle/CoreBundle/spec/Context/SessionAndChannelBasedCartContextSpec.php
- src/Sylius/Component/Core/Repository/CartRepositoryInterface.php
> [Shop][Cart] Update cart after channel switching  

- src/Sylius/Bundle/CartBundle/Controller/Controller.php
> [Cart] Controller cleanup

- docs/bundles/SyliusInventoryBundle/installation.rst
- Corrects references to classes moved from the bundle to the component
- Removes configuration references for routing and templates, neither exist in the bundle
- Updates the component configuration example to match the current definition
> Tweaks for inventory bundle installation docs
