Sylius/Sylius

- src/Sylius/Bundle/FlowBundle/Process/Builder/ProcessBuilder.php
- src/Sylius/Bundle/FlowBundle/spec/Process/Builder/ProcessBuilderSpec.php
| BC breaks?      | no/hope not
Currently the `isActive` method of the `StepInterface` is not used.
We have a situation where we would like to "remove" a checkout step based on a certain condition.
I assume that this is what the `isActive()` method was intended for, it is here added to the `ProcessBuilder`.
> Only add steps that are active

- docs/book/architecture.rst
- docs/book/state_machine.rst
> [Documentation] Architecture - Resource Layer & State Machine

- features/account/sign_in.feature
- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
- src/Sylius/Behat/Context/Ui/UserContext.php
- src/Sylius/Behat/Page/Shop/Account/LoginPage.php
- src/Sylius/Behat/Page/Shop/Account/LoginPageInterface.php
Small typo. I bet we have meant [username instead of user name](http://english.stackexchange.com/a/43470).
> [Behat] Username typo

- src/Sylius/Bundle/GridBundle/Doctrine/ORM/ExpressionBuilder.php
- src/Sylius/Component/Grid/Filter/StringFilter.php
| Related tickets | mentioned in #5476
I also had some issues when filter form was submitting with empty string value so I thought maybe do not restrict DataSource when filer data is empty?!
> [GridBundle] Allow filtering by fields from associated objects

- src/Sylius/Bundle/ProductBundle/Behat/ProductContext.php
- src/Sylius/Component/Attribute/Factory/AttributeFactory.php
- src/Sylius/Component/Attribute/spec/Factory/AttributeFactorySpec.php
> [Attribute] Unsupport ``createNew()`` method of attribute factory

- src/Sylius/Bundle/PayumBundle/composer.json
> correct payum version constraints for SyliusPayumBundle

- src/Sylius/Bundle/PayumBundle/Model/PaymentSecurityToken.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterResourcesPass.php
- src/Sylius/Bundle/ResourceBundle/EventListener/AbstractDoctrineSubscriber.php
- src/Sylius/Bundle/ResourceBundle/EventListener/ODMMappedSuperClassSubscriber.php
- src/Sylius/Bundle/ResourceBundle/EventListener/ORMMappedSuperClassSubscriber.php
- src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Entity/BookTranslation.php
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/DependencyInjection/Compiler/RegisterResourcesPassTest.php
- src/Sylius/Bundle/SearchBundle/Model/SearchIndexInterface.php
- src/Sylius/Bundle/SearchBundle/Model/SearchLogInterface.php
- src/Sylius/Component/Core/Model/ImageInterface.php
- src/Sylius/Component/Order/Model/Identity.php
- src/Sylius/Component/Order/Model/IdentityInterface.php
> [Resource] Fix resource loading / metadata

- src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
- src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
In order to keep testing consistency I need to extend crud pages object and override only some methods of them like `getRouteName()`, hence I have to set protected access on some properties. WDYT?
> [Behat] Make crud page objects extendable

- src/Sylius/Bundle/OrderBundle/NumberAssigner/OrderNumberAssigner.php
- src/Sylius/Bundle/OrderBundle/NumberGenerator/OrderNumberGeneratorInterface.php
- src/Sylius/Bundle/OrderBundle/NumberGenerator/SequentialOrderNumberGenerator.php
- src/Sylius/Bundle/OrderBundle/spec/NumberAssigner/OrderNumberAssignerSpec.php
- src/Sylius/Bundle/OrderBundle/spec/NumberGenerator/SequentialOrderNumberGeneratorSpec.php
> [Order] Fix number generator

- src/Sylius/Bundle/CoreBundle/Fixture/TaxonFixture.php
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/TaxonFixtureTest.php
- src/Sylius/Bundle/FixturesBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/ConfigurationTest.php
| Related tickets | fixes #5572
> [Fixtures] Allow for nested array nodes at sylius_fixtures.**.options and taxon.children

- docs/book/payments.rst
Troubleshooting was misspelled "troubleshoooting"
> Correct a typo in word "troubleshooting"

- app/migrations/Version20160725084855.php
- features/channel/managing_channels/adding_channel.feature
- features/channel/managing_channels/channel_validation.feature
- features/channel/managing_channels/not_being_able_to_add_disabled_channel_when_no_other_exist.feature
- features/channel/managing_channels/not_being_able_to_disable_last_available_channel.feature
- features/channel/managing_channels/selecting_default_tax_zone_for_channel.feature
- features/channel/managing_channels/selecting_locales_available_for_channel.feature
- features/channel/managing_channels/selecting_payment_methods_available_for_channel.feature
- features/channel/managing_channels/selecting_shipping_methods_available_for_channel.feature
- features/channel/managing_channels/selecting_tax_calculation_strategy_for_channel.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
- src/Sylius/Behat/Page/Admin/Channel/CreatePage.php
- src/Sylius/Behat/Page/Admin/Channel/CreatePageInterface.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
| Related tickets | https://github.com/Sylius/Sylius/pull/5565
> [Channel] Add not blank validation for channel default currency

- tests/DataFixtures/ORM/resources/channels.yml
> [Api][Test] Add default currency

- docs/book/attributes.rst
- docs/book/index.rst
- docs/book/map.rst.inc
- docs/components/Attribute/basic_usage.rst
> [Documentation] Concepts: Attributes

- src/Sylius/Bundle/ResourceBundle/Routing/Configuration.php
- src/Sylius/Bundle/ResourceBundle/Routing/ResourceLoader.php
- src/Sylius/Bundle/ResourceBundle/spec/Routing/ResourceLoaderSpec.php
At \Sylius\Bundle\ResourceBundle\Routing\Configuration 
> ->scalarNode('permission')->defaultValue(false)->end()
Should this node have boolean type?
> Process missing 'permission' parameter in ResourceLoader

- src/Sylius/Bundle/ResourceBundle/Controller/ParametersParser.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ParametersParserSpec.php
| Fixed tickets | ~
To decouple our service from other services, we just simply use standard Sylius service configuration without registering unnecessary service by compile pass or manual configure by using services file.
For example, we want to create new product with `archetype`, no need to couple `ProductFactory` with `ArchetypeRepository` to find `archetype`. We just inject the real `ArchetypeObject` into factory method directly as parameter.
Factory
```php
public function createFromArchetype($archetypeCode)
// refactoring
public function createFromArchetype(ArchetypeInterface $archetype)
```
Routing configuration …
> [ResourceBundle] Allow arguments with expression service accept parameters.

- app/config/security.yml
- docs/api/authorization.rst
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- tests/Controller/OauthTokenApiTest.php
- tests/DataFixtures/ORM/authentication/api_administrator.yml
- tests/Responses/Expected/authentication/new_access_token.json
BC Break included. Before, access token was available under `/oauth/v2/token` path. Now, it is available under `/api/oauth/v2/token`.
> [API] Fix api authenticator

- src/Sylius/Bundle/GridBundle/Doctrine/DBAL/ExpressionBuilder.php
- src/Sylius/Bundle/GridBundle/Doctrine/ORM/ExpressionBuilder.php
- src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExpressionBuilder.php
- src/Sylius/Component/Grid/Data/ExpressionBuilderInterface.php
- src/Sylius/Component/Grid/Filter/StringFilter.php
- src/Sylius/Component/Grid/spec/Filter/StringFilterSpec.php
Should be faster, more intuitive and cleaner.
> [Grid] Introduce variadics

- features/cart/shopping_cart/adding_products_with_quantity_to_cart.feature
- features/cart/shopping_cart/inability_of_adding_a_product_with_insufficient_stock.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Transform/SharedStorageContext.php
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Behat/Page/Shop/Product/ShowPage.php
- src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/cart/shopping_cart.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/InventoryBundle/Resources/config/services.xml
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_addToCart.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_inventory.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_outOfStock.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/show.html.twig
- src/Sylius/Component/Inventory/Checker/AvailabilityChecker.php
- src/Sylius/Component/Inventory/spec/Checker/AvailabilityCheckerSpec.php
[BC Break] - removal of `backorders` flag from sylius configuration, most likely it's going to be brought back to life or replaced after `Inventory`'s refactoring
> [Behat][Shop] Added stock level dependant rendering of simple product's details page

- src/Sylius/Component/Core/Provider/ChannelBasedCurrencyProvider.php
There's no reason not to use `map` on Collection instead of `array_map` on array (nice chaining included).
> [Core] Rewrite ChannelBasedCurrencyProvider

- src/Sylius/Bundle/ThemeBundle/Asset/Installer/AssetsInstaller.php
- src/Sylius/Bundle/ThemeBundle/Tests/Functional/AssetTest.php
- src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/Resources/views/Asset/modifiedAssetsTest.txt.twig
This PR fixes an issue when you want to update your assets once they were already installed at least one time. Let's say I have installed assets, I edit one of the asset files in my theme and run `sylius:theme:assets:install` command again - the updated asset file won't be copied over to the `web` directory, thus I still get the old version.
> [ThemeBundle] fixed assets re-installation

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
| Related tickets | fixes #5561 
> Issue#5561: Taxon root is not being checked

- features/product/viewing_products/viewing_product_price_on_products_list.feature
- features/product/viewing_products/viewing_products_price.feature
- src/Sylius/Behat/Context/Domain/OrderContext.php
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Behat/Page/Shop/Product/ShowPage.php
- src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php
- src/Sylius/Behat/Page/Shop/Taxon/ShowPage.php
- src/Sylius/Behat/Page/Shop/Taxon/ShowPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/domain.xml
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
- src/Sylius/Behat/Resources/config/suites/ui/product/viewing_products.yml
- src/Sylius/Bundle/CoreBundle/Cart/ItemResolver.php
- src/Sylius/Bundle/CoreBundle/EventListener/ImageUploadListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/spec/Cart/ItemResolverSpec.php
- src/Sylius/Bundle/CoreBundle/spec/EventListener/ImageUploadListenerSpec.php
- src/Sylius/Bundle/ProductBundle/DependencyInjection/SyliusProductExtension.php
- src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/ProductOptionFieldSubscriber.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductType.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_price.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_simpleBox.html.twig
- src/Sylius/Bundle/VariationBundle/Resources/config/services.xml
- src/Sylius/Component/Variation/Resolver/DefaultVariantResolver.php
- src/Sylius/Component/Variation/Resolver/VariantResolverInterface.php
- src/Sylius/Component/Variation/spec/Resolver/DefaultVariantResolverSpec.php
> [Shop][Product] Viewing product's price

- docs/api/authorization.rst
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/UserExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/UserFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
After changes in *FixturesBundle* we've lost default API user, which is obviously useful for API development.
> [API][Fixtures] Added default API user

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
Fix findEnabledByTaxonCodeAndChannel in ProductRepository with true value instead of 1, for PostgreSQL compatibility.
> [Core][Product] Fix query with true value instead of 1

- docs/api/customers.rst
- docs/api/users.rst
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/customer.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/locale.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/payment.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/payment_method.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_archetype.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_attribute.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/promotion_coupon.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/shipment.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/shipping_method.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/user.yml
Some of the endpoints were unusable due to bad sorting and therefore fatal errors throwing.
> [API] API fixes

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/zone.yml
- tests/Controller/ZoneApiTest.php
- tests/DataFixtures/ORM/resources/countries.yml
- tests/DataFixtures/ORM/resources/zones.yml
- tests/Responses/Expected/country/index_response.json
- tests/Responses/Expected/zone/create_response.json
- tests/Responses/Expected/zone/create_validation_fail_response.json
- tests/Responses/Expected/zone/index_response.json
- tests/Responses/Expected/zone/show_response.json
- tests/Responses/Expected/zone/update_response.json
- tests/Responses/Expected/zone/update_validation_fail_response.json
> [API][Zone] Zone API tests

- features/account/sign_in.feature
- features/user/managing_customers/browsing_customers.feature
- features/user/managing_customers/seeing_customer_details.feature
- src/Sylius/Behat/Context/Setup/UserContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPage.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/customer.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/customer.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/user.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/show.html.twig
> [Admin] [Customer]Remove delete button on index, add information about no account on show page

- features/checkout/paying_for_order/preventing_not_available_payment_method_selection.feature
- src/Sylius/Behat/Context/Setup/PaymentContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentMethodRepository.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Component/Core/Repository/PaymentMethodRepositoryInterface.php
- src/Sylius/Component/Core/Resolver/ChannelBasedPaymentMethodsResolver.php
- src/Sylius/Component/Core/spec/Resolver/ChannelBasedPaymentMethodsResolverSpec.php
- src/Sylius/Component/Payment/Repository/PaymentMethodRepositoryInterface.php
> [Shop][Payment] Prevent selecting payment method not assigned to channel

- app/AppKernel.php
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
Moving this three bundle to ``AppKernel`` makes it much more easy to unplug one of the *Sylius* sections (it would also be really useful for *Sylius-Standard*).
> [Core] Move main Sylius bundles to AppKernel

- docs/api/orders.rst
- src/Sylius/Bundle/CoreBundle/Form/Type/Api/OrderType.php
The OrderType in ApiBundle has the optional **customer** field instead of the mandatory and deprecated **user** field.
> [API][Order] Update OrderType to have customer optional

- Gulpfile.js
- src/Sylius/Bundle/AdminBundle/Gulpfile.js
- src/Sylius/Bundle/AdminBundle/package.json
- src/Sylius/Bundle/ShopBundle/Gulpfile.js
- src/Sylius/Bundle/ShopBundle/package.json
We should deeply consider gulp files structure in *Sylius*. First step could be splitting ``Gulpfile.js`` into *ShopBundle* and *AdminBundle*, that would allow us to easily install only needed assets (again - superuseful for *Sylius-Standard*).
> [Gulp] Clean up Sylius gulp files

- features/installer/install_command.feature
- src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php
- src/Sylius/Component/Core/Model/AdminUser.php
By default a setup command should create an admin user, not a shop one.
> [Instaltion] Fix setup instalator

- src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
This PR enables the possibility to set the theme name in the fixtures as follows:
```yml
sylius_fixtures:
suites:
default:
listeners:
orm_purger: ~
logger: ~
fixtures:
channel:
options:
custom:
us_web_store:
name: US Web Store
locales:
- "%locale%"
currencies:
- "%currency%"
shipping_methods:
- ups
- dhl_express
- fedex
payment_methods:
- cash_on_delivery
- bank_transfer
theme_name: vendor/theme-name
```
> Allow setting theme name in Channel fixtures

- composer.json
- composer.lock
| Related tickets | #5869
Now that RBAC is out of core, it should be possible to require `sylius/rbac` and/or `sylius/rbac-bundle` in a project where `sylius/sylius` is already a dependency.
These two lines are preventing it and should be removed.
I don't think `composer.lock` requires an update, please let me know if I'm wrong.
> [Rbac] Remove RBAC-related packages from composer "replace" list

- docs/bundles/SyliusProductBundle/installation.rst
Translation bundle doesn't exist anymore, can't enable a bundle that doesn't exist.
> Remove reference to translation bundle

- docs/bundles/SyliusPromotionBundle/models.rst
| Related tickets | partially #5901
> [Docs] Models referred in PromotionBundle docs had wrong paths

- docs/bundles/SyliusPricingBundle/index.rst
- docs/bundles/SyliusPricingBundle/installation.rst
- docs/bundles/index.rst
- docs/bundles/map.rst.inc
There is no documentation for the pricing bundle and clicking the docs link in the bundle's README results in a 404 page.  This creates stubs so there's at least a usable (even if minimal) page to be found.
> Stubs for pricing bundle docs

- src/Sylius/Component/Shipping/Calculator/CalculatorInterface.php
- src/Sylius/Component/Shipping/Calculator/DelegatingCalculator.php
- src/Sylius/Component/Shipping/Calculator/DelegatingCalculatorInterface.php
- src/Sylius/Component/Shipping/Calculator/FlatRateCalculator.php
- src/Sylius/Component/Shipping/Calculator/FlexibleRateCalculator.php
- src/Sylius/Component/Shipping/Calculator/PerUnitRateCalculator.php
- src/Sylius/Component/Shipping/Calculator/VolumeRateCalculator.php
- src/Sylius/Component/Shipping/Calculator/WeightRateCalculator.php
- src/Sylius/Component/Shipping/spec/Calculator/PerUnitRateCalculatorSpec.php
- src/Sylius/Component/Shipping/spec/Calculator/VolumeRateCalculatorSpec.php
- src/Sylius/Component/Shipping/spec/Calculator/WeightRateCalculatorSpec.php
Instead of **ShippingSubjectInterface** we should now use the **ShipmentInterface** - corrected in the **CalculatorInterface** and all its implementations. :)
> [Shipping] ShipmentInterface of subject in the Calculators fix

- docs/bundles/SyliusCartBundle/services.rst
- src/Sylius/Bundle/CartBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/CartBundle/DependencyInjection/SyliusCartExtension.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
| Related tickets | continuation from #5862
The `Sylius\Component\Cart\Resolver\ItemResolverInterface` was removed and its uses in the CartBundle pulled out as well.  However it is still required to configure a resolver in the CartBundle's configuration.  Removed this configuration requirement and the remaining documentation for the service.
> Remove the remaining resolver references

- app/migrations/Version20160829162740.php
- features/account/customer_account/subscribing_newsletter.feature
- src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
- src/Sylius/Behat/Page/Shop/Account/ProfileUpdatePage.php
- src/Sylius/Behat/Page/Shop/Account/ProfileUpdatePageInterface.php
- src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerProfileType.php
- src/Sylius/Bundle/CustomerBundle/Resources/config/doctrine/model/Customer.orm.xml
- src/Sylius/Bundle/CustomerBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/CustomerBundle/spec/Form/Type/CustomerProfileTypeSpec.php
- src/Sylius/Bundle/CustomerBundle/spec/Form/Type/CustomerTypeSpec.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/profileUpdate.html.twig
- src/Sylius/Component/Customer/Model/Customer.php
- src/Sylius/Component/Customer/Model/CustomerInterface.php
- tests/Responses/Expected/customer/create_validation_fail_response.json
- tests/Responses/Expected/customer/create_with_user_validation_fail_response.json
- tests/Responses/Expected/customer/update_validation_fail_response.json
> [Account] Subscribe to the newsletter in customer account

- features/checkout/prices_get_updated_throughout_checkout.feature
- features/checkout/returning_from_order_summary_page_to_one_of_previous_steps.feature
- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectPaymentPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectPaymentPageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPageInterface.php
- src/Sylius/Behat/Page/Shop/HomePage.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/shop/checkout.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/order_processor.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_summary.html.twig
- src/Sylius/Component/Core/OrderProcessing/OrderExchangeRateProcessor.php
- src/Sylius/Component/Core/Updater/OrderExchangeRateAndCurrencyUpdater.php
- src/Sylius/Component/Core/Updater/OrderExchangeRateUpdater.php
- src/Sylius/Component/Core/Updater/OrderUpdaterInterface.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderExchangeRateProcessorSpec.php
- src/Sylius/Component/Core/spec/Updater/OrderExchangeRateAndCurrencyUpdaterSpec.php
- src/Sylius/Component/Core/spec/Updater/OrderExchangeRateUpdaterSpec.php
> [Checkout] Ensured exchange rate gets updated throughout checkout

- features/order/managing_orders/shipping_order.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Context/Ui/EmailContext.php
- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
- src/Sylius/Behat/Context/Ui/Shop/RegistrationContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites/ui/account/login.yml
- src/Sylius/Behat/Resources/config/suites/ui/account/registration.yml
- src/Sylius/Behat/Resources/config/suites/ui/account/verification.yml
- src/Sylius/Behat/Resources/config/suites/ui/order/managing_orders.yml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/CoreBundle/Resources/views/Email/shipmentConfirmation.html.twig
- src/Sylius/Bundle/ShippingBundle/Controller/ShipmentController.php
| Related tickets | - 
Based on #5912
> [Behat] Checked if the shipment confirmation email gets sent

- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Bundle/CoreBundle/EventListener/OrderRecalculationListener.php
- src/Sylius/Bundle/CoreBundle/EventListener/UserCartRecalculationListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/order_processor.xml
- src/Sylius/Bundle/CoreBundle/spec/EventListener/OrderRecalculationListenerSpec.php
- src/Sylius/Bundle/CoreBundle/spec/EventListener/UserCartRecalculationListenerSpec.php
- src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
- src/Sylius/Component/Core/OrderProcessing/OrderAdjustmentsClearer.php
- src/Sylius/Component/Core/OrderProcessing/OrderExchangeRateProcessor.php
- src/Sylius/Component/Core/OrderProcessing/OrderPaymentProcessor.php
- src/Sylius/Component/Core/OrderProcessing/OrderPricesRecalculator.php
- src/Sylius/Component/Core/OrderProcessing/OrderPromotionProcessor.php
- src/Sylius/Component/Core/OrderProcessing/OrderShipmentProcessor.php
- src/Sylius/Component/Core/OrderProcessing/OrderTaxesProcessor.php
- src/Sylius/Component/Core/OrderProcessing/ShippingChargesProcessor.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderAdjustmentsClearerSpec.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderExchangeRateProcessorSpec.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderPaymentProcessorSpec.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderPricesRecalculatorSpec.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderShipmentProcessorSpec.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderTaxesProcessorSpec.php
- src/Sylius/Component/Core/spec/OrderProcessing/ShippingChargesProcessorSpec.php
- src/Sylius/Component/Order/Processor/CompositeOrderProcessor.php
- src/Sylius/Component/Order/Processor/OrderProcessorInterface.php
`CompositeOrderProcessor` doesn't have any external dependencies, so it could be useful to keep it inside an `Order` component instead of core. Same with `OrderProcessorInterface`. 
When it'll be merged, `CartModifier` from #5970 could be moved to `CartBundle` from the Core also.
> [RFC] [OrderComponent] OrderProcessorInterface moved to order component.

- src/Sylius/Component/Core/OrderProcessing/OrderExchangeRateProcessor.php
- src/Sylius/Component/Core/OrderProcessing/OrderPaymentProcessor.php
- src/Sylius/Component/Core/OrderProcessing/OrderPricesRecalculator.php
- src/Sylius/Component/Core/OrderProcessing/OrderPromotionProcessor.php
- src/Sylius/Component/Core/OrderProcessing/OrderShipmentProcessor.php
- src/Sylius/Component/Core/OrderProcessing/OrderTaxesProcessor.php
- src/Sylius/Component/Core/OrderProcessing/ShippingChargesProcessor.php
| Related tickets | related to #5971
> [Core] Typehint for Core Order if needed

- features/promotion/receiving_discount/receiving_percentage_discount_promotion_on_order.feature
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Component/Core/Promotion/Action/PercentageDiscountAction.php
- src/Sylius/Component/Core/spec/Promotion/Action/PercentageDiscountActionSpec.php
> [Promotion] Use proportional distribution in order percentage discount

- src/Sylius/Bundle/ThemeBundle/Twig/ThemeFilesystemLoader.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/5886
> [Theme] Twig loader quick fix to avoid profiler exception

- src/Sylius/Bundle/ShopBundle/Resources/config/routing/checkout.yml
Just a very minor cleanup for a duplicate config entry that was introduced in 0b555349.
> Remove duplicate “flash” config entry

- src/Sylius/Component/Promotion/Action/PromotionApplicator.php
- src/Sylius/Component/Promotion/Action/PromotionApplicatorInterface.php
Provides IDE support for `execute` / `revert` methods.
> [Promotion] Clean up PromotionApplicator

- docs/book/checkout.rst
There was a misspelled on. I have change it from `ont` to `on`.
The whole sentence was
```
is run and checks all the adjustments ont the order.
```
and not it is
is run and checks all the adjustments on the order.
> Correct spelling

- docs/bundles/SyliusOrderBundle/index.rst
- docs/bundles/SyliusOrderBundle/processors.rst
- docs/components/Order/index.rst
- docs/components/Order/processors.rst
First time using `.rst`, hope formatting is okey
> [Documentation][Order] Added order processor docs

- docs/customization/index.rst
- docs/customization/map.rst.inc
- docs/customization/state_machine.rst
> [Documentation] Customization Guide: State Machine

- docs/book/taxation.rst
> [Documentation] Concepts: Taxation

- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Component/Core/Resolver/ZoneAndChannelBasedShippingMethodsResolver.php
- src/Sylius/Component/Core/spec/Resolver/ZoneAndChannelBasedShippingMethodsResolverSpec.php
| Related tickets | fixes #5861
Check for shipping method eligibility when getting shipping methods based on zone and channel.
> [BugFix][Core] Added shipping method eligibility checker to core methods resolver

- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine.yml
| Related tickets | fixes #5667
I looked into issue #5667 and I think the best way to solve it is to remove the whole cascade of the transitions all together. This will prevent some nasty errors that are currently present in core.
> [BugFix][Core] Remove cascade transitions on sylius_shipment_unit

- src/Sylius/Component/Core/Promotion/Checker/Rule/ShippingCountryRuleChecker.php
- src/Sylius/Component/Core/spec/Promotion/Checker/Rule/ShippingCountryRuleCheckerSpec.php
This promotion rule is currently broken and ignored when used.
> [Bug Fix] ShippingCountryRuleChecker, Use the country configuration as a code, instead of it's id

- src/Sylius/Bundle/ShopBundle/Controller/CurrencyController.php
- src/Sylius/Bundle/ShopBundle/Controller/LocaleController.php
I noticed that when you directly switch the locale or currency you get a 500 error since there is no `referer`. These changes will provide a nice fallback for when that happens.
> [ShopBundle] Locale and currency switcher small improvement

- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_addresses.html.twig
| Related tickets | fixes #6098 
Use the `_address.html.twig` partial template from the ShopBundle instead of the AdminBundle.
> [ShopBundle] Fix dependency issue with AdminBundle in _addresses.html.twig

- src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodChoiceType.php
use code to show shipping method options, because id will change when we generate sample data each time , but  code is fixed ,it  is much easier for api.
> use code to show shipping method options

- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
| Related tickets | - 
Should fix the 1/empty label rendering in admin's customer index. No way to test it without SyliusBot push crowdin and getting translations back. 😞
> [Ui] Fixed yes/no translations

- src/Sylius/Bundle/CoreBundle/Resources/config/integration/hwi_oauth.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/test_services.xml
> [Core] Remove all *.class parameters

- app/config/security.yml
| Related tickets | fixes #6168 
> [Security] Admin redirection fix

- features/order/managing_orders/seeing_order_item_detailed_data.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
- src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/order/managing_orders.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_item.html.twig
| Related tickets | fixes #6116
> [Admin] Changed product code to variant code on orders show page

- src/Sylius/Bundle/UserBundle/composer.json
- src/Sylius/Component/User/composer.json
| Related tickets | partially #5999
The User component only uses Doctrine's Collections library.  Instead of requiring the full ORM, only that library is required instead using the same version constraint the ORM uses at 2.4.8.
> The User component only requires doctrine/collections

- app/config/security.yml
| Related tickets | partially #3564 
Quote from Symfony Profiler: "remember_me.key is deprecated since version 2.8 and will be removed in 3.0. Use remember_me.secret instead."
> [Sylius] Changed remember_me key to secret

- features/product/managing_products/changing_images_of_product.feature
- features/product/managing_products/product_image_unique_code.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPageInterface.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
- src/Sylius/Bundle/CoreBundle/Resources/config/validation.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
This PR is based on one commit from https://github.com/Sylius/Sylius/pull/6183
> [Admin][Product] Product image unique code validation

- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine.yml
- sylius_create_payment (sylius_order_checkout state machine) is already applyed on sylius_order state machine
- move sylius_request_payment from sylius_order to sylius_order_checkout, to keep consistency with sylius_request_shipping
> Cleanup some state machine callbacks.

- docs/book/orders.rst
> [Documentation] Concepts: Orders

- src/Sylius/Bundle/ShopBundle/Gulpfile.js
> [Shop][UI] Fix styles path for the shop

- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine.yml
Move sylius_request_shipping & sylius_request_payment callbacks to sylius_order state machine.
Basically do the same job than before :)
> Cleanup some state machine callbacks | Reviews

- app/config/routing.yml
| Related tickets | fixes #6168 [comment](https://github.com/Sylius/Sylius/issues/6168#issuecomment-250596019)
> [Admin] Fix admin without a slash sufix path

- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
> [Admin] Remove admin root path

- features/promotion/complex_promotions.feature
Feature has not been ran, due to bad ``@promotion`` tag.
> [Behat] Run idle feature and adjust it to current logic

- src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php
According to [this line](https://github.com/lchrusciel/Sylius/blob/09b8f6afaf630a09b293320392677080488a5255/src/Sylius/Bundle/CoreBundle/Fixture/CurrencyFixture.php#L95) this will be more appropriate prototype. The definition should looks like this:
```yml
locale:
options:
locales:
de-DE: true
```
> [Fixture] Change prototype for locales

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
It is needed to avoid following situation:
> [Fixture] Add amount to fulfill name assumptions

- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/Model/OrderInterface.php
| Related tickets | fixes #6139, fixes #6140
Not used anywhere now.
> [Order] Remove OrderInterface::isInoviceAvailable

- src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
| Related tickets | fixes #6318
Fix `sylius.cart_item.pre_create` not being fired due to incorrect naming. Now, the event we can listen to is `sylius.order_item.pre_create`. A `sylius.order_item.post_create` is now also available.
> [OrderBundle] Fix Add-to-cart Pre-create event

- src/Sylius/Bundle/ResourceBundle/Controller/RedirectHandler.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/RedirectHandlerSpec.php
| BC breaks?      | yes (made final)
Time for `@checkout` suite dropped from 4 minutes 40 seconds to 3 minutes.
See: https://github.com/symfony/symfony/issues/7368
Blackfire profile: https://blackfire.io/profiles/compare/6e1fb119-00c7-48e7-9c1f-50b27d660474/graph
> [Resource] Make RedirectHandler use *cached* router methods

- src/Sylius/Bundle/ResourceBundle/Controller/FlashHelper.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/ResourceBundle/spec/Controller/FlashHelperSpec.php
- src/Sylius/Bundle/ResourceBundle/test/app/config/config.yml
- src/Sylius/Bundle/UiBundle/Resources/views/_flashes.html.twig
> [Resource] Moved flash translation from helper to template

- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Setup/LocaleContext.php
- src/Sylius/Component/Addressing/Model/Country.php
- src/Sylius/Component/Addressing/Model/CountryInterface.php
- src/Sylius/Component/Addressing/Model/Zone.php
- src/Sylius/Component/Addressing/Model/ZoneInterface.php
- src/Sylius/Component/Addressing/spec/Model/CountrySpec.php
- src/Sylius/Component/Addressing/spec/Model/ZoneSpec.php
- src/Sylius/Component/Attribute/Model/AttributeSubjectInterface.php
- src/Sylius/Component/Channel/Model/ChannelsAwareInterface.php
- src/Sylius/Component/Core/Model/Channel.php
- src/Sylius/Component/Core/Model/Product.php
- src/Sylius/Component/Core/Model/Promotion.php
- src/Sylius/Component/Core/spec/Model/ProductSpec.php
- src/Sylius/Component/Currency/Model/CurrenciesAwareInterface.php
- src/Sylius/Component/Locale/Model/LocalesAwareInterface.php
- src/Sylius/Component/Product/Model/Product.php
- src/Sylius/Component/Taxonomy/Model/TaxonsAwareInterface.php
- src/Sylius/Component/User/Model/User.php
- src/Sylius/Component/User/Model/UserInterface.php
| Related tickets | fixes #6314
> Remove unused set*(Collection) methods on models

- src/Sylius/Bundle/CoreBundle/EventListener/SessionCartSubscriber.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
| Related tickets | partially #6279 
Partially fixes #6279, perhaps the OrderBundle might want to provide a default implementation of this that doesn't call `getChannel()`
> Move SessionCartSubscriber to CoreBundle

- src/Sylius/Bundle/GridBundle/Doctrine/ORM/Driver.php
- src/Sylius/Bundle/ResourceBundle/Controller/NewResourceFactory.php
- src/Sylius/Bundle/ResourceBundle/Controller/ResourcesResolver.php
- src/Sylius/Bundle/ResourceBundle/Controller/SingleResourceProvider.php
- src/Sylius/Bundle/ThemeBundle/Translation/ThemeAwareTranslator.php
Using variadic arguments instead of `call_user_func_array` is faster (it's the reason of [PerformanceExtension](https://github.com/FriendsOfBehat/PerformanceExtension) too).
> Use variadic instead of call_user_func_array

- src/Sylius/Component/Customer/Model/Customer.php
Cleaning up unnecessary code in Customer constructor
> Remove unecessary assignation in Customer constructor

- src/Sylius/Bundle/CoreBundle/Form/Type/Rule/CustomerGroupType.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/CustomerGroupRuleChecker.php
Fix the CustomerGroupType and RuleChecker
> Fix Customer Group Type and RuleChecker

- features/currency/managing_currency/inability_of_disabling_base_currency.feature
- features/locale/managing_locales/inability_of_disabling_base_locale.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCurrenciesContext.php
- src/Sylius/Behat/Page/Admin/Currency/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Currency/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/currency/managing_currencies.yml
- src/Sylius/Bundle/CoreBundle/Form/Type/CurrencyType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/Currency.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/CannotDisableCurrency.php
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/CannotDisableCurrencyValidator.php
> [Admin] Disable toggling of base currency

- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_details.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/_form.html.twig
This pull request fixes a minor inconsistency between Product and Product Variant forms in Admin Bundle, more specifically, the Variant form when used in the context of a simple product and that of a configurable product.
| -       | Product | Variant (before) | Variant (after)
| ------- | ------- | --------------| ---------------
| **Details** | [![Product details](http://i.imgur.com/Hyytdrb.png)](http://i.imgur.com/Hyytdrb.png) | [![Variant details (before)](http://i.imgur.com/uN7dtyc.png)](http://i.imgur.com/uN7dtyc.png) | [![Variant details (after)](http://i.imgur.com/OsF9cyP.png)](http://i.imgur.com/OsF9cyP.png)
| **Taxes** …
> [AdminBundle] Fixed consistency issue with Product and ProductVariant

- features/taxonomy/managing_taxons/taxon_image_unique_code_validation_within_taxon.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePageInterface.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/Taxon.xml
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/ImageUniqueCode.php
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/ImageUniqueCodeValidator.php
- src/Sylius/Bundle/CoreBundle/spec/Validator/Constraints/ImageUniqueCodeSpec.php
- src/Sylius/Bundle/CoreBundle/spec/Validator/Constraints/ImageUniqueCodeValidatorSpec.php
> [Images][Taxon] Validation for unique code during creation/edition

- src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php
| Related tickets | fixes #5762 
I don't remember, why did we do this magic with unsetting logger, but at least it is the fastest working solution.
> [Installer] Fix getCode on null exception

- src/Sylius/Bundle/SettingsBundle/Controller/SettingsController.php
- src/Sylius/Bundle/SettingsBundle/Resources/config/services.xml
- src/Sylius/Bundle/ThemeBundle/Resources/config/services/integrations/settings.xml
> [SettingsBundle] Fix service name

- src/Sylius/Bundle/SettingsBundle/Resolver/ResolverServiceRegistry.php
- src/Sylius/Component/Registry/ServiceRegistry.php
> [SettingsBundle][Registry] Remove final, because classes must be proxied

- features/promotion/receiving_discount/applying_only_promotions_enabled_for_given_channel.feature
- src/Sylius/Behat/Resources/config/suites/ui/promotion/receiving_discount.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
`ActivePromotionsByChannelProvider` was not used in `Core`
> [Promotion] Fix per channel promotions availability

- features/cart/shopping_cart/adding_products_with_quantity_to_cart.feature
- features/inventory/cart_inventory/prevent_buying_more_products_than_available_in_a_stock.feature
- features/inventory/cart_inventory/verify_inventory_quantity_when_updating_carty_summary.feature
- features/inventory/verify_reserved_inventory_is_back_in_stock_on_order_cancelling.feature
- features/inventory/viewing_product_variant_with_specify_quantity_of_items_on_hand.feature
- features/order/managing_orders/seeing_order_item_detailed_data.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
| Related tickets | fixes #5934
- Rename `items` to `units` when talking about inventory (#5934)
- Use `DefaultVariantResolver` instead of `getFirstVariant`
> [Behat] Cleanup ProductContext

- features/order/managing_orders/cancelling_order_with_promotion.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_payment.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
`OrderPaymentProcessor` should be called instead of `OrderProcessor` on payment fail/cancel to avoid whole order recalculation.
Based on #6437.
> [Critical][Order] Fix order cancelling issue

- CONTRIBUTING.md
We currently have PR template in `PULL_REQUEST_TEMPLATE.md` so the one in `CONTRIBUTING.md` is not needed (and is outdated).
> Remove PR template from CONTRIBUTING.md

- features/promotion/applying_promotion_rules/receiving_discount_based_on_chosen_product.feature
- features/promotion/managing_promotions/adding_promotion_with_rule.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Rule/ContainsProductConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
- src/Sylius/Component/Core/Factory/PromotionRuleFactory.php
- src/Sylius/Component/Core/Factory/PromotionRuleFactoryInterface.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/ContainsProductRuleChecker.php
- src/Sylius/Component/Core/spec/Factory/PromotionRuleFactorySpec.php
- src/Sylius/Component/Core/spec/Promotion/Checker/Rule/ContainsProductRuleCheckerSpec.php
I have added few tests and fix current implementation of contains product promotion.
> [Promotion] Contains product promotion fix

- features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_per_customer_usage_limit.feature
- features/promotion/applying_promotion_rules/receiving_discount_based_on_nth_order.feature
- features/promotion/applying_promotion_rules/receiving_discount_based_on_nth_order_for_guest_customer.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Resources/config/suites/ui/promotion/applying_promotion_coupon.yml
- src/Sylius/Behat/Resources/config/suites/ui/promotion/applying_promotion_rules.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
| Related tickets | fixes #5412
The `count(o.id)` was counting the same order multiple times (depending on number of items) because of `leftJoin('o.items', 'item')`.
**UPDATE**
Revealed another bug, related to `nth` order scenarios implementation.
> [Critical][Promotion] Fix per customer usage limit

- features/promotion/receiving_discount/receiving_percentage_discount_promotion_on_order.feature
| Related tickets | mentioned in #6190
To make sure that the promotion is applied correctly even if the discount is bigger than the item total.
> [Promotion] Better coverage of percentage promotion distribution

- features/cart/shopping_cart/change_currency_of_cart.feature
- features/promotion/complex_promotions.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_item.html.twig
| Related tickets | fixes #6267
> [Cart] Fix cart summary display

- src/Sylius/Component/Core/Promotion/Action/FixedDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Action/PercentageDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Action/ShippingPercentageDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Action/UnitFixedDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Action/UnitPercentageDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Applicator/UnitsPromotionAdjustmentsApplicator.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/ContainsProductRuleChecker.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/ContainsTaxonRuleChecker.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/CustomerGroupRuleChecker.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/NthOrderRuleChecker.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/ShippingCountryRuleChecker.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/TaxonRuleChecker.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/TotalOfItemsFromTaxonRuleChecker.php
- src/Sylius/Component/Core/Promotion/Filter/PriceRangeFilter.php
- src/Sylius/Component/Core/Promotion/Filter/TaxonFilter.php
> [RFC] [Promotion] Finalize promotion classes in core

- src/Sylius/Bundle/PromotionBundle/composer.json
Without this fix packages check will fail. I'm surprised that it does not occur on current master.
> [Promotion] Add missing requirement

- app/migrations/Version20161020113011.php
- features/user/managing_customers/seeing_customer_details.feature
- features/user/managing_customers/seeing_province_created_manually_on_customer_details_page.feature
- src/Sylius/Behat/Context/Setup/CustomerContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPage.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/_content.html.twig
- src/Sylius/Bundle/CoreBundle/EventListener/CheckoutAddressingListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Customer.orm.xml
- src/Sylius/Bundle/CoreBundle/spec/EventListener/CheckoutAddressingListenerSpec.php
- src/Sylius/Component/Core/Model/Customer.php
- src/Sylius/Component/Core/Model/CustomerInterface.php
- src/Sylius/Component/Core/spec/Model/CustomerSpec.php
> [Core] Changed shipping/billing address into defaultAddress on customer's model

- docs/api/authorization.rst
Hello there :hand: 
It has been a while :)
This PR allows to copy/paste the API commands. Without the `\`, the next lines are not taken into consideration. It can lead to misunderstandings, as the command does not fail, even if the other arguments are not applied.
> [Documentation][API] Fix API authorization doc

- src/Sylius/Component/Addressing/Comparator/AddressComparator.php
| Bug fix?        | yes (static calls to non-static method)
| Related tickets | related to #6536 
> [Addressing] Simplify AddressComparator

- features/product/viewing_products/searching_products_by_name_within_specific_taxon.feature
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Behat/Page/Shop/Taxon/ShowPage.php
- src/Sylius/Behat/Page/Shop/Taxon/ShowPageInterface.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Grid/Filter/string.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Grid/_default.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_filters.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/show.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php
Maybe it doesn't look great, but at least it works 😄  🐫
> [Product] Product search for customer

- features/account/customer_account/address_book/setting_default_address.feature
- features/account/customer_account/address_book/viewing_addresses.feature
- src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPage.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPageInterface.php
- src/Sylius/Bundle/CoreBundle/Form/Type/AddressChoiceType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Customer/CustomerDefaultAddressType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/account/address_book.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_defaultAddress.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_defaultAddressForm.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_item.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/index.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/flashes.en.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Shop][Account] Marking an address as default

- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceControllerSpec.php
We have state machine transition possible from `updateAction` but not from `createAction`. Can be pretty useful depending on your model.
> [ResourceController] Allow state machine transition from createAction

- docs/book/index.rst
- docs/book/map.rst.inc
- docs/book/product_associations.rst
> [Documentation][Book] Product Associations

- docs/cookbook/checkout.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
> [Documentation][Cookbook] How to customize Sylius Checkout?

- src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php
| BC breaks?      | kinda
| Related tickets | fixes #6599 
I don't even know how this could work before. **Payum** uses ints internally to represent total amounts (see https://github.com/Payum/Payum/issues/597#issuecomment-255673769), and the **Payum\Core\Model\Payment** class explicitly declares `$totalAmount` as an int so
I hope I'm not overlooking something important here, but to me this looks like something that should be fixed.
> [Critical] Payum uses int for amount, not float

- src/Sylius/Bundle/CoreBundle/Controller/OrderController.php
These two private methods are not called from any other method in that class, so i guess they can be removed.
> Deleted unused private methods in OrderController

- docs/bundles/SyliusTaxonomyBundle/categorization.rst
The doc mentionned sylius_taxon_selection type but in the code it is called sylius_taxon_choice
> Fixed form type name in categorization.rst

- src/Sylius/Bundle/TaxonomyBundle/Resources/config/doctrine/model/Taxon.orm.xml
This pull request rename the taxon table from "taxon" to "sylius_taxon"
> [TaxonomyBundle] rename the taxon table on TaxonomyBundle

- PULL_REQUEST_TEMPLATE.md
There were problems with ``|`` signs in few rows.
Previous:
Now:
> [Github] Fix default PR description template

- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-product-slug.js
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_details.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/_slugField.html.twig
* Loader on slug field, not on whole form
* Toggle slug button now shows current state, not target state (more natural, I suppose)
> [Admin][UI] Small fixes in slug generation UI

- docs/book/taxation.rst
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Related tickets | partially #5275, #6664 |
> [Documentation][Book] Taxation - included in price examples

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Attribute/attributesCollection.html.twig
By checking the form type instead of the attribute type it is possible to use the CheckboxAttributeType of Sylius as form type parent and thereby get its looks in the product's attributes view. This is more in line with how using form type parents work in Symfony.
> [AdminBundle] Create checkbox based on form instead of attribute

- features/cart/shopping_cart/adding_product_to_cart_with_prices_dependent_on_channel_and_currency.feature
- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
- src/Sylius/Behat/Resources/config/suites/ui/cart/shopping_cart.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/pricing.xml
- src/Sylius/Component/Core/OrderProcessing/OrderPricesRecalculator.php
- src/Sylius/Component/Core/Pricing/Calculators.php
- src/Sylius/Component/Core/Pricing/ChannelAndCurrencyBasedCalculator.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderPricesRecalculatorSpec.php
- src/Sylius/Component/Core/spec/Pricing/ChannelAndCurrencyBasedCalculatorSpec.php
> [Product][Shop] Buy product in correct prices for channel and currency

- src/Sylius/Bundle/CoreBundle/Command/AbstractInstallCommand.php
- src/Sylius/Bundle/CoreBundle/Command/InstallAssetsCommand.php
- src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php
This fixes a problem when the install command is not called from the Symfony root directory. Since the web paths are relative, the directories will be created wherever I call the installer from.
Additionally, I removed a `no-interaction` check since Symfony's `askConfirmation` method will do this automatically for us in the next step.
> [Core] Ensure writable web/ directories with absolute paths in the installer

- src/Sylius/Bundle/ResourceBundle/Routing/Configuration.php
| Related tickets | ~
Before:
```yaml
rout_name:
resource: |
form: form_type_name
```
After
```yaml
rout_name:
resource: |
form: form_type_name
form:
type: form_type_name
options:
foo: bar
```
> [ResourceBundle] Allow array to form config.

- src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
- src/Sylius/Bundle/AdminBundle/Resources/private/js/move-taxon.js
> [Behat] Fix wait for methods

- src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_user.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/integrations/hwi_oauth.xml
In the integration of HWIOAuthBundle we've been creating an AdminUser instead of ShopUser.
> [CoreBundle] Fix OAuthUser

- src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php
This change makes it possible to use the same database name in every environment. Currently, the `InstallDatabaseCommand` will always prepend `_%env%` to the database name, even if I specified `sylius` (no `_%env%`) in my dev config, which won't match the expectations made here.
It will return `NULL` for SQLite and eventually explode since `listDatabases` is not supported anyway.
> [Core] Use dbname from doctrine connection to allow custom values

- src/Sylius/Bundle/ShopBundle/Controller/CurrencySwitchController.php
Currently the currency switch action falls back to `$request->getBaseUrl()`, but unfortunately that is also blank for me. I switched it to use `$request->getSchemeAndHttpHost()`.
By the way, why are controllers final? I was just going to override this controller and change the one action, but can't.
> [ShopBundle] Fix redirect when referer is blank

- docs/bundles/SyliusOrderBundle/cart_actions.rst
| Related tickets | fixes #6595 |
This page in the documentation is currently out of date, because the mentioned routes don't exist anymore. Furthermore the replacement routes are in another bundle (the ShopBundle) now. This PR alleviates both problems.
> fixes #6595

- src/Sylius/Bundle/CoreBundle/Resources/config/services/taxation.xml
This fixes a 'non-numeric value encountered' warning when running
PHP7.1. PR in Symfony to handle these: https://github.com/symfony/symfony/pull/20539
> [Taxation] Remove useless argument type property

- features/homepage/viewing_latest_products.feature
- features/product/viewing_products/viewing_latest_product.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Shop/HomepageContext.php
- src/Sylius/Behat/Page/Shop/HomePage.php
- src/Sylius/Behat/Page/Shop/HomePageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/ui/homepage/viewing_products.yml
- src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
| Related tickets | fixes #3513 |
The issue #3513 does not exist at the moment. This scenarios would protect us from regression. 
The base problem of an issue is to add select with translation. With the current [function](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php#L74-L86) we do not add any select. If we would add any to-many association, then this query would be broken. Of course, we can consider to have translation fetched from database directly in the query instead of lazy loaded, but before we won't measure its impact on performance it is just a blind shot.
Anyway, if we …
> Latest translatable issue

- src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
- src/Sylius/Component/Order/CartActions.php
| Related tickets | partially #3535 |
> [Order][Cart] Clean up cart events

- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_details.html.twig
| Related tickets | fixes #6786 |
Just adds the name field in the product variant edit form.
> Show name field in product variant form so it wont get lost on updating

- src/Sylius/Behat/Page/Page.php
According to [doc block](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Behat/Page/Page.php#L145-L149), an array can be returned from defined elements as well.
> [Behat] Allow to define array of elements

- features/account/customer_account/viewing_orders_history/seeing_province_created_manually_in_order_history.feature
- features/account/customer_account/viewing_orders_history/viewing_order_recalculated_by_exchange_rate.feature
- features/cart/shopping_cart/adding_product_to_cart_with_prices_dependent_on_channel_and_currency.feature
- features/cart/shopping_cart/viewing_cart_summary_in_many_channels.feature
- features/channel/managing_channels/browsing_channels.feature
- features/checkout/seeing_order_summary/seeing_prices_recalculated_by_exchange_rate_on_order_summary.feature
- features/currency/handling_different_currencies_on_multiple_channels.feature
- features/currency/handling_disabled_currencies.feature
- features/currency/managing_currency/inability_of_modifying_base_currency.feature
- features/currency/switching_current_currency.feature
- features/order/managing_orders/modifying_shipping_address/modifying_shipping_address_on_order_with_different_exchange_rate.feature
- features/order/managing_orders/modifying_shipping_address/modifying_shipping_address_validation.feature
- features/order/managing_orders/seeing_order_currency_on_show.feature
- features/order/managing_orders/seeing_order_prices_with_its_currencys_exchange_rate_on_show.feature
- features/order/managing_orders/seeing_orders_currency_on_index.feature
- features/order/managing_orders/seeing_orders_currency_with_different_exchange_rates_on_index.feature
- features/promotion/managing_promotions/adding_promotion_with_action_in_different_currencies.feature
- features/promotion/receiving_discount/receiving_fixed_discount_dependent_on_currency.feature
- src/Sylius/Behat/Context/Setup/ChannelContext.php
- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/test_services.xml
- src/Sylius/Component/Core/Test/Services/DefaultChannelFactory.php
- src/Sylius/Component/Core/Test/Services/DefaultChannelFactoryInterface.php
- src/Sylius/Component/Core/Test/Services/DefaultUnitedStatesChannelFactory.php
- src/Sylius/Component/Core/spec/Test/Services/DefaultUnitedStatesChannelFactorySpec.php
| Related tickets | #6766 |
According to upcoming changes with currencies, it will be more appropriate to have base currency set in channel creation step (``United States`` channel has obviously ``USD`` base currency).
> [Behat] Fix base currency step semantics

- src/Sylius/Bundle/CoreBundle/Controller/OrderController.php
- src/Sylius/Bundle/CoreBundle/Controller/ProductTaxonController.php
- src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
- src/Sylius/Bundle/ResourceBundle/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceControllerSpec.php
- src/Sylius/Bundle/UserBundle/Controller/UserController.php
| Related tickets | extracted from #6738 |
> Remove deprecated usage of FormInterface::submit(Request $request)

- app/migrations/Version20161121085119.php
- docs/components/Payment/models.rst
- features/checkout/paying_for_order/sorting_payment_method_selection.feature
- features/payment/managing_payment_methods/sorting_payment_methods.feature
- features/payment/managing_payment_methods/sorting_payment_methods_by_position.feature
- src/Sylius/Behat/Context/Setup/PaymentContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentMethodsContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectPaymentPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectPaymentPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment_method.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/PaymentMethod/_form.html.twig
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentMethodRepository.php
- src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentMethodType.php
- src/Sylius/Bundle/PaymentBundle/Resources/config/doctrine/model/PaymentMethod.orm.xml
- src/Sylius/Bundle/PaymentBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/PaymentBundle/spec/Form/Type/PaymentMethodTypeSpec.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectPayment.html.twig
- src/Sylius/Component/Payment/Model/PaymentMethod.php
- src/Sylius/Component/Payment/Model/PaymentMethodInterface.php
- src/Sylius/Component/Payment/spec/Model/PaymentMethodSpec.php
> [Admin][Payment] Sorting payment metods by position

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentMethodRepository.php
In MySQL 5.7.16 the following error can occur: 
This PR will fix it.
> [HOTFIX] [Payment] Ordering payment repositories

- src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/checkout.yml
IMO `complete` is more appropriate name for an event dispatched after the checkout summary step.
> [RFC][BC Break] Rename checkout summary event

- src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Address.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Order.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/OrderItem.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Product.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductTranslation.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
- src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Order.orm.xml
- src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/OrderItem.orm.xml
- src/Sylius/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.xml
- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/Product.orm.xml
- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/ProductTranslation.orm.xml
> Remove loggable

- src/Sylius/Behat/Behaviour/Toggles.php
**Before:**
```
Behat\Testwork\Call\Exception\FatalThrowableError: Fatal error: Wrong parameters for RuntimeException([string $message [, long $code [, Throwable $previous = NULL]]]) in vendor/sylius/sylius/src/Sylius/Behat/Behaviour/Toggles.php:57
```
**After:**
```
RuntimeException: Toggleable element state is 'false' but expected 'true'. in vendor/sylius/sylius/src/Sylius/Behat/Behaviour/Toggles.php:57
```
> [Behat] Fix exception msg for Toggles checkbox assertion

- src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/Show/_breadcrumb.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/Show/_children.html.twig
Do not allow to navigate to a root taxon in the default UI.
> [RFC] Hide root taxon from UI

- app/config/security.yml
- features/cart/shopping_cart/clearing_cart_after_logging_out.feature
- features/cart/shopping_cart/maintaining_previous_cart_after_authorization.feature
- src/Sylius/Behat/Context/Ui/UserContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/CoreBundle/Context/CustomerAndChannelBasedCartContext.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/CoreBundle/EventListener/ShopUserLogoutHandler.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/context.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/handlers.xml
- src/Sylius/Bundle/CoreBundle/spec/Context/CustomerAndChannelBasedCartContextSpec.php
- src/Sylius/Bundle/CoreBundle/spec/EventListener/ShopUserLogoutHandlerSpec.php
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
This PR solves two issues:
- when we had some products in the cart (or even some checkout steps already passed) and logged out, cart was still available for the not logged in user
- after logging out with unfinished order, it was impossible to continue shopping after session expired/on different browser etc.
> [Core] Maintain previous cart after logging in

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Configuration.php
With this change the translation services will be loaded always, unless intentionally disabled.
> [BugFix] Enable translations at default

- src/Sylius/Bundle/CoreBundle/Command/AbstractInstallCommand.php
- src/Sylius/Bundle/CoreBundle/Command/CheckRequirementsCommand.php
- src/Sylius/Bundle/CoreBundle/Command/CommandExecutor.php
- src/Sylius/Bundle/CoreBundle/Command/InstallAssetsCommand.php
- src/Sylius/Bundle/CoreBundle/Command/InstallCommand.php
- src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php
- src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php
- src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php
- src/Sylius/Bundle/CoreBundle/Installer/Checker/CommandDirectoryChecker.php
- src/Sylius/Bundle/CoreBundle/Installer/Checker/RequirementsChecker.php
- src/Sylius/Bundle/CoreBundle/Installer/Checker/RequirementsCheckerInterface.php
- src/Sylius/Bundle/CoreBundle/Installer/Checker/SyliusRequirementsChecker.php
- src/Sylius/Bundle/CoreBundle/Installer/Executor/CommandExecutor.php
- src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
- src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProviderInterface.php
- src/Sylius/Bundle/CoreBundle/Installer/Renderer/TableRenderer.php
- src/Sylius/Bundle/CoreBundle/Installer/Setup/ChannelSetup.php
- src/Sylius/Bundle/CoreBundle/Installer/Setup/ChannelSetupInterface.php
- src/Sylius/Bundle/CoreBundle/Installer/Setup/CurrencySetup.php
- src/Sylius/Bundle/CoreBundle/Installer/Setup/CurrencySetupInterface.php
- src/Sylius/Bundle/CoreBundle/Installer/Setup/LocaleSetup.php
- src/Sylius/Bundle/CoreBundle/Installer/Setup/LocaleSetupInterface.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/installer.xml
- src/Sylius/Bundle/CoreBundle/spec/Installer/Executor/CommandExecutorSpec.php
*Sylius* installer is a powerful tool, but since last few years it became a little bit messy. This PR is the first step to make it usable.
To-do:
I hope we will be able to test this commands properly in the nearest future, as current test doesn't really test anything ;)
> [Core][Installer] Rework installer commands

- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/_widget.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
currently, adding a product to cart will render "1 items". instead of using ifs, why not using transchoice?
it looks like this:
> POC - Use trans choice instead of multiple message keys

- src/Sylius/Bundle/OrderBundle/Controller/OrderController.php
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/cart.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/_widget.html.twig
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/6961, related to https://github.com/Sylius/Sylius/pull/6958 |
The problem is, in ``showAction`` repository uses newly created cart as argument to ``find`` method - but it does not have an id, and that's why it fails.
Again two questions:
- what was the problem with previous implementation?
- how is it possible it does not break the build on Travis? It fails every single shop scenario on my local machine
> [Critical][Shop] Revert changes that "fixed" broken cart widget

- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_form.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_media.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Form/imagesTheme.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
After this change, images are displayed in three columns, as below:
> [Admin][Images] Fix displaying images on product and taxon pages

- src/Sylius/Component/Core/Updater/UnpaidOrdersStateUpdater.php
Just a small fix — using a defined class constant instead of a string
> [UnpaidOrdersStateUpdater] Use class constant

- src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_customers.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_orders.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/index.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/summary.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Order/show.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_main.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/_list.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
The messages macro in `@SyliusUi/Macro/messages.html.twig` will attempt to translate the message it is given when rendering, so there isn't a need to also translate the message in the calling layout.  This results in the message trying to be translated twice and Symfony's profiler will tell you there are missing translations for the second attempt.
> Don't double translate messages

- src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-product-attributes.js
So that it now also works on other attributes than product attribute. Such as when enabling attributes for product variants.
Without this PR, no attributes will be returned by the 
`$attributes = $form->getData();`
in the "renderAttributeValueFormsAction" function of an attribute enabled model.
> [UI][JS] Make attribute choice listener generic

- src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
- src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
- src/Sylius/Behat/Resources/config/services/pages/admin/admin_user.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/channel.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/country.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/currency.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/customer.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/customer_group.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/exchange_rate.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/locale.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/order.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/payment_method.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/product.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/product_association_type.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/product_attribute.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/product_option.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/product_review.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/product_variant.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/promotion.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/promotion_coupon.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/shipping_category.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/shipping_method.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/tax_category.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/tax_rate.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/taxon.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/zone.xml
This allows to use generic CRUD pages while not following Sylius' route notation.
> [Behat] Use full route names

- composer.json
- composer.lock
- phpspec.yml.dist
- src/Sylius/Bundle/FixturesBundle/composer.json
- src/Sylius/Bundle/FixturesBundle/phpspec.yml.dist
- src/Sylius/Bundle/FixturesBundle/spec/Suite/SuiteFactorySpec.php
- src/Sylius/Bundle/FixturesBundle/spec/Suite/SuiteSpec.php
PhpSpec 3.2 has it out of the box - https://github.com/phpspec/phpspec/pull/1016.
> Remove dependency on pamil/phpspec-generator-extension

- src/Sylius/Bundle/InventoryBundle/DependencyInjection/Configuration.php
The `InventoryBundle` specifies that its `resources` section is required to be configured but each of the nodes provides sensible and usable configuration values.  This removes the configuration directive specifying that it must be declared in the configuration.
> Don't mandate configuring the InventoryBundle resources section

- src/Sylius/Bundle/AdminBundle/Resources/views/Common/Macro/money.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Macro/money.html.twig
| Bug fix?        | maybe |
| Related tickets | no |
Before:
```
<span>
€75.00
</span>
```
After:
`<span>€75.00</span>`
> Trim whitespaces from money macro

- src/Sylius/Bundle/PromotionBundle/Resources/config/services/forms.xml
| Related tickets | see https://github.com/Sylius/Sylius/pull/5946#issuecomment-266992768 |
During our upgrade process to `beta.1` the forms were not able to render, as the `action` registry was injected in the `rule` subscriber (and the other way around).
> [Promotion] Inject correct registry in subscriber

- features/checkout/addressing_order/returning_to_addressing_step_and_changing_address_data.feature
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPageInterface.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_header.html.twig
- tests/Controller/CheckoutAddressingApiTest.php
Proceeding checkout as guest and then going back to addressing step caused vanishing of email field. That was because we only checked is there `customer` set on cart and if yes, then corresponding field was not added. After this change, we're also checking if there is also `user` on this cart customer - which means is there user logged in or not. Maybe it's not the best solution but imo it would be sufficient for now.
> [Checkout][Core] Fix disappearing email after going back to addressing step

- src/Sylius/Bundle/PromotionBundle/Form/EventListener/AbstractConfigurationSubscriber.php
| Related tickets | comment https://github.com/Sylius/Sylius/pull/5946#issuecomment-266992768 |
As the `AbstractConfigurationSubscriber` should be abstract, it should not mention rule or action. Renamed these internal variables for readability, as it both can be `Rules` and `Actions` (or anything implementing the interfaces).
> [Promotion] Make subscriber abstract, rename variables

- composer.json
- composer.lock
| Related tickets | related to #7080 |
Right now, if you remove `composer.lock` and `vendor`, `composer update` will fail.
We still have `php-http/guzzle6-adapter` in our `composer.lock`, but there's no information about that in `composer.json`.
> Use php-http/guzzle6-adapter explicitly

- src/Sylius/Component/Core/Model/ShippingMethod.php
If extended and the extended class is configured to be used, there is an doctrine error thrown that the property doesnt exist.
> Channels should be protected

- src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
| Related tickets | fixes #7097  |
When server version is present in configs getSchemaManager will not throw exceptions.
> Move listDatabases call into try block

- src/Sylius/Component/Core/Promotion/Checker/Eligibility/PromotionCouponPerCustomerUsageLimitEligibilityChecker.php
- src/Sylius/Component/Core/spec/Promotion/Checker/Eligibility/PromotionCouponPerCustomerUsageLimitEligibilityCheckerSpec.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/7112 |
I hope this is good enough. The better way to do this would be to actually check if this entity is managed by the entity manager to infer existence, but this seemed simpler.
> [Core] Ensure customer exists before checking for eligibility

- src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_channelSwitch.html.twig
| Bug fix?        | deprecation fix |
> [MINOR] Use "same as" instead of deprecated "sameas" in Twig

- src/Sylius/Bundle/ResourceBundle/Controller/FlashHelper.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/FlashHelperSpec.php
A default [symfony translator](https://github.com/symfony/translation/blob/master/IdentityTranslator.php#L19) implementation doesn't implement *TranslatorBagInterface* but it is require by FlashHelper. This fix will allow to handle all symfony translator classes
> [Resource] Allow to inject IdentityTranslator to flash helper

- src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
It was really annoying in `dev` environment (last menu item covered with debug bar) and also just looks better (more space, more air, more freedom 🐃 ).
Before:
After:
> [Ui] Perfect admin menu display

- src/Sylius/Bundle/ResourceBundle/Controller/ResourcesResolver.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourcesResolverSpec.php
| BC breaks?      | no  |
| Related tickets | partially https://github.com/Sylius/Sylius/issues/4072 |
If routing configuration was
```yml
paginate: false
limit: false
```
listed resources was not sorted, even if ``sorting`` attribute was set correctly.
> [Resource] Add possibility to sort not paginated and not limited resources

- composer.json
- composer.lock
- src/Sylius/Bundle/ApiBundle/composer.json
- src/Sylius/Bundle/ChannelBundle/composer.json
- src/Sylius/Bundle/CurrencyBundle/composer.json
- src/Sylius/Bundle/FixturesBundle/composer.json
- src/Sylius/Bundle/GridBundle/composer.json
- src/Sylius/Bundle/InventoryBundle/composer.json
- src/Sylius/Bundle/LocaleBundle/composer.json
- src/Sylius/Bundle/MailerBundle/composer.json
- src/Sylius/Bundle/MoneyBundle/composer.json
- src/Sylius/Bundle/ResourceBundle/composer.json
- src/Sylius/Bundle/ThemeBundle/composer.json
- src/Sylius/Bundle/UiBundle/composer.json
Symfony's TwigBundle and TwigBridge require `"twig/twig": "~1.28|~2.0"` as of Symfony 3.2.  This PR updates the Twig dependency for the main app and all bundles to match the 1.x branch requirement.
> Bump bundle Twig dependencies to match Symfony's TwigBundle and TwigBridge

- src/Sylius/Bundle/ThemeBundle/Twig/ThemeFilesystemLoader.php
Since Twig 1.27, a `Twig_LoaderInterface` implementation should also implement `Twig_SourceContextLoaderInterface` as the `getSource()` method is deprecated.  This PR implements the new interface and method.
This also introduces forward compatibility with Twig 2.0.  The `getSourceContext()` method is moved to `Twig_LoaderInterface` and `Twig_SourceContextLoaderInterface` deprecated.  So appropriate checks are made in the Exception handling block of the new method before throwing a `Twig_Error_Loader` as defined by the interface in an error state.
> Implement Twig_SourceContextLoaderInterface

- src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
The language specified in the lang attribute has to follow the ISO 639-1 standard (http://www.w3schools.com/tags/ref_language_codes.asp), i.e. let's use the first two characters of our lang attribute which may be up to five characters long (ISO 639-1 + '_' + ISO 3166-1 alpha-2, e.g. sv_SE)
> [Shop] Made lang attribute W3C standard compliant

- app/migrations/Version20170103120334.php
- src/Sylius/Bundle/AttributeBundle/Resources/config/doctrine/model/AttributeValue.orm.xml
- src/Sylius/Component/Attribute/Model/AttributeValue.php
- src/Sylius/Component/Attribute/Model/AttributeValueInterface.php
As **json** storage type is not currently used by any existing attribute, it could be immensely useful for more sophisticated custom attributes.
> [Attribute] Add Json storage type for custom attributes

- features/promotion/managing_promotions/editing_promotion.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/BuildChannelBasedPromotionActionFormSubscriber.php
- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/BuildChannelBasedPromotionRuleFormSubscriber.php
Fix for following issue:
```gherkin
Given this promotion gives "$10.00" discount to every order
When the store also operates on another channel named "EU-WEB"
Then I should be able to modify a "Christmas sale" promotion
```
resulted in:
> [Promotion] Fix promotion edit page

- src/Sylius/Component/Core/OrderCheckoutStates.php
| Bug fix?        | kindof |
| Related tickets | mentioned in #7031 |
OrderCheckoutStates' constants should reflect the state machine — one constant was missing after the mentioned PR, this adds it back in.
> [Free Order] Add missing constant state for checkout

- src/Sylius/Bundle/ResourceBundle/AbstractResourceBundle.php
the object manager name created in AbstractResourceBundle is not consistent with the one created in AbstractResourceExtension, which makes us to add extra code to register model namespace.
> add a way to make object manager name consistent

- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/Product.orm.xml
| Related tickets | Complementary to PR #7147  |
Products options aren't sorted by position when displayed on product page. The PR #7147 fixed their order in the admin, but it seems logical that they should be displayed in the same order in the shop.
It seems to me like adding a "order-by" in the product mapping fixes this and doesn't have any other implications.
> [Shop][Product] Sort product options by position

- src/Sylius/Bundle/ApiBundle/Controller/TokenController.php
- src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
- tests/Controller/CheckoutAddressingApiTest.php
- tests/Controller/CheckoutApiTestCase.php
- tests/Controller/CountryApiTest.php
- tests/Controller/CustomerApiTest.php
- tests/Controller/OrderApiTest.php
One of a milestones for beta2 are finishing and polishing our API. One of it drawback is incoherence in field notation. JMSSerializer returns a snaked_cased fields by default, when our forms expects a camelCased notation. The simplest solution for that is to turn on camel cased normalizer. The problem with this solution is that FOSOauthServer requires snaked_cased parameters, because token generation is not done with forms...
How can we avoid this? Create custom TokenController which has some logic from FOSRest and FOSOAuthServer. 
Please, share your thought about my proposal :)
> [RFC] [API] Snake cased fields

- docs/api/authorization.rst
OAuth2 plugin from commerceguys is abandoned. In addition it hasn't support Guzzle in version 6 (last supported is 5), which is a current one for Sylius. Proposed a fork, which is maintained. 
> [DOCS] Proposed a maintained fork of OAuth2 plugin for API authorization

- features/inventory/verify_reserved_inventory_is_back_in_stock_on_order_cancelling.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Component/Core/Inventory/Operator/OrderInventoryOperator.php
- src/Sylius/Component/Core/spec/Inventory/Operator/OrderInventoryOperatorSpec.php
| Related tickets | fixes #7144 |
> [Core] Fixed OrderInventoryOperator to take into account refunded payments

- features/product/viewing_products/viewing_different_price_for_different_product_variants_selected_with_options.feature
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Behat/Page/Shop/Product/ShowPage.php
- src/Sylius/Bundle/ProductBundle/Form/DataTransformer/ProductVariantToProductOptionsTransformer.php
- src/Sylius/Bundle/ProductBundle/spec/Form/DataTransformer/ProductVariantToProductOptionsTransformerSpec.php
- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-add-to-cart.js
- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-variants-prices.js
| Related tickets | fixes #7209  |
For now only the web UI part is done ; I'm not sure where to act on PHP part, because the exception is thrown very deeply in the Symfony Form handling code.
> Fix #7209: prevent adding unavailable variant

- src/Sylius/Bundle/UserBundle/Command/AbstractRoleCommand.php
- src/Sylius/Bundle/UserBundle/Command/DemoteUserCommand.php
- src/Sylius/Bundle/UserBundle/Command/PromoteUserCommand.php
New PR from #7096.
| BC breaks?      | maybe* |
| Related tickets | fixes #7093 #7094  |
[SyliusUserBundle] Refactored question helper - fixes #7093 
[SyliusUserBundle] Added a new interaction to specify the user type - fixes #7094 
* I don't know if this can be called a "BC break" since the code was already broken since Symfony 3.0, and the patch should work on Symfony 2.5+.
* The protected function `Sylius\Bundle\UserBundle\Command\AbstractRoleCommand::executeRoleCommand` has a new 1st argument: `InputInterface`. This indeed leads to a BC break to possible custom inheritances of `Sylius\Bundle\UserBundle\Command\AbstractRoleCommand`, but the probability to drink a …
> Fix #7093 #7094 #7096

- tests/Controller/ChannelApiTest.php
- tests/DataFixtures/ORM/resources/channels.yml
In every other fixture file we are using a snake case notation.
> [API] Keep resource name coherent

- docs/bundles/SyliusGridBundle/filters.rst
I added info about string filter configuration not mentioned in a docs. I want to write my own filter without choosing matching possibilities but I saw, that this is already implemented but anything in docs about it.
> [DOC] Added string filter option.type configuration

- docs/bundles/SyliusResourceBundle/forms.rst
The error is this one : Invalid type for path "sylius_resource.resources.app.book.classes.form". Expected scalar, but got array.
> [Documentation]  SyliusResourceBundle » Forms current config ends up with an error

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion_coupon.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/shop_user.yml
- src/Sylius/Bundle/ResourceBundle/EventListener/ResourceDeleteSubscriber.php
Now it'll only handle admin's delete action of sylius resources exclusively.
No more random catching of failed updates, or any other crap like that.
> [Resource] Upgraded ResourceDeleteSubscriber

- docs/bundles/SyliusResourceBundle/forms.rst
The service definition of the form wasn't given, it could be a good idea to describe it.
If you don't specify the service the forms construct is not filled and end up with an error.
> [Documentation]  SyliusResourceBundle » Forms precision

- app/config/config_test_cached.yml
Before:
After:
Result cache not even used yet! 🎉
> Doctrine caching in test_cached environment

- src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteSubscriber.php
- src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
- src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml
| Related tickets | mentioned in #7335 |
Plus a slight trim, the addition of `section` check invalidates all its API related logic, because we don't use sections in API's routing.
> [Admin] Relocated ResourceDeleteSubscriber

- src/Sylius/Bundle/ShopBundle/Resources/config/routing/order.yml
There are payment providers that do a POST based redirect back to the store instead of the GET.
> Allow POST on sylius_shop_order_after_pay route

- src/Sylius/Bundle/ResourceBundle/EventListener/ODMMappedSuperClassSubscriber.php
- src/Sylius/Bundle/ResourceBundle/EventListener/ORMMappedSuperClassSubscriber.php
If the metadata already has existing association mappings for the given field, we won't override anything and leave it as is.
**Example:**
In our bundle, we define our own product entity and want to add an `order-by` to the association mapping of an existing field. So we copy the field definition from `Product.orm.xml` to our own configuration and modify it to our needs.
The current code will always override our custom association mappings for a given field. So the fix is to check if the field has custom association mappings and only apply them if none are configured.
Also renamed the `hasRelation` method since it's really checking if it …
> [ResourceBundle] Prevent overriding existing association mappings

- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonChoiceType.php
- src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
> Fix root option on TaxonChoiceType

- UPGRADE.md
- app/config/routing.yml
It automatically redirect from `/admin` to `/admin/`, both when logged in or not.
> Remove unused "sylius_admin_dashboard_redirect" route

- src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePage.php
- src/Sylius/Behat/Page/Shop/Order/ShowPage.php
This should not be final, since you should be able to extend these pages. These are the only behat pages that are final, probably by accident.
> [BugFix] Remove final keyword from some Behat pages

- src/Sylius/Bundle/ApiBundle/Normalizer/LocaleAwareCamelKeysNormalizer.php
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Tests/Normalizer/LocaleAwareCamelKeysNormalizerTest.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
- tests/Controller/LocaleApiTest.php
- tests/Controller/ProductApiTest.php
- tests/DataFixtures/ORM/resources/locales.yml
- tests/DataFixtures/ORM/resources/products.yml
- tests/Responses/Expected/locale/create_response.json
- tests/Responses/Expected/locale/index_response.json
- tests/Responses/Expected/locale/show_response.json
- tests/Responses/Expected/locale/update_response.json
- tests/Responses/Expected/product/create_response.json
- tests/Responses/Expected/product/show_response.json
During development it appears, that the default body listener breaks our translation support. It changed locale codes from `en_US` to `enUS` and therefore, we weren't able to update resource translation via API. I have added a custom listener, which is locale codes aware, so it will just skip these keys. With updated tests for product we should be protected from regression.
> [API] Fix normalization of locale codes

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Component/Currency/Context/CompositeCurrencyContext.php
- src/Sylius/Component/Locale/Context/CompositeLocaleContext.php
| Related tickets | fixes #6474, fixes #5812 |
Ensured the last exception caught in `Composite*Context`s gets linked to the one it throws itself.
So now instead of a single `CurrencyNotFound` we'll see every exception which led up to it, giving us the root of the problem (more or less).
Although not a perfect solution, it's probably one of the simplest which won't convolute the logic.
> Fixed incoherent exception when a channel cannot be resolved (Currency not found)

- src/Sylius/Bundle/ThemeBundle/Twig/ThemeFilesystemLoader.php
Instead of failing immediately in the `ThemeFilesystemLoader` if a template doesn't exist, try to check the decorated loader if it supports checking for existence for the template as well.
The check here is similar to the one used for `getSourceContext` since the method is not implemented on the base loader interface in Twig 1.x and loaders may not implement the deprecated `Twig_ExistsLoaderInterface` if supporting Twig 2.0+ only.
> Let the ThemeFilesystemLoader check if a template exists in the decorated loader

- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
Hi,
sorting fields in grid by position parameter works nice, but not for filters. Added sort_by in filter loop - simple fix.
> [Grid] Fixed sorting filter in grid by position parameter

- etc/travis/suites/application/is_suitable.sh
Excluded files:
- `CHANGELOG.md`
- `CONTRIBUTING.md`
- `LICENSE`
- `PULL_REQUEST_TEMPLATE.md`
- `README.md`
- `UPGRADE.md`
This prevents application from being tested on Travis by PRs like #7436.
> [Travis] Skip application tests if only *.md files were changed

- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
Right now `sylius_admin_shop_user_delete` is located at `/admin/{id}`.
> Use proper path for shop user deletion route

- src/Sylius/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php
Payum provides a mechanism to use a NotifyNullAction for gateways that do not have a per-payment notification URL capability to call the "payum_notify_do_unsafe" route for the URL "/payment/notify/unsafe/{gateway}"
The issue happens because in this scenario, the NotifyNullAction is the last item in the Payum processing stack, as it is the first action that has been called, and due to it's stateless nature, it does not have a PaymentInterface model (getFirstModel returns "null"), meaning the extension can't update the payment status.
This means that Payum's built-in Be2Bill should fail too, but I have my own local gateway provider that has the same workflow. It took me quite a while to figure it out and I have done extensive testing on this.
This is the best idea I came up with how to …
> Payment state update for NotifyNullAction

- src/Sylius/Bundle/AddressingBundle/Resources/config/services.xml
- src/Sylius/Bundle/ChannelBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/context.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
- src/Sylius/Bundle/CurrencyBundle/Resources/config/services.xml
- src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
- src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
- src/Sylius/Bundle/PaymentBundle/Resources/config/services.xml
- src/Sylius/Bundle/ProductBundle/Resources/config/services.xml
- src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
- src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml
- src/Sylius/Bundle/ResourceBundle/Resources/config/services/integrations/grid.xml
- src/Sylius/Bundle/TaxonomyBundle/Resources/config/services.xml
- src/Sylius/Bundle/ThemeBundle/Resources/config/services/integrations/assets.xml
- src/Sylius/Bundle/ThemeBundle/Resources/config/services/integrations/templating.xml
- src/Sylius/Bundle/ThemeBundle/Resources/config/services/integrations/translations.xml
- src/Sylius/Bundle/ThemeBundle/Resources/config/services/integrations/twig.xml
| Related tickets | fixes #7403 |
This ensures that custom, 3rd party decorations without specified priority are made after the Sylius ones.
> Allow easier decoration for 3rd party extensions

- app/migrations/Version20170208103250.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ChannelPricing.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductTaxon.orm.xml
Added unique constraints on product_taxon and product_channel_pricing entities
[Core] added unique constraints on following entities:
product_variant_id/channel_id combination in sylius_channel_pricing
product_id/taxon_id combination in sylius_product_taxon
| Q                        | A
| ---------------  | ---
| Bug fix?              | yes
| New feature?     | no
| BC breaks?        | no
| Related tickets  | fixes https://github.com/Sylius/Sylius-Standard/issues/158
| License              | MIT
> Added unique constraints on product_taxon and product_channel_pricing

- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_payment.yml
The `from` parts of `partially_pay` and `partially_refund` were missing :)
> [CoreBundle] Add sylius_order_payment missing transitions

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_attribute.yml
| Related tickets | #6117 |
This PR aims to fix product attribute creation via api as the configured factory does not allows creating untyped attributes (https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Attribute/Factory/AttributeFactory.php#L48-L53).
> Product attribute creation must be typed

- src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
I noticed that the core bundle doesn't register controller services for important resources such as `product_image` etc. Since most people will need to interact with those resources, through an API for example, it is wise to let them come with a controller by default.
> [Bug][CoreBundle] Add missing controller configuration options.

- src/Sylius/Bundle/ApiBundle/Controller/ShowAvailablePaymentMethodsController.php
- src/Sylius/Bundle/ApiBundle/Controller/ShowAvailableShippingMethodsController.php
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/checkout.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/payment_method.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/CoreBundle/Controller/OrderController.php
- src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentMethodChoiceType.php
- src/Sylius/Bundle/PaymentBundle/Resources/config/serializer/Model.Payment.yml
- src/Sylius/Bundle/PaymentBundle/Resources/config/serializer/Model.PaymentMethod.yml
- tests/Controller/CheckoutAddressingApiTest.php
- tests/Controller/CheckoutApiTestCase.php
- tests/Controller/CheckoutCompleteApiTest.php
- tests/Controller/CheckoutPaymentApiTest.php
- tests/Controller/CheckoutShippingApiTest.php
- tests/DataFixtures/ORM/resources/checkout.yml
- tests/Responses/Expected/checkout/get_available_payment_methods.json
- tests/Responses/Expected/checkout/get_available_payment_methods_failed.json
- tests/Responses/Expected/checkout/get_available_shipping_methods.json
- tests/Responses/Expected/checkout/get_available_shipping_methods_failed.json
- tests/Responses/Expected/checkout/shipping_selected_order_response.json
From now on it will be possible to fetch available shipping and payments method based submitted data(e.g. address for shipment). I have also made a little refactor of CheckoutApiTest. 
TODOs:
It would be easier to review if I wait for #7297 and I will write a documentation in separate PR.
> [API] [Checkout] Get available shipping and payment methods

- src/Sylius/Bundle/CoreBundle/Form/Type/User/AdminUserType.php
Hi,
it's simple commit adding translations to admin user form (firstName and lastName fields, which was hardcoded earlier).
> [Translations] added translations to admin user form

- src/Sylius/Bundle/ApiBundle/Form/Type/AddressType.php
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/checkout.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/form.xml
- tests/Controller/CheckoutAddressingApiTest.php
- tests/Controller/CheckoutApiTestCase.php
- tests/Controller/CheckoutCompleteApiTest.php
- tests/Controller/CheckoutPaymentApiTest.php
- tests/Controller/CheckoutShippingApiTest.php
- tests/DataFixtures/ORM/resources/checkout.yml
- tests/Responses/Expected/checkout/addressed_order_response.json
- tests/Responses/Expected/checkout/addressing_invalid_customer.json
- tests/Responses/Expected/checkout/addressing_validation_failed_billing_address.json
- tests/Responses/Expected/checkout/addressing_validation_failed_shipping_address.json
- tests/Responses/Expected/checkout/completed_order_response.json
- tests/Responses/Expected/checkout/payment_selected_order_response.json
- tests/Responses/Expected/checkout/shipping_invalid_order_state.json
- tests/Responses/Expected/checkout/shipping_selected_order_response.json
| BC breaks?      | yes but only in API |
I have removed an email field from AddressType, because email is required to create a car anyway. There is no need to send it one more time. I have also refactored the whole checkout test suite. Now, to start checkout the cart is built from the scratch, a new item is added, and then the checkout can proceed.
> [API] [Checkout] Remove email from address type

- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceControllerSpec.php
Small dx improvement to have at least some message in returned exception.
Before:
```json
{"code":404,"message":""}
```
After:
```json
{"code":404,"message":"The \"order\" has not been found"}
```
or in UI:
Another thing is the translation of this error, but the same problem lays on the every exception in Sylius.
> [Resource] [DX] Add short message to not found exception

- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
| Related tickets | fixes #7095 |
Prepared basing on this comment: https://github.com/Sylius/Sylius/issues/7095#issuecomment-268904810
Having such a `getContainerLoader` method [this guide](http://docs.sylius.org/en/latest/cookbook/checkout.html#overwrite-the-state-machine-of-checkout) works properly.
> [CoreBundle] Add getContainerLoader method to Kernel

- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-compound-form-errors.js
Turns out the previous selector (namely `element.find('.ui.segment')`) was going way too deep down the rabbit hole, losing the names of the tabs with errors.
The outcome being **every** error was aggregated onto the first tab of the menu.
> [Admin][JS] Fixed way too imprecise selector for errors rendering in the tabular form

- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/_content.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/_info.html.twig
The links to mail a customer are broken due to having a space in them.
> Fix broken mail links

- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductAssociation.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductAssociationType.yml
- tests/Controller/ProductApiTest.php
- tests/Responses/Expected/product/create_with_associations_response.json
Removed current/fallback locales and timestamps from API's product associations responses.
> [Product] Added serialization for ProductAssociation classes

- app/migrations/Version20170217141621.php
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/exchange_rate.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/CurrencyBundle/Resources/config/doctrine/model/ExchangeRate.orm.xml
- src/Sylius/Bundle/CurrencyBundle/Resources/config/serializer/Model.Currency.yml
- src/Sylius/Bundle/CurrencyBundle/Resources/config/serializer/Model.ExchangeRate.yml
- src/Sylius/Bundle/CurrencyBundle/Validator/Constraints/UniqueCurrencyPairValidator.php
- src/Sylius/Component/Currency/Model/ExchangeRate.php
- src/Sylius/Component/Currency/spec/Model/ExchangeRateSpec.php
- tests/Controller/ExchangeRateApiTest.php
- tests/DataFixtures/ORM/resources/exchange_rates.yml
- tests/Responses/Expected/currency/create_response.json
- tests/Responses/Expected/currency/show_response.json
- tests/Responses/Expected/exchange_rate/create_response.json
- tests/Responses/Expected/exchange_rate/create_validation_fail_response.json
- tests/Responses/Expected/exchange_rate/index_response.json
- tests/Responses/Expected/exchange_rate/non_unique_pair_validation_fail_response.json
- tests/Responses/Expected/exchange_rate/show_response.json
- tests/Responses/Expected/exchange_rate/update_ratio_with_string_validation_fail_response.json
- tests/Responses/Expected/exchange_rate/update_response.json
- tests/Responses/Expected/exchange_rate/update_validation_fail_response.json
| Related tickets | [comment](https://github.com/Sylius/Sylius/pull/7541#discussion_r101720622) |
This PR adds the TimestampableTrait to exchange rates and test it via API. 
Based on #7541
> [API] [Currency] ExchangeRate CRUD and add TimestampableTrait

- docs/customization/factory.rst
- docs/customization/validation.rst
I suppose that `\` should be used for namespaces, but `/` for directories/paths.
> [Docs] Unify some paths in documentation

- src/Sylius/Bundle/AdminBundle/EventListener/ShipmentShipListener.php
- src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml
- src/Sylius/Bundle/AdminBundle/spec/EventListener/ShipmentShipListenerSpec.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/ShopBundle/EventListener/OrderCompleteListener.php
- src/Sylius/Bundle/ShopBundle/EventListener/OrderCustomerIpListener.php
- src/Sylius/Bundle/ShopBundle/EventListener/OrderLocaleAssigner.php
- src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php
- src/Sylius/Bundle/ShopBundle/EventListener/OrderTotalIntegrityChecker.php
- src/Sylius/Bundle/ShopBundle/EventListener/UserRegistrationListener.php
- src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/ShopBundle/spec/EventListener/OrderCompleteListenerSpec.php
- src/Sylius/Bundle/ShopBundle/spec/EventListener/OrderCustomerIpListenerSpec.php
- src/Sylius/Bundle/ShopBundle/spec/EventListener/OrderLocaleAssignerSpec.php
- src/Sylius/Bundle/ShopBundle/spec/EventListener/OrderPromotionIntegrityCheckerSpec.php
- src/Sylius/Bundle/ShopBundle/spec/EventListener/OrderTotalIntegrityCheckerSpec.php
I have noticed that some of the listeners listen to the custom events from Admin or Shop. Probably it will be cleaner to place them in the appropriate bundle. It is just a proposal, so I'm open for votes should we move them or not. If yes, I will update an UPGRADE file as well.
> [RFC] [Core] [Shop] [Admin] Move listeners to the proper bundle

- src/Sylius/Bundle/CoreBundle/Installer/Checker/CommandDirectoryChecker.php
It used to crash with:
```
$ bin/console sylius:install:assets
Installing Sylius assets for environment dev.
Cannot run command due to bad directory permissions (tried to change permissions to 0755).
Set "/Users/pamil/Projects/Sylius/Sylius-Standard/web/bundles" writable recursively and run command "sylius:install:assets"
```
While `web/bundles/` had `0755` permissions (but there was a symlink inside).
> Improve permissions checking while installing assets

- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml
- src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
| Related tickets | fixes #7231 and #7314 |
Quick fix for a problem with adding a product to a new channel without a shipping method.
> [Core][Shipping] Add missing default shipping method resolver service definition

- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
I'm injecting a different implementation as the default resolver in my project. I think it should rely on an interface instead of a concrete class.
> Manage variant context relies on implementation instead of interface

- src/Sylius/Bundle/GridBundle/Doctrine/DBAL/ExpressionBuilder.php
- src/Sylius/Bundle/GridBundle/Doctrine/ORM/ExpressionBuilder.php
- src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExpressionBuilder.php
Each of the `Sylius\Component\Grid\Data\ExpressionBuilderInterface` implementations right now have a stub `comparison()` method that throws a `BadMethodCallException` because the methods aren't actually implemented.  This PR adds them.
The DBAL adapter just proxies directly to the expression builder's method.  Since the other two don't expose a similar method, the internals from those expression builders are copied and a `Comparison` object is instantiated and returned directly.
> Implement comparison method on all ExpressionBuilderInterface classes

- docs/cookbook/facebook-login.rst
Without this change, I keep receiving the `RouteNotFound` error.
**Update:**
- Some docs about requiring a path without any controller: https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/3-configuring_the_security_layer.md#b-configure-the-oauth-firewall
- And comment on issue with some explanation: https://github.com/hwi/HWIOAuthBundle/issues/781#issuecomment-100463435
> [Documentation] Missing path for facebook login

- docs/api/product_variants.rst
- docs/api/tax_rates.rst
- docs/api/taxons.rst
- docs/api/zones.rst
It appears that we have missed a few mistakes in our docs
> [Documenation] Change `the the` to `the`

- docs/bundles/SyliusResourceBundle/update_resource.rst
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceControllerSpec.php
- tests/Controller/OrderApiTest.php
- tests/Responses/Expected/order/order_payed_show_response.json
The second approach to the #7483 problem. With this solution, it will be easy to customize returning content after an update or state machine transition. What do you think? /cc @steffenbrem @bendavies It is based on your suggestions :) You can check the second commit to see the changes. The first one is needed for the test purposes. 
Based on #7484.
> [POC] [Resource] [API] Conditional update response	

- package.json
- src/Sylius/Bundle/AdminBundle/Gulpfile.js
- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- src/Sylius/Bundle/ShopBundle/Gulpfile.js
- src/Sylius/Bundle/ShopBundle/Resources/private/js/app.js
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
It's one of the most important UX feature. From now, leaving the page with form that was not submitted will require a confirmation (for now it's just a browser default alert box).
Protected forms:
- all forms on Admin panel (except filters - I think it's unnecessary for them)
- **personal info** form on my account page in Shop
- **address** forms on my account page in Shop
> [Admin][Shop] Prevent from leaving page with unsaved form data

- src/Sylius/Bundle/CoreBundle/Installer/Requirement/FilesystemRequirements.php
Our Installer should not be writing to `parameters.yml`, therefore the `is_writable` check is redundant.
> [CoreBundle] Installer Requirements - fix

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion_coupon.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/taxon.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/cart_item.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/ResourceBundle/ExpressionLanguage/ExpressionLanguage.php
- src/Sylius/Bundle/ResourceBundle/ExpressionLanguage/NotNullExpressionFunctionProvider.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/ajax/cart.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/cart.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/product_review.yml
- src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php
With current implementation, if expression (for example in grid) returns `null` value it's passed further and results in some nasty errors.
Example for unexisting taxon slug on shop:
With this simple change, we can display pretty 404 page if anything gone bad.
> [Resource] Throw 404 if expression is invalid

- package.json
- src/Sylius/Bundle/AdminBundle/Gulpfile.js
- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- src/Sylius/Bundle/ShopBundle/Gulpfile.js
- src/Sylius/Bundle/ShopBundle/Resources/private/js/app.js
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
| Related tickets | introduced in https://github.com/Sylius/Sylius/pull/7607 |
It's a really nice UX feature, but for now it makes more harm than good. It results in frequent fails of js scenarios on Travis and as soon as we have no good idea to fix it, it must be removed to not cause more frustration.
> [Shop][Admin] Revert problematic JS feature

- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_support.html.twig
Let's use span instead, identical looks thanks to ".sub.header".
> [Shop][Ui] Div tags are not allowed as a child to h2

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/promotion.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/links.html.twig
I have added a condition to `Manage coupons` action on promotion index. Otherwise, clicking the `Create` button results with `HTTP 500` error if promotion was not coupon based. 
Before:
After:
> [Admin] [UI] Conditional link action

- src/Sylius/Bundle/CoreBundle/Form/Type/AddressChoiceType.php
Replaced `findBy(['customer' => $options['customer']])` in favor of `findByCustomer($options['customer'])` in AddressChoiceType to allow overrides
| Related tickets | fixes #7672 |
> Removed hardcoded 'customer' relation

- src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
Sorry, I forgot to include the actual configuration change in PR https://github.com/Sylius/Sylius/pull/7659
> [Fixtures] adding default_tax_zone in the ChannelFixture configuration

- src/Sylius/Component/Resource/Translation/TranslatableEntityLocaleAssigner.php
This is not needed?
`use Sylius\Component\Resource\Translation\TranslatableEntityLocaleAssignerInterface;`
> Remove unncesessary `use`

- src/Sylius/Bundle/AddressingBundle/Form/Type/CountryChoiceType.php
| Related tickets | fixes #7232 |
As mentioned in #7232, country list was mantaining the order from the DB. When changing between languages it results in bad UX.
I decided to use `usort` but maybe this has to be done at repository level (not sure about this).
> Ordered CountryChoiceType

- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Index/_actions.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_search.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
- src/Sylius/Component/Grid/Definition/Grid.php
- src/Sylius/Component/Grid/spec/Definition/GridSpec.php
This PR fixes a problem with customizing grids, because now, for example when we disable all filters, that there will remain empty filter block above table.
Before:
After:
> [Grid] Add methods for getting only enabled fields, actions and filters

- .travis.yml
Travis' builds are all broken now after upgrade to PHP 7.1.2.
> Run Travis with PHP 7.1.0

- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/MongoDB/TranslatableRepository.php
Translatable fields were removed from resource bundle config, `setTranslatableFields` and `setLocaleProvider` aren't called from anywhere.
> Translatable fields are no longer used

- docs/bundles/SyliusFixturesBundle/builtin_listeners.rst
Looking at the code and testing it, the settings for a purger need to be under the 'options' node, not directly at the purger level. At least this is how I got it working in beta.1 for 'orm_purger'.
> [Docs] Put options of 'orm_purger' in child node

- docs/customization/model.rst
I think the extra operations that need to be done when someone needs to extend a model with a translatable property should be documented.
Code and configuration provided has been obtained through the #support channel in sylius-devs slack community and tested in my own code.
> [Documentation] How to extend a model with a translatable property

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_taxonomy.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
There's a hardcoded string in the admin product taxonomy layout.  Make it translatable.
> Translate hardcoded English string in product taxonomy layout

- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
| Related tickets | fixes #7390 |
> Fix taxon repository

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment_method.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentMethodRepository.php
| Related tickets | fixes #7765  |
See the link for the error. in the fix i join with the gateway config table and then set the correct property to do the order.
> Fix issue-7765. Allow ordering payment methods by gateway config name

- UPGRADE.md
While upgrading to latest dev-master, I didn't adjust the path to the AdminApiBundle path (only adjusted the routing path) as it was not mentioned. Added it to the upgrade docs.
> Add in UPGRADE.md about config file change (AdminBundle)

- docs/cookbook/platform-sh.rst
According to the Platform.sh docs (https://docs.platform.sh/configuration/routes.html):
`
note For the moment, the value of upstream is always in the form: <application-name>:http. <application-name> is the name defined in .platform.app.yaml file. :php is a deprecated application endpoint; use :http instead. In the future, Platform.sh will support multiple endpoints per application.
`
> [Docs] Adjust :php to :http endpoint for Platform.sh configuration

- src/Sylius/Component/User/Model/User.php
The `\DateTime::add()` changes the object itself, not just returns a changed copy.
> Don't change passwordRequestedAt on expiration check

- features/product/managing_products/editing_product.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/BrowsingProductVariantsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites/ui/inventory/checkout_inventory.yml
- src/Sylius/Behat/Resources/config/suites/ui/inventory/managing_inventory.yml
- src/Sylius/Behat/Resources/config/suites/ui/product/managing_product_variants.yml
- src/Sylius/Behat/Resources/config/suites/ui/product/managing_products.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_details.html.twig
| Related tickets | fixes #7735 |
TODO:
> Do not make product variant's fields empty while editing simple product

- src/Sylius/Bundle/CoreBundle/Application/Plugin.php
- src/Sylius/Bundle/CoreBundle/Application/SyliusPluginTrait.php
As you probably know, one of the key concepts for Sylius is to introduce an easy way of creating external plugins which will extend the core logic and don't mess with the core itself. It can be useful to somehow differentiate them from regular Symfony bundles. And this is the main topic of this PR. This abstract class will slightly change the default behaviour of SymfonyBundle and will require creating AppPlugin instead of AppBundle. Also, it will change the way, how the config files should be included. 
Let's assume that we have created `SylusSomeBundle` as a plugin with routing, grids and templates inside and want to …
> [RFC] [Core] Introduce Plugin concept

- src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/product_option.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductOption.yml
- tests/Controller/ProductOptionApiTest.php
- tests/Responses/Expected/product/create_with_options_response.json
- tests/Responses/Expected/product_option/create_response.json
- tests/Responses/Expected/product_option/create_validation_fail_response.json
- tests/Responses/Expected/product_option/index_response.json
- tests/Responses/Expected/product_option/index_response_after_delete.json
- tests/Responses/Expected/product_option/show_response.json
- tests/Responses/Expected/product_option/show_response_after_partial_update.json
- tests/Responses/Expected/product_option/show_response_after_update.json
| Related tickets | first introduced in #7547 |
This PR replaces #7547. It exposes the `translations` property for product options to the API. It also re-introduces creating, updating and deleting product options via the API, which was removed in #7482.
> Allow writing product options via API

- src/Sylius/Bundle/AdminBundle/Resources/views/Form/theme.html.twig
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Filter/ProductFilterConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Rule/ContainsProductConfigurationType.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductAutocompleteChoiceType.php
This change will just increase a DX for developers which would like to take an advantage of product autocomplete feature. Right now, it is not possible without creating a new block definition. With this change, it would be enough to just use `ProductAutocompleteChoiceType`
> [DX] Create product autocomplete form type

- docs/cookbook/custom-promotion-action.rst
- docs/cookbook/custom-promotion-rule.rst
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/RegisterPromotionActionsPass.php
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/RegisterRuleCheckersPass.php
| doc fix?        | yes |
Not sure if this is the right way to amend the docs but when updating to latest master, a missing `form-type` attribute error popped up, apparently not mentioned in the docs for custom rule checkers and actions.
I added a more meaningful Exception message too in the RuleCheckersPass to detect the misbehaving service declaration.
Hope it helps.
> [Documentation] Add missing 'form-type' attribute

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/_slugField.html.twig
When you want to add a translation to a Product in admin, the slug field is locked when you have a slug for the default locale. I think that the slug field should not be locked by default if there is no value.
> Fix product slug field in Admin

- src/Sylius/Bundle/GridBundle/Form/Type/Filter/StringFilterType.php
The label for the string filter field's text input isn't translatable.  Let's change that.
> Make the label for the string filter input translatable

- src/Sylius/Bundle/GridBundle/Renderer/TwigGridRenderer.php
| Bug fix?        | somewhat |
There's a slight bug with submitting filter form, when more than one filter is present.
Doesn't matter whether or not we provide all information the form wants from us, **always** a validation error will occur.
The cause is every filter has a parent with the same name (`criteria`), so at submit, all data gets concocted as if it was coming from a single form.
> [Grid] Fix validation errors with multiple filters

- src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
| Related tickets | fixes #7859 |
The [Cart API allows filtering](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminApiBundle/Resources/config/grids/cart.yml#L39-L51) by customer/channel, but they're missing from the query builder.
> [OrderBundle] Add missing selects/joins to cart query builder

- app/migrations/Version20170327135945.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Taxon.orm.xml
So the Taxon API docs say [here](https://github.com/Sylius/Sylius/blob/master/docs/api/taxons.rst#definition-2) that `(optional) Field and direction of sorting, by default ‘desc’ and ‘createdAt’`. Which led me to the database where I couldn't find any dates for the `sylius_taxon` table.
Checking the [beta1 migration file](https://github.com/Sylius/Sylius/blob/master/app/migrations/Version20161202011555.php#L80) shows that those fields really didn't make it, but `Sylius\Component\Core\Model\Taxon` uses the `TimestampableTrait`.
First of all, is this a correct fix?
Additional questions:
* How about BC?
* Do I have to do …
> [Core][Taxon] Add missing createdAt/updatedAt mappings to Taxon.orm.xml

- src/Sylius/Bundle/UserBundle/EventListener/UserLastLoginSubscriber.php
If you have two way of login in one app (sylius and an other user provider / form), the event onSecurityInteractiveLogin or onImplicitLogin is fired but your entity User is not a Sylius entity user with the user interface UserInterface from sylius. So you have a php error because your 2nd user entity doesn't have the UserInterface implemented.
The strong typing is useless, because on first line we check the user class.
> Remove strong typing on updateUserLastLogin event

- docs/api/checkouts.rst
- docs/api/orders.rst
refs #7886
| Related tickets | fixes #7886 |
> [Documentation] API onHand/onHold spelling fix

- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductVariant.yml
Some weird chars got introduced at the end of the line (probably MacOS or Windows style line ending) in this commit https://github.com/Sylius/Sylius/commit/01ffece60a87ab88aeb25e6d614e8ba6be152a9f#diff-8eb0e5bc2c23fef1cdc63d93a85f949a
> Removed weird chars in Model.ProductVariant.yml

- src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/cart.yml
- src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/cart_item.yml
- tests/Responses/Expected/cart/add_to_cart_hard_available_item_response.json
- tests/Responses/Expected/cart/add_to_cart_response.json
- tests/Responses/Expected/cart/add_to_cart_with_bigger_quantity_response.json
- tests/Responses/Expected/cart/increase_quantity_response.json
- tests/Responses/Expected/cart/recalculated_items_total_response.json
- tests/Responses/Expected/cart/show_response.json
Currently the cart list serialize more information than the
show/update/create routes. To fix this we add the default group for the specific routes.
> [Cart] Add default serialization group for cart

- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.Image.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.ProductImage.yml
- tests/DataFixtures/ORM/resources/products.yml
- tests/Responses/Expected/product/index_response.json
- tests/Responses/Expected/product/show_response.json
- tests/Responses/Expected/product/sorted_index_response.json
| Related tickets | fixes #7898 |
The path will be included in default serialization. I have also added a new fixture to avoid regression. The question for later is, should also send an information about related variants.
> [API] [Product] Add path to default serialization

- docs/cookbook/disabling-order-confirmation-email.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
| Related tickets | fixes #7763 |
> [Documentation][Cookbook] Disabling order confirmation email

- src/Sylius/Bundle/CoreBundle/Fixture/ProductAttributeFixture.php
Adds the 'configuration' node to the 'product_attribute' fixture. It was now missing, as it's only done inside fixtures like 'mug_product'. Simply allows an array with configuration options, as there are many possibilities based on each type.
> Add 'configuration' node in 'product_attribute' fixture

- src/Sylius/Bundle/PayumBundle/Form/Type/PaypalGatewayConfigurationType.php
With password type, the form doesn't show any values when editing.
Edit: Just took a look at the failing test - it doesn't seem related.
> Change paypal password to TextType from PasswordType

- docs/cookbook/platform-sh.rst
Sylius admin tries to load a .woff2 file (icons.woff2) but the platform.sh config does not allow it which results in a 404.
> Allow .woff2 files in platform.sh config

- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithButtons.html.twig
| Related tickets | fixes #7949 |
This fix remove double translation for label. Firstly message was translated in `_treeWithButtons.html.twig` and secondly in `Sylius/Bundle/UiBundle/Resources/views/Macro/buttons.html.twig`. I've removed first translation.
> Fixed double translation for add button in tree view

- src/Sylius/Bundle/UiBundle/Resources/views/_flashes.html.twig
Right now including the `@SyliusUi/_flashes.html.twig` layout will always force a session to start by reading into the flashbag.  Even if other parts of the request cause a session to get started, this layout shouldn't arbitrarily force it, so check for an active session before reading the data.
> Don't allow the flashes layout to force a session start

- src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/product_association_type.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductAssociationType.yml
- tests/Controller/ProductAssociationTypeApiTest.php
- tests/DataFixtures/ORM/resources/product_association_types.yml
- tests/Responses/Expected/product/create_with_associations_response.json
- tests/Responses/Expected/product_association_type/create_response.json
- tests/Responses/Expected/product_association_type/create_validation_fail_response.json
- tests/Responses/Expected/product_association_type/index_response.json
- tests/Responses/Expected/product_association_type/show_response.json
- tests/Responses/Expected/product_association_type/update_response.json
- tests/Responses/Expected/product_association_type/update_validation_fail_response.json
| Bug fix?        | kind of |
API endpoints for product association types were missing.
> Add API for managing product association types

- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.Promotion.yml
Fixed typo in Model.Promotion.yml for the 'xml_root_name' parameter
| Related tickets | fixes #8012 |
> [Core] fixed typo in Model.Promotion.yml

- src/Sylius/Bundle/AddressingBundle/Resources/translations/messages.en.yml
Usually street field is called 'Street address'. Because it's not just the name of the street.
> Update label for street field in address form

- src/Sylius/Bundle/ShopBundle/Resources/config/routing/shop_user.yml
Usually, after successful registration, users will immediately check the post and follow the link in the email and thinking that have already entered, but it is not. This changes will redirect user to login page or to account dashboard.
> Update redirect after email verification

- src/Sylius/Bundle/UserBundle/Controller/UserController.php
Current event dispatching positioning does not allow to keep user disabled after the registration. `$user->disable()` would be overwritten with `$user->enable()` in this case.
> Do not overwrite user changes after PRE_EMAIL_VERIFICATION

- src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
Makes it easier for plugin development to add things to head / end of body etc.
> Add layout events for head & body

- docs/book/architecture/contact.rst
- docs/book/architecture/emails.rst
Wrong paths are mentioned in the docs about the location of the email templates. The upgrade file mentioned them, but docs were not adjusted accordingly.
> [Docs] Adjust paths in Docs/Book/Architecture/Emails & Contact

- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-variants-prices.js
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_variants.html.twig
The `handleProductVariantsChange` JavaScript function is a little not optimal in that it searches for the price based a cell in a specific position in the table.  Instead of doing this, let's add a class to that cell and target that in the function instead.  With this, you wouldn't need to override this function if you change the layout file going forward.
> Add a class to the variant price cell for better JS targeting

- src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
| Related tickets | mentioned in https://github.com/Sylius/Sylius/pull/7999#issuecomment-300183360 |
As @psren pointed out in the comment linked above, it might be better to move the 'before_head' listener a bit lower based on this information: https://www.w3.org/International/questions/qa-html-encoding-declarations.
Also it seems that the X-UA-Compatible meta tag should be high too: https://msdn.microsoft.com/en-us/library/jj676915%28v=vs.85%29.aspx.
> Move the before head hook lower due to conflict with W3 specs

- src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php
- src/Sylius/Bundle/PayumBundle/Provider/PaymentDescriptionProvider.php
- src/Sylius/Bundle/PayumBundle/Provider/PaymentDescriptionProviderInterface.php
- src/Sylius/Bundle/PayumBundle/Resources/config/services.xml
- src/Sylius/Bundle/PayumBundle/Resources/config/services/action.xml
- src/Sylius/Bundle/PayumBundle/Resources/config/services/provider.xml
- src/Sylius/Bundle/PayumBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/PayumBundle/spec/Action/CapturePaymentActionSpec.php
- src/Sylius/Bundle/PayumBundle/spec/Provider/PaymentDescriptionProviderSpec.php
| Related tickets | fixes #7971 |
Made a quick concept for #7971. Added some of the order/payment object variables, but list can be way longer. Can also be automated to get all properties from an entity maybe.
Looking forward for feedback on it.
> Payment description configurable with translation and placeholders (Sylius/Sylius#7971)

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Attribute/attributeValues.html.twig
Hi all,
I noticed that when adding an attribute with child fields (e.g. `datetime` or `date`) to a product, the generated markup from `ProductAttributeController::renderAttributeValueFormsAction` is incorrect, which leads to the attribute & data not being saved against the product.
The generated markup is this:
```html
<div class="ui label">Attribute Name</div>
<select id="attribute_name" name="_[attributes][0][value][date][year]" data-name="_[attributes][0][value][date][year]">
<option value="2012">2012</option>
<option value="2013">2013</option>
<option value="2014">2014</option>
<option value="2015">2015</option>
<option …
```
> Added missing macro call parameters

- src/Sylius/Bundle/ThemeBundle/Resources/config/services/integrations/assets.xml
| Related tickets | https://github.com/symfony/symfony/pull/22529 |
This fixes an issue with Symfony 3.3 (currently in Beta): service arguments are now required to have an ID. Since the argument is replaced by a compiler pass, we can omit the type.
> Remove invalid placeholder arguments

- UPGRADE.md
| Related tickets | mentioned in #7979 |
@lchrusciel There was no section yet for 1.0.0, so I've added it in the same style as beta1 -> beta2. Hopefully this is what you meant.
> Add section for 1.0.0 upgrade & document change in PayumBundle (UPGRADE.MD)

- app/config/config.yml
This removes `trusted_proxies` config from `app/config/config.yml` since it results in the following exception on Symfony 3.3:
```
[InvalidArgumentException]
The "framework.trusted_proxies" configuration key has been removed in Symfony
3.3. Use the Request::setTrustedProxies() method in your front controller instead.
```
> [Symfony 3.3] Remove trusted_proxies config

- docs/bundles/SyliusGridBundle/your_first_grid.rst
Fixes grid docs mistake - `tournament` has been added probably by copy/paste from elsewhere.
> [docs][Grid] Use supplier instead of tournament

- docs/customization/model.rst
| Related tickets | fixes #7914 |
It seems the docs describe usage of a static method to point to the proper translation class. In #7914 @lasotaartur showed that that doesn't work and that it works by overriding the `createTranslation` method in the entity class. Instead of rewriting the code to make it work with the static method call, I've adjusted the docs. I have the impression static method calls are not used that often in Sylius anyway, so it feels a bit out of style :)
> [Docs] Adjust instructions for customizing model with translations (fixes #7914)

- docs/cookbook/images-on-entity.rst
The correct reference is `images` not `image` - there is no single image upload available.
> [Docs] Typo in image upload listener configuration YAML in cookbook

- src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/Form/Builder/DefaultFormBuilder.php
- src/Sylius/Bundle/ResourceBundle/spec/Doctrine/ORM/Form/Builder/DefaultFormBuilderSpec.php
`property` is no longer available in Symfony > 3.0, it has been replaced by `choice_label`:
http://symfony.com/doc/2.8/reference/forms/types/entity.html#choice-label
> Deprecated 'property' form option

- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductOption.yml
- tests/Responses/Expected/product/create_with_options_response.json
- tests/Responses/Expected/product_option/create_response.json
- tests/Responses/Expected/product_option/index_response.json
- tests/Responses/Expected/product_option/index_response_after_delete.json
- tests/Responses/Expected/product_option/show_response.json
- tests/Responses/Expected/product_option/show_response_after_partial_update.json
- tests/Responses/Expected/product_option/show_response_after_update.json
Fixes the link generated in the `self` reference when serializing a product option. This incorrectly generated a URL to the product show page.
> Fix self reference in product options API

- app/migrations/Version20170518123056.php
- src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/AddressLogEntry.orm.xml
This uses snake_cased column names for the AddressLogEntry entity, which was missing `column` declaration in mappings. This can cause issues when people change the default naming strategy for ORM and is the only entity that didn't have `column` properties in field mappings.
> Fix address log entry column names

- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_promotion.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
The shipping and promotion table rows in the order tables conditionally show some data, but the display of the table cells isn't really optimized for this.  This improves the handling a bit to not display an empty table cell and to improve the calculation for the colspans for the always displayed cells.
> Improve table display for order checkout process

- src/Sylius/Bundle/InventoryBundle/Validator/Constraints/InStock.php
- src/Sylius/Bundle/InventoryBundle/Validator/Constraints/InStockValidator.php
I used "sylius.cart_item.not_available" id as it was already existing. Let me know what do you think about it.
> [Inventory] Added translation id to instock constraint message

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Grid/Field/mainTaxon.html.twig
| Related tickets | partially #7815 |
The main taxon field on Product objects is really kind of hidden away as described in #7815.  One way to at least help with addressing this is to show the field on the admin grid, so this PR adds that column.
Note for now that I haven't made the column sortable nor is it filterable.
Screenshot for reference:
> Show main taxon in admin product grid

- docs/cookbook/images-on-entity.rst
The use statement path of class ShippingMethodImageType is wrong.
`use AppBundle\Form\Type\ShippingMethod\ShippingMethodImageType`
must become
`use AppBundle\Form\Type\ShippingMethodImageType`
> [documentation] Fix ShippingMethodImageType use path

- docs/cookbook/images-on-entity.rst
The interface is called ImagesAwareInterface not ImageAwareInterface
> [Documentation] fix ImagesAwareInterface typo

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_mainImage.html.twig
ALT tag was empty, but we can easily insert the product name.
> Add alt attribute to main product image

- docs/cookbook/custom-model.rst
There is no SyliusGridBundle built-in field type called "text". Replaced with "string".
> [documentation] Fix supplier field type

- src/Sylius/Component/Product/Generator/ProductVariantGenerator.php
- src/Sylius/Component/Product/spec/Generator/ProductVariantGeneratorSpec.php
Use case: I wanted to use it in an unit test, but it's based around the entities ID's and as I didn't want to persist them, there is no way (as I see it) to assign an ID to easily. That makes it harder to use it in stand-alone situations. 
The `code` field of the entities is also a required field, which should be there if there is also an ID, but using `code` allows to use setters to use this generator stand-alone for such use-cases.
> Use codes of option value & option instead of ID in variant generator

- features/product/managing_product_options/adding_product_option.feature
- features/product/managing_product_options/product_option_validation.feature
- src/Sylius/Bundle/ProductBundle/Resources/config/validation/ProductOption.xml
- tests/Responses/Expected/product_option/create_validation_fail_response.json
| Related tickets | / |
Currently, a product option must have at least two values for it to be valid. While it may not make a lot of sense to have product options with only one value, there is also no reason for those options not to exist.
In our case, a product may be available in one or more colors. Since colors in a clothing store range from your usual colors (red, blue, green) to weird combinations (striped red and blue) we create a new option for each product using the API. However, if a product were only available in a single color, that color would have to be added as an attribute, which makes looking for all products that are available …
> Remove count constraint on option values collection

- src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/checkout.yml
- tests/Controller/CheckoutCompleteApiTest.php
- tests/Responses/Expected/checkout/complete_validation_failed_disabled_product.json
- tests/Responses/Expected/checkout/complete_validation_failed_insufficient_stock.json
| Related tickets | ~ |
This fix introduces the missing checkout complete validation group to the finalize step. This is to ensure event data passed through the admin api is validated according to the application requirements.
> Add missing checkout complete validation group

- src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php
Fix wrong assertion which prevented default admin user creation (sylius@example.com / sylius) when installing with '--no-interaction' option
> Fix wrong assertion which prevented default admin user creation

- docs/cookbook/images-on-entity.rst
Made so by default the config is for multiple image upload and added a tip section that explains how to make a single image upload in detail
| Related tickets | Fixes a use-case #7790 |
> Fixed on how to make "single image upload"

- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductImage.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
- src/Sylius/Component/Core/Model/ProductImagesAwareInterface.php
- src/Sylius/Component/Core/Model/ProductVariant.php
- src/Sylius/Component/Core/Model/ProductVariantInterface.php
- src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php
| Related tickets | fixes #7993|
Add the possibility to get variant's images directly from product variant entity without loading images of parent product.
> Product variant images

- src/Sylius/Bundle/UiBundle/Resources/views/Layout/centered.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Layout/sidebar.html.twig
When implementing custom pages in admin interface, we need to put some markup directly before and after the rendered content. We could do it in the full view template itself which extends from the layout, but sometimes, we're including some pages and routes which are not Sylius specific and are used on other CMSes, like eZ Platform in which case this additional pre-content and post-content markup would not make sense.
This PR adds two blocks called `pre_content` and `post_content` to UiBundle layouts which allow to inject some markup before and after the content when needed.
> Add pre & post content blocks to UiBundle layouts

- src/Sylius/Component/Grid/Filter/DateFilter.php
- src/Sylius/Component/Grid/spec/Filter/DateFilterSpec.php
There seems to have been some arbitrary decision made that the DateFilter should have inclusive from, but exclusive to. 
I've made these configurable.
Defaults reflect the current code, so no BC break.
> [Grid] allow configuring inclusiveness of to and from date filters

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product_taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/customer.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/inventory.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/address.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/channel.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/customer.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/product.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/promotion.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/shipment.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_association_type.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_review.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipping_method.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/taxon.yml
While implementing the `Sylius\Bundle\ResourceBundle\Controller\AuthorizationCheckerInterface` we found out that many routes from the admin bundle miss the `permission` flag and so the authorization check is never called for these routes ([see source](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php#L484)). This is kind of security issue when implementing privileges separation for different roles of admins.
> Add missing permission flag to the admin routes for the authorization check to actually work

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Attribute/attributeValues.html.twig
By not hard coding application name and subject.
Makes it possible to re-use attributeValues.html.twig for attributes for
your custom models (and Sylius default models).
| Related tickets | fixes https://sylius-devs.slack.com/files/sweoggy/F5T2DSDS8/Untitled.php |
> [Admin][DX] Improved attributes extensibility

- src/Sylius/Component/Grid/Filter/DateFilter.php
- src/Sylius/Component/Grid/spec/Filter/DateFilterSpec.php
As per the form type: https://github.com/Sylius/Sylius/blob/a912a695563d853a86e4bd2b2fafef1cd6b75a15/src/Sylius/Bundle/GridBundle/Form/Type/Filter/DateFilterType.php#L30-L46
`to` and `from` are not required, and not providing them cause an `Undefined index` error.
> [Grid] to and from are not required in grid date filter

- src/Sylius/Bundle/ThemeBundle/Templating/TemplateNameParser.php
- src/Sylius/Bundle/ThemeBundle/spec/Templating/TemplateNameParserSpec.php
| Related tickets | fixes #8189 |
Fixes support for custom Twig namespaces (http://symfony.com/doc/current/templating/namespaced_paths.html#registering-your-own-namespaces)
I don't know if this should be done this way, but the patch works fine.
> [ThemeBundle] Fix support for custom Twig namespaces

- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/create.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/index.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/update.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/show.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/index.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/history.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/show.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/update.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/index.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/generate.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/index.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/generate.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/index.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
Instead of prefix, this is better UX. Knowing where you are in the admin
panel is more important to users than knowing what is powering it.
| BC breaks?      | no (Well yes if someone relied on page titles...) |
> [UX][Admin] Changed admin titles to include Sylius as postfix

- features/account/customer_account/address_book/editing_address.feature
- src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
Assertion for containing a string in an address was missing which caused the step `it should contain` to always pass.
> [Behat][AddressBook] Added missing assertion

- docs/components/Product/basic_usage.rst
This fixes partially. If you copy the code from [Product attributes management](http://docs.sylius.org/en/latest/components/Product/basic_usage.html#product-attributes-management) , it throws
```
PHP Fatal error:  Uncaught RuntimeException: No locale has been set and current locale is undefined. in /home/hari/experiments/php/sylius/product/vendor/sylius/resource/Model/TranslatableTrait.php:126
Stack trace:
```
The problem is locale not set for Translation. Want to look into it regarding how to fix the same..
> [Documentation][Product] Fix some typos

- src/Sylius/Bundle/AddressingBundle/Form/EventListener/BuildAddressFormSubscriber.php
When the form is loaded without ajax on the form post, the label should be correct immediately. See https://github.com/Sylius/Sylius/issues/8152
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/8152, partially #Y, mentioned in #Z |
> Use appropriate labels and placeholders

- docs/bundles/SyliusGridBundle/field_types.rst
The description was missing a hint how to get the single field data or
the whole instance data into the twig template and display it.
Otherwise the example will display an error.
| Bug fix?        | yes - documentation bug |
> [Documentation][SyliusGridBundle] fixing twig field type

- UPGRADE.md
- app/config/config.yml
- app/config/security.yml
Now if we want to have url which starts with `/api` we have access denied exception due to /api firewall. Also where is similar issue with FOS FormatListener, etc.
Before 
| url | http code |
|---|----|
| /api/something | 401 |
| /apiary | 401 |
After
| url | http code |
|---|----|
| /api/something | 401 |
| /apiary | 200 |
> Validate API url with pattern ^/api/.* not just ^/api

- tests/Controller/CheckoutApiTestCase.php
This adds a few assertions in CheckoutApiTestCase to make sure API calls are successful. Noticed this after a change produced an error in one of the API calls which wasn't detected and only caused a subsequent call to fail.
> Add assertions in CheckoutApiTestCase

- docs/bundles/SyliusResourceBundle/create_resource.rst
- docs/bundles/SyliusResourceBundle/update_resource.rst
| Related tickets | / |
I believe this is an error in the docs. The `validation_groups` (and other form options) need to be defined under a key `options` instead of directly under `form`.
(See: https://github.com/Sylius/Sylius/blob/v1.0.0-beta.2/src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php#L149)
> [Documentation][Resource] Fix the form options configuration in docs

- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/locale/url.xml
Since now we have the option to configure the shop firewall name, chage it to be able to impersonate
| Related tickets | #8210  |
> Take shop firewallname in services from container parameter

- src/Sylius/Bundle/MailerBundle/Sender/Adapter/SwiftMailerAdapter.php
In Swiftmailer v6 the `newInstance()` methods were removed.
This change makes the MailerBundle compatible with both Swiftmailer v5 and v6 👍
> [MailerBundle] Fix compatibility for Swiftmailer v6

- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/string.html.twig
Fix empty label when `form_options: { type }` is 'string'.
How to reproduce:
in `sylius_grid_mymodel.yml` specify form_options to avoid matching type dropdown:
```
year:
type: string
form_options:
type: contains
```
And field label disappear:
> [UI] Show filter label when form type is defined

- docs/bundles/SyliusShippingBundle/resolving_available_methods.rst
I was no able to load form type using the code from the example, it was possible to load it only with ShippingMethodChoiceType::class and null as a second arg.
> Example did not work for me.

- src/Sylius/Bundle/AddressingBundle/Resources/config/validation/Zone.xml
- src/Sylius/Bundle/AddressingBundle/Resources/config/validation/ZoneMember.xml
| Related tickets | fixes #3886 |
Fixes Mysql Error Integrity constraint violation: 1062 when creating a new zone with duplicate zone members
> [Addressing] Use UniqueWithinCollectionConstraint instead UniqueEntity for members validation

- src/Sylius/Behat/Page/Admin/Product/IndexPerTaxonPage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/IndexPage.php
| Related tickets | None |
At present a few steps in Behat scenarios are somewhat unstable - they sometimes pass and sometimes fail due to a race condition. `And I save my new configuration` in  [`features/product/managing_products/sorting_products_within_a_taxon_by_position.feature` ](https://github.com/Sylius/Sylius/blob/de21554/features/product/managing_products/sorting_products_within_a_taxon_by_position.feature#L34) is one particular instance.
The issue seems to arise from the fact, that `waitFor` condition is checking if a particular element has a particular class (`.loading`), but the check internally is two steps: 1) find the element …
> [Behat] Change how Page objects wait/check for disappearing element

- docs/contributing/documentation/overview.rst
- docs/requirements.txt
| Bug fix?        | kinda |
requirements.txt for pip is located in the docs/ folder in the root of the project. also, running all these commands I ended up with an error like the one described here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/293#issuecomment-266879303
therefor, I thought it would be better to include that dependency as explicit.
> [Documentation] improve the contribution guide for docs

- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/generate.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/generate.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Form/Buttons/_create.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Form/Buttons/_update.html.twig
| Related tickets | fixes #7580 |
Before:
After:
It does not seem like the translation is used in any other place.
Should i remove it from the translations (which would be a very minor BC-Break, if anyone uses this key for anything else)
If I should remove it: where do i remove it? Only in the english language files or everywhere?
(Sorry, I don't know how the auto-update from crowdin works)
> remove "or" from ui because it breaks with foreign translations

- src/Sylius/Bundle/ResourceBundle/Routing/Configuration.php
- src/Sylius/Bundle/ResourceBundle/Routing/ResourceLoader.php
- src/Sylius/Bundle/ResourceBundle/spec/Routing/ResourceLoaderSpec.php
This adds the `filterable` option to the ResourceLoader, allowing to specify filterable routes without having to manaually redeclare the `index` route.
> Allow filterable resource routes

- src/Sylius/Bundle/ResourceBundle/Controller/RequestConfigurationFactory.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/RequestConfigurationFactorySpec.php
By fetching all request headers of a given key instead of the first one only (which is the default of Symfonys headers `get`), configuring a request is possible event if two `Accept` headers are sent.
> Allow multiple Accept headers in request configuration

- .travis.yml
Trusty was automatically enabled for our builds causing fails, until #8327 or #8293 is merged we should stay on Precise.
> Force Travis to use Ubuntu Precise

- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceControllerSpec.php
Return event response so it's possible to return a different template with a list of relations (as example) before deleting the resource.
> [ResourceBundle] Return event response if exists before deleting resource

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_pagination.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_sorting.html.twig
Without these changes, some filter states are lost due to improper merging of the query parameters. If you would for example filter on 50 products per page and change the order to display the products, the limit is for example lost. These changes fix this.
> [BugFix] Make sure query parameters are retained properly when filtering.

- features/shipping/applying_shipping_fee/applying_correct_shipping_fee_on_order.feature
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Resources/config/suites/ui/shipping/applying_shipping_fee.yml
- src/Sylius/Component/Core/OrderProcessing/OrderShipmentProcessor.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderShipmentProcessorSpec.php
Steps to reproduce:
1. Create shipping method with `per_unit_rate` calculator
2. Add some product to cart with quantity bigger than 1
3. Go to checkout and select shipping method created in *1.*
4. Go back to cart an decrease quantity of added order item
5. Cry a lot, as shipping fee is as big as it was before.
This is just a hotfix, to be 100% that proper units are added for the only one shipment. We should definitely think about some more sophisticated solution.
> [Shipment] Shipment amount was not updated after decreasing item quantity

- src/Sylius/Bundle/ShopBundle/Resources/private/js/app.js
Based on Customer validation an email should be between 2 - 254 characters. I noticed in my 404 logs that sometimes this request is fired without any information in it (empty). That will for sure return no valid customer and it's ineffecient.
Based on https://semantic-ui.com/behaviors/api.html#/usage ('Cancelling requests') this adjustment should prohibit this call when nothing (or something too long) is entered. It could be extended to check for email validatity, but that's always an hard issue.
> Check for input minimum length on customer existence check in checkout

- src/Sylius/Component/Addressing/Model/AddressLogEntry.php
According to the [docs](https://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/tutorials/getting-started.html#what-are-entities):
> An entity class must not be final or contain final methods.
> Make AddressLogEntry entity extendable

- src/Sylius/Component/Core/Checker/OrderShippingMethodSelectionRequirementChecker.php
- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/Model/OrderInterface.php
- src/Sylius/Component/Core/OrderProcessing/OrderShipmentProcessor.php
- src/Sylius/Component/Core/spec/Checker/OrderShippingMethodSelectionRequirementCheckerSpec.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderShipmentProcessorSpec.php
| Related tickets | resolves #8380  |
Hi,
As mentioned in #8380, I've moved the check for whether shipping is required onto the order model itself.
I've added it to the core `OrderInterface` since that's where the other shipping related method definitions exist, and also updated the PHPSpec tests to suit.
Let me know if there's any issues or anything I've missed!
> Moved the shipping required check to the order model itself

- src/Sylius/Bundle/CustomerBundle/Resources/config/validation/Customer.xml
- src/Sylius/Bundle/CustomerBundle/Resources/translations/validators.en.yml
The email validator already checks for a minimum length.
| Related tickets | fixes #8363 |
> Remove min length validator from Customer Email (fixes #8363)

- src/Sylius/Bundle/ThemeBundle/Twig/ThemeFilesystemLoader.php
| Related tickets | fixes #8392 |
Since Symfony's WebProfilerBundle still requires implementing interfaces required in Twig 1.x, this adds back the implementation of `Twig_ExistsLoaderInterface` to the `ThemeFilesystemLoader` to satisfy the problematic class' requirements in the least disruptive way.
> Implement Twig_ExistsLoaderInterface to keep compatibility with Symfony's WebProfilerBundle (Fix #8392)

- src/Sylius/Bundle/CoreBundle/Fixture/ProductFixture.php
| Related tickets | fixes #8403 |
If you're generating products with the Sylius Fixtures Bundle you'll run into trouble with `product_reviews`. Sylius will let you know that they don't exist. Removing `product_reviews` as an option resolves the issue.
```[Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException]
The option "product_reviews" does not exist. Defined options are: "channels", "code", "description", "enabled", "images", "main_taxon", "name", "product_attri
butes", "product_options", "shipping_required", "short_description", "taxons", "variant_selection_method".```
> Product Reviews does not exist on product

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_box.html.twig
Add the ability to hook into a product listing before and after each product box.
> Add event before / after product box on product listing

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_main.html.twig
In the product list, the events get supplied a `products` var, which is empty. The products are actually in `resources.data`, which therefore should be supplied to the events.
> Fix events on product listings, resources.data should be used

- src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/RequestConfigurationSpec.php
| Related tickets | #8382 |
This PR allows to set redirect parameters when using sylius.resource and a custom criteria. For example:
```
app_document:
prefix: /customers/{customerId}/
resource: |
alias: app.document
section: ...
templates: ...
redirect: index
grid: app_document
form:
type: ...
criteria:
customer: $customerId
vars:
all:
redirect:
parameters:
customerId: $customerId
type: sylius.resource
```
> [Resource] Allows to set redirect parameters when using sylius.resource and a custom criteria

- src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/_header.html.twig
Can be used e.g. to add tracking based on Taxon name (e.g. Enhanced Ecommerce).
> Add events before and after taxon header

- docs/components/Shipping/basic_usage.rst
The width property was declared twice.
> Remove duplicate width property

- UPGRADE.md
- src/Sylius/Bundle/MailerBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/MailerBundle/DependencyInjection/SyliusMailerExtension.php
- src/Sylius/Bundle/MailerBundle/Renderer/Adapter/EmailTwigAdapter.php
- src/Sylius/Bundle/MailerBundle/Sender/Adapter/SwiftMailerAdapter.php
- src/Sylius/Bundle/MailerBundle/spec/Renderer/Adapter/EmailTwigAdapterSpec.php
- src/Sylius/Bundle/MailerBundle/spec/Sender/Adapter/SwiftMailerAdapterSpec.php
- src/Sylius/Bundle/MailerBundle/test/app/AppKernel.php
- src/Sylius/Bundle/MailerBundle/test/src/Tests/SyliusMailerBundleTest.php
- src/Sylius/Component/Mailer/Event/EmailRenderEvent.php
- src/Sylius/Component/Mailer/Event/EmailSendEvent.php
- src/Sylius/Component/Mailer/Factory/EmailFactory.php
- src/Sylius/Component/Mailer/Factory/EmailFactoryInterface.php
- src/Sylius/Component/Mailer/Model/Email.php
- src/Sylius/Component/Mailer/Model/EmailInterface.php
- src/Sylius/Component/Mailer/Provider/DefaultSettingsProvider.php
- src/Sylius/Component/Mailer/Provider/DefaultSettingsProviderInterface.php
- src/Sylius/Component/Mailer/Provider/EmailProvider.php
- src/Sylius/Component/Mailer/Provider/EmailProviderInterface.php
- src/Sylius/Component/Mailer/Renderer/Adapter/AbstractAdapter.php
- src/Sylius/Component/Mailer/Renderer/Adapter/AdapterInterface.php
- src/Sylius/Component/Mailer/Renderer/RenderedEmail.php
- src/Sylius/Component/Mailer/Sender/Adapter/AbstractAdapter.php
- src/Sylius/Component/Mailer/Sender/Adapter/AdapterInterface.php
- src/Sylius/Component/Mailer/Sender/Sender.php
- src/Sylius/Component/Mailer/Sender/SenderInterface.php
- src/Sylius/Component/Mailer/spec/Factory/EmailFactorySpec.php
- src/Sylius/Component/Mailer/spec/Model/EmailSpec.php
- src/Sylius/Component/Mailer/spec/Provider/EmailProviderSpec.php
- src/Sylius/Component/Mailer/spec/Sender/SenderSpec.php
| Related tickets | https://github.com/Sylius/Sylius/issues/8425 |
> [Mailer] Scalar types in Mailer

- docs/cookbook/custom-email.rst
The Senderinterface requires the email addresses as an Array. Bug in sample code
> [Documentation][Email] SenderInterface->send requires Array of Emails

- docs/bundles/SyliusGridBundle/index.rst
The GridBundle states it supports bulk actions on the feature overview. I'm quite sure it doesn't at the moment (although it would be a great feature to have). Probably better to remove it from the docs, as this shows up on the first Google result when searching for 'Sylius bulk action'.
> Remove 'bulk actions' from GridBundle feature list

- docs/book/products/products.rst
When attempting to create product without setting the slug, I get an MySQL error saying that column slug can not be null. Setting the slug persists the product. Please ensure that my proposed change is valid.
> Adds slug requirement for product creation

- docs/book/configuration/currencies.rst
Handy Money Format helpers are already there in Sylius - but not
documented. Here u go! ;-)
> [Documentation][ShopBundle][TheBook] twig money format helpers

- src/Sylius/Behat/Page/SymfonyPage.php
- src/Sylius/Behat/Page/SymfonyPageInterface.php
The problem at hand was that when verifying if the current url belongs to the page object it expects the URL to match perfectly, but in case of `CRUD/UpdatePage` this is not always desired, as it requires ID of the resource to be passed in order to generate the full expected URL. But in some cases the ID is not relevant and I would be happy for it to match any URL that is for an UpdatePage of my resource.
For this reason, I have added a new method `verifyRoute()` which will validate if the matched route has the same name as expected and validates any parameters that you explicitly provide (any other parameters that …
> [Behat] Add a less strict alternative to SymfonyPage::verifyUrl

- UPGRADE.md
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
[No one](http://symfony.com/doc/current/setup/web_server_configuration.html) should be using the internal web server in a production environment anyway. Makes the Kernel a tiny bit slimmer and promotes good practises (it always possible to re-add the bundle if needed).
> [Core] Removed WebServerBundle from prod env

- src/Sylius/Component/Grid/Definition/ArrayToDefinitionConverter.php
- src/Sylius/Component/Grid/Definition/Field.php
- src/Sylius/Component/Grid/spec/Definition/ArrayToDefinitionConverterSpec.php
- src/Sylius/Component/Grid/spec/Definition/FieldSpec.php
This properly fix the sortable fields. As it is right now it's not possible to specify that a field is sortable exactly as the docs states:
[SyliusGridBundle Docs](http://docs.sylius.org/en/latest/bundles/SyliusGridBundle/configuration.html
)
`sortable: true
`
It only allows you to specify the field name otherwise a doctrine exception is thrown because `true` is used as field name.
> Sortable fields not working when sortable: true

- src/Sylius/Bundle/ResourceBundle/Controller/ParametersParser.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ParametersParserSpec.php
| Related tickets | discovered in in https://github.com/Sylius/Sylius/pull/8478 |
While working on introducing strict scalar types in *Core*, I've realized we can have some problems with them while using parameters passed with [yml routing configuration](https://github.com/Sylius/Sylius/blob/7c13a247355d42d07a4e8cb360bbac709d706528/src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/product.yml#L16). Yaml itself supports explicit typing (https://symfony.com/doc/current/components/yaml/yaml_format.html#explicit-typing), however it does not work for variables which are always passed as a string.
I think we can use the same syntax in …
> [Resource] Allow parsing variable in yaml to int/float/double

- docs/bundles/SyliusProductBundle/installation.rst
It seems that the locale bundle is a dependency of the product bundle, and hence also needs to be registered with the kernel.
> Adds locale bundle to list of bundles

- docs/cookbook/disabling-shop-admin-api.rst
| Related tickets | fixes #7991 |
Documentation fix on disabling the API. Suggested change was mentioned in #7991.
> [Docs] Fix docs about disabling API (fixes #7991)

- docs/cookbook/platform-sh.rst
| Related tickets | fixes #8124 |
As requested by @CoderMaggie, some additional information on the Platform.sh docs based on findings in a project running Platform.sh in production.
> [Docs] Tune default Platform.sh docs based on project in production

- src/Sylius/Bundle/ThemeBundle/Asset/Package/UrlPackage.php
- src/Sylius/Bundle/ThemeBundle/Resources/config/services/integrations/assets.xml
- src/Sylius/Bundle/ThemeBundle/spec/Asset/Package/UrlPackageSpec.php
| Related tickets | fixes #8278 |
Overrides Symfony's UrlPackage to allow theme bundle to handle different base URL's. Allows users that use themes, also to use CDN base URL's for assets.
> Base URL support in ThemeBundle (fixes #8278)

- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/DocumentRepository.php
Fixes the following error I ran in after upgrading to `dev-master` today:
```
Compile Error: Declaration of Sylius\Bundle\ResourceBundle\Doctrine\ODM\PHPCR\DocumentRepository::createPaginator(array $criteria = Array, array $sorting = Array) must be compatible with Sylius\Component\Resource\Repository\RepositoryInterface::createPaginator(array $criteria = Array, array $sorting = Array): iterable
```
Probably because I'm using the Lakion CmsPlugin, which uses PHPCR.
> Fix DocumentRepository not compatible with Interface

- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ResourceBundle/Doctrine/DBAL/Type/UTCDateTimeType.php
- src/Sylius/Bundle/ResourceBundle/Tests/Doctrine/DBAL/Type/UTCDateTimeTypeTest.php
| Related tickets | fixes #8305 |
Based on code provided by @mbabker in #8305 (thanks!) - added support for `\DateTimeImmutable`, stricter typehints and some tests.
> Store datetimes in UTC

- UPGRADE.md
- src/Sylius/Bundle/CoreBundle/Controller/OrderController.php
- src/Sylius/Bundle/CoreBundle/Controller/PaymentMethodController.php
- src/Sylius/Bundle/CoreBundle/Controller/ProductTaxonController.php
- src/Sylius/Bundle/CoreBundle/Controller/ProductVariantController.php
- src/Sylius/Bundle/ProductBundle/Controller/ProductAttributeController.php
| Related tickets | fixes #8563 |
In case it's decided that controllers extending `ResourceController` should not be `final`, then here is the PR to fix that.
> Remove final from controllers extending ResourceController (fixes #8563)

- src/Sylius/Component/Registry/ServiceRegistry.php
- src/Sylius/Component/Registry/spec/ServiceRegistrySpec.php
Following #8519
Hello there,
[Sylius Registry](http://docs.sylius.org/en/latest/components/Registry/basic_usage.html) is a very useful standalone component that allow to locate services that share the same type.
This is a common need in many PHP projects, however the current implementation limits the type checking to services that share the same `interface`.
Some PHP projects or libraries rely on abstract classes instead of interfaces and type comparing with `instanceof` work as well. 
The aim of this PR is to use the `instanceof` operator instead of `class_implements()` - thus we could register services sharing the …
> Allow parent class type in ServiceRegistry

- features/checkout/skipping_payment_step_when_order_total_is_zero_after_applying_coupon.feature
- features/order/managing_orders/seeing_order_payment_state_as_completed_if_free_order_coupon_was_applied.feature
- features/order/managing_orders/seeing_order_payment_state_as_completed_if_order_total_is_zero.feature
- features/order/managing_orders/seeing_order_shipment_state_as_shipped_if_there_is_not_shipments_to_deliver.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Transform/PromotionContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
- src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/transform.xml
- src/Sylius/Behat/Resources/config/suites/ui/order/managing_orders.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_payments.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipments.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/show.html.twig
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_checkout.yml
- src/Sylius/Component/Core/OrderProcessing/OrderPaymentProcessor.php
- src/Sylius/Component/Core/StateResolver/OrderPaymentStateResolver.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderPaymentProcessorSpec.php
- src/Sylius/Component/Core/spec/StateResolver/OrderPaymentStateResolverSpec.php
- src/Sylius/Component/Core/spec/StateResolver/OrderShippingStateResolverSpec.php
| Related tickets | https://github.com/Sylius/Sylius/issues/7952, https://github.com/Sylius/Sylius/issues/7943  |
Big thanks for @Persata and @bruno-ds for pointing this out!
For now, if there is no shipment to deliver we mark order as `shipped` and if there is no payment we make order `paid`. We can of course introduce some new states but I think it's not crucial for 1.0.0.
> [Core] Control Order's payment and shipping state

- features/account/customer_account/viewing_orders_history/seeing_customer_orders_placed_as_guest.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Ui/Shop/CheckoutContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites/ui/account/customer.yml
- src/Sylius/Bundle/CoreBundle/Form/Type/Customer/CustomerGuestType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
The problem was, that if we change email address in addressing checkout step, it was changed in customer entity. The quick fix for that is to create a new `Customer` if email is changed. It would sadly result in unneeded `Customer`s with wrong email in database, but it's still much better than current bug 😄
> Prevent guest orders hijacking

- UPGRADE.md
- composer.json
- composer.lock
| Related tickets | fixes #8574  |
Going forward with #8574 & https://github.com/liip/LiipImagineBundle/releases/tag/1.9.1, hereby the PR to move past this BC break. It's rather small for Sylius users probably, but it is something.
> Upgrade liip/imagine-bundle to ^1.9.1 to move past BC break in CLI cmd (fixes #8574)

- src/Sylius/Bundle/PayumBundle/Model/PaymentSecurityToken.php
Just ran into this issue using an offline payment method.
```
Type error: Return value of Sylius\Bundle\PayumBundle\Model\PaymentSecurityToken::getAfterUrl() must be of the type string, null returned
```
The used gateway = 'offline', so it's the Sylius internal one. Ran into it as in the resulting controller I'm doing some logging, which requested the afterUrl. Looking at the class code, it makes sense that it could return `null`, without the user having any other option finding out whether it is set at all (no other way to test this).
> Make afterUrl nullable

- UPGRADE.md
- src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodType.php
- src/Sylius/Bundle/ShippingBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Shipping/Model/ShippingMethod.php
- src/Sylius/Component/Shipping/Model/ShippingMethodInterface.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/8360 |
I was not sure what to do with `getCategoryRequirementLabel` method, as it uses the static method that would couple component with translations keys... but now there is no easy way to display shipping method category requirement... but we don't display it anywhere 😄  🎪
> [Shipping] Make shipping method category requirements translatable

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment_method.yml
- src/Sylius/Bundle/CoreBundle/Form/Extension/PaymentMethodTypeExtension.php
| Related tickets | fixes #8060 |
Changes:
- display gateway as gateway factory name in payment methods grid
- set gateway name as a payment method code which is unique instead of payment method name
> [PaymentMethod] Minor gateway fixes

- docs/cookbook/disabling-order-confirmation-email.rst
| Doc fix?        | ~yes |
| New docs?    | no :( |
| Related tickets | fixes #8395, at least in the docs there will be no more confusion |
Currently the `sylius.order.payment.post/pre_complete` events are not available.
And the `sylius.payment.post/pre_complete` events cannot be used in the `sylius.listener.order_complete` as they contain Payment object not Order.
> [Documentation] Update Disabling Order Confirmation email cookbook

- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
`getCurrencyCode() must be of the type string, null returned` error
> Eager fetch locales and currencies on channel to prevent blowing up Sylius

- docs/components_and_bundles/bundles/SyliusOrderBundle/services.rst
`$orderItem->getTotal();` should be 2 * 1000 = 2000
Changed the `"0"` and `"2"` because getQuantity() returns an integer.
> [Docs] Corrections on OrderItemQuantityModifier

- .gitignore
| Related tickets | fixes #8681  |
> Gitignore webserver pid files

- docs/cookbook/checkout.rst
There is no any ```completeAction``` in source file (ShopBundle/Resources/config/routing/checkout.yml) 
Also there is no such action in ```OrderController``` or its ancestors, so it cause error
> [Documentation] Non-existent action used

- README.md
Hello there,
I suggest some minor changes in the README. When looking at the installation part, I found some confusing points:
* The guide assumes you've never used composer but you're comfortable with yarn (it will probably be the contrary)
* There's no "production" point.
* The code block looks big, and some may think the installation is tedious at first glance
* There are too many links to my eyes :)
I also changed the order of the sentences in the intro to conclude with "Enjoy being an eCommerce Developer again!" instead of having it somewhere in the middle.
What's your opinion?
> [Documentation / README] Simplified installation guide

- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/PaymentState/partially_refunded.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/ShippingState/partially_shipped.html.twig
| Related tickets | fixes #8717; fixes #8719  |
> Do not crash admin while listing partially shipped orders

- src/Sylius/Component/Mailer/Sender/SenderInterface.php
> [Mailer] Added missing PHPDoc argument

- src/Sylius/Bundle/ShopBundle/EventListener/UserRegistrationListener.php
- src/Sylius/Bundle/ShopBundle/spec/EventListener/UserRegistrationListenerSpec.php
| Related tickets | fixes #8720 |
> Do flush after enabling a user in user registration listener

- src/Sylius/Bundle/ReviewBundle/DependencyInjection/SyliusReviewExtension.php
- src/Sylius/Bundle/ReviewBundle/EventListener/ReviewChangeListener.php
- src/Sylius/Bundle/ReviewBundle/spec/EventListener/ReviewChangeListenerSpec.php
| Bug fix?        | kind of |
| New feature?    | kind of  |
In case you handle your reviews without moderation (directly with accepted status), you need your subject would be recalculate on post create event. You also need this feature if you handle ratings without title and comment.
> [ReviewBundle] Recalculate subject rating on review post create event

- docs/book/themes/themes.rst
| Related tickets |  mentioned in #8789 
Added step 3 in the guide. This is mainly taken from [here](http://docs.sylius.org/en/latest/components_and_bundles/bundles/SyliusThemeBundle/important_changes.html#assets) but when you are reading this page on how to create a theme, you don't know to find that page. One option was to link to that, but as that page is about changes, it seems to make more sense to put it into the core documentation. Merging it in to this page will prevent developers from struggling (as I did) to find out why the issues in ticket #8789 are happening.
I've renamed later steps to …
> [Documentation] Clarification of how to install assets in a new theme

- docs/components_and_bundles/bundles/SyliusShippingBundle/custom_calculators.rst
- docs/components_and_bundles/bundles/SyliusTaxationBundle/custom_calculators.rst
> [Documentation] Quick typo fix

- etc/travis/suites/application/script.sh
- etc/travis/suites/application/script/validate-composer-security
Not sure 1.0 is good here, but let's first see if it works on Travis. Next to validating Composer, Yarn, etc, it might also be good to check dependencies for known security issues. Currently there is nothing, but it's good to keep it automated I think.
> Run security:check to actively check issues in Composer dependencies

- README.md
- docs/book/installation/installation.rst
| Related tickets | fixes #8765
Mention about PHP ^7.1 not to confuse people installing older Sylius versions.
> Mention ^PHP7.1 requirement when installing Sylius (closes 8765)

- docs/book/orders/orders.rst
As mentioned in https://github.com/Sylius/Sylius/pull/6901#commitcomment-21147273 this confused me quite a bit before I found this.
Feel free to suggest sth. different
> [Documentation] Remove outdated exchange rate info from Order docs

- features/product/managing_product_attributes/adding_select_product_attribute.feature
- features/product/managing_product_attributes/select_product_attribute_validation.feature
- features/product/managing_product_attributes/text_product_attribute_validation.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductAttributesContext.php
- src/Sylius/Behat/Page/Admin/ProductAttribute/CreatePage.php
- src/Sylius/Behat/Page/Admin/ProductAttribute/CreatePageInterface.php
- src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/Configuration/DateAttributeConfigurationType.php
- src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/Configuration/DatetimeAttributeConfigurationType.php
- src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/Configuration/SelectAttributeConfigurationType.php
- src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/Configuration/TextAttributeConfigurationType.php
- src/Sylius/Bundle/AttributeBundle/Resources/config/services.xml
- src/Sylius/Bundle/AttributeBundle/Resources/config/validation/Attribute.xml
- src/Sylius/Bundle/AttributeBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/AttributeBundle/Validator/Constraints/ValidSelectAttributeConfiguration.php
- src/Sylius/Bundle/AttributeBundle/Validator/Constraints/ValidSelectAttributeConfigurationValidator.php
- src/Sylius/Bundle/AttributeBundle/Validator/Constraints/ValidTextAttributeConfiguration.php
- src/Sylius/Bundle/AttributeBundle/Validator/Constraints/ValidTextAttributeConfigurationValidator.php
- src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/ValidSelectAttributeConfigurationSpec.php
- src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/ValidSelectAttributeConfigurationValidatorSpec.php
- src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/ValidTextAttributeConfigurationSpec.php
- src/Sylius/Bundle/AttributeBundle/spec/Validator/Constraints/ValidTextAttributeConfigurationValidatorSpec.php
| Related tickets | fixes #8671
> [Attribute] Configuration validation of text and select attributes

- features/installer/install_command.feature
- features/installer/load_sample_data_command.feature
- src/Sylius/Behat/Context/Cli/InstallerContext.php
- src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php
| Related tickets | fixes #8613
> [Installation] Add setting a username during installation

- src/Sylius/Bundle/AdminApiBundle/Form/Type/OrderType.php
- src/Sylius/Bundle/AdminApiBundle/Resources/config/services/form.xml
Reverts #8778.
Replacing `CustomerChoiceType` with `TextType` looks like a BC break - behaviour would change if anyone has relied on form type being `CustomerChoiceType` and therefore extended it by a type extension. Moreover, it feels like it does not feel right semantically.
In order to improve performance we should use a choice loader inside our choice types. Since patch release will be out today (or at last tomorrow), reverting it and coming up with more backward compatible yet performant solution later seems like the best decision.
> Revert "Changed CustomerChoiceType for a ResourceToIdentifierTransformer in OrderType of SyliusAdminApiBundle"

- src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
| Related tickets | fixes #8679  |
It seems the version was missing from admin due to a bug in a twig file - the footer block in admin got renamed post_content at some point in history. 
On top of fixing this bug, I added a new constant in the kernel class, APP_NAME with the default value being "Sylius". In case at a later point someone decides to craft a forked version of Sylius called "Supercharged Sylius" and it needs to brag about the name. Before hand, Sylius was hardcoded in the twig template. 
I have declared both Sylius\Bundle\CoreBundle\Application\Kernel::VERSION and Sylius\Bundle\CoreBundle\Application\Kernel::APP_NAME as twig …
> add sylius version to the footer in admin

- src/Sylius/Bundle/CoreBundle/Installer/Checker/SyliusRequirementsChecker.php
| Bug fix?        | not realy
Hey ya, 
During the installation, when any requirements collection fails it would print out the entire not-fulfilled table of the previous component aswell. This PR introduces a table per collection. As a result this:
```
PHP version and settings
+-------------------------+----------+
| Requirement             | Status   |
+-------------------------+----------+
| timezone                | ERROR!   |
| Recommended PHP version | WARNING! |
| detect_unicode          | WARNING! |
| session.auto_start      | WARNING! |
+-------------------------+----------+
extensions …
```
> Clean the not Fulfilled Table before each collection

- etc/travis/suites/application/is_suitable.sh
- etc/travis/suites/docs/is_suitable.sh
- etc/travis/suites/packages/is_suitable.sh
> Optimise Travis builds

- src/Sylius/Bundle/AdminApiBundle/Model/ClientManager.php
- src/Sylius/Bundle/AdminApiBundle/spec/Model/ClientManagerSpec.php
| Related tickets | fixes #8673
The underlying `findOneBy` may return null, the docblock seems to be
wrong. The null value will be handled correctly in the `AuthorizeController`.
> [AdminApi] Fix nullable ClientInterface return type in admin api

- .travis.yml
- src/Sylius/Bundle/AddressingBundle/test/app/config/config.yml
- src/Sylius/Bundle/AttributeBundle/test/app/config/config.yml
- src/Sylius/Bundle/ChannelBundle/test/app/config/config.yml
- src/Sylius/Bundle/CurrencyBundle/test/app/config/config.yml
- src/Sylius/Bundle/CustomerBundle/test/app/config/config.yml
- src/Sylius/Bundle/FixturesBundle/test/app/config/config.yml
- src/Sylius/Bundle/GridBundle/test/app/config/config.yml
- src/Sylius/Bundle/InventoryBundle/test/app/config/config.yml
- src/Sylius/Bundle/LocaleBundle/test/app/config/config.yml
- src/Sylius/Bundle/MailerBundle/test/app/config/config.yml
- src/Sylius/Bundle/MoneyBundle/test/app/config/config.yml
- src/Sylius/Bundle/OrderBundle/test/app/config/config.yml
- src/Sylius/Bundle/PaymentBundle/test/app/config/config.yml
- src/Sylius/Bundle/ProductBundle/test/app/config/config.yml
- src/Sylius/Bundle/PromotionBundle/test/app/config/config.yml
- src/Sylius/Bundle/ResourceBundle/test/app/config/config.yml
- src/Sylius/Bundle/ReviewBundle/test/app/config/config.yml
- src/Sylius/Bundle/ShippingBundle/test/app/config/config.yml
- src/Sylius/Bundle/TaxationBundle/test/app/config/config.yml
- src/Sylius/Bundle/TaxonomyBundle/Tests/Functional/app/config/config.yml
- src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/config/config.yml
- src/Sylius/Bundle/UserBundle/Tests/Functional/app/config/config.yml
| Bug fix?        | kinda
| New feature?    | kinda
| Related tickets | continues #8868
> Support for PHP 7.2

- docs/contributing/code/bc.rst
- docs/contributing/code/index.rst
- docs/contributing/code/map.rst.inc
| Related tickets | related to #8748
> Backwards compatibility promise

- docs/book/products/products.rst
…4234008d0881a1d6a92cf5
Some interfaces in the product documentation no longer exist in the Sylius project.
They have been prefixed with Product in commit:
https://github.com/Sylius/Sylius/commit/14b7e412321a55c50b4234008d0881a1d6a92cf5
> Fix: Old interface names used in product documentation

- .travis.yml
- etc/travis/suites/application/before_install.sh
This also uses LTS Node v6 since v7 is not officially supported:
```
yarn install v1.2.1
warning You are using Node "7.5.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
```
To use Node v8, we'd need either Trusty (which causes some problems as you know) or upgrade gcc ourselves, but I'd just wait and see if Trusty works in the near future.
> [Travis] Update Yarn to stable 1.2.1, use Node v6

- docs/customization/factory.rst
After the question at https://stackoverflow.com/questions/47135122/error-following-sylius-customizing-factories-guide-examples, it seems the `use` statement shown in the example is wrong when checking it agains the 1.0 code base.
> Fix wrong use statement for ProductInterface

- docs/plugins/creating-plugin.rst
| BC breaks?      | yes (sort of.. but no in docs)
| Related tickets | fixes #8848
After discussion in #8848, hereby the PR. Difference from the discussion is that I've chosen to name the repository after the class bundle name, to have it all consistent and in the same style. 
Before merging this, there should also come a PR to the PluginSkeleton to rename things I think.
> Plugin naming convention RFC implementation (closes #8848)

- src/Sylius/Component/Resource/Metadata/Metadata.php
Small contribution to make the exception thrown in the Metadata resource more explanatory. When an Exception is thrown: "Invalid alias", the alias is now included in the Exception message, which makes debugging much easier.
> Improved parse alias exception message

- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-variants-prices.js
| Branch?         | 1.0 or master 
| Related tickets | fixes #8734
Add more accurate select jQuery selector for custom select appended in the add to cart form.
> Add more accurate select jQuery selector

- src/Sylius/Bundle/CoreBundle/Application/SyliusPluginTrait.php
I am not entirely sure what is going on here.
It seems for one that when I implemented a proper Di extension in FOSSyliusImportExportPlugin I suddenly ended up with 
```
[Payum\Core\Exception\InvalidArgumentException]
The storage factory with such name filesystem already registered
```
Which in turn seems to be caused by suddenly `\Payum\Bundle\PayumBundle\PayumBundle::build` being called twice.
Messing around I eventually ended up at:
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Return value of …
```
> ensure we return null rather than void in SyliusPluginTrait::getContainerExtension

- docs/contributing/organization/vision-and-strategy.rst
GitHub has introduced a native support for issues labeled with `Help Wanted` (so that their count can bed displayed near repository summary etc.).
> Change "Support Request" label to "Help Wanted"

- src/Sylius/Bundle/ReviewBundle/composer.json
- src/Sylius/Bundle/ReviewBundle/test/app/AppKernel.php
| Related tickets | fixes #8977
Reviews bundle doesn't need CustomerBundle and should be required.
> Decouple reviews customer

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_breadcrumb.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/_breadcrumb.html.twig
Issue: As far as there are `isRoot()` and `getRoot()` functions exists at `Taxon.php`, referring to `root` at Twig template (meaning `isRoot`) causing not expected behavior and all breadcrumbs become text rather than links (as far as `getRoot` actually called and it always `true`). 
PR fixing this issue.
> Fixed: Breadcrumbs links for Taxon and Product views

- src/Sylius/Bundle/AddressingBundle/composer.json
- src/Sylius/Bundle/AdminApiBundle/composer.json
- src/Sylius/Bundle/AdminBundle/composer.json
- src/Sylius/Bundle/AttributeBundle/composer.json
- src/Sylius/Bundle/ChannelBundle/composer.json
- src/Sylius/Bundle/CoreBundle/composer.json
- src/Sylius/Bundle/CurrencyBundle/composer.json
- src/Sylius/Bundle/CustomerBundle/composer.json
- src/Sylius/Bundle/FixturesBundle/composer.json
- src/Sylius/Bundle/GridBundle/composer.json
- src/Sylius/Bundle/InventoryBundle/composer.json
- src/Sylius/Bundle/LocaleBundle/composer.json
- src/Sylius/Bundle/MailerBundle/composer.json
- src/Sylius/Bundle/MoneyBundle/composer.json
- src/Sylius/Bundle/OrderBundle/composer.json
- src/Sylius/Bundle/PaymentBundle/composer.json
- src/Sylius/Bundle/PayumBundle/composer.json
- src/Sylius/Bundle/ProductBundle/composer.json
- src/Sylius/Bundle/PromotionBundle/composer.json
- src/Sylius/Bundle/ResourceBundle/composer.json
- src/Sylius/Bundle/ReviewBundle/composer.json
- src/Sylius/Bundle/ShippingBundle/composer.json
- src/Sylius/Bundle/ShopBundle/composer.json
- src/Sylius/Bundle/TaxationBundle/composer.json
- src/Sylius/Bundle/TaxonomyBundle/composer.json
- src/Sylius/Bundle/ThemeBundle/composer.json
- src/Sylius/Bundle/UiBundle/composer.json
- src/Sylius/Bundle/UserBundle/composer.json
We're fetching all services to smoke test whether they are properly wired and Symfony in 4.0 marks all services as private by default, so it's breaking the build. This PR is rather a fast workaround than the proper solution, but it'll do fine for now (and we'll be able to merge other PRs).
> Restrict packages to use Symfony's DI in ^3.2 version for tests

- docs/components_and_bundles/components/Order/models.rst
- docs/components_and_bundles/components/Order/processors.rst
> [Documentation] [Order] Fixes in Order component documentation: typo in models.rst and wording in processors.rst

- docs/components_and_bundles/bundles/SyliusMailerBundle/installation.rst
The mailer bundle don't need doctrine.
There is also a lot of unused dependencies in the require-dev part of the composer.json file of the bundle. Tests also register useless bundles (such as doctrine). Should I create another PR to clean both composer.json & tests?
> [Documentation][MailerBundle] Clean installation part

- src/Sylius/Component/Core/Customer/CustomerOrderAddressesSaver.php
- src/Sylius/Component/Core/spec/Customer/CustomerOrderAddressesSaverSpec.php
Because both `shippingAddress` and `billingAddress` can be returned `null`.
> [Core] Fix customer order addresses saver

- docs/customization/form.rst
| Related tickets | fixes #7862
As requested by @lchrusciel
> Add info about constraints / validation groups when using form extensions (closes #7862)

- docs/cookbook/configuration/disabling-shop-admin-api.rst
> [Documenation] Turn off bundles fixes

- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-add-to-cart.js
Use window.location.href instead of window.location.replace() to keep previous location in history and expected behavior for web browser's back-button
See https://stackoverflow.com/questions/503093/how-to-redirect-to-another-webpage
> Fixes history issue when adding to cart

- composer.json
- composer.lock
Inspired by https://twitter.com/nicolasgrekas/status/943798987638878208, removing the Polyfills for PHP <= 7.1, as Sylius requires a minimum of 7.1 anyway.
> Remove PHP <= 7.1 Polyfills

- src/Sylius/Bundle/AdminApiBundle/SyliusAdminApiBundle.php
- src/Sylius/Bundle/PayumBundle/SyliusPayumBundle.php
- src/Sylius/Bundle/ResourceBundle/AbstractResourceBundle.php
The `AbstractResourceBundle` right now requires that bundles/plugins define a model namespace.  Following conventions in core, by default this is presumably `<BundleNamespace>\Model`.  So instead of forcing child classes to define this we can make an assumption by default as a small DX improvement.
For the most part this doesn't impact core as most bundles are using component models (except for the two changed here).  But this can impact the plugin ecosystem and local app development by requiring one less method to set up.
> Try to auto-detect a bundle's model namespace by default

- app/config/security.yml
This change fixes the "... locale is unavailable in this channel" exception when loading product images in some condition.
Suppose client's browser locale is en_US, while the store's locale is zh_CN, this bug would prevent any product images from being loaded because the "NonChannelLocaleListener" class wrongly breaks the requests.
So the fix is to exclude the "/media" path from shop firewall match pattern.
> Exclude the web/media directory from firewall restrict list.

- src/Sylius/Bundle/AdminBundle/Resources/views/_flashes.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/complete.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/_flashes.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Layout/sidebar.html.twig
_flashes.html.twig are now two different file to allow override.
Ref. #9032 @pamil 
| Related tickets | fixes #9032 
> Allow specific override of flash messages for Admin and Shop.

- app/migrations/Version20180102140039.php
- src/Sylius/Bundle/ChannelBundle/Resources/config/doctrine/model/Channel.orm.xml
| Branch?         | 1.1 / master
| Related tickets | replaced #9080
The first query occuring on each request in my app does a call to the `ChannelRepository::findOneByHostname` method from the `HostnameBasedRequestResolver::findChannel` method, resulting in a query looking like this:
```
EXPLAIN SELECT t0.code AS code_1, t0.name AS name_2, t0.color AS color_3, t0.description AS description_4, t0.enabled AS enabled_5, t0.hostname AS hostname_6, t0.created_at AS created_at_7, t0.updated_at AS updated_at_8, t0.id AS id_9, t0.theme_name AS theme_name_10, t0.tax_calculation_strategy AS tax_calculation_strategy_11, t0.contact_email …
```
> Add index on Channel::hostname to prevent table scan on each request

- UPGRADE-1.0.md
- UPGRADE-1.1.md
- docs/components_and_bundles/bundles/SyliusThemeBundle/configuration_sources/filesystem.rst
- src/Sylius/Bundle/ThemeBundle/Configuration/Filesystem/FilesystemConfigurationSourceFactory.php
- src/Sylius/Bundle/ThemeBundle/Locator/RecursiveFileLocator.php
- src/Sylius/Bundle/ThemeBundle/Tests/DependencyInjection/FilesystemSource/ConfigurationTest.php
- src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/TestBundle/public/theme_asset.txt
- src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/TestBundle/translations/messages.en.yml
- src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/TestBundle/views/Templating/bothThemesTemplate.txt.twig
- src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/TestBundle/views/Templating/lastThemeTemplate.txt.twig
- src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/composer.json
- src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/translations/messages.en.yml
- src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/views/Templating/bothThemesTemplate.txt.twig
- src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/YetAnotherTheme/TestTheme/views/Templating/lastThemeTemplate.txt.twig
- src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/config/config.yml
- src/Sylius/Bundle/ThemeBundle/spec/Locator/RecursiveFileLocatorSpec.php
| Related tickets | mentioned in #9008
> Restrict scanning for composer.json in themes to certain directory depth (optional)

- src/Sylius/Bundle/CurrencyBundle/Resources/config/doctrine/model/ExchangeRate.orm.xml
This fixes an error that surfaces when trying to extend the `Currency` entity: due to the wrong mapping, it's not actually possible to extend the `Currency` entity.
I'm not sure how to reliably test this, apart from looking at all 97 `target-entity` attributes and ensuring they point to interfaces (except a Payum `GatewayConfig` that doesn't have an interface).
> Fix wrong target-entity in exchange-rate entity

- src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-form-collection.js
If you have a collection in a collection in an admin form for example, it should take the last add button not the first.
If you take the first, it will take the first of the first embedded collection if you have one (not the right one).
> Fix UI form add button issue collection in a collection

- src/Sylius/Bundle/ShopBundle/EventListener/SessionCartSubscriber.php
Prevent the kernel response listener for cart from continuing when the session is not actually started. Otherwise the next `cartContext->getCart()` method call would open a session with no sense.
A problem caused by this issue is that the following cache-control header being sent to client anyway: (because a session is started, the Symfony session listener would set that header)
> cache-control:max-age=0, must-revalidate, private
For landing pages without cart, or some shop API calls need to be cached from the CDN layer, we don't want the above cache-control header being set. …
> Prevent the kernel response listener for cart from continuing when the session is not actually started.

- docs/book/products/taxons.rst
I copied that part and wondered why my IDE wasn't suggesting methods.
Turned out, that the variable was once named $taxonsRepository instead of the singular one.
> [Documentation] Fixed Docblock in Taxon document

- .github/stale.yml
RFCs without any activity in last three months are really unlikely to be noticed again.
The comment stalebot makes a week before closing an issue might be used as a reminder instead.
> Remove RFC label from stalebot's whitelist

- src/Sylius/Behat/Resources/config/profiles/default.yml
Without `marionette: null`, MinkExtension in v2.3.0 runs Firefox instead of Chrome.
> Make Travis tests more reliable

- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
There were lots of failures because the saved image URL was a data URI.
> Make images removal tests great again

- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/8900
For sure it's not the best solution from the js point of view, but it works :)
The problem was that newly added select attribute values has translation accordion inside which needs to be triggered to make them work.
> Make accordion in select attribute values great again

- docs/contributing/documentation/standards.rst
- docs/cookbook/shop/cms.rst
- docs/cookbook/shop/map.rst.inc
| Related tickets | fixes #9155 as it was missing inclusion in .rst file
Added some statements regarding the neutrality of Sylius Documentation to the contribution guide.
> [Documentation] Add more rules to the contribution guide + Fix CMS cookbook

- docs/components_and_bundles/bundles/SyliusGridBundle/configuration.rst
sortable: true --> translates to o.1 in the SQL query
sortable: ~ --> translates to o.attribute in SQL query
sortable: path.to.my.subentity.prop --> translates to o.subentity.prop
| Related tickets | fixes none
> [Documentation][GridBundle]Wrong definition of sortable attribute

- src/Sylius/Bundle/ResourceBundle/Resources/config/services/integrations/translation.xml
make `sylius.translatable_entity_locale_assigner` public as is it retreived from the container by `ORMTranslatableListener`, trigging a deprecation warning in symfony 3.4.
unsure if this is a bug fix. shall i raise target 1.0?
> [ResourceBundle] make sylius.translatable_entity_locale_assigner public

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDriver.php
unsure if this is a bug fix. shall i raise target 1.0?
Symfony's `ContainerControllerResolver` is is triggering a deprecation warning on when retrieving controllers from the container because they are private by default. They should be public.
```
The "..." service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
```
> [ResourceBundle] make controller public by default

- src/Sylius/Bundle/AttributeBundle/composer.json
We use AttributeBundle as a standalone and since this commit https://github.com/Sylius/Sylius/commit/59b13758876f4a2ae519f97e5fac481c6154df90 we have issue about a missing lib ramsey/uuid.
I just added in the composer.json of the AttributeBundle
The lib is used in src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/Configuration/SelectAttributeChoicesCollectionType.php
> [AttributeBundle] Fixing composer.json for ramsey/uuid

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDriver.php
| Related tickets | ~
Resource controllers have the tag missing. This does not allow having dependencies injected into actions.
> [ResourceBundle] Add the controller tag

- docs/customization/factory.rst
Additionally added, more extensive documentation. Assures that the routing points to /admin, and that the simple product page is overwritten. 
Additionally bug fixing. Now we are really pointing to the simple page, instead of pointing to the configurable product page.
https://github.com/Sylius/Sylius/commit/9a99d2b597a5851cd6c3aefaf963cf32413de4ba
> [Documentation] Customizing Factory

- docs/api/customers.rst
| Branch?         | 1.0 (affects all)
According to the Customer API docs, "groups" fields is expected to be an array while it has a 1 to N relationship in DB, and it does not work if an array is passed.
> Fixed Customer API docs with invalid "groups" parameter

- src/Sylius/Bundle/CoreBundle/Fixture/BookProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxonExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/TaxonFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/TaxonFixtureTest.php
From Fixtures level we are not able to add images to Taxons as we can in Products. This PR adds missing configuration 😉
> [Fixtures] Creating images from array for Taxons

- docs/api/admin_users.rst
- tests/Controller/AdminUserApiTest.php
- tests/Responses/Expected/admin_user/create_response.json
It was quite frustrating to see such a big disrespect for this awesome creature :/
http://lotr.wikia.com/wiki/Balrog
To be precisely, we should refer to a specific Balrog's name ([Durin's Bane](http://lotr.wikia.com/wiki/Durin%27s_Bane) in this case), but it can be a little bit confusing, so it's good as it is right now :)
> Fix wrong Balrog of Morgoth name

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/PaymentMethodExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/PaymentMethodFixture.php
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/PaymentMethodFixtureTest.php
Not a real bug, but just a missing option. Default is still `null`, so it doesn't confuse as it's an optional text.
> Add PaymentMethod::instructions option to fixtures

- src/Sylius/Behat/Exception/NotificationExpectationMismatchException.php
- src/Sylius/Behat/Service/Accessor/NotificationAccessor.php
- src/Sylius/Behat/Service/Accessor/NotificationAccessorInterface.php
- src/Sylius/Behat/Service/NotificationChecker.php
- src/Sylius/Behat/Service/NotificationCheckerInterface.php
- src/Sylius/Behat/spec/Service/NotificationCheckerSpec.php
With previous implementation, `NotificationAccessor` was always returning the first found flash message, which was a little bit uncomfortable. New implementation should work like a charm, and make this service more reusable.
> [Behat] Handle multiple notifications in NotificationChecker

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Compiler/PrioritizedCompositeServicePass.php
| Branch?         | 1.0, 1.1
`PrioritizedCompositeServicePass` is general purpose code, so it shouldn't have those channel specific variable names.
I've some troubles creating PR against 1.0 or 1.1, so please commit however you need this.
> Cleanup PrioritizedCompositeServicePass definition name

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDriver.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/AbstractDoctrineDriver.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineORMDriver.php
- src/Sylius/Bundle/ResourceBundle/Tests/Resource/ResourceServicesTest.php
- tests/Resource/ResourceServicesTest.php
Since Symfony 3.4 services are made private by default. Getting them from the container explicitly is now deprecated, but not possible in Symfony 4 (which we're heading to).
> [Resource] Make sure Sylius resources services are public

- src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml
- src/Sylius/Component/Core/OrderProcessing/OrderAdjustmentsClearer.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderAdjustmentsClearerSpec.php
Due to the fact, that cleared adjustments types has been set as static array, after adding new adjustment type (that is also processed during checkout), it was necessary to implement whole new class (with very similar/the same implementation, but different static array) and override the service definition. With this change, only definition overriding is needed.
> [Adjustment] Inject adjustment types that shall be cleared

- features/order/managing_orders/filtering_orders_by_date.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Order/IndexPage.php
- src/Sylius/Behat/Page/Admin/Order/IndexPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/order.yml
- src/Sylius/Bundle/GridBundle/Form/DataTransformer/DateTimeFilterTransformer.php
- src/Sylius/Bundle/GridBundle/Form/Type/Filter/DateFilterType.php
- src/Sylius/Component/Grid/Filter/DateFilter.php
- src/Sylius/Component/Grid/spec/Filter/DateFilterSpec.php
| Related tickets | Fixes https://twitter.com/nickchambers/status/977964619787587585
Bug was reporter on Twitter 🐦 by Nick Chambers. I'm not 100% sure about this approach, as it requires providing default time in both form type and filter itself. Nevertheless, it works nice (as shown in scenario). I assume that proposed approach (`00:00` as default time for *from* and `23:59` as default time for *to*) should be appropriate for most cases :)
> [Grid] Filtering orders bug

- src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-auto-complete.js
- src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-product-auto-complete.js
We should be good to go for browser compatibility because `Array.prototype.filter()` has been supported since IE 9: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#Browser_compatibility and jQuery 3.x (which we're using) only supports IE 9+: https://jquery.com/browser-support/
> Fix JS error when autocomplete field is empty

- docs/customization/model.rst
In doctrine config the field flag is defined as nullable, so we should use nullable type in getter.
> Documentation - Use nullable return type

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/customer.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/order.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/product_review.yml
Removes some Symfony deprecation warnings.
> Quote usage of !!int  to remove deprecation warning

- src/Sylius/Bundle/AdminApiBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/PayumBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/UiBundle/Resources/config/services/controller.xml
| Branch?         | 1.0 (it's harmless to explicitly declare controller services as public)
| Bug fix?        | no (but it removes deprecation messages since Symfony 3.4)
Services are private by default since Symfony 3.4 (see https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default)
> Make sure controller services are public

- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceControllerSpec.php
| Related tickets | fixes #8539 
> Return event response for initialize update event

- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
| Bug fix?        | maybe? (to me invalid YAML syntax could be considered a bug)
1.1 because it requires Symfony 3.4
Symfony introduced invalid YAML syntax but they've since fixed it. This removes a deprecation message. See https://github.com/symfony/symfony/pull/22913
> Fix invalid YAML tag syntax

- UPGRADE-1.2.md
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
| Bug fix?        | no (but it removes a lot of deprecation messages)
| BC breaks?      | no? (only in app configuration)
> Disable deprecated "form mapping" feature in SonataCoreBundle

- docs/cookbook/images/images-on-entity.rst
| Bug fix?        | no (docs improvement)
Don't override `sylius.listener.images_upload`, so that we don't have to duplicate tags that might change at anytime.
> Declare a separate ImagesUploadListener service

- src/Sylius/Bundle/ChannelBundle/Collector/ChannelCollector.php
- src/Sylius/Bundle/CoreBundle/Collector/SyliusCollector.php
- src/Sylius/Bundle/ThemeBundle/Collector/ThemeCollector.php
This one fixes a deprecation messages:
```
User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Sylius\Bundle\ChannelBundle\Collector\ChannelCollector".
User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Sylius\Bundle\ThemeBundle\Collector\ThemeCollector".
User Deprecated: Implementing …
```
> Add reset method to DataCollectors, needed for SF4 compat

- src/Sylius/Bundle/AdminBundle/Gulpfile.js
- src/Sylius/Bundle/ShopBundle/Gulpfile.js
We should be fine for Node.js compatibility, since yarn doesn't support node < v4 anyway. And `for...of` with arrays has been supported since node v4: https://node.green/#ES2015-syntax-for--of-loops-with-arrays
> Fix sourcemaps

- package.json
- yarn.lock
Node.js 10 compatibility was introduced in node-sass [v4.9.0](https://github.com/sass/node-sass/releases/tag/v4.9.0)
> Update node-sass for compatibility with Node.js 10

- src/Sylius/Component/Core/OrderProcessing/OrderPaymentProcessor.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderPaymentProcessorSpec.php
The `Order::getPayments` method does not accept a `$state` property to filter payments so it would always remove all payments that are attached to it
> Fix removal of cart payments in OrderPaymentProcessor

- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/Product.orm.xml
Can set the product variants position in admin but no effect in public product page.
| Branch?         | 1.0, 1.1 or master 
> Fixed missing orderby in product variants

- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product_taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml
| Bug fix?        | kind of? (configuration)
Specify default `_format` in individual AJAX routes. If it is set at a higher level, it can never be overridden per route. See https://github.com/symfony/symfony/issues/10779
This fixes `sylius_admin_ajax_render_province_form`.
> [AdminBundle] Specify default _format in individual AJAX routes

- features/checkout/shipping_order/seeing_default_shipping_method_selected_based_on_shipping_address.feature
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutShippingContext.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPageInterface.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml
- src/Sylius/Component/Core/OrderProcessing/OrderShipmentProcessor.php
- src/Sylius/Component/Core/Resolver/DefaultShippingMethodResolver.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderShipmentProcessorSpec.php
- src/Sylius/Component/Core/spec/Resolver/DefaultShippingMethodResolverSpec.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/7965 |
Two bugs where involved in this issue:
1. `DefaultShippingMethodResolver` where returning only enabled shipping methods for channel, without considering their eligibility for proper zone.
2. When the shipment was already set on `Order` it was taken confidently, without checking does it's method is eligible for current state of the order.
It was especially frustrating when shipping step was skipped.
Current solution is not perfect (even more complexity in `OrderShipmentProcessor`) but better than not working at all 😄  🐃
> [Shipping][OrderProcessing] Default shipping method fixes

- src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Layout/centered.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Layout/sidebar.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/_stylesheets.html.twig
If there are more styles included through `@SyliusUi/_stylesheets.html.twig` (for example bootstrap from cdn) it causes duplicate includes of IE 9 polyfills.
> Moved IE css polyfills

- src/Sylius/Bundle/AddressingBundle/Form/Type/AddressType.php
Once the `$options['shippable']` is true, 'shippable' validation group is added persistently to the form type default validation groups and used subsequently despite the `$options['shippable']` value.
In case of `\Sylius\Bundle\CoreBundle\Form\Type\Checkout\AddressType` which has 2 fields of that type, both of them will have validation groups including `shippable`, even if the 2nd one (`billingAddress`) does not have `'shippable' => true` option.
Moreover, in case of more than 1 field with `'shippable' => true`, validation groups will contain an entry of `shippable` group per …
> [Addressing]  Fix default validation groups of AddressType

- gulpfile.babel.js
Since it was unnecessarily added in #9405, and not properly implemented anyway.
> Remove vendorPath command-line argument from root gulpfile

- docs/book/installation/installation.rst
| Related tickets | #9455
With Symfony 4 `--docroot=web` need to be added to server:start command
https://github.com/Sylius/Sylius/issues/9455
> [docs] fix server:start command

- docs/contributing/code/patches.rst
| Related tickets | fixes #9445 
> [Documentation] Fix deprecated link to repository

- docs/components_and_bundles/bundles/SyliusResourceBundle/create_resource.rst
- docs/components_and_bundles/bundles/SyliusResourceBundle/delete_resource.rst
- docs/components_and_bundles/bundles/SyliusResourceBundle/update_resource.rst
Pretty straight-forward documentation right now, but it's still better than nothing 😄
> Document "event" option in resource routing

- src/Sylius/Behat/Page/Shop/Product/IndexPage.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_main.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_horizontalList.html.twig
This is a small improvement to how Semantic UI's cards are rendered with the ShopBundle's default layouts.  Right now they're used within `.ui.grid` containers, but a `.ui.cards` container can also be used as a grid and handles rendering a little better overall (especially with ensuring the cards are equal heights, see below screenshots).
Current demo homepage:
Homepage with patch:
> Improve use of Semantic's cards in frontend

- .github/stale.yml
Stalebot is a great tool, that helps a lot with some old, deprecated issues and pull requests. However, sometimes it's quite frustrating when we have the issue that needs to be kept open, but currently, there is no time or possibility to process it (2 examples from the recent past: https://github.com/Sylius/Sylius/issues/6580, https://github.com/Sylius/Sylius/issues/5846). 
I propose to introduce a new label, that would be used in such situations. I don't know is it the best option (even the label name is a neologism, I think 😄), but could be good enough to try. The only thing we must …
> Make Stalebot less annoying

- src/Sylius/Behat/Context/Api/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingTaxonsContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
- src/Sylius/Behat/Page/Admin/Channel/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Order/UpdatePage.php
- src/Sylius/Behat/Page/SymfonyPage.php
- src/Sylius/Bundle/ShopBundle/Router/LocaleStrippingRouter.php
- src/Sylius/Bundle/ThemeBundle/Loader/CircularDependencyChecker.php
- src/Sylius/Component/Core/Test/Services/DefaultChannelFactory.php
- src/Sylius/Component/Promotion/Model/Promotion.php
Php Inspections (EA Ultimate): new findings
> [minor] SCA

- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
Right now usage of `sylius.admin.dashboard.after_content` Sonata block bundle will result in following message:
which is result of:
Maybe we should test blocks somehow but right now I do not have time to figure it our :(
> [HOTFIX] Missing configuration for channel in sonata

- docs/cookbook/shop/custom-redirect-after-cart-add-action.rst
the name of sylius-add-to-cart.js file was misspelled.
| Related tickets | there is not any
> the name of file was wrong in docu

- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-notification.js
On admin login page, sylius-notifications.js tries to use toString() on an undefined variable, this fix adds a check before the call to prevent javascript from throwing TypeError.
This bug is present in 1.1 but variable has a different name: data in 1.1 and response in 1.2.
| Related tickets | None
> Fix a TypeError on admin login page.

- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_taxonomy.html.twig
It could be used for more than taxons, so the name of the data-* properties should not include "taxon".
> Use generic names for data-* properties in sylius-lazy-choice-tree.js

- src/Sylius/Bundle/CoreBundle/Fixture/BookProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/MugProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/ProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/StickerProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/TshirtProductFixture.php
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/ProductFixtureTest.php
It wasn't actually working with `ProductExampleFactory`, but the tests don't catch it.
> Fix wrong type for "images" option in ProductFixture

- src/Sylius/Bundle/ThemeBundle/README.md
Since it is usable in 3.x and 4.x too, this info was wrong.
| Bug fix?        | yes - only docs
> Remove Symfony Version from README.md

- docs/cookbook/images/images-on-entity.rst
This part of the doc was lacking strict PHP typing.
| Branch?         | 1.0, 1.1, 1.2
Adding strict typing for the cookbook in images.
> Adding strict typing for PHP classes in images doc

- src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
| Branch?         | 1.0+
`$connection->getDatabase()` returns null in case the database name has not being specified ( example : using sqlite )
> Ensure that DatabaseSetupCommandsProvider::getDatabaseName() returns a string.

- src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerChoiceType.php
Change 'choice_label' to use a closure that renders customers full name and e-mail.
Nor field `name`, nor method `getName` exist in Customer entity
Should go to 1.0, 1.1 and master
| Related tickets | None
> Field used for label does not exist

- features/account/resetting_password.feature
- features/user/managing_customers/resetting_customer_password.feature
- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
> [Behat] Grammar fix

- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_items.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectPayment/_payment.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectShipping/_form.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectShipping/_shipment.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_variants.html.twig
When using Sylius with [PHP-PM](https://github.com/php-pm/php-pm), it cannot be guaranteed that the elements of an ArrayCollection will have continuous indexes (for example if you add two items to the cart, then remove one then add a third one the final items collection will have indexes 0 and 2). This sometimes breaks Sylius in Twig templates where loop.index0 is used because it may not match the current item index.
This PR fixes the issue by using the actual index within the loop instead of loop.index0.
> Remove instances of loop.index0

- src/Sylius/Bundle/CoreBundle/Resources/config/services/context.xml
- src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
ShopBasedCartContext keeps an instance of the cart internally. When using [PHP-PM](https://github.com/php-pm/php-pm), this attribute needs to be reset at the end of each request otherwise unexpected behaviors happen. This solution uses the kernel.reset tag introduced specifically for this purpose in https://github.com/symfony/symfony/issues/23984
> Fix ShopBasedCartContext resetting

- src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php
- src/Sylius/Bundle/CoreBundle/spec/OAuth/UserProviderSpec.php
If the user tries to log in with Facebook but chooses to not give their email, Sylius crashes because it attempts to insert a user with null email into the database. This PR fixes this by checking this case in the user provider.
> Handle null email in oauth login

- src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/ChannelFixtureTest.php
In this pull request the switch for account verification in the channel entity is now configurable in the Sylius fixtures.
> Added account verification option to fixture parser

- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-product-images-preview.js
| Bug fix?        | in rare cases
| Related tickets | fixes #9595
`$el.on(event, selector, handler)` attaches event handler to the `$el` element. If event is triggered on the `$el`, it is checked that element that triggered the event (child of `$el`) matches given `selector`. In case the element matches the `selector`, `handler` is called - otherwise nothing happens.
So it's not necessary to attach event handler for each element - it's enough to attach it to some parent and specify `selector` of childs for which the `handler` should be called. See https://api.jquery.com/on/#on-events-selector-data-handler for details.
> Simplify code of `sylius-product-images-preview` module

- app/migrations/Version20161223091334.php
| Related tickets | 0
When running Migrations on MySQL 8, one query causes an SQL error:
> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'row_number FROM sylius_product INNER JOIN sylius_product' at line 2
The name has to be properly quoted for MySQL 8 where `ROW_NUMBER` is a reserved identifier.
> Quote row_number identifier for MySQL queries

- src/Sylius/Bundle/ThemeBundle/Translation/Finder/TranslationFilesFinder.php
Where `\` is used instead of `/`.
| Related tickets | fixes #5289
> Theme translation : Add support of Windows OS

- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/archive.html.twig
| Branch?         | 1.0, 1.1, 1.2, master
Hi,
I was adding `ArchivableInterface` to my `ProductVariant`, when I've noticed, that `archive.html.twig` can't work on urls with multiple parameters, like `productId`, `id`, e.g. `/admin/products/206/variants/195`
Solution is copy-pasted from `delete.html.twig`, which doesn't have such problem. https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/delete.html.twig
Works for me on `shipping-methods` and custom `product/product-variants` views.
Let me know, if something is unclear.
Cheers.
> Fix Grids archive ability to work on multi-param urls

- docs/customization/form.rst
Because probably the customization goes into the end application and the proper location for the service config file is `app/config/services.yml`. Moreover if the extension is registered in `AppBundle/Resources/config/services.yml` it doesn't work if that file is not loaded through the AppBundle DI extension (https://symfony.com/doc/current/bundles/extension.html).
> [Docs] Fixes services file path

- app/AppKernel.php
- app/TestAppKernel.php
- behat.yml.dist
- composer.json
- src/Sylius/Behat/Resources/config/profiles/default.yml
The change in Behat configuration made Sylius-Standard < 1.3.0 applications to fail, as there is no `Kernel` class.
> Add backwards compatibility layer for Behat configuration referenced in Sylius-Standard

- app/TestAppKernel.php
- app/config/_container_deprecation.php
- app/config/_routing_deprecation.php
- app/config/routing.yml
- app/config/routing_dev.yml
- app/config/security.yml
Files `app/config/routing.yml`, `app/config/routing_dev.yml` and `app/config/security.yml` are referenced in PluginSkeleton. This PR provides a backwards compatibility layer for them.
> Provide a BC layer for files in "app/config/" referenced by PluginSkeleton

- app/config/routing.yml
- app/config/routing_dev.yml
Symfony's Routing component does not support parameters while importing so that the current implementation didn't work correctly. Related to #9672.
> Fix routing BC layer

- .env.dist
- .env.test.dist
| Related tickets | potentially fixes https://github.com/Sylius/Sylius/issues/9680
Sylius was using `APP_ENV=dev` as default in all environments 😕
> Fix resolving environment variables

- src/Sylius/Bundle/GridBundle/composer.json
- src/Sylius/Component/Resource/composer.json
Pagerfanta 2.0 only changes [minimum PHP version](https://github.com/whiteoctober/Pagerfanta/releases/tag/v2.0.0), which shouldn't cause a major release btw.
> Allow to use Pagerfanta in both ^1.0 and ^2.0

- composer.json
The ultimate goal is to get rid of the application from Sylius/Sylius without sacrificing the DX while contributing. However, we should allow one not to use Symfony Flex while using Sylius.
> Move symfony/flex dependency to require-dev

- docs/components_and_bundles/bundles/SyliusCustomerBundle/summary.rst
- docs/components_and_bundles/bundles/SyliusInventoryBundle/summary.rst
- docs/components_and_bundles/bundles/SyliusOrderBundle/summary.rst
- docs/components_and_bundles/bundles/SyliusPromotionBundle/summary.rst
- docs/components_and_bundles/components/Grid/summary.rst
- docs/components_and_bundles/components/Resource/summary.rst
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/9499
That was a tough one 😄
> PHPSpec version not specified in docs

- .github/stale.yml
| Related tickets | mentioned in https://github.com/Sylius/Sylius/issues/9503#issuecomment-422750965
I think that if we select some issue to our Roadmap, it should not be staled/closed until its solved.
> Do not stale issues selected to Roadmap

- UPGRADE-1.3.md
As far as I see it's all you should do, for both Symfony 3.4 and 4.1 based application 🐃 It would be nice if somebody checks it on some real application - I've only followed this guide on regular Sylius-Standard and some application with really few customizations.
And as mentioned in the file, changing directory structure is not required, but should be recommended IMO - but it can be written after checking the most trivial part of upgrade :)
Cheers 🍻
> Minimalistic UPGRADE path from Sylius 1.2 to 1.3

- UPGRADE-1.3.md
- composer.json
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
| Related tickets | replaces https://github.com/Sylius/Sylius/pull/9735
As we remove `sylius-labs/sensio-distribution-bundle` we need to add `sensiolabs/security-checker` to make command `security:check` available
> Make Flex recipes to be based on Sylius possible (with build passing)

- docs/api/introduction.rst
| Related tickets | n/A
It was obviously a bad copy/paste.
> Fix the "REST APIs" link in the documentation

- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
| Related tickets | [#9365](https://github.com/Sylius/Sylius/issues/9365)
Before this fix was checking which checkbox were checked but is loading the tree in lazy mode, so if you didn't load some part of the tree where you had taxons checked, those taxons were lost when saving.
> [Admin][Product edit] Change the value of the taxons individually when checked/unchecked.

- features/account/resetting_password.feature
- src/Sylius/Behat/Context/Setup/UserContext.php
- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
- src/Sylius/Behat/Page/Shop/Account/RequestPasswordRequestResetPage.php
- src/Sylius/Behat/Page/Shop/Account/RequestPasswordResetPage.php
- src/Sylius/Behat/Page/Shop/Account/RequestPasswordResetPageInterface.php
- src/Sylius/Behat/Page/Shop/Account/ResetPasswordPage.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/shop/account.xml
| Related tickets | fixes #9731 
I've changed a behat page and its interface cause I've renamed an existing one... If you have a better idea, I'm opened. But the old name was confusing with missing one.
> [Behat] Changing my account password with token I received scenario

- src/Sylius/Bundle/GridBundle/Doctrine/ORM/ExpressionBuilder.php
- src/Sylius/Component/Grid/Filter/DateFilter.php
- src/Sylius/Component/Grid/Filter/MoneyFilter.php
- src/Sylius/Component/Grid/spec/Filter/DateFilterSpec.php
- src/Sylius/Component/Grid/spec/Filter/MoneyFilterSpec.php
Fixes #9730.
The behaviour has been inconsistent in the ExpressionBuilder methods.
> [GridBundle] Do not put unnecessary "andWhere" in ExpressionBuilder

- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-province-field.js
Fixes #9134. Not the most elegant solution, but it seems like that whole province-related logic needs some love. Happy resolving merge conflicts to the future me!
> Fix doubled province id on checkout addressing page

- src/Sylius/Component/Core/composer.json
Fixes #7391. `symfony/http-foundation` has been already required through `sylius/user` -> `symfony/security`.
> [Core] Make implicit dependency explicit

- UPGRADE-1.4.md
- features/locale/handling_different_locales_on_multiple_channels.feature
- features/locale/switching_current_locale.feature
- src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
- src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelper.php
- src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelperInterface.php
- src/Sylius/Bundle/LocaleBundle/spec/Templating/Helper/LocaleHelperSpec.php
Fixes #7878, closes #7887.
I reimplemented it instead of using #7887 as this approach lets you specify the locale code in the template by using `{{ 'en_US'|sylius_locale_name('pl_PL') }}`.
Shop:
Admin:
> Show localised locale names

- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/create.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/update.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/changePassword.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/profileUpdate.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/requestPasswordReset.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/resetPassword.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/summary.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/address.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/complete.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectPayment.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectShipping.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Contact/request.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Form/theme.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_addToCart.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/create.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/login.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/register.html.twig
I created the file `Form/theme.html.twig` in `SyliusShopBundle` in order to be able to override this template in theme and only impact the front. With that, we can customize our shop without break the admin render.
I changed the form theme called in `SyliusShopBundle` templates in order to call the created file.
See the [Slack conversation](https://sylius-devs.slack.com/archives/C3EGDG9LY/p1538663226000100)
Thank you for your amazing work on Sylius 🚀
If you want more information, ask me 👀
> Add SyliusShopBundle form theme

- docs/components_and_bundles/bundles/SyliusFixturesBundle/architecture.rst
- docs/components_and_bundles/bundles/SyliusFixturesBundle/custom_fixture.rst
- docs/components_and_bundles/bundles/SyliusFixturesBundle/custom_listener.rst
- src/Sylius/Bundle/FixturesBundle/DependencyInjection/Compiler/FixtureRegistryPass.php
- src/Sylius/Bundle/FixturesBundle/DependencyInjection/Compiler/ListenerRegistryPass.php
- src/Sylius/Bundle/FixturesBundle/DependencyInjection/SyliusFixturesExtension.php
- src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/Compiler/FixtureRegistryPassTest.php
- src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/Compiler/ListenerRegistryPassTest.php
- src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/DummyFixture.php
- src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/DummyListener.php
- src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/SyliusFixturesExtensionTest.php
| New feature?    | kindda
Improve DX by bringing autoconfiguration to services implementing the `Sylius\Bundle\FixturesBundle\Fixture\FixtureInterface`. This allow developper to omit the `sylius_fixtures.fixture` tag on their service definitions (and even omit the whole definition if autowiring is on).
I would suggest to put the tag value in a constant of the `FixtureRegistryPass`, seems like a good idea to you ?
> [FixtureBundle] Add autoconfiguration for instance of FixtureInterface

- docs/contributing/code/bdd.rst
- src/Sylius/Bundle/CoreBundle/Command/InstallCommand.php
- src/Sylius/Bundle/ThemeBundle/Command/AssetsInstallCommand.php
| Bug fix?        | No
| New feature?    | No
| BC breaks?      | No
| Deprecations?   | No
| Related tickets | No
----
This PR removes a few leftover references to Symfony 3. `app.php` and `app_dev.php` are no longer used and `web` has been renamed to `public`.
> Removed leftover Symfony3 references

- docs/components_and_bundles/bundles/SyliusOrderBundle/processors.rst
- src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/RegisterCartContextsPass.php
- src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/RegisterProcessorsPass.php
- src/Sylius/Bundle/OrderBundle/DependencyInjection/SyliusOrderExtension.php
- src/Sylius/Bundle/OrderBundle/Tests/DependencyInjection/SyliusOrderExtensionTest.php
| New feature?    | 
This is made to improve DX by allowing auto-configuration (and thus, autowiring) of services implementing the `CartContextInterface` and the `OrderProcessorInterface` (as for the FixtureBundle - see #9789).
The PR also contains a "fix" about creating dummy classes for the FixtureBundle : phpUnit does that very well and it costs much less lines of codes :)
> [OrderBundle] Add autoconfiguration for cart contexts and order processor services.

- docs/components_and_bundles/bundles/SyliusFixturesBundle/builtin_listeners.rst
The documentation has not been updated after renaming the `orm_purger` option.
> `purge_mode` has been rename to `mode`

- src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-product-attributes.js
As class addition was missing and in Behat [we wait for form "loading" class to be removed](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php#L90), it could sometimes result in failed scenario (see https://travis-ci.org/Sylius/PluginSkeleton/builds/438197025)... and is just incorrect :)
> Improve product attributes JS

- docs/customization/controller.rst
It seems that the Custom homepage controller service needs to be marked as public as well, otherwise it cannot be fetched from the container. 
It looks like there is a default service configuration for the controllers in config.yml which is supposed to make public all controllers in AppBundle but it doesn't resolve this issue
| Branch?         | 1.2, 1.3 or master 
> Custom homepage controller as public service

- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
Avoid *SyntaxError: Unexpected token: operator (>)* error with uglify in production mode.
Initial commit was b376768 "Filter blank values" (taxon selection in tree when product edit).
> Fix gulp uglify error with arrow functions

- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Index/_content.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Grid/_default.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/index.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Grid/_default.html.twig
I created the file `Grid/_default.html.twig` in `SyliusShopBundle` in order to be able to override this template in theme and only impact the front. With that, we can customize our shop without break the admin render.
I changed the grid called in `ShopBundle/Resources/views/Account/Order/index.html.twig`.
Thank you for your amazing work on Sylius 🚀
If you want more information, ask me 👀
> Use SyliusShop grid default template

- src/Sylius/Bundle/ShopBundle/Resources/views/Account/layout.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Menu/simple.html.twig
I created the file `Menu/simple.html.twig` in `SyliusShopBundle` in order to be able to override this template in theme and only impact the front. With that, we can customize our shop without break the admin render.
I changed the menu called in `ShopBundle/Resources/views/Account/layout.html.twig`.
The `Menu/simple.html.twig` is only called in this template. In the future, if I want to use it on admin and/or in front I will be able to customize it.
Thank you for your amazing work on Sylius 🚀
If you want more information, ask me 👀
> Use SyliusShop simple menu template

- docs/cookbook/entities/custom-model.rst
Sensio Generator Bundle does not support Symfony 4, and we should use the Maker Bundle as it's stated here https://github.com/sensiolabs/SensioGeneratorBundle
| Branch?         | 1.2, 1.3 or master 
> SensioGeneratorBundle vs SymfonyMakerBundle

- docs/book/configuration/locales.rst
`getAvailableLocalesCodes` return `string[]` not an object
| Branch?         | 1.2 1.3
| Related tickets | unknown
> Wrong usage of returned data
