- app/migrations/Version20160830085457.php
> [Migrations] Add missing migrations after removing metadata and reports

- src/Sylius/Bundle/UserBundle/Command/DemoteUserCommand.php
on #5619, I see another typo error. My bad :) 
So this PR fix that.
> Fix a typo in DemoteUserCommand

- docs/book/shipments.rst
> [Documentation] Concepts: Shipments

- docs/book/addresses.rst
> [Documentation] Concepts: Addresses

- docs/book/payments.rst
> [Documentation] Concepts: Payments

- docs/book/adminuser.rst
- docs/book/index.rst
- docs/book/map.rst.inc
> [Documentation] Concepts: AdminUser

- features/locale/channel_independent_translatable_entities_locales.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingTranslatableEntitiesContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites/ui/locale/managing_locales.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/context.xml
- src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php
- src/Sylius/Bundle/ResourceBundle/Form/Type/ResourceTranslationsType.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/translation.xml
- src/Sylius/Bundle/ResourceBundle/spec/Form/Type/ResourceTranslationsTypeSpec.php
- src/Sylius/Bundle/ResourceBundle/test/app/config/config.yml
- src/Sylius/Component/Core/Provider/ChannelBasedLocaleProvider.php
- src/Sylius/Component/Core/spec/Provider/ChannelBasedLocaleProviderSpec.php
- src/Sylius/Component/Locale/Provider/ImmutableLocaleProvider.php
- src/Sylius/Component/Locale/Provider/LocaleProvider.php
- src/Sylius/Component/Locale/Provider/LocaleProviderInterface.php
- src/Sylius/Component/Locale/spec/Provider/ImmutableLocaleProviderSpec.php
- src/Sylius/Component/Locale/spec/Provider/LocaleProviderSpec.php
> [Core] Translatable entities should not rely on current channel's locales and available ones

- features/locale/channel_independent_translatable_entities_locales.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingTranslatableEntitiesContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites/ui/locale/managing_locales.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/context.xml
- src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/translation.xml
> [Core] Translatable entities should not rely on current channel's locales

- features/account/registration.feature
- src/Sylius/Behat/Context/Ui/Shop/RegistrationContext.php
- src/Sylius/Component/Core/Test/Services/EmailChecker.php
- src/Sylius/Component/Core/Test/Services/EmailCheckerInterface.php
> [Behat] Checked whether a customer receives the welcoming email

- features/cart/shopping_cart/removing_cart_item.feature
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/cart/shopping_cart.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/_widget.html.twig
- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/Model/OrderInterface.php
- src/Sylius/Component/Core/OrderProcessing/OrderShipmentProcessor.php
- src/Sylius/Component/Core/spec/Model/OrderSpec.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderShipmentProcessorSpec.php
> [Cart] Refactor removing cart item from cart

- features/account/subscribing_newsletter_during_registration.feature
- src/Sylius/Behat/Context/Ui/Shop/RegistrationContext.php
- src/Sylius/Behat/Page/Shop/Account/RegisterPage.php
- src/Sylius/Behat/Page/Shop/Account/RegisterPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/CoreBundle/Form/Type/CustomerRegistrationType.php
- src/Sylius/Bundle/CoreBundle/spec/Form/Type/CustomerRegistrationTypeSpec.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Register/_form.html.twig
> [Registration] Subscribe to the newsletter during registration

- features/account/subscribing_newsletter_during_registration.feature
- features/user/managing_customers/seeing_customer_details.feature
- src/Sylius/Behat/Context/Setup/CustomerContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Context/Ui/Shop/RegistrationContext.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPage.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPageInterface.php
- src/Sylius/Behat/Page/Shop/Account/RegisterPage.php
- src/Sylius/Behat/Page/Shop/Account/RegisterPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/show.html.twig
- src/Sylius/Bundle/CoreBundle/Form/Type/CustomerRegistrationType.php
- src/Sylius/Bundle/CoreBundle/spec/Form/Type/CustomerRegistrationTypeSpec.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Register/_form.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Admin][Customer] Checking subscribed to the newsletter on customer show page

- features/user/managing_customers/editing_customer.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Page/Admin/Customer/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Customer/UpdatePageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/_form.html.twig
> [Admin][Customer] Making customer subscribed to the newsletter

- features/account/customer_account/subscribing_newsletter.feature
- features/account/subscribing_newsletter_during_registration.feature
- features/user/managing_customers/seeing_customer_details.feature
- src/Sylius/Behat/Context/Setup/CustomerContext.php
- src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
- src/Sylius/Behat/Context/Ui/Shop/RegistrationContext.php
> [Behat] Fix some steps associated with newsletter subscription

- src/Sylius/Bundle/CoreBundle/Handler/CartLocaleChangeHandler.php
> Fix typo in CartLocaleChangeHandler Exception

- src/Sylius/Bundle/CoreBundle/Form/Type/CartType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/form.xml
> [Core] Remove unneeded listener in CartType

- features/user/managing_customers/editing_customer.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
> [Behat] Fix step name in editing customer

- src/Sylius/Bundle/CartBundle/Controller/CartItemController.php
I'm pretty sure, that this event should be dispatched also for not html requests.
> [Cart] Fix event and flush order in CartItemController

- src/Sylius/Behat/Context/Setup/AdminSecurityContext.php
> [Behat] Missing constructor typehint

- app/config/security.yml
- src/Sylius/Bundle/UserBundle/Resources/config/services.xml
> [Security][Kinda] Typos fixes never end

- composer.json
- composer.lock
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/checkout.yml
- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/AddDefaultBillingAddressOnOrderFormSubscriber.php
- tests/Controller/CheckoutAddressingApiTest.php
- tests/Controller/CheckoutApiTest.php
- tests/Controller/CheckoutApiTestCase.php
- tests/Controller/CheckoutCompleteApiTest.php
- tests/Controller/CheckoutPaymentApiTest.php
- tests/Controller/CheckoutReaddressingApiTest.php
- tests/Controller/CheckoutReselectingPaymentApiTest.php
- tests/Controller/CheckoutReselectingShippingApiTest.php
- tests/Controller/CheckoutShippingApiTest.php
- tests/DataFixtures/ORM/resources/checkout.yml
- tests/DataFixtures/ORM/resources/customers.yml
- tests/Responses/Expected/checkout/addressed_order_response.json
- tests/Responses/Expected/checkout/addressing_invalid_customer.json
- tests/Responses/Expected/checkout/addressing_validation_failed_billing_address.json
- tests/Responses/Expected/checkout/addressing_validation_failed_shipping_address.json
- tests/Responses/Expected/checkout/complete_invalid_order_state.json
- tests/Responses/Expected/checkout/completed_order_response.json
- tests/Responses/Expected/checkout/payment_invalid_order_state.json
- tests/Responses/Expected/checkout/payment_selected_order_response.json
- tests/Responses/Expected/checkout/payment_validation_failed.json
- tests/Responses/Expected/checkout/readdressing_response.json
- tests/Responses/Expected/checkout/reselect_payment_response.json
- tests/Responses/Expected/checkout/reselect_shipping_response.json
- tests/Responses/Expected/checkout/shipping_invalid_order_state.json
- tests/Responses/Expected/checkout/shipping_selected_order_response.json
- tests/Responses/Expected/checkout/shipping_validation_failed.json
> [API] Checkout API rework

- docs/bundles/SyliusAddressingBundle/installation.rst
- docs/bundles/SyliusAttributeBundle/installation.rst
- docs/bundles/SyliusMailerBundle/installation.rst
- docs/bundles/SyliusOrderBundle/installation.rst
- docs/bundles/SyliusSettingsBundle/installation.rst
- docs/bundles/SyliusShippingBundle/installation.rst
- docs/bundles/SyliusTaxationBundle/installation.rst
- docs/bundles/SyliusTaxonomyBundle/installation.rst
- docs/bundles/SyliusVariationBundle/installation.rst
| Related tickets | fixes #1595, partially #3750
As sugested by patie here: https://github.com/Sylius/Sylius/issues/1595
#1595 - Resource bundle missing state machine
#3750 - Merge Translation & TranslationBundle into Resource
#3778 - Merge Translation into Resource + some clean ups
#4633 - dependency on a non-existent service
> Docs - fixing dependencies in AppKernel

- src/Sylius/Behat/Context/Setup/AdminUserContext.php
- src/Sylius/Behat/Context/Setup/UserContext.php
> [Behat][Setup][Users] Create only enabled accounts

- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
`factory-service` / `factory-method` on `service` is deprecated
> [Core] Improve factories usage in DI

- src/Sylius/Bundle/AttributeBundle/EventListener/LoadMetadataSubscriber.php
- src/Sylius/Bundle/CartBundle/Twig/CartExtension.php
- src/Sylius/Bundle/ContentBundle/Form/Type/ImagineBlockType.php
- src/Sylius/Bundle/MoneyBundle/Form/Type/MoneyType.php
- src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentGatewayChoiceType.php
- src/Sylius/Bundle/PricingBundle/Form/Extension/PriceableTypeExtension.php
- src/Sylius/Bundle/PricingBundle/Form/Type/CalculatorChoiceType.php
- src/Sylius/Bundle/PricingBundle/Templating/Helper/PricingHelper.php
- src/Sylius/Bundle/PricingBundle/Twig/PricingExtension.php
- src/Sylius/Bundle/ProductBundle/Validator/ProductUniqueValidator.php
- src/Sylius/Bundle/PromotionBundle/Form/DataTransformer/CouponToCodeTransformer.php
- src/Sylius/Bundle/ResourceBundle/Twig/ResourceExtension.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/CalculatorChoiceType.php
- src/Sylius/Bundle/TaxationBundle/Form/Type/CalculatorChoiceType.php
- src/Sylius/Bundle/TaxationBundle/Form/Type/TaxCategoryChoiceType.php
- src/Sylius/Bundle/TaxonomyBundle/Form/EventListener/BuildTaxonFormSubscriber.php
- src/Sylius/Component/Payment/Model/Payment.php
- src/Sylius/Component/Pricing/Calculator/DelegatingCalculator.php
> [DocBlocks] Clean up obvious comments.

- src/Sylius/Bundle/ChannelBundle/DependencyInjection/Compiler/PrioritizedCompositeServicePass.php
> [Channel] Add missing type hints

- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Transform/ProductVariantContext.php
> [Behat] Fixes in Order and ProductVariant contexts

- features/order/managing_orders/seeing_orders_currency_on_index.feature
- features/order/managing_orders/seeing_orders_currency_with_different_exchange_rates_on_index.feature
- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Resources/config/suites/ui/order/managing_orders.yml
> [Behat] Scenarios for seeing orders totals in exchange rate of their currency on index

- features/order/managing_orders/seeing_orders_currency_on_index.feature
- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
> [Behat] Scenarios for seeing orders in different currencies on index

- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_promotion.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Checkout] Add missing translation

- docs/book/promotions.rst
> [Documentation] Concepts: Promotions

- features/inventory/cart_inventory/inability_of_adding_a_product_with_insufficient_stock.feature
- features/inventory/cart_inventory/prevent_buying_more_products_than_available_in_a_stock.feature
- features/inventory/cart_inventory/verify_inventory_quantity_when_updating_carty_summary.feature
- features/inventory/checkout_inventory/validating_product_quantity_on_checkout_complete.feature
- features/inventory/prevent_buying_more_products_than_available_in_a_stock.feature
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
- src/Sylius/Behat/Page/Shop/Product/ShowPage.php
- src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/ui/inventory/cart_inventory.yml
- src/Sylius/Behat/Resources/config/suites/ui/inventory/checkout_inventory.yml
- src/Sylius/Bundle/ShopBundle/Resources/private/js/semantic-ui-api-actions.js
- src/Sylius/Bundle/ShopBundle/Resources/private/js/verification-of-quantity-during-adding-to-cart.js
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_addToCart.html.twig
> [Cart][Inventory] Verify quantity of units on adding to cart 

- features/taxonomy/managing_taxons/removing_images_of_taxon.feature
- src/Sylius/Behat/Context/Setup/TaxonomyContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
> [Taxon] Removing images of a taxon

- src/Sylius/Bundle/SettingsBundle/Doctrine/EventListener/ParameterTransformerListener.php
- src/Sylius/Bundle/SettingsBundle/Resources/config/services.xml
> Revert "[Settings] Do not inject container to ParameterTransformerListener"

- src/Sylius/Bundle/CoreBundle/Fixture/BookProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/MugProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/StickerProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/TshirtProductFixture.php
| Related tickets | fixes #5495
> [Core] Make all codes lowercase in new fixtures

- features/checkout/being_able_to_modify_remaining_steps.feature
- features/checkout/placing_an_order_after_moving_back_in_checkout.feature
> [Checkout][Behat] Split checkout features

- features/product/managing_product_variants/browsing_product_variants.feature
- features/product/managing_product_variants/disable_or_enable_inventory_on_product_variant.feature
- features/product/managing_products/disable_or_enable_inventory_on_product.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Transform/ProductVariantContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
- src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_details.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Field/inventory.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_details.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Admin][Product] Enable tracking

- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/summary.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/_footer.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/_header.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/index.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_associations.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_inventory.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
| Bug fix?           | no
| New feature?   | no
| Related tickets | #3564
| License           | MIT
> [Shop] HTML5 conformance and Symfony deprecations

- src/Sylius/Component/Core/OrderCheckoutTransitions.php
Cleanup unused checkout transitions next to https://github.com/Sylius/Sylius/pull/5956/files
> Cleanup unused OrderCheckoutTransitions

- features/order/managing_orders/seeing_order_currency_on_show.feature
> [Behat] Seeing order prices in it's currency on details page

- features/order/managing_orders/seeing_order_currency_on_show.feature
> [Critical] Fixed build failing due to unresolved behat step

- features/account/verification/email_verification.feature
- features/order/managing_orders/shipping_order.feature
- src/Sylius/Behat/Context/Ui/EmailContext.php
- src/Sylius/Component/Core/Test/Services/EmailChecker.php
- src/Sylius/Component/Core/Test/Services/EmailCheckerInterface.php
| Related tickets | fixes #5932 
> [Behat] EmailChecker upgrades

- src/Sylius/Bundle/ThemeBundle/Twig/ThemeFilesystemLoader.php
| Related tickets | #5958, #6067 
> [Theme] fix bc break in templates loading, add real template existence check

- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Admin][Translation] Add translation for editing administrator

- src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
- src/Sylius/Bundle/UiBundle/Resources/views/Menu/sidebar.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Menu/simple.html.twig
| Related tickets | fixes #5942 
Based on #5944
> [Ui] Small frontend fixes

- features/cart/shopping_cart/adding_product_with_variants_to_cart.feature
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Product/_variant.html.twig
| Related tickets | fixes #6076 
> [Shop] Made sure item's variant code is displayed

- app/migrations/Version20160914110913.php
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
- src/Sylius/Component/Core/Model/ProductVariant.php
- src/Sylius/Component/Core/Model/ProductVariantInterface.php
> [Core] Removed the 'sold' field from ProductVariant

- src/Sylius/Component/Core/Model/AdminUser.php
> [User] Do not redeclare roles property on AdminUser

- features/order/managing_orders/deleting_order.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Resources/config/suites/domain/order/managing_orders.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_actions.html.twig
> [Order][Admin] Remove possibility to delete an order

- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectShipping/_form.html.twig
- tests/Controller/CheckoutApiTestCase.php
- tests/Controller/CheckoutCompleteApiTest.php
- tests/Controller/CheckoutPaymentApiTest.php
- tests/Controller/CheckoutShippingApiTest.php
Fix current failing master build. It is not a best solution, but the fastest one.
> [HOTFIX] [CRITICAL] Fix master build

- src/Sylius/Bundle/TaxationBundle/Resources/config/driver/doctrine/orm.xml
- src/Sylius/Bundle/TaxationBundle/Resources/config/services.xml
> [Taxation] Remove .class parameters

- src/Sylius/Bundle/TaxonomyBundle/Resources/config/driver/doctrine/mongodb-odm.xml
- src/Sylius/Bundle/TaxonomyBundle/Resources/config/driver/doctrine/orm.xml
- src/Sylius/Bundle/TaxonomyBundle/Resources/config/services.xml
> [Taxonomy] Remove .class parameters

- features/checkout/prevent_starting_checkout_with_empty_cart.feature
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Bundle/CoreBundle/Checkout/CheckoutResolver.php
- src/Sylius/Bundle/CoreBundle/Checkout/CheckoutStateUrlGenerator.php
- src/Sylius/Bundle/CoreBundle/Checkout/CheckoutStateUrlGeneratorInterface.php
- src/Sylius/Bundle/CoreBundle/spec/Checkout/CheckoutStateUrlGeneratorSpec.php
| Related tickets | https://github.com/Sylius/Sylius/issues/5988
> [Shop][Checkout] Prevent starting checkout with empty cart

- features/order/managing_orders/deleting_order.feature
> [Order][Behat] Minor fix after updating a deleting an order feature

- src/Sylius/Component/Shipping/Model/ShipmentUnit.php
> [ShipmentUnit] Docblock fix

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_details.html.twig
| Related tickets | fixes #5677, partially #5817
> [Product] Remove duplicated field

- src/Sylius/Bundle/AssociationBundle/Resources/config/services.xml
> [Association] Remove .class parameters

- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
> [Api] Remove .class parameters

- src/Sylius/Bundle/AttributeBundle/Resources/config/attribute_types.xml
- src/Sylius/Bundle/AttributeBundle/Resources/config/services.xml
> [Attribute] Remove .class parameters

- src/Sylius/Bundle/ChannelBundle/Resources/config/debug.xml
- src/Sylius/Bundle/ChannelBundle/Resources/config/driver/doctrine/orm.xml
- src/Sylius/Bundle/ChannelBundle/Resources/config/services.xml
> [Channel] Remove .class parameters

- src/Sylius/Bundle/CustomerBundle/Resources/config/services.xml
> [Customer] Remove .class parameters

- src/Sylius/Bundle/MailerBundle/Resources/config/services.xml
> [Mailer] Remove .class parameters

- src/Sylius/Bundle/PaymentBundle/Resources/config/driver/doctrine/orm.xml
- src/Sylius/Bundle/PaymentBundle/Resources/config/services.xml
> [Payment] Remove .class parameters

- src/Sylius/Bundle/UserBundle/Resources/config/driver/doctrine/orm.xml
- src/Sylius/Bundle/UserBundle/Resources/config/services.xml
> [User] Remove .class parameters

- src/Sylius/Bundle/ShippingBundle/Resources/config/driver/doctrine/orm.xml
- src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
> [Shipping] Remove .class parameters

- src/Sylius/Bundle/ReviewBundle/Resources/config/services.xml
> [Review] Remove .class parameters

- src/Sylius/Bundle/AdminBundle/Resources/views/Administrator/Field/api.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Administrator/Field/confirmed.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Field/confirmed.html.twig
- src/Sylius/Bundle/AttributeBundle/Resources/views/Types/checkbox.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/labels.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Modal/_confirmation.html.twig
| Related tickets | fixes #6129 
> [Ui] Changed yes/no translations for crowdin to catch up

- src/Sylius/Component/Core/Model/Product.php
- src/Sylius/Component/Core/Model/ProductInterface.php
- src/Sylius/Component/Core/Model/ProductVariant.php
- src/Sylius/Component/Core/Model/ProductVariantInterface.php
- src/Sylius/Component/Core/spec/Model/ProductSpec.php
- src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php
> [Core] Remove metadata outtakes

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/administrator.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/currency.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/customer.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment_method.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_option.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipping_method.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/zone.yml
> [Admin] Fixed class deprecations in grids declarations

- src/Sylius/Bundle/CoreBundle/Resources/config/integration/hwi_oauth.xml
| Related tickets | fixes #5761 
> [CoreBundle][HwiOauth] Type error on HwiOauth authentication / Fix service definition

- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Component/Core/Formatter/StringInflector.php
| Related tickets | fixes my ocd
> [Core] Fixed typo in StringInflector's method name

- features/checkout/addressing_order/having_only_possible_country_preselected.feature
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_address.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_countryCode.html.twig
> [Shop] Preselect only available country on addressing form

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/administrator.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/currency.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/customer.yml
> [Admin] Unified grid fields declaration convention

- src/Sylius/Bundle/ShopBundle/Resources/private/js/province-field.js
> [CRITICAL][Shop] Check for provinces on preselected country

- features/order/managing_orders/seeing_order_new_state_after_customers_checkout.feature
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Resources/config/services.xml
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Service/SharedSecurityService.php
- src/Sylius/Behat/Service/SharedSecurityServiceInterface.php
- src/Sylius/Behat/spec/Service/SharedSecurityServiceSpec.php
> [Behat] Remove unused steps

- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Ui][Translation] Crowdin wake up

- src/Sylius/Behat/Context/Setup/ShippingContext.php
> [Behat] Fixed ShippingContext's faulty method use

- src/Sylius/Bundle/PayumBundle/Action/ConvertPaymentToPaypalExpressAction.php
- src/Sylius/Bundle/PayumBundle/Resources/config/services.xml
- src/Sylius/Bundle/PayumBundle/spec/Action/ConvertPaymentToPaypalExpressActionSpec.php
> [Payum] Fix converting prices to correct currencies in PayPal

- app/migrations/Version20160926175601.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductImage.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/TaxonImage.orm.xml
| Related tickets | fixes #6210 
Fix code constraint name.
> [CoreBundle] Rename taxon and product image unique code constraint

- src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/RegisterCurrencyHandlersPass.php
- src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/RegisterLocaleHandlersPass.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/handlers.xml
- src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
- src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/Compiler/RegisterCurrencyHandlersPassTest.php
- src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/Compiler/RegisterLocaleHandlersPassTest.php
> [Core] Made currency/locale change handlers taggable

- docs/book/emails.rst
> [Documentation] Concepts: Emails

- src/Sylius/Bundle/AdminBundle/Gulpfile.js
- src/Sylius/Bundle/ShopBundle/Gulpfile.js
> Fix Gulpfile - Wrong minifile assets.

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/_mainImage.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_images.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_mainImage.html.twig
> [ProductImage] Fix displaying images by a code

- src/Sylius/Behat/Context/Transform/OrderContext.php
- src/Sylius/Behat/Page/Admin/Country/CreatePage.php
- src/Sylius/Behat/Page/Admin/Country/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Product/CreateConfigurableProductPage.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/ProductOption/CreatePage.php
- src/Sylius/Behat/Page/Admin/ProductOption/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Promotion/CreatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
> [Behat] Add assert to getting last element of an array

- src/Sylius/Behat/Context/Cli/InstallerContext.php
- src/Sylius/Bundle/CoreBundle/Command/AbstractInstallCommand.php
- src/Sylius/Bundle/CoreBundle/Command/CheckRequirementsCommand.php
- src/Sylius/Bundle/CoreBundle/Command/CommandExecutor.php
- src/Sylius/Bundle/CoreBundle/Command/InstallAssetsCommand.php
- src/Sylius/Bundle/CoreBundle/Command/InstallCommand.php
- src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php
- src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php
- src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php
- src/Sylius/Bundle/CoreBundle/Installer/Requirement/SettingsRequirements.php
- src/Sylius/Bundle/CoreBundle/spec/Command/CommandExecutorSpec.php
| Related tickets | fixes #6211 
> [CoreBundle] Fix installation commands

- src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Product.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Taxon.orm.xml
- src/Sylius/Component/Core/Model/ProductImageInterface.php
- src/Sylius/Component/Core/Model/TaxonImage.php
- src/Sylius/Component/Core/Model/TaxonImageInterface.php
| Related tickets | fixes #6212 
> [ProductImage][TaxonImage] Add ProductImageInterface and TaxonImageInterface

- features/product/managing_products/removing_images_of_product.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPageInterface.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
> [Admin][Product] Removing images of a product

- features/checkout/shipping_order/preventing_shipping_step_completion_without_a_selected_method.feature
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPageInterface.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/checkout.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/checkout.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectShipping/_form.html.twig
> [Checkout] Minor fixes on checkout shipping selection 

- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_item.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Field/name.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_details.html.twig
- src/Sylius/Bundle/ProductBundle/Form/DataTransformer/ProductVariantToProductOptionsTransformer.php
- src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/BuildProductVariantFormSubscriber.php
- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
- src/Sylius/Bundle/ProductBundle/Validator/ProductVariantCombinationValidator.php
- src/Sylius/Bundle/ProductBundle/spec/Form/DataTransformer/ProductVariantToProductOptionsTransformerSpec.php
- src/Sylius/Bundle/ProductBundle/spec/Form/EventSubscriber/BuildProductVariantFormSubscriberSpec.php
- src/Sylius/Bundle/ProductBundle/spec/Validator/ProductVariantCombinationValidatorSpec.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Product/_variant.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_variants.html.twig
- src/Sylius/Component/Core/Model/ProductVariant.php
- src/Sylius/Component/Product/Generator/ProductVariantGenerator.php
- src/Sylius/Component/Product/Model/ProductVariant.php
- src/Sylius/Component/Product/Model/ProductVariantInterface.php
- src/Sylius/Component/Product/spec/Generator/ProductVariantGeneratorSpec.php
- src/Sylius/Component/Product/spec/Model/ProductVariantSpec.php
> [ProductVariant] Rename options to optionValues

- docs/bundles/SyliusOrderBundle/adjustments.rst
- src/Sylius/Bundle/InventoryBundle/README.md
- src/Sylius/Bundle/OrderBundle/README.md
- src/Sylius/Bundle/ProductBundle/README.md
- src/Sylius/Bundle/TaxonomyBundle/README.md
> [Documentation] Fix all the links to http://guides.spreecommerce.org/

- UPGRADE.md
> [UPGRADE][ProductVariant] Add missing upgrade note

- docs/book/coupons.rst
- docs/book/index.rst
- docs/book/map.rst.inc
> [Documentation] Concepts: Coupons

- docs/cookbook/custom-email.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
> [Documentation] Cookbook - How to send a custom email?

- docs/book/index.rst
- docs/book/installation.rst
> [Documentation] Installation: Project Structure

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ShippingMethodRepository.php
- src/Sylius/Component/Core/Repository/ShippingMethodRepositoryInterface.php
- src/Sylius/Component/Core/Resolver/DefaultShippingMethodResolver.php
- src/Sylius/Component/Core/spec/Resolver/DefaultShippingMethodResolverSpec.php
> [CoreBundle][Core] Improvement of DefaultShippingMethodResolver

- src/Sylius/Bundle/CoreBundle/Resources/config/validation.xml
> [Core] Minor refactor validation file

- features/inventory/verify_reserved_inventory_is_back_in_stock_on_order_cancelling.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Transform/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Component/Core/Inventory/Operator/OrderInventoryOperator.php
- src/Sylius/Component/Core/spec/Inventory/Operator/OrderInventoryOperatorSpec.php
> [Inventory] Minor fixes for back to stock after order cancellation

- src/Sylius/Behat/Context/Setup/AdminSecurityContext.php
- src/Sylius/Behat/Context/Ui/UserContext.php
> [Behat] Unify keys for admin user

- src/Sylius/Bundle/CoreBundle/Form/Type/CouponType.php
- src/Sylius/Bundle/PromotionBundle/Form/Type/CouponType.php
> [Coupon] Minor fixes in CouponType

- src/Sylius/Behat/Page/Admin/Country/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/ProductOption/CreatePage.php
- src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Zone/CreatePage.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_form.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
> [CRITICAL][Shop] Minor fix in out of stock validation message display

- docs/book/adjustments.rst
- docs/book/index.rst
- docs/book/map.rst.inc
> [Documentation] Concepts: Adjustments

- features/product/viewing_products/viewing_different_price_for_different_product_variants.feature
- features/product/viewing_products/viewing_different_price_for_different_product_variants_selected_with_options.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Bundle/CoreBundle/Twig/ProductVariantsPricesExtension.php
- src/Sylius/Bundle/CoreBundle/spec/Twig/ProductVariantsPricesExtensionSpec.php
| Related tickets | https://github.com/Sylius/Sylius/pull/6161
> [Behat] Display variant price on product details improvements

- features/checkout/paying_for_order/preventing_to_pay_for_cancelled_order.feature
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Context/Ui/PaypalContext.php
- src/Sylius/Behat/Page/Shop/Checkout/OrderDetailsPage.php
- src/Sylius/Behat/Page/Shop/Checkout/OrderDetailsPageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/ThankYouPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/shop/checkout.xml
- src/Sylius/Behat/Resources/config/suites/ui/checkout/paying_for_order.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/orderDetails.html.twig
> [Checkout] Preventing to pay for cancelled order

- src/Sylius/Bundle/CoreBundle/Fixture/MugProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/StickerProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/TshirtProductFixture.php
> [Product] Add product options to mug, sticker and t-shirt product fixtures

- features/product/managing_product_variants/adding_product_variant.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Page/Admin/ProductVariant/CreatePage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/CreatePageInterface.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionValueCollectionType.php
- src/Sylius/Bundle/ProductBundle/Resources/config/services.xml
> [ProductBundle] Creating new product's variant with specific option's value 

- features/product/managing_products/editing_product.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/ProductOptionFieldSubscriber.php
> [Product] Quick fix to disabling product options in product form

- src/Sylius/Bundle/GridBundle/Form/Type/Filter/BooleanFilterType.php
Simply label fixes for BooleanFilterType in GridBundle :)
> [Grid] fixed BooleanFilterType choice labels

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
> [Fixture] Wrong tax category

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
> [Fixture] Missing quotation mark around names

- .travis.yml
> [Travis] Disabled email notifications

- src/Sylius/Component/Core/Formatter/StringInflector.php
> [Core] Finalize string inflector

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
| Related tickets | fixes [comment](https://github.com/Sylius/Sylius/pull/6298#discussion_r81959987)
> [Fixtures] More quotation marks

- src/Sylius/Bundle/AddressingBundle/composer.json
- src/Sylius/Bundle/AssociationBundle/composer.json
- src/Sylius/Bundle/AttributeBundle/composer.json
- src/Sylius/Bundle/CurrencyBundle/composer.json
- src/Sylius/Bundle/CustomerBundle/composer.json
- src/Sylius/Bundle/GridBundle/composer.json
- src/Sylius/Bundle/OrderBundle/composer.json
- src/Sylius/Bundle/PaymentBundle/composer.json
- src/Sylius/Bundle/PricingBundle/composer.json
- src/Sylius/Bundle/PromotionBundle/composer.json
- src/Sylius/Bundle/ResourceBundle/composer.json
- src/Sylius/Bundle/TaxationBundle/composer.json
- src/Sylius/Bundle/TaxonomyBundle/composer.json
- src/Sylius/Component/Promotion/composer.json
> Drop doctrine/orm <2.5 constraint

- app/migrations/Version20161006103721.php
- src/Sylius/Bundle/CoreBundle/Form/Type/ChannelType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
- src/Sylius/Component/Core/Model/Channel.php
- src/Sylius/Component/Core/Model/ChannelInterface.php
| Related tickets | fixes #6316
> [Channel] Remove taxons

- features/cart/shopping_cart/deleting_expired_carts_automatically.feature
- src/Sylius/Behat/Context/Domain/CartContext.php
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Resources/config/services/contexts/domain.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/domain/cart/shopping_cart.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
- src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/OrderBundle/DependencyInjection/SyliusOrderExtension.php
- src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
- src/Sylius/Component/Order/Remover/ExpiredCartsRemover.php
- src/Sylius/Component/Order/Remover/ExpiredCartsRemoverInterface.php
- src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php
- src/Sylius/Component/Order/spec/Remover/ExpiredCartsRemoverSpec.php
> [Order] Automatically delete expired carts

- features/order/managing_orders/cancelling_unpaid_orders_automatically.feature
- src/Sylius/Behat/Context/Domain/ManagingOrdersContext.php
- src/Sylius/Behat/Resources/config/services/contexts/domain.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/OrderBundle/Command/CancelUnpaidOrdersCommand.php
- src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/OrderBundle/DependencyInjection/SyliusOrderExtension.php
- src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
- src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php
- src/Sylius/Component/Order/Updater/UnpaidOrdersStateUpdater.php
- src/Sylius/Component/Order/Updater/UnpaidOrdersStateUpdaterInterface.php
- src/Sylius/Component/Order/spec/Updater/UnpaidOrdersStateUpdaterSpec.php
This PR is based on https://github.com/Sylius/Sylius/pull/6291.
> [Order] Automatically cancel unpaid orders

- src/Sylius/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php
- src/Sylius/Bundle/PayumBundle/Resources/config/services/extension.xml
| Related tickets | fixes #6337
> [BugFix] Apply payment state transition for Payum Notify requests

- composer.json
- composer.lock
- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Setup/LocaleContext.php
- src/Sylius/Behat/Resources/config/profiles/default.yml
> [Behat] Use FriendsOfBehat/VariadicExtension

- docs/book/promotions.rst
- docs/bundles/SyliusPromotionBundle/models.rst
- docs/bundles/SyliusPromotionBundle/summary.rst
- docs/components/Promotion/basic_usage.rst
- docs/components/Promotion/interfaces.rst
- docs/components/Promotion/models.rst
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/PromotionBundle/Form/EventListener/BuildPromotionRuleFormSubscriber.php
- src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionRuleType.php
- src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/Promotion.orm.xml
- src/Sylius/Bundle/PromotionBundle/Resources/config/doctrine/model/PromotionRule.orm.xml
- src/Sylius/Bundle/PromotionBundle/spec/Form/EventListener/BuildPromotionRuleFormSubscriberSpec.php
- src/Sylius/Bundle/PromotionBundle/spec/Form/Type/PromotionRuleTypeSpec.php
- src/Sylius/Bundle/ShippingBundle/CHANGELOG.md
- src/Sylius/Component/Core/Factory/PromotionRuleFactory.php
- src/Sylius/Component/Core/Factory/PromotionRuleFactoryInterface.php
- src/Sylius/Component/Core/spec/Factory/PromotionRuleFactorySpec.php
- src/Sylius/Component/Promotion/Checker/Eligibility/PromotionRulesEligibilityChecker.php
- src/Sylius/Component/Promotion/Model/Promotion.php
- src/Sylius/Component/Promotion/Model/PromotionInterface.php
- src/Sylius/Component/Promotion/Model/PromotionRule.php
- src/Sylius/Component/Promotion/Model/PromotionRuleInterface.php
- src/Sylius/Component/Promotion/spec/Checker/Eligibility/PromotionRulesEligibilityCheckerSpec.php
- src/Sylius/Component/Promotion/spec/Model/PromotionRuleSpec.php
- src/Sylius/Component/Promotion/spec/Model/PromotionSpec.php
| Related tickets | fixes #6310
> [Promotion] Rename Rule(Interface) to PromotionRule(Interface)

- src/Sylius/Bundle/PayumBundle/DependencyInjection/SyliusPayumExtension.php
Currently it only processes the first `payum` configuration, this fix makes it processing all `payum` configurations.
> [Payum] Fix PayumBundle -> SyliusPayumBundle -> SyliusPaymentBundle integration

- features/locale/managing_locales/inability_of_disabling_base_locale.feature
- features/locale/managing_locales/toggling_locale.feature
- src/Sylius/Behat/Context/Setup/LocaleContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingLocalesContext.php
- src/Sylius/Behat/Context/Ui/Shop/LocaleContext.php
- src/Sylius/Behat/Page/Admin/Locale/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Locale/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/locale/managing_locales.yml
- src/Sylius/Bundle/CoreBundle/Form/Type/LocaleType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/CannotDisableLocale.php
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/CannotDisableLocaleValidator.php
> [Admin] Disable toggling of base locale/currency

- features/cart/shopping_cart/deleting_expired_carts_automatically.feature
- features/order/managing_orders/cancelling_unpaid_orders_automatically.feature
- src/Sylius/Behat/Context/Domain/CartContext.php
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
- src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
- src/Sylius/Component/Order/spec/Remover/ExpiredCartsRemoverSpec.php
| Related tickets | https://github.com/Sylius/Sylius/pull/6321, https://github.com/Sylius/Sylius/pull/6291
> [Core][Order][Behat] Minor fixes for expired orders and carts

- src/Sylius/Bundle/GridBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
- src/Sylius/Component/Grid/Definition/ArrayToDefinitionConverter.php
- src/Sylius/Component/Grid/Definition/Field.php
Easy way to toggle show/hide default Sylius grid column definition.
> [Grid] Add show/hide ability for grid column.

- src/Sylius/Bundle/OrderBundle/Command/CancelUnpaidOrdersCommand.php
- src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
| Related tickets | #6321 #6291
> [OrderBundle] Bug fix - add flush after cancel expired order/cart.

- docs/book/orders.rst
> [Documentation] Concepts: Orders Fixes

- docs/book/state_machine.rst
> [Documentation] [State machine] Update state machine references to meet current implementation

- features/user/managing_customers/adding_customer.feature
- features/user/managing_customers/editing_customer.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Page/Admin/Customer/CreatePage.php
- src/Sylius/Behat/Page/Admin/Customer/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/Customer/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Customer/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/user/managing_customers.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/_form.html.twig
Based on https://github.com/Sylius/Sylius/pull/6329
> [Customer] Add group to customer create and edit page

- features/promotion/tracking_usage_limit/decreasing_promotion_usage_after_cancelling_order.feature
- features/promotion/tracking_usage_limit/increasing_promotion_usage_after_placing_order.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Behat/Page/Admin/Promotion/IndexPage.php
- src/Sylius/Behat/Page/Admin/Promotion/IndexPageInterface.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
- src/Sylius/Bundle/OrderBundle/Resources/config/app/state_machine.yml
- src/Sylius/Component/Core/Promotion/Modifier/OrderPromotionsUsageModifier.php
- src/Sylius/Component/Core/Promotion/Modifier/OrderPromotionsUsageModifierInterface.php
- src/Sylius/Component/Core/spec/Promotion/Modifier/OrderPromotionsUsageModifierSpec.php
- src/Sylius/Component/Promotion/Model/Promotion.php
- src/Sylius/Component/Promotion/Model/PromotionInterface.php
- src/Sylius/Component/Promotion/spec/Model/PromotionSpec.php
> [Core][Promotion] Tracking promotions usage

- composer.lock
For more information see https://github.com/Payum/OmnipayBridge/pull/28
> [BugFix] Upgrade payum omnipay bridge to 1.2.4

- composer.json
- composer.lock
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
- src/Sylius/Bundle/CoreBundle/composer.json
- src/Sylius/Bundle/PromotionBundle/composer.json
- src/Sylius/Bundle/TaxonomyBundle/composer.json
> Remove JMSTranslationBundle

- docs/customization/flash.rst
- docs/customization/index.rst
- docs/customization/map.rst.inc
| Related tickets | partially #5275, #6218
> [Documentation] Customization Guide: Flashes

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/order.yml
- src/Sylius/Bundle/GridBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/GridBundle/Tests/DependencyInjection/ConfigurationTest.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/_grid.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/sorting.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
- src/Sylius/Component/Grid/Definition/Grid.php
- src/Sylius/Component/Grid/Sorting/Sorter.php
- src/Sylius/Component/Grid/View/GridView.php
- src/Sylius/Component/Grid/spec/Definition/GridSpec.php
- src/Sylius/Component/Grid/spec/Sorting/SorterSpec.php
- src/Sylius/Component/Grid/spec/View/GridViewSpec.php
> [Grid] Simplified sorting urls

- web/.htaccess
| Related tickets | fixes #4707
Added rewrite rule to htaccess to prevent issues with Bearer token being stripped by apache
> Added rewrite rule to htaccess to prevent issues with api token

- docs/bundles/SyliusProductBundle/installation.rst
| Related tickets | fixes #6369
> [Documentation] #6369 Removed old documentation

- docs/book/adjustments.rst
- docs/book/checkout.rst
- docs/book/coupons.rst
- docs/book/emails.rst
- docs/book/index.rst
- docs/book/map.rst.inc
- docs/cookbook/custom-email.rst
- docs/cookbook/installation-commands.rst
- docs/customization/flash.rst
- docs/customization/index.rst
- docs/customization/state_machine.rst
- docs/index.rst
> [Documentation] Various Fixes

- features/product/viewing_products/viewing_product_sorted_by_date.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Behat/Page/Shop/Taxon/ShowPage.php
- src/Sylius/Behat/Page/Shop/Taxon/ShowPageInterface.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_gridList.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/show.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php
> [Shop] Sort product by date 

- docs/book/orders.rst
> [Documentation][Book][Orders] Shipments & Payments of an Order

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
> [Fixtures] Only channel should always be enabled

- features/product/viewing_products/viewing_sorted_products.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Behat/Page/Shop/Taxon/ShowPage.php
- src/Sylius/Behat/Page/Shop/Taxon/ShowPageInterface.php
> [Shop] Sort product by price

- docs/cookbook/api.rst
- docs/cookbook/custom-model.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
> [Documentation] Cookbook - How to use Sylius API?

- features/product/viewing_products/viewing_sorted_products.feature
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
> [Critical][Behat] Fix broken scenarios

- src/Sylius/Bundle/UserBundle/EventListener/UserDeleteListener.php
- src/Sylius/Component/User/Security/UserPbkdf2PasswordEncoder.php
| Related tickets | fixes #6387
> [User] Cleaning fixes

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
> [Fixtures] Allow channel to define default locale and currency

- docs/cookbook/api.rst
- docs/cookbook/custom-model.rst
> [Documentation][Cookbook][Api] Fix

- docs/book/fixtures.rst
- docs/book/index.rst
- docs/book/map.rst.inc
> [Documentation][Book] Fixtures

- src/Sylius/Component/Addressing/Matcher/ZoneMatcherInterface.php
- src/Sylius/Component/Addressing/Model/Country.php
- src/Sylius/Component/Shipping/Calculator/DefaultCalculators.php
- src/Sylius/Component/Shipping/Model/ShippingMethodInterface.php
> [Clean-up] Revert some useful comments

- features/checkout/paying_for_order/paying_with_paypal_during_checkout.feature
- src/Sylius/Behat/Context/Ui/PaypalContext.php
- src/Sylius/Behat/Service/Mocker/Mocker.php
- src/Sylius/Behat/Service/Mocker/MockerInterface.php
- src/Sylius/Behat/Service/Mocker/PaypalApiMocker.php
- src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
> [Paypal][Behat] Unmock api responses after paypal action

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDriver.php
Just noticed there was a little refactoring that could be done here to IMO make this more clear.
- Eliminate early return
- Remove code duplication
> Refactor AbstractDriver addFactory method

- src/Sylius/Bundle/CoreBundle/Installer/Requirement/RequirementCollection.php
| Related tickets | fixes #6426
> Closes #6426: RequirementCollection should be abstract

- src/Sylius/Behat/Context/Domain/ManagingProductsContext.php
- src/Sylius/Behat/Context/Domain/ManagingPromotionCouponsContext.php
- src/Sylius/Behat/Context/Domain/ManagingPromotionsContext.php
| Related tickets | fixes #5832 
As explained in review comment, we shouldn't catch the exception on `When I delete product`
> [Behat] Split 'delete' and 'try to delete' methods in Domain contexts

- src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php
> [Core] Remove final from OAuth UserProvider

- src/Sylius/Bundle/CoreBundle/Resources/views/Email/passwordReset.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/security.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/resetPassword.html.twig
- src/Sylius/Bundle/UserBundle/Controller/UserController.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/6262
> [Shop] Fix Forgot Password

- features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_per_customer_usage_limit.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
> [Promotion] Per customer usage limit should not count cancelled orders

- features/promotion/tracking_usage_limit/decreasing_promotion_coupon_usage_after_cancelling_order.feature
- features/promotion/tracking_usage_limit/increasing_promotion_coupon_usage_after_placing_order.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
- src/Sylius/Component/Core/Promotion/Modifier/OrderPromotionsUsageModifier.php
- src/Sylius/Component/Core/spec/Promotion/Modifier/OrderPromotionsUsageModifierSpec.php
- src/Sylius/Component/Promotion/Model/PromotionCoupon.php
- src/Sylius/Component/Promotion/Model/PromotionCouponInterface.php
- src/Sylius/Component/Promotion/spec/Model/PromotionCouponSpec.php
> [Promotion] Track promotion coupon usage

- etc/bin/test-package
- etc/travis/suites/application/script/test-behat-with-cli
- etc/travis/suites/application/script/test-behat-with-javascript
- etc/travis/suites/application/script/test-behat-without-javascript
- etc/travis/suites/application/script/test-phpspec
> [Travis] Maintenance update

- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/_menu.html.twig
> [Admin][ProductVariant] Remove unnecessary media tab

- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_item.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_totals.html.twig
- src/Sylius/Bundle/MoneyBundle/Formatter/MoneyFormatter.php
- src/Sylius/Bundle/MoneyBundle/spec/Formatter/MoneyFormatterSpec.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_totals.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_promotion.html.twig
> Improve discount rendering

- src/Sylius/Component/Grid/Definition/ArrayToDefinitionConverter.php
> [Grid] Improve ArrayToDefinitionConverter

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
> [Core] Improve ProductExampleFactory

- src/Sylius/Bundle/ResourceBundle/Controller/ParametersParser.php
> [Resource] Improve ParametersParser

- app/migrations/Version20161017164559.php
- features/checkout/shipping_order/sorting_shipping_method_selection.feature
- features/shipping/managing_shipping_methods/adding_shipping_method.feature
- features/shipping/managing_shipping_methods/sorting_shipping_methods_by_name_or_code.feature
- features/shipping/managing_shipping_methods/sorting_shipping_methods_by_position.feature
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Admin/ShippingMethod/CreatePage.php
- src/Sylius/Behat/Page/Admin/ShippingMethod/CreatePageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipping_method.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/ShippingMethod/_form.html.twig
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ShippingMethodRepository.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodType.php
- src/Sylius/Bundle/ShippingBundle/Resources/config/doctrine/model/ShippingMethod.orm.xml
- src/Sylius/Bundle/ShippingBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/ShippingBundle/spec/Form/Type/ShippingMethodTypeSpec.php
- src/Sylius/Component/Shipping/Model/ShippingMethod.php
- src/Sylius/Component/Shipping/Model/ShippingMethodInterface.php
> [Admin] [Shipping] Sorting shipping methods

- docs/book/inventory.rst
> [Documentation][Book] Inventory

- src/Sylius/Bundle/ChannelBundle/DependencyInjection/Compiler/CompositeChannelContextPass.php
- src/Sylius/Bundle/ChannelBundle/DependencyInjection/Compiler/CompositeRequestResolverPass.php
- src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/RegisterCurrencyHandlersPass.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/context.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/handlers.xml
- src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/Compiler/RegisterCurrencyHandlersPassTest.php
- src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/Compiler/RegisterLocaleHandlersPassTest.php
- src/Sylius/Bundle/CurrencyBundle/DependencyInjection/Compiler/CompositeCurrencyContextPass.php
- src/Sylius/Bundle/CurrencyBundle/Resources/config/services.xml
- src/Sylius/Bundle/CurrencyBundle/SyliusCurrencyBundle.php
- src/Sylius/Bundle/LocaleBundle/DependencyInjection/Compiler/CompositeLocaleContextPass.php
- src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml
- src/Sylius/Bundle/LocaleBundle/SyliusLocaleBundle.php
- src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/RegisterCartContextsPass.php
- src/Sylius/Bundle/OrderBundle/DependencyInjection/Compiler/RegisterProcessorsPass.php
- src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Compiler/PrioritizedCompositeServicePass.php
> [Resource] Refactor composite complier pass

- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
> [Resource] Remove move*() methods

- features/account/customer_account/address_book/deleting_address.feature
- features/account/customer_account/address_book/viewing_addresses.feature
- src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPage.php
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/account/address_book.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_item.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/create.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/index.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Shop] Tweak the UI of the address book

- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
> [Resource] Remove actions for toggling from ResourceController

- features/product/managing_product_association_types/adding_product_association.feature
- features/product/managing_product_association_types/browsing_product_association_types.feature
- features/product/managing_product_association_types/deleting_product_association_type.feature
- features/product/managing_product_association_types/editing_product_association_type.feature
- features/product/managing_product_association_types/product_association_type_unique_code_validation.feature
- features/product/managing_product_association_types/product_association_type_validation.feature
- src/Sylius/Behat/Context/Setup/ProductAssociationTypeContext.php
- src/Sylius/Behat/Context/Transform/ProductAssociationTypeContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductAssociationTypesContext.php
- src/Sylius/Behat/Page/Admin/ProductAssociationType/CreatePage.php
- src/Sylius/Behat/Page/Admin/ProductAssociationType/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/ProductAssociationType/UpdatePage.php
- src/Sylius/Behat/Page/Admin/ProductAssociationType/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
- src/Sylius/Behat/Resources/config/services/contexts/transform.xml
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/admin.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/product_association_type.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/ui/product/managing_product_association_types.yml
- src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_association_type.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_association_type.yml
- src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductAssociationType/_form.html.twig
- src/Sylius/Bundle/AssociationBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Admin][ProductAssociationType] CRUD

- features/product/managing_products/browsing_products_by_taxon.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Page/Admin/Product/IndexPage.php
- src/Sylius/Behat/Page/Admin/Product/IndexPageInterface.php
- src/Sylius/Behat/Resources/config/services/pages/admin/product.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/index.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/Partial/_tree.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/Partial/_treeWithButtons.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/Partial/_treeWithoutButtons.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/create.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/update.html.twig
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php
> [Admin] Filter by taxons on products grid

- features/checkout/having_new_addresses_saved_in_address_book.feature
- src/Sylius/Behat/Context/Ui/CustomerContext.php
- src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPage.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/checkout/checkout.yml
- src/Sylius/Bundle/AddressingBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_checkout.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Component/Addressing/Comparator/AddressComparator.php
- src/Sylius/Component/Addressing/Comparator/AddressComparatorInterface.php
- src/Sylius/Component/Addressing/spec/Comparator/AddressComparatorSpec.php
- src/Sylius/Component/Core/Customer/AddressAdderInterface.php
- src/Sylius/Component/Core/Customer/CustomerOrderAddressesSaver.php
- src/Sylius/Component/Core/Customer/CustomerUniqueAddressAdder.php
- src/Sylius/Component/Core/Customer/OrderAddressesSaverInterface.php
- src/Sylius/Component/Core/spec/Customer/CustomerOrderAddressesSaverSpec.php
- src/Sylius/Component/Core/spec/Customer/CustomerUniqueAddressAdderSpec.php
> [Shop] Saving new addresses into customer's address book after checkout

- docs/customization/menu.rst
> [Documentation][Customization][Menus] Fix

- docs/book/index.rst
- docs/book/map.rst.inc
- docs/book/product_reviews.rst
> [Documentation][Book] Product Reviews

- docs/book/address_book.rst
- docs/book/index.rst
- docs/book/map.rst.inc
> [Documentation][Book] Address Book

- features/promotion/receiving_discount/receiving_fixed_discount_on_specific_products.feature
- features/promotion/receiving_discount/receiving_percentage_discount_on_specific_products.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
- src/Sylius/Component/Core/Promotion/Action/UnitFixedDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Action/UnitPercentageDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Filter/ProductFilter.php
- src/Sylius/Component/Core/spec/Promotion/Action/UnitFixedDiscountPromotionActionCommandSpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/UnitPercentageDiscountPromotionActionCommandSpec.php
- src/Sylius/Component/Core/spec/Promotion/Filter/ProductFilterSpec.php
| Related tickets | continuation for #6480 
> [Promotion] Product filter

- docs/cookbook/images.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
> [Documentation][Cookbook] Resizing Images

- src/Sylius/Bundle/AdminBundle/composer.json
- src/Sylius/Bundle/AttributeBundle/composer.json
- src/Sylius/Bundle/ShopBundle/composer.json
| Related tickets | fixes #6525
> [Composer] Add SonataIntlBundle to requirements

- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Component/Core/Customer/CustomerUniqueAddressAdder.php
- src/Sylius/Component/Core/spec/Customer/CustomerUniqueAddressAdderSpec.php
| Related tickets | regarding https://github.com/Sylius/Sylius/pull/6536#issuecomment-255955143
> [Core] Removed unnecessary flush from CustomerUniqueAddressAdder

- features/promotion/managing_promotions/adding_promotion_with_filter.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Bundle/CoreBundle/Form/DataTransformer/ProductsToCodesTransformer.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Filter/ProductFilterConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/PromotionFiltersType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/CoreBundle/spec/Form/DataTransformer/ProductsToCodesTransformerSpec.php
- src/Sylius/Component/Core/Promotion/Filter/TaxonFilter.php
> [Promotion] UI for product filter

- docs/cookbook/custom-model.rst
| New feature?    | no|no
| BC breaks?      | no|no
| Related tickets | fixes #6544 
> [Documentation] custom model, step 8 service fix

- docs/cookbook/images.rst
| Related tickets | fixes #6550
Quick fix. Paste the proper link to The LiipImagineBundle
> [Documentation][Cookbook] Resize Image Fix

- features/order/managing_orders/seeing_order_item_detailed_data.feature
- src/Sylius/Behat/Context/Setup/ProductAttributeContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Setup/TaxonomyContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
- src/Sylius/Behat/Page/Shop/Account/RegisterPage.php
- src/Sylius/Component/Attribute/spec/Model/AttributeSpec.php
- src/Sylius/Component/Core/Formatter/StringInflector.php
- src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php
> [Behat] Use StringInflector wherever it can be used

- src/Sylius/Behat/Context/Setup/GeographicalContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Setup/RouteContext.php
- src/Sylius/Behat/Context/Setup/StaticContentContext.php
- src/Sylius/Behat/Context/Setup/TaxonomyContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
> [Behat][DX] Use variadics wherever they can be used

- features/checkout/addressing_order/choosing_billing_and_shipping_address_from_address_book.feature
- src/Sylius/Behat/Context/Setup/CustomerContext.php
- src/Sylius/Behat/Context/Transform/AddressingContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/transform.xml
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/shop/checkout.xml
- src/Sylius/Bundle/ShopBundle/Resources/private/js/address-book.js
- src/Sylius/Bundle/ShopBundle/Resources/private/js/checkout-addressing.js
- src/Sylius/Bundle/ShopBundle/Resources/private/js/semantic-ui-api-actions.js
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_form.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_addressBookSelect.html.twig
- src/Sylius/Bundle/UiBundle/Resources/private/js/app.js
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Addresing][Checkout] Choosing address from address book during checkout

- etc/travis/suites/application/script/test-behat-with-javascript
Still looking for better solutions.
> [Travis] Temporary fix: partition Behat with JS

- etc/travis/suites/application/script/test-behat-with-javascript
- src/Sylius/Behat/Extension/SeleniumExtension/SeleniumSessionRestarter.php
- src/Sylius/Behat/Extension/SeleniumExtension/ServiceContainer/SeleniumExtension.php
- src/Sylius/Behat/Resources/config/profiles/default.yml
> [Travis] Make JS tests great again!

- features/account/customer_account/address_book/adding_address.feature
- features/account/customer_account/address_book/adding_address_validation.feature
- features/account/customer_account/address_book/deleting_address.feature
- features/account/customer_account/address_book/editing_address.feature
- features/account/customer_account/address_book/viewing_addresses.feature
- src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/CreatePage.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/CreatePageInterface.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPage.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPageInterface.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePage.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/shop/account.xml
- src/Sylius/Behat/Resources/config/suites/ui/account/address_book.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/account/address_book.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_item.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/create.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/index.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/layout.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/update.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_address.html.twig
> [Shop][Account] Updating customer's address

- features/user/managing_users/changing_shop_user_password.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
- src/Sylius/Behat/Resources/config/suites/ui/user/managing_users.yml
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/6283
> [Behat][Admin][Shop] Change shop user password as administrator

- src/Sylius/Bundle/ReviewBundle/DependencyInjection/Compiler/RegisterReviewFactoryPass.php
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/product_review.yml
- src/Sylius/Component/Review/Factory/ReviewFactory.php
- src/Sylius/Component/Review/Factory/ReviewFactoryInterface.php
- src/Sylius/Component/Review/spec/Factory/ReviewFactorySpec.php
> [Review] Enhance review factory

- app/migrations/Version20161026101817.php
- features/user/managing_customer_groups/adding_customer_group.feature
- features/user/managing_customer_groups/customer_group_unique_code_validation.feature
- features/user/managing_customer_groups/editing_customer_group.feature
- src/Sylius/Behat/Context/Setup/CustomerGroupContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomerGroupsContext.php
- src/Sylius/Behat/Page/Admin/CustomerGroup/CreatePage.php
- src/Sylius/Behat/Page/Admin/CustomerGroup/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/CustomerGroup/UpdatePage.php
- src/Sylius/Behat/Page/Admin/CustomerGroup/UpdatePageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/customer_group.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/CustomerGroup/_form.html.twig
- src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerGroupType.php
- src/Sylius/Bundle/CustomerBundle/Resources/config/doctrine/model/CustomerGroup.orm.xml
- src/Sylius/Bundle/CustomerBundle/Resources/config/validation/CustomerGroup.xml
- src/Sylius/Bundle/CustomerBundle/Resources/translations/validators.en.yml
- src/Sylius/Component/Customer/Model/CustomerGroup.php
- src/Sylius/Component/Customer/Model/CustomerGroupInterface.php
- src/Sylius/Component/Customer/spec/Model/CustomerGroupSpec.php
> [Customer] Add code to customer group

- docs/api/promotions.rst
- docs/book/promotions.rst
- docs/book/resource_layer.rst
- docs/book/shipments.rst
- docs/bundles/SyliusFixturesBundle/architecture.rst
- docs/bundles/SyliusFixturesBundle/builtin_listeners.rst
- docs/bundles/SyliusFixturesBundle/custom_listener.rst
- docs/bundles/SyliusGridBundle/your_first_grid.rst
- docs/bundles/SyliusResourceBundle/create_resource.rst
- docs/bundles/SyliusTaxonomyBundle/categorization.rst
- docs/bundles/SyliusThemeBundle/your_first_theme.rst
- docs/components/Inventory/basic_usage.rst
- docs/components/Inventory/models.rst
- docs/components/Mailer/basic_usage.rst
- docs/components/Promotion/checkers.rst
- docs/components/Shipping/basic_usage.rst
- docs/cookbook/custom-model.rst
- docs/customization/model.rst
- docs/customization/state_machine.rst
> [Documentation] Fixed typos

- features/user/managing_customer_groups/deleting_customer_group.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomerGroupsContext.php
> [Behat][Admin][CustomerGroup] Add missing scenario for deleting a customer group

- features/payment/managing_payment_methods/deleting_payment_method.feature
- features/user/managing_customer_groups/browsing_customer_groups.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomerGroupsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductAssociationTypesContext.php
> [Behat] Minor fixes

- features/order/managing_orders/refunding_order_payment.feature
- features/user/managing_users/changing_shop_user_password.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
| Related tickets | applies @GSadee comments from https://github.com/Sylius/Sylius/pull/6565 and https://github.com/Sylius/Sylius/pull/6555
> [Behat] Small semantic fixes in scenarios

- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_payment.yml
- src/Sylius/Component/Core/OrderPaymentStates.php
- src/Sylius/Component/Core/OrderPaymentTransitions.php
- src/Sylius/Component/Core/StateResolver/OrderPaymentStateResolver.php
- src/Sylius/Component/Core/spec/StateResolver/OrderPaymentStateResolverSpec.php
| Related tickets | mentioned in https://github.com/Sylius/Sylius/pull/6555
> [Core] Improve OrderPaymentStateResolver

- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Component/Addressing/Comparator/AddressComparator.php
- src/Sylius/Component/Addressing/Comparator/AddressComparatorInterface.php
- src/Sylius/Component/Addressing/spec/Comparator/AddressComparatorSpec.php
- src/Sylius/Component/Core/Customer/CustomerAddressAdderInterface.php
- src/Sylius/Component/Core/Customer/CustomerOrderAddressesSaver.php
- src/Sylius/Component/Core/Customer/CustomerUniqueAddressAdder.php
- src/Sylius/Component/Core/spec/Customer/CustomerOrderAddressesSaverSpec.php
- src/Sylius/Component/Core/spec/Customer/CustomerUniqueAddressAdderSpec.php
| Related tickets | fixes #6536 comments
> [WIP][Shop] Fixes of saving unique addresses after checkout

- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomerGroupsContext.php
| Related tickets | https://github.com/Sylius/Sylius/pull/6568
> [Behat][CustomerGroup] Method name fix

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php
> [Core] Remove unused method from ProductRepository

- src/Sylius/Bundle/CoreBundle/Fixture/BookProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/MugProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/StickerProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/TshirtProductFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures.xml
> [CoreBundle] Clean product fixtures.

- src/Sylius/Behat/Page/Shop/Product/ShowPage.php
| Q | A |
| --- | --- |
| Related tickets | #6564 |
> [Behat][ProductAssociation] Minor fixes in ShowPage

- src/Sylius/Bundle/ShopBundle/Resources/private/js/address-book.js
| Related tickets | https://github.com/Sylius/Sylius/pull/6526
> [Address] Clean all inputs before filling in the address

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
| Related tickets | fixes #6487
> [Fixtures] Add 'code' to fixtures, fixes #6487

- src/Sylius/Component/Pricing/Calculator/Calculators.php
| Related tickets | detected in #6608 
> [Pricing] Remove redundant Calculator constant

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/payment_method.yml
> [API] Fix payment method show

- docs/bundles/SyliusOrderBundle/installation.rst
| Q | A |
| --- | --- |
I believe the configuration shown here was outdated. I updated it matching what I found here: https://github.com/Sylius/Sylius/issues/5380
Disclaimer: I am still a total beginner with Symfony, Doctrine and Sylius. Please somebody review it carefully. Thank you!
> update of sylius_order configuration template (documentation)

- src/Sylius/Bundle/CoreBundle/Controller/OrderController.php
> [Order] Format agnostic cart summary

- src/Sylius/Component/Core/Model/ProductTranslationInterface.php
> [Core] Extend proper interface in Core/ProductTranslationInterface

- docs/book/pricing.rst
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
> [Documentation][Book] Pricing

- docs/book/emails.rst
> [Documentation] Correct order confirmation email description

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_promotion.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/SyliusPromotionExtension.php
- src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
| Related tickets | fixes #6602
> [Promotion] Remove weird "decorating" stuff from PromotionExtension

- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/api/taxon.yml
| Q  | A |
| --------------- | --- |
> [Admin] Fix admin api routing

- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
- docs/cookbook/stripe.rst
> [Documentation][Cookbook] Stripe Credit Card

- docs/bundles/SyliusResourceBundle/configuration.rst
| Related tickets | fixes #6624 
> [Documentation][ResourceBundle] configure several doctrine drivers with sylius resource

- features/product/managing_products/product_image_validation.feature
- features/product/managing_products/removing_images_of_product.feature
- features/taxonomy/managing_taxons/removing_images_of_taxon.feature
- features/taxonomy/managing_taxons/taxon_image_validation.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
- src/Sylius/Behat/Page/Admin/Product/CreateConfigurableProductPage.php
- src/Sylius/Behat/Page/Admin/Product/CreateConfigurableProductPageInterface.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPageInterface.php
- src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPageInterface.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites/ui/taxonomy/managing_taxons.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/ProductImage.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/Taxon.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/TaxonImage.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
| Q | A |
| --- | --- |
| New feature? | yes |
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/6561 |
> [ProductImage][TaxonImage] Code validation

- composer.json
- composer.lock
- src/Sylius/Bundle/CoreBundle/composer.json
- src/Sylius/Bundle/ResourceBundle/composer.json
| Related tickets | n/A
There is no BC break with 0.2
> Allow StateMachineBundle 0.3

- src/Sylius/Bundle/CoreBundle/EmailManager/ShipmentEmailManager.php
| Related tickets | fixes [this](https://scrutinizer-ci.com/g/Sylius/Sylius/issues/master/files/src/Sylius/Bundle/CoreBundle/EmailManager/ShipmentEmailManager.php?selectedLabels%5B0%5D=9&orderField=path&order=asc&honorSelectedPaths=0)
> Fix ShipmentInterface use statement in ShipmentEmailManager

- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_payments.html.twig
> [Admin][Order] Fix payment state label on order show page

- docs/cookbook/embedding-products.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
> [Documentation][Cookbook] How to embed a list of products?

- features/taxonomy/managing_taxons/adding_taxon.feature
- features/taxonomy/managing_taxons/adding_taxon_for_parent.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
- src/Sylius/Behat/Page/Admin/Taxon/CreateForParentPage.php
- src/Sylius/Behat/Page/Admin/Taxon/CreateForParentPageInterface.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/taxon.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/Partial/_treeWithButtons.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_form.html.twig
- src/Sylius/Bundle/TaxonomyBundle/Resources/config/services.xml
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/buttons.html.twig
- src/Sylius/Component/Taxonomy/Factory/TaxonFactory.php
- src/Sylius/Component/Taxonomy/Factory/TaxonFactoryInterface.php
- src/Sylius/Component/Taxonomy/Model/Taxon.php
- src/Sylius/Component/Taxonomy/spec/Factory/TaxonFactorySpec.php
- src/Sylius/Component/Taxonomy/spec/Model/TaxonSpec.php
> [Behat][Taxon] Adding taxon to specific parent

- Gulpfile.js
- app/migrations/Version20161102145826.php
- features/taxonomy/managing_taxons/deleting_taxon.feature
- features/taxonomy/managing_taxons/reordering_taxon.feature
- package.json
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePageInterface.php
- src/Sylius/Bundle/AdminBundle/Gulpfile.js
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/api.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/api/taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/private/js/delete-resource-action.js
- src/Sylius/Bundle/AdminBundle/Resources/private/js/move-taxon.js
- src/Sylius/Bundle/AdminBundle/Resources/private/js/semantic-ui-api-actions.js
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/Partial/_treeWithButtons.html.twig
- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonPositionType.php
- src/Sylius/Bundle/TaxonomyBundle/Resources/config/doctrine/model/Taxon.orm.xml
- src/Sylius/Bundle/TaxonomyBundle/Resources/config/services.xml
- src/Sylius/Component/Taxonomy/Model/Taxon.php
- src/Sylius/Component/Taxonomy/Model/TaxonInterface.php
- src/Sylius/Component/Taxonomy/spec/Model/TaxonSpec.php
> [Taxon] Changing order of the taxon

- docs/customization/controller.rst
- docs/customization/template.rst
- docs/customization/translation.rst
This is an update to PR#6549. 6549 was created on master, whereas this was made on its own branch, so it's a separate pull request. This incorporates all changes from 6549 as well as the two suggestions made by @TheMadeleine.
> Grammar updates to docs customization section

- src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php
Issue mentioned [here](https://github.com/Sylius/Sylius/pull/6600#discussion_r85987264)
> [BugFix] Correct total in payment description

- src/Sylius/Behat/Page/Admin/Product/CreateConfigurableProductPage.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
| Related tickets | mentioned in https://github.com/Sylius/Sylius/pull/6657#discussion_r86981478 |
> [Behat] Lower maximum waiting time for slug generation

- app/migrations/Version20161109102007.php
- docs/api/checkouts.rst
- docs/api/orders.rst
- docs/components/Order/models.rst
- src/Sylius/Behat/Context/Domain/ManagingOrdersContext.php
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/spec/Service/SharedSecurityServiceSpec.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_header.html.twig
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.Order.yml
- src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/OrderBundle/Resources/config/app/state_machine.yml
- src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Order.orm.xml
- src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
- src/Sylius/Bundle/OrderBundle/StateMachineCallback/CompleteCheckoutCallback.php
- src/Sylius/Bundle/OrderBundle/spec/StateMachineCallback/CompleteCheckoutCallbackSpec.php
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/account/order.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Show/_header.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Order/show.html.twig
- src/Sylius/Component/Order/Model/Order.php
- src/Sylius/Component/Order/Model/OrderInterface.php
- src/Sylius/Component/Order/spec/Model/OrderSpec.php
- tests/Responses/Expected/checkout/completed_order_response.json
| Related tickets | fixes #4022
> [Order] Renamed 'completedAt' to 'checkoutCompletedAt'

- features/user/managing_customers/resetting_customer_password.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPage.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/user/managing_customers.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/customer.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/_header.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/requestResetPassword.html.twig
- src/Sylius/Bundle/UserBundle/Controller/UserController.php
> [Admin][Customer] Reset customer's password from Admin panel

- PULL_REQUEST_TEMPLATE.md
Without this change by default we would end up with the same result as above. It is similar to first @Zales0123 solution from #6633. Now: 
> [Github] Yet another pull request template fix

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/api/taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/private/js/semantic-ui-api-actions.js
> [Taxon] Fix auto complete

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
> [Order] Changed OrderRepository queries to rely on cart state

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/order.yml
| Related tickets | fixes #6646, #6648 |
ToDo: Check for other occurrences of faulty sorting.
> [WIP][Grid] Fixed sortable properties' paths

- docs/cookbook/custom-promotion-rule.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
> [Documentation][Cookbook] How to add a custom promotion rule?

- docs/book/orders.rst
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_inventory.html.twig
- src/Sylius/Component/Core/Model/Product.php
- src/Sylius/Component/Core/Model/ProductInterface.php
- src/Sylius/Component/Core/spec/Model/ProductSpec.php
> [Core] Removed all occurrences of 'getFirstVariant' method

- features/product/managing_product_reviews/browsing_product_reviews.feature
- features/product/managing_product_reviews/editing_product_review.feature
- features/product/managing_product_reviews/recalculating_product_average_rating.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductReviewsContext.php
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Behat/Resources/config/suites/ui/product/managing_product_reviews.yml
- src/Sylius/Bundle/ReviewBundle/Resources/config/services.xml
> [Behat][ProductReview] Recalculate average rating after review rate change

- docs/book/architecture.rst
I stumbled over this sentence and thought it made more sense removing the first three words.
> removes superfluous words in documentation

- app/migrations/Version20161114105904.php
- src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Country.orm.xml
- src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Province.orm.xml
| Related tickets | fixes #4772 |
> [Province] Ensured provinces cannot exist without a country

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/promotion.yml
> [Admin] Added sorting to promotions

- src/Sylius/Behat/Page/Admin/Promotion/CreatePage.php
> [Behat] Fix JS tests related to promotions actions/rules

- features/user/managing_customers/browsing_orders_of_customer.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/customer.xml
- src/Sylius/Behat/Resources/config/suites/ui/user/managing_customers.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/customer.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/customer_order.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/customer.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Grid/Action/showOrders.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Order/Index/_breadcrumb.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/_header.html.twig
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
> [Admin][Customer] Browsing orders of a customer

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_details.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_details.html.twig
- src/Sylius/Bundle/CoreBundle/Form/Type/Product/ProductVariantType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/ProductVariant.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Admin] Added physical dimensions to variant/simple product views

- docs/cookbook/facebook-login.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
| Related tickets | requires #6714 |
> [Documentation][Cookbook] How to add Facebook login?

- docs/book/promotions.rst
| Q | A |
| --- | --- |
| Doc fix? | yes |
| New docs? | no |
| Related tickets | #5354 |
> [Documentation][Book] Promotion - usageLimit clarification

- src/Sylius/Behat/Context/Ui/EmailContext.php
- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/Model/OrderInterface.php
- src/Sylius/Component/Core/Taxation/Applicator/OrderShipmentTaxesApplicator.php
- src/Sylius/Component/Core/spec/Taxation/Applicator/OrderShipmentTaxesApplicatorSpec.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/4638
Based on https://github.com/Sylius/Sylius/pull/6662
> [BC Break] Remove getLastShipment method from Order

- src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePage.php
> [Promotion] Fix unhelpful exception message

- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.OrderItem.yml
| New feature?    | No |
| Related tickets | #6706 |
#6706 fix : order-item instead of item
> #6706 update Model.OrderItem.yml

- features/account/customer_account/viewing_orders_history/paying_for_order.feature
- src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
- src/Sylius/Behat/Page/Shop/Account/Order/IndexPage.php
- src/Sylius/Behat/Page/Shop/Account/Order/IndexPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/account/order.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Grid/Action/pay_for_order.html.twig
> [Account][Order] Be able to pay for unpaid orders

- app/migrations/Version20161115123347.php
> [Mailer] Added missing migration

- features/product/managing_product_variants/configuring_channel_and_currency_calculator_for_product_variant.feature
- features/product/managing_products/configuring_channel_and_currency_calculator_for_product.feature
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
| Related tickets | https://github.com/Sylius/Sylius/pull/6683 |
> [Behat] Price per channel and currency fixes

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/AdminUserExampleFactory.php
> [Core] Make example Admin great again

- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_summary.html.twig
> [Twig] Add missing currency variable

- features/cart/shopping_cart/adding_products_with_quantity_to_cart.feature
- features/cart/shopping_cart/changing_quantity_of_product_in_cart.feature
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Component/Core/Cart/Modifier/LimitingOrderItemQuantityModifier.php
- src/Sylius/Component/Core/spec/Cart/Modifier/LimitingOrderItemQuantityModifierSpec.php
- src/Sylius/Component/Order/Modifier/OrderItemQuantityModifier.php
- src/Sylius/Component/Order/spec/Modifier/OrderItemQuantityModifierSpec.php
> [Shop] Restrict the max quantity of units on add to cart

- features/product/managing_product_variants/generating_product_variant.feature
- features/product/managing_product_variants/generating_product_variant_validation.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Page/Admin/ProductVariant/GeneratePage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/GeneratePageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/product_variant.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Generate/_breadcrumb.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Generate/_form.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/generate.html.twig
- src/Sylius/Bundle/CoreBundle/Form/Type/Product/ProductVariantGenerationType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_product.yml
- src/Sylius/Bundle/CoreBundle/Resources/translations/flashes.en.yml
- src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ProductBundle/DependencyInjection/SyliusProductExtension.php
- src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/BuildProductVariantFormSubscriber.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductGenerateVariantsType.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductVariantGenerationType.php
- src/Sylius/Bundle/ProductBundle/Resources/config/services.xml
- src/Sylius/Bundle/ProductBundle/Resources/config/validation/ProductVariant.xml
- src/Sylius/Bundle/ProductBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/ProductBundle/Validator/ProductVariantCombinationValidator.php
- src/Sylius/Bundle/ProductBundle/spec/Form/EventSubscriber/BuildProductVariantFormSubscriberSpec.php
- src/Sylius/Bundle/ProductBundle/spec/Validator/ProductVariantCombinationValidatorSpec.php
- src/Sylius/Component/Product/Checker/ProductVariantsParityChecker.php
- src/Sylius/Component/Product/Checker/ProductVariantsParityCheckerInterface.php
- src/Sylius/Component/Product/Generator/ProductVariantGenerator.php
- src/Sylius/Component/Product/spec/Generator/ProductVariantGeneratorSpec.php
> [Product] Product variant generation

- features/shipping/managing_shipping_methods/adding_shipping_method.feature
- features/shipping/managing_shipping_methods/browsing_shipping_methods.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingShippingMethodsContext.php
> [Behat] Be consistent with shipping method naming

- features/shipping/managing_shipping_methods/adding_shipping_method.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingShippingMethodsContext.php
| Related tickets | fixes [comment](https://github.com/Sylius/Sylius/pull/6731#discussion_r88256631) |
> [Shipment] Fix master build and consistency

- docs/cookbook/custom-promotion-action.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
> [Documentation][Cookbook] How to add a custom promotion action?

- features/promotion/complex_promotions.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Behat/Page/Admin/ShippingMethod/CreatePage.php
- src/Sylius/Behat/Page/Admin/ShippingMethod/CreatePageInterface.php
- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Filter/ProductFilterConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Filter/TaxonFilterConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Rule/HasTaxonConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
| Related tickets | proposed in #6731, #6744 |
> [Core][Behat] Minor fixes from previous PRs

- features/promotion/managing_promotions/adding_promotion_with_action.feature
- features/promotion/managing_promotions/adding_promotion_with_action_in_different_currencies.feature
- features/promotion/managing_promotions/adding_promotion_with_filter.feature
- features/promotion/receiving_discount/receiving_fixed_discount_dependent_on_currency.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites/ui/promotion/managing_promotions.yml
- src/Sylius/Behat/Resources/config/suites/ui/promotion/receiving_discount.yml
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Action/CurrencyBasedDiscountAmountType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Action/FixedDiscountConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Action/UnitFixedDiscountConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Handler/CartCurrencyChangeHandler.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/handlers.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
- src/Sylius/Bundle/CoreBundle/spec/Handler/CartCurrencyChangeHandlerSpec.php
- src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Factory/PromotionActionFactory.php
- src/Sylius/Component/Core/Factory/PromotionActionFactoryInterface.php
- src/Sylius/Component/Core/Promotion/Action/FixedDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Action/UnitFixedDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/spec/Factory/PromotionActionFactorySpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/FixedDiscountPromotionActionCommandSpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/UnitFixedDiscountPromotionActionCommandSpec.php
> [PromotionAction] Configuring discounts in different currencies

- features/taxonomy/managing_taxons/taxon_validation.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
- src/Sylius/Bundle/TaxonomyBundle/Resources/config/validation/TaxonTranslation.xml
- src/Sylius/Bundle/TaxonomyBundle/Resources/translations/validators.en.yml
| Related tickets | fixes #3570 |
> [Taxon][Admin] Taxon slug validation

- src/Sylius/Bundle/GridBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/GridBundle/Tests/DependencyInjection/ConfigurationTest.php
> [Grid] Overwritable sorting declarations

- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Component/Core/Promotion/Filter/ProductFilter.php
- src/Sylius/Component/Core/Promotion/Filter/TaxonFilter.php
- src/Sylius/Component/Core/spec/Promotion/Filter/ProductFilterSpec.php
- src/Sylius/Component/Core/spec/Promotion/Filter/TaxonFilterSpec.php
> [Promotion] Fix product and taxon filter

- features/promotion/managing_promotions/adding_promotion_with_action_in_different_currencies.feature
- features/promotion/receiving_discount/receiving_fixed_discount_dependent_on_currency.feature
- src/Sylius/Bundle/CoreBundle/Handler/CartCurrencyChangeHandler.php
- src/Sylius/Bundle/CoreBundle/spec/Handler/CartCurrencyChangeHandlerSpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/UnitFixedDiscountPromotionActionCommandSpec.php
| Related tickets | fixes associated with PR #6734 
> [PromotionAction] Minor fixes

- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/_widget.html.twig
| Related tickets | fixes #6667 |
> [BugFix] Show items total in cart widget

- app/migrations/Version20161118090221.php
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_details.html.twig
- src/Sylius/Bundle/CoreBundle/Form/Type/Product/ProductVariantType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/ProductVariant.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Model/ProductVariant.php
- src/Sylius/Component/Core/Model/ProductVariantInterface.php
- src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php
> [Product] Removed 'originalPrice' field from ProductVariant

- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePageInterface.php
> [Behat] Improve product association scenario step

- docs/components/Resource/translation.rst
- src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Entity/Book.php
- src/Sylius/Component/Attribute/Model/Attribute.php
- src/Sylius/Component/Core/Model/Product.php
- src/Sylius/Component/Payment/Model/PaymentMethod.php
- src/Sylius/Component/Product/Model/Product.php
- src/Sylius/Component/Product/Model/ProductAttribute.php
- src/Sylius/Component/Product/Model/ProductOption.php
- src/Sylius/Component/Product/Model/ProductOptionValue.php
- src/Sylius/Component/Resource/Model/TranslatableInterface.php
- src/Sylius/Component/Resource/Model/TranslatableTrait.php
- src/Sylius/Component/Shipping/Model/ShippingMethod.php
- src/Sylius/Component/Taxonomy/Model/Taxon.php
| Related tickets | fixes #6739, fixes #5731 |
> Improve TranslatableTrait

- app/console
| Related tickets | Sylius/Sylius-Standard#137 |
> Use default Symfony env names

- features/taxonomy/managing_taxons/editing_taxon_slug.feature
> [Behat] Remove duplicated reason sentence beginning

- app/migrations/Version20161117163856.php
- features/channel/managing_channels/adding_channel.feature
- features/channel/managing_channels/channel_validation.feature
- features/channel/managing_channels/not_being_able_to_add_disabled_channel_when_no_other_exist.feature
- features/channel/managing_channels/selecting_default_tax_zone_for_channel.feature
- features/channel/managing_channels/selecting_locales_available_for_channel.feature
- features/channel/managing_channels/selecting_tax_calculation_strategy_for_channel.feature
- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
- src/Sylius/Behat/Page/Admin/Channel/CreatePage.php
- src/Sylius/Behat/Page/Admin/Channel/CreatePageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Channel/_form.html.twig
- src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php
- src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Form/Type/ChannelType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/Channel.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
- src/Sylius/Component/Core/Model/Channel.php
- src/Sylius/Component/Core/Model/ChannelInterface.php
- src/Sylius/Component/Core/Provider/ChannelBasedCurrencyProvider.php
- src/Sylius/Component/Core/Test/Services/DefaultChannelFactory.php
- src/Sylius/Component/Core/Test/Services/DefaultUnitedStatesChannelFactory.php
- src/Sylius/Component/Core/spec/Provider/ChannelBasedCurrencyProviderSpec.php
- src/Sylius/Component/Core/spec/Test/Services/DefaultChannelFactorySpec.php
- src/Sylius/Component/Core/spec/Test/Services/DefaultUnitedStatesChannelFactorySpec.php
- tests/DataFixtures/ORM/resources/channels.yml
- tests/DataFixtures/ORM/resources/checkout.yml
> [Core] Renamed 'defaultCurrency' to 'baseCurrency' on Channel model

- features/taxonomy/managing_taxons/reordering_taxon.feature
This scenario is failing from unknown reason in 90% of cases and makes the builds red. We have to bring back build stability so I temporary disabled this scenario from running.
> [Behat] Temporary disable unstable taxon scenario

- features/product/managing_product_variants/configuring_channel_and_currency_calculator_for_product_variant.feature
- features/product/managing_products/configuring_channel_and_currency_calculator_for_product.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
> [Behat] Fix confusing product price step

- package.json
Just cleaning up npm dependencies
> [Npm] Remove unused dependencies

- app/migrations/Version20161117144632.php
- features/checkout/assigning_customer_ip_address_to_places_order.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
- src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_customer.html.twig
- src/Sylius/Bundle/CoreBundle/Assigner/CustomerIpAssigner.php
- src/Sylius/Bundle/CoreBundle/Assigner/IpAssignerInterface.php
- src/Sylius/Bundle/CoreBundle/EventListener/OrderCustomerIpListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Order.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/CoreBundle/spec/Assigner/CustomerIpAssignerSpec.php
- src/Sylius/Bundle/CoreBundle/spec/EventListener/OrderCustomerIpListenerSpec.php
- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/Model/OrderInterface.php
- src/Sylius/Component/Core/spec/Model/OrderSpec.php
> [Admin][Order] Set customer IP on placed order

- features/product/managing_product_variants/adding_product_variant.feature
- features/product/managing_product_variants/product_variant_validation.feature
- features/product/managing_products/adding_product.feature
- features/product/managing_products/adding_product_with_associations.feature
- features/product/managing_products/adding_product_with_text_attribute.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Bundle/ProductBundle/Validator/UniqueSimpleProductCodeValidator.php
| BC breaks?      | no (yes, but only related to removing `generate_variants` from validation tree) |
Changes from #6768
> [Product] Product variant validation

- features/channel/managing_channels/editing_channel.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
- src/Sylius/Behat/Page/Admin/Channel/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Channel/UpdatePageInterface.php
- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/AddBaseCurrencySubscriber.php
- src/Sylius/Bundle/CoreBundle/Form/Type/ChannelType.php
- src/Sylius/Bundle/CoreBundle/spec/Form/EventSubscriber/AddBaseCurrencySubscriberSpec.php
> [Channel][Admin] Base currency immutable

- features/product/managing_product_options/managing_values_of_product_option.feature
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionType.php
> [Product] Disabled deleting of option value for now

- src/Sylius/Bundle/GridBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/GridBundle/Renderer/TwigGridRenderer.php
- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
- src/Sylius/Component/Grid/Definition/ArrayToDefinitionConverter.php
- src/Sylius/Component/Grid/Definition/Filter.php
- src/Sylius/Component/Grid/spec/Definition/FilterSpec.php
| Related tickets | fixes filters in admin after #6542 |
> [Grid] Allow to define custom template for filter

- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/AddBaseCurrencySubscriber.php
> [Channel][Admin] Minor fixes in AddBaseCurrencySubscriber

- src/Sylius/Behat/Context/Transform/ShippingMethodContext.php
> [Behat] Fix typo

- src/Sylius/Bundle/CoreBundle/Controller/OrderController.php
- src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
- src/Sylius/Bundle/ResourceBundle/Controller/Parameters.php
- src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/RequestConfigurationSpec.php
- src/Sylius/Bundle/UiBundle/Controller/SecurityController.php
- src/Sylius/Bundle/UiBundle/spec/Controller/SecurityControllerSpec.php
- src/Sylius/Bundle/UserBundle/Controller/SecurityController.php
- src/Sylius/Bundle/UserBundle/Controller/UserController.php
| Related tickets | extracted from #6738 |
> Remove deprecations from ParameterBag usage

- app/migrations/Version20161115141726.php
- features/product/managing_product_attributes/sorting_product_attributes_by_position.feature
- features/product/viewing_products/viewing_product_attributes.feature
- src/Sylius/Behat/Context/Setup/ProductAttributeContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductAttributesContext.php
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Behat/Page/Shop/Product/ShowPage.php
- src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_attribute.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductAttribute/_form.html.twig
- src/Sylius/Bundle/AttributeBundle/Resources/config/doctrine/model/Attribute.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/ProductBundle/DependencyInjection/SyliusProductExtension.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductAttributeType.php
- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/ProductAttribute.orm.xml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductAttribute.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Tab/_attributes.html.twig
- src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml
- src/Sylius/Bundle/UiBundle/Twig/SortByExtension.php
- src/Sylius/Bundle/UiBundle/composer.json
- src/Sylius/Bundle/UiBundle/spec/Fixtures/SampleInterface.php
- src/Sylius/Bundle/UiBundle/spec/Twig/SortByExtensionSpec.php
- src/Sylius/Component/Attribute/Model/Attribute.php
- src/Sylius/Component/Attribute/Model/AttributeInterface.php
- src/Sylius/Component/Attribute/spec/Model/AttributeSpec.php
- src/Sylius/Component/Product/Model/ProductAttributeInterface.php
- src/Sylius/Component/Product/Model/ProductAttributeValue.php
> [Shop][Admin] Product attributes sorting

- src/Sylius/Bundle/GridBundle/Doctrine/ORM/Driver.php
- src/Sylius/Bundle/GridBundle/Resources/config/services/integrations/doctrine/orm.xml
- src/Sylius/Bundle/GridBundle/spec/Doctrine/ORM/DriverSpec.php
> [GridBundle] Add multiple object managers support

- features/account/customer_account/viewing_orders_history/seeing_province_created_manually_in_order_history.feature
- features/account/customer_account/viewing_orders_history/viewing_order_recalculated_by_exchange_rate.feature
- features/cart/shopping_cart/adding_product_to_cart_with_prices_dependent_on_channel_and_currency.feature
- features/cart/shopping_cart/viewing_cart_summary_in_many_channels.feature
- features/channel/managing_channels/browsing_channels.feature
- features/checkout/seeing_order_summary/seeing_prices_recalculated_by_exchange_rate_on_order_summary.feature
- features/currency/handling_different_currencies_on_multiple_channels.feature
- features/currency/handling_disabled_currencies.feature
- features/currency/switching_current_currency.feature
- features/order/managing_orders/modifying_shipping_address/modifying_shipping_address_on_order_with_different_exchange_rate.feature
- features/order/managing_orders/modifying_shipping_address/modifying_shipping_address_validation.feature
- features/order/managing_orders/seeing_order_currency_on_show.feature
- features/order/managing_orders/seeing_order_prices_with_its_currencys_exchange_rate_on_show.feature
- features/order/managing_orders/seeing_orders_currency_on_index.feature
- features/order/managing_orders/seeing_orders_currency_with_different_exchange_rates_on_index.feature
- features/promotion/managing_promotions/adding_promotion_with_action_in_different_currencies.feature
- features/promotion/receiving_discount/receiving_fixed_discount_dependent_on_currency.feature
- src/Sylius/Behat/Context/Setup/ChannelContext.php
- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
- src/Sylius/Component/Core/Test/Services/DefaultChannelFactory.php
I open this PR once more time to avoid merge problems on ``currency-party``.
> [Behat] Fix base channel currency step

- .gitignore
- composer.json
- composer.lock
- etc/travis/suites/application/script/test-behat-with-cli
- etc/travis/suites/application/script/test-behat-with-javascript
- etc/travis/suites/application/script/test-behat-without-javascript
- etc/travis/suites/application/script/test-phpspec
- etc/travis/suites/application/script/test-phpunit
- etc/travis/suites/application/script/validate-behat-features
| Related tickets | introduced in #6822 |
> Bring back executables to /bin

- features/checkout/shipping_order/seeing_shipping_method_when_all_units_match_to_shipping_category.feature
- features/checkout/shipping_order/seeing_shipping_method_when_at_least_one_unit_match_to_shipping_method.feature
- features/checkout/shipping_order/seeing_shipping_method_when_no_units_match_to_shipping_category.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Setup/ShippingCategoryContext.php
- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Context/Transform/ShippingCategoryContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
- src/Sylius/Behat/Resources/config/services/contexts/transform.xml
- src/Sylius/Behat/Resources/config/suites/ui/checkout/checkout.yml
> [Shipment] Shipping methods available, based on the category of items in my cart

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Grid/Action/manageVariants.html.twig
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentMethodRepository.php
Based on #6828.
During m work on #5118 I have forgotten to add button to access this websites. Sorry! 💨
> [ProductVariant] Add generate button

- composer.json
- composer.lock
- src/Sylius/Bundle/GridBundle/Doctrine/ORM/DataSource.php
- src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php
| Bug fix?        | yes (kind of)
| Related tickets | unfixes #3836 (in fact, it is not really fixed right now too)
I have spent some time in order to find the best solution and bring back doctrine 2.5 support and this is my proposal. 
The second parameter of DoctrineORMAdapter defines if `fetchJoinCollection` variable. By default it is value is equal to true. According to [doctrine documentation](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/pagination.html) it should behave like this:
```
Paginating Doctrine queries is not as simple as you might think in the beginning. If you have complex fetch-join scenarios with one-to-many or many-to-many …
```
> [RFC] Bring back doctrine 2.5 support

- features/admin/dashboard.feature
- features/admin/dashboard_per_channel.feature
- features/user/managing_administrators/adding_administrator.feature
- features/user/managing_administrators/editing_administrator.feature
- src/Sylius/Behat/Context/Setup/AdminSecurityContext.php
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Ui/Admin/DashboardContext.php
- src/Sylius/Behat/Page/Admin/DashboardPage.php
- src/Sylius/Behat/Page/Admin/DashboardPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/admin/dashboard.yml
- src/Sylius/Bundle/AdminBundle/Controller/DashboardController.php
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/channel.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/Partial/_chooseChannel.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/index.html.twig
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Dashboard/DashboardStatisticsProvider.php
- src/Sylius/Component/Core/Dashboard/DashboardStatisticsProviderInterface.php
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
- src/Sylius/Component/Core/spec/Dashboard/DashboardStatisticsProviderSpec.php
- src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php
> [Admin] Dashboard statistics per channel

- src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php
> [Installer] Fix setup command

- src/Sylius/Bundle/CoreBundle/Resources/config/validation/ProductImage.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/TaxonImage.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
| Related tickets | partially #5744 |
> [Core] Added image size validation

- src/Sylius/Behat/Context/Ui/Admin/ManagingShippingMethodsContext.php
> [Behat] Fix typos

- src/Sylius/Bundle/CoreBundle/Collector/SyliusCollector.php
> [Collector] Fix multichannel handling

- src/Sylius/Bundle/CoreBundle/spec/Form/DataTransformer/ProductTaxonCollectionToTaxonCollectionTransformerSpec.php
- src/Sylius/Component/Core/spec/Factory/AddressFactorySpec.php
- src/Sylius/Component/Core/spec/Model/ProductSpec.php
- src/Sylius/Component/Core/spec/Model/ProductTaxonSpec.php
- src/Sylius/Component/Core/spec/Promotion/Filter/ProductFilterSpec.php
Some of annotation appear lately. Lets remove them. Continuation of #6453
> [Maintenance] Remove mixin annotation from spec

- docs/bundles/SyliusResourceBundle/configuration.rst
| Bug fix?           | yes |
| New feature?   | no |
> [Documentation][ResourceBundle] Fix configure several doctrine drivers.

- features/checkout/paying_for_order/paying_with_paypal_during_checkout.feature
- src/Sylius/Behat/Context/Ui/PaypalContext.php
- src/Sylius/Behat/Page/Shop/Order/ShowPage.php
- src/Sylius/Behat/Page/Shop/Order/ShowPageInterface.php
- src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
- src/Sylius/Bundle/UiBundle/Resources/translations/flashes.en.yml
- src/Sylius/Bundle/UiBundle/Resources/views/_flashes.html.twig
| BC breaks?      | fixes #6668 |
> [Payment] Notify about payment status

- app/migrations/Version20161124103833.php
- features/checkout/shipping_order/seeing_shipping_method_when_all_units_match_to_shipping_category.feature
- features/checkout/shipping_order/seeing_shipping_method_when_at_least_one_unit_match_to_shipping_method.feature
- features/checkout/shipping_order/seeing_shipping_method_when_no_units_match_to_shipping_category.feature
- features/product/managing_product_variants/adding_product_variant.feature
- features/product/managing_products/adding_product.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Transform/ShippingCategoryContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPageInterface.php
- src/Sylius/Behat/Page/Admin/ProductVariant/CreatePage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/CreatePageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/checkout/checkout.yml
- src/Sylius/Behat/Resources/config/suites/ui/product/managing_product_variants.yml
- src/Sylius/Behat/Resources/config/suites/ui/product/managing_products.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_details.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_details.html.twig
- src/Sylius/Bundle/CoreBundle/Form/Type/Product/ProductVariantType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Product.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Model/Product.php
- src/Sylius/Component/Core/Model/ProductInterface.php
- src/Sylius/Component/Core/Model/ProductVariant.php
- src/Sylius/Component/Core/Model/ProductVariantInterface.php
- src/Sylius/Component/Core/spec/Model/ProductSpec.php
- src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php
> [Admin] Move shipping category from Product to ProductVariant 

- src/Sylius/Bundle/UiBundle/Resources/translations/flashes.en.yml
> Improve flashes translation

- features/taxonomy/managing_taxons/reordering_taxon.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/Partial/_treeWithButtons.html.twig
> [Taxon] Cover reordering taxonomy

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxonExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/TaxonFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/TshirtProductFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/TaxonFixtureTest.php
| Related tickets | Fixes https://github.com/Sylius/Sylius/issues/6604 |
> [BugFix] Adjust taxon slugs and add T-Shirts as parent taxon

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_from_taxon.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
- src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php
- src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
> [BC Break] Initial cleanup in Product and Taxon repository

- features/promotion/applying_promotion_rules/receiving_discount_based_on_nth_order.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Transform/SharedStorageContext.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
> [BugFix] Nth order promotion should exclude cancelled orders

- features/admin/dashboard.feature
- features/promotion/applying_promotion_rules/receiving_discount_based_on_nth_order.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Transform/SharedStorageContext.php
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/checkout.yml
- src/Sylius/Bundle/CoreBundle/Context/SessionAndChannelBasedCartContext.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/CoreBundle/spec/Context/SessionAndChannelBasedCartContextSpec.php
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/account/order.yml
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
Based on https://github.com/Sylius/Sylius/pull/6876
> [BC Break] Initial Order repository cleanup

- features/order/managing_orders/modifying_billing_address/modifying_billing_address.feature
- features/order/managing_orders/modifying_billing_address/modifying_billing_address_on_order_with_cupon.feature
- features/order/managing_orders/modifying_billing_address/modifying_billing_address_on_order_with_different_exchange_rate.feature
- features/order/managing_orders/modifying_billing_address/modifying_billing_address_validation.feature
- features/order/managing_orders/modifying_billing_address/modifying_shipping_address_on_order_with_promotion.feature
- features/order/managing_orders/modifying_billing_address/modifying_shipping_address_on_order_with_taxes.feature
- features/order/managing_orders/modifying_shipping_address/modifying_shipping_address.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Transform/AddressContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Order/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Order/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/ui/order/modifying_address.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_addresses.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/update.html.twig
> [Admin][Order] Edit order billing address

- app/config/routing.yml
- app/config/security.yml
- features/admin/impersonating_customers.feature
- src/Sylius/Behat/Context/Setup/CustomerContext.php
- src/Sylius/Behat/Context/Ui/Admin/ImpersonatingCustomersContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPage.php
- src/Sylius/Behat/Page/Admin/Customer/ShowPageInterface.php
- src/Sylius/Behat/Page/Shop/HomePage.php
- src/Sylius/Behat/Page/Shop/HomePageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/ui/admin/impersonating_customers.yml
- src/Sylius/Bundle/AdminBundle/Controller/ImpersonateUserController.php
- src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.en.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/_content.html.twig
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php
- src/Sylius/Bundle/CoreBundle/Security/UserImpersonatorInterface.php
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
| Related tickets | closes #3925 |
> [Admin][Core] User switching

- app/config/config_test.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/parameters.yml
| Related tickets | fixes #6897 |
Just removed some params that aren't used anymore
> Removed unused parameters

- .gitignore
- bin/build-package
- bin/build-packages
- bin/clean-package
- bin/clean-packages
- bin/fix-coding-standards
- bin/install-package
- bin/install-packages
- bin/test-package
- bin/test-packages
- bin/validate-package
- bin/validate-packages
- etc/travis/suites/packages/install.sh
- etc/travis/suites/packages/script.sh
> Move custom scripts from etc/bin to bin

- src/Sylius/Bundle/AdminBundle/Controller/ImpersonateUserController.php
- src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
> [Core] Remove translator from ImpersonateUserController

- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
Order should be always placed in channel's base currency.
> [BugFix] Fix order fixtures

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_inventory.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_simpleBox.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/show.html.twig
> [Shop] Fixed 500 on listing a configurable product with no variants

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShopUserExampleFactory.php
> [Fixture] Make example Shop user great again

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services/integrations/translation.xml
> [RFC] Add default translation provider to ResourceBundle

- app/config/routing.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
> [Admin] Move impersonation routing since referer was added

- features/promotion/tracking_usage_limit/increasing_promotion_usage_after_placing_order.feature
- src/Sylius/Component/Core/Promotion/Action/FixedDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Action/PercentageDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Action/ShippingPercentageDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Action/UnitFixedDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/Promotion/Action/UnitPercentageDiscountPromotionActionCommand.php
- src/Sylius/Component/Core/spec/Promotion/Action/FixedDiscountPromotionActionCommandSpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/PercentageDiscountPromotionActionCommandSpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/UnitFixedDiscountPromotionActionCommandSpec.php
- src/Sylius/Component/Core/spec/Promotion/Action/UnitPercentageDiscountPromotionActionCommandSpec.php
- src/Sylius/Component/Promotion/Action/PromotionActionCommandInterface.php
- src/Sylius/Component/Promotion/Action/PromotionApplicator.php
- src/Sylius/Component/Promotion/spec/Action/PromotionApplicatorSpec.php
> [Core][Promotion] Apply promotion only when any action has been applied

- src/Sylius/Component/Promotion/Action/PromotionApplicator.php
- src/Sylius/Component/Promotion/spec/Action/PromotionApplicatorSpec.php
> [BugFix] Fix promotion applicator

- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Grid/Action/generateVariants.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Grid/Action/manageVariants.html.twig
> [Admin][Product] Hide generating variants for product without options

- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/BuildChannelBasedPromotionActionFormSubscriber.php
- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/BuildChannelBasedPromotionRuleFormSubscriber.php
| Related tickets | replaces https://github.com/Sylius/Sylius/pull/6935 |
> [Core] Fix wrong data passed in subscriber causing not displayed value

- features/product/managing_products/adding_text_attributes_to_existing_product.feature
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Attribute/attributesCollection.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_attributes.html.twig
- src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-product-attributes.js
| Related tickets | fixes #6796 and #6837 |
> [Admin][Product] Attributes fixes

- features/checkout/addressing_order/filling_shipping_and_billing_address_details_as_guest.feature
- src/Sylius/Bundle/CoreBundle/Form/Type/Customer/CustomerGuestType.php
> [Checkout] Fix checkout addressing

- .travis.yml
> [Maintenance] Temporary disable packages on PHP 5.6

- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/cart.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/_widget.html.twig
> Fix cart widget (broke cart summary page)

- src/Sylius/Bundle/CoreBundle/Checkout/CheckoutResolver.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Filter/ProductFilterConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Rule/ContainsProductConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Rule/CustomerGroupConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Rule/TotalOfItemsFromTaxonConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/installer.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
- src/Sylius/Bundle/ProductBundle/Controller/ProductAttributeController.php
- src/Sylius/Bundle/PromotionBundle/Controller/PromotionCouponController.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/CustomerGroupRuleChecker.php
- src/Sylius/Component/Customer/Model/Customer.php
- src/Sylius/Component/Customer/Model/CustomerInterface.php
| Related tickets | closes https://github.com/Sylius/Sylius/pull/6785 and https://github.com/Sylius/Sylius/pull/6066 |
> [BugFix] Random fixes and CustomerGroupRule

- README.md
> Adjust README to reflect Symfony3 support

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/promotion.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/boolean.html.twig
| Related tickets | fixes #6946 |
> [Grid] Add label to boolean filter template

- src/Sylius/Bundle/CoreBundle/Form/Type/Shipping/Calculator/ChannelBasedFlatRateConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Shipping/Calculator/ChannelBasedPerUnitRateConfigurationType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/Calculator/FlatRateConfigurationType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/Calculator/PerUnitRateConfigurationType.php
> [Admin][Shipping] Display appropriate currency symbol in amount field

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
> [Fixtures] Fixed product variant fixtures generation

- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-variants-prices.js
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_variantsPricing.html.twig
JavaScript was not running properly due to signs conflicts in html tags.
> [Shop] Handle properly prices of variants with quotation mark in name

- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-add-to-cart.js
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_login.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_addToCart.html.twig
- src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-api-login.js
> [Ui] Validation fix

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/customer.yml
> [ApiBundle] Minor fix for user fields disappearing 

- docs/customization/form.rst
| Related tickets | changes according to #6943, fixes #6894 |
UPDATE: **Works now!**
> [Documentation][Customization Guide] Forms update

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_taxonomy.html.twig
- src/Sylius/Bundle/CoreBundle/Form/Extension/ProductTypeExtension.php
> [Admin][Product] Fix saving and displaying main taxon on product

- docs/cookbook/cron-jobs.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
> [Documentation][Cookbook] CRON jobs basics

- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/ChannelFormSubscriber.php
- src/Sylius/Bundle/CoreBundle/Form/Extension/ChannelTypeExtension.php
- src/Sylius/Bundle/CoreBundle/spec/Form/EventSubscriber/ChannelFormSubscriberSpec.php
It fixes problem when sm1 chooses a base currency or a default locale on channel and doesn't choose it in the available currencies or locales for this channel.
> [Admin][Channel] Add subscriber to add baseCurrency and defaultLocale to channel's collections

- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/taxon.yml
- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonChoiceType.php
- src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
> [BugFix] Cleanup in TaxonRepository

- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/ChannelFormSubscriber.php
- src/Sylius/Bundle/CoreBundle/spec/Form/EventSubscriber/ChannelFormSubscriberSpec.php
> Improve ChannelFormSubscriber coverage

- features/product/managing_product_variants/product_variant_validation.feature
- features/product/managing_products/adding_product_with_prices_for_multiple_channels.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Page/Admin/ProductVariant/CreatePage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/CreatePageInterface.php
- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/AddUserFormSubscriber.php
- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/ChannelPricingsFormSubscriber.php
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/ChannelPricing.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/ProductVariant.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/CoreBundle/spec/Form/EventSubscriber/ChannelPricingsFormSubscriberSpec.php
> [BugFix] Fix validation on product variant

- src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml
| Related tickets | mentioned in #6988  |
Reordered and prioritized order processors. 
| Processor | Priority |
| ----------- | --------- |
| OrderAdjustmentsClearer  | 60 |   
| OrderShipmentProcessor   | 50 |  
| OrderPricesRecalculator  | 40 |   
| ShippingChargesProcessor | 30 |    
| OrderPromotionProcessor  | 20 |   
| OrderTaxesProcessor      | 10 |
| OrderPaymentProcessor    |  0 |
> Prioritized OrderProcessors

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_from_taxon.yml
My YAML parser was complaining about these weird characters in this file. I don't know what they were or how they got here, but we should probably strip them out.
> Remove strange characters

- features/promotion/applying_promotion_rules/receiving_discount_based_on_customer_group.feature
- features/promotion/managing_promotions/adding_promotion_with_rule.feature
- src/Sylius/Behat/Context/Setup/CustomerContext.php
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Context/Transform/CustomerGroupContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Behat/Resources/config/suites/ui/promotion/applying_promotion_rules.yml
- src/Sylius/Behat/Resources/config/suites/ui/promotion/managing_promotions.yml
- src/Sylius/Component/Core/Promotion/Checker/Rule/CustomerGroupRuleChecker.php
> Behat scenarios for customer group based promotions

- src/Sylius/Bundle/CoreBundle/Fixture/CustomerGroupFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/CustomerGroupExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShopUserExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/CustomerGroupFixtureTest.php
> [Core][Fixture] Add customer groups fixtures

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductReviewExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/ProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/ProductReviewFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/RandomReviewsFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/ProductReviewFixtureTest.php
It would be nice to have some product reviews created as sample data ;)
> [Core][Fixture] Product reviews fixtures

- src/Sylius/Bundle/UiBundle/Resources/views/Form/imagesTheme.html.twig
| Related tickets | fixes #7006 |
> [Ui][Admin] Fix displaying image form

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAssociationExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAssociationTypeExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/ProductAssociationFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/ProductAssociationTypeFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/SimilarProductAssociationFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/ProductAssociationFixtureTest.php
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/ProductAssociationTypeFixtureTest.php
> [Core][Fixture] Product associations and product association types fixtures

- docs/conf.py
- docs/requirements.txt
> [Travis] Fix documentation generation tests

- README.md
| Related tickets | mentioned in #6998 |
> Change example folder to avoid confusion

- docs/components/Payment/index.rst
> Payum url seems to be invalid

- src/Sylius/Bundle/AttributeBundle/Resources/config/services/attribute_types.xml
| Related tickets | fixes #7024 |
Just fixed the typos for those arguments
> Fix issue-7024. Typos in services definition

- features/addressing/managing_zones/adding_zone.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingZonesContext.php
- src/Sylius/Behat/Page/Admin/Zone/CreatePage.php
- src/Sylius/Behat/Page/Admin/Zone/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/Zone/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Zone/UpdatePageInterface.php
- src/Sylius/Bundle/AddressingBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Zone/_form.html.twig
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_addressing.yml
| Related tickets | partially https://github.com/Sylius/Sylius/issues/7011 |
First step to make zones great again according to mentioned issue.
> [Admin][Zone] Manage zones scopes

- features/account/customer_account/address_book/address_province_validation.feature
- features/checkout/addressing_order/choosing_billing_and_shipping_address_from_address_book.feature
- src/Sylius/Behat/Context/Setup/GeographicalContext.php
- src/Sylius/Behat/Context/Transform/AddressContext.php
- src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePage.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
- src/Sylius/Behat/Resources/config/services/contexts/transform.xml
- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-address-book.js
- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-province-field.js
| Related tickets | fixes #6651 |
> [Shop] Fix disappearing provinces from address forms

- composer.json
- composer.lock
| BC breaks?      | yes (only if anyone uses `Sylius\*\*\Tests` in their application based on Sylius at the same time with classmap autoloader or runs `Sylius/Sylius` without dev dependencies) |
| Related tickets | fixes https://github.com/Sylius/Sylius-Standard/issues/146 |
> Improve Composer autoloader

- app/Resources/TwigBundle/views/Exception/error404.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/error404.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Shop] Custom 404 error page

- .travis.yml
- etc/travis/suites/common/before_install.sh
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
Run the travis test suite in PHP 7.1 as well. This might help to spot errors like #6752
> [Travis] Enable PHP 7.1 for tests

- src/Sylius/Bundle/CoreBundle/Fixture/AddressFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/AddressExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
> [Core] Fixtures for addresses

- docs/customization/grid.rst
- docs/customization/index.rst
- docs/customization/map.rst.inc
Before having a full customization guide to grids we need to fix that behaviour of variableNodes in yaml configs -> #6637 .
> [Documentation][Customization Guide] Grids

- docs/bundles/SyliusGridBundle/filters.rst
- features/order/managing_orders/filtering_orders_by_channel.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Order/IndexPage.php
- src/Sylius/Behat/Page/Admin/Order/IndexPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/order.yml
- src/Sylius/Bundle/GridBundle/Form/Type/Filter/EntityFilterType.php
- src/Sylius/Bundle/GridBundle/Resources/config/services/filters.xml
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/entity.html.twig
- src/Sylius/Component/Grid/Filter/EntityFilter.php
- src/Sylius/Component/Grid/spec/Filter/EntityFilterSpec.php
> [Grid][Admin][Order] Entity filter on orders' list

- features/product/managing_products/editing_product_attributes.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
- src/Sylius/Bundle/ProductBundle/Controller/ProductAttributeController.php
- src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-product-attributes.js
Bug caused some nasty errors on ajax request.
> [Admin][Product][Attribute] Fix adding existing attributes to product bug

- UPGRADE.md
| Related tickets | documents #7044 |
> Create UPGRADE.md with boilerplate

- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/links.html.twig
> [Grid][Action] Fix visible option in links action template

- src/Sylius/Behat/Context/Setup/ShippingContext.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
| BC breaks?      | yes (but only in behats) |
Second part of #7055. This should be separate PRs as it will make them easier to pass.
> [Shipping] [Behats] [Refactor] Setup shipping context refactoring

- features/order/managing_orders/modifying_billing_address/modifying_shipping_address_on_order_with_taxes.feature
Previously, this feature has not been checked
> [Feature] Wrong feature tag

- src/Sylius/Bundle/CoreBundle/Form/Extension/PromotionFilterCollectionTypeExtension.php
> [Admin][Promotion] Remove duplicated filter label

- Gulpfile.js
> [Gulp] Add gulp watch

- src/Sylius/Bundle/CoreBundle/Tests/Fixture/AddressFixtureTest.php
- src/Sylius/Bundle/ShopBundle/Tests/DependencyInjection/ConfigurationTest.php
> [Test] Added AddressFixtureTest to Core and fixed ShopBundle's ConfigurationTest

- src/Sylius/Behat/Page/Shop/HomePage.php
Introduced in e4728efab9b765680da92fb0df5180dabe458f64
> [Behat] Remove dangling semicolon

- app/Resources/TwigBundle/views/Exception/error.html.twig
- app/Resources/TwigBundle/views/Exception/error500.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/error.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/error500.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Shop] Custom errors pages

- features/currency/managing_exchange_rates/filtering_exchange_rates_by_currency.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingExchangeRatesContext.php
- src/Sylius/Behat/Page/Admin/ExchangeRate/IndexPage.php
- src/Sylius/Behat/Page/Admin/ExchangeRate/IndexPageInterface.php
- src/Sylius/Behat/Page/Admin/Order/IndexPage.php
- src/Sylius/Behat/Resources/config/services/pages/admin/exchange_rate.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/exchange_rate.yml
- src/Sylius/Bundle/GridBundle/Form/Type/Filter/EntityFilterType.php
- src/Sylius/Component/Grid/Filter/EntityFilter.php
- src/Sylius/Component/Grid/spec/Filter/EntityFilterSpec.php
> [Admin][ExchangeRate] Filtering exchange rates by a specific currency

- composer.json
- composer.lock
- src/Sylius/Behat/Service/Mocker/PaypalApiMocker.php
> [Paypal] Mock http client interface instead of concrete class

- src/Sylius/Bundle/GridBundle/Form/Type/Filter/EntityFilterType.php
- src/Sylius/Component/Grid/Filter/EntityFilter.php
| Related tickets | fixes after #7073 |
> [Grid] Fix entity filter to accept only fields option

- src/Sylius/Component/Core/Model/ChannelPricing.php
> Remove final from ChannelPricing

- docs/book/products/products.rst
> [Doc][Product] Update product with options snippet

- src/Sylius/Bundle/CoreBundle/Form/Type/Product/ChannelPricingType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Shipping/Calculator/ChannelBasedFlatRateConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Shipping/Calculator/ChannelBasedPerUnitRateConfigurationType.php
- src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentMethodChoiceType.php
- src/Sylius/Bundle/PromotionBundle/Form/Type/Action/FixedDiscountConfigurationType.php
- src/Sylius/Bundle/PromotionBundle/Form/Type/Action/UnitFixedDiscountConfigurationType.php
- src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionRuleChoiceType.php
It is a BC, but this one should be cleaned anyway, as it is a dead code
> [Forms] Remove getName clean up survivors

- docs/book/architecture/events.rst
- docs/book/architecture/index.rst
- docs/book/architecture/map.rst.inc
- docs/book/customers/customer_and_shopuser.rst
- docs/book/orders/checkout.rst
- docs/book/orders/payments.rst
- docs/book/orders/shipments.rst
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/shipment.yml
Docs update + **[AdminBundle] Events on payment complete and shipment ship added.**
> [Documentation][Book] Events

- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
> Remove drivers configuration where possible

- src/Sylius/Bundle/ResourceBundle/Form/Type/ResourceTranslationsType.php
> [Resource] Remove unneeded code

- UPGRADE.md
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_payment.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml
- src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/Model/OrderInterface.php
- src/Sylius/Component/Core/OrderProcessing/OrderPaymentProcessor.php
- src/Sylius/Component/Core/Payment/Exception/NotProvidedOrderPaymentException.php
- src/Sylius/Component/Core/Payment/Provider/OrderPaymentProvider.php
- src/Sylius/Component/Core/Payment/Provider/OrderPaymentProviderInterface.php
- src/Sylius/Component/Core/spec/Model/OrderSpec.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderPaymentProcessorSpec.php
- src/Sylius/Component/Core/spec/Payment/Provider/OrderPaymentProviderSpec.php
- src/Sylius/Component/Payment/Model/Payment.php
- src/Sylius/Component/Payment/spec/Model/PaymentSpec.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/7003 |
> [Payment] Fix default payment state

- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_header.html.twig
| Related tickets | fixes #7100 |
> [Admin][UX] Show full date-time in order summary page

- features/inventory/managing_inventory/browsing_inventory.feature
- features/inventory/managing_inventory/filtering_inventory_by_code.feature
- features/inventory/managing_inventory/filtering_inventory_by_name.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingInventoryContext.php
- src/Sylius/Behat/Page/Admin/Inventory/IndexPage.php
- src/Sylius/Behat/Page/Admin/Inventory/IndexPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/admin.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/inventory.xml
- src/Sylius/Behat/Resources/config/suites/ui/inventory/managing_inventory.yml
- src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/inventory.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/inventory.yml
- src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Inventory/Index/_breadcrumb.html.twig
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductVariantRepository.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_product.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Repository/ProductVariantRepositoryInterface.php
> [Admin][Inventory] Inventory index page in admin panel

- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/inventory.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_variant.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductVariantRepository.php
- src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php
- src/Sylius/Component/Core/Repository/ProductVariantRepositoryInterface.php
- src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php
> [Critical][ProductVariant] Add locale to product variant query builders

- docs/bundles/SyliusGridBundle/custom_filter.rst
> [DOC][GridBundle] fix customer filter documentation

- src/Sylius/Behat/Context/Ui/Admin/ManagingCurrenciesContext.php
> [Behat] Cleaned up leftover steps from exchange rate rework

- src/Sylius/Behat/Context/Setup/UserContext.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
| BC breaks?      | yes (in Behats) |
It is dead code anyway. ☠️
> [Behat] Remove address coupling in user context

- features/product/managing_products/product_validation.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Bundle/ProductBundle/Validator/UniqueSimpleProductCodeValidator.php
- src/Sylius/Bundle/ProductBundle/spec/Validator/UniqueSimpleProductCodeValidatorSpec.php
| Related tickets | fixes #7005  |
> [Product] Do not show code validation message during update

- src/Sylius/Behat/Page/Shop/Account/ChangePasswordPage.php
- src/Sylius/Behat/Page/Shop/Account/DashboardPage.php
- src/Sylius/Behat/Page/Shop/Account/ProfileUpdatePage.php
> Fix typo in my email address

- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/context.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
- src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
- src/Sylius/Bundle/TaxonomyBundle/Resources/config/services.xml
> [Core][Promotion][Taxonomy] Unify decorated services ids

- docs/book/orders/orders.rst
> [Documentation][Book][Orders] Fix

- features/product/managing_product_association_types/filtering_product_association_types.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductAssociationTypesContext.php
- src/Sylius/Behat/Page/Admin/ProductAssociationType/IndexPage.php
- src/Sylius/Behat/Page/Admin/ProductAssociationType/IndexPageInterface.php
- src/Sylius/Behat/Resources/config/services/pages/admin/product_association_type.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_association_type.yml
| Related tickets | fixes after #7134 |
> [ProductAssociationType] Fix filtering product association types by name

- UPGRADE.md
- src/Sylius/Component/Core/StateResolver/OrderPaymentStateResolver.php
- src/Sylius/Component/Core/StateResolver/OrderShippingStateResolver.php
- src/Sylius/Component/Core/StateResolver/OrderStateResolver.php
| Related tickets | fixes #7137 |
> [Core] Finalize state resolvers

- app/migrations/Version20161221133514.php
- features/product/managing_product_options/sorting_product_options_by_position.feature
- src/Sylius/Behat/Context/Setup/ProductOptionContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductOptionsContext.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_option.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductOption/_form.html.twig
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionType.php
- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/ProductOption.orm.xml
- src/Sylius/Bundle/ProductBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Product/Model/ProductOption.php
- src/Sylius/Component/Product/Model/ProductOptionInterface.php
- src/Sylius/Component/Product/spec/Model/ProductOptionSpec.php
> [ProductOption] Sorting product options by position

- src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
| Related tickets | fixes #7156  |
It just a proposal and a hot fix. I didn't find a better one. But without it every Sylius based project is broken so it is still better than nothing.
Another possible solution is to this config dynamically in extension. Or extract this config to main app folder and prepare a documentation how to add it. 
Another thing. Should we extract this config to resource bundle?
> [RFC] [Core] [HotFix] Add core bundle root dir parameter

- src/Sylius/Behat/Context/Setup/ProductOptionContext.php
| Related tickets | fixes after review #7147 |
> [Behat][ProductOption] Minor fix after review

- features/checkout/addressing_order/having_default_address_preselected.feature
- src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
- src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
- src/Sylius/Component/Core/spec/Cart/Context/ShopBasedCartContextSpec.php
> [Core][Cart] Having default address preselected

- src/Sylius/Behat/Page/Admin/CustomerGroup/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Promotion/UpdatePage.php
- src/Sylius/Behat/Page/Admin/TaxCategory/UpdatePage.php
- src/Sylius/Behat/Page/Admin/TaxRate/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
- src/Sylius/Behat/Page/Shop/Account/Order/IndexPage.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
- src/Sylius/Bundle/CoreBundle/Command/CancelUnpaidOrdersCommand.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/ChangePaymentMethodType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Order/AddToCartType.php
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/CartItemAvailabilityValidator.php
- src/Sylius/Bundle/CurrencyBundle/SyliusCurrencyBundle.php
- src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExpressionVisitor.php
- src/Sylius/Bundle/LocaleBundle/SyliusLocaleBundle.php
- src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
- src/Sylius/Bundle/OrderBundle/Factory/AddToCartCommandFactory.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterResourceRepositoryPass.php
- src/Sylius/Bundle/ResourceBundle/Form/DataTransformer/RecursiveTransformer.php
- src/Sylius/Bundle/ResourceBundle/Tests/DependencyInjection/Compiler/RegisterResourceRepositoryPassTest.php
- src/Sylius/Component/Payment/Factory/PaymentFactory.php
> [CS] Fix invalid inheritdoc comments to keep convention

- src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
| Related tickets | fixes #7158 |
> Improve loading Gedmo Loggable behaviour in CoreBundle

- features/promotion/receiving_discount/applying_promotion_with_expiration_date.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
> [Promotion] Behats for start and ends date for promotion

- app/migrations/Version20161223091334.php
- features/product/managing_product_variants/sorting_product_variants_within_product_by_position.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Page/Admin/ProductVariant/IndexPage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/IndexPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-move-product-variant.js
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Grid/Action/updatePositions.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Grid/Field/position.html.twig
- src/Sylius/Bundle/CoreBundle/Controller/ProductVariantController.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_product.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
- src/Sylius/Component/Product/Model/ProductVariant.php
- src/Sylius/Component/Product/Model/ProductVariantInterface.php
- src/Sylius/Component/Product/spec/Model/ProductVariantSpec.php
> [Admin][ProductVariant] Sorting variants within a product by position

- composer.lock
With v1.1 ApiTestCase goes faster and has less memory leaks.
> [Maintenance] Bump version of ApiTestCase

- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterFormBuilderPass.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineORMDriver.php
- src/Sylius/Bundle/ResourceBundle/Form/Type/DefaultResourceType.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml
- src/Sylius/Bundle/ResourceBundle/Resources/config/services/integrations/doctrine/orm.xml
- src/Sylius/Bundle/ResourceBundle/SyliusResourceBundle.php
- src/Sylius/Bundle/ResourceBundle/test/app/config/resources.yml
- src/Sylius/Bundle/ResourceBundle/test/app/config/routing.yml
- src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Entity/ComicBook.php
- src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Resources/config/doctrine/ComicBook.orm.yml
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/Controller/ComicBookApiTest.php
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/DataFixtures/ORM/comic_books.yml
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/DependencyInjection/SyliusResourceExtensionTest.php
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/Responses/Expected/comic-books/create_response.json
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/Responses/Expected/comic-books/index_response.json
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/Responses/Expected/comic-books/show_response.json
| Related tickets | partially #7041 |
> [Resource] Bring back a default form type

- features/product/managing_products/editing_product.feature
- features/product/managing_products/product_validation.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPageInterface.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/Product.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/ProductVariant.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasAllPricesDefined.php
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasAllPricesDefinedValidator.php
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasAllVariantPricesDefined.php
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasAllVariantPricesDefinedValidator.php
- src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/SimpleProductSubscriber.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductVariantGenerationType.php
- src/Sylius/Bundle/ProductBundle/Resources/config/validation/Product.xml
> [Core] Not specified price error polishing

- features/inventory/managing_inventory/decreasing_invetory_below_on_hold_validation.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/inventory/managing_inventory.yml
> [Inventory] Changing inventory after placing an order 

- features/order/managing_orders/seeing_orders_currency_on_index.feature
- features/user/managing_customers/seeing_customer_details.feature
- features/user/managing_customers/seeing_province_created_manually_on_customer_details_page.feature
- src/Sylius/Behat/Context/Setup/AddressContext.php
- src/Sylius/Behat/Context/Transform/AddressContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Resources/config/services/contexts/transform.xml
- src/Sylius/Behat/Resources/config/suites/ui/user/managing_customers.yml
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/AddressExampleFactory.php
| BC breaks?      | yes (but only in behats) |
Starting refactoring of Behat to make code more maintainable.
> [Behat] Use Address example factory in Address transformer

- features/user/managing_customers/seeing_province_created_manually_on_customer_details_page.feature
| Related tickets | fixes [comment](https://github.com/Sylius/Sylius/pull/7055#discussion_r94738234) |
> [Behat] Minor semantical fix

- src/Sylius/Bundle/ApiBundle/Form/Type/OrderType.php
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerChoiceType.php
- tests/Controller/OrderApiTest.php
- tests/DataFixtures/ORM/resources/orders.yml
- tests/Responses/Expected/order/create_response.json
- tests/Responses/Expected/order/create_validation_fail_response.json
- tests/Responses/Expected/order/index_response.json
- tests/Responses/Expected/order/show_response.json
| Related tickets | fixes #7198, fixes #7194  |
> [API] Order type fixes

- src/Sylius/Bundle/UserBundle/Controller/UserController.php
> Reset password request do not need template when API call

- docs/book/architecture/architecture.rst
- docs/cookbook/disabling-shop-admin-api.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
> [Documentation][Cookbook] How to disable default shop, admin or API of Sylius?

- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePageInterface.php
- src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_payments.html.twig
- src/Sylius/Component/Core/StateResolver/CheckoutStateResolver.php
- src/Sylius/Component/Core/spec/StateResolver/CheckoutStateResolverSpec.php
> [Shop] Minor fixes to free order 

- features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_an_item_in_order.feature
- features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_an_item_in_order_when_tax_rate_included_in_price.feature
- features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_shipping.feature
- features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_shipping_when_tax_rate_included_in_price.feature
- features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_whole_order.feature
- features/taxation/applying_taxes/applying_correct_taxes_for_order_with_discount_for_whole_order_when_tax_rate_included_in_price.feature
- src/Sylius/Behat/Resources/config/suites/ui/taxation/applying_taxes.yml
> [Promotion][Taxation] Check correctness of applying taxes for order with a promotion

- docs/book/installation/index.rst
- docs/book/installation/installation.rst
- docs/book/installation/map.rst.inc
- docs/book/installation/vagrant_installation.rst
> [Documentation][Book] Installation via Vagrant

- tests/Controller/ChannelApiTest.php
- tests/Controller/CountryApiTest.php
- tests/Controller/CurrencyApiTest.php
- tests/Controller/LocaleApiTest.php
- tests/Controller/OrderApiTest.php
- tests/Controller/ProvinceApiTest.php
- tests/Controller/ShippingCategoryApiTest.php
- tests/Controller/TaxCategoryApiTest.php
- tests/Controller/ZoneApiTest.php
> [Tests][CS] Make API test methods names consistent

- src/Sylius/Bundle/UserBundle/spec/EventListener/UserLastLoginSubscriberSpec.php
| Related tickets | missing test from #7228  |
> [User] Add missing test for UserLastLoginSubscriber

- src/Sylius/Bundle/AddressingBundle/DependencyInjection/SyliusAddressingExtension.php
- src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
- src/Sylius/Bundle/AttributeBundle/DependencyInjection/SyliusAttributeExtension.php
- src/Sylius/Bundle/ChannelBundle/DependencyInjection/SyliusChannelExtension.php
- src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
- src/Sylius/Bundle/CurrencyBundle/DependencyInjection/SyliusCurrencyExtension.php
- src/Sylius/Bundle/CustomerBundle/DependencyInjection/SyliusCustomerExtension.php
- src/Sylius/Bundle/FixturesBundle/DependencyInjection/SyliusFixturesExtension.php
- src/Sylius/Bundle/GridBundle/DependencyInjection/SyliusGridExtension.php
- src/Sylius/Bundle/InventoryBundle/DependencyInjection/SyliusInventoryExtension.php
- src/Sylius/Bundle/LocaleBundle/DependencyInjection/SyliusLocaleExtension.php
- src/Sylius/Bundle/MailerBundle/DependencyInjection/SyliusMailerExtension.php
- src/Sylius/Bundle/MoneyBundle/DependencyInjection/SyliusMoneyExtension.php
- src/Sylius/Bundle/OrderBundle/DependencyInjection/SyliusOrderExtension.php
- src/Sylius/Bundle/PaymentBundle/DependencyInjection/SyliusPaymentExtension.php
- src/Sylius/Bundle/PayumBundle/DependencyInjection/SyliusPayumExtension.php
- src/Sylius/Bundle/ProductBundle/DependencyInjection/SyliusProductExtension.php
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/SyliusPromotionExtension.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php
- src/Sylius/Bundle/ReviewBundle/DependencyInjection/SyliusReviewExtension.php
- src/Sylius/Bundle/ShippingBundle/DependencyInjection/SyliusShippingExtension.php
- src/Sylius/Bundle/ShopBundle/DependencyInjection/SyliusShopExtension.php
- src/Sylius/Bundle/TaxationBundle/DependencyInjection/SyliusTaxationExtension.php
- src/Sylius/Bundle/TaxonomyBundle/DependencyInjection/SyliusTaxonomyExtension.php
- src/Sylius/Bundle/ThemeBundle/DependencyInjection/SyliusThemeExtension.php
- src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
The first parameter is not used in default implementation.
> Simplify getConfiguration() call in extensions

- app/migrations/Version20170110120125.php
- features/payment/managing_payment_methods/preventing_deletion_of_used_payment_method.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentMethodsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites/ui/payment/managing_payment_methods.yml
- src/Sylius/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.xml
| Related tickets | fixes #7211 |
> Fixed #7211: now can't delete a used PaymentMethod

- features/checkout/seeing_order_summary/seeing_shipping_discount_on_order_summary_page.feature
- features/order/managing_orders/seeing_order_aggregated_discounts.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Context/Ui/CheckoutContext.php
- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
- src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_totals.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
> [Promotion][Shop][Admin] Seeing shipping promotion on order summary in admin and in shop

- app/config/security.yml
- docs/api/authorization.rst
- docs/cookbook/api.rst
- src/Sylius/Bundle/ApiBundle/Resources/config/routing.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/ReviewBundle/test/app/config/config.yml
- src/Sylius/Bundle/UserBundle/test/app/config/config.yml
- tests/Controller/OauthTokenApiTest.php
| Related tickets | fixes [comment](https://github.com/Sylius/Sylius/pull/7243#discussion_r95876441) |
> [Api] Remove version from oauth

- src/Sylius/Component/Product/Model/Product.php
- src/Sylius/Component/Product/spec/Model/ProductSpec.php
Fix suggested by @michalmarcinkowski in #7196 ; thanks @Pitoune for noticing the bug, and @michalmarcinkowski for helping find a pragmatic solution ;)
| Related tickets | fixes #7196 and #7189  |
> Fixed Product model Attributes-related methods

- features/product/managing_products/product_validation.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Bundle/ProductBundle/Resources/config/validation/ProductTranslation.xml
- src/Sylius/Bundle/ProductBundle/Resources/translations/validators.en.yml
| Related tickets | fixes #7245 |
> [Product] Unique contraint on slug

- UPGRADE.md
- features/product/managing_product_reviews/recalculating_product_average_rating.feature
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_product_review.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/ReviewBundle/DependencyInjection/SyliusReviewExtension.php
- src/Sylius/Bundle/ReviewBundle/Resources/config/integrations/doctrine/orm.xml
- src/Sylius/Bundle/ReviewBundle/Resources/config/services.xml
| Related tickets | fixes #7250  |
> [Review] Remove orm coupling and register recalculator dynamically. 

- docs/api/channels.rst
- docs/api/checkouts.rst
- docs/api/customers.rst
- docs/api/orders.rst
- docs/api/payments.rst
- docs/api/products.rst
- docs/api/promotions.rst
- docs/api/shipments.rst
- docs/api/users.rst
I will iterate over docs later, but for sure I have forgotten to update docs to #7253 changes
> [Doc] Use snake case in api docs

- docs/book/architecture/events.rst
| Related tickets | Documentation fix |
> Fix command path

- docs/customization/factory.rst
- docs/customization/index.rst
- docs/customization/map.rst.inc
| Related tickets | partially #4226, mentioned in #7004 |
> [Documentation] Customization Guide: Factories

- docs/bundles/SyliusGridBundle/custom_filter.rst
- docs/bundles/SyliusGridBundle/your_first_grid.rst
- docs/bundles/SyliusMailerBundle/your_first_email.rst
- docs/cookbook/custom-email.rst
- docs/cookbook/custom-promotion-action.rst
- docs/cookbook/custom-promotion-rule.rst
- docs/customization/controller.rst
- docs/customization/flash.rst
- docs/customization/translation.rst
> [Documentation][Customization] Apply Symfony best practices

- docs/api/shipping_categories.rst
> [Documentation] Coherent doc title

- docs/customization/validation.rst
> [Documentation][Customization] Validation messages reference

- docs/book/installation/index.rst
- docs/book/installation/map.rst.inc
- docs/book/installation/upgrading.rst
> [Documentation][Book][Installation] Upgrading Sylius

- docs/cookbook/images-gridfs.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
| Related tickets | mentioned in https://github.com/Sylius/Sylius/issues/6995#issuecomment-265088881 |
> [Documentation] Store and load images with MongoDB's GridFS

- docs/api/authorization.rst
- docs/api/orders.rst
> [WIP] [Docs][API] Misc fixes

- docs/api/index.rst
- docs/behat/index.rst
- docs/contributing/index.rst
- docs/cookbook/index.rst
- docs/index.rst
> [Documentation] Unify main chapters' titles

- docs/book/index.rst
- docs/book/orders/index.rst
- docs/index.rst
> [Documentation] Enhance descriptions of chapters in the Book + index

- docs/book/installation/installation.rst
- docs/book/installation/requirements.rst
> [Docs] Fix list of writable directories in requirements chapter

- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/boolean.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/entity.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/string.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/buttons.html.twig
> [Ui] Fixed doubled `|trans` calls

- features/order/managing_orders/filtering_orders_by_total_in_different_currencies.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
> [Behat] Fix OrderContext

- docs/book/products/attributes.rst
> [Docs] Added missing attribute types

- UPGRADE.md
- app/config/security.yml
> [Security] Remember me

- docs/book/configuration/currencies.rst
It looked pretty weird before 😄
> [Docs] Fix bad looking FQCN

- composer.lock
> [Composer] Update composer lock

- docs/cookbook/creating-extension.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
> [Documentation] Creating your own Sylius extension

- docs/book/index.rst
- docs/book/map.rst.inc
> [Documentation][Book] Fix Themes chapter

- src/Sylius/Bundle/GridBundle/Doctrine/DBAL/DataSource.php
- src/Sylius/Bundle/GridBundle/Doctrine/ORM/DataSource.php
- src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/DataSource.php
> Prevent querying the database twice while using grids

- docs/customization/repository.rst
> [Documentation][Customization] Repositories Fix

- docs/book/orders/checkout.rst
> [Docs] Minor fixes in checkout docs

- docs/book/themes/themes.rst
| Related tickets | mentioned in #7304 |
Thanks to suggestions of @gabiudrescu! 👍
> [Documentation][Book] When should you use Themes?

- src/Sylius/Bundle/ApiBundle/Form/Type/CustomerProfileType.php
- src/Sylius/Bundle/ApiBundle/Form/Type/ProductType.php
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/customer.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/form.xml
> [API] Change forms declaration and add form.xml

- docs/components/Order/models.rst
> [Documentation] Update order model information

- docs/customization/model.rst
> [Documentation][Customization] Translatable Models

- docs/api/customers.rst
- docs/api/products.rst
- docs/api/shipping_categories.rst
I have changed two things here: 
* `“` -> `"` to prevent the the following error: ```curl: (6) Could not resolve host: application```
* Add `\` to be able to copy&paste curls and easily edit them in terminal
> [Documentation] [Maintenance] Fix wrong or missing special chars

- UPGRADE.md
- src/Sylius/Bundle/AddressingBundle/SyliusAddressingBundle.php
- src/Sylius/Bundle/AdminBundle/DependencyInjection/SyliusAdminExtension.php
- src/Sylius/Bundle/AdminBundle/SyliusAdminBundle.php
- src/Sylius/Bundle/ApiBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php
- src/Sylius/Bundle/ApiBundle/SyliusApiBundle.php
- src/Sylius/Bundle/AttributeBundle/SyliusAttributeBundle.php
- src/Sylius/Bundle/CustomerBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/CustomerBundle/DependencyInjection/SyliusCustomerExtension.php
- src/Sylius/Bundle/CustomerBundle/SyliusCustomerBundle.php
- src/Sylius/Bundle/InventoryBundle/SyliusInventoryBundle.php
- src/Sylius/Bundle/PaymentBundle/SyliusPaymentBundle.php
- src/Sylius/Bundle/PayumBundle/SyliusPayumBundle.php
- src/Sylius/Bundle/ReviewBundle/SyliusReviewBundle.php
- src/Sylius/Bundle/ShippingBundle/SyliusShippingBundle.php
- src/Sylius/Bundle/ShopBundle/DependencyInjection/SyliusShopExtension.php
- src/Sylius/Bundle/ShopBundle/SyliusShopBundle.php
- src/Sylius/Bundle/TaxationBundle/SyliusTaxationBundle.php
- src/Sylius/Bundle/TaxonomyBundle/SyliusTaxonomyBundle.php
- src/Sylius/Bundle/UiBundle/SyliusUiBundle.php
> Finalize bundles, container extensions and bundles configurations

- docs/book/architecture/resource_layer.rst
- docs/bundles/SyliusResourceBundle/create_resource.rst
- docs/bundles/SyliusResourceBundle/forms.rst
- docs/bundles/SyliusResourceBundle/reference.rst
- docs/bundles/SyliusResourceBundle/routing.rst
- docs/bundles/SyliusResourceBundle/update_resource.rst
As @PyRowMan noticed our docs about forms are quite outdated. There is a few more places, where we should update documentation.
> [Documentation] Change reference of forms to Symfony3

- etc/travis/suites/common/before_install.sh
> [Travis] Remove unnecessary commands

- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-move-product-variant.js
- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-move-product.js
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Grid/Action/updatePositions.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Grid/Action/updatePositions.html.twig
- src/Sylius/Bundle/CoreBundle/Controller/ProductTaxonController.php
- src/Sylius/Bundle/CoreBundle/Controller/ProductVariantController.php
> [Admin][Security] Use csrf token in update position

- src/Sylius/Behat/Page/Shop/HomePage.php
- src/Sylius/Bundle/ShopBundle/Resources/config/routing.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/_currencySwitch.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/_localeSwitch.html.twig
> [Shop] Revert changing http method for switching locales and currency

- src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product.yml
- tests/Controller/ProductApiTest.php
- tests/Responses/Expected/product/index_response.json
- tests/Responses/Expected/product/paginated_index_response.json
- tests/Responses/Expected/product/sorted_index_response.json
> [API] Improve routing of product

- docs/components/Channel/index.rst
Help users more easily learn more about what Channels are in Sylius
> [Documentation][Channel] - add link to book docs

- docs/customization/menu.rst
> [Documentation][Customization] Account Menu - quickfix

- UPGRADE.md
- app/config/security.yml
> [Security] Fix partial security acl

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product.yml
> [API] Improve product routing

- UPGRADE.md
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
> [Core] Move repository method from order to core

- src/Sylius/Bundle/ResourceBundle/Controller/ParametersParser.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ParametersParserSpec.php
> Improve ParametersParser

- docs/book/architecture/index.rst
- docs/book/architecture/map.rst.inc
- docs/book/architecture/translations.rst
> [Documentation][Book] Translations

- UPGRADE.md
- app/config/config_test.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/test_services.xml
- src/Sylius/Component/Core/Payment/IdBasedInvoiceNumberGenerator.php
- src/Sylius/Component/Core/Payment/RandomInvoiceNumberGenerator.php
- src/Sylius/Component/Core/spec/Payment/RandomInvoiceNumberGeneratorSpec.php
- tests/Driver/MySqlDriver.php
- tests/Driver/PgSqlDriver.php
| Related tickets | extracted from #7344  |
> Move test services to more appropriate namespaces

- src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/CurrencyBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/CurrencyBundle/DependencyInjection/SyliusCurrencyExtension.php
- src/Sylius/Bundle/CurrencyBundle/Resources/config/services/integrations/doctrine/orm.xml
- src/Sylius/Bundle/OrderBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/OrderBundle/DependencyInjection/SyliusOrderExtension.php
- src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ProductBundle/Resources/config/services/integrations/doctrine/orm.xml
- src/Sylius/Bundle/ReviewBundle/DependencyInjection/Configuration.php
I have removed all possible repositories from configuration tree, to decouple our bundles us as much as it is possible from Doctrine ORM.
> [Core] [Currency] [Order] [Product] [Review] Repositories cleanup

- UPGRADE.md
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/taxon.yml
- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
- src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php
- src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
| BC breaks?      | yes (see `UPGRADE.md`) |
Before:
After:
> Make product browsing fast again

- src/Sylius/Bundle/ProductBundle/test/src/Tests/SyliusProductBundleTest.php
Just a small typo in class name ;)
> [Product] Typo in class name

- src/Sylius/Bundle/ResourceBundle/Controller/FlashHelper.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/FlashHelperSpec.php
Now it will actually check if a translation exists also with `IdentityTranslator`.
> [Resource] Fixed FlashHelper

- composer.lock
> update project depedencies

- docs/cookbook/custom-redirect-after-cart-add-action.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
- src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
- src/Sylius/Bundle/ResourceBundle/Event/ResourceControllerEvent.php
- src/Sylius/Bundle/ResourceBundle/spec/Event/ResourceControllerEventSpec.php
Add set/get Response on `ResourceControllerEvent`.
> [Cart] Make possibility to change response after add to cart action

- etc/travis/suites/application/script/test-fixtures
- src/Sylius/Bundle/FixturesBundle/Command/FixturesLoadCommand.php
> [Fixtures] Fixture loading command asks for confirmation before purging database

- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
| Related tickets | fixes #7405 |
During clean up of #7330 I didn't notice this leftover
> [Core] Remove unneeded service definition

- src/Sylius/Bundle/AddressingBundle/Form/Type/AddressType.php
- src/Sylius/Bundle/AddressingBundle/Form/Type/CountryChoiceType.php
- src/Sylius/Bundle/AddressingBundle/Form/Type/CountryCodeChoiceType.php
- src/Sylius/Bundle/AddressingBundle/Form/Type/ProvinceChoiceType.php
- src/Sylius/Bundle/AddressingBundle/Form/Type/ProvinceCodeChoiceType.php
- src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneChoiceType.php
- src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneCodeChoiceType.php
- src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneType.php
- src/Sylius/Bundle/ChannelBundle/Form/Type/ChannelChoiceType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/ShipmentType.php
- src/Sylius/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php
- src/Sylius/Bundle/OrderBundle/Form/Type/OrderItemType.php
- src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentGatewayChoiceType.php
- src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentMethodChoiceType.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductAssociationTypeChoiceType.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductAssociationsType.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductChoiceType.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionChoiceType.php
- src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionActionChoiceType.php
- src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionRuleChoiceType.php
- src/Sylius/Bundle/ResourceBundle/Form/Type/ResourceChoiceType.php
- src/Sylius/Bundle/ResourceBundle/Form/Type/ResourceToIdentifierType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/CalculatorChoiceType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingCategoryChoiceType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodChoiceType.php
- src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodType.php
- src/Sylius/Bundle/TaxationBundle/Form/Type/TaxCalculatorChoiceType.php
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonChoiceType.php
All of these forms are final, so there is no possibility to extend them anyway.
> [Core] [Promotion] [Shipping] [Addressing] Private fields in final forms

- src/Sylius/Bundle/CoreBundle/Resources/config/validation/Channel.xml
| New feature?    | no/yes |
| BC breaks?      | no/yes |
| Related tickets | fixes #7414  |
> [BugFix] Put `taxCalculationStrategy` in `sylius` validation group.

- docs/book/architecture/architecture.rst
> [Documentation][Book] Architecture - Third Party Bundles

- docs/book/architecture/architecture.rst
> [Documenation] Typo in library name

- src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
- src/Sylius/Bundle/UiBundle/Resources/private/js/app.js
- src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Layout/sidebar.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Menu/sidebar.html.twig
Also, disable dimming and autoclosing of the sidebar.
> Admin Sidebar Menu Persistence

- docs/bundles/SyliusGridBundle/custom_filter.rst
Corrected misspelling in TournamentStatisticsFilterType namespace.
> [DOC] Update custom_filter.rst (corrected misspelling)

- src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php
- src/Sylius/Bundle/ResourceBundle/test/app/config/routing.yml
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/Controller/BookApiTest.php
> [Resource] Fix internal server error when apply sorting or filtering

- docs/bundles/SyliusResourceBundle/configuration.rst
- docs/bundles/SyliusResourceBundle/create_resource.rst
- docs/bundles/SyliusResourceBundle/delete_resource.rst
- docs/bundles/SyliusResourceBundle/forms.rst
- docs/bundles/SyliusResourceBundle/index.rst
- docs/bundles/SyliusResourceBundle/index_resources.rst
- docs/bundles/SyliusResourceBundle/reference.rst
- docs/bundles/SyliusResourceBundle/routing.rst
- docs/bundles/SyliusResourceBundle/services.rst
- docs/bundles/SyliusResourceBundle/show_resource.rst
- docs/bundles/SyliusResourceBundle/update_resource.rst
> [Documentation][Bundles] ResourceBundle - rework

- tests/Controller/ProductApiTest.php
- tests/Responses/Expected/product/create_with_images_response.json
| Related tickets | fixes master build |
Two changes on product has been merged at the same time, which results in failing master build. `code` has been changed to `type` on product but in a meantime a new test for product images has been added.
> [HOTFIX] [Product] Rename code to type on image

- docs/book/products/product_reviews.rst
There is a missing word in the documentation of the product review.
> [Documentation] Add missing word in product review

- UPGRADE.md
- app/migrations/Version20170208102345.php
- docs/api/products.rst
- docs/components/Product/basic_usage.rst
- docs/components/Product/models.rst
- src/Sylius/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php
- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/Product.orm.xml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.Product.yml
- src/Sylius/Component/Product/Model/Product.php
- src/Sylius/Component/Product/Model/ProductInterface.php
- src/Sylius/Component/Product/spec/Model/ProductSpec.php
- tests/Responses/Expected/product/create_response.json
- tests/Responses/Expected/product/create_with_associations_response.json
- tests/Responses/Expected/product/create_with_attributes_response.json
- tests/Responses/Expected/product/create_with_channels_response.json
- tests/Responses/Expected/product/create_with_images_response.json
- tests/Responses/Expected/product/create_with_main_taxon_response.json
- tests/Responses/Expected/product/create_with_options_response.json
- tests/Responses/Expected/product/create_with_product_taxons_response.json
- tests/Responses/Expected/product/show_response.json
| Related tickets |mentioned in #7298|
> [Product] Remove product's avaiability

- src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php
| Related tickets | fixes #7354 |
> [Critical BUG FIX] Wrong logic in apply criteria/sorting.

- docs/api/index.rst
- docs/api/map.rst.inc
- docs/api/product_variants.rst
- src/Sylius/Bundle/ApiBundle/Form/Type/ProductVariantType.php
- src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/grids/product_variant.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/CoreBundle/Form/Extension/ProductVariantTypeExtension.php
- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.ProductVariant.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductVariant.yml
- tests/Controller/ProductVariantApiTest.php
- tests/DataFixtures/ORM/resources/product_variants.yml
- tests/DataFixtures/ORM/resources/products.yml
- tests/Responses/Expected/product_variant/create_response.json
- tests/Responses/Expected/product_variant/create_tracked_response.json
- tests/Responses/Expected/product_variant/create_validation_fail_response.json
- tests/Responses/Expected/product_variant/create_with_channel_pricings_response.json
- tests/Responses/Expected/product_variant/create_with_product_option_response.json
- tests/Responses/Expected/product_variant/create_with_shipping_category_response.json
- tests/Responses/Expected/product_variant/create_with_tax_category_response.json
- tests/Responses/Expected/product_variant/create_with_translations_response.json
- tests/Responses/Expected/product_variant/index_response.json
- tests/Responses/Expected/product_variant/not_changed_on_hand_response.json
- tests/Responses/Expected/product_variant/paginated_index_response.json
- tests/Responses/Expected/product_variant/show_response.json
- tests/Responses/Expected/product_variant/sorted_index_response.json
> [API][ProductVariant] Crud for product variants 

- UPGRADE.md
| Related tickets | fixes #7421 |
> [UPGRADE] Add note about api routing change

- src/Sylius/Component/Product/Model/Product.php
> [Product] Remove availability stuff from model

- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_payment.yml
| Related tickets | mentioned [here](https://github.com/Sylius/Sylius/pull/7456#discussion_r100159606) |
> [BugFix] Remove redundant comma in sylius_order_payment state machine

- src/Sylius/Bundle/ResourceBundle/Controller/RedirectHandler.php
- src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
| Related tickets | ~ |
Fix missing `hash` when redirect to referer.
> Fix redirect to referer with hash.

- docs/bundles/SyliusResourceBundle/reference.rst
- docs/bundles/SyliusResourceBundle/routing.rst
| Related tickets | [comment](https://github.com/Sylius/Sylius/pull/7448#issuecomment-278281465) |
As I promised, docs for today added feature.
> [Resource] [Documentation] New features of routing generator

- UPGRADE.md
- src/Sylius/Bundle/OrderBundle/Remover/ExpiredCartsRemover.php
- src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
- src/Sylius/Bundle/OrderBundle/SyliusCartsRemoveEvents.php
- src/Sylius/Bundle/OrderBundle/spec/Remover/ExpiredCartsRemoverSpec.php
> [Order] Events dispatched before and after expired carts removal

- src/Sylius/Bundle/AddressingBundle/test/src/Tests/SyliusAddressingBundleTest.php
- src/Sylius/Bundle/AttributeBundle/test/src/Tests/SyliusAttributeBundleTest.php
- src/Sylius/Bundle/ChannelBundle/test/src/Tests/SyliusChannelBundleTest.php
- src/Sylius/Bundle/CurrencyBundle/test/src/Tests/SyliusCurrencyBundleTest.php
- src/Sylius/Bundle/CustomerBundle/test/src/Tests/SyliusCurrencyBundleTest.php
- src/Sylius/Bundle/FixturesBundle/test/src/Tests/SyliusFixturesBundleTest.php
- src/Sylius/Bundle/GridBundle/test/src/Tests/SyliusGridBundleTest.php
- src/Sylius/Bundle/InventoryBundle/test/src/Tests/SyliusInventoryBundleTest.php
- src/Sylius/Bundle/LocaleBundle/test/src/Tests/SyliusLocaleBundleTest.php
- src/Sylius/Bundle/MailerBundle/test/src/Tests/SyliusMailerBundleTest.php
- src/Sylius/Bundle/OrderBundle/test/src/Tests/SyliusOrderBundleTest.php
- src/Sylius/Bundle/PaymentBundle/test/src/Tests/SyliusPaymentBundleTest.php
- src/Sylius/Bundle/ProductBundle/test/src/Tests/SyliusProductBundleTest.php
- src/Sylius/Bundle/PromotionBundle/test/src/Tests/SyliusPromotionBundleTest.php
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/SyliusResourceBundleTest.php
- src/Sylius/Bundle/ReviewBundle/test/src/Tests/SyliusReviewBundleTest.php
- src/Sylius/Bundle/ShippingBundle/test/src/Tests/SyliusShippingBundleTest.php
- src/Sylius/Bundle/TaxationBundle/test/src/Tests/SyliusTaxationBundleTest.php
- src/Sylius/Bundle/TaxonomyBundle/test/src/Tests/SyliusTaxonomyBundleTest.php
- src/Sylius/Bundle/ThemeBundle/test/src/Tests/SyliusThemeBundleTest.php
- src/Sylius/Bundle/UserBundle/test/src/Tests/SyliusUserBundleTest.php
Mostly typos or wrong filenames/namespaces
> Fixed Bundles' Initialisation Tests

- src/Sylius/Bundle/OrderBundle/Remover/ExpiredCartsRemover.php
- src/Sylius/Bundle/OrderBundle/SyliusExpiredCartsEvents.php
- src/Sylius/Bundle/OrderBundle/spec/Remover/ExpiredCartsRemoverSpec.php
| Related tickets | fixes #7470 comments |
> [Order] Renamed SyliusCartsRemoveEvents to SyliusExpiredCartsEvents

- docs/cookbook/disabling-shop-admin-api.rst
> [Documentation][Cookbook] Quickfix

- features/admin/dashboard_per_channel.feature
- src/Sylius/Behat/Context/Ui/Admin/DashboardContext.php
> Fix channel dashboard scenarios

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_variant.yml
> [Api][ProductVariant] Add api section to product variant routing

- docs/book/architecture/emails.rst
- src/Sylius/Bundle/CoreBundle/EmailManager/ContactEmailManager.php
- src/Sylius/Bundle/CoreBundle/EmailManager/ContactEmailManagerInterface.php
- src/Sylius/Bundle/CoreBundle/EmailManager/OrderEmailManager.php
- src/Sylius/Bundle/CoreBundle/EmailManager/OrderEmailManagerInterface.php
- src/Sylius/Bundle/CoreBundle/EmailManager/ShipmentEmailManager.php
- src/Sylius/Bundle/CoreBundle/EmailManager/ShipmentEmailManagerInterface.php
- src/Sylius/Bundle/CoreBundle/spec/EmailManager/ContactEmailManagerSpec.php
- src/Sylius/Bundle/ShopBundle/Controller/ContactController.php
> [Core][EmailManager] Add interfaces to email managers

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Component/Core/Customer/Statistics/CustomerStatisticsProvider.php
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
- src/Sylius/Component/Core/spec/Customer/Statistics/CustomerStatisticsProviderSpec.php
> [Admin][Customer][Order] Exclude cancelled orders from customer statistics provider

- docs/api/index.rst
- docs/api/map.rst.inc
- docs/api/taxons.rst
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
- src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/grids/taxon.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/taxon.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.Taxon.yml
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonChoiceType.php
- src/Sylius/Bundle/TaxonomyBundle/Resources/config/serializer/Model.Taxon.yml
- tests/Controller/ProductApiTest.php
- tests/Controller/TaxonApiTest.php
- tests/DataFixtures/ORM/resources/many_taxons.yml
- tests/DataFixtures/ORM/resources/taxons.yml
- tests/Responses/Expected/product/create_with_main_taxon_response.json
- tests/Responses/Expected/product/create_with_product_taxons_response.json
- tests/Responses/Expected/taxon/create_response.json
- tests/Responses/Expected/taxon/create_root_response.json
- tests/Responses/Expected/taxon/create_root_with_multiple_translations_response.json
- tests/Responses/Expected/taxon/create_validation_fail_response.json
- tests/Responses/Expected/taxon/create_with_images_response.json
- tests/Responses/Expected/taxon/create_with_multiple_translations_response.json
- tests/Responses/Expected/taxon/create_with_parent_response.json
- tests/Responses/Expected/taxon/index_response.json
- tests/Responses/Expected/taxon/paginated_index_response.json
- tests/Responses/Expected/taxon/show_response.json
- tests/Responses/Expected/taxon/show_root_response.json
> [API] Taxon CRUD

- src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php
> Hot fix resource join filters

- src/Sylius/Bundle/ResourceBundle/Controller/RedirectHandler.php
| Related tickets | #7462 |
Sorry my bad 😢  already have in L:94
> Hotfix revert redirect hash.

- docs/bundles/SyliusResourceBundle/routing.rst
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/cart.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/cart_item.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/ResourceBundle/Routing/ResourceLoader.php
- src/Sylius/Bundle/ResourceBundle/spec/Routing/ResourceLoaderSpec.php
**UPDATED**
Another improvement to routing generator. I have used this new feature to generate cart item routing to see if it works properly.
> [Resource] [API] [Product] Resource criteria improvment

- docs/book/products/inventory.rst
> [Documentation][Book] Inventory - clarify onHand/onHold

- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-variants-prices.js
- src/Sylius/Component/Core/Provider/ProductVariantsPricesProvider.php
- src/Sylius/Component/Core/spec/Provider/ProductVariantsPricesProviderSpec.php
Base product variant prices on option code and not on option text
> Base product variant prices on option code

- docs/book/orders/checkout.rst
- docs/book/products/products.rst
| Related tickets | because of #7215 |
> [Documentation][Book] Skipping shipping step

- src/Sylius/Bundle/CoreBundle/EventListener/OrderCompleteListener.php
- src/Sylius/Bundle/CoreBundle/EventListener/ShipmentShipListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_shipment.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/CoreBundle/spec/EventListener/OrderCompleteListenerSpec.php
- src/Sylius/Bundle/CoreBundle/spec/EventListener/ShipmentShipListenerSpec.php
| Related tickets | contains #7478 and associated with #7357 |
> [Order][Shipment] Move sending email logic from state machines to listeners

- UPGRADE.md
| Related tickets | mentions changes in #7486 |
> Add upgrade instructions for currency switching logic refactoring

- composer.json
- composer.lock
Removes space introduced here https://github.com/Sylius/Sylius/pull/7505/files
> remove space in composer.json

- docs/cookbook/disabling-localised-urls.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
| Related tickets | introduced with #7412 |
> [Documentation] [Cookbook] How to disable localised URLs?

- docs/api/product_variants.rst
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductVariant.yml
- tests/Controller/ProductVariantApiTest.php
- tests/Responses/Expected/product_variant/index_response.json
- tests/Responses/Expected/product_variant/paginated_index_response.json
- tests/Responses/Expected/product_variant/sorted_index_response.json
During my work on #7485 I have realized that we have missed proper serialization groups on product variant. I have fixed that and also provide some small refactor of the test suite.
> Product test refactor

- docs/book/products/taxons.rst
| Related tickets | fixes #7511|
> [Documentation] Fix book: adding taxons to product

- docs/cookbook/disabling-localised-urls.rst
| Related tickets | fixes https://github.com/Sylius/Sylius/pull/7507#discussion_r101241585 |
> [Documentation] Correct a typo in disabling localised URLs cookbook

- docs/api/products.rst
> [Documentation] Update api product documentation 

- UPGRADE.md
- src/Sylius/Bundle/ShopBundle/Controller/HomepageController.php
| Related tickets | related to #7502 |
> [ShopBundle] Make HomepageController final

- src/Sylius/Bundle/CoreBundle/Form/DataTransformer/ProductTaxonToTaxonTransformer.php
- src/Sylius/Bundle/CoreBundle/Form/Extension/ProductTypeExtension.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Taxon/ProductTaxonAutocompleteChoiceType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/CoreBundle/Tests/Form/Type/Taxon/ProductTaxonAutocompleteChoiceTypeTest.php
- src/Sylius/Bundle/CoreBundle/spec/Form/DataTransformer/ProductTaxonToTaxonTransformerSpec.php
- src/Sylius/Bundle/ResourceBundle/Form/Type/ResourceAutocompleteChoiceType.php
| BC breaks?      | maybe |
| Related tickets | #3570, #7446  |
> [Product] Fix duplicate entry exception

- UPGRADE.md
For route changes for locales in URL it said that you need to modify security.yml, should be routing.yml
> Fixed wrong config file reference

- docs/cookbook/custom-redirect-after-cart-add-action.rst
- docs/cookbook/disabling-localised-urls.rst
- docs/cookbook/embedding-products.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
- docs/cookbook/taxons-menu.rst
This should be a [RFC] actually, about **how to organize contents of the Cookbook?**
> [RFC][Documentation][Cookbook] Slightly reorganize content

- docs/customization/template.rst
> [Documentation][Customization] Templates - global variables

- UPGRADE.md
- docs/components/Payment/state_machine.rst
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_payment.yml
- src/Sylius/Bundle/PaymentBundle/Form/Type/PaymentType.php
- src/Sylius/Bundle/PaymentBundle/Resources/translations/flashes.en.yml
- src/Sylius/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php
- src/Sylius/Bundle/PayumBundle/Request/GetStatus.php
- src/Sylius/Component/Payment/Model/PaymentInterface.php
> [Payment] Clean up payment state machine

- docs/customization/controller.rst
> [Documentation][Customization] Non-resource controllers - update

- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/ShippingBundle/Resources/config/serializer/Model.Shipment.yml
- tests/Controller/CheckoutApiTestCase.php
- tests/Controller/OrderApiTest.php
- tests/Responses/Expected/order/order_canceled_show_response.json
- tests/Responses/Expected/order/order_fulfilled_show_response.json
- tests/Responses/Expected/order/order_payed_show_response.json
- tests/Responses/Expected/order/order_shipped_show_response.json
- tests/Responses/Expected/order/order_shipped_with_tracking_show_response.json
From now on it will be possible to cancel, ship or complete the payment for order via API
> [API] Order management actions

- docs/api/orders.rst
- tests/Controller/OrderApiTest.php
> [Documentation] [API] [Order] Order actions

- UPGRADE.md
- app/migrations/Version20170215143031.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/ProductBundle/Resources/config/doctrine/model/ProductTranslation.orm.xml
- src/Sylius/Bundle/ProductBundle/Resources/config/validation/ProductTranslation.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/product_review.yml
- src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php
> [Shop] Reduce number of queries related to product

- docs/customization/validation.rst
> [Documentation][Customization] Validation - fix

- src/Sylius/Bundle/UiBundle/Controller/SecurityController.php
- src/Sylius/Bundle/UiBundle/Resources/views/Form/imagesTheme.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/create.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/default.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/delete.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/show.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/update.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/boolean.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/date.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/entity.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/exists.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/money.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/string.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_history.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Layout/sidebar.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Security/_login.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Security/login.html.twig
Allow overriding of any _SyliusUiBundle_ template
| Related tickets | partially #7536  |
> Template naming refactoring => use the @ notation

- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-auto-complete.js
> [Js] Disable caching for autocomplete choices

- features/product/managing_products/select_taxons_for_product.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
> [Behat] Fix selecting taxon scenarios

- src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/OrderItemUnit.orm.xml
Cart summary # of queries reduced from 79 to 47.
> Reduce # of queries by eagerly loading adjustments on order item units

- src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
PR resolves two issues:
- after customizing `OrderItem` and adding some fields to add to cart form, the additional form was not validated
- validation message added on fields (not on the whole object) was not displayed properly
Before:
After:
For these problems should be deeply considered (there are problems with validation using custom data mappers - `OrderItem` cannot be persisted with invalid quantity), but for now I think it's a good solution.
> [Order] Fix validation while adding product to cart

- docs/cookbook/checkout.rst
> [Documentation][Cookbook] Update Checkout customization guide

- docs/book/installation/upgrading.rst
> [Documentation][Book] Upgrading - small fix

- docs/api/checkouts.rst
- src/Sylius/Bundle/AddressingBundle/Resources/config/serializer/Model.Address.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/checkout.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.ChannelPricing.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.Payment.yml
- src/Sylius/Bundle/PaymentBundle/Resources/config/serializer/Model.Payment.yml
- src/Sylius/Bundle/PaymentBundle/Resources/config/serializer/Model.PaymentMethod.yml
- src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductOptionValue.yml
- src/Sylius/Bundle/ShippingBundle/Resources/config/serializer/Model.Shipment.yml
- src/Sylius/Bundle/ShippingBundle/Resources/config/serializer/Model.ShippingMethod.yml
- tests/Controller/CheckoutCompleteApiTest.php
- tests/Responses/Expected/checkout/addressed_order_response.json
- tests/Responses/Expected/order/cart_show_response.json
- tests/Responses/Expected/order/order_canceled_show_response.json
- tests/Responses/Expected/order/order_fulfilled_show_response.json
- tests/Responses/Expected/order/order_payed_show_response.json
- tests/Responses/Expected/order/order_shipped_show_response.json
- tests/Responses/Expected/order/order_shipped_with_tracking_show_response.json
- tests/Responses/Expected/order/order_show_response.json
- tests/Responses/Expected/product_variant/create_with_channel_pricings_response.json
| BC breaks?      | yes (different serialization in API) |
> [API] [Documentation] [Checkout] Documentation for checkout and a few tweaks 

- README.md
| Related tickets | fixes #7565 |
> Fix README installation guide

- features/product/viewing_products/viewing_products_sorted_by_first_variant_price.feature
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Behat/Page/Shop/Product/IndexPage.php
- src/Sylius/Behat/Page/Shop/Product/IndexPageInterface.php
| Related tickets | fixes #7306, closes #7272 |
> Ensure products are sorted by their first variant price

- docs/api/authorization.rst
- docs/api/carts.rst
- docs/api/channels.rst
- docs/api/countries.rst
- docs/api/currencies.rst
- docs/api/customers.rst
- docs/api/introduction.rst
- docs/api/locales.rst
- docs/api/orders.rst
- docs/api/payments.rst
- docs/api/product_variants.rst
- docs/api/products.rst
- docs/api/promotions.rst
- docs/api/shipments.rst
- docs/api/shipping_categories.rst
- docs/api/taxons.rst
- docs/api/users.rst
> [Documentation][API] Minor Fixes

- src/Sylius/Bundle/ThemeBundle/Translation/ThemeAwareTranslator.php
| Related tickets | fixes #5883 |
> [Theme] Fixed missing translations of custom messages

- app/migrations/Version20170220150813.php
- features/account/registering.feature
- src/Sylius/Behat/Context/Setup/ChannelContext.php
- src/Sylius/Behat/Context/Ui/EmailContext.php
- src/Sylius/Behat/Context/Ui/Shop/RegistrationContext.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Channel/_form.html.twig
- src/Sylius/Bundle/CoreBundle/Form/Extension/ChannelTypeExtension.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/CustomerBundle/Resources/translations/flashes.en.yml
- src/Sylius/Bundle/ShopBundle/EventListener/UserRegistrationListener.php
- src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/ShopBundle/spec/EventListener/UserRegistrationListenerSpec.php
- src/Sylius/Component/Core/Model/Channel.php
- src/Sylius/Component/Core/Model/ChannelInterface.php
- src/Sylius/Component/Core/spec/Model/ChannelSpec.php
> [Shop] Possibility to disable the e-mail verification after registration

- src/Sylius/Component/Resource/Model/TranslatableTrait.php
`PersistentCollection::get($key)` does not store its result, so the following code makes three queries:
```php
$product = $productRepository->find(42);
$product->getName(); // $product->getTranslation()->getName()
$product->getSlug(); // $product->getTranslation()->getSlug()
```
> Decrease number of queries made when accessing not-joined translation's fields

- docs/bundles/SyliusPromotionBundle/action_applicator.rst
- docs/bundles/SyliusPromotionBundle/applying_promotions.rst
- docs/bundles/SyliusPromotionBundle/coupon_based.rst
- docs/bundles/SyliusPromotionBundle/models.rst
- docs/bundles/SyliusPromotionBundle/rule_checker.rst
> fix SyliusPromotionBundle docs

- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Index/_header.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/links.html.twig
| Related tickets | partially fixes #7529 |
> [Grid] Add missing check if main action is enabled

- libphp7.so
Quite sure this shouldn't be in the repo 💃
> [?] Removed symlink to php7 library

- features/locale/browsing_shop_in_different_than_default_locale.feature
- src/Sylius/Behat/Context/Ui/Shop/CurrentChannelContext.php
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Bundle/ShopBundle/EventListener/NonChannelLocaleListener.php
- src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/locale/url.xml
- src/Sylius/Bundle/ShopBundle/phpspec.yml.dist
- src/Sylius/Bundle/ShopBundle/spec/EventListener/NonChannelLocaleListenerSpec.php
Although the switch available in shop already does it, you could still change the url's locale by hand, which would yield some weird behaviour.
> [Shop] Restricted url locales

- src/Sylius/Bundle/ShopBundle/Tests/DependencyInjection/ConfigurationTest.php
- src/Sylius/Bundle/ShopBundle/Tests/DependencyInjection/SyliusShopExtensionTest.php
- src/Sylius/Bundle/ShopBundle/composer.json
- src/Sylius/Bundle/ShopBundle/phpunit.xml.dist
> [Shop] Turned on Unit tests

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_main.html.twig
> [Shop] Fix displaying dropdowns above images on product list

- UPGRADE.md
- src/Sylius/Bundle/CoreBundle/Context/SessionAndChannelBasedCartContext.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/AssociationHydrator.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/OrderBundle/Controller/OrderController.php
- src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/OrderItemUnit.orm.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/checkout.yml
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
| Related tickets | based on #7606 |
Before:
After:
> Product show page optimisation

- UPGRADE.md
- src/Sylius/Bundle/CoreBundle/Context/SessionAndChannelBasedCartContext.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/AssociationHydrator.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/OrderBundle/Controller/OrderController.php
- src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/OrderItemUnit.orm.xml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/checkout.yml
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
| BC breaks?      | yes (methods added to repository interface) |
Based on [Ocramius' blogpost](http://ocramius.github.io/blog/doctrine-orm-optimization-hydration/).
Benchmarking locally, before:
After:
> Checkout queries optimisation

- docs/api/shipments.rst
- src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/grids/shipments.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/shipment.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ShipmentRepository.php
- src/Sylius/Bundle/ShippingBundle/Resources/config/serializer/Model.Shipment.yml
- src/Sylius/Component/Core/Repository/ShipmentRepositoryInterface.php
- tests/Controller/ShipmentApiTest.php
- tests/Responses/Expected/checkout/shipping_selected_order_response.json
- tests/Responses/Expected/order/cart_show_response.json
- tests/Responses/Expected/order/order_canceled_show_response.json
- tests/Responses/Expected/order/order_fulfilled_show_response.json
- tests/Responses/Expected/order/order_shipped_show_response.json
- tests/Responses/Expected/order/order_shipped_with_tracking_show_response.json
- tests/Responses/Expected/order/order_show_response.json
- tests/Responses/Expected/shipment/shipment_index_response.json
- tests/Responses/Expected/shipment/shipment_show_response.json
> [API] [Documentation] Shipments endpoint

- tests/Responses/Expected/order/order_payed_show_response.json
> [API] Fix failing order API test

- docs/api/product_options.rst
> [Documentation] [API] Fix wrong path

- docs/api/currencies.rst
- docs/api/customers.rst
- docs/api/exchange_rates.rst
- docs/api/index.rst
- docs/api/map.rst.inc
- docs/api/orders.rst
- src/Sylius/Bundle/CurrencyBundle/Resources/config/serializer/Model.Currency.yml
- tests/Controller/ExchangeRateApiTest.php
- tests/Responses/Expected/currency/create_response.json
- tests/Responses/Expected/currency/show_response.json
- tests/Responses/Expected/exchange_rate/create_response.json
- tests/Responses/Expected/exchange_rate/show_response.json
- tests/Responses/Expected/exchange_rate/update_response.json
Small fix in currencies docs and exchange rates tests included
> [Documenation] Exchange rates

- src/Sylius/Behat/Context/Ui/Shop/RegistrationContext.php
- src/Sylius/Bundle/CustomerBundle/Resources/translations/flashes.en.yml
| Related tickets | minor fix after #7563 |
> [Registration] Revert change of flash message after registration

- docs/cookbook/images-on-entity.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
> [Documentation][Cookbook] How to add images to an entity?

- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/PaymentState/awaiting_payment.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/PaymentState/cancelled.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/PaymentState/paid.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/PaymentState/partially_paid.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/PaymentState/refunded.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/ShippingState/cancelled.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/ShippingState/ready.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Label/ShippingState/shipped.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_payments.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipments.html.twig
> [Admin][Order] Tweak the display of payment and shipping state on the order show

- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
> [Ui][Admin] Put grid filters on index pages in accordion

- docs/api/payments.rst
- src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/grids/payments.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/payment.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentRepository.php
- src/Sylius/Component/Core/Repository/PaymentRepositoryInterface.php
- tests/Controller/PaymentApiTest.php
- tests/Responses/Expected/order/order_show_response.json
- tests/Responses/Expected/payment/payment_index_response.json
- tests/Responses/Expected/payment/payment_show_response.json
> [API] [Documentation] Payments endpoint

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/AssociationHydrator.php
> don't perform useless unnecessary query

- UPGRADE.md
- docs/api/promotions.rst
- src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/grids/promotion.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/promotion.yml
- src/Sylius/Bundle/PromotionBundle/Resources/config/serializer/Model.Promotion.yml
- tests/Controller/PromotionApiTest.php
- tests/DataFixtures/ORM/resources/many_promotions.yml
- tests/DataFixtures/ORM/resources/product_taxons.yml
- tests/DataFixtures/ORM/resources/promotions.yml
- tests/Responses/Expected/promotion/create_coupon_based_response.json
- tests/Responses/Expected/promotion/create_exclusive_response.json
- tests/Responses/Expected/promotion/create_response.json
- tests/Responses/Expected/promotion/create_response_with_actions.json
- tests/Responses/Expected/promotion/create_response_with_channels.json
- tests/Responses/Expected/promotion/create_response_with_rules.json
- tests/Responses/Expected/promotion/create_response_with_time_of_duration.json
- tests/Responses/Expected/promotion/create_validation_fail_response.json
- tests/Responses/Expected/promotion/filtered_by_code_and_name_index_response.json
- tests/Responses/Expected/promotion/index_response.json
- tests/Responses/Expected/promotion/only_coupon_based_index_response.json
- tests/Responses/Expected/promotion/show_response_after_partial_update.json
- tests/Responses/Expected/promotion/show_response_after_update.json
- tests/Responses/Expected/promotion/sorted_by_code_index_response.json
- tests/Responses/Expected/promotion/sorted_by_name_index_response.json
- tests/Responses/Expected/promotion/sorted_by_priority_index_response.json
- tests/Responses/Expected/promotion_coupon/index_response.json
- tests/Responses/Expected/promotion_coupon/show_response.json
> [API][Promotions] Allows to create, delete and edit Promotions  

- docs/api/channels.rst
- docs/api/checkouts.rst
- docs/api/countries.rst
- docs/api/currencies.rst
- docs/api/promotion_coupons.rst
- docs/api/provinces.rst
- docs/api/shipping_categories.rst
- docs/api/shipping_methods.rst
- docs/api/tax_categories.rst
- docs/api/tax_rates.rst
- docs/api/taxons.rst
- docs/api/zones.rst
> [Documentation] Minor fixes in api documentation

- UPGRADE.md
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/taxon.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/product_review.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Tabs/_reviews.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_breadcrumb.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_reviews.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_box.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_info.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/create.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/_breadcrumb.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/_horizontalMenu.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/_verticalMenu.html.twig
- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
- src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
- tests/Controller/ProductApiTest.php
> Make shop up & running without having to translate all taxons & products

- docs/api/index.rst
- docs/api/map.rst.inc
- docs/api/sorting_and_filtration.rst
> [Documentation] Sorting and filtration in api

- UPGRADE.md
- app/config/routing.yml
- features/checkout/paying_for_order/paying_offline_during_checkout_as_guest.feature
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutThankYouContext.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
- src/Sylius/Behat/Resources/config/suites/ui/checkout/paying_for_order.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing.yml
| Related tickets | closes #7609 |
> Make Payum routes locale-independent

- UPGRADE.md
This step is required after PR #7349
| Related tickets | ~ |
> Added missing upgrade step to docs

- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
- docs/cookbook/platform-sh.rst
> [WIP] [Documentation][Cookbook] Deploying to Platform.sh

- UPGRADE.md
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php
- src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php
Without these fixes, we are accessing variants just based on their id.
> [Admin] [API] Improve product variant routing

- src/Sylius/Bundle/UiBundle/Resources/private/js/app.js
> [Admin][Js] Fix admin sidebar animation

- src/Sylius/Bundle/CoreBundle/Form/Type/Shipping/Calculator/ChannelBasedFlatRateConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Shipping/Calculator/ChannelBasedPerUnitRateConfigurationType.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductAssociationsType.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionValueCollectionType.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductVariantMatchType.php
> Make customising form rendering easier

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
> [Fixtures] adding default_tax_zone to ChannelFixture

- src/Sylius/Bundle/AdminBundle/Menu/CustomerShowMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/spec/Menu/CustomerShowMenuBuilderSpec.php
> [Admin][Customer] Fix dispatching proper event in customer menu builder

- docs/customization/controller.rst
- docs/customization/factory.rst
- docs/customization/flash.rst
- docs/customization/form.rst
- docs/customization/grid.rst
- docs/customization/menu.rst
- docs/customization/model.rst
- docs/customization/repository.rst
- docs/customization/state_machine.rst
- docs/customization/template.rst
- docs/customization/translation.rst
- docs/customization/validation.rst
> [Documentation][CustomizationGuide] Fixes

- docs/book/orders/payments.rst
| Related tickets | fixes #7654 |
> [Documentation][Book] Payments - custom gateways

- docs/book/orders/promotions.rst
| Related tickets | fixes #7661 |
> [Documentation][Book] Promotion - Rules and Actions configuration reference

- app/migrations/Version20170301135010.php
- src/Sylius/Bundle/CoreBundle/Fixture/StickerProductFixture.php
- src/Sylius/Bundle/CoreBundle/Form/Extension/ProductTypeExtension.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Product/ProductImageType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductImage.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductVariant.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.ProductImage.yml
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductVariantChoiceType.php
- src/Sylius/Bundle/ShopBundle/Resources/private/js/app.js
- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-variant-images.js
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_imageVariants.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_images.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Form/imagesTheme.html.twig
- src/Sylius/Component/Core/Model/ProductImage.php
- src/Sylius/Component/Core/Model/ProductImageInterface.php
- src/Sylius/Component/Core/Model/ProductVariant.php
- src/Sylius/Component/Core/spec/Model/ProductImageSpec.php
- src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php
| Related tickets | related #6380 |
> [Image][Variant] Brought back variant images

- features/promotion/managing_promotions/editing_promotion.feature
- features/promotion/managing_promotions/promotion_unique_code_validation.feature
> [Behat] [Promotion] Semantical fixes

- features/taxonomy/managing_taxons/autocomplete_taxon_name.feature
- features/taxonomy/managing_taxons/choosing_taxon_from_tree.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingTaxonsContext.php
- src/Sylius/Behat/Context/Setup/TaxonomyContext.php
- src/Sylius/Behat/Resources/config/services/contexts.xml
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/taxon/managing_taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml
- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_taxonomy.html.twig
- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
- src/Sylius/Bundle/TaxonomyBundle/Resources/config/serializer/Model.Taxon.yml
- src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-auto-complete.js
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
- src/Sylius/Component/Taxonomy/Model/Taxon.php
- src/Sylius/Component/Taxonomy/Model/TaxonInterface.php
- src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
- src/Sylius/Component/Taxonomy/spec/Model/TaxonSpec.php
> [Product] Lazy tree choice type

- docs/bundles/SyliusGridBundle/configuration.rst
- docs/bundles/SyliusGridBundle/filters.rst
> [Documentation][SyliusGridBundle] Filters - fix

- features/taxonomy/managing_taxons/choosing_taxon_from_tree.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingTaxonsContext.php
> [Behat] Improve choosing taxon from tree feature

- src/Sylius/Bundle/ApiBundle/EventListener/CartChangeListener.php
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/spec/EventListener/CartChangeListenerSpec.php
- tests/Controller/CartApiTest.php
- tests/DataFixtures/ORM/resources/cart_with_items.yml
- tests/Responses/Expected/cart/recalculated_items_total_response.json
> [API][Cart] Fix recalculation of cart on orderItem deletion

- src/Sylius/Bundle/ResourceBundle/Tests/Command/DebugResourceCommandTest.php
- src/Sylius/Bundle/ThemeBundle/Tests/Functional/AssetTest.php
- src/Sylius/Bundle/ThemeBundle/Tests/Functional/TemplatingTest.php
- src/Sylius/Bundle/ThemeBundle/Tests/Functional/TranslationTest.php
| Related tickets | fixes #4506 |
> Make test methods naming consistent

- UPGRADE.md
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/OrderBundle/Factory/AddToCartCommandFactory.php
- src/Sylius/Bundle/OrderBundle/Factory/AddToCartCommandFactoryInterface.php
- src/Sylius/Bundle/OrderBundle/spec/Factory/AddToCartCommandFactorySpec.php
- src/Sylius/Bundle/ResourceBundle/SyliusResourceBundle.php
- src/Sylius/Component/Addressing/Model/AddressLogEntry.php
- src/Sylius/Component/Resource/Model/ResourceLogEntry.php
- src/Sylius/Component/Resource/composer.json
> Remove components' dependencies on bundles

- UPGRADE.md
| Related tickets | fixes after #7705, related with #7715 |
> [Core] Fix UPGRADE file after moving emails

- src/Sylius/Bundle/ApiBundle/Controller/ProductTaxonPositionController.php
- tests/Controller/TaxonApiTest.php
> [ApiBundle] Fix updating products positions in a taxon

- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_addressBookSelect.html.twig
Display the country name that has been selected for the address on checkout form.
> Display country for address book

- src/Sylius/Bundle/ResourceBundle/EventListener/ORMMappedSuperClassSubscriber.php
| Q | A |
| --- | --- |
| Related tickets | fixes #955 |
> Fixed issue #955 - could not run command "doctrine:mapping:import"

- docs/bundles/SyliusGridBundle/configuration.rst
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/links.html.twig
It fixes a problem with displaying a generating variants button for product without options on product list in admin panel.
> [Grid] Add possibility to set visible parameter for each link in links action

- docs/bundles/SyliusFixturesBundle/builtin_listeners.rst
- src/Sylius/Bundle/FixturesBundle/Listener/ORMPurgerListener.php
| Related tickets | closes #7727 (rebased with master) |
> Add support to ORM Purger (Fixtures) to exclude tables

- src/Sylius/Bundle/ResourceBundle/Form/Type/ResourceTranslationsType.php
- src/Sylius/Bundle/ResourceBundle/Tests/Form/Type/ResourceTranslationsTypeTest.php
| Related tickets | closes #7719 |
> Pass entry options to entry types in ResourceTranslationsType

- docs/cookbook/custom-promotion-action.rst
- docs/cookbook/custom-promotion-rule.rst
> [Documentation] [Promotion] Update cookbooks about custom actions and rules

- docs/bundles/SyliusThemeBundle/your_first_theme.rst
Hello,
Just installed sylius theme bundle and had to fix that method to get it up and running.
> replace method findByLogicalName by findOneByName

- docs/book/installation/installation.rst
> [Documentation] Yarn instead of Node - small fix

- UPGRADE.md
> Add instructions about migrations to UPGRADE.md

- features/promotion/receiving_discount/receiving_stacked_promotions_with_changing_context.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Component/Promotion/Processor/PromotionProcessor.php
| Related tickets | fixes #7681, fixes #7584 |
Just a rebased version of #7681, investigating the PHP 5.6 job failure on Travis.
> Double check promotions are eligible in PromotionProcessor (duplicate of #7681)

- docs/book/orders/shipments.rst
> [Documentation] Fix typos in book/orders/shipments.rst

- src/Sylius/Bundle/AdminBundle/Resources/views/Order/show.html.twig
Another variant with the condition in a main template.
| Related tickets | alternative solution of #7756 |
> Don't show shipments segment when no shipments

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/promotion.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/promotion_coupon.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Create/_breadcrumb.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Create/_headerTitle.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Generate/_breadcrumb.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Generate/_form.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Index/_breadcrumb.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/generate.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Create/_breadcrumb.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Create/_headerTitle.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Generate/_breadcrumb.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Index/_breadcrumb.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Index/_header.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Index/_promotionHeader.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/generate.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/index.html.twig
> [Admin][ProductVariant][PromotionCoupon] Fix headers to be consistent

- src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
> Add 'skipping_shipping_step_allowed' setting to Channel Fixture

- features/payment/managing_payment_methods/editing_payment_method.feature
- src/Sylius/Bundle/CoreBundle/Form/Extension/ProductVariantGenerationTypeExtension.php
- src/Sylius/Bundle/CoreBundle/Form/Extension/ProductVariantTypeExtension.php
- src/Sylius/Bundle/CoreBundle/Form/Type/ChannelCollectionType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Shipping/Calculator/ChannelBasedFlatRateConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Shipping/Calculator/ChannelBasedPerUnitRateConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductAssociationsType.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductVariantMatchType.php
- src/Sylius/Bundle/ResourceBundle/Form/Type/FixedCollectionType.php
- src/Sylius/Bundle/ResourceBundle/Form/Type/ResourceTranslationsType.php
- src/Sylius/Bundle/ResourceBundle/Tests/Form/Type/FixedCollectionTypeTest.php
| Related tickets | -|
Translations, channel configuration, promotion rules, promotion actions - all of them benefit by usage of fixed collection type.
> Introduce fixed collection form type

- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/create.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/index.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/update.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
| Related tickets | continuation of #7717 |
Gives possibility to add some custom JS and CSS files to main shop/admin layout and entity specific crud page in Admin
> [UI] Add events for js and css

- src/Sylius/Bundle/ProductBundle/Form/DataTransformer/ProductsToProductAssociationsTransformer.php
> [ProductBundle] fix javadoc on setAssociatedProductsByProductCodes

- docs/customization/template.rst
| Related tickets | based on #7704 + #7717 + #7747 |
> [Documentation][Customization Guide] Templates via events

- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
introduced by Sylius\Bundle\UserBundle\Form\Model\PasswordResetRequest
> Add missing translation keys

- src/Sylius/Behat/Context/Ui/Admin/LoginContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Context/Ui/Shop/AddressBookContext.php
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutPaymentContext.php
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutShippingContext.php
- src/Sylius/Behat/Context/Ui/Shop/HomepageContext.php
- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
Exceptions should give us more info.
> Replace Page::isOpen() with Page::verify() where possible

- UPGRADE.md
- src/Sylius/Component/Core/Model/Product.php
- src/Sylius/Component/Core/Model/ProductTaxonsAwareInterface.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/TotalOfItemsFromTaxonRuleChecker.php
- src/Sylius/Component/Core/spec/Model/ProductSpec.php
- src/Sylius/Component/Core/spec/Promotion/Checker/Rule/TotalOfItemsFromTaxonRuleCheckerSpec.php
| Related tickets | resolves #7523 |
> Proxy taxon collection on product

- src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/RegisterPromotionActionsPassTest.php
- src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/RegisterRuleCheckersPassTest.php
> [Promotion] [Tests] Move protected methods after public

- features/checkout/returning_from_order_summary_page_to_one_of_previous_steps.feature
- src/Sylius/Behat/Context/Setup/AddressContext.php
- src/Sylius/Behat/Context/Transform/AddressContext.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_addressBookSelect.html.twig
| Related tickets | fixes #7774 |
> Fix addresses selection logic during checkout

- features/checkout/paying_for_order/changing_payment_method_after_order_confirmation.feature
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutOrderDetailsContext.php
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutThankYouContext.php
- src/Sylius/Behat/Page/Shop/Order/ThankYouPage.php
- src/Sylius/Behat/Page/Shop/Order/ThankYouPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Order/thankYou.html.twig
| Related tickets | fixes #7707 |
> Do not validate order when changing payment method after it is placed

- features/product/managing_product_variants/adding_product_variant.feature
- features/product/managing_products/adding_product.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPageInterface.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
- src/Sylius/Behat/Page/Admin/ProductVariant/CreatePage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_details.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_details.html.twig
- src/Sylius/Bundle/CoreBundle/Form/Extension/ProductVariantTypeExtension.php
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- tests/Responses/Expected/product_variant/create_validation_fail_response.json
> [Ui] Add is shipping required field for product variant

- src/Sylius/Component/Core/Promotion/Checker/Rule/HasTaxonRuleChecker.php
- src/Sylius/Component/Core/Promotion/Filter/TaxonFilter.php
- src/Sylius/Component/Core/spec/Promotion/Checker/Rule/HasTaxonRuleCheckerSpec.php
- src/Sylius/Component/Core/spec/Promotion/Filter/TaxonFilterSpec.php
Just small clean up after #7807
> [Promotion] Small cleanup related to product taxon proxy

- src/Sylius/Bundle/ResourceBundle/Controller/Parameters.php
> Removed unused argument

- src/Sylius/Bundle/CoreBundle/Fixture/PaymentMethodFixture.php
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/PaymentMethodFixtureTest.php
> [Core][Fixture] Make possible to pass custom array as gateway config

- features/cart/shopping_cart/adding_product_with_options_to_cart.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
- src/Sylius/Bundle/ProductBundle/Form/DataTransformer/ProductVariantToProductOptionsTransformer.php
| Related tickets | fixes #7813 |
> Make product variant match selection method working correctly again

- docs/book/architecture/events.rst
- docs/book/architecture/state_machine.rst
- docs/customization/state_machine.rst
> [Documentation] Customizing Sylius via events vs. state machines

- docs/components/Payment/state_machine.rst
> [Documentation][Payment] Outdated states

- features/taxonomy/managing_taxons/editing_taxon_slug_in_multiple_locales.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php
- src/Sylius/Behat/Page/Admin/Product/CreateConfigurableProductPage.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php
- src/Sylius/Behat/Page/Admin/Promotion/CreatePage.php
- src/Sylius/Behat/Page/Admin/Promotion/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePageInterface.php
- src/Sylius/Behat/Service/AutocompleteHelper.php
- src/Sylius/Behat/Service/SlugGenerationHelper.php
This *should* make slug generation/selecting multiple autocomplete options tests more reliable, so they won't fail as often as they do right now.
> [Behat] Upgraded javascript related tests

- docs/bundles/SyliusGridBundle/custom_filter.rst
Grid usage example was incorrect and outdated. I have fixed and updated it according to used Symfony and PHP versions.
> Update Grid filter usage examples

- src/Sylius/Bundle/ResourceBundle/Controller/ResourcesCollectionProvider.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourcesCollectionProviderSpec.php
> [Resource][Grid] Restricted max pagination size based on grid's limits configuration

- src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
- src/Sylius/Bundle/OrderBundle/Resources/translations/flashes.en.yml
| Related tickets | fixes #7850 |
> [Order] Ensured bought items will not be deleted via cart

- UPGRADE.md
| Related tickets | fixes #7729 |
> Improve UPGRADE.md file

- docs/api/product_attributes.rst
- docs/api/product_options.rst
- src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/product_attribute.yml
- tests/Controller/ProductAttributeApiTest.php
- tests/Controller/ProductOptionApiTest.php
- tests/Responses/Expected/product_attribute/create_response.json
- tests/Responses/Expected/product_attribute/create_validation_fail_response.json
- tests/Responses/Expected/product_attribute/index_response_after_delete.json
- tests/Responses/Expected/product_attribute/show_response_after_partial_update.json
- tests/Responses/Expected/product_attribute/show_response_after_update.json
| Related tickets | related to #7811  |
Similar to #7811, but for product attributes.
> Allow writing product attributes via API

- app/migrations/Version20170217141621.php
> [Maintenance] Fixed invalid exchange rate migration vol2

- src/Sylius/Behat/Page/Shop/Product/ShowPage.php
- src/Sylius/Behat/Service/AutocompleteHelper.php
- src/Sylius/Behat/Service/JQueryHelper.php
- src/Sylius/Behat/Service/SlugGenerationHelper.php
> [Behat] Removed `wait()` occurrences

- docs/cookbook/encrypting-gateway-config.rst
- src/Sylius/Bundle/PayumBundle/DependencyInjection/SyliusPayumExtension.php
> [Payum] Fix encryption docs and merging of payum configurations

- src/Sylius/Bundle/CoreBundle/Fixture/BookProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/MugProductFixture.php
> [Fixture] Fix creating attribute's values for select product attribute

- src/Sylius/Component/Product/Generator/CartesianSetBuilder.php
> Fix typo in CartisianSetBuilder

- README.md
replace the old slack link with the new one.
> Add valid slack invite link

- docs/cookbook/disabling-guest-checkout.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
| Related tickets | fixes #7947 |
> [Documentation][Cookbook] Disabling guest checkout

- docs/support/index.rst
| Doc fix?           | yes |
| Related tickets | resolved #7922 |
> [Docs] Update the Slack invitation link

- src/Sylius/Bundle/ThemeBundle/Model/Theme.php
- src/Sylius/Bundle/ThemeBundle/spec/Model/ThemeSpec.php
| Related tickets | fixes #7980 |
> Allow for numbers in themes' names

- tests/DataFixtures/ORM/resources/checkout.yml
- tests/Responses/Expected/checkout/get_available_payment_methods.json
- tests/Responses/Expected/order/cart_show_response.json
- tests/Responses/Expected/order/order_canceled_show_response.json
- tests/Responses/Expected/order/order_fulfilled_show_response.json
- tests/Responses/Expected/order/order_payed_show_response.json
- tests/Responses/Expected/order/order_shipped_show_response.json
- tests/Responses/Expected/order/order_shipped_with_tracking_show_response.json
- tests/Responses/Expected/order/order_show_response.json
- tests/Responses/Expected/order/order_with_coupon_based_promotion_show_response.json
- tests/Responses/Expected/order/order_with_promotion_show_response.json
- tests/Responses/Expected/payment/payment_index_response.json
- tests/Responses/Expected/payment/payment_show_response.json
> [Tests] Typo fix

- docs/bundles/SyliusFixturesBundle/custom_fixture.rst
Still figuring things out but I feel it lacks the call to children()
> typo + suggestion

- docs/book/orders/taxation.rst
> [Docs] Correct typo (book/order/taxation)

- src/Sylius/Bundle/PayumBundle/Resources/views/layout.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Field/money.html.twig
> Fix Twig templates

- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
> [Translation][UIBundle] Translation for filters

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/_mainImage.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_images.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_mainImage.html.twig
In order to avoid mixed content warnings when using https for your website
| Bug fix?        | yes, kind of |
> [Shop][Admin] Use schema independent url for placeholdit

- docs/bundles/SyliusGridBundle/field_types.rst
> [documentation] Fix English typos

- docs/bundles/SyliusGridBundle/custom_filter.rst
> [doc][custom_filters] fix form_options on custom filter documentation

- src/Sylius/Behat/Context/Setup/CustomerContext.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
> Generate address by resource factory in behat context

- etc/travis/suites/application/script.sh
- etc/travis/suites/application/script/validate-twig
| Related tickets | Fixes #8146 |
> Validate Twig files on Travis CI

- src/Sylius/Bundle/ThemeBundle/Tests/Translation/DependencyInjection/Compiler/TranslatorResourceProviderPassTest.php
- src/Sylius/Bundle/ThemeBundle/Translation/DependencyInjection/Compiler/TranslatorResourceProviderPass.php
| Related tickets | fixes #8123, closes #8125 |
> Make ThemeBundle compatibile with Symfony 3.3+

- features/product/managing_product_attributes/adding_select_product_attribute.feature
- src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/Configuration/SelectAttributeChoicesCollectionType.php
| Related tickets | fixes #8111, closes #8134 |
> Allow for select attribute values to contain non-latin characters

- docs/bundles/SyliusTaxonomyBundle/categorization.rst
Hey ! Thanks for your awesome job !
This is a little fix of a documentation exemple cause TaxonInterface has been moved from Bundle to Component.
> [Documentation] Updating target-entity of Taxonomy

- app/config/config.yml
| Bug fix?        | kinda |
| BC breaks?      | no ? |
| Related tickets | fixes #8163 |
As per instructions by @lchrusciel in #8163, opening this to allow the community to give their opinion :)
> Disable aliasing serializer service to jms_serializer.serializer

- docs/customization/form.rst
Form Extensions explained with ProductVariant example
> [Documentation] Customizing Forms: Extensions

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_images.html.twig
Just some defaults, better than none it seems.
> Add default alt text to images on product show page

- etc/travis/suites/docs/script.sh
| New feature?    | sort of |
I've improved the way we test the documentation, introducing a Linkcheck builder to ensure every link of the docs is reachable.
> Improved validation of documentation

- docs/components/Resource/model.rst
> [Documentation][Resource] Fix broken link.

- src/Sylius/Bundle/CoreBundle/Checkout/CheckoutResolver.php
- src/Sylius/Bundle/CoreBundle/Checkout/CheckoutStateUrlGenerator.php
- src/Sylius/Bundle/CoreBundle/Checkout/CheckoutStateUrlGeneratorInterface.php
- src/Sylius/Bundle/CoreBundle/spec/Checkout/CheckoutStateUrlGeneratorSpec.php
- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
| Related tickets | fixes #8185  |
> [Checkout] decoupled empty order logic from ShopBundle

- docs/book/architecture/emails.rst
- docs/book/installation/requirements.rst
- docs/book/installation/vagrant_installation.rst
- docs/book/orders/checkout.rst
- docs/book/orders/coupons.rst
- docs/book/orders/promotions.rst
- docs/book/orders/taxation.rst
- docs/components/Attribute/basic_usage.rst
- docs/components/Channel/basic_usage.rst
- docs/components/Channel/interfaces.rst
- docs/components/Inventory/interfaces.rst
- docs/plugins/index.rst
| Related tickets | fix current failing master |
> [HOTFIX] [Documentation] Fix links in documenation

- src/Sylius/Bundle/GridBundle/composer.json
- src/Sylius/Bundle/MailerBundle/composer.json
> Fix Travis packages build

- src/Sylius/Component/Order/composer.json
| Related tickets | closes #8207 |
#8207 rebased (thanks @harikt).
> Add webmozart/assert dependency to adjustment component

- docs/cookbook/disabling-shop-admin-api.rst
| Related tickets | closes #8219 |
#8219 rebased (thanks @aserratorta)! 🎉
> Fix sylius_api routing key example

- src/Sylius/Bundle/UserBundle/Controller/UserController.php
#7207 try to fix this issue, but the check was wrong. Tests will be added soon :)
> [User] Reset password request do not need template when API call

- docs/components/Resource/translation.rst
| Related tickets | closes #8205 |
#8205 rebased (thanks @harikt)! 🎉
> Fix the variable name in ResourceBundle docs

- src/Sylius/Component/Resource/Repository/InMemoryRepository.php
- src/Sylius/Component/Resource/spec/Repository/InMemoryRepositorySpec.php
> [Resource] Implement find method in InMemoryRepository

- UPGRADE.md
- docs/bundles/SyliusGridBundle/custom_filter.rst
- docs/cookbook/custom-promotion-action.rst
- docs/cookbook/custom-promotion-rule.rst
- src/Sylius/Bundle/AttributeBundle/DependencyInjection/Compiler/RegisterAttributeTypePass.php
- src/Sylius/Bundle/GridBundle/DependencyInjection/Compiler/RegisterFiltersPass.php
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/RegisterPromotionActionsPass.php
- src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/RegisterRuleCheckersPass.php
- src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/RegisterPromotionActionsPassTest.php
- src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/RegisterRuleCheckersPassTest.php
- src/Sylius/Bundle/ShippingBundle/DependencyInjection/Compiler/RegisterCalculatorsPass.php
| Related tickets | mentioned in #7838 |
> Use underscores for tag attribute names

- features/taxonomy/managing_taxons/deleting_taxon.feature
- src/Sylius/Bundle/TaxonomyBundle/Resources/config/doctrine/model/Taxon.orm.xml
| Bug fix?        | not yet |
| Related tickets | closes #7950 |
> Add a failing test scenario and fix #7950 (taxon deletion)

- UPGRADE.md
| Related tickets | related to #8096 |
> Mention that tag attributes changes does not apply for XML definitions

- src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/cart.yml
- src/Sylius/Bundle/ResourceBundle/Routing/Configuration.php
- src/Sylius/Bundle/ResourceBundle/Routing/ResourceLoader.php
| Related tickets | kinda fixes #8165, helps #8120 |
Makes it compatible with Symfony 3.3 🎉
> Make ResourceBundle routing working correctly again

- src/Sylius/Bundle/ShopBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ShopBundle/DependencyInjection/SyliusShopExtension.php
- src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/ShopBundle/Tests/DependencyInjection/ConfigurationTest.php
- src/Sylius/Bundle/ShopBundle/Tests/DependencyInjection/SyliusShopExtensionTest.php
| Q                      | A
| ------------------- | --------
| Bug fix?            | no       |
| New feature?    | no       |
| BC breaks?       | no       |
| Related tickets  | #8151 |
| License             | MIT     |
> Add support to configure the shop firewall context name

- src/Sylius/Component/Core/Uploader/ImageUploader.php
- src/Sylius/Component/Core/spec/Uploader/ImageUploaderSpec.php
| Related tickets | fixes #8236 |
Replacement of #8237 with adjusted specs. Thanks @psihius for the fix :)
> Check if image exists before trying to delete it

- src/Sylius/Behat/Service/Accessor/NotificationAccessor.php
- src/Sylius/Bundle/UiBundle/Resources/views/_flashes.html.twig
| Related tickets | fixes #7989 |
> Fix flash messages rendering

- UPGRADE.md
- src/Sylius/Bundle/AdminBundle/Controller/NotificationController.php
- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-notification.js
- src/Sylius/Bundle/AdminBundle/Resources/views/_notification.html.twig
- src/Sylius/Bundle/AdminBundle/Twig/NotificationWidgetExtension.php
| Related tickets | fixes #8108 |
> [Admin] add current Sylius version checker for admin panel notification

- src/Sylius/Bundle/AdminBundle/Controller/NotificationController.php
- src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/AdminBundle/Tests/Controller/NotificationControllerTest.php
| Related tickets | fixes #8108 |
> Send environment during GUS version check

- src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
| Related tickets | fixes #8257, introduced by #8253 |
> Remove CoreBundle -> ShopBundle coupling on UserImpersonator

- features/product/managing_products/select_taxons_for_product.feature
- src/Sylius/Behat/Resources/config/suites/ui/product/managing_products.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml
- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
- src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
| Related tickets | fixes #8130, fixes #8225, closes #8221 |
Thanks @bitbager for the initial PR I based on :)
> Do not rely on admin's locale for taxon autocomplete / tree select

- composer.lock
- src/Sylius/Behat/Service/Setter/CookieSetter.php
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
- src/Sylius/Bundle/UserBundle/Authentication/AuthenticationSuccessHandler.php
- src/Sylius/Bundle/UserBundle/Authentication/DefaultAuthenticationSuccessHandler.php
- src/Sylius/Bundle/UserBundle/DependencyInjection/Compiler/SymfonyCompatibilityPass.php
- src/Sylius/Bundle/UserBundle/SyliusUserBundle.php
| New feature?    | kinda |
| Related tickets | closes #8165, closes #8247 |
Blocking:
- https://github.com/symfony/symfony/pull/23411 (workaround https://github.com/Sylius/Sylius/pull/8120/commits/951e26db7f69d4e55a51a5a3cf7dc2f242c3bdd3)
- https://github.com/minkphp/MinkBrowserKitDriver/pull/118 (workaround https://github.com/Sylius/Sylius/pull/8120/commits/6f7d51fe83167f6cbe2106f34ea6581fca69fbdf)
Nice to have:
- https://github.com/symfony/symfony/issues/23412 (workaround https://github.com/Sylius/Sylius/pull/8247)
> Support Symfony 3.3

- features/addressing/managing_zones/editing_zone.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingZonesContext.php
- src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneCodeChoiceType.php
- src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneType.php
| Related tickets | fixes #3879 |
> Prevent adding a zone of type zone to itself

- src/Sylius/Component/Attribute/Model/AttributeValue.php
- src/Sylius/Component/Attribute/spec/Model/AttributeValueSpec.php
| Related tickets | fixes #8192 |
Thanks @David-Crty for reporting this bug and initial work! :)
> Make AttributeValue handle `null` values

- src/Sylius/Bundle/UiBundle/Resources/views/Layout/sidebar.html.twig
| Related tickets | fixes #8276 |
> Show pushable sidebar at pageload without animation

- src/Sylius/Component/Grid/Sorting/Sorter.php
- src/Sylius/Component/Grid/spec/Sorting/SorterSpec.php
| Related tickets | closes #8282 |
Thanks @vcraescu for bringing it up, wrote some specs for that bug and fixed the build. :)
> Fix sorter for fields with null sortable property

- src/Sylius/Bundle/ThemeBundle/Asset/Package/PathPackage.php
- src/Sylius/Bundle/ThemeBundle/spec/Asset/Package/PathPackageSpec.php
| Related tickets | closes #8283 |
Kudos to @regnisolbap for the initial PR and reporting this one :)
> [Theme] Handle absolute paths and urls in PathPackage

- src/Sylius/Behat/Context/Ui/Admin/LoginContext.php
| Related tickets | fixes #7321 |
> [Behat] Make logging again as admin step more reusable

- features/product/viewing_products/viewing_product_attributes.feature
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
| Related tickets | fixes #8295 |
> [Behat] Compare date attributes more loosely

- src/Sylius/Component/Attribute/Factory/AttributeFactory.php
- src/Sylius/Component/Attribute/spec/Factory/AttributeFactorySpec.php
There's no reason to forbid it.
> Allow to create new attributes without type

- docs/customization/template.rst
| Bug fix?        | kinda |
On top of fixing some of the typos found in the documentation, I have included some references to themes as another possible solution of template customization.
> [Documentation] Improve Templating customization

- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-notification.js
| Related tickets | fixes #8302 |
> Improve notification widget

- tests/DataFixtures/ORM/resources/admin_users.yml
- tests/DataFixtures/ORM/resources/associations.yml
- tests/DataFixtures/ORM/resources/cart.yml
- tests/DataFixtures/ORM/resources/cart_with_items.yml
- tests/DataFixtures/ORM/resources/channels.yml
- tests/DataFixtures/ORM/resources/checkout.yml
- tests/DataFixtures/ORM/resources/countries.yml
- tests/DataFixtures/ORM/resources/currencies.yml
- tests/DataFixtures/ORM/resources/customers.yml
- tests/DataFixtures/ORM/resources/exchange_rates.yml
- tests/DataFixtures/ORM/resources/payment_methods.yml
- tests/DataFixtures/ORM/resources/product_association_types.yml
- tests/DataFixtures/ORM/resources/product_attributes.yml
- tests/DataFixtures/ORM/resources/product_options.yml
- tests/DataFixtures/ORM/resources/products.yml
- tests/DataFixtures/ORM/resources/shipping_methods.yml
- tests/DataFixtures/ORM/resources/tax_rates.yml
I have added quotation to the strings and remove unnecessary object config
> [Tests] Minor fixtures cleanup

- package.json
- yarn.lock
| BC breaks?      | yes, for jQuery usage |
| Related tickets | fixes #8321  |
> replace jquery 2 with jquery 3

- UPGRADE.md
- src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/OrderBundle/composer.json
- src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php
| Related tickets | related to https://github.com/Sylius/Sylius/pull/8117#issuecomment-318310717 |
> OrderRepositoryInterface::count() -> OrderRepositoryInterface::countPlacedOrders()

- docs/cookbook/platform-sh.rst
> [Documentation] More explicit platform.sh guide

- src/Sylius/Component/Resource/Model/TranslatableTrait.php
> [Resource] Prevent extra translation lookup if locale is same as fallback locale

- src/Sylius/Component/User/Security/Generator/UniquePinGenerator.php
- src/Sylius/Component/User/Security/Generator/UniqueTokenGenerator.php
- src/Sylius/Component/User/spec/Security/Generator/UniquePinGeneratorSpec.php
- src/Sylius/Component/User/spec/Security/Generator/UniqueTokenGeneratorSpec.php
> [User] Drop pointless max length constraints for pin / token generators

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_sorting.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> change sylius.ui.display to sylius.ui.sort

- docs/book/installation/upgrading.rst
> [docs] Add link to and UPGRADE.md file

- UPGRADE.md
- src/Sylius/Component/Core/Checker/OrderShippingMethodSelectionRequirementChecker.php
- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/Model/OrderInterface.php
- src/Sylius/Component/Core/OrderProcessing/OrderShipmentProcessor.php
- src/Sylius/Component/Core/spec/Checker/OrderShippingMethodSelectionRequirementCheckerSpec.php
- src/Sylius/Component/Core/spec/OrderProcessing/OrderShipmentProcessorSpec.php
| Related tickets | mentioned in #8384 |
> Renamed `requiresShipping` method

- src/Sylius/Bundle/MoneyBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/MoneyBundle/DependencyInjection/SyliusMoneyExtension.php
- src/Sylius/Bundle/MoneyBundle/Form/DataTransformer/SyliusMoneyTransformer.php
- src/Sylius/Bundle/MoneyBundle/Form/Type/MoneyType.php
- src/Sylius/Bundle/MoneyBundle/Formatter/MoneyFormatter.php
- src/Sylius/Bundle/MoneyBundle/Formatter/MoneyFormatterInterface.php
- src/Sylius/Bundle/MoneyBundle/Templating/Helper/ConvertMoneyHelper.php
- src/Sylius/Bundle/MoneyBundle/Templating/Helper/ConvertMoneyHelperInterface.php
- src/Sylius/Bundle/MoneyBundle/Templating/Helper/FormatMoneyHelper.php
- src/Sylius/Bundle/MoneyBundle/Templating/Helper/FormatMoneyHelperInterface.php
- src/Sylius/Bundle/MoneyBundle/Twig/ConvertMoneyExtension.php
- src/Sylius/Bundle/MoneyBundle/Twig/FormatMoneyExtension.php
- src/Sylius/Bundle/MoneyBundle/spec/Form/DataTransformer/SyliusMoneyTransformerSpec.php
- src/Sylius/Bundle/MoneyBundle/spec/Formatter/MoneyFormatterSpec.php
- src/Sylius/Bundle/MoneyBundle/spec/Templating/Helper/ConvertMoneyHelperSpec.php
- src/Sylius/Bundle/MoneyBundle/spec/Templating/Helper/FormatMoneyHelperSpec.php
> [MoneyBundle] Use typehints introduced by PHP7+

- UPGRADE.md
- src/Sylius/Component/Registry/ExistingServiceException.php
- src/Sylius/Component/Registry/NonExistingServiceException.php
- src/Sylius/Component/Registry/PrioritizedServiceRegistry.php
- src/Sylius/Component/Registry/PrioritizedServiceRegistryInterface.php
- src/Sylius/Component/Registry/ServiceRegistry.php
- src/Sylius/Component/Registry/ServiceRegistryInterface.php
- src/Sylius/Component/Registry/spec/ExistingServiceExceptionSpec.php
- src/Sylius/Component/Registry/spec/NonExistingServiceExceptionSpec.php
- src/Sylius/Component/Registry/spec/PrioritizedServiceRegistrySpec.php
- src/Sylius/Component/Registry/spec/ServiceRegistrySpec.php
> [Registry] Use typehints introduced by PHP 7+

- UPGRADE.md
- src/Sylius/Bundle/CoreBundle/Context/CustomerContext.php
- src/Sylius/Bundle/CoreBundle/spec/EventListener/ReviewCreateListenerSpec.php
- src/Sylius/Bundle/CustomerBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/CustomerBundle/DependencyInjection/SyliusCustomerExtension.php
- src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerChoiceType.php
- src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerGroupChoiceType.php
- src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerGroupCodeChoiceType.php
- src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerGroupType.php
- src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerProfileType.php
- src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerType.php
- src/Sylius/Bundle/CustomerBundle/Form/Type/GenderType.php
- src/Sylius/Bundle/CustomerBundle/SyliusCustomerBundle.php
- src/Sylius/Component/Core/Context/ShopperContext.php
- src/Sylius/Component/Core/Model/Address.php
- src/Sylius/Component/Core/Model/Customer.php
- src/Sylius/Component/Core/Model/CustomerInterface.php
- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/Model/ShopUser.php
- src/Sylius/Component/Customer/Context/CustomerContextInterface.php
- src/Sylius/Component/Customer/Model/Customer.php
- src/Sylius/Component/Customer/Model/CustomerAwareInterface.php
- src/Sylius/Component/Customer/Model/CustomerGroup.php
- src/Sylius/Component/Customer/Model/CustomerGroupInterface.php
- src/Sylius/Component/Customer/Model/CustomerInterface.php
- src/Sylius/Component/Customer/spec/Model/CustomerGroupSpec.php
- src/Sylius/Component/Customer/spec/Model/CustomerSpec.php
- src/Sylius/Component/Review/Model/Reviewer.php
- src/Sylius/Component/Review/Model/ReviewerInterface.php
> [Customer] Use typehints introduced by PHP7+
