Sylius/Sylius

- UPGRADE.md
> [UPGRADE] Typo fix

- src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php
- src/Sylius/Bundle/PayumBundle/Action/ExecuteSameRequestWithPaymentDetailsAction.php
- src/Sylius/Bundle/PayumBundle/Action/Offline/ConvertPaymentAction.php
- src/Sylius/Bundle/PayumBundle/Action/Offline/ResolveNextRouteAction.php
- src/Sylius/Bundle/PayumBundle/Action/Offline/StatusAction.php
- src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php
- src/Sylius/Bundle/PayumBundle/Action/ResolveNextRouteAction.php
- src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
- src/Sylius/Bundle/PayumBundle/DependencyInjection/Compiler/RegisterGatewayConfigTypePass.php
- src/Sylius/Bundle/PayumBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/PayumBundle/DependencyInjection/SyliusPayumExtension.php
- src/Sylius/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php
- src/Sylius/Bundle/PayumBundle/Form/Extension/CryptedGatewayConfigTypeExtension.php
- src/Sylius/Bundle/PayumBundle/Form/Type/GatewayConfigType.php
- src/Sylius/Bundle/PayumBundle/Form/Type/PaypalGatewayConfigurationType.php
- src/Sylius/Bundle/PayumBundle/Form/Type/StripeGatewayConfigurationType.php
- src/Sylius/Bundle/PayumBundle/Model/GatewayConfig.php
- src/Sylius/Bundle/PayumBundle/Model/PaymentSecurityToken.php
- src/Sylius/Bundle/PayumBundle/Provider/PaymentDescriptionProvider.php
- src/Sylius/Bundle/PayumBundle/Provider/PaymentDescriptionProviderInterface.php
- src/Sylius/Bundle/PayumBundle/Request/GetStatus.php
- src/Sylius/Bundle/PayumBundle/Request/ResolveNextRoute.php
- src/Sylius/Bundle/PayumBundle/SyliusPayumBundle.php
- src/Sylius/Bundle/PayumBundle/spec/Action/CapturePaymentActionSpec.php
- src/Sylius/Bundle/PayumBundle/spec/Action/Offline/ConvertPaymentActionSpec.php
- src/Sylius/Bundle/PayumBundle/spec/Action/Offline/ResolveNextRouteActionSpec.php
- src/Sylius/Bundle/PayumBundle/spec/Action/Paypal/ExpressCheckout/ConvertPaymentActionSpec.php
- src/Sylius/Bundle/PayumBundle/spec/Action/ResolveNextRouteActionSpec.php
- src/Sylius/Bundle/PayumBundle/spec/Provider/PaymentDescriptionProviderSpec.php
| Related tickets | https://github.com/Sylius/Sylius/issues/8425 |
> [Payum] Scalar types in Payum

- UPGRADE.md
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Bundle/InventoryBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/InventoryBundle/DependencyInjection/SyliusInventoryExtension.php
- src/Sylius/Bundle/InventoryBundle/SyliusInventoryBundle.php
- src/Sylius/Bundle/InventoryBundle/Templating/Helper/InventoryHelper.php
- src/Sylius/Bundle/InventoryBundle/Twig/InventoryExtension.php
- src/Sylius/Bundle/InventoryBundle/Validator/Constraints/InStock.php
- src/Sylius/Bundle/InventoryBundle/Validator/Constraints/InStockValidator.php
- src/Sylius/Bundle/InventoryBundle/spec/Templating/Helper/InventoryHelperSpec.php
- src/Sylius/Bundle/InventoryBundle/spec/Validator/Constraints/InStockSpec.php
- src/Sylius/Bundle/InventoryBundle/spec/Validator/Constraints/InStockValidatorSpec.php
- src/Sylius/Bundle/InventoryBundle/test/app/AppKernel.php
- src/Sylius/Bundle/InventoryBundle/test/src/Tests/SyliusInventoryBundleTest.php
- src/Sylius/Component/Core/Model/OrderItemUnit.php
- src/Sylius/Component/Core/Model/ProductVariant.php
- src/Sylius/Component/Inventory/Checker/AvailabilityChecker.php
- src/Sylius/Component/Inventory/Checker/AvailabilityCheckerInterface.php
- src/Sylius/Component/Inventory/Model/InventoryUnit.php
- src/Sylius/Component/Inventory/Model/InventoryUnitInterface.php
- src/Sylius/Component/Inventory/Model/StockableInterface.php
- src/Sylius/Component/Inventory/spec/Checker/AvailabilityCheckerSpec.php
- src/Sylius/Component/Inventory/spec/Model/InventoryUnitSpec.php
| Related tickets | https://github.com/Sylius/Sylius/issues/8425 |
> [Inventory] Scalar types in Inventory

- UPGRADE.md
- src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonSlugController.php
- src/Sylius/Bundle/TaxonomyBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/TaxonomyBundle/DependencyInjection/SyliusTaxonomyExtension.php
- src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonAutocompleteChoiceType.php
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonPositionType.php
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonTranslationType.php
- src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonType.php
- src/Sylius/Component/Taxonomy/Factory/TaxonFactory.php
- src/Sylius/Component/Taxonomy/Factory/TaxonFactoryInterface.php
- src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php
- src/Sylius/Component/Taxonomy/Generator/TaxonSlugGeneratorInterface.php
- src/Sylius/Component/Taxonomy/Model/Taxon.php
- src/Sylius/Component/Taxonomy/Model/TaxonInterface.php
- src/Sylius/Component/Taxonomy/Model/TaxonTranslation.php
- src/Sylius/Component/Taxonomy/Model/TaxonTranslationInterface.php
- src/Sylius/Component/Taxonomy/Model/TaxonsAwareInterface.php
- src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
- src/Sylius/Component/Taxonomy/spec/Factory/TaxonFactorySpec.php
- src/Sylius/Component/Taxonomy/spec/Generator/TaxonSlugGeneratorSpec.php
- src/Sylius/Component/Taxonomy/spec/Model/TaxonSpec.php
- src/Sylius/Component/Taxonomy/spec/Model/TaxonTranslationSpec.php
> [Taxonomy] Use typehints introduced by PHP7+

- src/Sylius/Bundle/UiBundle/Block/BlockEventListener.php
- src/Sylius/Bundle/UiBundle/Controller/SecurityController.php
- src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php
- src/Sylius/Bundle/UiBundle/Form/Type/SecurityLoginType.php
- src/Sylius/Bundle/UiBundle/Menu/Event/MenuBuilderEvent.php
- src/Sylius/Bundle/UiBundle/Twig/PercentageExtension.php
- src/Sylius/Bundle/UiBundle/Twig/SortByExtension.php
- src/Sylius/Bundle/UiBundle/spec/Controller/SecurityControllerSpec.php
- src/Sylius/Bundle/UiBundle/spec/Twig/PercentageExtensionSpec.php
- src/Sylius/Bundle/UiBundle/spec/Twig/SortByExtensionSpec.php
> [UiBundle] Use typehints introduced by PHP7+

- UPGRADE.md
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_breadcrumb.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/_breadcrumb.html.twig
- src/Sylius/Component/Taxonomy/Model/Taxon.php
- src/Sylius/Component/Taxonomy/Model/TaxonInterface.php
- src/Sylius/Component/Taxonomy/spec/Model/TaxonSpec.php
| Related tickets | introduced by #8447 |
> Bring back method for getting taxon's ancestors

- UPGRADE.md
- src/Sylius/Bundle/AdminBundle/Controller/CustomerStatisticsController.php
- src/Sylius/Bundle/AdminBundle/Controller/DashboardController.php
- src/Sylius/Bundle/AdminBundle/Controller/ImpersonateUserController.php
- src/Sylius/Bundle/AdminBundle/Controller/NotificationController.php
- src/Sylius/Bundle/AdminBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/AdminBundle/DependencyInjection/SyliusAdminExtension.php
- src/Sylius/Bundle/AdminBundle/EmailManager/ShipmentEmailManager.php
- src/Sylius/Bundle/AdminBundle/EmailManager/ShipmentEmailManagerInterface.php
- src/Sylius/Bundle/AdminBundle/Event/CustomerShowMenuBuilderEvent.php
- src/Sylius/Bundle/AdminBundle/Event/OrderShowMenuBuilderEvent.php
- src/Sylius/Bundle/AdminBundle/Event/ProductMenuBuilderEvent.php
- src/Sylius/Bundle/AdminBundle/Event/ProductVariantMenuBuilderEvent.php
- src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteSubscriber.php
- src/Sylius/Bundle/AdminBundle/EventListener/ShipmentShipListener.php
- src/Sylius/Bundle/AdminBundle/Menu/CustomerShowMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Menu/OrderShowMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Menu/ProductFormMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Menu/ProductVariantFormMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/SyliusAdminBundle.php
- src/Sylius/Bundle/AdminBundle/Tests/Controller/NotificationControllerTest.php
- src/Sylius/Bundle/AdminBundle/Twig/NotificationWidgetExtension.php
- src/Sylius/Bundle/AdminBundle/spec/Context/AdminBasedLocaleContextSpec.php
- src/Sylius/Bundle/AdminBundle/spec/Event/CustomerShowMenuBuilderEventSpec.php
- src/Sylius/Bundle/AdminBundle/spec/Event/OrderShowMenuBuilderEventSpec.php
- src/Sylius/Bundle/AdminBundle/spec/EventListener/ShipmentShipListenerSpec.php
- src/Sylius/Bundle/AdminBundle/spec/Menu/CustomerShowMenuBuilderSpec.php
- src/Sylius/Bundle/AdminBundle/spec/Menu/OrderShowMenuBuilderSpec.php
| Related tickets | https://github.com/Sylius/Sylius/issues/8425 |
> [AdminBundle] Scalar types in Admin

- features/checkout/addressing_order/choosing_billing_and_shipping_address_from_address_book.feature
> [Behat] Improve feature description

- src/Sylius/Bundle/ThemeBundle/Collector/ThemeCollector.php
- src/Sylius/Bundle/ThemeBundle/HierarchyProvider/ThemeHierarchyProviderInterface.php
| Related tickets | introduced by #8450 |
> [Theme] Do not crash on dev environment

- src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/promotion_coupon.yml
- src/Sylius/Bundle/PromotionBundle/Doctrine/ORM/PromotionCouponRepository.php
- src/Sylius/Component/Promotion/Repository/PromotionCouponRepositoryInterface.php
- tests/DataFixtures/ORM/resources/promotion_coupons.yml
- tests/DataFixtures/ORM/resources/promotions.yml
- tests/Responses/Expected/promotion/filtered_by_code_and_name_index_response.json
- tests/Responses/Expected/promotion/index_response.json
- tests/Responses/Expected/promotion/only_coupon_based_index_response.json
- tests/Responses/Expected/promotion/sorted_by_code_index_response.json
- tests/Responses/Expected/promotion/sorted_by_name_index_response.json
- tests/Responses/Expected/promotion/sorted_by_priority_index_response.json
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/8025, closes https://github.com/Sylius/Sylius/pull/8024 |
Thanks @alcaeus for pointing this out.
> [API][Promotion] Index coupons only for requested promotion

- app/migrations/Version20170824124122.php
- src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Order.orm.xml
| Related tickets | fixes #8326 |
> [Order] change Order notes type as text

- docs/book/products/products.rst
I was not able to create a variant without the code and position attributes set (MySQL complains that they cannot be null).
> Documents required Variant attributes

- UPGRADE.md
- src/Sylius/Bundle/MailerBundle/Sender/Adapter/SwiftMailerAdapter.php
- src/Sylius/Bundle/ShopBundle/EmailManager/ContactEmailManager.php
- src/Sylius/Bundle/ShopBundle/spec/EmailManager/ContactEmailManagerSpec.php
- src/Sylius/Component/Mailer/Event/EmailSendEvent.php
- src/Sylius/Component/Mailer/Sender/Adapter/AdapterInterface.php
- src/Sylius/Component/Mailer/Sender/Sender.php
- src/Sylius/Component/Mailer/Sender/SenderInterface.php
- src/Sylius/Component/Mailer/spec/Sender/SenderSpec.php
| Related tickets | mentioned in #8371  |
> [Mailer] add reply-to on contact request email

- src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php
| Related tickets | #8328 |
With this fix we can define our own mapping to resolve #8328
> [ResourceBundle] Add check before add translation mapping

- src/Sylius/Behat/Context/Cli/InstallerContext.php
- src/Sylius/Behat/Service/SharedStorage.php
- src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/SelectAttributeType.php
- src/Sylius/Bundle/CoreBundle/Command/CancelUnpaidOrdersCommand.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/AddressExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductReviewExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/OptionsResolver/LazyOption.php
- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
- src/Sylius/Bundle/CoreBundle/Form/DataTransformer/ProductsToCodesTransformer.php
- src/Sylius/Bundle/CoreBundle/Form/DataTransformer/TaxonsToCodesTransformer.php
- src/Sylius/Bundle/CoreBundle/Installer/Requirement/SettingsRequirements.php
- src/Sylius/Bundle/GridBundle/spec/Doctrine/PHPCRODM/DriverSpec.php
- src/Sylius/Bundle/MailerBundle/Sender/Adapter/SwiftMailerAdapter.php
- src/Sylius/Bundle/MailerBundle/spec/Renderer/Adapter/EmailTwigAdapterSpec.php
- src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductGenerateVariantsType.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Extension/AbstractResourceExtension.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php
- src/Sylius/Bundle/ThemeBundle/Asset/Installer/OutputAwareAssetsInstaller.php
- src/Sylius/Component/Core/Distributor/ProportionalIntegerDistributor.php
- src/Sylius/Component/Core/Provider/ActivePromotionsByChannelProvider.php
- src/Sylius/Component/Core/spec/Taxation/Applicator/OrderShipmentTaxesApplicatorSpec.php
- src/Sylius/Component/Mailer/Model/Email.php
- src/Sylius/Component/Promotion/Generator/PercentageGenerationPolicy.php
- src/Sylius/Component/Resource/Metadata/Metadata.php
- src/Sylius/Component/Taxation/Model/TaxRate.php
Minor code tweaks on behalf of people from Sylius community =)
> SCA with Php Inspections (EA Extended)

- UPGRADE.md
- src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/promotion_coupon.yml
- src/Sylius/Bundle/PromotionBundle/Doctrine/ORM/PromotionCouponRepository.php
- src/Sylius/Component/Promotion/Repository/PromotionCouponRepositoryInterface.php
| BC breaks?      | no (just documented previous one) |
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/8483 |
> [Promotion] Change misleading PromotionCouponRepository method name

- src/Sylius/Bundle/ThemeBundle/Model/Theme.php
- src/Sylius/Component/Attribute/Model/Attribute.php
- src/Sylius/Component/Product/Model/Product.php
| Related tickets | fixes #8020 |
> Cast return values of __toString() as string

- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/address.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectPayment.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectShipping.html.twig
| Related tickets | fixes #8355 |
> [Checkout] Add missing form errors block

- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/Statistics/index.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.bg.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.de.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.es.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.fr.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.it.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.lt.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.nl.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.pl.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.pt_BR.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.ru.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.sk.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.th.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.uk.yml
| Related tickets | fixes #8008 |
@TODO: I just updated translations for French and English labels, need help for translating other languages.
> [Admin][Customer]Issue 8008: Fix inappropriate statistic message

- features/promotion/managing_coupons/generating_coupon.feature
- src/Sylius/Component/Promotion/Generator/PromotionCouponGeneratorInstruction.php
- src/Sylius/Component/Promotion/Generator/PromotionCouponGeneratorInstructionInterface.php
> [Promotion] Allow to generate coupons without expiration date

- src/Sylius/Component/Grid/Definition/ArrayToDefinitionConverter.php
- src/Sylius/Component/Grid/Definition/Field.php
| Related tickets | closes #8524 |
> Fix ArrayToDefinitionConverter after introducing scalar types there

- docs/bundles/SyliusGridBundle/your_first_grid.rst
| Related tickets | fixes #7794 |
Solution as mentioned in #7794 by @lchrusciel.
> [Docs] Add sortable field to sorting grid documentation (fixes #7794)

- src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/8351 |
> [Installer] Use migrations for Sylius installation

- src/Sylius/Bundle/ResourceBundle/Controller/ResourcesCollectionProvider.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourcesCollectionProviderSpec.php
fix limit being parsed to resolveMaxPerPage - must be ?int
| Related tickets | #8439 |
> fix limit type

- features/account/customer_account/address_book/deleting_address_created_after_checkout.feature
- features/account/customer_account/address_book/setting_default_address.feature
- features/account/customer_account/address_book/viewing_addresses_created_after_checkout.feature
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPage.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/account/address_book.yml
- src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
| Related tickets | fixes #8168 |
> [AddressBook] Fix problem with cloning default address during checkout

- UPGRADE.md
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product_variant.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Form/imagesTheme.html.twig
- src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php
- src/Sylius/Component/Product/Repository/ProductVariantRepositoryInterface.php
| Related tickets | fixes #8336 |
> [Admin][Product] Fix SQL error on selecting products variants for a product image

- features/product/managing_products/adding_product_with_integer_attribute.feature
- features/product/managing_products/adding_product_with_percent_attribute.feature
- src/Sylius/Behat/Context/Setup/ProductAttributeContext.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Component/Attribute/AttributeType/IntegerAttributeType.php
- src/Sylius/Component/Attribute/AttributeType/PercentAttributeType.php
| Related tickets | fixes #8486 |
> Fix the error happening while creating integer / percent attribute values

- src/Sylius/Bundle/ResourceBundle/Controller/ParametersParser.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ParametersParserSpec.php
| Related tickets | related to #8507 |
> ParametersParser - bugfixes & enhancements related to typecasting

- UPGRADE.md
| Related tickets | closes #8425 |
> Add UPGRADE.md note about scalar / return typehints

- UPGRADE.md
- features/admin/dashboard.feature
- features/admin/dashboard_per_channel.feature
- features/user/managing_customers/seeing_orders_statistics_on_customer_details_page.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_statistics.html.twig
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Dashboard/DashboardStatisticsProvider.php
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
- src/Sylius/Component/Core/spec/Dashboard/DashboardStatisticsProviderSpec.php
| Related tickets | fixes #8251 |
It is based on #8285 and associated with #8516
> [Admin] Fix statistics to take into account only fulfilled orders

- docs/book/installation/installation.rst
- docs/components_and_bundles/bundles/SyliusResourceBundle/index_resources.rst
- docs/components_and_bundles/bundles/SyliusResourceBundle/routing.rst
| Related tickets | fixes #8063 |
> [Documentation] Suggest yarn version

- src/Sylius/Bundle/ShopBundle/Resources/config/routing/partial/product_review.yml
| Related tickets | fixes #8544 |
> Fix entity int typing in bundle's routing

- src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/update.html.twig
- src/Sylius/Bundle/OrderBundle/Form/Type/OrderType.php
| Related tickets | fixes #8346 |
Based on PR created by @bricelalu (#8513)
> [Admin][Order] Change PATCH to PUT in the order update action

- docs/contributing/index.rst
- docs/contributing/map.rst.inc
- docs/contributing/translations/index.rst
| Related tickets | fixes #8044 |
> [Documentation] Contributing translations

- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Generate/_form.html.twig
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductGenerateVariantsType.php
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
> [Admin] Improve the variant generation form UI

- src/Sylius/Bundle/CoreBundle/Application/SyliusPluginTrait.php
- src/Sylius/Bundle/CoreBundle/Tests/Application/SyliusPluginTraitTest.php
> Make SyliusPluginTrait great again (or at least not crashing peoples' apps)

- UPGRADE.md
- features/admin/placing_order_as_impersonated_customers.feature
- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
- src/Sylius/Behat/Resources/config/suites/ui/admin/impersonating_customers.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/services/integrations/shop.xml
- src/Sylius/Bundle/CoreBundle/Context/SessionAndChannelBasedCartContext.php
- src/Sylius/Bundle/CoreBundle/EventListener/UserImpersonatedListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/context.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php
- src/Sylius/Bundle/CoreBundle/Storage/CartSessionStorage.php
- src/Sylius/Bundle/CoreBundle/spec/Context/SessionAndChannelBasedCartContextSpec.php
- src/Sylius/Bundle/CoreBundle/spec/EventListener/UserImpersonatedListenerSpec.php
- src/Sylius/Bundle/CoreBundle/spec/Storage/CartSessionStorageSpec.php
- src/Sylius/Bundle/UserBundle/UserEvents.php
- src/Sylius/Component/Core/Storage/CartStorageInterface.php
| Related tickets | fixes #8127 and #8254 |
> [Admin] Add listener to resolve cart of an impersonated customer

- src/Sylius/Component/Taxonomy/Model/TaxonInterface.php
| Related tickets | fixes #8568  |
> Add slug aware interface to Taxon interface, model has method (fixes #8568)

- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Action/ChannelBasedFixedDiscountConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Action/ChannelBasedUnitFixedDiscountConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Action/ChannelBasedUnitPercentageDiscountConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Rule/ChannelBasedItemTotalConfigurationType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml
- src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml
> move channel dependent promotion rules and actions to SyliusCoreBundle

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/CustomerRepository.php
- src/Sylius/Component/Core/Dashboard/DashboardStatisticsProvider.php
- src/Sylius/Component/Core/Repository/CustomerRepositoryInterface.php
- src/Sylius/Component/Core/spec/Dashboard/DashboardStatisticsProviderSpec.php
| Related tickets | fixes #8566 |
> [Customer] Rename count() repository method to countCustomers()

- composer.json
- composer.lock
> Update requirement for akeneo/phpspec-skip-example-extension to ^3.0

- UPGRADE.md
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/Handler/ResourceDeleteHandler.php
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/Handler/ResourceUpdateHandler.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/spec/Doctrine/ORM/Handler/ResourceDeleteHandlerSpec.php
- src/Sylius/Bundle/CoreBundle/spec/Doctrine/ORM/Handler/ResourceUpdateHandlerSpec.php
- src/Sylius/Bundle/ResourceBundle/Controller/EventDispatcher.php
- src/Sylius/Bundle/ResourceBundle/Controller/EventDispatcherInterface.php
- src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php
- src/Sylius/Bundle/ResourceBundle/Controller/ResourceDeleteHandler.php
- src/Sylius/Bundle/ResourceBundle/Controller/ResourceDeleteHandlerInterface.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDriver.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/ResourceBundle/spec/Controller/EventDispatcherSpec.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceControllerSpec.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourceDeleteHandlerSpec.php
- src/Sylius/Component/Resource/Exception/DeleteHandlingException.php
- src/Sylius/Component/Resource/Exception/UpdateHandlingException.php
- src/Sylius/Component/Resource/spec/Exception/DeleteHandlingExceptionSpec.php
- src/Sylius/Component/Resource/spec/Exception/UpdateHandlingExceptionSpec.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/7305, replaces https://github.com/Sylius/Sylius/pull/8465 |
Thank you @ste93cry for making a base for this PR 👍
> [Resource] Resource events consistency

- UPGRADE.md
| Related tickets | fixes #8564 |
> Show autoload changes in readme for upgrade beta3 -> 1.0 (fixes #8564)

- src/Sylius/Bundle/AddressingBundle/Form/Type/CountryChoiceType.php
- src/Sylius/Bundle/AddressingBundle/phpunit.xml.dist
- src/Sylius/Bundle/AddressingBundle/test/Tests/Form/Type/CountryChoiceTypeTest.php
> Add filter option to country choice type

- bin/symfony_requirements
- composer.json
- composer.lock
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
| Related tickets | mentioned in #8565, closing #8570  |
Based on @stefandoorn work, just to merge it faster.
> Require ^3.3.8 for Symfony - when in 3.3.x

- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-product-images-preview.js
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/6771 |
Quick preview 🐃 :
https://youtu.be/geTNGacvSHI
> [Admin] Display product and taxon images right after upload

- src/Sylius/Bundle/PayumBundle/Action/ResolveNextRouteAction.php
- src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
- src/Sylius/Bundle/PayumBundle/Factory/GetStatusFactory.php
- src/Sylius/Bundle/PayumBundle/Factory/GetStatusFactoryInterface.php
- src/Sylius/Bundle/PayumBundle/Factory/ResolveNextRouteFactory.php
- src/Sylius/Bundle/PayumBundle/Factory/ResolveNextRouteFactoryInterface.php
- src/Sylius/Bundle/PayumBundle/Request/GetStatus.php
- src/Sylius/Bundle/PayumBundle/Request/ResolveNextRoute.php
- src/Sylius/Bundle/PayumBundle/Request/ResolveNextRouteInterface.php
- src/Sylius/Bundle/PayumBundle/Resources/config/services.xml
- src/Sylius/Bundle/PayumBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/PayumBundle/Resources/config/services/factory.xml
- src/Sylius/Bundle/PayumBundle/spec/Factory/GetStatusFactorySpec.php
- src/Sylius/Bundle/PayumBundle/spec/Factory/ResolveNextRouteFactorySpec.php
- src/Sylius/Bundle/PayumBundle/spec/Request/GetStatusSpec.php
- src/Sylius/Bundle/PayumBundle/spec/Request/ResolveNextRouteSpec.php
- src/Sylius/Component/Payment/Model/PaymentInterface.php
> [Payum] Support authorize action

- docs/book/architecture/state_machine.rst
- src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order.yml
- src/Sylius/Component/Core/TokenAssigner/OrderTokenAssignerInterface.php
- src/Sylius/Component/Core/TokenAssigner/UniqueIdBasedOrderTokenAssigner.php
- src/Sylius/Component/Core/spec/TokenAssigner/UniqueIdBasedOrderTokenAssignerSpec.php
The logic will be more consistent if we assign a token only when there is no other value.
> [Core] Improve token assigner

- UPGRADE.md
- app/config/routing.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing.yml
| Related tickets | fixes #7984 |
> [Shop] [Admin] Move liip imagine routing to the main app

- docs/cookbook/admin-js-and-css.rst
- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
- docs/customization/template.rst
| Related tickets | fixes #8002 |
> [Documentation][Cookbook] How to add custom JS & CSS to Admin?

- features/promotion/receiving_discount/receiving_percentage_discount_on_shipping.feature
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
> [Behat][Promotion] Add additional scenarios for receiving percentage discount on shipping

- UPGRADE.md
- src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/locale/storage.xml
- src/Sylius/Bundle/ShopBundle/Router/LocaleStrippingRouter.php
- src/Sylius/Bundle/ShopBundle/spec/Router/LocaleStrippingRouterSpec.php
| Bug fix?        | kinda |
| New feature?    | kinda |
| BC breaks?      | a really small one |
| Related tickets | fixes #7970 |
> [Shop] Strip _locale parameter from URL if using storage locale switcher

- app/config/config.yml
- composer.json
- composer.lock
- src/Sylius/Bundle/CoreBundle/composer.json
- src/Sylius/Bundle/CustomerBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ResourceBundle/composer.json
| Related tickets | fixes #8193  |
> [Maintenance] Upgrade JMS Serializer Bundle to 2.0

- app/config/config_staging.yml
- web/app_staging.php
| Related tickets | fixes #8455 |
Not sure if should duplicate the prod config or import it
> [Maintenance] Add staging environment

- features/account/customer_account/redirect_when_already_signed_in.feature
- src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/security.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/routing/security.yml
- src/Sylius/Bundle/UiBundle/Controller/SecurityController.php
- src/Sylius/Bundle/UiBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/UiBundle/spec/Controller/SecurityControllerSpec.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/3448 |
> Disable the access to login page for already logged in customers/admins

- src/Sylius/Component/Channel/Context/ChannelNotFoundException.php
> [DX] Add tip about switching channel in toolbar

- UPGRADE.md
- features/account/customer_account/viewing_orders_history/viewing_order_only_from_current_channel.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Resources/config/suites/ui/account/customer.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/account/order.yml
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
> [Account] Display orders only from current channel

- docs/book/introduction/environments.rst
| Related tickets | documentation for #8581 |
> [Documentation] Describe staging environment

- docs/book/architecture/emails.rst
- docs/cookbook/index.rst
- docs/cookbook/mailer.rst
- docs/cookbook/map.rst.inc
| Related tickets | fixes #8065 |
> [Documentation][Cookbook] How to configure mailer?

- src/Sylius/Bundle/CoreBundle/Collector/SyliusCollector.php
> Do not let debug toolbar crash when channel cannot be found

- docs/book/themes/themes.rst
| Related tickets | Fixes https://github.com/Sylius/Sylius/issues/8161 |
> Remove non-existent feature from theming docs

- app/TestAppKernel.php
- src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php
- src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php
- src/Sylius/Behat/Page/Admin/Taxon/UpdatePage.php
- src/Sylius/Bundle/CoreBundle/EventListener/ImagesRemoveListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/CoreBundle/composer.json
- src/Sylius/Bundle/CoreBundle/spec/EventListener/ImagesRemoveListenerSpec.php
- src/Sylius/Component/Core/Uploader/ImageUploader.php
- src/Sylius/Component/Core/spec/Uploader/ImageUploaderSpec.php
> [File] Removing file on entity delete

- UPGRADE.md
- app/config/config.yml
- app/config/parameters.yml.dist
> Remove locale from parameters.yml just like Sylius-Standard

- src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/integrations/hwi_oauth.xml
- src/Sylius/Bundle/CoreBundle/spec/OAuth/UserProviderSpec.php
| Related tickets | https://github.com/Sylius/Sylius/pull/8273 |
> [Core] Oauth fix

- docs/customization/model.rst
| Doc fix?        | yes! |
| Related tickets | fixes #8023 |
> [Documentation] Customizing translatable fields of translatable models fix

- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
- src/Sylius/Bundle/ShopBundle/Resources/views/_footer.html.twig
> Prepare RC1 Release

- features/user/managing_customers/changing_customer_email.feature
- src/Sylius/Behat/Context/Setup/CustomerContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
- src/Sylius/Behat/Resources/config/suites/ui/user/managing_customers.yml
> [Customer] Changing an email of a customer

- src/Sylius/Behat/Context/Ui/Shop/CheckoutContext.php
- src/Sylius/Bundle/CoreBundle/EventListener/UserImpersonatedListener.php
- src/Sylius/Bundle/ShopBundle/EventListener/ShopUserLogoutHandler.php
- src/Sylius/Component/Core/OrderProcessing/OrderPaymentProcessor.php
- src/Sylius/Component/Core/Shipping/Calculator/FlatRateCalculator.php
> Remove unused use statements

- docs/cookbook/stripe.rst
- src/Sylius/Bundle/PayumBundle/Form/Type/StripeGatewayConfigurationType.php
> [Documentation][PaymentMethod] Minor stripe fixes

- docs/cookbook/embedding-products.rst
| Related tickets | fixes #8212 |
> [Documentation][Fix] How to embed a list of products?

- bin/symfony_requirements
- composer.json
- composer.lock
| Related tickets | https://github.com/Sylius/Sylius/pull/8576#discussion_r138279604 |
Thanks @bendavies for pointing it out 👍
> [Maintenance] Upgrade distribution bundle

- features/shipping/managing_shipping_methods/shipping_method_validation.feature
| Related tickets | mentioned in https://github.com/Sylius/Sylius/issues/8426 |
Moreover, the scenario was broken (wrong name in the last step).
> [Behat] Enable shipping method name validation scenario

- UPGRADE.md
- src/Sylius/Bundle/AdminBundle/Resources/views/Customer/_form.html.twig
- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/AddUserFormSubscriber.php
- src/Sylius/Bundle/CoreBundle/spec/Form/EventSubscriber/AddUserFormSubscriberSpec.php
- src/Sylius/Component/Core/Model/Customer.php
- src/Sylius/Component/Core/Model/ShopUser.php
| Related tickets | fixes #8597 |
> Synchronise customer / user emails correctly when editing them in admin panel

- docs/book/orders/promotions.rst
| Related tickets | fixes #8118 |
> [Documentation] More detailed docs of Promotion Actions vs. Filters

- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/string.html.twig
> [Twig][UiBundle] fix value's label on string filter type

- docs/book/installation/installation.rst
| Bug fix?        | no/yes |
| New feature?    | no/yes |
| BC breaks?      | no/yes |
> Update installation instructions

- docs/api/introduction.rst
> [Documentation] Link Rest Api docs with Api cookbook

- README.md
- docs/contributing/index.rst
> [Documentation] Installing RC

- features/account/verification/verifying_email_address.feature
- src/Sylius/Behat/Context/Setup/ChannelContext.php
- src/Sylius/Behat/Resources/config/suites/ui/account/email_verification.yml
- src/Sylius/Bundle/ShopBundle/EventListener/UserRegistrationListener.php
- src/Sylius/Bundle/ShopBundle/spec/EventListener/UserRegistrationListenerSpec.php
> [Account Verification] Fix sending email verification

- src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/RequestConfigurationSpec.php
- tests/Controller/CustomerApiTest.php
- tests/Responses/Expected/customer/page_not_found_response.json
| Related tickets | fixes #8631  |
> [Resouce] Fix 0 page paginator

- src/Sylius/Component/Core/Model/ShopUser.php
> Remove unused use statement

- README.md
Link the tag directly to the tagged search.
> Link directly to tags on Stackoverflow from README

- src/Sylius/Bundle/PayumBundle/Model/PaymentSecurityToken.php
After discussion with @lchrusciel in #8608 and @pamil on Slack.
> Remove return type in PaymentSecurityToken, might not always be correct

- src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
> [Ui] Grid overflow x

- src/Sylius/Bundle/ShopBundle/Resources/views/Email/orderConfirmation.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Email/passwordReset.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Email/verification.html.twig
| Related tickets | fixes #8649, relates to #7985 |
replace the Raw URL in the verification email to a link
> fix verification email url

- UPGRADE.md
| Related tickets | partially #8642 |
> UPGRADE file: Tips on 1.0.0 update

- docs/cookbook/platform-sh.rst
> [Docs] HotFix link

- UPGRADE.md
- src/Sylius/Component/Attribute/Model/AttributeInterface.php
- src/Sylius/Component/Attribute/Model/AttributeTranslationInterface.php
- src/Sylius/Component/Payment/Model/PaymentMethodInterface.php
- src/Sylius/Component/Payment/Model/PaymentMethodTranslationInterface.php
- src/Sylius/Component/Product/Model/ProductAssociationTypeTranslationInterface.php
- src/Sylius/Component/Product/Model/ProductOptionInterface.php
- src/Sylius/Component/Product/Model/ProductOptionTranslationInterface.php
- src/Sylius/Component/Product/Model/ProductOptionValueTranslationInterface.php
- src/Sylius/Component/Product/Model/ProductTranslationInterface.php
- src/Sylius/Component/Product/Model/ProductVariantTranslationInterface.php
- src/Sylius/Component/Shipping/Model/ShippingMethodInterface.php
- src/Sylius/Component/Shipping/Model/ShippingMethodTranslationInterface.php
| Related tickets | based on #8653 |
> [Translation] Use TranslationInterface

- README.md
- docs/book/installation/installation.rst
- docs/contributing/index.rst
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
> Prepare v1.0.0 Stable Release

- README.md
> Make README great again

- docs/plugins/creating-plugin.rst
| Related tickets | fixes #8661 |
you're welcome @bitbager ;)
> fix link to BitBager PayUPlugin

- src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
> [ResourceBundle] Fix variable name

- docs/book/installation/requirements.rst
- docs/contributing/code/patches.rst
- docs/plugins/creating-plugin.rst
> [Documentation] Fix PHP min version

- docs/components_and_bundles/bundles/SyliusFixturesBundle/architecture.rst
- src/Sylius/Bundle/FixturesBundle/Tests/DependencyInjection/ConfigurationTest.php
> [Fixtures] Docs & tests about disabling listeners / fixtures in a suite

- docs/book/orders/checkout.rst
Just a little fix for a valid example code
> [Documentation] Syntax typo fix

- .gitignore
| Bug fix?        | no/yes |
| New feature?    | no/yes |
| BC breaks?      | no/yes |
> gitignore webserver pid files

- etc/travis/suites/application/script.sh
- etc/travis/suites/application/script/validate-yarn-packages
| New feature?    | kind of |
Adding [Yarn check](https://yarnpkg.com/en/docs/cli/check)
I've tried both commands but the second one is not verbose enough!
> [Travis] Validating yarn packages on travis tests suite

- src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/AddUserFormSubscriber.php
- src/Sylius/Bundle/PayumBundle/Model/PaymentSecurityToken.php
- src/Sylius/Component/Core/Model/Customer.php
> Fix coding standard

- features/cart/shopping_cart/changing_display_currency_of_cart.feature
> [Behat] Minor typo fix

- UPGRADE-1.1.md
| Related tickets | related to #8712 |
> Set up upgrade file for 1.1

- docs/book/installation/upgrading.rst
> [Documentation] Fix broken link to UPGRADE file

- docs/components_and_bundles/bundles/SyliusTaxationBundle/configuring_taxation.rst
Create a new PR since #8721 had to be rebased. Hope it is fine now :-)
> [Docs] Typos in SyliusTaxationBundle

- src/Sylius/Bundle/UiBundle/Resources/private/js/app.js
| Related tickets | fixes #8732 |
> Do not close sidebar when clicking outside of it

- docs/contributing/code/standards.rst
> Add coding standard section to docs

- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
| Related tickets | fixes #8735 |
> Load lazy taxon tree using a single click

- docs/book/configuration/locales.rst
| Related tickets | related with #8780 
> [Documentation] Update locales page in book

- docs/contributing/code/patches.rst
> [Documentation] Update PR template in contribution guide

- src/Sylius/Bundle/UserBundle/Controller/UserController.php
- src/Sylius/Bundle/UserBundle/Resources/translations/flashes.en.yml
| Related tickets | fixes #8769 
> [UserBundle] Decouple UserBundle from CoreBundle

- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ProductImage.orm.xml
| Related tickets | associated with #8762
> [ProductImage] Fix association between images and variants

- src/Sylius/Bundle/AdminApiBundle/Form/Type/OrderType.php
- src/Sylius/Bundle/AdminApiBundle/Resources/config/services/form.xml
| Related tickets | fixes #8776 
> Changed CustomerChoiceType for a ResourceToIdentifierTransformer in OrderType of SyliusAdminApiBundle

- docs/components_and_bundles/bundles/SyliusShippingBundle/custom_calculators.rst
| Related tickets | fixes #7929, #8139, #8176
> [Documentation] Update docs about creating custom shipping calculators

- docs/components_and_bundles/bundles/SyliusTaxationBundle/custom_calculators.rst
> [Documentation] Update docs about creating custom tax calculators

- features/promotion/reverting_discount/reverting_previously_applied_discount_on_cart.feature
Related to [this tweet](https://twitter.com/juukie14/status/917640032932057088)
> [tests] Remove duplicate scenario

- src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/ShopBundle/EventListener/UserImpersonatedListener.php
- src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/ShopBundle/spec/EventListener/UserImpersonatedListenerSpec.php
| Related tickets | fixes #8764
> Move user impersonated listener to shop bundle

- src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php
| Related tickets | fixes #8613, related with #8798 
> [Installation] Add setting an email as username during installation

- phpstan.neon
- src/Sylius/Behat/Context/Ui/Shop/LocaleContext.php
- src/Sylius/Behat/Page/Admin/ShippingMethod/CreatePage.php
- src/Sylius/Behat/Page/Admin/TaxRate/CreatePage.php
- src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php
- src/Sylius/Bundle/CoreBundle/Form/Type/Product/ProductReviewType.php
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/CurrencyFixtureTest.php
- src/Sylius/Bundle/ProductBundle/Controller/ProductAttributeController.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductAssociationTypeChoiceType.php
- src/Sylius/Bundle/PromotionBundle/Form/Type/AbstractConfigurablePromotionElementType.php
- src/Sylius/Component/Attribute/AttributeType/TextareaAttributeType.php
- src/Sylius/Component/Core/Model/Image.php
- src/Sylius/Component/Core/Model/ProductImage.php
- src/Sylius/Component/Core/Model/Taxon.php
> PHPStan: initial config & first fixes

- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
> Change master branch version to 1.1.0-DEV

- docs/requirements.txt
| Related tickets | https://github.com/sphinx-doc/sphinx/issues/4139
> [BUGFIX][Documentation] Restrict Sphinx version contraints

- docs/book/products/attributes.rst
| Doc fix?        | no/yes
| Related tickets | based on #8810, fixes #8799
Credits go to @garbetjie, who is our **first time contributor** 💪 ! I just made a rebase ;)
> [Documentation][Book] Product attributes fix

- docs/cookbook/custom-promotion-rule.rst
| Related tickets | based on #8763 
Credits go to @flochntrl, who is our first time contributor 💪 ! I just made a rebase ;)
> [Documentation] Custom Promotion Rule Checker Fix

- app/config/parameters.yml.dist
> Allow to use environmental variables to populate parameters

- docs/customization/controller.rst
| Related tickets | fixes #8834
Fixes #8834.
> Added missing return type in customization/controller docs

- docs/PULL_REQUEST_TEMPLATE.md
> Update comment in the PR template

- docs/customization/factory.rst
- docs/customization/form.rst
- docs/customization/menu.rst
- docs/customization/model.rst
- docs/customization/repository.rst
>  [Documentation] Add typehints to customization guide

- phpstan.neon
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Setup/ProductTaxonContext.php
- src/Sylius/Behat/Context/Setup/TaxonomyContext.php
- src/Sylius/Behat/Context/Setup/UserContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentMethodsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
- src/Sylius/Behat/Page/Admin/Country/CreatePage.php
- src/Sylius/Behat/Page/Admin/Country/UpdatePage.php
- src/Sylius/Behat/Page/Admin/ProductOption/CreatePage.php
- src/Sylius/Behat/Page/Admin/ProductOption/UpdatePage.php
> Random codebase enhancements

- docs/book/installation/vagrant_installation.rst
- docs/contributing/index.rst
> [Documentation] Explain how to contribute using vagrant

- etc/travis/suites/docs/script.sh
| Related tickets | as mentioned in #8851
> Do not check links while building documentation

- src/Sylius/Bundle/CustomerBundle/Resources/config/serializer/Model.Customer.yml
| Related tickets | replaces #8767
It replaces a PR created by @igormukhingmailcom using his squashed commits
> [Customer] Fix typo in serializer file

- .travis.yml
- etc/travis/suites/application/is_suitable.sh
- etc/travis/suites/docs/is_suitable.sh
- etc/travis/suites/packages/is_suitable.sh
| Related tickets | fixes #8771 
> [Travis] Allow failures for PHP 7.2 builds

- docs/cookbook/disabling-order-confirmation-email.rst
| Related tickets | (adds to) fixes #8630
> remove send on different moment and add section links

- features/product/viewing_products/viewing_product_attributes_in_different_locales_and_channels.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Tabs/_attributes.html.twig
- src/Sylius/Component/Attribute/Model/AttributeSubjectInterface.php
- src/Sylius/Component/Product/Model/Product.php
- src/Sylius/Component/Product/spec/Model/ProductSpec.php
| Related tickets | partially fixes #8220
> [ProductAttribute] Fix displaying attributes depending on locales and channels

- docs/book/architecture/resource_layer.rst
> Change Symfony2 to Symfony

- docs/book/configuration/channels.rst
> [Docs] Mention hostname configuration for multiple channels

- src/Sylius/Behat/Page/Admin/ProductAttribute/CreatePage.php
- src/Sylius/Behat/Page/Admin/ProductAttribute/UpdatePage.php
- src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/Configuration/SelectAttributeValueTranslationsType.php
- tests/Controller/ProductAttributeApiTest.php
> Apply coding standard fixes

- docs/book/orders/payments.rst
| Related tickets | fixes #8849
It replaces the PR #8877 created by @PapsOu
> [Documentation] Fix channel assignment example on a payment method

- src/Sylius/Component/Attribute/Model/Attribute.php
- src/Sylius/Component/Attribute/Model/AttributeInterface.php
- src/Sylius/Component/Core/Model/CustomerInterface.php
- src/Sylius/Component/Core/Model/Product.php
- src/Sylius/Component/Core/Model/ProductInterface.php
- src/Sylius/Component/Payment/Model/PaymentMethod.php
- src/Sylius/Component/Payment/Model/PaymentMethodInterface.php
- src/Sylius/Component/Product/Model/Product.php
- src/Sylius/Component/Product/Model/ProductAssociationType.php
- src/Sylius/Component/Product/Model/ProductAssociationTypeInterface.php
- src/Sylius/Component/Product/Model/ProductInterface.php
- src/Sylius/Component/Product/Model/ProductOption.php
- src/Sylius/Component/Product/Model/ProductOptionInterface.php
- src/Sylius/Component/Product/Model/ProductOptionValue.php
- src/Sylius/Component/Product/Model/ProductOptionValueInterface.php
- src/Sylius/Component/Product/Model/ProductVariant.php
- src/Sylius/Component/Product/Model/ProductVariantInterface.php
- src/Sylius/Component/Shipping/Model/ShippingMethod.php
- src/Sylius/Component/Shipping/Model/ShippingMethodInterface.php
- src/Sylius/Component/Taxonomy/Model/Taxon.php
- src/Sylius/Component/Taxonomy/Model/TaxonInterface.php
| Related tickets | partly #8224
Thanks @ondrejmirtes for initiating this work :)
> Narrow typehints for models - part 1

- docs/customization/form.rst
It replaces the PR #8884 created by @Snake-Tn
> [Documentation] Fix form extension link

- CHANGELOG-1.0.md
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
- src/Sylius/Component/Product/Model/ProductAssociationTypeInterface.php
- src/Sylius/Component/Product/Model/ProductOptionInterface.php
> Prepare 1.0.2 release

- UPGRADE-1.0.md
| Related tickets | related to #8869
> Update UPGRADE file mentioning risky changes made between v1.0.1 and v1.0.2 releases

- features/contact/requesting_contact_validation.feature
- src/Sylius/Behat/Context/Ui/Shop/ContactContext.php
> [Behat] fix typo in contact context

- src/Sylius/Bundle/GridBundle/DependencyInjection/SyliusGridExtension.php
- src/Sylius/Bundle/GridBundle/Renderer/TwigBulkActionGridRenderer.php
- src/Sylius/Bundle/GridBundle/Renderer/TwigGridRenderer.php
- src/Sylius/Bundle/GridBundle/Resources/config/services/templating.xml
- src/Sylius/Bundle/GridBundle/Resources/config/services/twig.xml
- src/Sylius/Bundle/GridBundle/Templating/Helper/BulkActionGridHelper.php
- src/Sylius/Bundle/GridBundle/Templating/Helper/GridHelper.php
- src/Sylius/Bundle/GridBundle/Twig/BulkActionGridExtension.php
- src/Sylius/Bundle/GridBundle/Twig/GridExtension.php
- src/Sylius/Bundle/GridBundle/spec/Renderer/TwigBulkActionGridRendererSpec.php
- src/Sylius/Bundle/GridBundle/spec/Renderer/TwigGridRendererSpec.php
- src/Sylius/Bundle/GridBundle/spec/Templating/Helper/BulkActionGridHelperSpec.php
- src/Sylius/Bundle/GridBundle/spec/Templating/Helper/GridHelperSpec.php
- src/Sylius/Bundle/ResourceBundle/Grid/Renderer/TwigBulkActionGridRenderer.php
- src/Sylius/Bundle/ResourceBundle/Grid/Renderer/TwigGridRenderer.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services/integrations/grid.xml
- src/Sylius/Bundle/ResourceBundle/spec/Grid/Renderer/TwigBulkActionGridRendererSpec.php
- src/Sylius/Component/Grid/Renderer/BulkActionGridRendererInterface.php
- src/Sylius/Component/Grid/Renderer/GridRendererInterface.php
| Related tickets | closes #8939, fixes #8491
> Change bulk action implementation and remove the need for a BC break

- docs/contributing/code/patches.rst
- docs/contributing/documentation/overview.rst
| Related tickets | fixes #8693 
> [Documentation] Branching strategy

- docs/components_and_bundles/bundles/SyliusThemeBundle/your_first_theme.rst
| Related tickets | fixes #8641
> [Documentation] Theme assets installing tip

- src/Sylius/Bundle/UiBundle/Resources/views/Macro/pagination.html.twig
| Related tickets | fixes #8412 
> [Bug] [Admin] fixed filter reset after changing grid page limits - third branch

- CHANGELOG-1.0.md
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
> Prepare 1.0.3 release

- CHANGELOG-1.0.md
- composer.json
- composer.lock
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
- src/Sylius/Bundle/ResourceBundle/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php
| Related tickets | fixes #8966
> Security release 1.0.4 - allowing to update to Symfony 3.3.13

- docs/contributing/index.rst
- docs/contributing/map.rst.inc
- docs/contributing/organization/core-team.rst
- docs/contributing/organization/index.rst
- docs/contributing/organization/map.rst.inc
- docs/contributing/organization/release-process.rst
- docs/contributing/organization/vision-and-strategy.rst
| Related tickets | replaces and closes #8107
> Community organization

- docs/support/index.rst
> [Documentation] Remove facebook group

- src/Sylius/Behat/Context/Setup/CurrencyContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPageInterface.php
- src/Sylius/Behat/Page/Shop/Account/DashboardPage.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
- src/Sylius/Bundle/AttributeBundle/Doctrine/ORM/Subscriber/LoadMetadataSubscriber.php
- src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php
- src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php
- src/Sylius/Bundle/PayumBundle/Action/Offline/StatusAction.php
- src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
- src/Sylius/Bundle/ResourceBundle/Controller/ViewHandlerInterface.php
- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/Model/OrderInterface.php
- src/Sylius/Component/Core/Model/ProductTaxonInterface.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/ContainsProductRuleChecker.php
- src/Sylius/Component/Core/Promotion/Checker/Rule/HasTaxonRuleChecker.php
- src/Sylius/Component/Order/Model/OrderInterface.php
- src/Sylius/Component/Payment/Model/PaymentInterface.php
Some random PHPDoc issues found by [PHPStan](https://github.com/phpstan/phpstan)
> PHPDoc fixes

- docs/components_and_bundles/bundles/SyliusGridBundle/custom_filter.rst
Just a quick fix on filters documentation.
> Syntax error fix in doc code snippet

- .github/stale.yml
- docs/contributing/organization/vision-and-strategy.rst
This one will help to focus on the most important issues and pull requests.
> Setup "Stale" probot

- docs/book/products/search.rst
- docs/components_and_bundles/bundles/SyliusResourceBundle/index.rst
| Related tickets | closes #8960 
All work made by @serieznyi in #8960, this PR is just a rebase to 1.0 branch.
> Use SyliusElasticSearchPlugin repository in docs

- CHANGELOG-1.0.md
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
> Prepare 1.0.5 release

- docs/book/architecture/resource_layer.rst
Removed gender from comment for inclusion.
| Branch?         | 1.0 or master 
> Removing gender from documentation

- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Setup/TaxonomyContext.php
- src/Sylius/Behat/Page/Page.php
- src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/RegisterTaxCalculationStrategiesPass.php
- src/Sylius/Bundle/PaymentBundle/DependencyInjection/Compiler/RegisterPaymentMethodsResolversPass.php
- src/Sylius/Bundle/ShippingBundle/DependencyInjection/Compiler/RegisterShippingMethodsResolversPass.php
- src/Sylius/Component/Grid/Filter/MoneyFilter.php
> Use Null Coalesce Operator

- .travis.yml
Right now our builds are failing, so it is a workaround rather than a bug fix, but it is best what I can do right now. We should investigate it deeper. /cc @pamil 
__Edit:__
Referenced builds:
https://travis-ci.org/Sylius/Sylius/jobs/315762118
https://travis-ci.org/Sylius/Sylius/jobs/315784553
https://travis-ci.org/Sylius/Sylius/jobs/315784093
> [Travis] Use old Trusty image

- docs/plugins/creating-plugin.rst
> [Documentation] Update plugin name

- docs/plugins/creating-plugin.rst
> [Documenation] Update plugin mapping recommendation

- src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
> [Grid] Fixes broken table when all item actions are disabled

- composer.json
- composer.lock
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
Getting ready for feature freeze for 1.1 (branch 1.1 created as well) by making master branch point to future 1.2 version.
> Change master branch version to 1.2.0-DEV

- composer.json
- composer.lock
> Require Symfony ^3.4

- etc/travis/suites/application/script.sh
- etc/travis/suites/application/script/test-installer
- src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
Fixes #9073, fixes #9028, fixes #8757, closes #8797.
> Test sylius:install command on Travis

- app/migrations/Version20180102140039.php
| Related tickets | mentioned in #9081
Here you go @lchrusciel :-)
> Remove strict declaration on migration

- docs/book/products/product_reviews.rst
> Fix referenced state machine configuration path

- UPGRADE-1.1.md
- docs/api/index.rst
- docs/api/map.rst.inc
> Minor enhancements to product review API pull request

- docs/contributing/code/bdd.rst
| Branch?         | 1.0, 
Related installation file https://github.com/Sylius/Sylius/blob/master/etc/travis/suites/application/script/test-behat-with-javascript#L23
> [Documentation] Update required selenium version

- src/Sylius/Bundle/ShopBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/show.html.twig
| Related tickets | fixes #9099
> Make lightbox label translatable (fixes #9099)

- src/Sylius/Component/Taxonomy/Model/Taxon.php
All the work done by @diimpp in #9123, this is just a rebase! :tada:
> Fix return typehint for TaxonTranslation

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/exchange_rate.yml
> [Admin] Fix wrong source currency translation

- docs/cookbook/payments/stripe.rst
All the work done by @reyostallenberg in #9113, this is just a rebase :tada:
> [Documentation] Add warning about trusted proxies when using stripe behind lb with https

- docs/contributing/code/patches.rst
All the work done @willy-ahva in #4797, it's just a rebase! :)
> [Documentation] Fix typo

- src/Sylius/Bundle/AddressingBundle/README.md
- src/Sylius/Bundle/AttributeBundle/README.md
- src/Sylius/Bundle/FixturesBundle/README.md
- src/Sylius/Bundle/GridBundle/README.md
- src/Sylius/Bundle/InventoryBundle/README.md
- src/Sylius/Bundle/MailerBundle/README.md
- src/Sylius/Bundle/OrderBundle/README.md
- src/Sylius/Bundle/ProductBundle/README.md
- src/Sylius/Bundle/PromotionBundle/README.md
- src/Sylius/Bundle/ResourceBundle/README.md
- src/Sylius/Bundle/ShippingBundle/README.md
- src/Sylius/Bundle/TaxationBundle/README.md
- src/Sylius/Bundle/TaxonomyBundle/README.md
- src/Sylius/Bundle/ThemeBundle/README.md
> [Documentation] Fix URL to docs in Bundles README

- src/Sylius/Bundle/AddressingBundle/composer.json
- src/Sylius/Bundle/AdminBundle/composer.json
- src/Sylius/Bundle/CoreBundle/composer.json
- src/Sylius/Bundle/CurrencyBundle/composer.json
- src/Sylius/Bundle/GridBundle/composer.json
- src/Sylius/Bundle/InventoryBundle/composer.json
- src/Sylius/Bundle/LocaleBundle/composer.json
- src/Sylius/Bundle/MoneyBundle/composer.json
- src/Sylius/Bundle/OrderBundle/composer.json
- src/Sylius/Bundle/ThemeBundle/composer.json
- src/Sylius/Bundle/UiBundle/composer.json
> Make packages providing Twig extensions conflict with Twig 1.x

- UPGRADE-1.0.md
- src/Sylius/Bundle/CoreBundle/Templating/Helper/VariantResolverHelper.php
- src/Sylius/Bundle/CoreBundle/spec/Templating/Helper/VariantResolverHelperSpec.php
Rebased #9119 done by @bitbager with added UPGRADE.md entry.
> Allow nullable product variants

- UPGRADE-1.0.md
> Fix typo in UPGRADE file

- docs/components_and_bundles/bundles/SyliusTaxonomyBundle/index.rst
- docs/components_and_bundles/bundles/SyliusTaxonomyBundle/summary.rst
> Semantic fixes in SyliusTaxonomyBundle docs

- composer.json
- composer.lock
> Update KnpGaufretteBundle to ^0.5

- src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/product_review.yml
- tests/Controller/ProductReviewApiTest.php
| Related tickets | related with https://github.com/Sylius/Sylius/pull/8772
> Product reviews API semantic fix

- docs/cookbook/index.rst
- docs/cookbook/shop/cms.rst
> [Documentation] Add CMS integration cookbook

- docs/contributing/code/patches.rst
- docs/contributing/documentation/overview.rst
> [Documentation] Add 1.1 branch to Contribution guides

- src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/SelectAttributeType.php
| Related tickets | fixes #9159
Not sure if/how to test this in a model CallbackTransformer.
> Fix invalid use of count by checking for an array

- docs/cookbook/entities/custom-translatable-model.rst
> [Documentation] Translatable model - Fix titles and add template support

- .travis.yml
- composer.lock
- etc/travis/suites/application/before_script.sh
> Run Travis with readonly project directories

- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
> Remove surprising redundant x sign from docblock

- docs/cookbook/images/images-on-entity.rst
Adding description on how to validate the images that can be uploaded when finishing this guide.
| Related tickets | fixes none
> [Documentation][Cookbook]Adding validation for image uploads

- src/Sylius/Bundle/AdminBundle/Resources/views/Locale/Grid/Field/name.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/flags.html.twig
| Related tickets | fixes #9184 
This PR improve flags support, it's not perfect en doesn't work for every country but at least that support more countries than previously.
> Improve flags support

- app/migrations/Version20180226142349.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
- src/Sylius/Bundle/ReviewBundle/Resources/config/doctrine/model/Review.orm.xml
- src/Sylius/Bundle/ReviewBundle/Resources/config/validation/Review.xml
| Related tickets | fixes #8172 
> [Reviews] nullable title for reviews

- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-address-book.js
- src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-province-field.js
| Q                     | A
| ------------------- | -----
| Branch?           | 1.0
| Bug fix?           | yes
| New feature?   | no
| Related tickets | fixes #8330
| License            | MIT
Before changes
https://drive.google.com/open?id=1ddyaMFtmW0M3oXX1JrfV8HuTvlk1jFY4
After changes
https://drive.google.com/open?id=1quA3mWzYAUoikCnTQLvgW0PBrLuHWaJH
Maybe not a best solution, but it`s work
Also it is work for billing address
> Fix select province in checkout address

- UPGRADE-1.1.md
> Mention the need of applying migrations when upgrading 1.0 -> 1.1

- src/Sylius/Bundle/GridBundle/composer.json
- src/Sylius/Bundle/ResourceBundle/composer.json
- src/Sylius/Component/Resource/composer.json
> Various composer.json enhancements

- src/Sylius/Bundle/ChannelBundle/Form/Type/ChannelType.php
| Related tickets | fixes #9146
> Changes form channel color from text to color input type

- composer.json
- etc/travis/suites/application/script.sh
- etc/travis/suites/application/script/test-phpstan
- phpstan.neon
- src/Sylius/Bundle/CoreBundle/Command/AbstractInstallCommand.php
> Run PHPStan in Travis CI

- docs/cookbook/configuration/extending-bundles-other-em.rst
- docs/cookbook/configuration/map.rst.inc
- docs/cookbook/extending-bundles-other-em.rst
- docs/cookbook/index.rst
Rebased and slightly improved https://github.com/Sylius/Sylius/pull/8517, thank you @Adraesh for your tremendous work!
> [Documentation][CookBook] Specific SyliusBundles extension

- app/config/config_test.yml
- composer.json
- phpunit.xml.dist
- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
- tests/Controller/OrderApiTest.php
- tests/Controller/PaymentMethodApiTest.php
- tests/Controller/ProductVariantApiTest.php
- tests/Controller/PromotionApiTest.php
- tests/Controller/PromotionCouponApiTest.php
- tests/Controller/ShippingMethodApiTest.php
- tests/Controller/TaxRateApiTest.php
- tests/Controller/TaxonApiTest.php
- tests/DataFixtures/ORM/resources/cart.yml
- tests/DataFixtures/ORM/resources/cart_with_items.yml
- tests/DataFixtures/ORM/resources/checkout.yml
- tests/DataFixtures/ORM/resources/customers.yml
- tests/DataFixtures/ORM/resources/shipping_categories.yml
- tests/DataFixtures/ORM/resources/tax_categories.yml
- tests/DataFixtures/ORM/resources/tax_categories_for_filtering.yml
- tests/DataFixtures/ORM/resources/tax_rates.yml
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/9240
> Update ApiTestCase to ^3.0

- src/Sylius/Component/Core/Model/ShopUser.php
| Bug fix?        | PHPDoc only
> Fix wrong CustomerInterface type in PHPDoc

- composer.json
Related issues to conflicts are linked in commits messages.
> Define conflicts with incompatible dependencies versions

- docs/cookbook/shop/taxons-menu.rst
| Related tickets | https://github.com/Sylius/Sylius/issues/9102
> Outdated method reference removed from docs

- docs/customization/form.rst
> Correct minor typo in docs

- docs/book/introduction/introduction.rst
| Branch?         | 1.0, 1.1 or master 
> Minor doc fix

- docs/book/products/product_reviews.rst
> [DOC] Minor documentation changes for product reviews

- src/Sylius/Bundle/ShopBundle/Resources/views/Email/contactRequest.html.twig
> formatting content in a email message

- src/Sylius/Component/Channel/Context/ChannelNotFoundException.php
| Deprecations?   | yes 
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/9294
> ChannelNotFoundException updated to other exceptions' format without BC break

- src/Sylius/Bundle/UiBundle/Resources/translations/flashes.en.yml
> Order update error flash message typo

- src/Sylius/Component/Addressing/README.md
- src/Sylius/Component/Attribute/README.md
- src/Sylius/Component/Channel/README.md
- src/Sylius/Component/Currency/README.md
- src/Sylius/Component/Grid/README.md
- src/Sylius/Component/Inventory/README.md
- src/Sylius/Component/Locale/README.md
- src/Sylius/Component/Mailer/README.md
- src/Sylius/Component/Order/README.md
- src/Sylius/Component/Payment/README.md
- src/Sylius/Component/Product/README.md
- src/Sylius/Component/Promotion/README.md
- src/Sylius/Component/Registry/README.md
- src/Sylius/Component/Resource/README.md
- src/Sylius/Component/Shipping/README.md
- src/Sylius/Component/Taxation/README.md
- src/Sylius/Component/Taxonomy/README.md
- src/Sylius/Component/User/README.md
> [Components] Fix links for documentation in readme

- src/Sylius/Bundle/AddressingBundle/composer.json
- src/Sylius/Bundle/AdminApiBundle/composer.json
- src/Sylius/Bundle/AttributeBundle/composer.json
- src/Sylius/Bundle/ChannelBundle/composer.json
- src/Sylius/Bundle/CoreBundle/composer.json
- src/Sylius/Bundle/CurrencyBundle/composer.json
- src/Sylius/Bundle/CustomerBundle/composer.json
- src/Sylius/Bundle/FixturesBundle/composer.json
- src/Sylius/Bundle/InventoryBundle/composer.json
- src/Sylius/Bundle/LocaleBundle/composer.json
- src/Sylius/Bundle/MailerBundle/composer.json
- src/Sylius/Bundle/MoneyBundle/composer.json
- src/Sylius/Bundle/OrderBundle/composer.json
- src/Sylius/Bundle/PaymentBundle/composer.json
- src/Sylius/Bundle/PayumBundle/composer.json
- src/Sylius/Bundle/ProductBundle/composer.json
- src/Sylius/Bundle/PromotionBundle/composer.json
- src/Sylius/Bundle/ReviewBundle/composer.json
- src/Sylius/Bundle/ShippingBundle/composer.json
- src/Sylius/Bundle/TaxationBundle/composer.json
- src/Sylius/Bundle/TaxonomyBundle/composer.json
- src/Sylius/Bundle/ThemeBundle/composer.json
- src/Sylius/Bundle/UserBundle/composer.json
> Replace outdated "Symfony2" with "Symfony" in package descriptions

- src/Sylius/Bundle/AdminApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/commands.xml
- src/Sylius/Bundle/FixturesBundle/Resources/config/services.xml
- src/Sylius/Bundle/OrderBundle/Resources/config/services.xml
- src/Sylius/Bundle/ThemeBundle/Resources/config/services.xml
- src/Sylius/Bundle/UserBundle/Resources/config/services.xml
> Define commands as services

- composer.json
- src/Sylius/Behat/Service/Setter/CookieSetter.php
| Related tickets | #9062 
Required for Symfony 4 support later.
> Make application compatible with not-yet-released Mink release

- docs/customization/repository.rst
>  Fix product repository's service id in docs

- src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/ProductBundle/Resources/config/services.xml
- src/Sylius/Bundle/ReviewBundle/DependencyInjection/SyliusReviewExtension.php
- src/Sylius/Bundle/UserBundle/Resources/config/services.xml
Prevents errors during container compilation such as https://github.com/doctrine/DoctrineBundle/issues/822
> Lazy load Doctrine event listeners

- .travis.yml
> Require passing build for Symfony 4 on Travis

- app/config/parameters.yml.dist
> Fix secret parameter resolving

- docs/components_and_bundles/bundles/SyliusResourceBundle/create_resource.rst
- src/Sylius/Bundle/ResourceBundle/Controller/NewResourceFactory.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/NewResourceFactorySpec.php
- src/Sylius/Bundle/ResourceBundle/test/app/config/config.yml
- src/Sylius/Bundle/ResourceBundle/test/app/config/routing.yml
- src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Factory/CustomBookFactory.php
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/Controller/BookApiTest.php
> Add ability to use a custom service as factory

- docs/contributing/code/patches.rst
> [Documentation] Fixed typo in note about --force-with-lease flag

- composer.json
- src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php
- src/Sylius/Bundle/ResourceBundle/Controller/ResourcesResolver.php
- src/Sylius/Bundle/ResourceBundle/Controller/SingleResourceProvider.php
- src/Sylius/Bundle/ResourceBundle/composer.json
- src/Sylius/Bundle/ResourceBundle/spec/Controller/ResourcesResolverSpec.php
- src/Sylius/Bundle/ResourceBundle/spec/Controller/SingleResourceProviderSpec.php
- src/Sylius/Bundle/ResourceBundle/test/app/config/config.yml
- src/Sylius/Bundle/ResourceBundle/test/app/config/routing.yml
- src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Repository/CustomBookRepository.php
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/Controller/BookApiTest.php
| Related tickets | related to #9422
> Add an ability to use custom resource repositories

- docs/components_and_bundles/bundles/SyliusResourceBundle/show_resource.rst
> Add documentation for using custom repository service in ResourceBundle

- src/Sylius/Bundle/CoreBundle/Resources/config/services.xml
> Remove two redundant services from CoreBundle

- src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
Renamed resolveNextRouteRequestFacotry to resolveNextRouteRequestFactory
| Related tickets | mentioned in https://github.com/Sylius/SyliusPayumBundle/pull/2
> Fixed typo in PayumController

- docs/book/orders/payments.rst
> [Documentation] Updated link to Payum docs

- UPGRADE-1.2.md
| Branch?         | 1.2 
| Related tickets | partially #9431
> Added note about LiipImagineBundle upgrade

- docs/contributing/organization/vision-and-strategy.rst
We've got labels descriptions on GitHub now 🎉
> Remove labels descriptions in docs

- docs/cookbook/entities/custom-model.rst
Fix a small inconsistence in the documentation
> [docs] Use `app/config/routing/admin.yml` everywhere

- UPGRADE-1.2.md
> Describe upgrade process for 1.1.x -> 1.2.0

- docs/support/index.rst
> [Documentation] Document Forum in the support section

- .github/ISSUE_TEMPLATE/bug-report---.md
- .github/ISSUE_TEMPLATE/documentation-issue---.md
- .github/ISSUE_TEMPLATE/feature-request--.md
- .github/ISSUE_TEMPLATE/support-question---.md
Hi there! 👋 
Highly inspired by Symfony, Sylius project is also introducing Issue templates to easen the process of submitting issues on our repository.
Read more: https://help.github.com/articles/about-issue-and-pull-request-templates/
> Update Sylius issue templates

- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_content.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_content.html.twig
> [Admin] Add missing form parameter to sonata form events

- docs/book/customers/addresses/address_book.rst
- docs/book/customers/customer_and_shopuser.rst
- docs/book/orders/adjustments.rst
- docs/book/orders/coupons.rst
- docs/book/orders/payments.rst
- docs/book/orders/promotions.rst
- docs/book/orders/shipments.rst
- docs/book/products/inventory.rst
- docs/book/products/pricing.rst
- docs/book/products/search.rst
- docs/book/products/taxons.rst
Some of these fixes are more about phrasing than typos; let me know if you want them to be removed from this PR.
> [Documentation] Fix typos

- src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/_single.html.twig
| Related tickets | fixes #9425 
> Added title to product reviews, fixes #9425

- src/Sylius/Component/Core/Resolver/EligibleDefaultShippingMethodResolver.php
- src/Sylius/Component/Core/spec/Resolver/EligibleDefaultShippingMethodResolverSpec.php
> Remove duplicated copyright note

- src/Sylius/Bundle/ResourceBundle/Routing/ResourceLoader.php
- src/Sylius/Bundle/ResourceBundle/spec/Routing/ResourceLoaderSpec.php
| Related tickets | fixes #9532 
> [ResourceBundle] fix routing templates for sf4

- README.md
> Mention roadmap in README

- UPGRADE-2.0.md
- src/Sylius/Bundle/GridBundle/DependencyInjection/SyliusGridExtension.php
- src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/DataSource.php
- src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/Driver.php
- src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExpressionBuilder.php
- src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExpressionBuilderInterface.php
- src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExpressionVisitor.php
- src/Sylius/Bundle/GridBundle/Doctrine/PHPCRODM/ExtraComparison.php
- src/Sylius/Bundle/GridBundle/Resources/config/services/integrations/doctrine/phpcr-odm.xml
- src/Sylius/Bundle/ResourceBundle/AbstractResourceBundle.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineODMDriver.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrinePHPCRDriver.php
- src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php
- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/MongoDB/DocumentRepository.php
- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/MongoDB/TranslatableRepository.php
- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/DocumentRepository.php
- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/EventListener/DefaultParentListener.php
- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/EventListener/NameFilterListener.php
- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/EventListener/NameResolverListener.php
- src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/Form/Builder/DefaultFormBuilder.php
- src/Sylius/Bundle/ResourceBundle/EventListener/ODMMappedSuperClassSubscriber.php
- src/Sylius/Bundle/ResourceBundle/EventListener/ODMRepositoryClassSubscriber.php
- src/Sylius/Bundle/ResourceBundle/EventListener/ODMTranslatableListener.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services/integrations/doctrine/mongodb-odm.xml
| Related tickets | see #9500
RFC-ed in #9500.
> Deprecate MongoDB and PHPCR drivers in ResourceBundle and GridBundle

- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
As the group by is not sql standard and is used to distinct the query result
| Related tickets | PR :  #7927|
As group by is used to distinct the result of sql query, it remove the SQL "group by" and add the "distinct".
It should fit the sql standard.
Please see :
https://github.com/Sylius/Sylius/pull/7927
> Remove groupby and add distinct

- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/spec/Model/OrderSpec.php
| Deprecations?   |
| Related tickets | fixes #9577 
> [Core] Nullable customer on order

- src/Sylius/Bundle/UserBundle/EventListener/UserLastLoginSubscriber.php
- src/Sylius/Bundle/UserBundle/spec/EventListener/UserLastLoginSubscriberSpec.php
> [User] Fix bc-break in UserLastLoginSubscriber

- src/Sylius/Bundle/AdminApiBundle/Command/CreateClientCommand.php
- src/Sylius/Bundle/AdminApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/AdminApiBundle/spec/Command/CreateClientCommandSpec.php
> [AdminApi] Fix command

- docs/components_and_bundles/bundles/SyliusGridBundle/your_first_grid.rst
| Related tickets | fixes none
> [Documentation][GridBundle]Describes sorting, filtering by sub entity properties

- docs/components_and_bundles/components/general/creating_resources.rst
Just some minor grammar fixes I noticed while reading the docs.
I had some trouble grasping the meaning of the second sentence ("Some of them can use default factory .."), please let me know if i've accidentally changing the meaning of it.
> Minor fixes to grammar

- src/Sylius/Component/Core/Model/ShopUser.php
- src/Sylius/Component/Core/spec/Model/ShopUserSpec.php
> Check if customer is set before get/set email

- docs/PULL_REQUEST_TEMPLATE.md
> Pull request template fix

- features/checkout/order_promotion/order_promotion_integrity_validation.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php
- src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/ShopBundle/spec/EventListener/OrderPromotionIntegrityCheckerSpec.php
| Related tickets | fixes #9593, #9512 
> Take unitTotal of order item to check if taxon rule can be applied

- docs/components_and_bundles/bundles/SyliusTaxationBundle/custom_calculators.rst
| Related tickets | fixes #9604
> [Doc] Fix service name for custom taxation calculator

- docs/components_and_bundles/components/Taxonomy/models.rst
| Related tickets | fixes #9619 
> [docs] updating taxon models documentation

- src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php
- src/Sylius/Component/Core/spec/Cart/Context/ShopBasedCartContextSpec.php
> Fix CS and add tests for ShopBasedCartContext

- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
>  Fix missing "required" class on some form fields 

- src/Sylius/Component/Core/spec/Order/OrderItemNamesSetterSpec.php
> [Core] Fix OrderItemNamesSetter specification

- src/Sylius/Component/Currency/spec/Model/CurrencySpec.php
> [Currency] Improve currency specs

- app/config/config.yml
- features/product/viewing_products/viewing_products_from_taxon_children.feature
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
- src/Sylius/Bundle/ShopBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/ShopBundle/DependencyInjection/SyliusShopExtension.php
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
- src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/6604
> Taxon with children taxons behavior in listing

- docs/book/configuration/currencies.rst
Changed lets to allows to improve the quality of the English
| Branch?         | 1.1, 1.2 or master 
> Updated a word in documentation to read better

- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_support.html.twig
Ref: https://semantic-ui.com/elements/icon.html
Before:
After:
> [UI] Fix icons on checkout

- src/Sylius/Bundle/CoreBundle/Fixture/GeographicalFixture.php
- src/Sylius/Bundle/CoreBundle/spec/Fixture/GeographicalFixtureSpec.php
| Related tickets | fixes #9221
> [Core][Fixture] Fix for ignored geographical zone scope

- docs/cookbook/frontend/admin-js-and-css.rst
| Related tickets | fixes #9535
> Fixing Typo in Documentation

- features/inventory/cart_inventory/verify_inventory_quantity_when_updating_cart_summary.feature
> Fix typo in Behat feature

- README.md
> Remaining official plugins listed in README.md file

- UPGRADE-1.3.md
> Fixed Symfony docs links in UPGRADE-1.3.md

- docs/book/installation/installation.rst
| Related tickets | mentioned in #9746
Complementary to #9746, both should be merged.
> Update installation.rst for Flex

- docs/book/installation/installation.rst
- docs/contributing/index.rst
- docs/cookbook/emails/mailer.rst
- docs/cookbook/payments/encrypting-gateway-config.rst
There are also some references to parameters in other parts of the cookbook, but AFAIK @CoderMaggie is working on improving cookbook as well, moreover, I honestly don't know how some of them should look like (for example redis configuration).
> [Documentation] Change parameters to env variables

- src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
> Allow for null hostname in ChannelFixture

- docs/api/taxons.rst
> [Documentation] Fix API example for creating a taxon

- src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
Will surely save some frustration :)
> [Order] Fixed sylius:remove-expired-carts help

- src/Sylius/Bundle/CustomerBundle/Form/Type/GenderType.php
- tests/Responses/Expected/customer/create_validation_fail_response.json
- tests/Responses/Expected/customer/create_with_user_validation_fail_response.json
- tests/Responses/Expected/customer/update_validation_fail_response.json
| Related tickets | fixes #8493|
@psihius could you confirm is fixes the API issue as well?
> set gender `u` as default value - resolves #8493

- src/Sylius/Component/Grid/Provider/ArrayGridProvider.php
See https://github.com/Sylius/Sylius/pull/9698#pullrequestreview-160730178 for details.
Fixes #9698.
> Make ArrayGridProvider more performant & suitable for PHP-PM

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionActionExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionRuleExampleFactory.php
> [CoreBundle] Make sure promotion action/rule amount is an integer

- src/Sylius/Bundle/ShopBundle/composer.json
- src/Sylius/Bundle/ThemeBundle/composer.json
> [ThemeBundle] Replace "symfony/symfony" dependency with specific Symfony packages

- src/Sylius/Component/Grid/Definition/Grid.php
- src/Sylius/Component/Grid/spec/Definition/GridSpec.php
> [Grid] Fix getting enabled grid items

- src/Sylius/Bundle/ShippingBundle/Resources/config/validation/ShippingMethod.xml
- src/Sylius/Bundle/ShippingBundle/Resources/translations/validators.en.yml
Fixes #8985. No Behat scenario since it's "as a hacker" one :)
> [ShippingBundle] Add validation for ShippingMethod calculator

- docs/components_and_bundles/bundles/SyliusTaxationBundle/configuring_taxation.rst
> Update "Configuring taxation" docs

- features/checkout/order_promotion/order_promotion_integrity_validation.feature
| Related tickets | covers #7836
With collaboration with @CoderMaggie and @gabiudrescu
> [Behat] Describe percentage promotion issue

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_sorting.html.twig
> Keep the existing pagination when changing sorting on product list page

- features/account/resetting_password_validation.feature
- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
- src/Sylius/Behat/Page/Shop/Account/ResetPasswordPage.php
- src/Sylius/Behat/Page/Shop/Account/ResetPasswordPageInterface.php
| BC breaks?      | maybe cause I've added a method on a behat page interface
> [Behat] Add scenarios on resetting password validation feature

- src/Sylius/Bundle/ShopBundle/Resources/views/Account/requestPasswordReset.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/resetPassword.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Contact/request.html.twig
Fix a small issue on the password request and contact pages, with a mobile view.
> [Shop] Fix password request & contact pages with a mobile view.

- config/bundles.php
> remove web server bundle on prod environment

- docs/cookbook/configuration/disabling-admin-notifications.rst
- docs/cookbook/configuration/map.rst.inc
- docs/cookbook/index.rst
| Related tickets | fixes #9554 
> [Docs] How to disable admin notifications

- docs/customization/template.rst
> [Documentation] Make bundle templates extension part correct

- CHANGELOG-1.4.md
- src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php
- src/Sylius/Bundle/ResourceBundle/Resources/config/services/integrations/translation.xml
| Related tickets | fixes #9677
> [ResourceBundle] Deprecate passing container to ORMTranslatableListener

- docs/components_and_bundles/components/Shipping/basic_usage.rst
- docs/components_and_bundles/components/Shipping/models.rst
| Branch?         | 1.*
| Related tickets | fixes #9855
> docs: removing references to Rule class

- docs/cookbook/deployment/platform-sh.rst
| Related tickets | fixes #9861 
> [Fix] Indentation error .platform.app.yml in docs

- docs/bdd/how-to-use-transformers.rst
I'm not a native speaker but changes seem more correct.
> Fix typos in BDD Transformers docs

- src/Sylius/Bundle/ThemeBundle/Command/AssetsInstallCommand.php
| Related tickets | Fixes https://github.com/Sylius/Sylius/issues/9849
That should fix that reverted commit - https://github.com/Sylius/SyliusThemeBundle/commit/108455f9f1479a068540cb62c5bfd503f366a726
> Make use of sylius_core.public_dir in ThemeBundle

- docs/customization/form.rst
> Use correct path for view overriding

- src/Sylius/Bundle/CoreBundle/spec/Context/CustomerContextSpec.php
I've seen this missing scenario while running it with a phpspec code-coverage extension :)
> [Phpspec] add a missing scenario on customer context spec

- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/PaymentMethod.orm.xml
- src/Sylius/Bundle/PayumBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/PayumBundle/Model/GatewayConfigInterface.php
- src/Sylius/Bundle/PayumBundle/Model/PaymentSecurityToken.php
- src/Sylius/Bundle/PayumBundle/Model/PaymentSecurityTokenInterface.php
> [Payum] Add missing model interfaces

- src/Sylius/Bundle/ThemeBundle/Command/AssetsInstallCommand.php
| Related tickets | Fixes https://github.com/Sylius/Sylius/issues/9939, https://github.com/Sylius/Sylius/issues/9849
> Fix sylius:theme:assets:install command

- docs/book/orders/promotions.rst
| Doc fix?        | Maybe? 😄 
| Related tickets | fixes #9907 
> [Docs][Book] Promotion priorities

- src/Sylius/Bundle/CoreBundle/Fixture/AbstractResourceFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
| Related tickets | fixes #9942
> Fix for #9942

- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_totals.html.twig
This avoid table overflow in some languages like : for exemple in French.
| Related tickets | unknow
> Remove inline css

- .gitignore
| Related tickets | fixes #9959 
PR for 1.3 as this bug specific for 1.3.
> Fixed: 9959 (added public/media/image/.gitkeep to repo)

- docs/components_and_bundles/bundles/SyliusTaxationBundle/configuring_taxation.rst
| Related tickets | fixes #9913
> Add missing code and calculator mandatory field on tax rate documenation

- docs/cookbook/emails/disabling-order-confirmation-email.rst
> Fix typo cookbook about emails

- features/cli/showing_available_plugins.feature
- src/Sylius/Behat/Context/Cli/ShowingAvailablePluginsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/cli.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/cli/showing_available_plugins.yml
- src/Sylius/Bundle/CoreBundle/Command/Model/PluginInfo.php
- src/Sylius/Bundle/CoreBundle/Command/ShowAvailablePluginsCommand.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/commands.xml
- src/Sylius/Bundle/CoreBundle/spec/Command/Model/PluginInfoSpec.php
> [Console] Add command for showing available Sylius plugins

- src/Sylius/Bundle/CoreBundle/Application/Kernel.php
I guess we shouldn't let the server run in a production environment.
> [Kernel] Move WebServerBundle to dev/test environment

- docs/book/customers/customer_and_shopuser.rst
The Customer entity does not have have the mentioned properties.
> Remove billingAddress and shippingAddress

- docs/customization/model.rst
Fixed config directory path and added info for orm mappings.
> [docs] fix config directory path and added info for orm mappings in customization/model

- docs/contributing/code/bdd.rst
> Fixed incorrect Behat MinkExtension key in the docs

- src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
> Fix type annotation for $addToCartCommand

- src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
| Related tickets | related to #10020
> Fix the build on 1.3 by more flexible router overriding

- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
> [Fixtures] StreetAddress instead of StreetName

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/AddressExampleFactory.php
> Removed unused use statement

- docs/bdd/basic-usage.rst
- docs/bdd/how-to-add-new-page.rst
> [Docs] Fix docs with page object extension usage

- composer.json
- features/user/managing_customers/customer_validation.feature
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/AdminUser.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/Channel.xml
- src/Sylius/Bundle/CoreBundle/composer.json
- src/Sylius/Bundle/CustomerBundle/Resources/config/validation/Customer.xml
- src/Sylius/Bundle/CustomerBundle/composer.json
- src/Sylius/Bundle/UserBundle/Resources/config/validation/PasswordResetRequest.xml
- src/Sylius/Bundle/UserBundle/composer.json
| Related tickets | fixes #9116
> Enable strict validation for email

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_sorting.html.twig
> Fixed sorting path while sorting by position

- docs/book/installation/installation.rst
> GUS existence mentioned in Sylius installation guide

- src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php
It was alone, not needed by anybody 😢
> Remove unused Behat method

- .travis.yml
- src/Kernel.php
| Branch?         | master (will be ported to lower versions later)
| Related tickets | solves #10015
> Add support for Symfony 4.2

- features/account/customer_account/address_book/adding_address.feature
- features/account/customer_account/address_book/setting_default_address.feature
- src/Sylius/Bundle/CoreBundle/EventListener/CustomerDefaultAddressListener.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml
- src/Sylius/Bundle/CoreBundle/spec/EventListener/CustomerDefaultAddressListenerSpec.php
… automatically
| Related tickets | fixes #9524 
> [CoreBundle] First address in the address book should be made default

- .travis.yml
- app/TestAppKernel.php
| Related tickets | changes incorporated from https://github.com/Sylius/Sylius/pull/10067
> Remove container cleanup in test environment (1.2)

- src/Sylius/Bundle/GridBundle/test/app/config/config.yml
> Fix GridBundle build

- config/packages/_sylius.yaml
- config/packages/security.yaml
- config/packages/test/security.yaml
- src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
- src/Sylius/Bundle/UserBundle/EventListener/UpdateUserEncoderListener.php
- src/Sylius/Bundle/UserBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/UserBundle/Tests/DependencyInjection/SyliusUserExtensionTest.php
- src/Sylius/Bundle/UserBundle/spec/EventListener/UpdateUserEncoderListenerSpec.php
- src/Sylius/Bundle/UserBundle/spec/Fixture/FixtureUser.php
- src/Sylius/Bundle/UserBundle/spec/Fixture/FixtureUserInterface.php
- src/Sylius/Component/User/Model/User.php
- tests/Functional/UpdatingUserPasswordEncoderTest.php
| Related tickets | closes #9560, related to #10080
TODO:
> Password hashing - update encoder on login

- docs/plugins/creating-plugin.rst
> less noise

- docs/customization/controller.rst
- Sylius config is now in `packages` subdirectory
> [Documentation] Update Sylius config path

- composer.json
> Require stable FOB/SymfonyExtension v2

- docs/book/orders/shipments.rst
as this is what the flat rate calculator in the core bundle is expecting.
> Using channel code in shipping method configuration

- .travis.yml
- composer.json
- symfony.lock
| Related tickets | based on #9929 
> Include PHP 7.3 in the build

- docs/components_and_bundles/bundles/SyliusGridBundle/configuration.rst
This is mentioned in 2.3 of the doc, but should be also said here.
> [GridBundle] Doc improvement

- docs/plugins/plugin-development-guide/implementation.rst
> Syntax error in documentation

- UPGRADE-1.4.md
> Upgrade guide from `v1.3.X` to `v1.4.0`

- config/bundles.php
- src/Kernel.php
> Move bundle registration from Kernel class to "bundles.php"

- src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/Configuration/SelectAttributeChoicesCollectionType.php
- src/Sylius/Bundle/ResourceBundle/test/app/config/routing.yml
- src/Sylius/Bundle/ResourceBundle/test/src/Tests/Controller/BookApiTest.php
| Related tickets | related with https://github.com/Sylius/Sylius/pull/10077
Even though we don't support Sylius 1.1 yet, it would be nice to have the build passing 😄 This version should still get security fixes and it can be hard to determine if this security fix does not break anything if the build would be failing anyway 🔐 👁
> [1.1] Fix select attributes according to recent Symfony form changes

- src/Sylius/Bundle/TaxonomyBundle/composer.json
> Make build passing for TaxonomyBundle

- docs/cookbook/shop/checkout.rst
| Branch?         | 1.3 or master 
| Related tickets | documents #9889
> [Docs] Change base dir for override config resources

- app/migrations/Version20190204092544.php
> [BuildFix] Fix AbstractMigration use statement

- features/order/managing_orders/seeing_order_without_shipping_address.feature
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
- src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_addresses.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
| Related tickets | replaces https://github.com/Sylius/Sylius/pull/7381
This is an old issue, I've rebased the previous PR and added some test. Thank you @DmitriyTrt for your work!
> Don't fail on billing or shipping address not set ver.2

- docs/book/orders/cart-flow.rst
- docs/book/orders/index.rst
- docs/book/orders/map.rst.inc
| Related tickets | related to https://github.com/Sylius/Sylius/issues/8370
> Cart flow documented

- features/channel/managing_channels/editing_shop_billing_data_on_channel.feature
- src/Sylius/Behat/Context/Setup/ChannelContext.php
Previous scenarios checked not exactly "editing channel shop billing data on channel" but "adding shop billing data to an existing channel" 💃
> Improve shop billing data edit scenario

- docs/_themes/sylius_rtd_theme/breadcrumbs.html
- docs/_themes/sylius_rtd_theme/static/css/sylius.css
> Add Sylius demo link

- docs/cookbook/entities/custom-translatable-model.rst
Invert the generation of migration part with the registration in sylius_resource
| Type             | Documentation
| Related tickets | fixes #10172
> [Docs] Reverse parts in Custom Translatable Model

- src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
| Related tickets | related to https://github.com/Sylius/Sylius/pull/10079
It's a little bit a new feature... but on the other hand, it's more like a missing part of the `ShopBillingData` feature, so I open this one to `1.4`. But I'm open for a discussion 😄
> ShopBillingData fixtures

- composer.json
- symfony.lock
| Branch?         | 1.3 
| Related tickets | fixes #10206 
> Add behat/transliterator library

- src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
| Related tickets | fixes #9538
> Fix Sylius Grid on smaller screens

- docs/contributing/organization/core-team.rst
Well, well, well... Two things happened:
1) I got married 👰 and have changed my surname (half a year ago 😂 )
2) @bartoszpietrzak1994 has joined the Core Team and it seems we forgot to add him 🎉
> [Docs] Core Team

- .github/PULL_REQUEST_TEMPLATE.md
> Make PR template great again

- docs/cookbook/configuration/disabling-admin-notifications.rst
> Fixing incorrect location in documentation for turning off admin norifications

- src/Sylius/Component/Core/spec/Model/CustomerSpec.php
> [Phpspec] Add missing specs on customer core model

- composer.json
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/10253
But we should definitely figure out the problem... We can open another issue for that 🚀
> [HotFix] Conflict with Twig 2.7.3 that breaks themes bundle

- src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionValueCollectionType.php
| Branch?         | 1.0-1.4, master
> Fix assertion's message for ProductOptionValueCollectionType

- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_user.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/test_services.xml
- src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php
- src/Sylius/Bundle/UserBundle/Factory/UserWithEncoderFactory.php
- tests/Functional/UpdatingUserPasswordEncoderTest.php
| Related tickets | fixes #10196
Note: This is not the final form/location of the test. In fact, I wasn't sure where to put it - suggestion are welcome. But it serves its purpose, it proves oAuth User Provider is broken as described in #10196.
Later this day I will provide the fix.
> [CoreBundle] oauth user provider fix

- features/shipping/managing_shipments/browsing_shipments.feature
- features/shipping/managing_shipments/browsing_shipments_from_multiple_channels.feature
- features/shipping/managing_shipments/browsing_single_shipment_from_single_channel.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/admin.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/shipment.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/ui/shipping/managing_shipments.yml
- src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipment.yml
| Related tickets | fixes #10218
> Browsing shipments

- docs/book/orders/promotions.rst
> Added a missing word

- docs/book/orders/orders.rst
Let requires an infinitive without particle to
> Fix a grammar mistake

- docs/_themes/sylius_rtd_theme/static/css/sylius-custom.css
> Add plugin-feature docs style

- src/Sylius/Bundle/UserBundle/EventListener/UserDeleteListener.php
- src/Sylius/Bundle/UserBundle/spec/EventListener/UserDeleteListenerSpec.php
| Related tickets | Fixed #9969  Mentioned #9988 
> [UserBundle] Fix user comparaison on user delete listener

- docs/components_and_bundles/bundles/SyliusGridBundle/filters.rst
- features/shipping/managing_shipments/filtering_shipments_by_state.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
- src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
- src/Sylius/Behat/Page/Admin/Shipment/IndexPageInterface.php
- src/Sylius/Behat/Resources/config/services/pages/admin/shipment.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
- src/Sylius/Bundle/GridBundle/Form/Type/Filter/SelectFilterType.php
- src/Sylius/Bundle/GridBundle/Resources/config/services/filters.xml
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/select.html.twig
- src/Sylius/Component/Grid/Filter/SelectFilter.php
> select filter + filter shipment by state

- features/account/customer_account/viewing_orders_history/viewing_payment_status_for_an_order.feature
- src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
- src/Sylius/Behat/Page/Shop/Account/Order/ShowPage.php
- src/Sylius/Behat/Page/Shop/Account/Order/ShowPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/PaymentState/orderPaymentState.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/PaymentState/singlePaymentState.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_payments.html.twig
| Related tickets | fixes #9933 
> Payment status at  order history page

- features/account/customer_account/viewing_orders_history/viewing_shipment_status.feature
- features/account/customer_account/viewing_orders_history/viewing_shipment_status_on_a_placed_order_show_page.feature
- src/Sylius/Behat/Context/Ui/Shop/AccountContext.php
- src/Sylius/Behat/Page/Shop/Account/Order/ShowPage.php
- src/Sylius/Behat/Page/Shop/Account/Order/ShowPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/ShipmentState/orderShipmentState.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/ShipmentState/singleShipmentState.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_shipments.html.twig
> Orders shipment status

- features/shipping/managing_shipments/managing_of_shipments_status.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
- src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
- src/Sylius/Behat/Page/Admin/Shipment/IndexPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipment.yml
- src/Sylius/Bundle/ShippingBundle/Resources/translations/flashes.en.yml
| Branch?         |master
| New feature?    |yes
| Related tickets | based on PR #10249
> Changing shipment state in shipment index

- config/routes/sylius_shop.yaml
- docs/cookbook/shop/disabling-localised-urls.rst
- features/locale/browsing_shop_in_different_than_default_locale.feature
| Related tickets | fixes #10173 
> fixes #10173, wrong regular expression for locale

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/ProductFixture.php
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/ProductFixtureTest.php
| Related tickets | fixes #10272
PS: Manually tested with next definitions:
```yams
tshirt_product:
options:
amount: 15
product:
options:
custom:
product_with_slug:
code: product_with_slug
slug: product-with-slug
description: Product with slug
channels:
- US_WEB
taxons:
- mugs
enabled: true
product_with_generated_slug:
code: product_with_generated_slug
name: Product with generated slug
channels:
- US_WEB
taxons:
- mugs
enabled: true
product_review:
options:
random: 40
```
> Improved: Product fixture (fixed #10272)

- docs/cookbook/emails/mailer.rst
Minor fix to `How to configure mailer?` cookbook presentation
> [Docs] Fix presentation of "How to configure mailer" cookbook

- docs/book/installation/installation.rst
Fix minor typo on config parameter.
| Q                       | A
| Branch?            | 1.3
| Bug fix?            | no
| BC breaks?       | no
| Deprecations?  | no
| Related tickets  |
| License             | MIT
> [DOC][Installation] Fix minor typo

- features/shipping/managing_shipments/access_shipments_order_from_shipment_index.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
- src/Sylius/Behat/Page/Admin/Shipment/IndexPage.php
- src/Sylius/Behat/Page/Admin/Shipment/IndexPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipment.yml
| Related tickets | based on #10258
> Show order directly from shipments page

- docs/contributing/documentation/overview.rst
> [Docs] Update contributing guide

- src/Sylius/Bundle/AdminBundle/Event/PromotionMenuBuilderEvent.php
- src/Sylius/Bundle/AdminBundle/Menu/PromotionUpdateMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Resources/config/services/menu.xml
- src/Sylius/Bundle/AdminBundle/Resources/views/Promotion/_toolbar.html.twig
- src/Sylius/Bundle/AdminBundle/spec/Event/PromotionMenuBuilderEventSpec.php
| Related tickets | introduced in #10250
> [Admin][Promotion] Update promotion menu builder name to be consistent with other

- src/Sylius/Bundle/GridBundle/composer.json
See https://github.com/symfony/symfony/issues/31152 and https://github.com/symfony/symfony/pull/31156.
> Add a workaround for GridBundle & Symfony 4.2.7 to make tests passing

- app/migrations/Version20190416073011.php
- features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_per_customer_usage_limit.feature
- features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_usage_limit.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/_form.html.twig
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/CoreBundle/Form/Extension/PromotionCouponTypeExtension.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/PromotionCoupon.orm.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Model/PromotionCoupon.php
- src/Sylius/Component/Core/Model/PromotionCouponInterface.php
- src/Sylius/Component/Core/Promotion/Modifier/OrderPromotionsUsageModifier.php
- src/Sylius/Component/Core/spec/Model/PromotionCouponSpec.php
- src/Sylius/Component/Core/spec/Promotion/Modifier/OrderPromotionsUsageModifierSpec.php
- tests/Responses/Expected/promotion_coupon/create_validation_fail_response.json
> [PromotionCoupon] Non reusable coupons after cancelling the orders

- docs/cookbook/deployment/platform-sh.rst
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/parameters.yml
Related to https://github.com/doctrine/DoctrineCacheBundle/issues/156.
> Remove dead configuration related to pre-stable Sylius RBAC

- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/account/order.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
- src/Sylius/Bundle/ShopBundle/Resources/views/Grid/Action/show.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Grid/Filter/string.html.twig
- src/Sylius/Bundle/UiBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/UiBundle/composer.json
> [Shop] Update grid action and filter keys to decouple shop from admin

- src/Sylius/Bundle/CoreBundle/Controller/OrderController.php
- src/Sylius/Bundle/OrderBundle/Controller/OrderController.php
| Related tickets | fixes #10319 
> fix OrderBundle depends on Core component #10319

- composer.json
- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Grid/Action/_pay_deprecated.html.twig
- src/Sylius/Bundle/ShopBundle/composer.json
| Related tickets | introduced in #10331 
See https://github.com/Sylius/Sylius/pull/10331#discussion_r278405715 for the details.
>  Bring back "pay" grid action for backwards compatibility

- src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/LocaleFixtureTest.php
Reverts Sylius/Sylius#10308, see the reasoning in the comment there.
> Revert "Fix base locale"

- docs/book/products/products.rst
Fixed incorrect variable.
`$variant` should be `$productVariant`
> Update documentation products.rst

- docs/api/product_variants.rst
> Quick fix product variants api invalid json

- docs/cookbook/promotions/custom-promotion-action.rst
> Fix wrong use statement in example

- src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
> fix default repository for variant and association type resources

- package.json
- yarn.lock
> [Maintenance] Upgrade minimal jquery version

- docs/customization/repository.rst
> [Docs] Update "Customizing Repositories"

- docs/customization/validation.rst
> [Docs] Update "Customizing Validation"

- docs/customization/form.rst
> [Docs] Update "Customizing Forms"

- docs/customization/factory.rst
> [Docs] Update "Customizing Factories"

- docs/customization/model.rst
> [Docs] Update "Customizing Models"

- docs/customization/controller.rst
> [Docs] Update "Customizing Controllers"

- docs/customization/grid.rst
> [Docs] Update "Customizing Grids"

- docs/cookbook/api/api.rst
> update documentation how to use api

- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php
> [Behat] Fix duplicate step definition

- features/product/viewing_products/accessing_product_page_via_permalink.feature
- features/shipping/managing_shipments/accessing_shipments_order_from_shipment_index.feature
> [Behat] Make feature filenames consistent with others

- features/taxonomy/managing_taxons/deleting_taxon.feature
- src/Sylius/Behat/Page/Admin/Product/IndexPage.php
- src/Sylius/Behat/Page/Admin/Product/IndexPerTaxonPage.php
- src/Sylius/Behat/Page/Admin/Taxon/CreatePage.php
- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-taxon-tree.js
- src/Sylius/Bundle/AdminBundle/Resources/private/sass/_taxonomy.scss
- src/Sylius/Bundle/AdminBundle/Resources/private/sass/main.scss
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/index.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithButtons.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithoutButtons.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/create.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Taxon/update.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
| Related tickets | fixes #9347
> Improve taxon UI

- features/promotion/managing_promotions/accessing_promotion_with_rule_that_contains_removed_taxon.feature
| Related tickets | https://github.com/Sylius/Sylius/pull/10228, https://github.com/Sylius/Sylius/pull/10365
| License         |
> [Build Fix][Behat] Change scenarios to @javascript due to taxon tree changes

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_breadcrumb.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_configurableProduct.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_simpleProduct.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/show.html.twig
> Fix product show page margins

- src/Sylius/Behat/Context/Setup/ProductTaxonContext.php
- src/Sylius/Behat/Context/Ui/Admin/ProductShowPageContext.php
- src/Sylius/Behat/Element/Product/ShowPage/MediaElement.php
related to comments:
https://github.com/Sylius/Sylius/pull/10296#discussion_r283246583
https://github.com/Sylius/Sylius/pull/10296#discussion_r283247211
https://github.com/Sylius/Sylius/pull/10296#discussion_r283247776
> [Admin][Product] Show page fixes

- features/product/managing_product_variants/checking_option_values_while_edit_product_variant.feature
- features/product/managing_product_variants/seeing_correct_option_values_while_editing_product_variant.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePageInterface.php
- src/Sylius/Bundle/ProductBundle/Form/Type/ProductOptionValueCollectionType.php
| Related tickets | fixes #8999, replaces #9223
> As an Administrator, I want always to have proper option values selected while editing a product variant

- docs/customization/state_machine.rst
> [Docs] Update "Customizing State Machine"

- .github/PULL_REQUEST_TEMPLATE.md
- docs/contributing/code/patches.rst
> Bump the Sylius release versions in docs

- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
> [Fixtures] Added random generated order complete date

- README.md
> Use HTTPS links when possible

- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_summary.html.twig
| Related tickets | related #10400 
> Add prices and discounts to the order summary box

- UPGRADE-1.3.md
Same snippets will be added to UPGRADE-1.4.md and UPGRADE-1.5.md after this PR is merged.
> Add known errors section to UPGRADE file

- src/Sylius/Bundle/AdminBundle/Resources/views/_security.html.twig
> Add admin user avatar placeholder

- features/account/customer_account/viewing_orders_history/order_is_always_placed_in_a_base_currency_of_a_channel.feature
- features/checkout/ability_to_confirm_an_order_with_a_promotion_on_shipping.feature
- features/checkout/prices_get_updated_throughout_checkout.feature
- features/checkout/seeing_order_summary/seeing_shipping_discount_on_order_summary_page.feature
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php
- src/Sylius/Behat/Page/Shop/Account/Order/ShowPage.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/private/js/app.js
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_headers.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_item.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
| Related tickets | related #10400 
The `_shipping.html.twig` file may require some changes
> Change order summary table

- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_item.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
| Related tickets | https://github.com/Sylius/Sylius/pull/10420#discussion_r291984319
<hr/>
Before:
After:
<hr/>
Before:
After:
<hr/>
Before:
After:
> Keep all prices in the same currency in checkout

- package.json
- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-forms-list.js
- yarn.lock
> Add an alert about unsaved changes

- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
> Unify shipping row on the order summary table

- docs/getting-started-with-sylius/deployment.rst
- docs/getting-started-with-sylius/shipping-and-payment.rst
From code review by @CoderMaggie in #10384.
> Fix typos and grammar in the Getting Started guide

- docs/book/architecture/fixtures.rst
- src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/LocaleFixtureTest.php
- src/Sylius/Bundle/CoreBundle/spec/Fixture/LocaleFixtureSpec.php
| Related tickets | documentation for #10342 
> [Docs] Describe available configuration options for locale fixture

- src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/BackwardsCompatibility/ResolveShopUserTargetEntityPass.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_user.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Customer.orm.xml
- src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
Both the first and the second commit should pass before merging this PR. This assures as the changes as backwards compatible (second change resigns from BC layer).
| Related tickets | fixes #10447, fixes #9360, related to #10408
> Fix interfaces mapping in Doctrine for admin user and shop user

- src/Sylius/Behat/Element/Product/ShowPage/AssociationsElement.php
- src/Sylius/Behat/Element/Product/ShowPage/VariantsElement.php
- src/Sylius/Bundle/AdminBundle/Resources/config/services.xml
- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- src/Sylius/Bundle/AdminBundle/Resources/private/sass/main.scss
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_associations.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_attributes.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_configurableProduct.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_details.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_media.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_moreDetails.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_options.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_pricing.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_shipping.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_simpleProduct.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_taxonomy.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variants.html.twig
- src/Sylius/Bundle/AdminBundle/Twig/ChannelNameExtension.php
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> Improve admin product show page UI

- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/AvatarImage.orm.xml
> AvatarImage Doctrine mapping fix

- docs/contributing/code/patches.rst
- docs/contributing/documentation/overview.rst
- docs/getting-started-with-sylius/installation.rst
> [Docs] Update Sylius versions in installation and contribution guides

- src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php
- src/Sylius/Bundle/CoreBundle/Tests/Fixture/LocaleFixtureTest.php
- src/Sylius/Bundle/CoreBundle/spec/Fixture/LocaleFixtureSpec.php
> Do not crash when duplicated locales are passed to the fixture

- src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
- src/Sylius/Bundle/UiBundle/Resources/views/Layout/sidebar.html.twig
> Add footer with Sylius version to the admin panel

- features/payment/managing_payments/accessing_payments_order_from_payment_index.feature
- features/payment/managing_payments/browsing_payments.feature
- features/payment/managing_payments/filtering_payments_by_state.feature
- features/payment/managing_payments/managing_of_payment_status.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentsContext.php
- src/Sylius/Behat/Page/Admin/Payment/IndexPage.php
- src/Sylius/Behat/Page/Admin/Payment/IndexPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/admin.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/payment.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/ui/payment/managing_payments.yml
- src/Sylius/Bundle/AdminBundle/Menu/MainMenuBuilder.php
- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/payment.yml
**View IndexPage**
**All filters:**
**Success after push Completed button**
**After filtered and don't find existent state**
> [Admin] Index of payments

- docs/cookbook/promotions/custom-promotion-action.rst
> [Promotion] Fix Action creation doc

- features/payment/managing_payments/filtering_payments_by_state.feature
- features/shipping/managing_shipments/filtering_shipments_by_state.feature
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
> [Admin] Minor fixes payment shipment

- src/Sylius/Bundle/AdminBundle/Resources/private/sass/main.scss
> [UI] Fix button groups radius

- features/product/viewing_product_in_admin_panel/viewing_product_for_particular_channel.feature
- features/product/viewing_product_in_admin_panel/viewing_product_for_single_channel.feature
- src/Sylius/Behat/Context/Setup/ChannelContext.php
- src/Sylius/Behat/Context/Setup/ProductContext.php
- src/Sylius/Behat/Context/Ui/Admin/ProductShowPageContext.php
- src/Sylius/Behat/Context/Ui/Shop/ProductContext.php
- src/Sylius/Behat/Page/Admin/Product/ShowPage.php
- src/Sylius/Behat/Page/Admin/Product/ShowPageInterface.php
- src/Sylius/Behat/Page/Shop/Product/ShowPage.php
- src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_header.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
**Before clicking:**
**After clicking in several channels:**
**One Channel**
**All channels are disabled in product**
> [Admin]Admin choose channel in product show page

- features/user/managing_customer_groups/customer_group_validation.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomerGroupsContext.php
- src/Sylius/Behat/Page/Admin/Crud/CreatePage.php
- src/Sylius/Behat/Page/Admin/Crud/CreatePageInterface.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePage.php
- src/Sylius/Behat/Page/Admin/Crud/UpdatePageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_content.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_content.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Crud/form_validation_errors_checker.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Admin] Form validation error 

- src/Sylius/Bundle/CustomerBundle/Resources/translations/validators.en.yml
> [Admin] Minor fixes customer group validation form

- src/Sylius/Behat/Context/Setup/ChannelContext.php
Fixes : https://github.com/Sylius/Sylius/pull/10483
> Minor Fixes - Admin choose channel in product show page

- src/Sylius/Bundle/AdminBundle/Resources/private/sass/main.scss
> [Admin] Fix css file

- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Update/_breadcrumb.html.twig
**New link:**
**After clicking:**
**to url:**
**Product edit page:**
> [Admin] Add link to product in variant breadcrumb

- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
Reverts Sylius/Sylius#10489
Ref. https://github.com/Sylius/Sylius/commit/608546bd4a9d1ee05e7afd4f2961f04ca3a989b5#r34204877
> Revert "Make it possible to have no shipping methods for Order fixtures"

- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_form.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/_media.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Form/imagesTheme.html.twig
| Related tickets | partially #10479 
> Add avatar preview

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Common/Label/paymentState.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Common/Label/shipmentState.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_payment.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipment.html.twig
**Payment index:**
_Before:_
_After:_
**Shipment index:**
_No changes:_
**Order show:**
_Before:_
_After:_
> [Admin] Unify payment and shipment labels

- src/Sylius/Bundle/UiBundle/Resources/private/sass/_filters.scss
- src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/date.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/money.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/string.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
> Improve filters UI

- src/Sylius/Bundle/ShopBundle/Resources/config/services/listeners.xml
> [Shop] Fix passed channel context service to be composite

- src/Sylius/Bundle/AdminBundle/Controller/ImpersonateUserController.php
> Marked router dependency as deprecated in admin ImpersonateUserController

- src/Sylius/Bundle/CoreBundle/Fixture/CapsProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/DressProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/JeansProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/NewTshirtProductFixture.php
- src/Sylius/Bundle/CoreBundle/Fixture/ProductFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
| Related tickets | based on: #10529 
> [Fixtures] Add tax category to product.

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
> [Fixtures] Variant name now is concatenated options value.

- .travis.yml
| Related tickets | fixes all current builds 💃 
I don't know it's a final fix, probably the best solution would be to switch to `xenial`... but still, it fixes a build 🎉
> [HotFix?] Move mysql service to fix the build

- src/Sylius/Bundle/UiBundle/Resources/private/sass/_filters.scss
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/date.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/money.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/string.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
> Improve filters

- src/Sylius/Bundle/AdminBundle/Resources/views/Common/_address.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Locale/Grid/Field/name.html.twig
- src/Sylius/Bundle/LocaleBundle/Twig/LocaleExtension.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/_address.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/flags.html.twig
| Related tickets | fixes #10416, #9479
NOTE: There is a commit per file because the PR was crafted entirely on GitHub.
> Flags are not languages

- src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
Even though I love **Composition over inheritance** principle, this controller is already poorly written and, I believe, we should make its customization as painless as possible 🔪 🤕
> [Order] Change OrderItemController methods to protected

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/ProductFixture.php
> [Fixtures] Added 'tracked' field to product fixture configuration

- src/Sylius/Bundle/UiBundle/Resources/views/Macro/buttons.html.twig
> Allow translation of custom labels

- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
Fixes 2 possible bugs/inaccuracies during fixture orders creation:
- does not allow to create an order with products that are not available in order's channel (especially useful, when you create more than one channel in fixtures 💃 )
- does not allow to duplicate variant within order items (the quantity is now increased in the existing item)
> [Fixture] Improve order fixture

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
> [Fixtures] Minor fixes.

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/jeans.yaml
> [Fixtures] Jeans attributes names fix

- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_summary.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Admin][Order] Change item to unit discount on summary page

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
A constructor argument [was added](https://github.com/Sylius/Sylius/compare/v1.6.0-ALPHA.1...master#diff-31d0979068f78962900cd057ebf0fc5fR112) and it should be optional.
> Avoid BC break in ProductExampleFactory

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/cap.yaml
> [CoreBundle] Fixtures creating SimpleProduct, remove options from caps

- docs/_themes/sylius_rtd_theme/breadcrumbs.html
- docs/_themes/sylius_rtd_theme/static/css/sylius.css
> Add course ad

- src/Sylius/Bundle/AdminBundle/Resources/views/_logo.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
> [AdminBundle] Extract logo to separate twig file

- src/Sylius/Bundle/AddressingBundle/Resources/translations/validators.en.yml
> Use {{ limit }} to allow min/max value update

- docs/cookbook/configuration/disabling-shop-admin-api.rst
These three lines have to be removed in order for Sylius to work without ShopBundle.
> [Documentation] Delete additional lines to remove ShopBundle

- docs/cookbook/payments/custom-payment-gateway.rst
> [Documentation][Minor] Removing redundant dots

- features/shipping/managing_shipments/browsing_shipments.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Resources/config/suites/ui/shipping/managing_shipments.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/shipment.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ShipmentRepository.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/10431
> [Admin][Shipment] Not displaying shipments in cart state on the list

- features/payment/managing_payments/browsing_payments.feature
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Resources/config/suites/ui/payment/managing_payments.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment.yml
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentRepository.php
| Related tickets | similar to https://github.com/Sylius/Sylius/pull/10605
> [Admin][Payment] Not displaying payments in cart state on the list

- docs/contributing/documentation/overview.rst
I had issues with `brew install`, and there is note, that this tap is for internal usage only. Also, I have some issues with proper versions of libraries installed. `pip` works like charm.
Second fix is related to the folder of command execution. I found it more convinient to run all commands from root folder.
> [Documentation][Contribution] Improve doc contribution guide

- docs/cookbook/payments/custom-payment-gateway.rst
> [Documentation][Minor] Proper comment in xml file

- src/Sylius/Bundle/PayumBundle/Action/AuthorizePaymentAction.php
- src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php
- src/Sylius/Bundle/PayumBundle/Provider/PaymentDescriptionProvider.php
- src/Sylius/Bundle/PayumBundle/spec/Provider/PaymentDescriptionProviderSpec.php
| Related tickets | replaces https://github.com/Sylius/Sylius/pull/10574, fixes https://github.com/Sylius/Sylius/issues/8958
Replaces the previous fix, with fixed spec. Thank you @Leobaillard for your work! 🎉 🏇
> [PayumBundle] Use Payment amount in Payum gateways actions

- src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
> [HOTFIX] [Behat] Fix tax extraction

- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
| Related tickets | replaces https://github.com/Sylius/Sylius/pull/10503, fixes https://github.com/Sylius/Sylius/issues/10502, https://github.com/Sylius/Sylius/issues/10490
Thank you @igormukhingmailcom for your work! It's rebased and refactored now
> [Fixtures] Allow no shipping and payments in fixtures

- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
> Fix bug after rebase

- features/shipping/managing_shipments/managing_of_shipments_status.feature
- src/Sylius/Behat/Context/Ui/EmailContext.php
- src/Sylius/Behat/Resources/config/suites/ui/shipping/managing_shipments.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipment.yml
- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/10581
> Sending email  after ship shipment on grid

- docs/customization/fixture_suites.rst
- docs/customization/index.rst
> [Docs]How to add your custom fixture suites?

- docs/customization/fixtures.rst
- docs/customization/index.rst
> [Docs] How to add your custom fixtures?

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/OrderExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
| Related tickets | based on #10550
> [Fixture] Make order fixture more flexible

- src/Sylius/Bundle/CoreBundle/Form/Type/User/AdminUserType.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
> Use fallback locale as default for the new administrators

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/OrderExampleFactory.php
> [Core] Improved fixture example factory

- features/payment/managing_payments/managing_of_payment_status.feature
- src/Sylius/Behat/Context/Ui/EmailContext.php
- src/Sylius/Behat/Resources/config/suites/ui/payment/managing_payments.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/payment.yml
> Fix email after complete payment via grid

- docs/_themes/sylius_rtd_theme/layout.html
> Add Blackfire ad

- features/payment/managing_payments/managing_of_payment_status.feature
- features/shipping/managing_shipments/managing_of_shipments_status.feature
- src/Sylius/Behat/Context/Ui/EmailContext.php
- src/Sylius/Behat/Resources/config/suites/ui/shipping/managing_shipments.yml
> [Admin] Proper tests for shipment mailing

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
> [Fixture] channel fixture fix

- src/Sylius/Behat/Context/Ui/EmailContext.php
> [Behat][Minor] Add a few typehints

- docs/customization/fixture_suites.rst
- docs/customization/fixtures.rst
| Related tickets | introduced by #10395
To do:
> [Documentation] Fixtures customization guides - fixes

- docs/_themes/sylius_rtd_theme/layout.html
> [Docs] Fix Blackfire Ad 

- docs/_themes/sylius_rtd_theme/layout.html
> [Docs] Fix Ad

- docs/_themes/sylius_rtd_theme/breadcrumbs.html
> Update online course ad

- README.md
> Add Sylius 1.6 banner to the docs

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/customer_order.yml
> removed customer from customer order grid

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/OrderExampleFactory.php
> [Fixture] Shipment and payment date are same like order

- features/payment/managing_payments/filtering_payments_by_channel.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentsContext.php
- src/Sylius/Behat/Page/Admin/Payment/IndexPage.php
- src/Sylius/Behat/Page/Admin/Payment/IndexPageInterface.php
- src/Sylius/Behat/Resources/config/suites/ui/payment/managing_payments.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/payment.yml
- symfony.lock
> [Payment] Filtering payments by channel

- composer.json
| Related tickets | fixes #10657 
> Remove ShippingBundle spec from autoload-dev

- features/order/managing_orders/seeing_order_payment_state_as_completed_if_order_total_is_zero.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
- src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_payments.html.twig
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> [Order] Added "no payments" label for order without payment

- src/Sylius/Bundle/CoreBundle/Command/InformAboutGUSCommand.php
To make it more clear why and how we use the GUS data 💃 🚀
> Improve GUS information notification

- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_payments.html.twig
| Related tickets | introduced in https://github.com/Sylius/Sylius/pull/10653
Before: 
After:
> Fix unnecessarily centered payment

- src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Grid/Field/channel.html.twig
To make channel fields consistent with the rest of the system, I changed channel code to channel name
> Change channel code to name

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_details.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variants.html.twig
> [Admin][Product] Fix displayed stocks on product show page

- src/Sylius/Bundle/AdminBundle/Resources/config/grids/order.yml
> fix order orders grid

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
| Related tickets | replaced #10696
> [Fixtures] Add env variable for channel hostname

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variantContentShipping.html.twig
| Related tickets | after #10694
> [Admin][Product] Fix displaying variants on product show page

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/cap.yaml
| Branch?         | 
| Deprecations?   | n
> Minor fixtures fixes

- docs/book/installation/installation.rst
> [Docs] update docs.

- docs/_themes/sylius_rtd_theme/breadcrumbs.html
- docs/getting-started-with-sylius/index.rst
> Update course ad

- features/product/viewing_product_in_admin_panel/accesing_product_edit_page_from_show_page.feature
- src/Sylius/Behat/Context/Ui/Admin/AccessingEditPageFromProductShowPageContext.php
- src/Sylius/Behat/Context/Ui/Admin/ProductShowPageContext.php
- src/Sylius/Behat/Page/Admin/Product/ShowPage.php
- src/Sylius/Behat/Page/Admin/Product/ShowPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/ui/product/accessing_edit_page_from_product_show_page.yml
- src/Sylius/Behat/Resources/config/suites/ui/product/viewing_products.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_header.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variantContent.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variantItem.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variants.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Update/_toolbar.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/_showInShopButton.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Update/_toolbar.html.twig
To improve UX I added edit button on the product show page and on each variant row.
> [Product] Go to edit from product show page

- src/Sylius/Bundle/AttributeBundle/Resources/config/validation/Attribute.xml
- src/Sylius/Bundle/AttributeBundle/Resources/config/validation/AttributeTranslation.xml
| Bug fix?        | No
| New feature?    | Sort of
| BC breaks?      | No
| Deprecations?   | No
> Do not impose a length of two on attribute codes and names

- src/Sylius/Bundle/PromotionBundle/Command/GenerateCouponsCommand.php
- src/Sylius/Bundle/PromotionBundle/Tests/Command/GenerateCouponsCommandTest.php
| Related tickets | fixes #10692
> [Promotion] Remove coupling to core

- features/addressing/managing_countries/managing_provinces_of_country.feature
- src/Sylius/Bundle/AddressingBundle/Resources/config/validation/Province.xml
to support official austrian province codes
| Related tickets | fixes #10604
> [Admin][Adressing] fixed province code validation regex

- src/Sylius/Bundle/UiBundle/Resources/views/Macro/buttons.html.twig
> Remove flashing from the bulk button

- src/Sylius/Behat/Context/Ui/Admin/ManagingProductAttributesContext.php
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product_attribute.yml
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
> Translate attribute type on attributes grid

- src/Sylius/Behat/Context/Ui/PaypalContext.php
> [Behat] Fix a typo on Paypal context

- docs/cookbook/payments/stripe.rst
> [Docs] Add tag that stripe is outdated and add SCA note

- docs/plugins/official-plugins.rst
- src/Sylius/Behat/Context/Cli/ShowingAvailablePluginsContext.php
- src/Sylius/Bundle/CoreBundle/Command/ShowAvailablePluginsCommand.php
> Remove unsupported RBAC plugin from command and docs

- src/Sylius/Behat/Page/Admin/Product/IndexPage.php
- src/Sylius/Behat/Page/Admin/ProductVariant/IndexPage.php
All Behat pages are not final except these two pages. Behat pages need to be extended easily with override method.
> [Behat] Remove final on product index and product variant index pages

- src/Sylius/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php
| Related tickets | fixes #9928 
> [Payum] infinite loop on state machine exception fixed

- src/Sylius/Bundle/AdminBundle/Resources/views/_support.html.twig
> [Admin] Fix Github issue tracker link

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/OrderExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/custom_fixtures.yaml
| Branch?         | 1.6 (as it present only at 1.6 and not present at 1.5 or 1.4)
| Related tickets | fixes #10719 
> Fix 10719 infinite order fixture loading

- features/channel/managing_channels/selecting_locales_available_for_channel.feature
> [Behat][Admin] Add scenarios for validating default locale for a channel

- features/channel/managing_channels/selecting_locales_available_for_channel.feature
- src/Sylius/Behat/Context/Setup/LocaleContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php
- src/Sylius/Behat/Page/Admin/Channel/CreatePage.php
- src/Sylius/Behat/Page/Admin/Channel/UpdatePage.php
- src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/Channel.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/ChannelDefaultLocaleEnabled.php
- src/Sylius/Bundle/CoreBundle/Validator/Constraints/ChannelDefaultLocaleEnabledValidator.php
- src/Sylius/Bundle/CoreBundle/spec/Validator/Constraints/ChannelDefaultLocaleEnabledValidatorSpec.php
| Related tickets | fixes #9307, #10763 
> [Admin][Channel] Validating default locale for a channel

- features/checkout/seeing_order_summary/seeing_summary_order_with_free_product.feature
- features/product/managing_product_variants/adding_product_variant.feature
- features/product/managing_product_variants/product_variant_validation.feature
- features/product/managing_products/adding_product.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php
- src/Sylius/Bundle/CoreBundle/Resources/config/validation/ChannelPricing.xml
- src/Sylius/Bundle/CoreBundle/Resources/translations/validators.en.yml
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/10730
As far as I see, it should not result in any problems for the current implementations 😄 💸 But it would be great if somebody checks it out 🏁
> Allow to define free products

- features/order/managing_orders/seeing_order_discounts.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
- src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/private/sass/main.scss
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_totals.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_totalsPromotions.html.twig
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/10753
Before:
After:
> [Admin][Order] Add promotions to order summary

- docs/book/plugins/approved-plugins.rst
- docs/book/plugins/creating-plugin.rst
- docs/plugin-development-guide/summary.rst
Since the very beginning of the Sylius plugins system, we are giving the availability to make your plugin officially [approved](https://docs.sylius.com/en/latest/book/plugins/approved-plugins.html). This technical review checklist is a detailed instruction what you should focus on, to make the approval process smoother and faster 🎉
> [Docs] Plugins technical review checklist

- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_totals.html.twig
| Related tickets | https://github.com/Sylius/Sylius/pull/10796
> [Admin][Order] Remove unnecessary tag

- features/cart/shopping_cart/seeing_shipping_costs_only_when_required.feature
- features/checkout/seeing_order_summary/seeing_shipping_total_on_order_summary_page.feature
- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_totals.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_summary.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
> [Shop] Hide shipping costs for orders with virtual products

- src/Sylius/Bundle/CoreBundle/Fixture/GeographicalFixture.php
| Branch?         | 1.5 (should be rebased to 1.4)
> Fixed: Typo/artifact

- docs/components_and_bundles/bundles/SyliusGridBundle/configuration.rst
> Fixed: Typo at grid configuration example

- src/Sylius/Component/Core/Model/Order.php
- src/Sylius/Component/Core/spec/Model/OrderSpec.php
| Related tickets | fixes #10800
> [Order] include order promotion adjustments in order promotion total

- src/Sylius/Component/Core/Model/TaxonInterface.php
| Related tickets | fixes #10728
> Added: TimestampableInterface to core TaxonInterface (fixes #10728)

- docs/index.rst
- docs/theming/index.rst
- docs/theming/map.rst.inc
- docs/theming/webpack.rst
| Related tickets | based on #10827
As mentioned in the docs, we are starting to build the Theming Guide iteratively, keep your fingers crossed so that it grows to be one of the best sections in Sylius Docs.
Thank you @kulczy for blessing us with Webpack recently! ✨
> [Docs] Theming Guide: Webpack Encore v1

- src/Sylius/Component/Promotion/Model/PromotionAction.php
- src/Sylius/Component/Promotion/spec/Model/PromotionActionSpec.php
> Do not merge promotion action configuration

- docs/contributing/organization/core-team.rst
> [Docs] Update core team

- docs/api/index.rst
> [Docs] Include link to ShopApi docs to REST API Reference

- src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/PaymentMethod/_form.html.twig
- src/Sylius/Bundle/PayumBundle/Resources/translations/messages.en.yml
> Deprecate Stripe Checkout due to lacking support for SCA

- docs/_themes/sylius_rtd_theme/layout.html
- docs/api/index.rst
> Move ShopApi reference to main menu

- docs/_themes/sylius_rtd_theme/layout.html
> [Docs] Open external links in a new tab

- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
| Related tickets | after https://github.com/Sylius/Sylius/pull/10846
> [Behat][Admin][Order] Fix scenarios for displaying promotions on 1.6 after upmerge

- features/order/managing_orders/seeing_order_discounts.feature
- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
| Related tickets | after #10846, associated with #10853 
> [Behat][Admin][Order] Fix scenarios for displaying promotions on master after upmerge

- features/promotion/managing_coupons/being_unable_to_generate_too_many_coupons_with_prefix_and_suffix.feature
- src/Sylius/Behat/Context/Setup/PromotionContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
- src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePage.php
- src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/setup.xml
- src/Sylius/Bundle/PromotionBundle/Doctrine/ORM/PromotionCouponRepository.php
- src/Sylius/Component/Promotion/Generator/PercentageGenerationPolicy.php
- src/Sylius/Component/Promotion/Repository/PromotionCouponRepositoryInterface.php
- src/Sylius/Component/Promotion/spec/Generator/PercentageGenerationPolicySpec.php
| Related tickets | fixes #10795
> [Admin][Promotion] Fix the prevention of generating too many coupons

- docs/theming/bootstrap-theme.rst
- docs/theming/index.rst
- docs/theming/webpack.rst
> Add warning message to the theming guide

- docs/_themes/sylius_rtd_theme/breadcrumbs.html
> Add docs banner

- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
- src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en.yml
> [Promotion] Improve coupon generation validation message

- .travis.yml
- psalm.xml
- src/Sylius/Bundle/AddressingBundle/composer.json
- src/Sylius/Bundle/CustomerBundle/composer.json
- src/Sylius/Bundle/OrderBundle/composer.json
- src/Sylius/Bundle/PaymentBundle/composer.json
- src/Sylius/Bundle/PromotionBundle/composer.json
- src/Sylius/Bundle/ReviewBundle/composer.json
- src/Sylius/Bundle/ShippingBundle/composer.json
- src/Sylius/Bundle/TaxationBundle/composer.json
- src/Sylius/Bundle/TaxonomyBundle/composer.json
- src/Sylius/Bundle/UserBundle/composer.json
- src/Sylius/Component/Attribute/Model/Attribute.php
- src/Sylius/Component/Core/Model/Product.php
- src/Sylius/Component/Payment/Model/PaymentMethod.php
- src/Sylius/Component/Product/Model/Product.php
- src/Sylius/Component/Product/Model/ProductAssociationType.php
- src/Sylius/Component/Product/Model/ProductAttribute.php
- src/Sylius/Component/Product/Model/ProductOption.php
- src/Sylius/Component/Product/Model/ProductOptionValue.php
- src/Sylius/Component/Product/Model/ProductVariant.php
- src/Sylius/Component/Shipping/Model/ShippingMethod.php
- src/Sylius/Component/Taxonomy/Model/Taxon.php
Reverting these changes, getting the following error with `dev-master` Sylius on Sylius-Standard:
```
Compile Error: Declaration of App\Entity\Product\Product::createTranslation
!!    (): Sylius\Component\Product\Model\ProductTranslationInterface must be comp
!!    atible with Sylius\Component\Core\Model\Product::createTranslation(): Syliu
!!    s\Component\Resource\Model\TranslationInterface
```
> Revert changes causing BC break

- src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php
> Fix build - remove redundant validation message part

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/cap.yaml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/dress.yaml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/jeans.yaml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/tshirt.yaml
| Branch?         | 1.6 
As the product names in Sylius fixtures were imperfect and not really close to real-life product names, here we have new ones! 🚀
> [Fixtures] Update product names

- src/Sylius/Behat/Context/Setup/UserContext.php
- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
- src/Sylius/Behat/Element/Shop/Account/RegisterElement.php
- src/Sylius/Behat/Page/Shop/Account/LoginPage.php
- src/Sylius/Behat/Page/Shop/Account/LoginPageInterface.php
- src/Sylius/Behat/Page/Shop/Account/RequestPasswordResetPage.php
- src/Sylius/Behat/Page/Shop/Account/RequestPasswordResetPageInterface.php
- src/Sylius/Behat/Page/Shop/Account/ResetPasswordPage.php
- src/Sylius/Behat/Page/Shop/HomePage.php
- src/Sylius/Behat/Page/Shop/HomePageInterface.php
- src/Sylius/Behat/Service/Resolver/CurrentPageResolver.php
- src/Sylius/Behat/Service/Resolver/CurrentPageResolverInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/requestPasswordReset.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/resetPassword.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Login/_form.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Menu/_security.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Register/_form.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/login.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/register.html.twig
- src/Sylius/Bundle/UiBundle/Form/Type/SecurityLoginType.php
- src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/messages.html.twig
- src/Sylius/Bundle/UiBundle/Twig/TestFormAttributeExtension.php
- src/Sylius/Bundle/UiBundle/Twig/TestHtmlAttributeExtension.php
- src/Sylius/Bundle/UserBundle/Form/Type/UserRequestPasswordResetType.php
- src/Sylius/Bundle/UserBundle/Form/Type/UserResetPasswordType.php
- src/Sylius/Component/User/Model/User.php
> Rework Behat testing from classes/ids to attributes for login and registration pages

- src/Sylius/Behat/Context/Ui/Shop/LoginContext.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Menu/_security.html.twig
- src/Sylius/Bundle/UiBundle/Twig/TestFormAttributeExtension.php
Fix for : https://github.com/Sylius/Sylius/pull/10883
> Minor fixes - Rework behat tests

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/cap.yaml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/dress.yaml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/jeans.yaml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/tshirt.yaml
Some french fixtures terms are misspelled, here are fixes.
> Fix misspellings in french fixtures files

- src/Sylius/Bundle/CoreBundle/Installer/Requirement/SettingsRequirements.php
- src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
- symfony.lock
> Add help messages to settings requirements checked in CLI

- docs/cookbook/emails/custom-email-template-per-channel.rst
> [Docs] [Channel]Fix docs with channel

- src/Sylius/Behat/Context/Ui/ThemeContext.php
- src/Sylius/Behat/Page/Shop/HomePage.php
- src/Sylius/Behat/Page/Shop/HomePageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/_footer.html.twig
> [Homepage] Fixes

- docs/cookbook/frontend/google-analytics.rst
- docs/cookbook/frontend/map.rst.inc
- docs/cookbook/index.rst
> [Documentation][Cookbook] How to add Google Analytics script to shop?

- src/Sylius/Bundle/ShopBundle/Resources/private/scss/style.scss
> Fix carousel links

- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutCompleteContext.php
- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutShippingContext.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
- src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectPaymentPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectPaymentPageInterface.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php
- src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPageInterface.php
> [Behat] Cleaning Behat checkout pages

- .github/PULL_REQUEST_TEMPLATE.md
> [Maintenance] Update PR template with supported versions

- docs/api/products.rst
| Branch?         | 1.4, 1.5, 1.6 or master 
> fix: api URI for getting single product detail

- docs/components_and_bundles/bundles/SyliusGridBundle/installation.rst
> Fix missing colon

- psalm.xml
> [Psalm] Exclude deprecated doctrine classes from analysis

- src/Sylius/Behat/Page/Shop/Product/IndexPage.php
- src/Sylius/Behat/Page/Shop/Product/IndexPageInterface.php
- src/Sylius/Behat/Page/Shop/Product/ShowPage.php
- src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php
> Rework ShowPage and IndexPage in Shop/Product

- features/order/managing_orders/resending_order_confirmation_email.feature
- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Context/Ui/EmailContext.php
- src/Sylius/Behat/Page/Admin/Order/ShowPage.php
- src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php
- src/Sylius/Bundle/AdminBundle/Action/ResendOrderConfirmationEmailAction.php
- src/Sylius/Bundle/AdminBundle/EmailManager/OrderEmailManager.php
- src/Sylius/Bundle/AdminBundle/EmailManager/OrderEmailManagerInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/config/app/sylius/sylius_mailer.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml
- src/Sylius/Bundle/AdminBundle/Resources/config/services/email.xml
- src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.en.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Email/layout.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Email/orderConfirmation.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_resendEmail.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Order/show.html.twig
- src/Sylius/Bundle/AdminBundle/spec/EmailManager/OrderEmailManagerSpec.php
- src/Sylius/Bundle/CoreBundle/Mailer/Emails.php
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
| Related tickets | fixes #10907 
Based on https://github.com/Sylius/Sylius/pull/10936
> [Admin][Order] Add resending an order confirmation email

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/OptionsResolver/LazyOption.php
- src/Sylius/Bundle/CoreBundle/Form/Extension/ChannelTypeExtension.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/10782
> [Channel] Prevent from adding default tax zone of a channel in a different scope than tax or all

- src/Sylius/Component/Core/spec/Cart/Context/ShopBasedCartContextSpec.php
- src/Sylius/Component/Core/spec/Customer/CustomerOrderAddressesSaverSpec.php
https://github.com/Sylius/Sylius/pull/10962 It should be done from this branch 💃
> Fix phpspec also on 1.5

- src/Sylius/Bundle/AdminBundle/Resources/views/Email/layout.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Email/layout.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Email/userRegistration.html.twig
> [Email] Use channel hostname in urls

- src/Sylius/Component/Core/Calculator/ProductVariantPriceCalculator.php
- src/Sylius/Component/Core/spec/Calculator/ProductVariantPriceCalculatorSpec.php
> Add code to exception message since name can be null

- behat.yml.dist
| Related tickets | mentioned in https://github.com/Sylius/Sylius/issues/10561#issuecomment-566763425
> [Behat] Disallow w3c in Behat Selenium session

- composer.json
- phpspec.yml.dist
> Upgrade to PHPSpec ^6.1

- .gitignore
- composer.json
- config/bundles.php
- etc/travis/suites/application/script/test-behat-with-javascript
- phpstan.neon
- psalm.xml
- symfony.lock
> Use Symfony CLI command instead of symfony/web-server-bundle

- composer.json
- etc/travis/suites/application/before_install.sh
- etc/travis/suites/application/script/test-behat-with-javascript
- etc/travis/suites/application/script/validate-composer-security
- symfony.lock
Related to #10928, replaces #10967.
> Use Symfony CLI command to check security

- features/addressing/managing_zones/deleting_multiple_zones.feature
- features/channel/managing_channels/deleting_multiple_channels.feature
- features/currency/managing_exchange_rates/deleting_multiple_exchange_rates.feature
- features/payment/managing_payment_methods/deleting_multiple_payment_methods.feature
- features/product/managing_product_association_types/deleting_multiple_product_association_types.feature
- features/product/managing_product_attributes/deleting_multiple_product_attributes.feature
- features/product/managing_product_options/deleting_multiple_product_options.feature
- features/product/managing_product_reviews/deleting_multiple_product_reviews.feature
- features/product/managing_product_variants/deleting_multiple_product_variants.feature
- features/product/managing_products/deleting_multiple_products.feature
- features/promotion/managing_coupons/deleting_multiple_coupons.feature
- features/promotion/managing_promotions/deleting_multiple_promotions.feature
- features/shipping/managing_shipping_categories/deleting_multiple_shipping_categories.feature
- features/shipping/managing_shipping_methods/deleting_multiple_shipping_methods.feature
- features/taxation/managing_tax_categories/deleting_multiple_tax_categories.feature
- features/taxation/managing_tax_rates/deleting_multiple_tax_rates.feature
- features/user/managing_administrators/deleting_multiple_administrators.feature
- features/user/managing_customer_groups/deleting_multiple_customer_groups.feature
- src/Sylius/Behat/Page/Admin/Crud/IndexPage.php
- src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-bulk-action-require-confirmation.js
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/buttons.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
| Related tickets | war started in https://github.com/Sylius/Sylius/pull/10043
Before:
`209 scenarios, 2204 steps, 14m57.61s (37.05Mb)`
After:
`191 scenarios, 2012 steps, 12m57.22s (34.90Mb)`
💃
> [Behat] Remove js requirement from bulk delete scenarios

- src/Sylius/Behat/Page/Shop/Checkout/SelectPaymentPage.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectPayment/_choice.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectPayment/_unavailable.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_steps.html.twig
| Related tickets | based on #10921  
rework payment page
> [Behat] Rework behat - using attributes instead class/id part in payment page

- features/cli/showing_available_plugins.feature
- src/Sylius/Behat/Context/Cli/ShowingAvailablePluginsContext.php
- src/Sylius/Bundle/CoreBundle/Command/ShowAvailablePluginsCommand.php
> [Installation] Inform about BitBagCommerce/SyliusCmsPlugin after installing Sylius

- src/Sylius/Behat/Page/Shop/Product/IndexPage.php
- src/Sylius/Behat/Page/Shop/Product/ShowPage.php
- src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_attributes.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_main.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_search.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Tabs/_attributes.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Tabs/_menu.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Tabs/_reviews.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_addToCart.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_association.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_header.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_images.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_options.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_outOfStock.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_price.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_variants.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_variantsPricing.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_box.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_info.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_starRating.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/_single.html.twig
> Rework ShowPage and IndexPage in Shop/Product to DataAttributes

- src/Sylius/Bundle/ShopBundle/Resources/views/_footer.html.twig
> Add a description to the Plus logo

- features/product/managing_product_options/product_option_unique_code_validation.feature
- features/product/managing_product_options/product_option_validation.feature
- features/shipping/managing_shipping_methods/editing_shipping_method.feature
- features/shipping/managing_shipping_methods/shipping_method_code_validation.feature
- src/Sylius/Behat/Service/JQueryHelper.php
- src/Sylius/Behat/Service/SlugGenerationHelper.php
| Related tickets | related issues https://github.com/Sylius/Sylius/pull/10973, https://github.com/Sylius/Sylius/pull/10562, https://github.com/Sylius/Sylius/pull/10043
Even though waiting for the slug generation should end when it's generated, I've noticed that it still takes a lot of time. So I made a quick experiment with lowering the waiting time and it seems to not harm and even improve execution time a little bit 💃 
I also removed a `@javascript` tag from some scenarios that _de facto_ didn't need it.
Before:
After:
> [Behat] Spend less time waiting for slug generation

- composer.json
- psalm.xml
| Related tickets | fixes https://github.com/Sylius/Sylius/pull/11001#issuecomment-571949612
> SyliusGridBundle downgrade lock

- src/Sylius/Component/Product/Model/Product.php
If you do any work with Attributes, this should be protected, no need for copy-paste
| Branch?         | 1.5, 1.6 or master 
> Making functions protected in Product for more flexible extenidng

- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_aboutUs.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_banner.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_latestProducts.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_latestProductsCarousel.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_newsletter.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Block/_productsGrid.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/index.html.twig
> Use template blocks for our homepage

- src/Sylius/Behat/Page/Shop/HomePage.php
- src/Sylius/Behat/Page/Shop/HomePageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Menu/_currencySwitch.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Menu/_localeSwitch.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Menu/_security.html.twig
> [HomePage][Behat] Rework behats - home page

- src/Sylius/Behat/Page/ErrorPage.php
- src/Sylius/Behat/Page/Shop/Contact/ContactPage.php
- src/Sylius/Behat/Page/Shop/Contact/ContactPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Contact/request.html.twig
> [Contact][Behat] Rework behats  - contact page

- src/Sylius/Behat/Page/Shop/Order/ShowPage.php
- src/Sylius/Behat/Page/Shop/Order/ShowPageInterface.php
- src/Sylius/Behat/Page/Shop/Order/ThankYouPage.php
- src/Sylius/Behat/Page/Shop/Order/ThankYouPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Order/show.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Order/thankYou.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/_flashes.html.twig
> Rework behats after checkout and thanks page

- src/Sylius/Bundle/OrderBundle/Controller/OrderController.php
| Related tickets | fixes #10930
> [API] Fixed OrderController save action issue in not html requests

- composer.json
- src/Sylius/Bundle/CoreBundle/composer.json
> Require LiipImagineBundle ^2.3

- src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutOrderDetailsContext.php
- src/Sylius/Behat/Page/Shop/Order/ShowPage.php
- src/Sylius/Behat/Page/Shop/Order/ShowPageInterface.php
- src/Sylius/Behat/Page/Shop/Order/ThankYouPage.php
> Fix key order and functions names

- docs/customization/controller.rst
| Related tickets | replaces #10706
> [Documentation] Add hint about disabling autowire when extending a controller 

- composer.json
- config/bundles.php
- config/packages/sonata_core.yaml
- src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/UiBundle/composer.json
- symfony.lock
> Upgrade to Sonata Block Bundle ^4.0

- .github/PULL_REQUEST_TEMPLATE.md
| Related tickets | consequence of #11022
> [Maintenance] Update github PR template

- src/Sylius/Bundle/CoreBundle/Resources/config/services/taxation.xml
- src/Sylius/Bundle/TaxationBundle/Resources/config/services.xml
| Related tickets | fixes #10582
> Move Taxation core service from TaxationBundle to CoreBundle

- tests/Controller/CheckoutAddressingApiTest.php
> [Checkout] Add missing unit test for using deprecated different billing address flag

- UPGRADE-1.7.md
Ref. https://github.com/Sylius/SyliusDemo/pull/119
> [Maintenance] Mention about SonataCore removal in UPGRADE.md

- docs/_themes/sylius_rtd_theme/layout.html
> [Docs] Fix docs build

- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_addresses.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_addresses.html.twig
| Related tickets | related with #11033 
> [Address] Change addresses order

- docs/components_and_bundles/bundles/SyliusResourceBundle/create_resource.rst
> [Docs] Update resource documentation

- UPGRADE-1.7.md
- package.json
- src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-chart.js
- src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_chart.html.twig
- src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/index.html.twig
- yarn.lock
> Add dashboard chart

- docs/customization/validation.rst
Fixed typo in services comment
| Branch?         | 1.6 or master 
> Fixed typo in services comment

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
> [Fixture] Extend fixtures

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
> [Fixture] Add missing euro

- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/UiBundle/Resources/views/Block/_include.html.twig
| Related tickets | related to #10997, introduced in #11059
> Replace "_include.html.twig" template event blocks with a simpler solution

- UPGRADE-1.7.md
> [Checkout] Add note to UPGRADE file about switching billing and shipping addresses

- features/checkout/ability_to_checkout_as_guest_with_a_registered_email.feature
> [Behat] Fix missing Behat step

- src/Sylius/Behat/Page/Shop/Account/ChangePasswordPage.php
- src/Sylius/Behat/Page/Shop/Account/ChangePasswordPageInterface.php
- src/Sylius/Behat/Page/Shop/Account/ProfileUpdatePage.php
- src/Sylius/Behat/Page/Shop/Account/ProfileUpdatePageInterface.php
- src/Sylius/Behat/Page/Shop/Account/VerificationPage.php
- src/Sylius/Behat/Page/Shop/Account/VerificationPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/changePassword.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/profileUpdate.html.twig
> [Behats] Rework password, profile update, change password, pages

- composer.json
> [Composer] Add conflicts to fix build for Symfony 3.4

- composer.json
- features/promotion/managing_coupons/coupon_generate_validation.feature
- features/promotion/managing_coupons/generating_coupon.feature
- src/Sylius/Bundle/PromotionBundle/Resources/config/validation/PromotionCouponGeneratorInstruction.xml
- src/Sylius/Component/Promotion/Generator/PercentageGenerationPolicy.php
- src/Sylius/Component/Promotion/spec/Generator/PercentageGenerationPolicySpec.php
| Related tickets | fixes #10912, based on #11064 and #11097
> [Promotion] Generating long coupons

- etc/travis/suites/application/script.sh
- etc/travis/suites/application/script/test-doctrine-migrations
| Branch?         | master (1.7)
| Bug fix?        | yes (CI only)
> Fix testing migrations

- src/Sylius/Bundle/CoreBundle/Fixture/Factory/OrderExampleFactory.php
- src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/custom_fixtures.yaml
> [Fixtures] Fulfill 60% orders fixtures

- src/Sylius/Behat/Context/Ui/Shop/CartContext.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_coupon.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_header.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_item.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_items.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_totals.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_update.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/_widget.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_info.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_mainImage.html.twig
> [Behats] Cart summary page - test attributes added

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/custom_fixtures.yaml
> [Fixtures] Change order for orders

- features/product/adding_product_reviews/adding_product_review_as_a_customer.feature
- features/product/adding_product_reviews/adding_product_review_as_a_guest.feature
- features/product/adding_product_reviews/review_validation.feature
- src/Sylius/Behat/Context/Ui/Shop/ProductReviewContext.php
- src/Sylius/Behat/Page/Shop/ProductReview/CreatePage.php
- src/Sylius/Behat/Page/Shop/ProductReview/CreatePageInterface.php
- src/Sylius/Behat/Page/Shop/ProductReview/IndexPage.php
- src/Sylius/Behat/Page/Shop/ProductReview/IndexPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/_form.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/create.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/index.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
> [Behat] Rework testing product reviews to use test attributes

- src/Sylius/Behat/Page/Shop/Account/Order/IndexPage.php
- src/Sylius/Behat/Page/Shop/Account/Order/IndexPageInterface.php
- src/Sylius/Behat/Page/Shop/Account/Order/ShowPage.php
- src/Sylius/Behat/Page/Shop/Account/Order/ShowPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Show/_breadcrumb.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/PaymentState/orderPaymentState.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Label/ShipmentState/orderShipmentState.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_payments.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/_shipments.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
> [Behat] Rework testing customer orders to use test attributes

- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Page/Shop/Account/RegisterPage.php
- src/Sylius/Behat/Page/Shop/Account/RegisterPageInterface.php
- src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_item.html.twig
> [Behat] Add attributes to registration page and fix summary page.

- src/Sylius/Behat/Page/Shop/Account/AddressBook/CreatePage.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/CreatePageInterface.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPage.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/IndexPageInterface.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePage.php
- src/Sylius/Behat/Page/Shop/Account/AddressBook/UpdatePageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_defaultAddress.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_defaultAddressForm.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_item.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/create.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/index.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/update.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_address.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_countryCode.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/_address.html.twig
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/buttons.html.twig
> [Behats] Rework address book tests

- src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
- src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ShopBillingData.orm.xml
- src/Sylius/Component/Core/Model/ShopBillingData.php
- src/Sylius/Component/Core/Model/ShopBillingDataInterface.php
| Related tickets | fixes #10563, replaces #10986
> Make ShopBillingData a resource

- features/admin/dashboard.feature
- features/admin/dashboard_per_channel.feature
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/_statistics.html.twig
- src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
- src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
- src/Sylius/Component/Core/Dashboard/DashboardStatisticsProvider.php
- src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
- src/Sylius/Component/Core/spec/Dashboard/DashboardStatisticsProviderSpec.php
> [Dashboard] Sales on dashboard updated

- src/Sylius/Behat/Page/Shop/Account/DashboardPage.php
- src/Sylius/Behat/Page/Shop/Account/DashboardPageInterface.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/dashboard.html.twig
> [Behats] Rework behat attributes for Shop/Account/DashboardPage

- docs/contributing/documentation/overview.rst
After problems with travis build on #11047.
> [Docs] Sphinx instalation guide 

- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
> Template events minor fix for Shop/Cart

- docs/cookbook/deployment/map.rst.inc
- docs/cookbook/deployment/symfonycloud.rst
- docs/cookbook/index.rst
Some customers asked us some basic configuration to deploy Sylius projects to SymfonyCloud, let 's make this available to everyone 😃
> Add documentation to deploy Sylius to SymfonyCloud

- src/Sylius/Bundle/UiBundle/Resources/private/js/app.js
> Disable clicked button

- docs/contributing/documentation/overview.rst
> [Docs] Improve installation steps

- docs/book/installation/sylius_plus_installation.rst
> [Docs] Mention Minimum stability in plus installation

- composer.json
- symfony.lock
| Related tickets | related to #10928 
> Update Mink-related libraries to allow for Symfony 5

- src/Sylius/Bundle/ShopBundle/Resources/views/Product/_info.html.twig
> Add link to product detail page

- src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePage.php
- src/Sylius/Behat/Page/Shop/Checkout/CompletePageInterface.php
- src/Sylius/Behat/Page/Shop/Product/IndexPage.php
- src/Sylius/Behat/Page/Shop/Product/ShowPage.php
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_addressBookSelect.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_login.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_item.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_shipping.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Common/Order/Table/_totals.html.twig
Originally #11140 by @AdamKasp (couldn't be reopened).
> [Behat] Fix missing html attributes coverage

- features/product/managing_product_options/product_option_validation.feature
- features/product/managing_product_options/sorting_product_options_by_position.feature
- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Context/Api/Admin/ManagingProductOptionsContext.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml
| Related tickets | continuation of https://github.com/Sylius/Sylius/pull/11144
- production option name validation
- default sorting of product options
> [API] Product options vol.2

- features/taxation/managing_tax_categories/adding_tax_category.feature
- features/taxation/managing_tax_categories/deleting_tax_category.feature
- features/taxation/managing_tax_categories/editing_tax_category.feature
- features/taxation/managing_tax_categories/tax_category_unique_code_validation.feature
- features/taxation/managing_tax_categories/tax_category_validation.feature
- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Context/Api/Admin/ManagingTaxCategoriesContext.php
- src/Sylius/Behat/Context/Api/Admin/NotificationContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingTaxCategoriesContext.php
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/taxation/managing_tax_categories.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxCategory.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/TaxCategory.xml
todo: bulk delete (i prepared contexts for this functionality but for now it doesn't work by api)
> [API][Behat] configure tax categories as API resource with tests

- features/product/managing_product_attributes/text_product_attribute_validation.feature
> [Behat][ProductAttribute] Remove unnecessary step

- docs/conf.py
Remove deprecated dependency : https://github.com/fabpot/sphinx-php/compare/v1.0.13...master
> [Docs] Remove sensio.sphinx.refinclude

- docs/plugin-development-guide/implementation.rst
For a long time already, we provide all entities [overridden in Sylius-Standard](https://github.com/Sylius/Sylius-Standard/tree/master/src/Entity). This approach enforces annotations mapping by default but allows Sylius to use multiple plugins extending the same entity at the same time. 
We should definitely recommend this approach in our **Plugin Development Guide**.
> [Docs] Recommend trait usage in Plugin Development Guide

- docs/book/customers/adminuser.rst
- docs/book/installation/sylius_plus_installation.rst
> [Plus Docs] Installation guide improvement and Administrator Roles

- docs/bdd/basic-usage.rst
> [missing return] Update basic-usage

- src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php
> [Behat][Admin] Fix step with checking number of orders in the list

- docs/bdd/basic-usage.rst
> Update basic-usage.rst with return Typography

- features/shipping/managing_shipping_categories/adding_shipping_category.feature
- features/shipping/managing_shipping_categories/browsing_shipping_categories.feature
- features/shipping/managing_shipping_categories/deleting_shipping_category.feature
- features/shipping/managing_shipping_categories/editing_shipping_category.feature
- features/shipping/managing_shipping_categories/shipping_category_unique_code_validation.feature
- features/shipping/managing_shipping_categories/shipping_category_validation.feature
- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Context/Api/Admin/ManagingProductOptionsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingCategoriesContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingTaxCategoriesContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingShippingCategoriesContext.php
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/shipping/managing_shipping_categories.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingCategory.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ShippingCategory.xml
`features/shipping/managing_shipping_categories/deleting_multiple_shipping_categories.feature` - waiting for edit concept
> [Api] Shipping categories create index update and delete

- features/user/managing_customer_groups/adding_customer_group.feature
- features/user/managing_customer_groups/browsing_customer_groups.feature
- features/user/managing_customer_groups/customer_group_unique_code_validation.feature
- features/user/managing_customer_groups/customer_group_validation.feature
- features/user/managing_customer_groups/deleting_customer_group.feature
- features/user/managing_customer_groups/editing_customer_group.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingCustomerGroupsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingCustomerGroupsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/user/managing_customer_groups.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CustomerGroup.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/CustomerGroup.xml
> [API] [Customer group] Api customers groups

- docs/book/architecture/emails.rst
- docs/book/customers/map.rst.inc
- docs/book/index.rst
- docs/book/installation/map.rst.inc
- docs/book/introduction/introduction.rst
- docs/book/orders/map.rst.inc
- docs/book/orders/returns.rst
- docs/book/products/map.rst.inc
- docs/book/products/multi_source_inventory.rst
- docs/cookbook/index.rst
- docs/cookbook/inventory/custom-inventory-sources-filter.rst
- docs/cookbook/inventory/map.rst.inc
| Doc fix?        | yes - broken links for The Book
| Related tickets | Part 2 of #11054 
> [Documentation] Sylius Plus docs part 2; including fixes to links

- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipment.html.twig
> [Order] add margin around resent shipment button

- README.md
> Sylius Plus feature scope update

- docs/book/customers/admin_user.rst
- docs/book/customers/index.rst
- docs/book/customers/map.rst.inc
- docs/book/index.rst
> [Docs][Plus] Add docs about administrators per channel

- features/product/managing_product_attributes/text_product_attribute_validation.feature
| Related tickets | continues #11166 
> [Maintenance] Remove uneeded step

- docs/book/customers/admin_user.rst
| Related tickets | associated with #11182 
> [Docs][Plus] Update docs about admin user fixtures

- src/Sylius/Bundle/AdminBundle/Resources/views/Shipment/show.html.twig
> [Admin][Shipment] Add back button on shipment show page

- src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/cap.yaml
This isn't a "casquette", it's a "bonnet" 😅
> Fixtures: fix French translation of cap

- src/Sylius/Behat/Context/Api/Admin/ManagingTaxCategoriesContext.php
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
> [API] Minor fixes after tax categories api configured

- src/Sylius/Bundle/AdminBundle/Resources/views/Product/_showInShopButton.html.twig
| Branch?         | 1.6 or master 
This is just a small UX improvement, it is much better to open the preview in new tab
> Opening show in the store in new tab from admin

- src/Sylius/Behat/Resources/config/suites/api/currency/managing_currencies.yml
- src/Sylius/Behat/Resources/config/suites/api/product/managing_product_variants.yml
- src/Sylius/Behat/Resources/config/suites/api/shipping/managing_shipping_categories.yml
- src/Sylius/Behat/Resources/config/suites/api/taxation/managing_tax_categories.yml
- src/Sylius/Behat/Resources/config/suites/api/taxon/managing_taxons.yml
- src/Sylius/Behat/Resources/config/suites/api/user/managing_customer_groups.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CustomerGroup.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionTranslation.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionValue.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingCategory.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxCategory.xml
> [API] Resources parameters in configuration

- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
> [Api] Temporarily hide customer and product collection operations

- features/currency/managing_exchange_rates/filtering_exchange_rates_by_currency.feature
- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Context/Api/Admin/ManagingExchangeRatesContext.php
- src/Sylius/Behat/Context/Transform/ExchangeRateContext.php
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/services/contexts/transform.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/currency/managing_exchange_rates.yml
- src/Sylius/Bundle/ApiBundle/Filters/ExchangeRateFilter.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ExchangeRate.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/filters.xml
This PR based on https://github.com/Sylius/Sylius/pull/11178
> [API] [ExchangeRate] Add currency filter

- docs/book/installation/installation.rst
- docs/getting-started-with-sylius/installation.rst
> [Docs] [Installation] Update latest stable version

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/documentation-issue.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/security-issue.md
- .github/ISSUE_TEMPLATE/support-question.md
- .github/ISSUE_TEMPLATE/translations.md
| Related tickets | Closes #11205
I've recommited this PR to fix file name:
> Add translations issue template

- src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml
| Branch?         | 1.7 or master
> Rename to a more explicit word

- composer.json
- features/payment/managing_payments/filtering_payments_by_state.feature
- features/payment/managing_payments/managing_of_payment_status.feature
- phpspec.yml.dist
- src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
- src/Sylius/Behat/Context/Setup/OrderContext.php
- src/Sylius/Behat/Context/Transform/OrderContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/suites/api/payment/managing_payments.yml
- src/Sylius/Bundle/ApiBundle/Applicator/PaymentStateMachineTransitionApplicator.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
- src/Sylius/Bundle/ApiBundle/spec/Applicator/PaymentStateMachineTransitionApplicatorSpec.php
> [API][Payment] Managing states and filtering by states

- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
- src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
> Use events fully for layout css and js

- src/Sylius/Bundle/AdminBundle/Resources/views/Security/login.html.twig
| Branch?         | 1.7 or master
> Use the sylius_ui for css and js on admin login screen

- src/Sylius/Behat/Context/Ui/Admin/ManagingShipmentsContext.php
> [Minor] [Behat] Typo fix

- features/payment/managing_payments/filtering_payments_by_channel.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Order.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
> [API][Payment] Implement filtering payments by channel feature

- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Client/Request.php
- src/Sylius/Behat/Client/RequestInterface.php
- src/Sylius/Behat/Context/Api/Admin/ManagingExchangeRatesContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
> [API] Refactor ApiPlatformClient ver.2

- src/Sylius/Behat/Context/Api/Admin/ManagingCurrenciesContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingCustomerGroupsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingExchangeRatesContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingProductOptionsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingProductReviewsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingCategoriesContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingTaxCategoriesContext.php
| Related tickets | fixes https://github.com/Sylius/Sylius/pull/11210#discussion_r392148395
> [API][Behat] Add comment to notification assertion

- src/Sylius/Behat/Context/Api/Admin/ManagingCurrenciesContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingCustomerGroupsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingExchangeRatesContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingProductOptionsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingProductReviewsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingCategoriesContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingTaxCategoriesContext.php
| Related tickets | after https://github.com/Sylius/Sylius/pull/11220
> [API][Behat] Minor contexts refactor

- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CustomerGroup.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ExchangeRate.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PaymentMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionTranslation.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionValue.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingCategory.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/TaxCategory.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Customer.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/CustomerGroup.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ExchangeRate.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Order.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Payment.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/PaymentMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Product.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOption.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionTranslation.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionValue.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionValueTranslation.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductReview.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ShippingCategory.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/TaxCategory.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
> [API] CS fixes in configuration of api resources and serializer

- features/shipping/managing_shipments/browsing_shipments.feature
- features/shipping/managing_shipments/browsing_shipments_from_multiple_channels.feature
- src/Sylius/Behat/Client/ResponseChecker.php
- src/Sylius/Behat/Client/ResponseCheckerInterface.php
- src/Sylius/Behat/Context/Api/Admin/ManagingShipmentsContext.php
- src/Sylius/Behat/Context/Transform/OrderContext.php
- src/Sylius/Behat/Resources/config/services/api.xml
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/shipping/managing_shipments.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Channel.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Shipment.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShipmentUnit.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Channel.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Order.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Shipment.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ShipmentUnit.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ShippingMethod.xml
| Branch?         | API
| Related tickets | replace #11208
> [API][Shipments] Browsing shipments

- features/shipping/managing_shipments/filtering_shipments_by_channel.feature
- features/shipping/managing_shipments/filtering_shipments_by_state.feature
- features/shipping/managing_shipments/shipping_a_shipment_from_shipment_list.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingShipmentsContext.php
- src/Sylius/Behat/Resources/config/suites/api/shipping/managing_shipments.yml
- src/Sylius/Bundle/ApiBundle/Applicator/ShipmentStateMachineTransitionApplicator.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Shipment.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShipmentUnit.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
- src/Sylius/Bundle/ApiBundle/spec/Applicator/ShipmentStateMachineTransitionApplicatorSpec.php
TODO:
cover transition with the provided tracking code
> [Api] Shipment filtering and State machine without tracking code

- features/user/managing_administrators/browsing_administrator.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingAdministratorsContext.php
- src/Sylius/Behat/Context/Setup/AdminUserContext.php
- src/Sylius/Behat/Resources/config/services/api.xml
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/user/managing_administrators.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AdminUser.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/AdminUser.xml
> [API][Administrator] Implement browsing administrators feature

- features/user/managing_administrators/adding_administrator.feature
- features/user/managing_administrators/administrator_unique_email_and_name_validation.feature
- features/user/managing_administrators/administrator_validation.feature
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Context/Api/Admin/ManagingAdministratorsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingAdministratorsContext.php
- src/Sylius/Behat/Resources/config/suites/api/user/managing_administrators.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AdminUser.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/AdminUser.xml
> [API][Administrator] Implement adding administrators features

- features/shipping/managing_shipping_methods/browsing_shipping_methods.feature
- features/shipping/managing_shipping_methods/deleting_shipping_method.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Behat/Resources/config/services/api.xml
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/shipping/managing_shipping_methods.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ShippingMethod.xml
> [API] Browsing and deleting shipping methods

- config/packages/api_platform.yaml
- features/order/managing_orders/browsing_orders.feature
- features/order/managing_orders/cancelling_order.feature
- features/order/managing_orders/cancelling_order_with_promotion.feature
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php
- src/Sylius/Behat/Resources/config/services/api.xml
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/order/managing_orders.yml
- src/Sylius/Bundle/ApiBundle/Applicator/OrderStateMachineTransitionApplicator.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Order.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/spec/Applicator/OrderStateMachineTransitionApplicatorSpec.php
> [API][Order] Orders browsing, cancelling and cancelling with promotion

- config/packages/api_platform.yaml
- features/user/managing_administrators/deleting_administrators.feature
- features/user/managing_administrators/editing_administrator.feature
- src/Sylius/Behat/Context/Api/Admin/LoginContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingAdministratorsContext.php
- src/Sylius/Behat/Context/Transform/AdminUserContext.php
- src/Sylius/Behat/Resources/config/services/contexts/transform.xml
- src/Sylius/Behat/Resources/config/suites/api/user/managing_administrators.yml
- src/Sylius/Bundle/ApiBundle/DataPersister/AdminUserDataPersister.php
- src/Sylius/Bundle/ApiBundle/Exception/CannotRemoveCurrentlyLoggedInUser.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AdminUser.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/AdminUser.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/spec/DataPersister/AdminUserDataPersisterSpec.php
> [API][Administrator] Implement deleting and editing administrators features

- src/Sylius/Behat/Resources/config/suites/api/shipping/managing_shipments.yml
- src/Sylius/Bundle/ApiBundle/Applicator/ShipmentStateMachineTransitionApplicator.php
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/spec/Applicator/ShipmentStateMachineTransitionApplicatorSpec.php
> [API][Shipment] Send email after shipment ship

- config/packages/api_platform.yaml
- src/Sylius/Behat/Resources/config/services/api.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml
> [API] Change operation path resolver from underscore to dash resolver

- features/shipping/managing_shipping_methods/adding_shipping_method.feature
- features/shipping/managing_shipping_methods/shipping_method_code_validation.feature
- features/shipping/managing_shipping_methods/shipping_method_flat_rate_per_shipment_validation.feature
- features/shipping/managing_shipping_methods/shipping_method_flat_rate_per_unit_validation.feature
- features/shipping/managing_shipping_methods/shipping_method_unique_code_validation.feature
- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Client/ResponseChecker.php
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Behat/Context/Transform/ShippingCalculatorContext.php
- src/Sylius/Behat/Context/Transform/ZoneContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/services/contexts/transform.xml
- src/Sylius/Behat/Resources/config/suites/api/shipping/managing_shipping_methods.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethodTranslation.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Zone.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ShippingMethodTranslation.xml
> [API] Adding shipping methods

- features/user/managing_administrators/adding_avatar_to_administrator.feature
- features/user/managing_administrators/changing_administrator_avatar.feature
- features/user/managing_administrators/removing_administrator_avatar.feature
- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Client/Request.php
- src/Sylius/Behat/Client/RequestInterface.php
- src/Sylius/Behat/Context/Api/Admin/ManagingAdministratorsContext.php
- src/Sylius/Behat/Resources/config/services/api.xml
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Bundle/ApiBundle/Controller/UploadAvatarImageAction.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AdminUser.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AvatarImage.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/AdminUser.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/AvatarImage.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php
| Related tickets | part of #11250
> [API][Administrator] Implement managing avatar features

- src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
> [API][Product] Add fixes for addTheOptions

- features/shipping/managing_shipping_methods/editing_shipping_method.feature
- features/shipping/managing_shipping_methods/shipping_method_unique_code_validation.feature
- features/shipping/managing_shipping_methods/shipping_method_validation.feature
- features/shipping/managing_shipping_methods/toggling_shipping_method.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ShippingMethodTranslation.xml
| Related tickets | Part of #11250 
> [API] Editing and validation of shipping methods

- src/Sylius/Behat/Context/Api/Admin/ManagingShippingCategoriesContext.php
> [Minor] Improve ShippingCategory test

- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
> [Api][Product] Fix default product sorting

- config/packages/api_platform.yaml
- features/shipping/managing_shipping_methods/preventing_deletion_of_used_shipping_method.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Behat/Resources/config/suites/api/shipping/managing_shipping_methods.yml
- src/Sylius/Bundle/ApiBundle/DataPersister/ShippingMethodDataPersister.php
- src/Sylius/Bundle/ApiBundle/Exception/ShippingMethodCannotBeRemoved.php
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
> [API] Protect shipping method from removal when in use

- features/shipping/managing_shipping_methods/sorting_shipping_methods_by_name_or_code.feature
- features/shipping/managing_shipping_methods/sorting_shipping_methods_by_position.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
| Related tickets | part of https://github.com/Sylius/Sylius/issues/11250
> [API] Sorting shipping method by code and position

- features/shipping/managing_shipping_methods/archiving_shipping_methods.feature
- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Client/Request.php
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Bundle/ApiBundle/Controller/ArchiveShippingMethodAction.php
- src/Sylius/Bundle/ApiBundle/DataPersister/ShippingMethodDataPersister.php
- src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/HideArchivedShippingMethodExtension.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
> [API] Hide archived shipping methods

- features/shipping/managing_shipping_methods/sorting_shipping_methods_by_name_or_code.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Bundle/ApiBundle/Filters/TranslationOrderFilter.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
| Related tickets | part of #11250, the continuation of #11267
> [API] Sorting shipping methods by name

- src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Behat/Resources/config/suites/api/shipping/managing_shipping_methods.yml
Something went wrong with merge 💃
> Fix build with API Behat

- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Client/Request.php
- src/Sylius/Behat/Client/RequestInterface.php
- src/Sylius/Behat/Context/Api/Admin/ManagingAdministratorsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
| Related tickets | after #11255
> [API][Administrator] Refactor upload action in api client + minor fixes

- features/shipping/managing_shipping_methods/archiving_shipping_methods.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Bundle/ApiBundle/Applicator/ArchivizationShippingMethodApplicator.php
- src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/HideArchivedShippingMethodExtension.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
> [API] Archivization toggling and filtration

- features/locale/managing_locales/adding_locale.feature
- features/locale/managing_locales/locale_unique_code_validation.feature
- features/locale/managing_locales/locale_validation.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingLocalesContext.php
- src/Sylius/Behat/Resources/config/services/api.xml
- src/Sylius/Behat/Resources/config/services/contexts/api.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/locale/managing_locales.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Locale.xml
| Related tickets | partially #11250 
Locales
- All the features from features/locale/managing_locales
- 2 scenarios / 3 files
- Create an index action only (show may be required as well)
> [API] add locale to Api Platform

- config/packages/_sylius.yaml
- src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
> [API] Move API Platform configuration to ApiBundle

- src/Sylius/Behat/Page/Shop/Account/Order/IndexPage.php
- src/Sylius/Bundle/UiBundle/Resources/views/Macro/buttons.html.twig
Apply Behat Rework selector to missing elements of Shop > Product  > Show
> [Behat] Rework Shop > Product  > Show

- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Client/Request.php
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Bundle/ApiBundle/Applicator/ArchivizationShippingMethodApplicator.php
- src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/HideArchivedShippingMethodExtension.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
| Related tickets | related with #11266 and #11269, part of #11250
> [API][Shipping Method] Improvement after PR preview

- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Swagger/DocumentationNormalizer.php
> [API] Add endpoint to Swagger to retrieve a JWT token

- config/packages/framework.yaml
- src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
> [API] Move serializer configuration to ApiBundle

- UPGRADE-1.8.md
> [API] Update UPGRADE-1.8 file after adding ApiBundle

- UPGRADE-1.8.md
| Bug fix?        | yes(?)
| Related tickets | mentioned in #11288
> Fixed hardcoded route &prefix in UPGRADE-1.8 document

- features/product/managing_products/sorting_products.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
> [API][Product] Add sorting for products by name

- composer.json
- src/Sylius/Bundle/ApiBundle/DataPersister/AdminUserDataPersister.php
- src/Sylius/Bundle/CoreBundle/Context/CustomerContext.php
- src/Sylius/Bundle/UserBundle/EventListener/UserDeleteListener.php
- symfony.lock
> [Psalm] Add symfony/polyfill-php80 to fix build

- src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_header.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Show/_header.html.twig
- src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Complete/_header.html.twig
| Related tickets | Fixes #11265
Thanks to @nayluge for initial work
> [ShopBundle] Fix the checkout page

- UPGRADE-1.8.md
- config/packages/security.yaml
- features/account/signing_in.feature
- features/account/signing_in_validation.feature
- src/Sylius/Behat/Client/ApiPlatformSecurityClient.php
- src/Sylius/Behat/Context/Api/Shop/LoginContext.php
- src/Sylius/Behat/Resources/config/services/api.xml
- src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
- src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/account/login.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/routing.yml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Swagger/AdminAuthenticationTokenDocumentationNormalizer.php
- src/Sylius/Bundle/ApiBundle/Swagger/ShopAuthenticationTokenDocumentationNormalizer.php
| Related tickets | partially #11250 
> [API][Shop] Add customer login

- docs/book/plugins/sylius-store.rst
> [Docs] Require tagged plugins for Sylius Store

- composer.json
- symfony.lock
Already introduced for `master` in https://github.com/Sylius/Sylius/pull/11298
> Install symfony/polyfill-php80 to fix the psalm build

- src/Sylius/Bundle/CoreBundle/Context/CustomerContext.php
- src/Sylius/Bundle/UserBundle/EventListener/UserDeleteListener.php
Introduced for `master` in https://github.com/Sylius/Sylius/pull/11298
> [Psalm] Fix build on 1.7 as well

- features/homepage/viewing_latest_products.feature
- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Client/Request.php
- src/Sylius/Behat/Client/RequestInterface.php
- src/Sylius/Behat/Context/Api/Shop/HomePageContext.php
- src/Sylius/Behat/Context/Api/Shop/HomepageContext.php
- src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
- src/Sylius/Behat/Resources/config/suites.yml
- src/Sylius/Behat/Resources/config/suites/api/homepage/viewing_products.yml
- src/Sylius/Bundle/ApiBundle/DataProvider/LatestProductCollectionDataProvider.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Product.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductImage.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductTranslation.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/contextBuilders.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/context_builders.xml
- src/Sylius/Bundle/ApiBundle/Serializer/ContextKeys.php
- src/Sylius/Bundle/ApiBundle/SerializerContextBuilder/ChannelContextBuilder.php
- src/Sylius/Bundle/ApiBundle/SerializerContextBuilder/LocaleContextBuilder.php
- src/Sylius/Bundle/ApiBundle/spec/DataProvider/LatestProductCollectionDataProviderSpec.php
- src/Sylius/Bundle/ApiBundle/spec/SerializerContextBuilder/ChannelContextBuilderSpec.php
- src/Sylius/Bundle/ApiBundle/spec/SerializerContextBuilder/LocaleContextBuilderSpec.php
> [API][Homepage] Latest products

- features/product/managing_products/sorting_products.feature
- src/Sylius/Behat/Client/ApiClientInterface.php
- src/Sylius/Behat/Client/ApiPlatformClient.php
- src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Context/Api/Admin/ManagingShippingMethodsContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingAdministratorLocalesContext.php
- src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php
- src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/suites/ui/product/managing_products.yml
- src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml
- src/Sylius/Bundle/ApiBundle/Filters/TranslationOrderNameFilter.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
> [API][Product] Product sorting by name

- src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
| Related tickets | closes #11313 (fixes the underlying issue)
> Fix BC breaks introduced with new template event system

- features/homepage/viewing_only_taxons_from_menu_taxon.feature
- src/Sylius/Behat/Context/Api/Shop/HomepageContext.php
- src/Sylius/Behat/Context/Ui/Shop/HomepageContext.php
- src/Sylius/Behat/Resources/config/services/api.xml
- src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
- src/Sylius/Behat/Resources/config/suites/api/homepage/viewing_products.yml
- src/Sylius/Bundle/ApiBundle/DataProvider/TaxonFromChannelMenuTaxonCollectionDataProvider.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Taxon.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/context_builders.xml
- src/Sylius/Bundle/ApiBundle/spec/DataProvider/LatestProductCollectionDataProviderSpec.php
- src/Sylius/Bundle/ApiBundle/spec/DataProvider/TaxonFromChannelMenuTaxonCollectionDataProviderSpec.php
- src/Sylius/Bundle/ApiBundle/spec/SerializerContextBuilder/ChannelContextBuilderSpec.php
- src/Sylius/Bundle/ApiBundle/spec/SerializerContextBuilder/LocaleContextBuilderSpec.php
> [Api][Homepage] menu taxons

- features/product/managing_products/editing_product_slug.feature
- src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php
- src/Sylius/Bundle/ApiBundle/EventSubscriber/ProductSlugEventSubscriber.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductTranslation.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/event_subscribers.xml
- src/Sylius/Bundle/ApiBundle/spec/EventSubscriber/ProductSlugEventSubscriberSpec.php
| Related tickets | partially #11250 
> [API][Product] Add subscriber for generating slug automatically

- src/Sylius/Component/User/Model/User.php
> Fix Psalm docblock marked as a regular one

- src/Sylius/Bundle/ApiBundle/Applicator/ArchivingShippingMethodApplicator.php
- src/Sylius/Bundle/ApiBundle/EventSubscriber/ProductSlugEventSubscriber.php
- src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/applicators.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/data_persisters.xml
- src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml
| Related tickets | fixes for review #11318 
> [API] Extract services configs + fixes to product slug event subscriber

- src/Sylius/Bundle/ApiBundle/Doctrine/Filters/ExchangeRateFilter.php
- src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
> [Minor] Move doctrine filters to doctrine folder in api bundle

- composer.json
Related to #10928 - unblocks Behat and related packages.
> Try out Behat packages supporting Symfony 5

- src/Sylius/Bundle/ApiBundle/Applicator/ArchivingShippingMethodApplicator.php
- src/Sylius/Bundle/ApiBundle/Applicator/ArchivingShippingMethodApplicatorInterface.php
- src/Sylius/Bundle/ApiBundle/Applicator/OrderStateMachineTransitionApplicator.php
- src/Sylius/Bundle/ApiBundle/Applicator/OrderStateMachineTransitionApplicatorInterface.php
- src/Sylius/Bundle/ApiBundle/Applicator/PaymentStateMachineTransitionApplicator.php
- src/Sylius/Bundle/ApiBundle/Applicator/PaymentStateMachineTransitionApplicatorInterface.php
- src/Sylius/Bundle/ApiBundle/Applicator/ProductReviewStateMachineTransitionApplicator.php
- src/Sylius/Bundle/ApiBundle/Applicator/ProductReviewStateMachineTransitionApplicatorInterface.php
- src/Sylius/Bundle/ApiBundle/Applicator/ShipmentStateMachineTransitionApplicator.php
- src/Sylius/Bundle/ApiBundle/Applicator/ShipmentStateMachineTransitionApplicatorInterface.php
> [Minor][API] Add interfaces to applicators

- src/Sylius/Behat/Resources/config/services/api.xml
- src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml
- src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
To be consistent with the rest of services name
> [API] fix typo in services

- src/Sylius/Component/Core/Model/Taxon.php
- src/Sylius/Component/Core/spec/Model/TaxonSpec.php
| Related tickets | fixes #10797 
Is this good for you?
Do you think I should do the same for all resources (as said in the issue commands)?
> Make taxon comparable

- features/locale/redirect_to_default_locale.feature
- src/Sylius/Behat/Context/Ui/Shop/LocaleContext.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Bundle/ShopBundle/EventListener/NonChannelLocaleListener.php
- src/Sylius/Bundle/ShopBundle/Resources/config/services/integrations/locale/url.xml
- src/Sylius/Bundle/ShopBundle/spec/EventListener/NonChannelLocaleListenerSpec.php
| Branch?         | 1.5 and after
| Related tickets | fixes #10763 
Redirect to homepage with default locale if locale requested not present in provider.
> redirect to default locale

- features/admin/impersonating_customers.feature
- src/Sylius/Behat/Context/Ui/Admin/ImpersonatingCustomersContext.php
- src/Sylius/Behat/Page/Admin/Administrator/ImpersonateUserPage.php
- src/Sylius/Behat/Page/Admin/Administrator/ImpersonateUserPageInterface.php
- src/Sylius/Behat/Resources/config/services/contexts/ui.xml
- src/Sylius/Behat/Resources/config/services/pages/admin.xml
- src/Sylius/Behat/Resources/config/services/pages/admin/impersonate_user.xml
- src/Sylius/Bundle/AdminBundle/Controller/ImpersonateUserController.php
| Related tickets | fixes #10886 
That solve the issue, but I don't know how to test it with Behat.
> impersonate user in new tab

- src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php
| Related tickets | replaces #10689
> Fix: Check PropertyPath value for add error to form
