features/checkout/ability_to_confirm_an_order_with_a_promotion_on_shipping.feature, src/Sylius/Component/Core/Promotion/Action/ShippingPercentageDiscountPromotionActionCommand.php
When you create a promotion with a discount on delivery, you cannot submit an order.
**Steps to reproduce**
Create a promotion with "Shipping percentage discount" (set any percents). All orders with applied promotions are unable to finish. After submitting on last step, you will see a "Your order total has been changed, check your order information and confirm it again." message.
=> [Core] Bad reverting of ShippingPercentageDiscount promotion

src/Sylius/Component/Order/Model/OrderItemInterface.php
The previous typing was ok for PHP, but IDE tends to throw an error with this syntax.
=> [Order] Changing function typing

src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PromotionRepository.php
| Related tickets | mentioned in #9882
See #9882 for explanation of what it's partially solving.
=> Hydrate promotion_rules directly on loading active promotions for a channel (1n)

src/Kernel.php
| Related tickets | fixes #9865
It has to be cloned to Sylius-Standard and PluginSkeleton. The behaviour stays the same as in previous versions.
=>  Allow to overwrite a specific config file

src/Sylius/Bundle/OrderBundle/Resources/config/app/state_machine.yml
This callback refers to nothing so when this file is called, it throws an error : `You have requested a non-existent service "sylius.complete_checkout_callback".`, plus this file is never called anywhere. But still useful as a base file for anyone using this bundle as standalone.
| Bug fix?        | not really
=>  [Order] Removing after SM callback

features/checkout/paying_for_order/changing_payment_method_after_order_confirmation_item_quantity.feature, src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutOrderDetailsContext.php, src/Sylius/Behat/Page/Shop/Order/ShowPage.php, src/Sylius/Behat/Page/Shop/Order/ShowPageInterface.php, src/Sylius/Bundle/ShopBundle/Resources/views/Order/_summary.html.twig
| Related tickets | fixes #9862 
Fixing number of items displayed in order summary page
=> #9862 Number of items in order summary page

features/product/managing_products/prevent_deletion_of_purchased_product.feature, src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php, src/Sylius/Behat/Page/Admin/Product/IndexPage.php, src/Sylius/Behat/Page/Admin/Product/IndexPageInterface.php, src/Sylius/Behat/Resources/config/services.xml, src/Sylius/Behat/Resources/config/services/contexts/ui.xml, src/Sylius/Behat/Resources/config/services/pages/admin/product.xml, src/Sylius/Behat/Service/Checker/ImageExistenceChecker.php, src/Sylius/Behat/Service/Checker/ImageExistenceCheckerInterface.php, src/Sylius/Bundle/CoreBundle/EventListener/ImagesRemoveListener.php, src/Sylius/Bundle/CoreBundle/Resources/config/app/parameters.yml, src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml, src/Sylius/Bundle/CoreBundle/Resources/config/test_services.xml, src/Sylius/Bundle/CoreBundle/spec/EventListener/ImagesRemoveListenerSpec.php
The problem was, whenever product deletion failed (for example because the variant is already used in a placed order), images files were still removed. The reason for that was, that the `ImagesRemoveListener` were listening on `postRemove` doctrine event, which is called **even if** flush ends with an error.
I've refactored `ImagesRemoveListener` to listen on both `onFlush` and `postFlush` events. It saves paths from scheduled to remove entities with `ImageInterface` type and removes them with `ImageUploader` and `CacheManager` when the whole transaction passes (is there any BC …
=> Product images deletion fix

docs/_themes/sylius_rtd_theme/layout.html, docs/_themes/sylius_rtd_theme/static/css/sylius-custom.css
=> [Documentation] Add new styles

docs/plugins/creating-plugin.rst
The previous instruction was a little bit misleading. The **repository name** can be easily understood as **the name of the repository on GitHub/Gitlab/etc.**. Thank you @stefandoorn for catching that (as well as for the willingness to fulfill our conventions 😄)
=> Fix plugin naming convention documentation

src/Sylius/Bundle/CoreBundle/Fixture/BookProductFixture.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxonExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/MugProductFixture.php, src/Sylius/Bundle/CoreBundle/Fixture/StickerProductFixture.php, src/Sylius/Bundle/CoreBundle/Fixture/TaxonFixture.php, src/Sylius/Bundle/CoreBundle/Fixture/TshirtProductFixture.php, src/Sylius/Bundle/CoreBundle/Tests/Fixture/TaxonFixtureTest.php, src/Sylius/Bundle/CoreBundle/spec/Fixture/Factory/TaxonExampleFactorySpec.php
| Branch?         | master?
| New feature?    | kind of
| Related tickets | fixes #9645 
With this PR, we can both use:
```
taxon:
options:
custom:
category:
code: category               
name: Category
```
```
taxon:
options:
custom:
category:
code: category
translations:
en_US:
name: Category
slug: category
cs_CZ: 
name: Kategorie
slug: kategorie
```
I've updated core fixtures for an example, but we can keep them as this.
=> Improve taxon fixtures with translations

composer.json, etc/travis/suites/common/before_install.sh, src/Sylius/Bundle/ResourceBundle/composer.json
Recent changes in Symfony 4.1.8 resulted in some unexpected errors in our build. As a quick fix, I propose to exclude this version of Symfony (and some specific packages) and investigate as it should be done in a more proper way.
=> [Hot-fix] Make build great again

composer.json
| Related tickets | related with https://github.com/Sylius/Sylius/pull/9970
As in the previous PR, we need to disable (for now) some specific versions of some specific packages. `"symfony/symfony": "3.4.7 || 4.0.7 || 4.1.8"` does not work anymore, as we don't use `symfony/symfony` since **Sylius 1.3** :)
=> Make build great again (one more time)

docs/book/installation/installation.rst
I've noticed that  here: 
https://docs.sylius.com/en/1.3/book/installation/installation.html#how-to-start-developing-project-structure
it says app/config dir but that does not exist when following those documentation, config folder is correct location.
=> Update book/installation docs with correct config folder

src/Sylius/Bundle/TaxonomyBundle/Form/Type/TaxonAutocompleteChoiceType.php, src/Sylius/Bundle/TaxonomyBundle/Resources/config/serializer/Model.Taxon.yml, src/Sylius/Component/Taxonomy/Model/Taxon.php, src/Sylius/Component/Taxonomy/Model/TaxonInterface.php, src/Sylius/Component/Taxonomy/spec/Model/TaxonSpec.php
| Branch?         | 1.2 (it based on 1.2, but should be merged to master I guess)
| Related tickets | fixes #9899, #8485
Was:
Become:
=> Fix #9899 (main taxon autocomplete drop down now contain full taxon name - with all parents)

docs/customization/form.rst
Overridden twig files are expected in `bundles/` folder instead of `bundle/`  and the `view/` path is obsolete. You also need to copy the original template and include the custom fields.
=> Correcting the documentation about how to customise forms templates

src/Sylius/Bundle/ShopBundle/EventListener/NonChannelLocaleListener.php, src/Sylius/Bundle/ShopBundle/spec/EventListener/NonChannelLocaleListenerSpec.php
| Related tickets | #9925 
Fixed issue with toolbar and profiler breaking whenever you are on a channel without the locale specified in `parameters.locale`.
=> Ignore locale request restriction for profiler and it's toolbar

src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingMethodExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/ShippingMethodFixture.php
| Branch?         | 1.2 
Using fixtures it was impossible to set categories for shipping methods, because because the option in the fixture and the corresponding factory had different names.
=> Repaired shipping method fixture

docs/book/architecture/translations.rst, docs/book/installation/installation.rst, docs/components_and_bundles/bundles/SyliusFixturesBundle/custom_fixture.rst, docs/components_and_bundles/bundles/SyliusFixturesBundle/custom_listener.rst, docs/components_and_bundles/bundles/SyliusGridBundle/custom_action.rst, docs/components_and_bundles/bundles/SyliusGridBundle/custom_field_type.rst, docs/components_and_bundles/bundles/SyliusGridBundle/custom_filter.rst, docs/components_and_bundles/bundles/SyliusGridBundle/your_first_grid.rst, docs/components_and_bundles/bundles/SyliusInventoryBundle/installation.rst, docs/components_and_bundles/bundles/SyliusMailerBundle/configuration.rst, docs/components_and_bundles/bundles/SyliusMailerBundle/your_first_email.rst, docs/components_and_bundles/bundles/SyliusPromotionBundle/installation.rst, docs/components_and_bundles/bundles/SyliusResourceBundle/configuration.rst, docs/components_and_bundles/bundles/SyliusResourceBundle/create_resource.rst, docs/components_and_bundles/bundles/SyliusResourceBundle/forms.rst, docs/components_and_bundles/bundles/SyliusResourceBundle/reference.rst, docs/components_and_bundles/bundles/SyliusResourceBundle/routing.rst, docs/components_and_bundles/bundles/SyliusResourceBundle/update_resource.rst, docs/components_and_bundles/bundles/SyliusShippingBundle/custom_calculators.rst, docs/components_and_bundles/bundles/SyliusTaxationBundle/custom_calculators.rst, docs/components_and_bundles/components/Promotion/basic_usage.rst, docs/cookbook/emails/disabling-order-confirmation-email.rst, docs/cookbook/entities/custom-translatable-model.rst, docs/cookbook/frontend/admin-js-and-css.rst, docs/cookbook/images/images-gridfs.rst, docs/cookbook/images/images-on-entity.rst, docs/customization/factory.rst, docs/customization/grid.rst, docs/customization/model.rst, docs/customization/validation.rst
| Related tickets | fixes #9951
The namespace `AppBundle` is still used in 1.3 docs. Even Symfony 4.x changed it to `App`. Remove or change it.
=> Remove `AppBundle` from docs.

docs/components_and_bundles/bundles/SyliusTaxonomyBundle/installation.rst
It seems gedmo 'sortable' extension required by this bundle. Otherwise it throws an exception
"Integrity constraint violation: 1048 Column 'position' cannot be null"
=> Column 'position' cannot be null

phpstan.neon, src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php, src/Sylius/Bundle/CoreBundle/Routing/Matcher/Dumper/PhpMatcherDumper.php, src/Sylius/Bundle/ResourceBundle/composer.json
| Related tickets | replaces https://github.com/Sylius/Sylius/pull/10014
The previous proposition did not work, although I tried hard :( Happily, I've investigated wich specific class caused these problems - `PhpMatcherDumper` (it was also the reason of problems in Symfony 4.1.8, but different ones).
As a quick fix, I propose overriding this class in Sylius, until these bugs will be resolved in Symfony itself. It can be also a good excuse to bump Symfony version to 4.2, which is (as far as I know) free of these bugs - see https://github.com/Sylius/Sylius/issues/10015.
**Pros:**
- No Symfony version has …
=> [HotFix][BuildFix] Use old PhpMatcherDumper to avoid trailing slash problems

features/account/customer_account/viewing_orders_history/viewing_order_items.feature, features/checkout/placing_an_order_with_different_scopes_for_shipping_and_taxes.feature, features/checkout/skipping_payment_method_step_when_only_one_payment_method_is_available.feature, features/product/adding_product_reviews/adding_product_review_as_a_customer.feature, features/product/adding_product_reviews/adding_product_review_as_a_guest.feature, features/product/adding_product_reviews/review_validation.feature, features/user/managing_customers/being_able_to_create_account_for_existing_customer.feature, src/Sylius/Behat/Page/Shop/ProductReview/CreatePage.php
This is a first PR from (planned, hope it will work :D) series of PR's refactoring our javascript Behat scenarios.
I think we're all aware of the value that Behat brings to us, but also we're all struggling with the unbelievably slow scenarios containing `@javascript` tag, run by Selenium. Just looking a the execution times can be scary:
- no-js scenarios: 11525 steps, ~6m18.29s
- js scenarios: 2413 steps, ~16m45.64s
I think that eventually, we should think about some faster and more reliable tool for testing our js features. On the other way, I have a deep premonition that we can …
=> Behat JS scenarios war vol.1

src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-move-taxon.js
With element(data), I coulnd't move up the last taxon for example because the script was Always sending -1 instead of the real number (position - 1).
=> [Admin] Taxon order : fix element(data) always returns 0

src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php
Makes working on PRs like #10062 easier.
=> Do not require clearing cache when changing ResourceBundle drivers or metadata classes

src/Kernel.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/10055, fixes https://github.com/Sylius/Sylius/issues/10058
It was also done here https://github.com/Sylius/Sylius-Standard/pull/306. Together with [AssociationHydrator v1.1.1](https://github.com/SyliusLabs/AssociationHydrator/releases/tag/v1.1.1) it allows Sylius to run with PHP 7.3. Even though we don't have tests on PHP 7.3 yet (and *right now* we probably don't want to have them to not make build even longer than it is), it would be good to make it possible, as we're not hooked strictly into 7.2.
=> Make Sylius tests not fail on PHP 7.3

src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType/Configuration/SelectAttributeChoicesCollectionType.php, src/Sylius/Bundle/ResourceBundle/test/app/config/routing.yml, src/Sylius/Bundle/ResourceBundle/test/src/Tests/Controller/BookApiTest.php
| Related tickets | related to https://github.com/symfony/symfony/pull/29307
Due to the latest Symfony 4.1.10/3.4.21 release and changes introduced in linked PR, a bug in select attribute type araised 🌤 Apparently, possible to select values in attribute configuration was saved with `TextType` form type, even though `SelectAttributeValueTranslationsType` should be used. It was somehow parsed before, but know it's not possible and this PR fixes this absurdity 🖖
=> Fix select attributes according to recent Symfony form changes

src/Sylius/Bundle/GridBundle/test/app/config/config.yml, src/Sylius/Bundle/ResourceBundle/.gitignore, src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDriver.php, src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/AbstractDoctrineDriver.php, src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrineORMDriver.php, src/Sylius/Bundle/ResourceBundle/phpunit.xml.dist, src/Sylius/Bundle/ResourceBundle/test/app/config/resources.yml, src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/DependencyInjection/AppExtension.php, src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Factory/BookFactory.php, src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Factory/BookFactoryInterface.php, src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Repository/BookRepository.php, src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Repository/BookRepositoryInterface.php, src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Resources/config/services.php, src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Service/FirstAutowiredService.php, src/Sylius/Bundle/ResourceBundle/test/src/AppBundle/Service/SecondAutowiredService.php
This feature is only available when used with Symfony DependencyInjection ^4.2.
TODO:
=> Make possible to autowire services generated by ResourceBundle

src/Sylius/Bundle/CoreBundle/EventListener/ChannelDeletionListener.php
I needed to decorate sylius.repository.channel but this listener constructor prevented me to do it...
=> [CoreBundle] Fix Type in Construct for ChannelDeletionListener

src/Sylius/Bundle/ThemeBundle/Templating/TemplateNameParser.php, src/Sylius/Bundle/ThemeBundle/spec/Templating/TemplateNameParserSpec.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/9654
It's hard to test this change with some functional test in a current tests structure, as it would require to use `SyliusPluginTrait` in test bundle/plugin, but it's in a core bundle :/ I have some idea have to test it properly with a Behat scenario, but I need to spend a few more minutes on that :)
It would be nice if someone could incorporate these changes into their application and see does it work as expected (cc @jacquesbh :)). I've of course done that, but _better safe than sorry_ 🐃 
This change only applies to `1.2` branch, for …
=> [Theme] Allow overriding templates from plugins (1.2.*)

src/Sylius/Bundle/ThemeBundle/Locator/BundleResourceLocator.php, src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/FirstTestTheme/TestPlugin/views/Templating/twigNamespacedBothThemesTemplate.txt.twig, src/Sylius/Bundle/ThemeBundle/Tests/Fixtures/themes/FirstTestTheme/TestPlugin/views/Templating/twigNamespacedVanillaOverriddenThemeTemplate.txt.twig, src/Sylius/Bundle/ThemeBundle/Tests/Functional/TemplatingTest.php, src/Sylius/Bundle/ThemeBundle/spec/Locator/BundleResourceLocatorSpec.php
| Related tickets | fixes (kinda) https://github.com/Sylius/Sylius/issues/9654
This is, of course, a quick fix and quite straight-forward, but it works 😄 And it is still required to use `@SyliusTestPlugin` notation (maybe it's worth to be documented somehow?). This PR fixes the functionality for Sylius `^1.3`, for working fix on `1.2` take a look here: https://github.com/Sylius/Sylius/pull/10082.
Regarding testing it better (as I've also written in fix for `1.2`):
> It's hard to test this change with some functional test in a current tests structure, as it would require to use `SyliusPluginTrait` in …
=> [Theme] Allow overriding templates from plugins (^1.3)

app/migrations/Version20190109091323.php, app/migrations/Version20190109095211.php, features/channel/managing_channels/adding_channel_with_shop_billing_data.feature, features/channel/managing_channels/editing_shop_billing_data_on_channel.feature, src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsBillingDataContext.php, src/Sylius/Behat/Element/Admin/Channel/ShopBillingDataElement.php, src/Sylius/Behat/Element/Admin/Channel/ShopBillingDataElementInterface.php, src/Sylius/Behat/Page/Admin/Channel/UpdatePage.php, src/Sylius/Behat/Page/Admin/Channel/UpdatePageInterface.php, src/Sylius/Behat/Resources/config/services/contexts/ui.xml, src/Sylius/Behat/Resources/config/services/elements.xml, src/Sylius/Behat/Resources/config/services/elements/admin.xml, src/Sylius/Behat/Resources/config/services/elements/shop.xml, src/Sylius/Behat/Resources/config/suites/ui/channel/managing_channels.yml, src/Sylius/Bundle/AdminBundle/Resources/views/Channel/_form.html.twig, src/Sylius/Bundle/CoreBundle/Form/Extension/ChannelTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Type/ShopBillingDataType.php, src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml, src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ShopBillingData.orm.xml, src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml, src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml, src/Sylius/Component/Core/Model/Channel.php, src/Sylius/Component/Core/Model/ChannelInterface.php, src/Sylius/Component/Core/Model/ShopBillingData.php, src/Sylius/Component/Core/Model/ShopBillingDataInterface.php, src/Sylius/Component/Core/spec/Model/ShopBillingDataSpec.php, tests/Responses/Expected/channel/create_validation_fail_response.json, tests/Responses/Expected/channel/update_validation_fail_response.json
| Related tickets | associated with https://github.com/Sylius/RefundPlugin/issues/106, https://github.com/Sylius/InvoicingPlugin/issues/52
During the development of `InvoicingPlugin`, we introduced a concept of shop billing data (set per channel) that is required to be displayed on an invoice. On the other hand, we also should have it in a `RefundPlugin` to generate a credit memo properly.
We considered a few options, but in the end, it's quite a common use case to have such a bunch of data manageable in Admin panel.
=> [Channel] Shop billing data

features/product/managing_products/select_taxons_for_new_product.feature, features/product/managing_products/select_taxons_for_product.feature, src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php, src/Sylius/Behat/Page/Admin/Product/CreateConfigurableProductPage.php, src/Sylius/Behat/Page/Admin/Product/CreateConfigurableProductPageInterface.php, src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPage.php, src/Sylius/Behat/Page/Admin/Product/CreateSimpleProductPageInterface.php
| Branch?         | 1.2 
Was running into this while trying to test for choosing a taxon when creating a new product:
```
Scenario: Creating a product with a custom slug
Given I want to create a new simple product
When I specify its code as "BOARD_MANSION_OF_MADNESS"
And I choose main taxon "Mugs"
Behat\Testwork\Call\Exception\FatalThrowableError: Fatal error: Call to undefined method Sylius\Behat\Page\Admin\Product\CreateSimpleProductPage::selectMainTaxon() in vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php:565
```
Not sure if `master` branch is correct btw.
=> [Behat] Test for assigning main taxon on new product

composer.json
Something went wrong in Twig 2.6.1 and it fails on accessing `vars` and `parent` of form in twig templates (see https://travis-ci.org/Sylius/Sylius/builds/479368942) :/
=> Fix build failing due to newest twig version

features/product/managing_product_reviews/editing_product_review.feature, src/Sylius/Bundle/AdminBundle/Resources/config/services.xml, src/Sylius/Bundle/AdminBundle/Resources/config/services/form.xml, src/Sylius/Bundle/ReviewBundle/Resources/config/validation/Review.xml
| Related tickets | #9895 
The test was a false-positive. I've changed it to create Customer and ShopUser so that UniqueReviewerEmailValidator has a user to validate against.
=> [Product Review] fixed review validation when edited by admin

src/Sylius/Bundle/ProductBundle/Resources/config/validation/ProductTranslation.xml, src/Sylius/Bundle/ProductBundle/Resources/translations/validators.en.yml, tests/Controller/ProductApiTest.php, tests/Responses/Expected/product/create_with_long_translations_validation_fail_response.json
| BC breaks?      | no (?)
This previously caused database errors when trying to insert data. Discovered this while working with the API, but this may also occur when trying to save a product in the admin GUI and the slug generator converts one character into > 1 characters like `ß` -> `ss`.
>SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'slug' at row 1
About the BC breaks yes/no: I guess someone could have increased the field length for the slug which this would prevent after updating. I personally don't see it as a BC break, but it may be useful to put a "warning" note in …
=> Add missing Length constraint on product translation slug

src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php
Looking through the code, in the `remover` itself (`ExpiredCartsRemover`) a `flush` call is made already on the Order Manager. Seems double and not needed to me here.
=> Remove flush() call, its done in the remover itself

app/migrations/Version20190204092544.php, src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Order.orm.xml
| Related tickets | partially #10148 
Makes selection of expired carts way more efficient. Especially helpful in growing projects.
Before:
After:
=> Add index on order.cart + order.updated_at for faster expired cart removal selection

composer.json, src/Sylius/Bundle/ThemeBundle/composer.json
`Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.`
=> Fix recent Composer deprecations

.github/PULL_REQUEST_TEMPLATE.md
As we now actively support branches `1.3` and `1.4` they should be mentioned in a PR template.
=> Change branches in Sylius PR template to supported ones

src/Sylius/Bundle/ShopBundle/Resources/private/scss/style.scss, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_search.html.twig
When using some languages the buttons break out the search segment, because the text on them is longer than what can fit in the semantic ui determined column size.
This change makes sure that the buttons always get enough room, by scaling the size of the text input field. Without breaking the layout.
To test this or reproduce the original behavior: 
1. please add the Dutch language from the admin side. And assign it to the default channel.
2. Add a translation for a product and for its taxon.
3. Now if you go to the `/nl/taxons/<dutch_taxon_slug>` route you will find that the layout …
=> Scaling text input field to keep enough room for the buttons

docs/contributing/organization/release-process.rst
- document what the current release process really is (minor at least every 4 months, patch at least every three weeks)
- add past / future releases tables with useful deadlines and overall lifecycle of a given release
- make development / stabilization phases relative to the time spent developing a release (3 months = 2.5 month developing & 0.5 month stabilizing, 6 months = 5 months developing & 1 month stabilizing)
=> Improve release process docs

src/Sylius/Bundle/AdminBundle/Resources/views/Product/Attribute/attributeChoice.html.twig
| Related tickets | fixes #6548
the problem was that the browser treats the button without the given type as submit, so after clicking enter it activated not this form
=> Fix product form submit

UPGRADE-1.3.md
`package.json` diff link and `.babelrc` diff link are reversed
| Related tickets | Doc error
Just a small mistake in the UPGRADE-1.3.md file.
Diff links are inversed ;)
=> Update UPGRADE-1.3.md diff link

docs/_themes/sylius_rtd_theme/layout.html, docs/book/introduction/introduction.rst
I've realised (thanks to @dukusz 👋 ) that we did not have any references to our Roadmap in the documentation.
That's why I'm adding it to the main menu:
And to the Book > Introduction :)
=> [Docs] Roadmap Link

src/Sylius/Bundle/AddressingBundle/Validator/Constraints/ProvinceAddressConstraintValidator.php, src/Sylius/Bundle/ChannelBundle/spec/Context/FakeChannel/FakeChannelPersisterSpec.php, src/Sylius/Component/Core/Payment/Provider/OrderPaymentProvider.php, src/Sylius/Component/Order/Model/Adjustment.php, src/Sylius/Component/Promotion/Checker/Eligibility/PromotionUsageLimitEligibilityChecker.php, src/Sylius/Component/Resource/Repository/InMemoryRepository.php
Code cleanup, brought by @Rector with [Code Quality level](https://github.com/rectorphp/rector/issues/424)
=> [cs] remove unnecesary variables and if conditions

src/Sylius/Bundle/GridBundle/Resources/config/services/integrations/doctrine/phpcr-odm.xml, src/Sylius/Bundle/ResourceBundle/Resources/config/services/integrations/doctrine/mongodb-odm.xml
This PR fixes Symfony error "deprecation template must contain the "%service_id%" placeholder" in Symfony\Component\DependencyInjection\Definition::setDeprecated() method. This error occurs when using deprecated Resource drivers.
=> [Resource] [Grid] deprecation warning fixed for deprecated Resource drivers

docs/cookbook/configuration/installation-commands.rst, src/Sylius/Bundle/CoreBundle/Command/InstallCommand.php, src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php, src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php
| Related tickets | fixes #8759
=> Fix for #8759 (ability to specify custom fixture suite during install)

src/Sylius/Bundle/ShopBundle/Resources/views/Taxon/_verticalMenu.html.twig
| Related tickets | fixes #9903 
=> Taxonomy tree modified - 'go level up' moved to the end of tree

composer.json
Reverts Sylius/Sylius#10255.
See https://github.com/Sylius/SyliusThemeBundle/pull/21.
=> Revert "[HotFix] Conflict with Twig 2.7.3 that breaks themes bundle"

src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/IgnoreAnnotationsPass.php, src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php
According to recent changes in `doctrine/collections` (specifically in `1.6.0` version), we need to ignore psalm-related annotations to make usage of `ArrayCollection` possible 🚀
=> [BuildFix] Ignore psalm annotations

.travis.yml, src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/10266, replaces https://github.com/Sylius/Sylius/pull/10274
The bug from issue #10266 has not been detected on Travis CI, due to the lower mySQL version (without `ONLY_FULL_GROUP_BY` option set). So this PR bumps the mySQL version on the Travis to **5.7** and contains the fix for the products sorting from #10274 (thank @laSyntez for this one!).
As a proof that it didn't work without the fix, you can take a look at [this build](https://travis-ci.org/Zales0123/Sylius/builds/512912936) or check out our failing demo 🚀 🤣 
We have also a PR …
=> Travis with mySQL 5.7 + product sorting fix

.travis.yml, etc/travis/suites/application/before_script.sh
Since merging https://github.com/Sylius/Sylius/pull/10278 Travis jobs takes up to 50 minutes and are closed due to reaching a public repository job time limit :/ I don't know is it an issue with the mySQL version for 100%, but I think we should give it a try (check out https://github.com/travis-ci/travis-ci/issues/9948). I hope it will work, as 50 minutes-long jobs are really painful 🔪 💀
=> [Travis] Update mysql version to speed up builds

.env, composer.json, etc/travis/suites/application/install.sh
| New feature?    | kind of
This is a performance improvement. You can read more on [Symfony blog](https://symfony.com/blog/new-in-symfony-flex-1-2) on **Improved the handling of ``.env`` files** section.
I added this dump-env on travis to speed up build (hope!).
=> Upgrade flex to use composer dump-env

docs/components_and_bundles/bundles/SyliusResourceBundle/index_resources.rst
Added missing config parameter `filterable`
| Branch?         | 1.0+
[Default value](https://github.com/Sylius/Sylius/blob/1.0/src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php#L323) of `RequestConfiguration::isFiltrable` is `false`. ResourceResolver [checks](https://github.com/Sylius/Sylius/blob/1.0/src/Sylius/Bundle/ResourceBundle/Controller/ResourcesResolver.php#L33) `RequestConfiguration::isFiltrable` to apply `criteria`. 
Current docs are missing `filterable` config parameter. Without it `criteria` are not applied to the query. This PR adds missing config.
=> [Documentation][ResourceBundle] 7.1. Overriding the Template and Criteria invalid config

config/packages/security.yaml, src/Sylius/Behat/Service/SecurityService.php, src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php
When always_authenticate_before_granting: is set to true there is infinity loop of redirects to login page because AuthenticationProviderManager can't find a provider which supports UsernamePasswordToken with providerKey _security_shop. So, a provider key in UsernamePasswordToken must be the same as  $firewallContextName, without _security_ prefix.
| Branch?         | 1.3, 1.4
=> Fix re-authenticating for impersonated users

composer.json, src/Sylius/Bundle/AddressingBundle/composer.json, src/Sylius/Bundle/CoreBundle/composer.json, src/Sylius/Bundle/CurrencyBundle/composer.json
The following subpackages rely on `symfony/intl`:
- Behat contexts
- CoreBundle
- CurrencyBundle
- AddressingBundle
- Addressing
- Locale
- Currency
Currently this package is installed because of transient dependencies, but we shouldn't rely on that.
=> Do not depend on transient dependencies for "symfony/intl" package

config/packages/test/sylius_uploader.yaml, config/packages/test_cached/sylius_uploader.yaml, features/cart/shopping_cart/having_proper_product_image_displayed_in_cart.feature, src/Sylius/Behat/Context/Setup/ProductContext.php, src/Sylius/Behat/Context/Ui/Shop/CartContext.php, src/Sylius/Behat/Page/Shop/Cart/SummaryPage.php, src/Sylius/Behat/Page/Shop/Cart/SummaryPageInterface.php, src/Sylius/Behat/Resources/config/suites/ui/cart/shopping_cart.yml, src/Sylius/Behat/Service/Uploader/ImageUploader.php, src/Sylius/Bundle/ShopBundle/Resources/views/Product/_info.html.twig
| Related tickets | replaces https://github.com/Sylius/Sylius/pull/8788, fixes https://github.com/Sylius/Sylius/issues/8787
This is a resurrection of linked PR, with some Behat tests added. I'm not very happy with the scenario implementation, as it requires overwriting the whole `ImageUploader` in a test environment, to keep uploaded image name - to give availability to check it in the scenario :/
IMO the best option would be to extract some service that would provide a new name for the uploaded image. I can do it in this or separate PR... What do you think? cc @Sylius/core-team @castler @gabiudrescu
=> [Shop] Use first variant image on a cart page

src/Sylius/Bundle/ResourceBundle/Grid/Parser/OptionsParser.php, src/Sylius/Bundle/ResourceBundle/spec/Grid/Parser/OptionsParserSpec.php
| BC breaks?      | potentially ?
When customizing grids quite a lot, we might get a queryBuilder returning an array of array instead of an array of entities. this array is built like this : 
```php
$result = [
0 => new Resource(),
'custom_value' => 8,
'other_custom_value' => 'aaa',
]
```
And for this reason, it might be usefull to allow this kind of option parsing.
=> Allowing options to be given with resource[0].id syntax

src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php, src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml, src/Sylius/Bundle/CoreBundle/Tests/Fixture/LocaleFixtureTest.php
| BC breaks?      | not sure (it backward compatible on default fixtures configuration)
| Deprecations?   | not sure (deprecation messages was added, but not appear on default fixtures configuration)
| Related tickets | fixes #10307, partially #7346
So, in BC in mind, with this PR it now will work like this:
- **If you have default (empty) configuration, as was before**:
```yaml
sylius_fixtures:
fixtures:
locale: ~
```
Then, base locale **will be added** to configuration.
- *But if you provided a list of locales*:
```yaml
sylius_fixtures:
suites:
my_custom_suite_to_add_to_existing_database:
listeners:
orm_purger: false
fixtures:
locale:
options: …
```
=> Fix base locale

docs/customization/menu.rst, features/product/managing_products/accessing_variants_management_from_product_edit_page.feature, src/Sylius/Behat/Context/Ui/Admin/BrowsingProductVariantsContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php, src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPage.php, src/Sylius/Behat/Page/Admin/Product/UpdateConfigurableProductPageInterface.php, src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPage.php, src/Sylius/Behat/Page/Admin/Product/UpdateSimpleProductPageInterface.php, src/Sylius/Behat/Resources/config/services/contexts/ui.xml, src/Sylius/Bundle/AdminBundle/Menu/ProductUpdateMenuBuilder.php, src/Sylius/Bundle/AdminBundle/Resources/config/routing/product.yml, src/Sylius/Bundle/AdminBundle/Resources/config/services/menu.xml, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Update/_toolbar.html.twig, src/Sylius/Bundle/UiBundle/Resources/views/Menu/top.html.twig
| Related tickets | replaces #9785, fixes #9647
=> [Admin][Product] Access the variants management from product edit page

src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml
| BC breaks?      | I wouldn't say so (see my comment below)
The service isn't used anywhere and if it would be used it wouldn't work since the `Sylius\Component\Shipping\Checker\RuleCheckerInterface` does not exist.
=> Removing unused service

src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
| Related tickets | fixes #9646 again
Using lambdas on the `1.1` branch does not work since the `1.1` branch uses **uglifyJS** without Babel, hence, ES6 notation cannot be used.
Without this PR, you cannot run `GULP_ENV=prod npm run gulp` on the `1.1` branch, and thus you cannot build the assets needed for the backoffice.
This PR reverts the lambdas to "regular" functions, unbreaking the asset building for this branch.
Please do not hesitate if I missed some guidelines for this PR
Best
=> Fix #9646 by removing lambdas in JS file

src/Sylius/Bundle/ProductBundle/DependencyInjection/Configuration.php
Reverts Sylius/Sylius#10350
These repositories are configured [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ProductBundle/Resources/config/services/integrations/doctrine/orm.xml). If there is indeed a bug, we need to give it a more in-depth consideration.
=> Revert "fix default repository for variant and association type resources"

features/promotion/managing_promotions/accessing_promotion_with_rule_that_contains_removed_taxon.feature, src/Sylius/Behat/Context/Setup/PromotionContext.php, src/Sylius/Behat/Context/Transform/TaxonContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingTaxonsContext.php, src/Sylius/Behat/Context/Ui/Admin/RemovingTaxonContext.php, src/Sylius/Behat/NotificationType.php, src/Sylius/Behat/Page/Admin/Promotion/UpdatePage.php, src/Sylius/Behat/Page/Admin/Promotion/UpdatePageInterface.php, src/Sylius/Behat/Resources/config/services/contexts/ui.xml, src/Sylius/Behat/Resources/config/suites/ui/promotion/managing_promotions.yml, src/Sylius/Behat/Resources/config/suites/ui/taxonomy/managing_taxons.yml, src/Sylius/Behat/Service/NotificationChecker.php, src/Sylius/Bundle/CoreBundle/EventListener/TaxonDeletionListener.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml, src/Sylius/Bundle/CoreBundle/Resources/config/services/promotion.xml, src/Sylius/Bundle/CoreBundle/spec/EventListener/TaxonDeletionListenerSpec.php, src/Sylius/Bundle/UiBundle/Resources/translations/flashes.en.yml, src/Sylius/Component/Core/Promotion/Updater/Rule/HasTaxonRuleUpdater.php, src/Sylius/Component/Core/Promotion/Updater/Rule/TaxonAwareRuleUpdaterInterface.php, src/Sylius/Component/Core/Promotion/Updater/Rule/TotalOfItemsFromTaxonRuleUpdater.php, src/Sylius/Component/Core/spec/Promotion/Updater/Rule/HasTaxonRuleUpdaterSpec.php, src/Sylius/Component/Core/spec/Promotion/Updater/Rule/TotalOfItemsFromTaxonRuleUpdaterSpec.php
| Related tickets | fixes #10225
=> [Admin][Promotion] Fix removing taxon used in promotion rule

src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php, src/Sylius/Bundle/CoreBundle/Tests/Fixture/LocaleFixtureTest.php, src/Sylius/Bundle/CoreBundle/spec/Fixture/LocaleFixtureSpec.php
| Related tickets | fixes #10307
Opened to master as it is a new feature at the end.
=> [Fixture] Togglable default locale loading

src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-taxon-tree.js
Fixes an error that was displayed on pages where there was no taxon tree
=> Fix error caused by the taxon tree

src/Sylius/Bundle/AdminBundle/Resources/views/Form/imagesTheme.html.twig, src/Sylius/Bundle/UiBundle/Resources/views/Form/imagesTheme.html.twig, src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
| Related tickets | Related #9843
Before this changing when you create a custom resource with image, on edit page you don't see uploaded image. 
now you see image uploaded earlier. it works if you don't override sylius image theme
=> Image display in edit form

src/Sylius/Bundle/CoreBundle/Installer/Setup/LocaleSetup.php
Improve DX by adding additional info about locale settings inside sylius:install:setup command.
| Related tickets | #10398
=> Add info into install command about need of setting the locale in symfony config

src/Sylius/Behat/Context/Api/Admin/ManagingProductVariantsContext.php, src/Sylius/Behat/Context/Api/Admin/ManagingTaxonsContext.php
Using client from browser kit component instead of http kernel component. I am using the deprecated version because the Symfony\Component\BrowserKit\AbstractBrowser is first introduced in SF4.3 (not sure this is correct?).
This commit fixes this issue when running behat tests:
`Argument 1 passed to Sylius\Behat\Context\Api\Admin\ManagingTaxonsContext::__construct() must be an instance of Symfony\Component\HttpKernel\Client, instance of Symfony\Bundle\FrameworkBundle\KernelBrowser given`
| Branch?         | 1.3 and newer
| Bug fix?        | Somewhat
=> Using client from browser kit component instead of http kernel component

docs/customization/validation.rst
Adding a tip on what validation group to configure in `_sylius.yaml` when using group sequence validation.
=> [Docs] Added tip for using group sequence validations

src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
Use native `.dataset` instead of jQuery `.data()` to avoid type conversion which make it impossible to remove taxons with numeric codes from products
| Related tickets | fixes #10439
=> Fix removing taxons with numeric codes from products

etc/travis/suites/application/script/test-behat-with-javascript, src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig
| License         | 
On some pages, especially on the orders index page, filters block is enormous and take almost half of the screen:
It seems a reasonable change to hide filters by default, as they're just an addition to the index page functionality, not the core of it:
=> [UI] Hide filters by default on index pages

src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_breadcrumb.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_content.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_breadcrumb.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_content.html.twig
It gives a possibility to configure:
```
your_route:
...
defaults:
...
_sylius:
vars:
...
index:
route:
name: custom_route
parameters: custom_parameters
```
=> [Admin] Add possibility to configure custom index route in routing

src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product.yml, src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/taxon.yml, src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductRepository.php, src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php, src/Sylius/Component/Product/Repository/ProductRepositoryInterface.php, src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php
In case you have a large amount of data (i.e. 100k products), the autocomplete query fetches all matching results which brokes down the whole web server. This simple fix limits the results to 25 as in most cases the end user does not need more than this amount of suggested hits. 
Could be improved by adding the limit parameter to the method signature.
=> Fix huge autocomplete queries issue

src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxonExampleFactory.php
@loevgaard suggested I made this PR for this problem we ran into with using the **Taxon** fixture to add many nested categories into our dev server.
When using the **TaxonFixture** to generate nested categories, with slugs being automatically generated based on name, the slugs generated for the child categories, will not inherit their parents slugs.
This is due to the way child categories are added in the **TaxonExampleFactory**. A child category is added to the parent category after the child category has had it's slug generated via the **taxonSlugGenerator**. Thus the …
=> [taxon_fixtures] Fix child taxon slug generation

src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_details.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variants.html.twig
- Fix channels display
- Remove options row from simple products
- Add margin to the stock column
=> Fix product show page elements

config/bootstrap.php
Fixes this notice: `The default value of "$usePutenv" argument of "Symfony\Component\Dotenv\Dotenv::__construct" will be changed from "true" to "false" in Symfony 5.0. You should define its value explicitly.`
=> Fix deprecation notice

src/Sylius/Behat/Page/Admin/Crud/IndexPage.php, src/Sylius/Bundle/UiBundle/Resources/private/js/app.js, src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-check-all.js, src/Sylius/Bundle/UiBundle/Resources/private/sass/main.scss, src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig, src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
=> Improve bulk actions

docs/book/orders/coupons.rst, features/promotion/managing_coupons/coupon_generate_validation.feature, features/promotion/managing_coupons/generating_coupon.feature, features/promotion/managing_coupons/generating_coupon_with_prefix_and_suffix.feature, src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionCouponsContext.php, src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePage.php, src/Sylius/Behat/Page/Admin/PromotionCoupon/GeneratePageInterface.php, src/Sylius/Behat/Page/Admin/PromotionCoupon/IndexPage.php, src/Sylius/Behat/Page/Admin/PromotionCoupon/IndexPageInterface.php, src/Sylius/Behat/Resources/config/services/pages/admin/promotion_coupon.xml, src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Generate/_form.html.twig, src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionCouponGeneratorInstructionType.php, src/Sylius/Bundle/PromotionBundle/Resources/translations/messages.en.yml, src/Sylius/Component/Promotion/Generator/PromotionCouponGenerator.php, src/Sylius/Component/Promotion/Generator/PromotionCouponGeneratorInstruction.php, src/Sylius/Component/Promotion/Generator/PromotionCouponGeneratorInstructionInterface.php, src/Sylius/Component/Promotion/spec/Generator/PromotionCouponGeneratorInstructionSpec.php, src/Sylius/Component/Promotion/spec/Generator/PromotionCouponGeneratorSpec.php
=> [Promotion] Coupon prefix and suffix

UPGRADE-1.5.md
I've just upgraded an application from `1.4` to `1.5` and one of the Sylius tests failed :/ I think this change is worth to be mentioned in UPGRADE file, even if it's not required for the application to work 🖖
=> [UPGRADE] Mention locale requirement change in UPGRADE-1.5

src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php
Currently it's not possible to have fixture suites with no shipping methods (a.k.a. virtual shipping only). This PR makes it possible.
| Branch?         | 1.4 
| Related tickets | #10490
=> Make it possible to have no shipping methods for Order fixtures

composer.json, symfony.lock
Psalm does not recognize conditional definitions like the one used by Symfony's EventDispatcherInterface: https://github.com/symfony/contracts/blob/master/EventDispatcher/EventDispatcherInterface.php#L16
=> Fix Psalm false-positives

src/Sylius/Bundle/ShopBundle/Resources/private/scss/style.scss
| Related tickets | fixes #10425 
I was on the page https://demo.sylius.com/en_US/taxons/books using Firefox 60.7.2esr (64-bit) and saw the issue described by #10425.
I added the css rule `width: -moz-fit-content;` online and had the proper display.
=> Add search bar css rule for Firefox

src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_details.html.twig
=> Fix 'disabled' label

src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/applyTransition.html.twig
I suppose it should not be required. It's quite weird to get an exception if you do not specify the color of the button 🐒
=> [Grid] Allow not to pass "apply_transition" button class

src/Sylius/Bundle/CoreBundle/Resources/config/test_services.xml, tests/Functional/UpdatingUserPasswordEncoderTest.php
| Related tickets | fixes #10530
=> Skip oauth_user_factory_is_not_overridden test if HWIOAuthBundle is not installed

src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_breadcrumb.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Create/_breadcrumb.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Generate/_breadcrumb.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Index/_breadcrumb.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Update/_breadcrumb.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Create/_breadcrumb.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Generate/_breadcrumb.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Index/_breadcrumb.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/PromotionCoupon/Update/_breadcrumb.html.twig
| New feature?    | rather an improvement
| Related tickets | triggered by #10509 😄 
The clue is to use entities **names** instead of **codes**, wherever it is possible. especially in entities that are _under_ other entities like coupons or variants.
Product variant edit:
Before:
After:
Without the variant name:
Channels edit:
Before:
After:
And while trying to unsuccessfully remove the name:
After (translation of names to Admin locale)
=> [Admin] Improve breadcrumbs (especially for ProductVariants and PromotionCoupons)

src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js
| Related tickets | fixes #10577 
=> Fix lazy choice tree will not automatically expanded

src/Sylius/Bundle/AdminBundle/Resources/config/grids/customer_order.yml
Fixes #10551.
Caused by https://github.com/Sylius/SyliusGridBundle/blob/15dd36ef9676836e1d1e02d9f108c6f1dbc21829/src/Component/Provider/ArrayGridProvider.php#L54.
=> Enable sorting of customer orders in admin panel

docs/book/orders/payments.rst
If you configure a payment gateway the way it's now hinted in the docs, it would prevent the gateway from receiving configuration from the database. This issue may be really frustrating and hard to debug for beginners (like me).
Configuring a factory by hand is not needed if it's been correctly configured with the `payum.gateway_factory_builder` tag.
=> [Docs] Fix incorrect documentation regarding payments

src/Sylius/Bundle/ShopBundle/Resources/private/js/app.js
Chrome has changed the way we can block autocomplete. This is the simplest way to change the automatically generated Semantics input properties.
=> Disable chrome autocomplete

src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures.xml, src/Sylius/Component/Core/OrderCheckoutStates.php
| Related tickets | introduces in https://github.com/Sylius/Sylius/pull/10618
There is no need to skip payment and shipment in order manually, as it's done automatically with [this callback](https://github.com/Sylius/Sylius/blob/60134b783c51c4b9da0b58c5a54482824a8baf8a/src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_checkout.yml#L53) 🎉
=> [Fixture] Do not skip payments and shipments manually

docs/customization/index.rst, docs/customization/map.rst.inc
| Related tickets | related to https://github.com/Sylius/Sylius/pull/10395
I've also changed the order in the left sidebar menu
=> [Docs] Add missing items to customization guide menu

features/user/managing_customers/browsing_orders_of_customer.feature, src/Sylius/Behat/Context/Ui/Admin/ManagingCustomersContext.php, src/Sylius/Behat/Page/Admin/Crud/IndexPage.php, src/Sylius/Behat/Page/Admin/Crud/IndexPageInterface.php, src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php
| Related tickets | Fixes #10637
=> [Admin] Fix sorting on customer orders list

docs/book/orders/adjustments.rst
=> [Documentation] Add tip about locked adjustments

app/migrations/Version20170711151342.php, etc/travis/suites/application/script.sh, etc/travis/suites/application/script/test-doctrine-migrations
In CI, we test migration up during installation, but we never test down migrations.
This new Travis test checks doctrine migration up & down.
=> Test doctrine migrations up & down

src/Sylius/Component/Payment/PaymentTransitions.php
It seems like the authorize transition has no constant on the payment.
=> Add authorize constant to payment transitions

src/Sylius/Behat/Page/Admin/DashboardPage.php
| Bug fix?        | yes (for BDD)
| BC breaks?      | no BC breaks promise on Behat
When adding grids on admin dashboard, if you extends Sylius\Behat\Page\Admin\DasboardPage, You have no access to tableAccessor to add some tests on your custom grids.
For information, my current workaround:
```
<?php
declare(strict_types=1);
namespace App\Tests\Behat\Page\Admin;
use Behat\Mink\Session;
use Sylius\Behat\Page\Admin\DashboardPage as BaseDashboardPage;
use Sylius\Behat\Service\Accessor\TableAccessorInterface;
use Symfony\Component\Routing\RouterInterface;
class DashboardPage extends BaseDashboardPage
{
/** @var TableAccessorInterface …
```
=> [Behat] Improve dashboard page extensibility

src/Sylius/Bundle/PayumBundle/Controller/PayumController.php
| Branch?         | 1.6 (as it present only since 1.6)
| Related tickets | fixes #10720, related 6c748c9aec878687c610bd440aac9635143df0c3
Decided to use `(bool)` here as it converts both `1` and `'1'` to true and `0` and `'0'` to false.
=> Fixed: use_authorize option comparison (fixes #)

docs/book/installation/installation.rst, src/Sylius/Bundle/CoreBundle/Installer/Setup/CurrencySetup.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/installer.xml
| Branch?         | 1.6 (or master)
Scenario: I want to run the `sylius:install` command with no interaction and use the data from my custom fixture to set up the webshop. This includes using Dutch as the language and Euro as the currency.
Currently: `sylius:install --no-interaction` uses the hardcoded preference of USD for the currency.
After this PR: The default is still USD, but can be overwritten with a `currency:` parameter similar to the locale (which is not a hardcoded preference during installation).
=> [Currency] added parameterized currency during installation

src/Sylius/Bundle/ChannelBundle/Collector/ChannelCollector.php
| BC breaks?      | unlikely, but possible
| Related tickets | fixes #10223
This is very annoying long standing issue.
I'm pretty sure this will fix the issue (it does in our case). As a side effect, this is more efficient, as there is less data needed to be serialized. 
This issue is related to circular references inside Channel model. In our case we can reproduce with
```php
$n = new Channel();
$locale = new Locale();
$n->addLocale($locale);
$n->setDefaultLocale($locale);
$this->data = [
'channel' => null,
'channels' => [$n],
'channel_change_support' => $channelChangeSupport,
];
```
inside ChannelCollector
I'm aware …
=> Fix ChannelCollector related serialization issue in Symfony profiler

src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php
This method could easily be used when extending the repository, therefore it would make sense to make it protected
| Bug fix?        | No
| New feature?    | Sort of
| BC breaks?      | No
| Deprecations?   | No
=> Changed visibility to make it usable when extending

src/Sylius/Bundle/CoreBundle/Context/CustomerContext.php
It's much cheaper to run a quick instanceof check first. If it returns false, we skip entire decision manager process. This is better for performance actually, at least when the user is not authenticated. Simple things do matter.
=> Switch statement conditions

UPGRADE-1.6.md
Update `package.json` in order to add JQuery Dirtyforms.
See [issue #88](https://github.com/Sylius/SyliusDemo/pull/88/files) for more informations
=> Add JQuery Dirtyforms in UPGRADE-1.6.md

src/Sylius/Bundle/ShopBundle/EventListener/UserImpersonatedListener.php, src/Sylius/Bundle/ShopBundle/spec/EventListener/UserImpersonatedListenerSpec.php
If you want to impersonate another user resource (for example, in my current project, we have a Partner user), this listener is called and is failed cause it's called on any user resource impersonating action.
=> Fix user impersonated listener when impersonating another user resource

docs/book/architecture/translations.rst, src/Sylius/Bundle/ReviewBundle/Updater/AverageRatingUpdater.php, src/Sylius/Bundle/ReviewBundle/spec/Updater/AverageRatingUpdaterSpec.php
https://github.com/doctrine/orm/blob/master/UPGRADE.md#bc-break-removed-entitymanagerflushentity-and-entitymanagerflushentities
| Related tickets | mentioned in #10107 
=> Replace EntityManager#flush($entity) by EntityManager#flush()

psalm.xml, src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php, src/Sylius/Bundle/AddressingBundle/Twig/ProvinceNamingExtension.php, src/Sylius/Bundle/AdminBundle/Twig/NotificationWidgetExtension.php, src/Sylius/Bundle/AdminBundle/Twig/ShopExtension.php, src/Sylius/Bundle/CoreBundle/Twig/CheckoutStepsExtension.php, src/Sylius/Bundle/CoreBundle/Twig/PriceExtension.php, src/Sylius/Bundle/CoreBundle/Twig/ProductVariantsPricesExtension.php, src/Sylius/Bundle/CoreBundle/Twig/VariantResolverExtension.php, src/Sylius/Bundle/CurrencyBundle/Twig/CurrencyExtension.php, src/Sylius/Bundle/InventoryBundle/Twig/InventoryExtension.php, src/Sylius/Bundle/LocaleBundle/Twig/LocaleExtension.php, src/Sylius/Bundle/MoneyBundle/Twig/ConvertMoneyExtension.php, src/Sylius/Bundle/MoneyBundle/Twig/FormatMoneyExtension.php, src/Sylius/Bundle/OrderBundle/Twig/AggregateAdjustmentsExtension.php, src/Sylius/Bundle/ShopBundle/Twig/OrderItemsSubtotalExtension.php, src/Sylius/Bundle/ShopBundle/Twig/OrderTaxesTotalExtension.php, src/Sylius/Bundle/UiBundle/Twig/PercentageExtension.php, src/Sylius/Bundle/UiBundle/Twig/SortByExtension.php
Created a list of deprecated classes, interfaces and method calls - it will make fixing them easier, just choose one, delete it in Psalm, fix the errors, done! :)
Also solved Twig deprecations making use of their forward compatibility layer.
=> Explicitly list deprecated things in the code & solve Twig deprecations

src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShopUserExampleFactory.php
When you override this example factory. You have to manually wire this argument.
This change helps Resource bundle to autowire this argument.
=> Rename shop user factory to help autowiring

src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php, src/Sylius/Bundle/PayumBundle/spec/Action/Paypal/ExpressCheckout/ConvertPaymentActionSpec.php
It was frustrating, that after passing all the required data in the "Address" step of checkout, we need to do it again in the PayPal form (when not being logged in, of course :)). With this improvement, we pass billing data to have it prefilled in PayPal - notice, that country code is passed as `LOCALECODE`, as it allows us to pass also country-specific data, like a phone number or province code/name.
**United States**
| Address | PayPal form | 
| ------- | ----------- |
| <img width="256" alt="Zrzut ekranu 2019-11-5 o 15 44 06" …
=> [Payum][Checkout] Pass address data to PayPal after checkout

.gitignore, composer.json, config/bundles.php, config/packages/assets.yaml, config/packages/webpack_encore.yaml, package.json, src/Sylius/Bundle/AdminBundle/Resources/private/entry.js, src/Sylius/Bundle/AdminBundle/Resources/views/_scripts.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/_styles.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig, src/Sylius/Bundle/ShopBundle/Resources/private/entry.js, src/Sylius/Bundle/ShopBundle/Resources/views/_scripts.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/_styles.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig, symfony.lock, webpack.config.js, yarn.lock
This is the first step to completely remove the gulp. For now, lets you choose whether you want to use the gulp or webpack. By default, it uses the gulp as before.
```js
// src/Sylius/Bundle/AdminBundle/Resources/views/_scripts.html.twig
{{ encore_entry_script_tags('admin-entry', null, 'admin') }}
```
```js
// src/Sylius/Bundle/AdminBundle/Resources/views/_styles.html.twig
{{ encore_entry_link_tags('admin-entry', null, 'admin') }}
```
```js
// src/Sylius/Bundle/AdminBundle/Resources/views/_logo.html.twig
{{ asset('build/admin/images/admin-logo.svg', 'admin') }}
```
And for shop:
```js
// src/Sylius/Bundle/ShopBundle/Resources/views/_scripts.html.twig
{{ encore_entry_script_tags('shop-entry', null, 'shop') }}
```
```js
// src/Sylius/Bundle/ShopBundle/Resources/views/_styles.html.twig
{{ …
```
=> Add Webpack Encore

.gitignore, composer.json, config/bundles.php, config/packages/assets.yaml, config/packages/webpack_encore.yaml, symfony.lock
| Related tickets | fixes #10803 
This PR removes webpack-encore-bundle from dependencies to avoid errors in plugins that have no webpack configuration
1. Install webpack-encore-bundle
```
composer require symfony/webpack-encore-bundle
```
2. Edit `config/packages/assets.yaml` file
```yml
framework:
assets:
packages:
shop:
json_manifest_path: '%kernel.project_dir%/public/build/shop/manifest.json'
admin:
json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'
```
3. Edit `config/packages/webpack_encore.yaml` file
```yml
webpack_encore:
output_path: '%kernel.project_dir%/public/build/default'
builds:
shop: '%kernel.project_dir%/public/build/shop'
admin: …
```
=> New Webpack approach

src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php, src/Sylius/Bundle/AddressingBundle/spec/Twig/CountryNameExtensionSpec.php
Fallback to code when there's no translation.
Fallback to empty string when there's no code.
| Related tickets | fixes #10799
=> [Addressing] Make sure the CountryNameExtension::translateCountryIsoCode() always returns a string

docs/contributing/code/bc.rst
There is a very unlikely possibility that one would create a new service based on our final controller class but with different arguments injected to the constructor. It is not a recommended way for sure - we try to keep final controllers as small as possible and the bigger ones are still non-final.
If you're using our final controllers, you're still covered with BC promise.
We need this exception for fixes like #10837.
=> Clarify BC promise for final controllers

features/order/managing_orders/seeing_order_currency_on_show.feature, features/order/managing_orders/seeing_order_discounts.feature, features/promotion/complex_promotions.feature, src/Sylius/Component/Core/Model/Order.php, src/Sylius/Component/Core/spec/Model/OrderSpec.php
Fix for: https://github.com/Sylius/Sylius/issues/10800
=> [Order] Include order unit promotion adjustments and order item promotion adjustments in order promotion total

src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneChoiceType.php, src/Sylius/Bundle/AddressingBundle/Resources/config/services/form.xml, src/Sylius/Bundle/AddressingBundle/Tests/Form/Type/ZoneChoiceTypeTest.php, src/Sylius/Bundle/CoreBundle/Form/Extension/ShippingMethodTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/TaxRateTypeExtension.php
Fixed issue with shipping zones available to select in tax rate form (and the other way)
- added zone_scope option to ZoneChoiceType to pass desired scope
- for BC default scope is "ALL"
- modified ShippingMethodTypeExtension and TaxRateTypeExtension to pass correct zone_scope option
- form type test for ZoneChoiceType
| Branch?         | 1.6 
| Deprecations?   | yes 
btw. Maybe this is not something that people usually write in PRs, but it is actually my first contribution to Sylius, so I feel that I should write something more in this important moment... I would like to dedicate this PR to my wife who always supports me and …
=> [Taxation] [Shipping] Fixed issue with shipping zones available to select in tax rate form (and the other way)

src/Sylius/Bundle/AddressingBundle/Resources/config/validation/Address.xml
In Oslo, Norway there is a postal code `1`. See https://worldpostalcode.com/norway/hordaland/oslo
| Branch?         | All
=> Decrement length constraint on postcode

src/Sylius/Bundle/UserBundle/Command/DemoteUserCommand.php, src/Sylius/Bundle/UserBundle/Command/PromoteUserCommand.php
| Related tickets | fixes #10862
A quick fix to make it clearer to users that if an error happens the user's roles are unchanged. Previously it was showing both success and error messages which gave the impression other role changes that didn't trigger an error had been applied when they hadn't (the entity is only flushed if no errors happen).
=> [SyliusUserBundle] Improve output of Promote/DemoteUserCommand

docs/book/plugins/approved-plugins.rst, docs/book/plugins/creating-plugin.rst, docs/book/plugins/index.rst, docs/book/plugins/map.rst.inc, docs/book/plugins/sylius-store.rst, docs/plugin-development-guide/summary.rst
This PR contains changes from https://github.com/Sylius/Sylius/pull/10731, which in fact should be from the beginning opened to `1.6` 😄 
Due to the release of Sylius Store, I propose a slightly new approach to approving/accepting plugins. We want to develop our plugins ecosystem, but on the other hand, we still want to keep the high quality of these extensions. There is also a new way to propose plugins to our plugins list - a [plugin request submit form](https://store.sylius.com/submit).
So my proposal is to accept all the plugins that work, provide a valuable extension to Sylius …
=> [Plugins][Docs] Plugin technical requirements changes

etc/travis/suites/application/script/validate-container, src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml, src/Sylius/Bundle/PayumBundle/Resources/config/services/controller.xml
| Q               | A 
| --------------- | ----- 
| Branch?         | 1.5 
| Bug fix?        | yes 
| New feature?    | no 
| BC breaks?      | no 
| Related tickets | - 
Removes services defined for nonexisting classes and fixes other container-related errors.
Adds `lint:container` command to the build.
https://symfony.com/blog/new-in-symfony-4-4-service-container-linter
=> Add lint:container command to the build & fix errors reported by it

features/order/managing_orders/resending_shipment_confirmation_email.feature, src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php, src/Sylius/Behat/Context/Ui/EmailContext.php, src/Sylius/Behat/Page/Admin/Order/ShowPage.php, src/Sylius/Behat/Page/Admin/Order/ShowPageInterface.php, src/Sylius/Bundle/AdminBundle/Action/ResendShipmentConfirmationEmailAction.php, src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipment.yml, src/Sylius/Bundle/AdminBundle/Resources/config/services/controller.xml, src/Sylius/Bundle/AdminBundle/Resources/translations/flashes.en.yml, src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipment.html.twig, src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
When the shipment is in `ready` state:
When the shipment is in `shipped` state:
=> [Admin][Order] Add resending a shipment confirmation email

src/Sylius/Component/Core/spec/Cart/Context/ShopBasedCartContextSpec.php, src/Sylius/Component/Core/spec/Customer/CustomerOrderAddressesSaverSpec.php
It seems that these specs should never work 😄 The problem is, it's hard to specify setting a cloned object... especially if in one of this case we also have some value changed 💃 So this is obviously not a final fix, but at least it should fix a build 🚀
=> [Hot-Fix] Fix failing specs after prophecy update

src/Sylius/Bundle/PayumBundle/Provider/PaymentDescriptionProvider.php, src/Sylius/Bundle/PayumBundle/Resources/translations/messages+intl-icu.en.yml, src/Sylius/Bundle/PayumBundle/Resources/translations/messages.en.yml, src/Sylius/Bundle/PayumBundle/spec/Provider/PaymentDescriptionProviderSpec.php, src/Sylius/Bundle/ShopBundle/Resources/views/Cart/_widget.html.twig, src/Sylius/Bundle/UiBundle/Resources/translations/messages+intl-icu.en.yml, src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
Symfony 5.0 removes `transchoice` filter and recommends using Intl ICU to handle pluralisation - https://symfony.com/doc/4.4/translation/message_format.html.
Referencing mega-issue #10928.
=> Handle pluralisation in translations with Intl ICU

src/Sylius/Bundle/AdminBundle/Resources/views/Email/shipmentConfirmation.html.twig
=> [Email][Shipment] Fix shipment confirmation email to send information about tracking only if it is provided

composer.json
There are no specs for shipping bundle, therefore this namespace is not needed.
=> [Maintenance] Remove shipping bundle from spec namespace config

src/Sylius/Behat/Page/Shop/Account/RequestPasswordResetPage.php, src/Sylius/Behat/Page/Shop/Account/ResetPasswordPage.php, src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php, src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php, src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_addressBookSelect.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_form.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_navigation.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectPayment/_navigation.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectShipping/_choice.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectShipping/_navigation.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectShipping/_shipment.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/SelectShipping/_unavailable.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_header.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_steps.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_summary.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_address.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_countryCode.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_login.html.twig, src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml, src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig, src/Sylius/Bundle/UiBundle/Twig/MergeRecursiveExtension.php
Replacing class/id by attributes in AddressPage, selectShippingPage and related html
for now, I left elements related to JS without changes, because simple attribute generates errors, it will be done in the near feature.
=> [Behat] Rework behat  - using attributes instead class/id in address and shipping page

features/promotion/receiving_discount/receiving_percentage_discount_on_shipping.feature, src/Sylius/Component/Core/Promotion/Action/ShippingPercentageDiscountPromotionActionCommand.php
If you create 2 promotions with a 100% discount for shipping, or you add the shipping action twice, 
you will receive a negative shipping cost.
This fix this issue!
=> Fix ShippingPercentageDiscountPromotionActionCommand.php

composer.json
New version GridBundle(1.7.4) need fixes because sorting by names doesn't work properly
=> [HotFix] SyliusGridBundle downgrade to 1.7.3

src/Sylius/Bundle/UiBundle/Command/DebugTemplateEventCommand.php, src/Sylius/Bundle/UiBundle/Resources/config/services/template_event.xml
| Related tickets | related to #10924
Added `sylius:debug:template-event` command:
=> Template events system - CLI command for debugging

src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php, src/Sylius/Bundle/PayumBundle/spec/Action/Paypal/ExpressCheckout/ConvertPaymentActionSpec.php
| Branch?         | 1.4 to master
| Related tickets | unknown
I was having trouble with many PayPal errors during the black friday and the error was :
`"The totals of the cart item amounts do not match order amounts."`
The bug was caused by the fact that PayPal make a validation of the total price with the sum of each item lines we build. This bug appear because all discounted prices are regrouped into an item line named "Discount" so all other lines shouldn't be filled with something related with discounts.
=> [Payum][Paypal] Use full price instead of discounted one

composer.json
This will prevent us from getting a dependency in failed state.
=> Replace unbound behat/mink dependency with tagged friends-of-behat/mink fork

docs/cookbook/images/images-on-aws-s3.rst, docs/cookbook/images/map.rst.inc, docs/cookbook/index.rst
| Related tickets | docs
Added instructions for how to store images on AWS S3, thanks to helpful instructions from @vvasiloi, taken from https://gist.github.com/vvasiloi/dc2ed665de9f38f977babce269029e27
=> [Docs] Added Docs and Instructions for how to store images on AWS-S3

src/Sylius/Bundle/UiBundle/Resources/private/js/app.js, src/Sylius/Bundle/UiBundle/Resources/views/Grid/Action/applyTransition.html.twig
works the same on all index pages with a "transition" buttons (payments, shipments, product reviews...)
=> Disabled all buttons from the column after click

app/migrations/Version20200122082429.php, docs/book/configuration/channels.rst, features/channel/managing_channels/adding_channel.feature, features/checkout/addressing_order/restricting_list_of_countries_available_for_addressing.feature, src/Sylius/Behat/Context/Setup/ChannelContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsContext.php, src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php, src/Sylius/Behat/Page/Admin/Channel/CreatePage.php, src/Sylius/Behat/Page/Admin/Channel/CreatePageInterface.php, src/Sylius/Behat/Page/Shop/Checkout/AddressPage.php, src/Sylius/Behat/Page/Shop/Checkout/AddressPageInterface.php, src/Sylius/Bundle/AddressingBundle/Form/Type/CountryChoiceType.php, src/Sylius/Bundle/AdminBundle/Resources/views/Channel/_form.html.twig, src/Sylius/Bundle/CoreBundle/Form/Extension/AddressTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/ChannelTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php, src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml, src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml, src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml, src/Sylius/Component/Core/Model/Channel.php, src/Sylius/Component/Core/Model/ChannelInterface.php, tests/Responses/Expected/channel/create_validation_fail_response.json, tests/Responses/Expected/channel/update_validation_fail_response.json
| Related tickets | fixes #9122 
Currently used only in checkout addressing to limit the list of countries. If not defined, fallbacks to the previous behaviour - all enabled countries.
=> Define countries for a channel

features/order/managing_orders/seeing_order_with_different_promotions.feature, src/Sylius/Behat/Page/Admin/Order/ShowPage.php, src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_item.html.twig
Since adjustments can have different value, picking just the first one may yield wrong results. Hence, I use the recursively fetched adjustments. Also, I added a ~ before the distributed amount to signify its variance. See #11112 for more details
| Branch?         | 1.6 or master 
| Related tickets | fixes #11112
=> Fixed wrongly calculated order-item subtotal

features/currency/managing_currencies/adding_currency.feature, features/currency/managing_currencies/browsing_currencies.feature, features/currency/managing_currencies/currency_unique_code_validation.feature, src/Sylius/Behat/Client/ApiClientInterface.php, src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Context/Api/Admin/ManagingCurrenciesContext.php, src/Sylius/Behat/Context/Api/Admin/NotificationContext.php, src/Sylius/Behat/Context/Setup/AdminApiSecurityContext.php, src/Sylius/Behat/Resources/config/services.xml, src/Sylius/Behat/Resources/config/services/api.xml, src/Sylius/Behat/Resources/config/services/api_clients.xml, src/Sylius/Behat/Resources/config/services/contexts/api.xml, src/Sylius/Behat/Resources/config/services/contexts/setup.xml, src/Sylius/Behat/Resources/config/suites/ui/currency/managing_currencies.yml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Currency.xml
=> Currencies API + first approach to API Behat tests

config/packages/framework.yaml, features/product/managing_product_options/adding_product_option.feature, features/product/managing_product_options/browsing_product_options.feature, src/Sylius/Behat/Client/ApiClientInterface.php, src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Context/Api/Admin/ManagingCurrenciesContext.php, src/Sylius/Behat/Context/Api/Admin/ManagingProductOptionsContext.php, src/Sylius/Behat/Context/Api/Admin/NotificationContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingProductOptionsContext.php, src/Sylius/Behat/Resources/config/services/contexts/api.xml, src/Sylius/Behat/Resources/config/suites.yml, src/Sylius/Behat/Resources/config/suites/api/currency/managing_currencies.yml, src/Sylius/Behat/Resources/config/suites/api/product/managing_product_options.yml, src/Sylius/Behat/Resources/config/suites/ui/product/managing_product_options.yml, src/Sylius/Bundle/ApiBundle/Behat/Extension/SyliusApiBundleExtension.php, src/Sylius/Bundle/ApiBundle/Behat/Tester/ApiScenarioEventDispatchingScenarioTester.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionValue.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOption.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionTranslation.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionValue.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionValueTranslation.xml
PR consists of API for creation and indexing product options (with product option values as sub-resources):
It also contains a PoC of the Behat extension, that does not allow to run a javascript session for API scenarios with multiple tags (like `@ui @javascript @api`) 💃
=> [API] Product options (with values) creation and index

src/Sylius/Bundle/CoreBundle/spec/OAuth/UserProviderSpec.php, src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php, src/Sylius/Bundle/UserBundle/spec/Provider/EmailProviderSpec.php, src/Sylius/Bundle/UserBundle/spec/Provider/UsernameOrEmailProviderSpec.php, src/Sylius/Bundle/UserBundle/spec/Provider/UsernameProviderSpec.php
| Branch?         | 1.5 and more
| Related tickets | fixes #10879 
UserProvider should throw UnsupportedUserException and not UnexpectedValueException.
=> user provider fix exception

features/product/managing_product_options/adding_product_option.feature, features/product/managing_product_options/editing_product_option.feature, features/product/managing_product_options/managing_values_of_product_option.feature, features/product/managing_product_options/product_option_unique_code_validation.feature, features/product/managing_product_options/product_option_validation.feature, src/Sylius/Behat/Client/ApiClientInterface.php, src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Context/Api/Admin/ManagingProductOptionsContext.php, src/Sylius/Behat/Context/Api/Admin/NotificationContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingProductOptionsContext.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionTranslation.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOption.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionTranslation.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionValue.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductOptionValueTranslation.xml
=> [API] Product options - update vol.1

src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Block/_legacySonataEvent.html.twig, src/Sylius/Bundle/UiBundle/DependencyInjection/Compiler/LegacySonataBlockPass.php, src/Sylius/Bundle/UiBundle/Resources/config/services/twig.xml, src/Sylius/Bundle/UiBundle/Resources/views/Block/_legacySonataEvent.html.twig, src/Sylius/Bundle/UiBundle/SyliusUiBundle.php, src/Sylius/Bundle/UiBundle/Twig/LegacySonataBlockExtension.php
| Related tickets | fixes #11120
All classes added as internal, the Twig function is not supposed to be used by end-users.
=> Filter variables passed to legacy Sonata block events

src/Sylius/Bundle/UiBundle/Block/BlockEventListener.php, src/Sylius/Bundle/UiBundle/Command/DebugTemplateEventCommand.php, src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockDataCollector.php, src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockRenderingHistory.php, src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateBlockRenderer.php, src/Sylius/Bundle/UiBundle/DataCollector/TraceableTemplateEventRenderer.php, src/Sylius/Bundle/UiBundle/DependencyInjection/Compiler/LegacySonataBlockPass.php, src/Sylius/Bundle/UiBundle/DependencyInjection/SyliusUiExtension.php, src/Sylius/Bundle/UiBundle/Registry/TemplateBlock.php, src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistry.php, src/Sylius/Bundle/UiBundle/Registry/TemplateBlockRegistryInterface.php, src/Sylius/Bundle/UiBundle/Renderer/DelegatingTemplateEventRenderer.php, src/Sylius/Bundle/UiBundle/Renderer/HtmlDebugTemplateBlockRenderer.php, src/Sylius/Bundle/UiBundle/Renderer/HtmlDebugTemplateEventRenderer.php, src/Sylius/Bundle/UiBundle/Renderer/TemplateBlockRendererInterface.php, src/Sylius/Bundle/UiBundle/Renderer/TemplateEventRendererInterface.php, src/Sylius/Bundle/UiBundle/Renderer/TwigTemplateBlockRenderer.php, src/Sylius/Bundle/UiBundle/Twig/LegacySonataBlockExtension.php, src/Sylius/Bundle/UiBundle/Twig/TemplateEventExtension.php
| Related tickets | related to #10997
Marking the implementation of template events as experimental, so that some changes can be made in 1.8 release (not too much probably). The end-user API (`sylius_template_event` Twig method and `sylius_ui` configuration) will always stay the same.
=> Mark new template events implementation as experimental

UPGRADE-1.7.md
I believe we should also delete [this migration file](https://github.com/Sylius/Sylius-Standard/blob/1.7/src/Migrations/Version20191119131635.php) due to https://github.com/Sylius/Sylius/pull/11053
=> Fix UPGRADE-1.7 file

features/product/managing_product_reviews/recalculating_product_average_rating.feature, psalm.xml, src/Sylius/Behat/Client/ApiClientInterface.php, src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Context/Api/Admin/ManagingProductReviewsContext.php, src/Sylius/Behat/Context/Transform/ProductReviewContext.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services.xml, src/Sylius/Bundle/ApiBundle/spec/Applicator/ProductReviewStateMachineTransitionApplicatorSpec.php
=> [API][Product review] Minor fixes after product review api merged

features/payment/managing_payments/browsing_payments.feature, src/Sylius/Behat/Client/ApiClientInterface.php, src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php, src/Sylius/Behat/Context/Setup/OrderContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentsContext.php, src/Sylius/Behat/Resources/config/services/contexts/api.xml, src/Sylius/Behat/Resources/config/suites.yml, src/Sylius/Behat/Resources/config/suites/api/payment/managing_payments.yml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/PaymentMethod.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Order.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Payment.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/PaymentMethod.xml
=> [API] Browsing payments

src/Sylius/Bundle/AdminBundle/Resources/views/Channel/_form.html.twig
| Branch?         | ^1.0 I think, master otherwise 
I really prefer to show `https://` instead of `http://` in the Channel form, it's a way to say "Hey, keep the web secure!".
And it doesn't change that much.
It could be `http(s)://` as well…
As you prefer!
=> Use https instead of http for Channel's hostname in form

features/product/managing_products/adding_product.feature, src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php, src/Sylius/Behat/Resources/config/services/api.xml, src/Sylius/Behat/Resources/config/services/contexts/api.xml, src/Sylius/Behat/Resources/config/suites.yml, src/Sylius/Behat/Resources/config/suites/api/product/managing_products.yml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductTranslation.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Product.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/ProductTranslation.xml
=> [API] [Product] [ProductTranslation] Add api configuration and test for adding product and product translations

features/shipping/managing_shipments/shipping_a_shipment_from_shipment_list.feature, src/Sylius/Behat/Client/ApiClientInterface.php, src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Context/Api/Admin/ManagingShipmentsContext.php, src/Sylius/Bundle/ApiBundle/Applicator/ShipmentStateMachineTransitionApplicator.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Shipment.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShipmentUnit.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serializer/Shipment.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services.xml, src/Sylius/Bundle/ApiBundle/spec/Applicator/ShipmentStateMachineTransitionApplicatorSpec.php
=> [API] shipping shipment with tracking code + minor fixes

docs/components_and_bundles/bundles/SyliusFixturesBundle/custom_fixture.rst
The interface is already implemented by the abstract class. Also add a missing use statement.
=> Remove useless interface in custom_fixture.rst

src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml, src/Sylius/Bundle/AdminBundle/Resources/views/layout.html.twig
| Related tickets | similar to https://github.com/Sylius/Sylius/pull/11212
Without this configuration, there was a problem on login page with stylesheets :(
=> [UI] Fix stylesheets problem on the login page

docs/plugin-development-guide/naming.rst
After you have change name of plugin, please run composer install in your main directory. Else you have this error :  PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Kernel" from namespace
=> Add Important information in documentation when change name of plugin

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
before you can add some request, after this change is will be impossible
before:
after:
it looks the same on all edited resources
=> [API] disable input on stateMachine transition endpoints

src/Sylius/Bundle/ShopBundle/Resources/views/Order/show.html.twig
Fix missing form style declaration "form_theme" in Order/show.html.twig for "@SyliusShop/Checkout/SelectPayment/_form.html.twig" include.
This file is also included in the Checkout/selectPayment.html.twig file, where "form_theme" is declared correctly.
=> [ShopBundle] Add missing form_theme declaration

src/Sylius/Component/Order/Model/OrderItemUnit.php
| Bug fix?        | no (kinda)
| Related tickets | ----
This pull request moves the initialization of the object's property before the logic that this object executes. The reason for this change is if the methods that are called because of the `addUnit` function require the adjustments to be set, then those will crash because the property has not been initialized yet.
=> Initializing adjustments before the order item is processed

.travis.yml, composer.json, etc/travis/suites/packages/before_install.sh, psalm.xml, src/Sylius/Bundle/ShopBundle/Calculator/OrderItemsSubtotalCalculator.php, src/Sylius/Bundle/ShopBundle/Calculator/OrderItemsSubtotalCalculatorInterface.php, src/Sylius/Bundle/ShopBundle/Resources/config/services.xml, src/Sylius/Bundle/ShopBundle/Resources/config/services/twig.xml, src/Sylius/Bundle/ShopBundle/Tests/Calculator/OrderItemsSubtotalCalculatorTest.php, src/Sylius/Bundle/ShopBundle/Twig/OrderItemsSubtotalExtension.php, src/Sylius/Bundle/ShopBundle/composer.json, symfony.lock
I'd like to be able to use the logic for calculating the subtotal of all order items outside of Twig templates, hence this separation.
=> Separated order items subtotal calculation logic from twig extension

etc/travis/suites/application/before_install.sh
Temporary solution, to make build green again. However, we should take a look into memory consumption in our builds and reduce it.
=> [Maintenance][Travis] Upgrade php memory to 6G

src/Sylius/Bundle/ShopBundle/EventListener/NonChannelLocaleListener.php
Ignore channel locale listener on profiler search & results routes
| Branch?         | 1.6, 1.7 or master 
| Related tickets | fixes #11362
=> fix #11362 : ignore channel locale listener on profiler routes

.github/autolabeler.yml
As a _General Hater of Not-labeled Pull Requests_, to help our work easier, I would like to introduce a https://github.com/apps/probot-autolabeler.
I'm not sure if it's **the best** choice from auto labelling bots, but it has one big advantage - can label PRs from forked repositories (which is crucial for Sylius). It has also a very simple configuration (which is both ➕ and ➖), so maybe we would have to modify it (or replace with something better) to handle some more sophisticated algorithms for labels 🏇 
This is just a first version of configuration - when it's merged, I would love …
=> Introduce Probot Autolabeler

UPGRADE-1.7.md
Using the old files leads to a not found template error in Front or Admin.
| Branch?         | 1.7 or master, I don't know if we consider this as a bug fix or not :p 
| Bug fix?        | yes or no… for me yes, for others no.
This PR is quite simple. I've just added some information about the move of some templates.  
I was using these templates and faced the issue in production since it was an edge case.  
Better to tell than sorry.
=> Add notice about moved templates during upgrade

composer.json, psalm.xml, src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/CustomerGroupExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/PaymentMethodExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAssociationTypeExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAttributeExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductOptionExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductReviewExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingCategoryExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingMethodExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxCategoryExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxRateExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxonExampleFactory.php, src/Sylius/Bundle/ShopBundle/EventListener/NonChannelLocaleListener.php, src/Sylius/Component/Core/OrderProcessing/OrderPricesRecalculator.php, src/Sylius/Component/Currency/Model/ExchangeRate.php
In all the latest builds, Psalm is in fatal error, here is a PR to update and correct it.
Example : https://travis-ci.org/github/Sylius/Sylius/jobs/677090470#L2593
> vendor/bin/psalm --show-info=false
PHP Fatal error:  Uncaught Psalm\Exception\TypeParseTreeException: Unterminated bracket in /home/travis/build/Sylius/Sylius/vendor/vimeo/psalm/src/Psalm/Internal/Type/ParseTree.php:571
=> [DX] update Psalm version

src/Sylius/Bundle/AdminBundle/Resources/private/sass/_ui.scss, src/Sylius/Bundle/UiBundle/Resources/private/sass/_variables.scss
Without `!default` it's not possible to override those variables in SCSS.
=> Use !default for SCSS variables to allow overriding them

docs/book/orders/promotions.rst
| Related tickets | fixes #9689 
=> Remove the doc reference to a promotion action that no longer exists in Core.

src/Sylius/Bundle/LocaleBundle/Templating/Helper/LocaleHelper.php, src/Sylius/Bundle/LocaleBundle/spec/Templating/Helper/LocaleHelperSpec.php
Prevents a 500 error if the locale code has no associated name in the Intl database. Example with `en_DG`:
=> Fallback to the locale code if the associated name isn't found

composer.json
Should fix the build for now, until some braking changes would be fixed on API Platform itself.
=> [Hot-fix] Conflict API Platform 2.5.5 to fix the build

src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/create.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/index.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/update.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/index.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/show.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Account/changePassword.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Account/dashboard.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Account/profileUpdate.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Account/requestPasswordReset.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Account/resetPassword.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Cart/summary.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/address.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/complete.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/layout.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectPayment.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectShipping.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Contact/request.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Order/show.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Order/thankYou.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/index.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/show.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/create.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/login.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/register.html.twig
| Deprecations?   | yes 
Having "Sylius" displayed in the `<title>` of every pages by default is weird and can be bad for SEO. I suggest to display the name of the current channel instead.
=> Add title on most pages

src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-form-collection.js, src/Sylius/Bundle/UiBundle/Resources/views/Form/imagesTheme.html.twig, src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
If there are nested form collections, the value `__name__` of the sub
collection is being replaced by the parent collection index.
Which makes every new sub collection items having the same index.
| Related tickets | fixes #9738
=> Bug #9738 Fix nested form collections

docs/cookbook/shop/disabling-localised-urls.rst
| Branch?         | >1.6
SImple typo in documentation. The last `"` shouldn't be here.
=> Typo in code block in documentation

UPGRADE-1.8.md, src/Sylius/Bundle/CoreBundle/Mailer/Emails.php, src/Sylius/Bundle/OrderBundle/SyliusExpiredCartsEvents.php, src/Sylius/Bundle/UserBundle/UserEvents.php, src/Sylius/Component/Addressing/Model/Scope.php, src/Sylius/Component/Core/Model/Scope.php, src/Sylius/Component/Core/OrderCheckoutStates.php, src/Sylius/Component/Core/OrderCheckoutTransitions.php, src/Sylius/Component/Core/OrderPaymentStates.php, src/Sylius/Component/Core/OrderPaymentTransitions.php, src/Sylius/Component/Core/OrderShippingStates.php, src/Sylius/Component/Core/OrderShippingTransitions.php, src/Sylius/Component/Core/ProductReviewTransitions.php, src/Sylius/Component/Core/SyliusLocaleEvents.php, src/Sylius/Component/Order/CartActions.php, src/Sylius/Component/Order/OrderTransitions.php, src/Sylius/Component/Order/SyliusCartEvents.php, src/Sylius/Component/Payment/PaymentTransitions.php, src/Sylius/Component/Shipping/Calculator/DefaultCalculators.php, src/Sylius/Component/Shipping/ShipmentTransitions.php
Final classes, which holds consts has been changed to interfaces. Therefore, still, no one is able to initialize them, while we are open to multi inheritance.  This should remove the problem of adding new values to them in plugins and end applications.
=> [RFC][DX] Open consts holder classes

src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/PromotionFixture.php, src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml, src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
This adds the possibility to define coupons in promotion fixtures.
```yaml
...
promotion:
options:
custom:
test:
name: 'Test'
coupon_based: true
coupons:
- code: 'abc'
- code: 'abcde'
expires_at: 'tomorrow'
usage_limit: 10
per_customer_usage_limit: 1
reusable_from_cancelled_orders: true
```
=> Promotion fixture coupons

docs/theming/bootstrap-theme.rst, docs/theming/index.rst, docs/theming/webpack.rst
Mentioned "master" branch is now "v1.7.x" tag.
=> [Docs] Remove experimental badges mentioning "master" branch from theming guide

docs/_exts/sphinxcontrib-redirects/__init__.py
The redirections map defined in `docs/redirection_map` works correctly for local builds but is skipped for docs hosted on ReadTheDocs because they use `readthedocs` builder instead of `html` one.
This PR should fix that (I hope so). Aiming at 1.6 because it's the earliest branch in which we wanted to create redirections.
=> [Docs] Enable redirections on ReadTheDocs

docs/cookbook/shop/facebook-login.rst
| Branch?         | At least from 1.6
Hello,
I'm working on a website in Sylius 1.6 with one locale (mywebsite.com/fr_FR), and I want to add Facebook login.
If I put the path `/login`, Facebook will redirect to mywebsite.com/login which fail (blank page with only a link to facebook).
But if I put the route name, the path will be `/fr_FR/login`, which works fine (for me at least)
=> [Documentation][Cookbook] Fix login & failure path

src/Sylius/Behat/Context/Setup/ChannelContext.php
Make `Sylius\Behat\Context\Setup\ChannelContext::storeOperatesOnASingleChannelInTheUnitedStatesNamed` behave same as `Sylius\Behat\Context\Setup\ChannelContext::theStoreOperatesOnAChannelNamed` regarding channel's name and code
=> [Behat] Consistent channel setup context

features/product/managing_products/filtering_products_by_channel.feature, src/Sylius/Behat/Context/Setup/ProductContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php, src/Sylius/Behat/Page/Admin/Product/IndexPage.php, src/Sylius/Behat/Page/Admin/Product/IndexPageInterface.php, src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml, src/Sylius/Bundle/AdminBundle/Resources/config/grids/product.yml, src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php, src/Sylius/Bundle/CoreBundle/Form/Type/Grid/Filter/EntitiesFilterType.php, src/Sylius/Bundle/CoreBundle/Resources/config/services.xml, src/Sylius/Bundle/UiBundle/Resources/views/Grid/Filter/entities.html.twig, src/Sylius/Component/Core/Grid/Filter/EntitiesFilter.php
=> [Feature] Products filtering by channel

features/product/viewing_product_in_admin_panel/viewing_details_of_simple_product.feature, src/Sylius/Behat/Context/Setup/ProductContext.php, src/Sylius/Behat/Context/Ui/Admin/ProductShowPageContext.php, src/Sylius/Behat/Element/Product/ShowPage/DetailsElement.php, src/Sylius/Behat/Element/Product/ShowPage/DetailsElementInterface.php, src/Sylius/Behat/Element/Product/ShowPage/PricingElement.php, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_pricing.html.twig
| Branch?         | 1.6 and after
| Related tickets | fixes #11399 
Behat :
@ui
Scenario: Viewing price block without channel enable
Given this product is unavailable in "United States" channel
When I access "Iron shield" product page
Then I should see product name "Iron shield"
And I should see the product in neither channel
And I should not see price for channel "United States"
Before fix step `Then I should see product name "Iron shield"` throw error in cause of error 500 in page.
After fix, all steps are green :heavy_check_mark:
=> Error on show product without pricing

src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_moreDetails.html.twig
=> Fix for product translation tabs to be folded by default

UPGRADE-1.7.md, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/Types/boolean.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/Types/date.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/Types/datetime.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/Types/default.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/Types/percent.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/Types/text.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_attributes.html.twig, src/Sylius/Bundle/AttributeBundle/Resources/views/Types/checkbox.html.twig, src/Sylius/Bundle/AttributeBundle/Resources/views/Types/date.html.twig, src/Sylius/Bundle/AttributeBundle/Resources/views/Types/datetime.html.twig, src/Sylius/Bundle/AttributeBundle/Resources/views/Types/default.html.twig, src/Sylius/Bundle/AttributeBundle/Resources/views/Types/percent.html.twig, src/Sylius/Bundle/AttributeBundle/Resources/views/Types/select.html.twig, src/Sylius/Bundle/AttributeBundle/Resources/views/Types/textarea.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Tabs/Attributes/_list.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Types/checkbox.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Types/date.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Types/datetime.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Types/default.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Types/percent.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Types/select.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/Types/textarea.html.twig
| Related tickets | fixes #11365
=> [Attribute] Bring back attribute types templates after BC break in 1.7

src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml, src/Sylius/Component/Core/spec/Locale/Context/StorageBasedLocaleContextSpec.php
After changes from this pr: https://github.com/Sylius/Sylius/pull/10565
Fix broken edit channel page and add product to cart page
Problem was in fixtures, in resolving locales and countries, for United Kingdom locale `en_UK` not working properly.  For properly working it need `en_GB`
=> [Countries]Add fixes for broken edit channel page and add product to cart

src/Sylius/Bundle/CoreBundle/Fixture/Factory/AddressExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php
When loading of a fixture fails because the factory can not find the objects it should attach to  precise error messages are very helpful.
Before:
After:
=> Making error messages in example factories more descriptive

features/product/viewing_products/viewing_different_discounted_price_for_different_product_variants.feature, src/Sylius/Behat/Context/Setup/ProductContext.php, src/Sylius/Behat/Context/Ui/Shop/ProductContext.php, src/Sylius/Behat/Page/Shop/Product/ShowPage.php, src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php, src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-variants-prices.js, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_price.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_variants.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_variantsPricing.html.twig, src/Sylius/Component/Core/Provider/ProductVariantsPricesProvider.php, src/Sylius/Component/Core/spec/Provider/ProductVariantsPricesProviderSpec.php
Follows up @lchrusciel's comment on #11423 about variant prices not updating on the product page or variant not displaying discount if the first variant of the product has no discount.
=> [UI] added display of product variant original price on product page

features/cart/shopping_cart/viewing_cart_summary.feature, src/Sylius/Behat/Client/ApiClientInterface.php, src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Client/Request.php, src/Sylius/Behat/Client/RequestInterface.php, src/Sylius/Behat/Context/Api/Admin/ManagingOrdersContext.php, src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php, src/Sylius/Behat/Context/Api/Shop/CartContext.php, src/Sylius/Behat/Resources/config/services/api.xml, src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml, src/Sylius/Behat/Resources/config/suites.yml, src/Sylius/Behat/Resources/config/suites/api/cart/shopping_cart.yml, src/Sylius/Bundle/ApiBundle/Command/PickupCart.php, src/Sylius/Bundle/ApiBundle/CommandHandler/PickupCartHandler.php, src/Sylius/Bundle/ApiBundle/PropertyInfo/Extractor/EmptyPropertyListExtractor.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml, src/Sylius/Bundle/ApiBundle/spec/CommandHandler/PickupCartHandlerSpec.php, src/Sylius/Bundle/ApiBundle/spec/PropertyInfo/Extractor/EmptyPropertyListExtractorSpec.php
| Related tickets | Related to #11250
=> [API] Pick up cart implementation

src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
| Related tickets | fixes #10466
I suggest adding support for form helpers.
**By adding a helper in a back office form**
```php
->add('plainPassword', PasswordType::class, [
'label' => 'sylius.form.user.password.label',
'help' => 'sylius.form.user.password.help',
])
```
Look like (Without any other changes, css, ...)
**By adding a helper in a front office form**
```php
->add('newPassword', RepeatedType::class, [
'type' => PasswordType::class,
'first_options' => [
'label' => 'sylius.form.user_change_password.new',
'help' => 'sylius.form.user_change_password.help',
],
'second_options' => ['label' => …
```
=> [UI] add form helper

src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_payment.yml, src/Sylius/Component/Core/StateResolver/OrderPaymentStateResolver.php, src/Sylius/Component/Core/spec/StateResolver/OrderPaymentStateResolverSpec.php
OrderPaymentStateResolver should resolve awaiting_payment state when there is payment under processing. This is needed to handle asynchronous payment confirmation.
> For asynchronous payment methods, it can take up to several days to confirm whether the payment has been successful. During this time, the payment cannot be guaranteed. The status of the payment’s Charge object is initially set to pending, until the payment has been confirmed as successful or failed. ACH debits are an example of an asynchronous method: with these debits, it takes a few days to confirm that the payment has succeeded.
https://stripe.com/docs/sources#synchronous-or-asynchronous-confirmation
| BC …
=> Resolve awaiting_payment state in resolver

src/Sylius/Bundle/PayumBundle/DependencyInjection/Compiler/RegisterGatewayConfigTypePass.php, src/Sylius/Bundle/PayumBundle/Resources/config/services/form.xml, src/Sylius/Bundle/PayumBundle/Tests/DependencyInjection/Compiler/RegisterGatewayConfigTypePassTest.php
`sylius.gateway_factories` parameter stays the same, priority is only used to order gateways - and therefore to display them in proper order in the admin panel.
If priority is not set, it's `0` by default.
=> Add priority to payment gateways

src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-notification.js
Don't make unnecessary backend calls if the notification bar is missing (eg. disabled).
| Related tickets | fixes #11604
=> Don't call the backend if the notification bar is disabled

src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_inventory.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/ProductVariant/Tab/_inventory.html.twig, src/Sylius/Bundle/CoreBundle/Form/Extension/ProductVariantTypeExtension.php, src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
| Related tickets | fixes #11518
Adding a little help text to the tracked flag of Sylius inventory.
=> Adding help to the tracking

docs/requirements.txt
After release new version of https://github.com/fabpot/sphinx-php we must downgrade sphinx to `1.8.5` through fault: https://github.com/fabpot/sphinx-php/issues/46
=> [Docs] Fix build - Downgrade sphinx to v1.8.5

src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml, src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
We are currently building some themes and having this could be very useful.
The previous behavior is kept.
=> Use env:SYLIUS_FIXTURES_THEME_NAME to set the theme in fixtures

src/Sylius/Bundle/ShopBundle/Resources/private/entry.js
Commit f3e5661476d1ca5d03658ed2267ebf5492c5ec21 added slick-carousel/slick/slick.css to src/Sylius/Bundle/ShopBundle/gulpfile.babel.js
If you want to use webpack encore, you should add slick-carousel/slick/slick.css to entry.js too
Related to https://github.com/Sylius/Sylius/pull/11631
| Branch?              | 1.7 or master 
| Bug fix?              | yes
| New feature?     | no
| BC breaks?        | no
| Related tickets  | 
| License              | MIT
=> Add slick-carousel to ShopBundle entry.js

src/Sylius/Bundle/ShopBundle/Resources/private/entry.js
| Bug fix?        | yes, kind of…
These two lines are really missing if you want to build the theme with webpack.
=> Add missing images in entry.js

app/migrations/Version20171003103916.php
_Previous title: Add method findTypeForMigration to ProductAttributeRepository_
| Related tickets | fixes #11592
I don't know how to test these except by running the database migrations.  
So…
I've added the repository in Core because I think it is where it belongs since
the Migrations are in the main App.
=> Fix migration

UPGRADE-1.8.md, src/Sylius/Behat/Context/Ui/EmailContext.php, src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml, src/Sylius/Bundle/AdminBundle/Resources/views/Email/shipmentConfirmation.html.twig
| Bug fix?        | yes (translation issue in French language…)
See this discussion on Crowdin: <https://crowdin.com/translate/sylius/981/en-fr#34209>.
The way the sentence was handled gives a bad translation in French since we need to
change the order of the 3 elements previously involved.
Using a placeholder `%tracking_code%` here will allow to have a correct translation
in all languages.
=> Use a placeholder in tracking code sentence in shipment email

src/Sylius/Bundle/AdminApiBundle/Command/CreateClientCommand.php, src/Sylius/Bundle/CoreBundle/Command/CancelUnpaidOrdersCommand.php, src/Sylius/Bundle/CoreBundle/Command/CheckRequirementsCommand.php, src/Sylius/Bundle/CoreBundle/Command/InformAboutGUSCommand.php, src/Sylius/Bundle/CoreBundle/Command/InstallAssetsCommand.php, src/Sylius/Bundle/CoreBundle/Command/InstallCommand.php, src/Sylius/Bundle/CoreBundle/Command/InstallDatabaseCommand.php, src/Sylius/Bundle/CoreBundle/Command/InstallSampleDataCommand.php, src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php, src/Sylius/Bundle/CoreBundle/Command/ShowAvailablePluginsCommand.php, src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php, src/Sylius/Bundle/PromotionBundle/Command/GenerateCouponsCommand.php, src/Sylius/Bundle/UserBundle/Command/DemoteUserCommand.php, src/Sylius/Bundle/UserBundle/Command/PromoteUserCommand.php
This commit is about of a little optimisation to avoid initialisation of all command services on each executing `bin/console` command.
Since Symfony 3.4 console commands can be lazy thanks to [a static name property](https://github.com/symfony/symfony/pull/23887).
This change does not break BC because the BC layer is already [in the base command's constructor](https://github.com/symfony/symfony/pull/23887/files#diff-8e80595663798837db1b033187835535R75).
=> Make console commands lazy

src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/Statistics/_perChannel.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Form/theme.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Macro/translationForm.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/PaymentMethod/_form.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Attribute/attributesCollection.html.twig
I just found this and I think it's easier to read `loop.first` than `0 == loop.index0`…
=> Loop.first is easier to 0 == loop.index0

src/Sylius/Bundle/ApiBundle/Resources/config/services.xml, src/Sylius/Bundle/ApiBundle/Swagger/AdminAuthenticationTokenDocumentationNormalizer.php, src/Sylius/Bundle/ApiBundle/Swagger/ShopAuthenticationTokenDocumentationNormalizer.php
fixes #11483
| Related tickets | fixes #11483
when you change the new api route in the parameters, it will now correctly reflect in the documentation
=> ensure swagger docs route matches the configured new api route

UPGRADE-1.8.md, config/packages/security.yaml, config/routes/sylius_admin.yaml, src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml
| New feature?    | yes, kind of
| BC breaks?      | I'm not sure. This PR doesn't change the routes but it allows it…
We always change the admin route URL. By default `/admin` is unsecure, it's too
easy to guess.
We wanted to ease this change by using an environment variable.
All plugins using `/admin` hard coded will have to use the dynamic `/%sylius_admin.path_name%` value instead.
=> Use env(SYLIUS_ADMIN_ROUTING_PATH_NAME) as admin's route name

src/Sylius/Bundle/ApiBundle/ApiPlatform/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php
Will be broken with this RFC - https://wiki.php.net/rfc/namespaced_names_as_token on PHP 8.
See https://wiki.php.net/rfc/namespaced_names_as_token#backward_incompatible_changes
UPD: fixed branch in description
=> Fix space position

docs/theming/webpack.rst
The file "templates/bundles/SyliusAdminBundle/_logo.html.twig" overrides "src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_logo.html.twig" but only the asset location should change.
Currently the documentation suggests to remove all the HTML of the template and to replace it with only the asset path, this is not correct.
| Branch?         | 1.7 or master 
=> [DOC] Fix webpack usage with appropriate _logo.html.twig template

composer.json
=> [Hot-Fix] Add conflict to symfonyą/form 4.11 and nikic/php-parser 4.7

psalm.xml, src/Sylius/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php, src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php
I've removed two unneeded docblocks, but most of the problems were caused by the `Assert::` methods usage. We could, in theory, remove the docblocks there as well, but it would result in the PHPStorm (or some other IDE) not detecting the types properly... That's why it's a hot-fix 💃
=> [Hot-fix] Handle extra docblocks in Psalm

features/checkout/accessing_order_right_after_completing_checkout.feature, src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php, src/Sylius/Behat/Context/Api/Shop/OrderContext.php, src/Sylius/Behat/Context/Ui/Shop/CheckoutContext.php, src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml, src/Sylius/Behat/Resources/config/suites/api/checkout/checkout.yml
=> [Api][Checkout][Order] Add tests for accessing order right after completing checkout

features/user/managing_customers/adding_customer_account.feature, src/Sylius/Bundle/CoreBundle/EventListener/DefaultUsernameORMListener.php
If applied, this commit will
-make sync behavior works on both customer and shop user,
resulting in username will never by setting username value whenever
shop user or customer is inserted or updated.
| Branch?         | 1.6 or master 
| Related tickets | fixes #10951
I could have used the solution proposed here 
https://github.com/Sylius/Sylius/issues/10951#issuecomment-566190560
but it might be better if the username is always in sync with customer email
=> Bug #10951 [Account] fix sync username with customer email

docs/customization/fixtures.rst
Removed the word "extended" that was used twice
=> [Documentation] fix typo in fixture docs

src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_moreDetails.html.twig
To be consistent with https://github.com/Sylius/Sylius/pull/8347 administrative interface should convert newlines in product description to breaklines in product details view
=> [Admin] Convert newlines in product description to breaklines 

src/Sylius/Component/Channel/Context/RequestBased/ChannelContext.php
| Deprecations?   | no (fixing them)
| Related tickets | -none-
When resolving the hostname in dev-mode it generates a lot of calls to exceptions:
This will keep the same error message but uses the new function signiture.
=> Fixing the ChannelContext deprecations

features/addressing/managing_zones/deleting_multiple_zones.feature, features/channel/managing_channels/deleting_multiple_channels.feature, features/currency/managing_exchange_rates/deleting_multiple_exchange_rates.feature, features/payment/managing_payment_methods/deleting_multiple_payment_methods.feature, features/product/managing_product_association_types/deleting_multiple_product_association_types.feature, features/product/managing_product_attributes/deleting_multiple_product_attributes.feature, features/product/managing_product_options/deleting_multiple_product_options.feature, features/product/managing_product_reviews/deleting_multiple_product_reviews.feature, features/product/managing_product_variants/deleting_multiple_product_variants.feature, features/product/managing_products/deleting_multiple_products.feature, features/promotion/managing_coupons/deleting_multiple_coupons.feature, features/promotion/managing_promotions/deleting_multiple_promotions.feature, features/shipping/managing_shipping_categories/deleting_multiple_shipping_categories.feature, features/shipping/managing_shipping_methods/deleting_multiple_shipping_methods.feature, features/taxation/managing_tax_categories/deleting_multiple_tax_categories.feature, features/taxation/managing_tax_rates/deleting_multiple_tax_rates.feature, features/user/managing_administrators/deleting_multiple_administrators.feature, features/user/managing_customer_groups/deleting_multiple_customer_groups.feature, src/Sylius/Behat/Page/Admin/Crud/IndexPage.php, src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-bulk-action-require-confirmation.js, src/Sylius/Bundle/UiBundle/Resources/views/Macro/buttons.html.twig, src/Sylius/Bundle/UiBundle/Resources/views/Macro/table.html.twig
This reverts commit 4013e51dfdd3ff7d5bd00f2751308eac2bb3149a.
Related to this issue https://github.com/Sylius/Sylius/issues/11324
Custom bulk action can't work cause of the id #bulk-delete wich has been had in the reverted commit.
=> Revert "[Behat] Remove js requirement for bulk delete scenarios"

src/Sylius/Bundle/AdminBundle/Resources/views/Customer/_form.html.twig
Edit the form_errors location to fix the display on Customer/_form.html.twig
Before:
After:
=> Fix Customer form_errors display

src/Sylius/Bundle/CoreBundle/Fixture/OptionsResolver/LazyOption.php
| Related tickets | (none)
Making the error message more helpful. When running the fixtures you might run into this error: 
```                                 
[InvalidArgumentException]              
Expected a non-empty value. Got: array  
```
Which is very undescriptive. But looking at the stacktrace it is clear that it's from the LazyOption. And would be much more helpful with this:
```
[InvalidArgumentException]
No items found for Sylius\Component\Core\Model\Promotion
```
What do you think?
=> Making the error message on fixutre load helpful

UPGRADE-1.7.md
This change (using the billing address instead of shipping address to calculate taxes) is actually a BIG change. It changed all our tax calculation and we didn't see that coming. 😭
=> Add warning on tax calculation in 1.7's upgrade

config/packages/security.yaml, src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Client/Request.php, src/Sylius/Behat/Client/RequestInterface.php, src/Sylius/Behat/Resources/config/services/api.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AdminUser.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/AvatarImage.xml
=> [Api][Administrator] refactor endpoints for admin and admin avatar

src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_headerTitle.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Index/_headerTitle.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_headerTitle.html.twig
@lchrusciel I think this is one of most unexpected BC breaks.
Fatal error due to type-hint change:
```
/**
* @param string $id
*/
public function trans($id, array $parameters = [], string $domain = null, string $locale = null);
public function trans(string $id, array $parameters = [], string $domain = null, string $locale = null);
```
=> Fixed Twig translate extension not working with `null` values

src/Sylius/Bundle/ApiBundle/Resources/config/validation/RegisterShopUser.xml, src/Sylius/Bundle/CoreBundle/Resources/config/validation/AdminUser.xml, src/Sylius/Bundle/CoreBundle/Resources/config/validation/Channel.xml, src/Sylius/Bundle/CustomerBundle/Resources/config/validation/Customer.xml, src/Sylius/Bundle/UserBundle/Resources/config/validation/PasswordResetRequest.xml
=> Fixed deprecated option usage on Email validator

src/Sylius/Bundle/CoreBundle/Form/Extension/CartItemTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/CartTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/ChannelTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/CountryTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/CustomerTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/LocaleTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/OrderTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/PaymentMethodTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/ProductTranslationTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/ProductTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/ProductVariantGenerationTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/ProductVariantTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/PromotionCouponTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/PromotionFilterCollectionTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/PromotionTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/ShippingMethodTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/TaxRateTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Extension/TaxonTypeExtension.php, src/Sylius/Bundle/PayumBundle/Form/Extension/CryptedGatewayConfigTypeExtension.php
Error with newer Symfony:
```bash
PHP Fatal error:  Class Sylius\Bundle\CoreBundle\Form\Extension\ChannelTypeExtension contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Form\FormTypeExtensionInterface::getExtendedTypes)
```
=> Add missing new method into form extensions

src/Sylius/Bundle/UiBundle/composer.json
| Branch?         | 1.7 (will target 1.8 also later)
there is no v4 need and it limits compatibility with other bundles, I believe this was mainly done to achieve compatibility with
symfony 5, but if you are still on symfony 4 its fine to use sonata-project/block-bundle: 3
=> allow sonata block bundle v3

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductAssociationType.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOption.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionValue.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml
Example on "Product" resource
Before changes:
After changes:
=> [API]add to swagger documentation missing locale code in translations

src/Sylius/Bundle/ApiBundle/Command/Checkout/AddressOrder.php, src/Sylius/Bundle/ApiBundle/Resources/config/services.xml
| Related tickets | https://github.com/Sylius/Sylius/pull/11693/files#r468483392
I was sure, that the parameter exists, however it is a missing feature from ResourceBundle: 
Still, the refactored version will be more coherent with Doctrine behavior and attribute bundle definition: 
Current addressing serialization:
=> [API] Unify interface parameters

src/Sylius/Bundle/ChannelBundle/Collector/ChannelCollector.php, src/Sylius/Bundle/CoreBundle/Collector/CartCollector.php, src/Sylius/Bundle/CoreBundle/Collector/SyliusCollector.php, src/Sylius/Bundle/UiBundle/DataCollector/TemplateBlockDataCollector.php
Error without this change:
```bash
HP Fatal error:  Declaration of Sylius\Bundle\ChannelBundle\Collector\ChannelCollector::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Exception $exception = NULL): void must be compatible with Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Throwable $exception = NULL) in /var/www/dimedic-reports/current/vendor/sylius/sylius/src/Sylius/Bun …
```
=> Fixed compatibility with newer version of data collectors

UPGRADE-1.8.md
| Bug fix?        | yes, because people will have an issue if they follow the typo…
The parameter `sylius_admin.path_prefix` doesn't exist.
=> Typo in UPGRADE-1.8.md

src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20200916093101.php
=> Fix build and add missing migration

features/account/customer_account/customer_profile_validation.feature, features/account/customer_account/editing_customer_profile.feature, src/Sylius/Behat/Context/Api/Shop/AccountContext.php, src/Sylius/Behat/Context/Setup/ShopSecurityContext.php, src/Sylius/Behat/Resources/config/services/api.xml, src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml, src/Sylius/Behat/Resources/config/suites.yml, src/Sylius/Behat/Resources/config/suites/api/account/customer.yml, src/Sylius/Bundle/ApiBundle/DataProvider/CustomerItemDataProvider.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Customer.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Customer.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml, src/Sylius/Bundle/ApiBundle/spec/DataProvider/CustomerItemDataProviderSpec.php
| Related tickets | part of #11250, based on #11872 
=> [Api] restrict access to customer account editing

src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PaymentMethod.xml
I have added to serialization code of payment method, as it is needed to complete 'select payment method' step in checkout.
=> [API] add payment method code to methods endpoint

UPGRADE-1.8.md, etc/migrations-1.8.sh, src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/11864
This PR fixes the problem with upgrade to Sylius 1.8. I believe it can be done better (_duplicated_ migrations should be detected automatically), but at least it allows to update quite smoothly. The main goal is to delete redundant migrations provided previously in Sylius-Standard (as they're **indeed** not needed anymore) and mark already executed migrations as *migrated*. 
The change in extension is also fixing the bug, that migrations are generated in vendors instead of `src/Migrations` directory.
Thank you for all the people …
=> Improve 1.8 migrations upgrade instructions

features/account/customer_account/viewing_orders_history/seeing_customer_orders_placed_as_guest.feature, features/account/customer_account/viewing_orders_history/viewing_only_my_orders.feature, features/account/customer_account/viewing_orders_history/viewing_orders.feature, src/Sylius/Behat/Context/Api/Shop/AccountContext.php, src/Sylius/Behat/Context/Setup/OrderContext.php, src/Sylius/Behat/Context/Setup/UserContext.php, src/Sylius/Behat/Context/Ui/Shop/AccountContext.php, src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml, src/Sylius/Behat/Resources/config/suites/api/account/customer.yml, src/Sylius/Behat/Resources/config/suites/ui/account/customer.yml, src/Sylius/Bundle/ApiBundle/DataProvider/OrderCollectionDataProvider.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Order.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/data_providers.xml, src/Sylius/Bundle/ApiBundle/spec/DataProvider/OrderCollectionDataProviderSpec.php, src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php, src/Sylius/Component/Order/Repository/OrderRepositoryInterface.php
=> [Api] orders index for customer's account

src/Sylius/Bundle/AdminApiBundle/DependencyInjection/SyliusAdminApiExtension.php, src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php
| Related tickets | fixes #11864, continuation of #11898
As I mentionned in [slack](https://sylius-devs.slack.com/archives/CBV3ZLA8P/p1601565976036000?thread_ts=1601372428.024800&cid=CBV3ZLA8P) after trying the fix provided by @Zales0123, there is still a problem when the AdminApiBundle is registered after CoreBundle in `config/bundles.php`.
This PR should fix that, by merging the new migration_path of CoreBundle AND AdminApiBundle with the latest migration_path provided in `doctrine_migrations` config. That's the project one.
=> [1.8] Fix migration generation

composer.json, src/Sylius/Bundle/ApiBundle/PropertyInfo/Extractor/EmptyPropertyListExtractor.php
In the [symfony/property-info 4.4](https://github.com/symfony/property-info/blob/v4.4.15/PropertyListExtractorInterface.php) the interface does not have a string typehint so Sylius does nolonger work with 4.4
| BC breaks?      | no (fixing one)
=> Removing typehint for Symfony 4.4 compatibility

src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/AddressOrderHandler.php, src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChoosePaymentMethodHandler.php, src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChooseShippingMethodHandler.php, src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/CompleteOrderHandler.php
`\Symfony\Component\Messenger\Handler\MessageHandlerInterface` is just a marker interface, so Symfony can autowire these classes. We have it implemented in all handlers despite the ones from the Checkout folder. Maybe it doesn't make sense to add them, but I would prefer to keep it consistent and in case just remove all these interfaces, or add missing as proposed in this PR.
=> [Minor][API] Add missing messenger handler interfaces

symfony.lock
=> [Maintenance] Adjusting symfony.lock to lowest supported PHP version

features/cart/shopping_cart/clearing_cart_after_logging_out.feature, features/cart/shopping_cart/maintaining_cart_after_authorization.feature, features/cart/shopping_cart/maintaining_previous_cart_after_authorization.feature, src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Client/ApiPlatformSecurityClient.php, src/Sylius/Behat/Client/Request.php, src/Sylius/Behat/Client/RequestInterface.php, src/Sylius/Behat/Context/Api/Shop/CartContext.php, src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php, src/Sylius/Behat/Context/Setup/CartContext.php, src/Sylius/Behat/Context/Transform/CartTokenContext.php, src/Sylius/Behat/Context/Ui/Shop/CartContext.php, src/Sylius/Behat/Resources/config/services/contexts/setup.xml, src/Sylius/Behat/Resources/config/services/contexts/transform.xml, src/Sylius/Bundle/ApiBundle/CommandHandler/PickupCartHandler.php, src/Sylius/Bundle/ApiBundle/Context/TokenValueBasedCartContext.php, src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml, src/Sylius/Bundle/ApiBundle/spec/CommandHandler/PickupCartHandlerSpec.php, src/Sylius/Bundle/ApiBundle/spec/Context/TokenValueBasedCartContextSpec.php, src/Sylius/Bundle/CoreBundle/Context/CustomerAndChannelBasedCartContext.php, src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php, src/Sylius/Bundle/CoreBundle/spec/Context/CustomerAndChannelBasedCartContextSpec.php, src/Sylius/Component/Core/Repository/OrderRepositoryInterface.php
| BC breaks?      | no?
Now, when the customer didn't have or had an empty cart and their had a cart in session, the one from session will be assigned to them.
=> [Cart] Change logic for maintaining cart after logging in

src/Sylius/Component/Core/Formatter/StringInflector.php, src/Sylius/Component/Core/Test/Tests/StringInflectorTest.php, src/Sylius/Component/Core/Test/phpunit.xml.dist
| BC breaks?      | possible
When we change strings with special characters ( f.e. '!' ) String inflector doesn't change it as should. Now it will delete those characters.
=> Changed behavior of string inflector

docs/book/products/attributes.rst
I was looking into adding a select type field and I saw that type was added 3 years ago in https://github.com/Sylius/Sylius/pull/4397 but the doc was not updated
| Related tickets | https://github.com/Sylius/Sylius/pull/4397
=> Adding select type to doc

src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Channel.orm.xml
| Related tickets | fixes #11625 
Fix the relation between Channel and ShopBillingData to allow override the ShopBillingData entity.
=> Patch for Unable to extends ShopBillingData [#11625]

src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml
Same as #11982, but this service does not exist in 1.8
=> [Minor] Update service definition to not using depracated service

docs/customization/translation.rst
| Related tickets | Follow-up to [PR 17](https://github.com/Sylius/Customizations/pull/17)
I think that we should mention that clearing the cache is required in order to see the new translations appear.
=> Updated translation.rst

docs/customization/controller.rst
in the services.yaml you need to override sylius.controller.shop.homepage not app.controller.shop.homepage
=> Customize a controller fix typo in services config

src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig
Order (label <=> input) in Semantic UI
| Branch         | 1.7, 1.8 and master
| Bug fix        | yes
| New feature    | no
| BC breaks      | no
| Deprecations   | no
=> [UI] Fix broken checkboxes that dont change state

docs/book/orders/payments.rst, docs/cookbook/payments/paypal.rst, docs/getting-started-with-sylius/shipping-and-payment.rst, src/Sylius/Bundle/AdminBundle/Resources/translations/messages.en.yml, src/Sylius/Bundle/AdminBundle/Resources/views/PaymentMethod/_form.html.twig
The next step is installing PayPalPlugin on Sylius-Standard by default 💃
=> Suggest PayPalPlugin as the default PayPal integration

src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml
| BC breaks?      | no (kind of)
Symfony messenger component will register handlers into all busses if we won't specify it. I would say, that additional busses are common enough, that we should not register our handlers in different busses by default. 
Ref. https://symfony.com/doc/current/messenger/multiple_buses.html#restrict-handlers-per-bus
=> [API] Explicitly define bus to all handlers

features/cart/shopping_cart/maintaining_last_picked_up_cart.feature, src/Sylius/Behat/Context/Api/Shop/CartContext.php, src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderGetMethodItemExtension.php, src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderMethodsItemExtension.php, src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderGetMethodItemExtensionSpec.php, src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/OrderMethodsItemExtensionSpec.php
Wrong query:
```sql
SELECT s0_.number AS number_0, s0_.notes AS notes_1, s0_.state AS state_2, s0_.checkout_completed_at AS checkout_completed_at_3, s0_.items_total AS items_total_4, s0_.adjustments_total AS adjustments_total_5, s0_.total AS total_6, s0_.created_at AS created_at_7, s0_.updated_at AS updated_at_8, s0_.id AS id_9, s0_.currency_code AS currency_code_10, s0_.locale_code AS locale_code_11, s0_.checkout_state AS checkout_state_12, s0_.payment_state AS payment_state_13, s0_.shipping_state AS shipping_state_14, s0_.token_value AS token_value_15, s0_.customer_ip AS …
```
=> [API][Order] Fixed wrong where condition when looking for order

src/Sylius/Component/Core/Updater/UnpaidOrdersStateUpdater.php, src/Sylius/Component/Core/spec/Updater/UnpaidOrdersStateUpdaterSpec.php
| BC breaks?      | kind of(as I reduced the scope of exceptions, that are caught)
Catching all exceptions may lead to flushing partially changed data. If after transition some service will change some part of data and after that, an exception will occur, we would silence this exception and proceed further without compensating partially changed data.
However, the release with these changes was published on Thursday, so the impact of it is negligible  (comparing to the problems it can create).
=> [Order] Order cancelation fix

src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml
| Branch?         | 1.8 or master 
ShopBillingData model override (in configuration) breaks fixtures. ShopBillingData should be created from factory instead of `Sylius\Component\Core\Model\ShopBillingData` class.
=> [FIXTURES] Use shopbillDataFactory in ChannelExampleFactory

src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
| Bug fix?        | kind of
I don't get exactly why I had that. But basically if you have no taxon then the fixture fails. And since a Channel can have a null value for the menu taxon…
=> Menu taxon can be null, even by default

docs/cookbook/entities/custom-model.rst, docs/cookbook/entities/custom-translatable-model.rst
| Branch?         | 1.7 / 1.8 
| BC breaks?      | no(?)
With old format in Symfony 5 there is fatal error that templates cannot be found, in code those locations are correct already:
- https://github.com/Sylius/Sylius/blob/1.8/src/Sylius/Bundle/AdminBundle/Resources/config/routing/product.yml#L5
=> Bugfix | Don't suggest old format for template locations

features/promotion/receiving_discount/applying_promotion_with_expiration_date.feature
=> [API] add api tag to applying promotions with expiration date

UPGRADE-1.6.md
| Related tickets | fixes #12065
The only migration I didn't have from 1.5 to 1.6 is this migration, so I suspect it should be this one.
=> Adjust link to migration file

CONFLICTS.md, composer.json
Fixed after this PR: https://github.com/lexik/LexikJWTAuthenticationBundle/pull/797
And new LexikJWTAuthenticationBundle tag v2.10.1
=> Remove lcobucci/jwt v3.4 conflict

src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Client/ApiPlatformIriClient.php, src/Sylius/Behat/Client/Request.php, src/Sylius/Behat/Client/RequestInterface.php, src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php, src/Sylius/Behat/Resources/config/services/api.xml, src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml, src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
Sometimes someone needs to add second security firewall like BasicAuth, Default authentication header allows to add only one type(Bearer in our case), This PR add ability to change default authentication header to other on our app, and automatically release default `Authorization` header to use with other security firewall
=> [Api] Be able to change authorization header 

UPGRADE-1.8.md
The `doctrine:migrations:migrate` command will fail if not executed from the project root. This is the case when using Deployer. The `%kernel.project_dir%` parameter will fix that.
=> Fix doctrine migrations config in UPGRADE-1.8.md

.github/workflows/application.yml
As the main solution for randomly failing jobs is to rerun them, my proposal is to rerun them by default 3 times(this number was randomly chosen by me). If the build would fail for a not random reason, it will make our builds slower, but from my observation, it is a much rarer case.
=> [Maintenance] Add retry to github action

.github/workflows/application.yml, src/Sylius/Behat/Service/Setter/CookieSetter.php
This change probably increases the execution time for JS Behat tests, but drastically reduces the failure rate.
I did a benchmark running `features/product/managing_products/changing_images_of_product.feature` 50 times and the results are:
Pre-change:
Passed: 34
Failed: 16
Post-change:
Passed: 49
Failed: 1
=> Improve retrying Behat and reduce failure rate

.github/workflows/application.yml, .github/workflows/documentation.yml, .github/workflows/packages.yml
In the coming weeks, ubuntu-latest will start pointing to ubuntu-20.04 instead of ubuntu-18.04. Let's prevent potential failures by specifying directly ubuntu-18.04 for now and consiously upgrading to ubuntu-20.04 when we're ready - possibly after dropping PHP 7.3 compatibility, since setting it up on the newer version of Ubuntu takes a lot more time.
Ref: https://github.com/actions/virtual-environments/issues/1816
=> [CI] Switch from ubuntu-latest to ubuntu-18.04

src/Kernel.php
Error:
```
Argument 1 of App\Kernel::configureContainer has wrong name $c, expecting $container as defined by Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait::configureContainer
```
=> [Bugfix][1.8] `Kernel::configureContainer()` should match it's parent signature

src/Sylius/Bundle/CoreBundle/Form/Extension/LocaleTypeExtension.php, src/Sylius/Component/Locale/Converter/LocaleConverter.php, src/Sylius/Component/Locale/Model/Locale.php
=> Fixed deprecated `Intl` component usage

features/checkout/seeing_proper_checkout_name.feature, features/checkout/seeing_purchaser_identifier_in_checkout_page.feature, src/Sylius/Behat/Context/Setup/ShopSecurityContext.php, src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php, src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutShippingContext.php, src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPage.php, src/Sylius/Behat/Page/Shop/Checkout/SelectShippingPageInterface.php, src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/_header.html.twig
| Branch?         | 1.8?
logged out (with same email as registered user):
logged in (with same email):
=> [BUG-FIX] display customer email if user is not logged in

composer.json
liminas/liminas-code 4.0.0 create those enigmatic bugs on php7.4 after run `vendor/bin/psalm --show-info=false`:
=> Add conflict liminas/liminas-code 4.0.0

composer.json
`friendsofphp/proxy-manager-lts` is fork with LTS for `ocramius/proxy-manager`
After this update you can get error with return type on `getProxyInitializer()` method in `src/ProxyManager/Proxy/LazyLoadingInterface.php` - tip: `clear:cache` is not enough but `rm -fr var/cache` fix problem
=> Add friendsofphp/proxy-manager-lts for ocramius/proxy-manager

CONFLICTS.md, composer.json
=> Add conflict with polyfill-mbstring 1.22.0

src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Order/Index/_breadcrumb.html.twig
| Related tickets | -none-
If you are looking at the orders of a customer you want to click on the id of the customer in the breadcrum to get back to the customer details page.
This is now clickable:
=> Getting back to customer details in admin panel.

UPGRADE-1.9.md
=> Fixes in the UPGRADE-1.9 file

docs/customization/controller.rst
=> update documentation for creating custom resource controller

docs/customization/controller.rst
| Deprecations?   | no (but fixing one :D )
* Fix the last route declaration to its real use
* Use the term `make sure` instead of `check if` since it is should to work
* use the double `:` syntax for controllers instead of the deprecated single `:`
=> [DOCS] Updating the controller customization

phpstan.neon, psalm.xml, src/Sylius/Bundle/CoreBundle/DependencyInjection/Compiler/CircularDependencyBreakingExceptionListenerPass.php, src/Sylius/Bundle/CoreBundle/EventListener/CircularDependencyBreakingExceptionListener.php, src/Sylius/Bundle/CoreBundle/SyliusCoreBundle.php, src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/CircularDependencyBreakingExceptionListenerPassTest.php, src/Sylius/Bundle/CoreBundle/Tests/Listener/CircularDependencyBreakingErrorListenerTest.php
This issue happens when upgrading Sylius 1.8 to Sylius 1.9, while keeping Symfony 4.4.
=> Fix timeout on 404 Not Found errors when using templating and Symfony 4.4

src/Sylius/Bundle/CoreBundle/Migrations/Version20201130071338.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20201204071301.php
I'm adding these `if` statements not to execute migrations if the changes already exist in the database. It could resolve potential problems for upgrading Sylius from 1.8 to 1.9 with installed the newest RefundPlugin.
=> [Adjustment] Update new migrations not to execute if the changes already exist in db

adr/2021_02_05_unified_api_prefix.md
=> [ADR] Unified API prefix

src/Sylius/Bundle/CoreBundle/Migrations/Version20201130071338.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20201204071301.php
| Related tickets | fixes https://github.com/Sylius/Sylius/pull/12364#issuecomment-780582088
=> [Adjustment] Update down methods of new migrations not to execute if the changes already exist in db

UPGRADE-1.9.md
It seems that these two steps are necessary also for upgrading Sylius with Symfony 4.4
=> Move some steps to different section in the UPGRADE-1.9 file

src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_content.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_content.html.twig
Discussion
----------
| Branch?         | 1.9 
After upgrade to Symfony 5, there is a problem with the default form for custom resources. Already rendered `_token` with `form_widget(form)` throws an exception when rendered again (previously it was just not rendered again).
Probably it would be nice to have some test for a custom resource with default templates 💃 Write now it can be easily reproduced by removing `vars->all->templates->form` from one of the resources (e.g. `AdminUser`).
=> [Bug-fix] Fix default form problem with _token field

src/Sylius/Bundle/CoreBundle/Resources/views/Collector/cart.html.twig
Only format accept currency as argument. 
Fix #11941.
| Related tickets | fixes #11941
A "Cart" menu/collector is added in Sylius 1.8, but this feature requires Channel to exist in the debugger/profiler's route, otherwise user will get the following error:
> An exception has been thrown during the rendering of a template ("Channel could not be found! Tip: You can use the Web Debug Toolbar to switch between channels in development.").
The error is triggered by `convertAndFormat()` in the Twig file. Change it to `format()` fix the problem. I think it was meant to use `format` since method signature was …
=> Fix incorrect money format being used

src/Sylius/Bundle/ApiBundle/test/src/Tests/PromotionTest.php
=> [API] improve tests for overwriting api configs

UPGRADE-1.9.md
This change is not small, it impacts the `bundles.php` and so all the test applications in plugins.
=> Use bold to alert on some changes in the README

src/Sylius/Component/User/Canonicalizer/Canonicalizer.php
In case `mb_detect_encoding` returns false, the call to `mb_convert_case` results in a `TypeError` as it has to be a nullable string as input.
=> Do not fail when mb_detect_encoding returns false

docs/book/architecture/architecture.rst
Into "architecture overview", replace Doctrine "About" URL pointed to a "Page Not Found"
=> Doc: Fix Doctrine project url

features/cart/shopping_cart/adding_product_with_options_to_cart.feature, src/Sylius/Behat/Context/Api/Shop/CartContext.php, src/Sylius/Behat/Resources/config/services/api.xml, src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml, src/Sylius/Bundle/ApiBundle/DataProvider/ChannelAwareItemDataProvider.php, src/Sylius/Bundle/ApiBundle/Doctrine/Filter/ProductVariantOptionValueFilter.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductOptionValue.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductOptionValue.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serialization/ProductVariant.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml, src/Sylius/Bundle/ApiBundle/spec/DataProvider/ChannelAwareItemDataProviderSpec.php
=> Filter product variants by product & option values

src/Sylius/Bundle/CoreBundle/Resources/translations/messages.en.yml
=> Decouple translation used in emails from shopBundle to coreBundle

src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
- When a new collection item is added, accordion are initialisated with
the ".accordion" selector instead of ".ui.accordion"
| Related tickets | fixes #12380
=> Fix nested accordion initialisation

src/Sylius/Component/Taxonomy/Model/Taxon.php, src/Sylius/Component/Taxonomy/spec/Model/TaxonSpec.php
This fixes a bug where this following taxon tree:
* A
* B
* C
would lead to a full name of `A  / B > C` instead of `A > B > C` if the call was `$taxonC->getFullname('>');`
=> Pass path delimiter up to parent taxon

src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-auto-complete.js
In the js file, `src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-auto-complete.js` is set timeout = 5 sec to wait for an async response from ajax autocomplete action.
possibly this was added because someone calculated that this time would be enough to load mutation observers. However, when we add more than one field of type `ResourceAutocompleteChoiceType` it loads with a long delay.
In this PR I removed timeout and add the `refresh` action on the dropdown with 'set selected' action after the response receiving.
=> Removing hard timeout on edit while load selected values

composer.json
| Branch?         | 1.9 only
If you try to install `Sylius ~1.9.0` with `Symfony ^4.4` you will get this type of error :
```
[TypeError]                                                                                                                                                                                                                          
Argument 1 passed to FOS\OAuthServerBundle\Entity\ClientManager::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, instance of EntityManager_9a5be93 given, called in …
```
=> [FOSOAuthServerBundle] Remove incompatible version

src/Sylius/Bundle/ApiBundle/composer.json, src/Sylius/Bundle/CoreBundle/composer.json
See https://github.com/symfony/symfony/issues/40365, the fix for ^5.2 hasn't been released yet.
=> Fix build for CoreBundle and ApiBundle packages

src/Sylius/Bundle/AdminApiBundle/Migrations/Version20210311142134.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20210311142134.php, src/Sylius/Bundle/UserBundle/Resources/config/doctrine/model/User.orm.xml
| Branch?         | 1.7, 1.8 or master 
When using a SSO such as Keycloak, you don't need a password. It's better to allow null instead of setting plain password with a random value.
Moreover, password will be decoupled from user interface on Symfony security user.
https://github.com/symfony/symfony/pull/40267
=> [UserBundle] Allow user password to be null for SSO

docs/api/unified_api/add_to_cart_product_chosen_by_product_options.rst, docs/api/unified_api/index.rst, docs/api/unified_api/map.rst.inc
I will open another PR with a tutorial on how to add the product to cart,
=> [Docs] How to add product variants by options to the cart in Sylius API?

src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Create/_content.html.twig
| Related tickets | fixes #12438
=> Don't render _token field if it's already rendered

src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Update/_content.html.twig
See https://github.com/Sylius/Sylius/pull/12439#pullrequestreview-616113495.
=> Don't render _token field if it's already rendered in update template

src/Sylius/Bundle/AddressingBundle/test/app/AppKernel.php, src/Sylius/Bundle/AttributeBundle/test/app/AppKernel.php, src/Sylius/Bundle/ChannelBundle/test/app/AppKernel.php, src/Sylius/Bundle/CurrencyBundle/test/app/AppKernel.php, src/Sylius/Bundle/CustomerBundle/test/app/AppKernel.php, src/Sylius/Bundle/LocaleBundle/test/app/AppKernel.php, src/Sylius/Bundle/MoneyBundle/test/app/AppKernel.php, src/Sylius/Bundle/OrderBundle/test/app/AppKernel.php, src/Sylius/Bundle/PaymentBundle/test/app/AppKernel.php, src/Sylius/Bundle/ProductBundle/test/app/AppKernel.php, src/Sylius/Bundle/PromotionBundle/test/app/AppKernel.php, src/Sylius/Bundle/ReviewBundle/test/app/AppKernel.php, src/Sylius/Bundle/ShippingBundle/test/app/AppKernel.php, src/Sylius/Bundle/TaxationBundle/test/app/AppKernel.php, src/Sylius/Bundle/TaxonomyBundle/Tests/Functional/app/AppKernel.php, src/Sylius/Bundle/UserBundle/Tests/Functional/app/AppKernel.php
Those bundles don't even need those extensions to be enabled.
=> Fix packages builds: ResourceBundle v1.8 does not require StofDoctrineExtensionsBundle anymore

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml
Create resource operation in Api Platform always belongs to `collectionOperation`.
The same operation is also being defined in Sylius Plus so please remember to fix it as well
=> Create resource belongs to collectionOperation

CONFLICTS.md, composer.json
Highly probable that issues are related to this tag: https://github.com/schmittjoh/JMSSerializerBundle/releases/tag/3.9.0 or this PR in particular: https://github.com/schmittjoh/JMSSerializerBundle/pull/824
=> [Maintenance] Conflict with JMSSerializer 3.9.0 due to issues with mapping of persistent collection

composer.json
Version ^6.0 is enough and installable with lowest supported dependencies.
=> Drop sspooky13/yaml-standards ^5.1 in favour of ^6.0

src/Sylius/Bundle/ShopBundle/Resources/config/services.xml
On logout, shop users are currently being redirected to a hardcoded `/` path. However, this isn't always desired. For example, if localized routes are involved, this effectively switches the shop to its default locale on logout.
This change passes `sylius_shop_homepage` route name instead of a `/` path to the LogoutHandler, meaning the actual path will be generated when the event occurs.
=> Use route name instead of a hardcoded '/' to redirect user on logout

src/Sylius/Bundle/ApiBundle/CommandHandler/ResendVerificationEmailHandler.php, src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml, src/Sylius/Bundle/ApiBundle/spec/CommandHandler/ResendVerificationEmailHandlerSpec.php
`ChannelRepository` was not used in this handler, hence I removed it
=> Cleanup resend verification email handler

src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShopUserExampleFactory.php
The `Sylius\Component\Customer\Model\CustomerInterface` was imported as **CustotmerComponent**. This is just to change that typo to **CustomerComponent**. It was also used 4 times in the class so I have changed those occurrences as well.
=> Fix CustomerComponent Typo

src/Sylius/Bundle/ApiBundle/Resources/config/services/event_handlers.xml
=> [Minor] Use explicit bus instead of the default one

src/Sylius/Bundle/CoreBundle/Migrations/Version20210422105530.php, src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/OrderItem.orm.xml, src/Sylius/Component/Core/Model/OrderItem.php, src/Sylius/Component/Core/Model/OrderItemInterface.php, src/Sylius/Component/Core/spec/Model/OrderItemSpec.php, src/Sylius/Component/Order/Model/Order.php, src/Sylius/Component/Order/Model/OrderItem.php, src/Sylius/Component/Order/Model/OrderItemUnit.php, src/Sylius/Component/Order/spec/Model/OrderSpec.php
While testing many requests in a short time to change the quantity of product in the cart, I detected 2 problems:
- an incorrect number of order item units in relation to the quantity on order item
- an incorrect adjustments total
This PR solves these two issues.
=> [Order] Fix race condition problem with multiple order recalculations

src/Sylius/Bundle/ApiBundle/PropertyInfo/Extractor/ReflectionExtractor.php
Problem: 
Adding boolval fix this problem:
=> [Api]Fix isAllowedProperty return type in ReflectionExtractor

features/product/viewing_products/viewing_enabled_products_only.feature, src/Sylius/Behat/Context/Api/Shop/ProductContext.php, src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/ProductsWithEnableFlagExtension.php, src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml, src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/ProductsWithEnableFlagExtensionSpec.php
Right now API `/shop/products` returns all products in database, even those that are explicitly disabled.
=> Bugfix | Filter out not enabled products in API collection

.github/workflows/application.yml
Make our builds fast again - there's almost no chance this behaviour would differ much between MySQL 5.7 and multiple versions of PHP and Symfony. We should switch to supporting MySQL 8.0 as the main database engine, replacing MySQL 5.7.
=> Include just one MySQL 5.7 build

features/checkout/preventing_adding_to_cart_disabled_products.feature, features/checkout/preventing_adding_to_cart_invalid_products.feature, src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php, src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml, src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddItemToCart.xml, src/Sylius/Bundle/ApiBundle/Validator/Constraints/ProductOrVariantEnabled.php, src/Sylius/Bundle/ApiBundle/Validator/Constraints/ProductOrVariantEnabledValidator.php, src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/ProductOrVariantEnabledValidatorSpec.php
=> [API] Validate if product or variant is enabled

docs/cookbook/shop/facebook-login.rst
Configuring the Facebook app with `localhost` sometimes does not work. Exposing local server temporarily seems to be more reliable.
=> [Docs] Mention localhost exposure for easier Facebook login

features/account/customer_account/editing_customer_profile.feature, src/Sylius/Behat/Context/Ui/Shop/LoginContext.php, src/Sylius/Behat/Context/Ui/Shop/RegistrationContext.php
Until we are blocked by symfony security, we decided to remove steps checking for notifications after logging out.
The problem is: https://github.com/symfony/symfony/commit/f012eee6c6034a94566dff596fe4e16dfc5d9c1f#diff-914ec544d4f7b26fda540aea3d7bc57cc5057d76bfb9ad72047d77739e3bb5a3R87 
Before this change user still authorized so there was posibility to get session flash bags even after logging out, right now it deletes all session storage along with flashes, so there is no way to display them.
=> [Bug] [Temporary solution] Comment out 2 behats steps for checking notifications

docs/getting-started-with-sylius/custom-business-logic.rst
=> [DOCS] API custom logic example

docs/getting-started-with-sylius/custom-business-logic.rst
| Related tickets | improves #12627 
The response in those endpoints are quite long and json codeblock does not let us use comments. I changed them to javascript (which does no change to UI/UX of docs) and added comments, so this would cut out confusion why responses are so short.
=> [DOCS] Change response codeblocks to be more clarified

features/product/viewing_products/viewing_different_price_for_different_product_variants.feature, src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php, src/Sylius/Behat/Context/Api/Shop/ProductContext.php, src/Sylius/Behat/Resources/config/suites/api/product/viewing_products.yml, src/Sylius/Bundle/ApiBundle/Resources/config/services.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/swagger.xml, src/Sylius/Bundle/ApiBundle/Serializer/ProductNormalizer.php, src/Sylius/Bundle/ApiBundle/Swagger/ProductDocumentationNormalizer.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductNormalizerSpec.php
=> [API][Product] Expose default variant on product show and index

.github/workflows/application.yml, .github/workflows/packages.yml
Symfony 5.3 breaks the build now.
References:
- https://github.com/symfony/symfony/issues/41470
- https://github.com/symfony/symfony/issues/41492
=> Use Symfony 5.2.* instead of ^5.2 for GitHub Actions

UPGRADE-1.10.md
These two should be taken into consideration as well:
- https://github.com/Sylius/Sylius-Standard/pull/567
- https://github.com/Sylius/Sylius-Standard/pull/564
The build on Sylius-Standard is failing most likely because of Symfony 5.3 release.
=> Improve the UPGRADE file for Sylius v1.10

features/promotion/applying_promotion_coupon/denying_usage_of_unexisting_promotion_coupon.feature, src/Sylius/Bundle/ApiBundle/Validator/Constraints/PromotionCouponEligibilityValidator.php, src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/PromotionCouponEligibilityValidatorSpec.php
=> [Api] Denying usage of unexisting promotion coupon

features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_expiration_date.feature, features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_per_customer_usage_limit.feature, features/promotion/applying_promotion_coupon/receiving_no_discount_if_coupon_promotion_is_not_eligible.feature, src/Sylius/Behat/Context/Api/Shop/PromotionContext.php, src/Sylius/Behat/Context/Setup/PromotionContext.php, src/Sylius/Behat/Resources/config/suites/api/promotion/applying_promotion_coupon.yml, src/Sylius/Bundle/ApiBundle/Checker/AppliedCouponEligibilityChecker.php, src/Sylius/Bundle/ApiBundle/Checker/AppliedCouponEligibilityCheckerInterface.php, src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml, src/Sylius/Bundle/ApiBundle/Validator/Constraints/PromotionCouponEligibilityValidator.php, src/Sylius/Bundle/ApiBundle/spec/Checker/AppliedCouponEligibilityCheckerSpec.php, src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/PromotionCouponEligibilityValidatorSpec.php
I've also unified the validation message to always show that coupon code is invalid (from the perspective of a Customer, much more natural information than `Promotion is invalid` 💃)
=> [API] Denying usage of coupon for invalid promotion

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Country.xml, src/Sylius/Bundle/ApiBundle/Resources/config/serialization/Country.xml
Country object doesn't have created/updated at field. It shouldn't be defined in api resources.
=> Country api resource shouldn't have created/updated at

CONFLICTS.md
There is no conflict with `api-platform/core` on this branch anymore
=> Remove unnecessary note about conflict with api-platform/core

CONFLICTS.md, composer.json
=> Bring back conflict to symfony/polyfill-mbstring

src/Sylius/Behat/Context/Api/Shop/OrderContext.php, src/Sylius/Bundle/ApiBundle/Resources/config/serialization/PaymentMethod.xml, tests/Api/DataFixtures/ORM/cart.yaml, tests/Api/Responses/Expected/shop/get_order_response.json, tests/Api/Shop/OrdersTest.php
| Related tickets | replaces https://github.com/Sylius/Sylius/pull/12723
=> [API] Serialize only payment id and method as payment in order response

docs/cookbook/index.rst, docs/cookbook/payments/custom-field-on-refund-payment.rst, docs/cookbook/payments/map.rst.inc
| Related tickets | bases on https://github.com/Sylius/Sylius/pull/12717 and waits for merge https://github.com/Sylius/RefundPlugin/pull/320
=> [Documentation][Refund] Add cookbook about refund customization with improvements

docs/book/installation/sylius_plus_installation.rst
| Related tickets | after #12767 
=> [Documentation] One more fix for warning about version of Sylius in Plus installation guide

config/packages/dev/_sylius.yaml
I believe it would be useful for the development 🖖 Without it if I want to change something in the API I need to change the parameter and pray to not forget to remove it before committing 🙏 🎉
=> Enable API by default in dev environment

src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeChoiceType.php
| Bug fix?        | no (but performance improvement)
We currently have about 110 attributes in our shop and opening up the product edit page takes quite a long time. (In dev without any caches, about 8 seconds). This is also due to a ton of queries running the in the background: 
1719 queries to show a product edit page.
After applying the fix this only causes the count to drop to about half of it:
The reduction of computing time is mostly thanks to the fact that there are fewer entities to hydrate.
I don't see that this is causing any issues. The file was[ created when migrating to the newer version …
=> Optimizing the attribute loading in product edit

src/Sylius/Bundle/ApiBundle/Serializer/CommandDenormalizer.php
| Related tickets | fixes #12811
Fixes tests on 1.10 and master branches, where we test [RegisterShopUser](https://github.com/Sylius/Sylius/blob/1.10/src/Sylius/Bundle/ApiBundle/Command/RegisterShopUser.php#L69) that has new not nullable argument with a default value.
Failing test: https://github.com/Sylius/Sylius/runs/3122767036?check_suite_focus=true#step:18:75
=> [API] Allow creation of commands with no arguments with a default value

src/Sylius/Bundle/ApiBundle/Serializer/CommandDenormalizer.php, src/Sylius/Bundle/ApiBundle/Serializer/CommandNormalizer.php, src/Sylius/Bundle/ApiBundle/Tests/ApiPlatform/Bridge/Symfony/Routing/CachedRouteNameResolverTest.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/CommandDenormalizerSpec.php, src/Sylius/Bundle/ApiBundle/test/config/config.yaml
| Related tickets | fixes #12811
=> [API] Do not check command arguments if there is an object to populate

UPGRADE-1.9.md, UPGRADE-API-1.9.md
| Related tickets | Split from #12831
=> [UPGRADE] Split API and non API upgrade files

UPGRADE-API-1.11.md, src/Sylius/Bundle/ApiBundle/Doctrine/Filter/ExchangeRateFilter.php, src/Sylius/Bundle/ApiBundle/Doctrine/Filter/TranslationOrderNameAndLocaleFilter.php, src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
All class folders are kept in the singular form. What is more, we already have one filter in the `Sylius\Bundle\ApiBundle\Doctrine\Filter` namespace
=> [API] Unification of filtration namespaces

src/Sylius/Bundle/ApiBundle/Provider/LiipProductImageFilterProvider.php, src/Sylius/Bundle/ApiBundle/Provider/ProductImageFilterProviderInterface.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductImage.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/providers.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/serializers.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/swagger.xml, src/Sylius/Bundle/ApiBundle/Serializer/ProductImageNormalizer.php, src/Sylius/Bundle/ApiBundle/Swagger/ProductImageDocumentationNormalizer.php, src/Sylius/Bundle/ApiBundle/spec/Provider/LiipProductImageFilterProviderSpec.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductImageNormalizerSpec.php, tests/Api/Responses/Expected/shop/get_filtered_product_image_response.json, tests/Api/Shop/ProductImageTest.php
| Related tickets | PR with PoC: https://github.com/Sylius/Sylius/pull/12798
At the moment it adds 'filtered_path' with normal 'path'.
You can choose filter from list
=> [API] Add liip image filters to API

src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_totals.html.twig
The extra wrapping div breaks Semantic UI's list here.
I'm guessing the intended layout was this?
=> [Admin] Fix shipping totals in order summary

src/Sylius/Bundle/ApiBundle/Serializer/CommandNormalizer.php, src/Sylius/Bundle/ApiBundle/Serializer/ProductImageNormalizer.php, src/Sylius/Bundle/ApiBundle/Serializer/ProductNormalizer.php, src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php, src/Sylius/Bundle/ApiBundle/Serializer/ShippingMethodNormalizer.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/CommandNormalizerSpec.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductImageNormalizerSpec.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductNormalizerSpec.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantNormalizerSpec.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/ShippingMethodNormalizerSpec.php
| Bug fix?        | kind of
While adding custom normalizer, it may be tempting to use the same name for the flag. This may lead to skipping part of normalization. It would be better to prefix our config keys with `sylius` and make official recommendation, that such keys in end projects should be prefixed with `app`
=> [DX] Add sylius prefixes to normalizers ALREADY_CALLED consts values to avoid name collision

UPGRADE-API-1.11.md, src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/AddressOrderHandler.php, src/Sylius/Bundle/ApiBundle/Resources/config/services/command_handlers.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/providers.xml, src/Sylius/Bundle/ApiBundle/Tests/CommandHandler/ChangeAddressOrderHandlerTest.php, src/Sylius/Bundle/ApiBundle/spec/CommandHandler/Checkout/AddressOrderHandlerSpec.php
instead of logic duplication
| Bug fix?        | partially 
=> [API] AddressOrderHandler refactored to use customer provider

docs/customization/grid.rst
| Branch?         |master 
Should be merged after merge PR https://github.com/Sylius/SyliusGridBundle/pull/68 and release new version of `SyliusGridBundle`
=> [Documentation] Note about changes related to upgrade to GridBundle 1.10

docs/customization/grid.rst
| Related tickets | fixes https://github.com/Sylius/Sylius/pull/12881#pullrequestreview-732714929
=> [Documentation] Minor fix in grids docs

src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_addresses.html.twig
I think it was OK until shipping address was first. Now the logic is inverted, so this change is needed to fix ugly address borders.
=> Fix borders in order - show - addresses

docs/book/products/product_associations.rst
| Related tickets | fixes #11603
This is a first draft to update the documentation to avoid using the removed function `TaxonInterface::getProducts()`. It probably needs a better integration of the custom repository query code. I welcome any suggestion to make it better :)
=> Fix #11603, Update documentation to replace use of removed function

.github/workflows/application.yml, .github/workflows/packages.yml
| Deprecations?   |
symfony/flex 1.14 came out recently, which crashes sylius app (vendor files are not found)
force github actions to use symfony flex 1.13.4
=> [Build] Force symfony flex in github actions

src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CatalogPromotion.xml, tests/Api/Admin/CatalogPromotionsTest.php, tests/Api/Responses/Expected/admin/catalog_promotion/get_catalog_promotion_response.json, tests/Api/Responses/Expected/admin/catalog_promotion/get_catalog_promotions_response.json, tests/Api/Responses/Expected/admin/catalog_promotion/post_catalog_promotion_response.json, tests/Api/Responses/Expected/admin/catalog_promotion/put_catalog_promotion_response.json
minor fixes of  https://github.com/Sylius/Sylius/pull/12994
=> Fixes to endpoints and contract tests of CP

UPGRADE-1.8.md, UPGRADE-API-1.8.md, docs/api/unified_api/introduction.rst
There is no such file as `app/config/packages/_sylius.yaml`. App prefix is not needed, because related configuration should be placed in: https://github.com/Sylius/Sylius-Standard/blob/1.10/config/packages/_sylius.yaml
=> [Bug] Fix default sylius config file path in Sylius 1.8

UPGRADE-1.8.md, UPGRADE-1.9.md, UPGRADE-API-1.8.md, UPGRADE-API-1.9.md, docs/api/unified_api/introduction.rst
There is no such file as `app/config/packages/_sylius.yaml`. App prefix is not needed, because related configuration should be placed in: https://github.com/Sylius/Sylius-Standard/blob/1.10/config/packages/_sylius.yaml
This PR contains fixes to 1.8 as well, as I'm not sure if we want to merge then on previous branch
=> [Bug] Fix default sylius config file path in Sylius 1.9

UPGRADE-1.10.md, UPGRADE-API-1.10.md
There is no such file as `app/config/packages/_sylius.yaml`. App prefix is not needed, because related configuration should be placed in: https://github.com/Sylius/Sylius-Standard/blob/1.10/config/packages/_sylius.yaml
=> [Bug] Fix default sylius config file path in Sylius 1.10

UPGRADE-API-1.11.md, docs/cookbook/taxation/customize-tax-by-address.rst
There is no such file as `app/config/packages/_sylius.yaml`. App prefix is not needed, because related configuration should be placed in: https://github.com/Sylius/Sylius-Standard/blob/1.10/config/packages/_sylius.yaml
=> [Bug] Fix default sylius config file path in Sylius master branch

src/Sylius/Bundle/AddressingBundle/Resources/config/serializer/Model.Country.yml, src/Sylius/Bundle/AddressingBundle/Resources/config/serializer/Model.Province.yml, src/Sylius/Bundle/AddressingBundle/Resources/config/serializer/Model.Zone.yml, src/Sylius/Bundle/CurrencyBundle/Resources/config/serializer/Model.Currency.yml, src/Sylius/Bundle/CurrencyBundle/Resources/config/serializer/Model.ExchangeRate.yml, src/Sylius/Bundle/LocaleBundle/Resources/config/serializer/Model.Locale.yml, src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductAssociationType.yml, src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductAttribute.yml, src/Sylius/Bundle/ProductBundle/Resources/config/serializer/Model.ProductOption.yml, src/Sylius/Bundle/ShippingBundle/Resources/config/serializer/Model.ShipmentUnit.yml, src/Sylius/Bundle/ShippingBundle/Resources/config/serializer/Model.ShippingCategory.yml, src/Sylius/Bundle/TaxationBundle/Resources/config/serializer/Model.TaxCategory.yml
| Related tickets | https://github.com/Sylius/SyliusAdminApiBundle/pull/9
After moved AdminApiBundle to a separate repo, we accidentally left part of serialization which cause errors in the applications without AdminApiBundle, now we moved these configs to AdminApiBundle so it should be deleted from Sylius core.
=> Remove serialization moved to admin api bundle

features/promotion/applying_catalog_promotions/seeing_applied_catalog_promotions_on_variants_list.feature, src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php, src/Sylius/Behat/Resources/config/suites/api/promotion/applying_catalog_promotions.yml, src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductVariantNormalizerSpec.php, src/Sylius/Bundle/CoreBundle/Applicator/CatalogPromotionApplicator.php, src/Sylius/Bundle/CoreBundle/Applicator/CatalogPromotionApplicatorInterface.php, src/Sylius/Bundle/CoreBundle/Formatter/AppliedPromotionInformationFormatter.php, src/Sylius/Bundle/CoreBundle/Formatter/AppliedPromotionInformationFormatterInterface.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20210830193340.php, src/Sylius/Bundle/CoreBundle/Processor/CatalogPromotionProcessor.php, src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ChannelPricing.orm.xml, src/Sylius/Bundle/CoreBundle/Resources/config/services.xml, src/Sylius/Bundle/CoreBundle/spec/Applicator/CatalogPromotionApplicatorSpec.php, src/Sylius/Bundle/CoreBundle/spec/Formatter/AppliedPromotionInformationFormatterSpec.php, src/Sylius/Bundle/CoreBundle/spec/Processor/CatalogPromotionProcessorSpec.php, src/Sylius/Component/Core/Model/ChannelPricing.php, src/Sylius/Component/Core/Model/ChannelPricingInterface.php, src/Sylius/Component/Core/Model/ProductVariant.php, src/Sylius/Component/Core/Model/ProductVariantInterface.php, src/Sylius/Component/Core/spec/Model/ChannelPricingSpec.php, src/Sylius/Component/Core/spec/Model/ProductVariantSpec.php
We need to keep the information about applied catalog promotions on each `ChannelPricing`. I propose to start simple, with an array of arrays 💃 to make it happen sooner than later. If we decide in the future we need some more sophisticated structure - we can always change it 🚀
=> [CatalogPromotions] Inform about promotions applied on variants

src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php, src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_promotion.yml, src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/CatalogPromotionRule.orm.xml, src/Sylius/Bundle/CoreBundle/Validator/Constraints/CatalogPromotionRulesValidator.php, src/Sylius/Bundle/CoreBundle/spec/Validator/Constraints/CatalogPromotionRulesValidatorSpec.php, src/Sylius/Component/Core/Model/CatalogPromotionRule.php, src/Sylius/Component/Core/Model/CatalogPromotionRuleInterface.php, src/Sylius/Component/Core/spec/Model/CatalogPromotionRuleSpec.php, src/Sylius/Component/Promotion/Model/CatalogPromotionRuleInterface.php, tests/Api/Admin/CatalogPromotionsTest.php
Variants do not exist (even conceptually) within the `PromotionBundle` 🖖
=> [CatalogPromotions] Move variant-related CatalogPromotionRule constant to Core

docs/cookbook/frontend/webpack.rst
Hello :wave:,
While following webpack tutorial, I noticed that there is no logo on Admin Login page. 
By overriding the template `Security/_content.html.twig`, we could change logo path to use one provided by webpack instead one build with gulp. 
I targetted 1.9 branch, tell me if I should change to master or 1.10.
=> [Docs] Webpack - Display logo on login page

composer.json, docs/book/api/index.rst
There is a new command for key generation and it is worth pointing Sylius users directly to it. We could consider adding it as a part of the installation process.
=> [Docs] Fix link to token generation for API

src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php, src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/theme.html.twig, src/Sylius/Bundle/CoreBundle/Form/Extension/CatalogPromotionRuleTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Type/CatalogRule/VariantRuleConfigurationType.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml, src/Sylius/Bundle/CoreBundle/Validator/Constraints/CatalogPromotionRulesValidator.php, src/Sylius/Bundle/CoreBundle/spec/Validator/Constraints/CatalogPromotionRulesValidatorSpec.php, src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionRuleType.php, src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogRule/VariantRuleConfigurationType.php, tests/Api/Admin/CatalogPromotionsTest.php, tests/Api/Responses/Expected/admin/catalog_promotion/post_catalog_promotion_response.json, tests/Api/Responses/Expected/admin/catalog_promotion/put_catalog_promotion_response.json
=> [CatalogPromotion] refactor cp rule to be consistent with cp action

src/Sylius/Bundle/CoreBundle/Form/Extension/CatalogPromotionRuleTypeExtension.php, src/Sylius/Bundle/CoreBundle/Form/Type/CatalogPromotionRule/ForVariantsRuleConfigurationType.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml
| Related tickets | after https://github.com/Sylius/Sylius/pull/13066#pullrequestreview-748814118
=> [CatalogPromotion] Improve names and namespaces of catalog promotion rule form types

features/promotion/managing_catalog_promotions/creating_catalog_promotion.feature, features/promotion/managing_catalog_promotions/validating_catalog_promotion_creation.feature, src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Bundle/CoreBundle/Validator/Constraints/CatalogPromotionRulesValidator.php, src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml, src/Sylius/Bundle/PromotionBundle/Resources/config/services/validators.xml, src/Sylius/Bundle/PromotionBundle/Resources/config/validation/CatalogPromotion.xml, src/Sylius/Bundle/PromotionBundle/Resources/config/validation/CatalogPromotionAction.xml, src/Sylius/Bundle/PromotionBundle/Resources/translations/validators.en.yml, src/Sylius/Bundle/PromotionBundle/Validator/CatalogPromotionActionValidator.php, src/Sylius/Bundle/PromotionBundle/Validator/Constraints/CatalogPromotionAction.php, src/Sylius/Bundle/PromotionBundle/spec/Validator/CatalogPromotionActionValidatorSpec.php, tests/Api/Admin/CatalogPromotionsTest.php, tests/Api/Responses/Expected/admin/catalog_promotion/post_catalog_promotion_with_invalid_actions_response.json
| Related tickets | based on #13037
=> [CatalogPromotion][API] Add validation for creating catalog promotion with actions

features/promotion/applying_catalog_promotions/applying_catalog_promotions_for_variant.feature, features/promotion/applying_catalog_promotions/seeing_applied_catalog_promotion_on_variant.feature, features/promotion/applying_catalog_promotions/seeing_applied_catalog_promotions_on_variants_list.feature, src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php, src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php, src/Sylius/Bundle/CoreBundle/Provider/CatalogPromotionVariantsProvider.php, src/Sylius/Bundle/CoreBundle/spec/Provider/CatalogPromotionVariantsProviderSpec.php, src/Sylius/Component/Core/Model/ChannelPricing.php
=> [Catalog Promotions] Fixing issues with multiple variants

features/promotion/applying_catalog_promotions/applying_catalog_promotions_for_variant.feature, features/promotion/applying_catalog_promotions/applying_catalog_promotions_in_proper_channels.feature, src/Sylius/Behat/Context/Api/Shop/ProductContext.php, src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php, src/Sylius/Behat/Context/Setup/ProductContext.php, src/Sylius/Behat/Resources/config/suites/api/promotion/applying_catalog_promotions.yml, src/Sylius/Bundle/CoreBundle/Applicator/CatalogPromotionApplicator.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionExampleFactory.php, src/Sylius/Bundle/CoreBundle/Provider/CatalogPromotionVariantsProvider.php, src/Sylius/Bundle/CoreBundle/spec/Applicator/CatalogPromotionApplicatorSpec.php
| Related tickets | https://github.com/Sylius/Sylius/pull/13009
=> [CatalogPromotion][API] Apply catalog promotion in proper channels

src/Sylius/Bundle/ApiBundle/Serializer/CommandDenormalizer.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/CommandDenormalizerSpec.php
=> [API] Fix command denormalizer to not throw exception if command does not have constructor

docs/book/products/catalog_promotions.rst
A quick fixup to docs references from https://github.com/Sylius/Sylius/pull/13084
before and after
=> [DOCS] Fix catalog promotions docs reference

src/Sylius/Bundle/ShopBundle/Resources/private/js/sylius-variants-prices.js, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_price.html.twig
| Related tickets | introduced in https://github.com/Sylius/Sylius/pull/13101
Before:
After:
=> [CatalogPromotions] Do not display applied promotion description in label if not set

src/Sylius/Bundle/OrderBundle/Controller/OrderController.php
I got this error during the development of a cart related feature:
```
Symfony\Component\Form\Exception\LogicException:
Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() before Form::isValid().
at vendor/symfony/form/Form.php:752
at Symfony\Component\Form\Form->isValid()
(vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Controller/OrderController.php:83)
at Sylius\Bundle\OrderBundle\Controller\OrderController->saveAction(object(Request))
(vendor/symfony/http-kernel/HttpKernel.php:157)
at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1) …
```
=> Check if the form is submitted before validation

src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionUpdateListener.php, src/Sylius/Bundle/CoreBundle/Processor/CatalogPromotionClearer.php, src/Sylius/Bundle/CoreBundle/Processor/CatalogPromotionProcessor.php, src/Sylius/Bundle/CoreBundle/Resources/config/services.xml, src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml, src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionUpdateListenerSpec.php, src/Sylius/Bundle/CoreBundle/spec/Processor/CatalogPromotionClearerSpec.php, src/Sylius/Bundle/CoreBundle/spec/Processor/CatalogPromotionProcessorSpec.php
The previous implementation was causing unexpected doctrine event cascades that resulted in multiple applied promotions in some cases 💃 Calling flush only once should fix this problem once for ever 🚀
=> Reorganize flushes in Catalog Promotions processing

features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_on_variant_once_its_data_changes.feature, src/Sylius/Behat/Context/Ui/Admin/ManagingProductVariantsPricesContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php, src/Sylius/Behat/Context/Ui/Shop/ProductContext.php, src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePage.php, src/Sylius/Behat/Page/Admin/ProductVariant/UpdatePageInterface.php, src/Sylius/Behat/Resources/config/services/contexts/ui.xml, src/Sylius/Behat/Resources/config/suites/ui/promotion/applying_catalog_promotions.yml, src/Sylius/Bundle/CoreBundle/EventListener/ProductVariantEventListener.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml, src/Sylius/Bundle/CoreBundle/spec/EventListener/ProductVariantEventListenerSpec.php
| Related tickets | based on https://github.com/Sylius/Sylius/pull/13128
=> [UI][CatalogPromotion] Reapplying catalog promotion on variant once its data changes

features/promotion/applying_catalog_promotions/reapplying_catalog_promotion_after_changing_rule.feature, features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_after_editing_their_actions.feature, features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_after_editing_their_rules.feature, src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Context/Ui/Shop/ProductContext.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/CatalogPromotionRule.xml, src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml, src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ChannelPricingRepository.php, src/Sylius/Bundle/CoreBundle/EventListener/CatalogPromotionEventListener.php, src/Sylius/Bundle/CoreBundle/Provider/CatalogPromotionVariantsProvider.php, src/Sylius/Bundle/CoreBundle/spec/EventListener/CatalogPromotionEventListenerSpec.php, src/Sylius/Bundle/CoreBundle/spec/Provider/CatalogPromotionVariantsProviderSpec.php
=> [API][CatalogPromotion] Reapplying catalog promotions on rule update

features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_after_editing_their_actions.feature, features/promotion/applying_catalog_promotions/reapplying_catalog_promotions_after_editing_their_rules.feature, src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Context/Ui/Shop/ProductContext.php, src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElement.php, src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElementInterface.php, src/Sylius/Behat/Page/Shop/Product/ShowPage.php, src/Sylius/Bundle/CoreBundle/EventListener/CatalogPromotionEventListener.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml, src/Sylius/Bundle/CoreBundle/spec/EventListener/CatalogPromotionEventListenerSpec.php
=> [UI][CatalogPromotion] Reapply catalog promotions after editing their rules and actions

docs/book/products/catalog_promotions.rst
=> [Documentation][CatalogPromotion] Adjust docs after removing usage of Doctrine events

features/checkout/addressing_order/order_address_validation.feature, src/Sylius/Behat/Context/Api/Shop/CartContext.php, src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php, src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddressOrder.xml
After addressing the empty cart and adding an item to it, there is a cart with some products but payment_skipped as payment state :dancer: *In theory*, it's not a problem, as after completion payment state is correct (awaiting payment), but if anything happens about payment before checkout completion, it can lead to some nasty errors. And, conceptually, addressing empty cart does not seems as something correct 🚀
=> [API] Do not allow to address empty cart

phpstan.neon.dist
| Related tickets | the same as https://github.com/Sylius/Sylius/pull/13138, but for 1.10
It started to fail on 1.10 as well :/ I'm temporarily disabling the analysis and we need to figure out what is wrong with it 🖖 🔥
=> [Build][Hot-fix] Ignore PHPStan analysis for StringInflector

composer.json
| Branch?         | 1.9 1.10 master
https://sylius-devs.slack.com/archives/C3EGDG9LY/p1634735181098300
This conflict is not documented in `CONFLICTS.md` anymore, was brought back in this commit:
https://github.com/Sylius/Sylius/commit/f80f42d06ffb98a8a5ffaaf543ccd646cdd202c6
However according https://github.com/laminas/laminas-code/issues/67 and considering:
https://github.com/Sylius/Sylius/blob/49b070933b32761de08475fafd6d86dca10d40ff/.github/workflows/application.yml#L104 should no longer be an issue.
If it still is, then I guess the build will show it and there should be a new issue opened somewhere.
=> Remove undocumented conflict on laminas-code ^4.0

.github/workflows/application.yml
by clearing cache before starting phpunit i achieved alot of less segfaults than before
Initial: atleast once per 8 phpunit actions
With cache clear: once / 60 phpunit actions 
Increase php memory limits, clear cache before js applications (which also were causing segfault)
=> [Github] clear cache before phpunit

.github/workflows/application.yml
| Deprecations?   |
As github support found out its about memory problems, there was still one place with github cli enabled. 
Disabling xdebug should reduce memory usage.
=> [Actions] disable xdebug for actions

features/product/viewing_products/accessing_product_page_via_permalink.feature, src/Sylius/Behat/Context/Api/Shop/ProductContext.php, src/Sylius/Bundle/ApiBundle/Controller/GetProductBySlugAction.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/swagger.xml, src/Sylius/Bundle/ApiBundle/Swagger/ProductSlugDocumentationNormalizer.php, tests/Api/Shop/ProductsTest.php
| Related tickets | mentioned in https://github.com/Sylius/Sylius/issues/12453
=> Get products by slug api endpoint

src/Sylius/Bundle/ApiBundle/composer.json, src/Sylius/Bundle/UserBundle/spec/Provider/UsernameOrEmailProviderSpec.php
just a spec fix, PhpSpec\Matcher\ThrowMatcher is unable to access $serialized, due to change on AuthenticationException, which unsets this field.
=> [Spec] change username to runtime exception

src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php, src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services.xml, src/Sylius/Bundle/ApiBundle/test/config/config.yaml, src/Sylius/Bundle/ApiBundle/test/src/Tests/DisablingDocumentationTest.php
| Related tickets | https://github.com/Sylius/Sylius/issues/12832
=> Remove swagger decorators when docs are disabled

.github/workflows/application.yml, .github/workflows/packages.yml, CONFLICTS.md, composer.json, psalm.xml, src/Sylius/Behat/Service/SecurityService.php, src/Sylius/Bundle/ApiBundle/Controller/Payment/GetPaymentConfiguration.php, src/Sylius/Bundle/ApiBundle/Controller/UploadAvatarImageAction.php, src/Sylius/Bundle/CoreBundle/Command/SetupCommand.php, src/Sylius/Bundle/CoreBundle/Controller/ProductTaxonController.php, src/Sylius/Bundle/CoreBundle/Controller/ProductVariantController.php, src/Sylius/Bundle/CoreBundle/Resources/config/services.xml, src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php, src/Sylius/Bundle/OrderBundle/Controller/OrderController.php, src/Sylius/Bundle/ProductBundle/Controller/ProductSlugController.php, src/Sylius/Bundle/ProductBundle/Resources/config/services.xml, src/Sylius/Bundle/UserBundle/Controller/SecurityController.php, src/Sylius/Bundle/UserBundle/Resources/config/services.xml, src/Sylius/Bundle/UserBundle/Security/UserLogin.php, tests/Controller/AdminProductAjaxTest.php
| Related tickets | Backport of https://github.com/Sylius/Sylius/pull/13339/ and https://github.com/Sylius/Sylius/pull/13358, fixes https://github.com/Sylius/Sylius-Standard/issues/630
Let's bring Sf5.4 support to Sylius 1.10. This way, current users will benefit from Symfony 5.4 with current installations. I'm considering it as a bug-fix, as it is already possible to install this version according to our composer.json. What is more, it will make it possible to migrate first to Sf5.4 and then upgrade to Sylius 1.11.
=> Add Symfony 5.4 support for Sylius 1.10 

.github/workflows/packages.yml
It seems Github Actions are not content with our number of builds 😄 
As a hot-fix, I propose we can run only Symfony `5.3.*` and `5.4.*` on packages builds, as **probably** most of the people uses these versions and 5.2 is no longer supported... and it allows the build to start :dancer:
=> Minimize number of build for packages

src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/Show/_details.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/_form.html.twig, src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionType.php
Time display format has been changed to Y-m-d H:m from Y-m-d h:m:s, where s was 00 by default and h was 12h format, form takes seconds to account
Before:
After:
=> [UI] change time format to 24H, autocomplete times on data change

CONFLICTS.md, composer.json
The conflict against `doctrine/orm:^2.10` has been unnecessary since the `gedmo/doctrine-extensions` 3.2 release.  In fact, the actual conflict was between the extensions package and the ORM, Sylius was never directly conflicted against it.  Now that newer versions of the extensions package either have the appropriate conflict or fixed the conflict and now require newer ORM versions, Sylius no longer needs to have this conflict.
=> Remove ORM 2.10 conflict

src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/Show/_header.html.twig
Catalog Promotion on all pages should have same icon.
=> [CatalogPromotion] change icon on show page

composer.json
| Related tickets | mentioned in #13372
The 2.x branch of `gedmo/doctrine-extensions` is no longer supported and isn't installable on PHP 8.  3.2 is set as the minimum to avoid allowing 3.0 or 3.1 to be installed with incompatible ORM versions.
=> Drop support for older `gedmo/doctrine-extensions` versions

src/Sylius/Bundle/CoreBundle/Migrations/Version20211125085254.php, src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/ChannelPricing.orm.xml
As far as I see, this `NOT NULL` is not needed at all when the default value is `0`. Additionally, when changing from Sylius 1.10 to `dev-master` (or rather - upcoming 1.11), it results in exception while migrations are applied:
=> [Migrations] Remove invalid NOT NULL usage

src/Sylius/Bundle/CoreBundle/Migrations/Version20161202011555.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20161214153137.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20161215103325.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20161219160441.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20161220092422.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20161221133514.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20161223091334.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20161223164558.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20170103120334.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20170109143010.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20170110120125.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20170120164250.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20170124221955.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20170303170201.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20201017150005.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20201104085538.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20201130071338.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20201204071301.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20201208105207.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20210311142134.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20210408131321.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20210422105530.php
This PR tries to solve the issue announced at our slack. Some of our migrations didn't have `mysql` check, while we had it already for the long time. So, I've added this check to missing migrations. As I've was doing it with replace, some comparations have changed to strict ones.
=> [Bug][Migrations] Add missing `mysql` check for our migrations to ensure proper syntax is available

.github/workflows/application.yml
To run PHPSpec we don't need to depend on the database nor setup it at all. Extracting this build would be even more valuable on `master` where we have more database-related variations 🚀
=> [CI] Extract PHPSpec build

src/Sylius/Behat/Page/Shop/Product/IndexPage.php, src/Sylius/Behat/Page/Shop/Product/ShowPage.php, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Box/_content.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_catalogPromotionLabels.html.twig, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_price.html.twig
| Related tickets | #13386 - this doc will be modified after this merge
to make customization easier we want to move catalog promotion labels to separate file
=> [Catalog Promotion] Moved labels to separate twig

features/promotion/managing_catalog_promotions/seeing_catalog_promotion_details.feature, src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Page/Admin/CatalogPromotion/ShowPage.php, src/Sylius/Behat/Page/Admin/CatalogPromotion/ShowPageInterface.php, src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/Show/Action/fixed_discount.html.twig, src/Sylius/Bundle/UiBundle/Resources/translations/messages.en.yml
| Related tickets | fixes #13325
=> [CatalogPromotion][Admin] Fix displaying fixed discount action on catalog show page

docs/cookbook/index.rst, docs/cookbook/promotions/custom-catalog-promotion-action.rst, docs/cookbook/promotions/custom-catalog-promotion-scope.rst, docs/cookbook/promotions/map.rst.inc, src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml, src/Sylius/Bundle/PromotionBundle/Resources/config/services/validators.xml
| Related tickets | partially fixes #https://github.com/Sylius/Sylius/pull/13325#discussion_r756750238
This PR contains a minor refactor of parameters with types of actions/scopes passed to validators.
=> [Documentation][CatalogPromotion] Add cookbook about creating a custom action + minor improvements

docs/book/plugins/guide/naming.rst
The Bundle file includes any namespace prefixes, so it should be `IronManSyliusProductOnDemandPlugin` instead of `SyliusProductOnDemandPlugin`
=> Class name typo

.github/workflows/application.yml
=> Remove invalid PHP version from PHPSpec build

src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/SetCatalogPromotionActionTypesPassTest.php, src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/SetCatalogPromotionScopeTypesPassTest.php
| Related tickets | fixes https://github.com/Sylius/Sylius/pull/13403#pullrequestreview-836220149
=> [CatalogPromotion] Add compiler pass tests for setting action/scope types parameters

src/Sylius/Bundle/ApiBundle/DependencyInjection/SyliusApiExtension.php, src/Sylius/Bundle/ApiBundle/OpenApi/AdminAuthenticationTokenDocumentationFactory.php, src/Sylius/Bundle/ApiBundle/OpenApi/ProductDocumentationFactory.php, src/Sylius/Bundle/ApiBundle/OpenApi/ProductVariantDocumentationFactory.php, src/Sylius/Bundle/ApiBundle/OpenApi/ShopAuthenticationTokenDocumentationFactory.php, src/Sylius/Bundle/ApiBundle/Resources/config/integrations/openapi.xml
| Bug fix?        | not sure
| New feature?    | not sure
| Related tickets | fixes #13384
I don't think this breaks anything (very reassuring, I know :sunglasses:), since it only adds extra bits to the OpenApi documentation generated by ApiPlatform 2.6 to make it on par with what we have for Api Platform 2.5.
No tests, and I don't think I could add any quickly. Sorry!
=> Decorate OpenApi documentation (Api Platform 2.6). Fixes #13384

src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php
Since Symfony 5.3, UserProviderInterface in Symfony suggest to use loadUserByIdentifier to replace loadUserByUsername
https://github.com/symfony/symfony/blob/1e968b49f516d8b1305d0b94158dabef557d334e/src/Symfony/Component/Security/Core/User/UserProviderInterface.php#L61-L68
=> Use loadUserByIdentifier() since Symfony 5.3

UPGRADE-1.10.md, composer.json, src/Sylius/Bundle/AttributeBundle/Resources/config/doctrine/model/AttributeValue.orm.xml, src/Sylius/Bundle/CoreBundle/Migrations/Version20211018130725.php, src/Sylius/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.xml
| Branch?         | 1.9, 1.10
| Related tickets | fixes #13211 
`doctrine/dbal:"^3"` remove `json_array` field type, previously it was deprecated in favor of `json` field type.
=> Replace `json_array` with `json` type as requested by the deprecation

docs/book/products/catalog_promotions.rst
| Branch?         |  1.11
it does not work with `async` messenger
=> [docs] fix catalog promotion async tip

src/Sylius/Bundle/CoreBundle/Resources/config/services/validators.xml, src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/SetCatalogPromotionActionTypesPass.php, src/Sylius/Bundle/PromotionBundle/DependencyInjection/Compiler/SetCatalogPromotionScopeTypesPass.php, src/Sylius/Bundle/PromotionBundle/Resources/config/services/validators.xml, src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/SetCatalogPromotionActionTypesPassTest.php, src/Sylius/Bundle/PromotionBundle/Tests/DependencyInjection/Compiler/SetCatalogPromotionScopeTypesPassTest.php
Renaming 
`sylius.catalog_promotion.actions` => `sylius.catalog_promotion.actions_types`
`sylius.catalog_promotion.scopes` => `sylius.catalog_promotion.scopes_types`
=> [CatalogPromotion] Rename actions and scopes

src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionUpdatedListener.php, src/Sylius/Bundle/CoreBundle/Listener/ProductUpdatedListener.php, src/Sylius/Bundle/CoreBundle/Listener/ProductVariantUpdatedListener.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml, src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionUpdatedListenerSpec.php, src/Sylius/Bundle/CoreBundle/spec/Listener/ProductUpdatedListenerSpec.php, src/Sylius/Bundle/CoreBundle/spec/Listener/ProductVariantUpdatedListenerSpec.php
=> [CatalogPromotion] Refactor names of listeners to be consistent with others

src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionAction/PercentageDiscountActionConfigurationType.php
We want to unify validation on both FixedDiscountActionConfigurationType and PercentageDiscountActionConfigurationType
and we have to choose beetween deletion additional validation or staying with additional validation on both
Close this PR in case [THIS](https://github.com/Sylius/Sylius/pull/13478) PR is merged
=> Validation deleted from PercentageDiscountActionConfigurationType

src/Sylius/Component/Core/Calculator/ProductVariantPriceCalculator.php, src/Sylius/Component/Core/Exception/MissingChannelConfigurationException.php, src/Sylius/Component/Core/spec/Calculator/ProductVariantPriceCalculatorSpec.php
This Pull Request will avoid returning null on int only return type allowed function. If getPrice is null for the channel the same exception is thrown.
=> [Product Variant] Price Calculator fixed to return always int

src/Sylius/Component/Shipping/ShipmentUnitTransitions.php
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/12705
These constants are not used at all :dancer:
=> Deprecate unused ShimentUnitTransitions class

UPGRADE-API-1.11.md, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml
I've moved `filter` word to the end of the service name, as this is a convention we have for the rest of the filters. The question arises if we shouldn't move to the old Symfony service convention for filters to have the same structure here, but I don't have any strong opinion about it.
=> [API][Minor] Archiving shipping methods filter rename to maintain naming convention

src/Sylius/Bundle/ApiBundle/EventSubscriber/CatalogPromotionEventSubscriber.php, src/Sylius/Bundle/ApiBundle/Resources/config/services/event_subscribers.xml, src/Sylius/Bundle/ApiBundle/spec/EventSubscriber/CatalogPromotionEventSubscriberSpec.php, src/Sylius/Bundle/CoreBundle/Announcer/CatalogPromotionAnnouncer.php, src/Sylius/Bundle/CoreBundle/Announcer/CatalogPromotionAnnouncerInterface.php, src/Sylius/Bundle/CoreBundle/EventListener/CatalogPromotionEventListener.php, src/Sylius/Bundle/CoreBundle/Resources/config/services.xml, src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml, src/Sylius/Bundle/CoreBundle/spec/Announcer/CatalogPromotionAnnouncerSpec.php, src/Sylius/Bundle/CoreBundle/spec/EventListener/CatalogPromotionEventListenerSpec.php
| Related tickets | fixes https://github.com/Sylius/Sylius/pull/13473#pullrequestreview-851633441
=> [CatalogPromotion] Extract dispatching catalog promotion events from listeners to a separate service

config/packages/nelmio_alice.yaml, config/packages/test_cached/nelmio_alice.yaml
This bundle is not turned on in all configuration. Without removal of it, no one can start prod env for example
=> [Maintenance] Remove NelmioAlice from the main packages config

docs/cookbook/payments/custom-invoice.rst
| Branch?         | 1.10 
Changed path of the invoice logo asset to the correct directory
=> [Docs] Altered custom invoice logo path

.github/workflows/application.yml
Composer install is already part of architekt github action https://github.com/phparkitect/arkitect-github-actions/blob/main/entrypoint.sh#L23
=> [Architecture] Do not double install PHP dependencies

.github/workflows/packages.yml, UPGRADE-API-1.11.md, src/Sylius/Bundle/ApiBundle/Filter/Doctrine/ExchangeRateFilter.php, src/Sylius/Bundle/ApiBundle/Filter/Doctrine/ProductPriceOrderFilter.php, src/Sylius/Bundle/ApiBundle/Filter/Doctrine/ProductVariantOptionValueFilter.php, src/Sylius/Bundle/ApiBundle/Filter/Doctrine/TaxonFilter.php, src/Sylius/Bundle/ApiBundle/Filter/Doctrine/TranslationOrderNameAndLocaleFilter.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ExchangeRate.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Product.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductVariant.xml, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ShippingMethod.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/filters.xml, src/Sylius/Bundle/ApiBundle/composer.json, src/Sylius/Bundle/ApiBundle/phparkitect.php, src/Sylius/Bundle/ApiBundle/spec/Filter/Doctrine/TaxonFilterSpec.php
Alternative solution to #13494
=> [API] Doctrine filters moved below filters namespace

features/promotion/managing_catalog_promotions/creating_catalog_promotion.feature, features/promotion/managing_promotions/adding_promotion_with_rule.feature, src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingPromotionsContext.php, src/Sylius/Behat/Page/Admin/CatalogPromotion/CreatePage.php, src/Sylius/Behat/Page/Admin/CatalogPromotion/CreatePageInterface.php, src/Sylius/Behat/Page/Admin/Promotion/CreatePage.php, src/Sylius/Behat/Page/Admin/Promotion/CreatePageInterface.php, src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js
Fixes #13463
| Related tickets | fixes #13463
Additionally to the bugfix, I made the jquery selectors more explicit by using direct ancestors. In fact, that's how I discovered this bug, because we were patching app.js to make these selectors more explicit, which allowed us embed additional collection forms inside action/rule collections forms.
=> Bugfix: display full cart promotion rule form when adding a new rule

composer.json
@lchrusciel `src/Sylius/*/*/phparkitect.php` files must be excluded from the autoloader because they use PHP Arkitect symbols which is dev dependency and not a production one.
=> Exclude PHP Arkitect rules files from autoloader

src/Sylius/Bundle/ApiBundle/test/config/security.yaml
This patch migrates security config to the new authenticator-based system introduced in Symfony 5.1.
Guard-based authentication has been deprecated in Symfony 5.3. Luckily, not much needs to change for us since Sylius didn't have any custom Guard authenticators to begin with.
The patch also drops `always_authenticate_before_granting: true` from config. This option [has been deprecated](https://symfony.com/doc/5.4/reference/configuration/security.html#always-authenticate-before-granting) since Symfony 5.4, and it's unclear why or whether at all it was needed in the first place, …
=> Update security config to use the new authenticator-based system

src/Sylius/Component/Core/OrderProcessing/ShippingChargesProcessor.php, src/Sylius/Component/Core/spec/OrderProcessing/ShippingChargesProcessorSpec.php
This code is with us since 2014. Since then, we have adjustment clearer - which is the first processor we run and it should clean up shipping adjustment already. Therefore, this fragment should not have any effect over codebase
=> [Minor] Removal of logic duplication in shipping charges processor

phpstan.neon.dist
=> [Maintenance] Remove phpstan exclude for PHP7.4

features/promotion/applying_catalog_promotions/not_reapplying_catalog_promotions_on_variant_once_its_prices_changes.feature, features/promotion/applying_catalog_promotions/not_reapplying_catalog_promotions_on_variants_once_products_taxon_changes.feature, src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php, src/Sylius/Behat/Context/Ui/Shop/ProductContext.php, src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionExampleFactory.php, src/Sylius/Bundle/CoreBundle/Processor/AllCatalogPromotionsProcessor.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml, src/Sylius/Bundle/CoreBundle/Resources/config/services/processors.xml, src/Sylius/Bundle/CoreBundle/spec/Processor/AllCatalogPromotionsProcessorSpec.php, src/Sylius/Bundle/PromotionBundle/Provider/EligibleCatalogPromotionsProvider.php, src/Sylius/Bundle/PromotionBundle/Provider/EligibleCatalogPromotionsProviderInterface.php, src/Sylius/Bundle/PromotionBundle/Resources/config/services.xml, src/Sylius/Bundle/PromotionBundle/spec/Provider/EligibleCatalogPromotionsProviderSpec.php, tests/Functional/EligibleCatalogPromotionsProcessorTest.php
to avoid potential bugs default criteria should be on the provider level
=> move default criteria to catalog promotion provider

src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml
| Branch?         | 1.10  
USA being a part of 2 zones at once was misleading with the concept of actual work predicted for zones and was causing some problems when calculating taxes for this country in case this 2 zones had different taxes.
=> [Fixtures] USA deleted from the World zone

src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/Scope/default.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/Scope/for_products.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/Scope/for_taxons.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/Scope/for_variants.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/CatalogPromotion/_action.html.twig
add Small imrovement to divide taxon/scopes elements with delete button
=> [UI][Admin] add divider after form elements

features/promotion/managing_catalog_promotions/creating_catalog_promotion.feature, src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php, src/Sylius/Behat/Context/Ui/Shop/ProductContext.php, src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionCreatedListener.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml, src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionCreatedListenerSpec.php
During Handling CatalogPromotionCreated we weren't processing all available catalog promotions, now it takes all into account.
=> [CatalogPromotion] Process all catalog promotions when catalog promotion is created

src/Sylius/Bundle/CoreBundle/Resources/config/services/checkers.xml, src/Sylius/Component/Core/Checker/CLIContextChecker.php, src/Sylius/Component/Core/spec/Checker/CLIContextCheckerSpec.php
I'm proposing alternative implementation to #13545, that takes into account request stack instead of env & SAPI. This way, we will have coherent behaviour among all envs which, in my opinion, will reduce possibility of bugs that exists on prod on dev, but where not detected by test.
Perhaps, we should consider similar behaviour just as a locale context - so fallbacking in the locale context to config value if CLI is executed
=> [Core][Optimalization] Assign fallback locale for command based requests

docs/book/products/catalog_promotions.rst
=> [Catalog Promotion] [Docs] docs updated

src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductVariantRepository.php, src/Sylius/Bundle/PromotionBundle/Doctrine/ORM/CatalogPromotionRepository.php
With the proposed changes, we are omitting the n+1 problem. The idea is to load all data required for CP processing in one batch, so we can drastically reduce the number of DB queries(in the cost of computation memory, but it can be neglected, as still the biggest problem of it is that we do not clear UnitOfWork)
I've also adjusted alias of query builder to `o`, as this is Sylius default 
Ref. https://blackfire.io/profiles/compare/3d7cc083-575f-4e58-acba-e2f60f444cbc/graph
=> [Catalog Promotion] Select more data during processing to avoid inefficient db calls

src/Sylius/Bundle/CoreBundle/Announcer/CatalogPromotionAnnouncer.php, src/Sylius/Bundle/CoreBundle/spec/Announcer/CatalogPromotionAnnouncerSpec.php
If we had CatalogPromotion already applied on channelPricings, after changing its startDate to next day, previous discounts would still be applied, with this event we force to recalculate catalog promotions.
=> Update catalog promotion instantly if date is set on future

docs/customization/form.rst
In fact, registering form extension **this way** when the autoconfiguration is enabled would result in registering it twice 💃
=> [Docs] Mention autoconfiguration case when extending the form

src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionExampleFactory.php, src/Sylius/Bundle/CoreBundle/Fixture/Listener/CatalogPromotionExecutorListener.php, src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/promotion.yaml, src/Sylius/Bundle/CoreBundle/Resources/config/services.xml, src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_factories.xml, src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_listeners.xml, src/Sylius/Bundle/CoreBundle/spec/Fixture/Listener/CatalogPromotionExecutorListenerSpec.php
Previous:
~With clearing entity manger we don't need to trace that many objects in UnitOfWork, therefore we are not calculating that much changes and we save ton of memory.~
~Ref. https://blackfire.io/profiles/compare/7c9cb9fd-c43f-4420-8e0a-0af2a7b4b000/graph~
Now:
Just a refactor of CP fixtures. The EntityManager will be cleared with https://github.com/symfony/doctrine-bridge/blob/5.4/Messenger/DoctrineClearEntityManagerWorkerSubscriber.php just by the fact, that it will be processed asynced. Which will be done in #13578. 
#13578 vs previous implementation …
=> [Catalog Promotion] Move catalog promotion processing after the fixture execution

src/Sylius/Bundle/CoreBundle/Fixture/Listener/CatalogPromotionExecutorListener.php, src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_listeners.xml, src/Sylius/Bundle/CoreBundle/spec/Fixture/Listener/CatalogPromotionExecutorListenerSpec.php
After our refactor of catalog promotions, fixtures don't work properly. With this fix, we process catalog promotions state after fixtures load.
=> [Catalog Promotions] State processing after fixtures load

src/Sylius/Bundle/CoreBundle/CommandDispatcher/ApplyCatalogPromotionsOnVariantsCommandDispatcherInterface.php, src/Sylius/Bundle/CoreBundle/CommandDispatcher/BatchedApplyCatalogPromotionsOnVariantsCommandDispatcher.php, src/Sylius/Bundle/CoreBundle/DependencyInjection/Configuration.php, src/Sylius/Bundle/CoreBundle/DependencyInjection/SyliusCoreExtension.php, src/Sylius/Bundle/CoreBundle/Resources/config/services.xml, src/Sylius/Bundle/CoreBundle/Tests/DependencyInjection/SyliusCoreExtensionTest.php, src/Sylius/Bundle/CoreBundle/spec/CommandDispatcher/BatchedApplyCatalogPromotionsOnVariantsCommandDispatcherSpec.php
In case of better management of batch sizes we decided to extract it to CatalogPromotion config, then we can resize it by modifying `_sylius.yaml` file
=> [CatalogPromotion] batch configuration size made a part of config

src/Sylius/Bundle/CoreBundle/Migrations/Version20220203115813.php
=> [Migration] add migration to messenger if transport is configured to doctrine

docs/cookbook/index.rst, docs/cookbook/promotions/catalog-promotion-performance.rst, docs/cookbook/promotions/map.rst.inc
| Related tickets | https://github.com/Sylius/Sylius/pull/13587
=> [Docs] Configuring catalog promotions batch sizes explained

UPGRADE-1.11.md, src/Sylius/Bundle/UiBundle/Resources/views/Macro/pagination.html.twig
| Related tickets | fixes #12462
=> Use semantic ui view instead of deprecated semantic_ui_translated

src/Sylius/Bundle/AddressingBundle/Validator/Constraints/ProvinceAddressConstraintValidator.php, src/Sylius/Bundle/AddressingBundle/spec/Validator/Constraints/ProvinceAddressConstraintValidatorSpec.php
The province validator returns early if it finds preexisting validation errors on the address. However, when checking that, it uses `strpos()` and passes current `$propertyPath` as a needle. This might cause problems when an address is validated as a top-level entity, because `$propertyPath` is an empty string in such case.
=> FIX: Avoid passing empty needle to strpos()

src/Sylius/Bundle/CoreBundle/CatalogPromotion/Command/UpdateCatalogPromotionState.php, src/Sylius/Bundle/CoreBundle/CatalogPromotion/CommandHandler/UpdateCatalogPromotionStateHandler.php, src/Sylius/Bundle/CoreBundle/Fixture/Listener/CatalogPromotionExecutorListener.php, src/Sylius/Bundle/CoreBundle/Listener/CatalogPromotionStateChangedListener.php, src/Sylius/Bundle/CoreBundle/Resources/config/app/messenger.yaml, src/Sylius/Bundle/CoreBundle/Resources/config/services.xml, src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_listeners.xml, src/Sylius/Bundle/CoreBundle/Resources/config/services/listeners.xml, src/Sylius/Bundle/CoreBundle/spec/CatalogPromotion/CommandHandler/UpdateCatalogPromotionStateHandlerSpec.php, src/Sylius/Bundle/CoreBundle/spec/Fixture/Listener/CatalogPromotionExecutorListenerSpec.php, src/Sylius/Bundle/CoreBundle/spec/Listener/CatalogPromotionStateChangedListenerSpec.php
=> [CatalogPromotions] Refactor processing catalog promotions states to use commands

docs/book/products/catalog_promotions.rst
| Related tickets | Reverts https://github.com/Sylius/Sylius/pull/13630/  because of https://github.com/Sylius/Sylius/pull/13624
This case does not exists anymore, as states are processed async as well
=> [Docs] Drop warning about active, not applied promotions as states are handled in async manner as well

features/promotion/managing_catalog_promotions/editing_catalog_promotion.feature, src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionActionType.php
When trying to edit the percentage discount value and save it with an empty amount there was a 500 error. This PR provides only a workaround for this problem.
=> [Catalog Promotion][UI] Fixed error when trying to save catalog promotion with empty percentage discount value

features/promotion/applying_catalog_promotions/seeing_applied_catalog_promotion_on_products_with_options.feature, src/Sylius/Behat/Context/Setup/CatalogPromotionContext.php, src/Sylius/Behat/Context/Setup/ProductContext.php, src/Sylius/Behat/Context/Transform/ProductOptionValueContext.php, src/Sylius/Behat/Context/Ui/Shop/ProductContext.php, src/Sylius/Behat/Page/Shop/Product/ShowPage.php, src/Sylius/Behat/Resources/config/services/contexts/transform.xml, src/Sylius/Behat/Resources/config/suites/ui/promotion/applying_catalog_promotions.yml, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_variantsPricing.html.twig
Displaying a proper catalog promotion labels while switching product's variants
=> [CatalogPromotion][UI][Shop] Fixed label displaying after option change

src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Element/Admin/CatalogPromotion/FormElement.php, src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionAction/FixedDiscountActionConfigurationType.php
=> [UI][CatalogPromotion] Fix to not displaying duplicated validation message for fixed discount action

adr/2022_02_11_declaring_services_in_container.md
=> [ADR] Declaring services as public in container

docs/book/installation/sylius_plus_installation.rst
| Related tickets | after #13650 
=> [Documentation] Adjust installation guide for Plus on 1.11

psalm.xml
`Error: psalm.xml:3:5: ConfigIssue: Attribute "totallyTyped" is deprecated and is going to be removed in the next major version (see https://psalm.dev/271)`
According to Psalm docs: 
**totallyTyped**
(Deprecated) Setting `totallyTyped` to "true" is equivalent to setting `errorLevel` to "1". Setting `totallyTyped` to "false" is equivalent to setting `errorLevel` to "2" and `reportMixedIssues` to "false"
=> [Psalm] Configuration - totallyTyped replaced according to docs to avoid deprecation problem

UPGRADE-1.11.md, package.json, src/Sylius/Bundle/AdminBundle/gulpfile.babel.js, src/Sylius/Bundle/ShopBundle/gulpfile.babel.js
| Branch?         | master (could be done on others, your call)
| BC breaks?      | yes (it won't work with gulp-sass 4.0 anymore I think)
| Related tickets | #12893 
node-sass is deprecated and its installation breaks on many many setups depending on:
- Node version (up to 12 it seems fine, it breaks for 13+)
- gpy installed or not
- Already installed tooling
- Platform (linux/mac/windows)
All of these problems make the `sass` package a benediction. This commit makes the sylius codebase compatible with it.
=> feat: use sass instead of node-sass

features/promotion/managing_catalog_promotions/editing_catalog_promotion.feature, features/promotion/managing_catalog_promotions/validating_catalog_promotion_creation.feature, src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Bundle/CoreBundle/Tests/Form/Type/CatalogPromotion/CatalogPromotionActionTypeTest.php, src/Sylius/Bundle/PromotionBundle/Form/DataTransformer/MoneyIntToLocalizedStringTransformer.php, src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionAction/FixedDiscountActionConfigurationType.php, src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionAction/PercentageDiscountActionConfigurationType.php, src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionActionType.php
There was a validation problem when changing actions in the catalog promotion.
=> [Admin][API] Catalog promotion actions validation fixed

features/product/viewing_products/viewing_sorted_products.feature, src/Sylius/Behat/Context/Api/Shop/ProductContext.php, src/Sylius/Bundle/ApiBundle/Doctrine/Filters/TranslationOrderNameAndLocaleFilter.php
| Branch?         | 1.10 
| Related tickets | fixes https://github.com/Sylius/Sylius/issues/12594
It resolves the issue with `500 status code` on products collection with `order[translation.name]` parameter.
=> [Product][API][Bug] Fixed product sorting by translated names

UPGRADE-API-1.12.md
| Related tickets | https://github.com/Sylius/Sylius/pull/13628
=> API Upgrade file updated after ShippingMethod endpoints changes 

src/Sylius/Behat/Context/Api/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php, src/Sylius/Bundle/CoreBundle/Tests/Form/Type/CatalogPromotion/CatalogPromotionActionTypeTest.php, src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionAction/FixedDiscountActionConfigurationType.php
| Related tickets | fixes #13651 
There was a problem with floating point value when updating catalog promotion.
=> [Admin] Fix for floating point amount on fixed action in catalog promotion.

docs/cookbook/api/how_force_login_already_registered_user_during_checkout.rst, docs/cookbook/api/map.rst.inc, docs/cookbook/index.rst
In API we should have the ability to force login during checkout if the user already has an account in our shop
=> [Docs] Force user to login during checkout

docs/cookbook/api/how_force_login_already_registered_user_during_checkout.rst
| Related tickets | fixes #13691 
Small fix with a path to validator class in the cookbook.
=> [Docs] Path fix for validator in API force login cookbook

src/Sylius/Component/Core/Model/Order.php, src/Sylius/Component/Core/Model/OrderInterface.php
| Related tickets | after https://github.com/Sylius/Sylius/pull/13695
=> [Order] Fix getters and setters to use a proper flag name after upmerge issue

tests/DataFixtures/Factory/CountryFactoryTest.php, tests/DataFixtures/Factory/CurrencyFactoryTest.php, tests/DataFixtures/Factory/CustomerGroupFactoryTest.php, tests/DataFixtures/Factory/LocaleFactoryTest.php, tests/DataFixtures/Factory/ProductAssociationTypeFactoryTest.php, tests/DataFixtures/Factory/ProductAttributeFactoryTest.php, tests/DataFixtures/Factory/ShippingCategoryFactoryTest.php, tests/DataFixtures/Factory/ShopUserFactoryTest.php, tests/DataFixtures/Factory/TaxCategoryFactoryTest.php, tests/DataFixtures/Factory/TaxonFactoryTest.php, tests/DataFixtures/Factory/ZoneFactoryTest.php, tests/DataFixtures/Factory/ZoneMemberFactoryTest.php, tests/PurgeDatabaseTrait.php
| Bug fix?        | yes, kind of, cause the ResetDatabase from Foundry is too low (it drops and recreates the database).
| Related tickets | partially #13621 
=> [Fixtures] Purge database trait

src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-auto-complete.js
Adds empty field, which allows user to reset autoselect.
=> [JS] add empty value to autocomplete selects

src/Sylius/Behat/Page/Admin/Order/ShowPage.php
| Bug fix?        | no but useful for Behat tests
| BC breaks?      | still no bc-promise on Behat?
All these methods are useful when you customize the order show page.
=> [Behat] Allow to use some useful methods on Order show page

features/product/managing_products/editing_product_slug.feature
The step was undefined in API context where we should create a configurable product, not a simple one. 
Build: https://github.com/Sylius/Sylius/runs/5559343143?check_suite_focus=true#step:24:85
=> [Behat][API] Change the undefined step to create a configurable product instead of simple one

src/Sylius/Behat/Client/ApiClientInterface.php, src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Client/Request.php, src/Sylius/Behat/Client/RequestInterface.php, src/Sylius/Behat/Context/Api/Admin/ManagingChannelsContext.php
In order to use Sylius with the next API Platform release (2.7), I added the ability to test API resources which contains non-collection sub-resources (i.e. channel).
This patch seems to be useless with API Platform 2.6, but is mandatory for API Platform 2.7.
=> [Behat] added context to manage non-collection subresources

src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-product-attributes.js
| Branch?         | 1.10 
| Related tickets | mentioned in [issue](https://github.com/Sylius/Sylius/issues/13326)
`Apply to all` button at admin product attribute edition page was working only for one option for select attribute, now it is possible to select all options.
https://user-images.githubusercontent.com/53942444/160408379-dd754e1e-5b44-4ce9-a4c5-19fb130c8ae1.mov
=> [Admin][JS] Applying all the options selected for an attribute of type multiple select fixed

.github/workflows/packages.yml
It's not required on 1.11, as we test only 2 Symfony versions there, but on 1.10 there are 3 (`^4.4`, `5.3.*`, `5.4.*`), so the number of combinations exceeds the limit of 256 builds :dancer:
=> Limit the number of packages build run on 1.10

.github/workflows/application.yml, src/Sylius/Bundle/AdminBundle/Controller/CustomerStatisticsController.php, src/Sylius/Bundle/AdminBundle/Controller/Dashboard/StatisticsController.php, src/Sylius/Bundle/AdminBundle/Controller/DashboardController.php, src/Sylius/Bundle/ShopBundle/Controller/ContactController.php, src/Sylius/Bundle/ShopBundle/Controller/CurrencySwitchController.php, src/Sylius/Bundle/ShopBundle/Controller/HomepageController.php, src/Sylius/Bundle/ShopBundle/Controller/LocaleSwitchController.php, src/Sylius/Bundle/ShopBundle/Controller/SecurityWidgetController.php, src/Sylius/Bundle/UiBundle/Controller/SecurityController.php
=> [GitHub Actions] Fix symfony/flex in workflows and invalid EngineInterface namespace

UPGRADE-1.10.md
| Related tickets | after #13837 
=> [Maintenance] Add note to UPGRADE file about dropping Symfony 5.2 support

src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml, src/Sylius/Bundle/ApiBundle/Swagger/AcceptLanguageHeaderDocumentationNormalizer.php, src/Sylius/Bundle/ApiBundle/spec/Swagger/AcceptLanguageHeaderDocumentationNormalizerSpec.php
| Related tickets | partially #13708
In the related ticket, we've added support for Accept-Language header but we can not use it in SwaggerUI. I provide a simple solution for that.
=> [API][Swagger] Accept language header in SwaggerUI

features/product/viewing_products/viewing_product_image.feature, src/Sylius/Behat/Context/Api/Shop/ProductContext.php
API scenario for viewing the main product image.
=> [Behat] Viewing product image - API scenario covered

features/product/viewing_products/viewing_sorted_products.feature, src/Sylius/Behat/Context/Api/Shop/ProductContext.php, src/Sylius/Behat/Context/Ui/Shop/ProductContext.php, src/Sylius/Bundle/ApiBundle/Filter/Doctrine/TaxonFilter.php, src/Sylius/Bundle/ApiBundle/spec/Filter/Doctrine/TaxonFilterSpec.php
1) Sorting shop products via API - test covered
2) Sorting products by `taxonPosition` if no other sorting parameter is specified
=> [API] Sorting products by date

features/checkout/picking_up_the_cart_with_the_locale_other_than_the_default.feature, src/Sylius/Behat/Context/Api/Shop/CartContext.php, src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml, src/Sylius/Bundle/ApiBundle/Resources/config/services/validator.xml, src/Sylius/Bundle/ApiBundle/Resources/config/validation/PickupCart.xml, src/Sylius/Bundle/ApiBundle/Resources/translations/validators.en.yaml, src/Sylius/Bundle/ApiBundle/Validator/Constraints/PickupCartLocale.php, src/Sylius/Bundle/ApiBundle/Validator/Constraints/PickupCartLocaleValidator.php, src/Sylius/Bundle/ApiBundle/spec/Validator/Constraints/PickupCartLocaleValidatorSpec.php
Validate localeCode for picking up cart endpoint.
=> [Cart] Add Validator for localeCode

composer.json, src/Sylius/Bundle/CoreBundle/Twig/FilterExtension.php
This commit removes support for liip imagine bundle 3.0 because we
extends a class that will not be in the bundle in its version 3.0.
| Related tickets | Rebased version of #13602
=> [Maintenance] Relax conflict on liip imagine bundle - rebased version

src/Sylius/Bundle/AdminBundle/Resources/config/app/events.yaml, src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/Form/_additionalInformation.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/AdminUser/Form/_personals.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variants.html.twig, src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_variantsContent.html.twig
| Related tickets | partially #13798
A new event for variants content and for additional information in an admin user form. 
⬇️
=> [Template][Events] Sylius template events - improvements

UPGRADE-API-1.12.md, features/product/viewing_products/viewing_product_enabled_variants_only.feature, features/product/viewing_products/viewing_product_enabled_variants_options_only.feature, src/Sylius/Behat/Context/Api/Shop/ProductContext.php, src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/EnabledProductVariantsExtension.php, src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml, src/Sylius/Bundle/ApiBundle/Serializer/ProductNormalizer.php, src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryCollectionExtension/EnabledProductVariantsExtensionSpec.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductNormalizerSpec.php, tests/Api/Admin/ProductTest.php, tests/Api/Responses/Expected/admin/get_product_response.json, tests/Api/Responses/Expected/admin/get_products_collection_response.json, tests/Api/Responses/Expected/shop/product/get_products_collection_response.json, tests/Api/Shop/ProductsTest.php
We haven't got any API scenarios for seeing only enabled variants in shop
=> [API][Shop] Viewing only the enabled variants of a product

.github/workflows/application.yml
The tag push is an actual moment when the new version of Sylius is done, the release is just the icing on the cake 🍰 So it makes more sense to run the workflow when the real thing is happening, not when it's nicely served 🖖
=> [Maintenance] Run the build on tags rather than on releases

src/Sylius/Bundle/ApiBundle/Resources/views/SwaggerUi/index.html.twig
Automatically log in to swagger docs after authorization. Just to improve user/developer experience to avoid requesting and copy-pasting credentials every time you refresh page.
I had to hack React using vanilla js xD appreciate it.
https://user-images.githubusercontent.com/22825722/162623176-07768e6c-6ca0-468b-b99e-dc6217a24f42.mov
=> [UI][Swagger] AutoAuthorize on sending admin credentials

src/Sylius/Component/Core/Uploader/ImageUploader.php, src/Sylius/Component/Core/spec/Uploader/ImageUploaderSpec.php
The image uploader has a dependency to a concrete class instead of the interface.  This widens the parameter type to allow the interface.
=> Use the Gaufrette FilesystemInterface instead of a concrete implementation

src/Sylius/Bundle/ApiBundle/Resources/config/integrations/swagger.xml, src/Sylius/Bundle/ApiBundle/Swagger/ProductImageDocumentationNormalizer.php, src/Sylius/Bundle/ApiBundle/Swagger/ProductSlugDocumentationNormalizer.php
| Related tickets | fixes #13854
Small PR to be able to use another api route prefix while generating the swagger page.
=> Use api route prefix parameter instead of `/api/v2`

src/Sylius/Behat/Client/ApiClientInterface.php, src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Client/ContentTypeGuide.php, src/Sylius/Behat/Client/ContentTypeGuideInterface.php, src/Sylius/Behat/Client/Request.php, src/Sylius/Behat/Client/RequestBuilder.php, src/Sylius/Behat/Client/RequestFactory.php, src/Sylius/Behat/Client/RequestFactoryInterface.php, src/Sylius/Behat/Client/RequestInterface.php, src/Sylius/Behat/Context/Api/Admin/ManagingAdministratorsContext.php, src/Sylius/Behat/Context/Api/Shop/CartContext.php, src/Sylius/Behat/Context/Api/Shop/CheckoutContext.php, src/Sylius/Behat/Context/Api/Shop/CustomerContext.php, src/Sylius/Behat/Context/Api/Shop/LoginContext.php, src/Sylius/Behat/Context/Api/Shop/OrderContext.php, src/Sylius/Behat/Context/Api/Shop/ProductContext.php, src/Sylius/Behat/Context/Api/Shop/PromotionContext.php, src/Sylius/Behat/Resources/config/services.xml, src/Sylius/Behat/Resources/config/services/api.xml, src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml, src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
It is a part of improving Developer Experience in Behat tests. I removed factory methods out of the Request class, as the object has really grown up. Moved these methods to separate Factory required a lot of changes, that's why I decided to postpone here and merge current changes.
Created Request Builder and Factory will provide an additional layer for future developers to build their own Requests
=> [behat]Extract Request creation to separate service

src/Sylius/Bundle/AdminBundle/EmailManager/OrderEmailManager.php, src/Sylius/Bundle/AdminBundle/EmailManager/ShipmentEmailManager.php, src/Sylius/Bundle/ApiBundle/CommandHandler/SendOrderConfirmationHandler.php, src/Sylius/Bundle/ApiBundle/CommandHandler/SendShipmentConfirmationEmailHandler.php, src/Sylius/Bundle/CoreBundle/EventListener/MailerListener.php, src/Sylius/Bundle/CoreBundle/Mailer/OrderEmailManager.php, src/Sylius/Bundle/ShopBundle/EmailManager/OrderEmailManager.php, src/Sylius/Bundle/UserBundle/EventListener/MailerListener.php
The latest Sylius Mailer update changed the email address type as not nullable. Therefore our psalm and phpstan pipelines recorded errors. This PR checks if the email is null. Similarly, as we did it in Sylius/Plus. There is no need to send a mail when the email address is null.
=> [maintenance][mailer]Assert that email is not null

docs/book/organization/release-cycle.rst
I was quite surprised when I found out that our release cycle is called _time-based_ in our documentation 😱 That's definitely not the way we are releasing Sylius now (and it has not been for some past versions as well). 
So, to improve transparency within the Community, I would like to document what are the factors we take into consideration when planning the new minor release and what are the consequences of this decision. 
I've also remodelled the tables with past releases a little bit :dancer:
Do not fear, the 1.12 release date will be determined soon 🚀 🖖
=> [Documentation] Improve and fix the release cycle documentation

.docker/test/php.ini, .github/workflows/docker.yml, Makefile, docker-compose.test.yml
Reverts Sylius/Sylius#13897, due to too quick merge. The build itself was red and it should not land in the codebase in the first place
=> Revert "[docker]Run Catalog Promotion via SYNC messenger transport"

src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml
| Bug fix?        | yes (in case you are not using the default api url prefix)
If you are using another url prefix, different from `/api/v2` then those paths are not processed, this PR fix this issue.
=> Use API Url prefix on sylius.api.paths_to_hide

ecs.php
`HeaderCommentFixer` was provided in https://github.com/Sylius/Sylius/pull/13890. Something went wrong during the upmerge I think and now ECS doesn't work on `1.11` and `master` branches.
=> [Maintenance] Fix missing import in ECS config

UPGRADE-1.10.md, UPGRADE-1.12.md, package.json, src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-chart.js, yarn.lock
Related to #12560
| Related tickets | #12560
To follow chart.js documentation (https://www.chartjs.org/docs/latest/getting-started/v3-migration.html): 
Distributed files are now in lower case. For example: `dist/chart.js`
And to avoid error:
```
$ encore production --progress
Running webpack ...
ERROR  Failed to compile with 1 errors
Module build failed: Module not found:
"../vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-chart.js"
contains a reference to the file
"chart.js/dist/Chart.min".
This file can not be found, please check it for typos or update it if the file …
```
=> Import lowercase chart.js/dist/chart.min

.github/workflows/application.yml, config/packages/doctrine.yaml, src/Sylius/Bundle/CoreBundle/Migrations/Version20220407131547.php, src/Sylius/Bundle/CoreBundle/Migrations/Version20220412144156.php
| Related tickets | [PR](https://github.com/Sylius/Sylius/pull/13846)
The PR should be failing, but after the https://github.com/Sylius/Sylius/pull/13846 it should be nice and green :)
This is what happened here. Cherry-pick the change from #13846 that all database pipelines were failing. What I found is that we actually test the schema, but accept failing steps. By not accepting that we were able to find out the problem with some extra things. Like our PostgreSQL schema is successfully validated, but our MariaDB schema is not. That's because of JSON type and the difference between MySQL and MariaDB. …
=> [Maintenance]Run schema validation on mysql pipeline

.docker/test/php.ini
| Related tickets | none                      |
We require almost 4GB in PHP memory, therefore 1GB of opcache memory shouldn't be that much in test environment and will reduce pipeline time
=> [maintenance][docker]Increase opcache limits

src/Sylius/Behat/Client/ApiPlatformClient.php, src/Sylius/Behat/Client/ApiPlatformSecurityClient.php, src/Sylius/Behat/Client/RequestFactory.php, src/Sylius/Behat/Context/Api/Admin/ManagingExchangeRatesContext.php, src/Sylius/Behat/Context/Api/Admin/ManagingPaymentsContext.php, src/Sylius/Behat/Context/Api/Admin/ManagingProductsContext.php, src/Sylius/Behat/Context/Api/Admin/ManagingShipmentsContext.php, src/Sylius/Behat/Context/Api/Shop/CartContext.php, src/Sylius/Behat/Context/Api/Shop/ChannelContext.php, src/Sylius/Behat/Context/Api/Shop/CustomerContext.php, src/Sylius/Behat/Context/Api/Shop/HomepageContext.php, src/Sylius/Behat/Context/Api/Shop/LoginContext.php, src/Sylius/Behat/Context/Api/Shop/OrderContext.php, src/Sylius/Behat/Context/Api/Shop/ProductContext.php, src/Sylius/Behat/Context/Api/Shop/RegistrationContext.php, src/Sylius/Behat/Resources/config/services/api.xml, src/Sylius/Behat/Resources/config/services/contexts/api/admin.xml, src/Sylius/Behat/Resources/config/services/contexts/api/shop.xml
Give the ability to use Behat API tests with a different api prefix, useful if you don't use the default prefix `/api/v2` or simply wanted to use some Behat services with another APIP installation.
=> Behat use project api prefix

src/Sylius/Bundle/AddressingBundle/Validator/Constraints/ZoneCannotContainItselfValidator.php, src/Sylius/Bundle/AddressingBundle/spec/Validator/Constraints/ZoneCannotContainItselfValidatorSpec.php
| Related tickets | fixes #11881, replaces #12867
=> Fix zone cannot contain itself validator

UPGRADE-API-1.12.md, features/product/viewing_product_variants/viewing_product_variant.feature, src/Sylius/Behat/Context/Api/Shop/ProductContext.php, src/Sylius/Behat/Context/Api/Shop/ProductVariantContext.php, src/Sylius/Behat/Context/Transform/ProductVariantContext.php, src/Sylius/Behat/Resources/config/suites.yml, src/Sylius/Behat/Resources/config/suites/api/product/viewing_product_variants.yml, src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/EnabledProductVariantItemExtension.php, src/Sylius/Bundle/ApiBundle/Resources/config/services/extensions.xml, src/Sylius/Bundle/ApiBundle/Serializer/ProductNormalizer.php, src/Sylius/Bundle/ApiBundle/Swagger/ProductDocumentationNormalizer.php, src/Sylius/Bundle/ApiBundle/spec/Doctrine/QueryItemExtension/EnabledProductVariantItemExtensionSpec.php, src/Sylius/Bundle/ApiBundle/spec/Serializer/ProductNormalizerSpec.php, tests/Api/Shop/ProductVariantsTest.php
| Related tickets | fixes to [PR](https://github.com/Sylius/Sylius/pull/13863)
This PR contains missing QueryItemExtension for ProductVariants that shows only enabled variants and corrects comments from [this](https://github.com/Sylius/Sylius/pull/13863) PR
=> [API][Shop] Viewing only the enabled variants of a product fixes

src/Sylius/Behat/spec/Service/SecurityServiceSpec.php, src/Sylius/Component/User/Model/User.php, src/Sylius/Component/User/Model/UserInterface.php
Remove deprecated message of `\Serializable` interface in `User` entity which is reported in PHP 8.1.
```
Deprecated: Sylius\Component\User\Model\User implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /srv/acme/vendor/sylius/sylius/src/Sylius/Component/User/Model/User.php on line 21
```
- Added new `__serialize` and `__unserialize` methods to cover serialization
- Made `serialize` and `unserialize` internal to prevent usage of them (we can remove in next version).
| Branch?         | 1.11         |
| …
=>  [1.11][User] Reduce usage of deprecated `\Serializable` interface #13642 

.github/workflows/docker.yml, docker-compose.test.yml
| Related tickets | master                      |
The test pipelines use synchronous messenger transport therefore docker test pipelines should too.
=> [maintenance][docker]Use synchronous messenger transport

composer.json
| Deprecations?   | yes |
| Related tickets | -                     |
https://symfony.com/blog/the-old-flex-infrastructure-is-shutting-down
=> Bump flex to ^1.17, v1.13 - old infrastructure shutdown

package.json, yarn.lock
| Branch?         |  master           |
| Related tickets | none                      |
Based on documentation: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines
I would like to propose adding the Node engine to the package.json as we currently maintain and test Sylius on …
=> [maintenance][js]Specify engines dependencies

src/Sylius/Bundle/AddressingBundle/spec/Form/EventListener/BuildAddressFormSubscriberSpec.php, src/Sylius/Bundle/AddressingBundle/spec/Validator/Constraints/ProvinceAddressConstraintValidatorSpec.php
| Bug fix?        | yes   (on Symfony 6)                                                   |
Trying to fix https://github.com/Sylius/Sylius/runs/6420686415?check_suite_focus=true#step:11:10 …
=> [Symfony 6] Fix specifications for Addressing bundle

src/Sylius/Bundle/AttributeBundle/test/app/config/config.yml
Trying to fix https://github.com/Sylius/Sylius/runs/6420686740?check_suite_focus=true#step:14:16
And it's now fixed here …
=> [Symfony 6] Fix attribute bundle test app

src/Sylius/Bundle/ChannelBundle/test/app/AppKernel.php, src/Sylius/Bundle/ChannelBundle/test/app/config/config.yml
| Bug fix?        | yes (for Symfony-6)                                                       |
| Related tickets | partially #13274                     |
Trying to fix https://github.com/Sylius/Sylius/runs/6420619327?check_suite_focus=true#step:14:9 …
=> [Symfony 6] Fix Channel bundle test app

src/Sylius/Bundle/CurrencyBundle/test/app/AppKernel.php, src/Sylius/Bundle/CurrencyBundle/test/app/config/config.yml
Trying to fix https://github.com/Sylius/Sylius/runs/6420619510?check_suite_focus=true#step:14:9 …
=> [Symfony 6] Fix Currency bundle test app

src/Sylius/Bundle/CustomerBundle/test/app/AppKernel.php, src/Sylius/Bundle/CustomerBundle/test/app/config/config.yml
| Bug fix?        | yes  (for Symfony 6)                                                   |
Trying to fix https://github.com/Sylius/Sylius/runs/6420619599?check_suite_focus=true#step:14:9 …
=> [Symfony 6] Fix Customer bundle test app

src/Sylius/Bundle/InventoryBundle/test/app/AppKernel.php, src/Sylius/Bundle/InventoryBundle/test/app/config/config.yml
Trying to fix https://github.com/Sylius/Sylius/runs/6420619703?check_suite_focus=true#step:14:15 …
=> [Symfony 6] Fix Inventory bundle test app

src/Sylius/Bundle/LocaleBundle/test/app/AppKernel.php, src/Sylius/Bundle/LocaleBundle/test/app/config/config.yml
Trying to fix https://github.com/Sylius/Sylius/runs/6420619797?check_suite_focus=true#step:14:9
And this is fixed here https://github.com/Sylius/Sylius/runs/6423360053?check_suite_focus=t …
=> [Symfony 6] Fix Locale bundle test app

src/Sylius/Bundle/PaymentBundle/test/app/AppKernel.php, src/Sylius/Bundle/PaymentBundle/test/app/config/config.yml
Trying to fix https://github.com/Sylius/Sylius/runs/6420620162?check_suite_focus=true#step:14:15
And this is fixed here https://github.com/Sylius/Sylius/runs/6423685514?check_suite_focus …
=> [Symfony 6] Fix Payment bundle test app

src/Sylius/Bundle/ProductBundle/spec/Form/EventSubscriber/BuildProductVariantFormSubscriberSpec.php
Trying to fix https://github.com/Sylius/Sylius/runs/6420687764?check_suite_focus=true#step:11:10
This is fixed here …
=> [Symfony 6] Fix specifications for build product variant form subscriber

src/Sylius/Bundle/TaxonomyBundle/Tests/Functional/app/AppKernel.php, src/Sylius/Bundle/TaxonomyBundle/Tests/Functional/app/config/config.yml
Trying to fix https://github.com/Sylius/Sylius/runs/6420620909?check_suite_focus=true#step:11:7
This is fixed here …
=> [Symfony 6] Fix Taxonomy bundle test app

src/Sylius/Bundle/UiBundle/spec/Controller/SecurityControllerSpec.php
Trying to fix https://github.com/Sylius/Sylius/runs/6454899537?check_suite_focus=true#step:11:10
This is fixed here …
=> [Symfony 6] Fix specifications for security controller

src/Sylius/Bundle/MoneyBundle/test/app/AppKernel.php, src/Sylius/Bundle/MoneyBundle/test/app/config/config.yml
Trying to fix https://github.com/Sylius/Sylius/runs/6420619940?check_suite_focus=true#step:14:9
And this is fixed here https://github.com/Sylius/Sylius/runs/6469667245?check_suite_focus= …
=> [Symfony 6] Fix Money bundle test app

phpspec.yml.dist
| Related tickets |     |
This is not needed anymore since #13921
=> Remove custom error level on Phpspec

src/Sylius/Bundle/ProductBundle/spec/Form/EventSubscriber/BuildProductVariantFormSubscriberSpec.php, src/Sylius/Bundle/ProductBundle/test/app/config/config.yml
| Bug fix?        | yes (for Symfony 6)                                                   |
Trying to fix https://github.com/Sylius/Sylius/runs/6452955213?check_suite_focus=true#step:14:15
This is fixed here (but next error) …
=> [Symfony 6] Fix Product bundle test app

src/Sylius/Bundle/TaxationBundle/spec/DependencyInjection/Compiler/RegisterCalculatorsPassSpec.php
Trying to fix https://github.com/Sylius/Sylius/runs/6420688720?check_suite_focus=true#step:11:10 …
=> [Symfony 6] Fix specifications for register calculators pass

config/bundles.php, symfony.lock
| New feature?    | no                                                   |
Ones `sonata-project/block-bundle` had update to 4.13 probably that's the reason why composer update was broken
=> [Dependencies] Removed unused registered Sonata bundles

src/Sylius/Bundle/AddressingBundle/test/app/AppKernel.php, src/Sylius/Bundle/AddressingBundle/test/app/config/config.yml
| Related tickets |  partially #13274                    |
Trying to fix https://github.com/Sylius/Sylius/runs/6628306528?check_suite_focus=true#step:14:1 …
=> Fix addressing test app

src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/GenerateProductVariantsSubscriber.php, src/Sylius/Bundle/ProductBundle/Resources/config/services/form.xml, src/Sylius/Bundle/ProductBundle/spec/Form/EventSubscriber/BuildProductVariantFormSubscriberSpec.php, src/Sylius/Bundle/ProductBundle/spec/Form/EventSubscriber/GenerateProductVariantsSubscriberSpec.php, src/Sylius/Bundle/ProductBundle/test/app/config/config.yml, src/Sylius/Component/Product/Generator/ProductVariantGeneratorInterface.php
Trying to fix https://github.com/Sylius/Sylius/runs/6453097655?check_suite_focus=true#step:14:16
This is fixed here …
=> [Symfony 6] Fix generate product variants subscriber

.github/workflows/refactor.yml, config/bundles.php
| Related tickets |                      |
As we no longer maintain support for version 1.10 (except security fixes), I would like to remove 1.10 branch from the scheduled ECS refactor.
=> [Maintenance] Remove 1.10 branch from scheduled ECS refactor

docs/book/configuration/currencies.rst
| Branch?         | 1.11          |
The mentioned `CurrencyProvider` does not exist since https://github.com/Sylius/Sylius/commit/16c50a96b6c369451993958e49cfe114dcfe585b from 2017 🎉
=> [Documentation] Remove section about CurrencyProvider that does not exist

.github/workflows/application.yml
| Branch?         | 1.10  |
| Related tickets |  same as https://github.com/Sylius/Sylius/pull/13970 |
=> Remove auto commenting feature on 1.10 & 1.11 as well

.github/workflows/split-repo.yml
| Branch?         | 1.11         |
Currently, we're doing packages split manually (I mean, with a script 😄 but by ourselves) after each merge. I suppose it's the highest time to automatize it. I checked this configuration on my fork and it …
=> Split Sylius packages in Github Actions

src/Sylius/Bundle/ApiBundle/Serializer/CommandArgumentsDenormalizer.php
| Branch?         | master        |
The return type has changed on Symfony 6, this is not a bc-break cause the service is final.
I based this PR to the master branch to prove it works correctly with a success …
=> [Symfony 6] Fix command arguments denormalizer return typehint

features/addressing/managing_countries/managing_provinces_of_country.feature, features/addressing/managing_zones/deleting_zone.feature, src/Sylius/Behat/Context/Api/Admin/ManagingCountriesContext.php, src/Sylius/Behat/Context/Api/Admin/ManagingZonesContext.php, src/Sylius/Behat/Context/Setup/ZoneContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingZonesContext.php, src/Sylius/Behat/Resources/config/services/contexts/ui.xml, src/Sylius/Behat/Resources/config/suites/api/addressing/managing_countries.yml, src/Sylius/Behat/Resources/config/suites/ui/addressing/managing_countries.yml, src/Sylius/Bundle/AddressingBundle/EventListener/ZoneMemberIntegrityListener.php, src/Sylius/Bundle/AddressingBundle/Resources/config/services.xml, src/Sylius/Bundle/AddressingBundle/Resources/config/services/checkers.xml, src/Sylius/Bundle/AddressingBundle/Resources/config/services/listeners.xml, src/Sylius/Bundle/AddressingBundle/spec/EventListener/ZoneMemberIntegrityListenerSpec.php, src/Sylius/Bundle/ApiBundle/DataPersister/CountryDataPersister.php, src/Sylius/Bundle/ApiBundle/DataPersister/ZoneDataPersister.php, src/Sylius/Bundle/ApiBundle/Exception/ProvinceCannotBeRemoved.php, src/Sylius/Bundle/ApiBundle/Exception/ZoneCannotBeRemoved.php, src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml, src/Sylius/Bundle/ApiBundle/Resources/config/services/data_persisters.xml, src/Sylius/Bundle/ApiBundle/spec/DataPersister/CountryDataPersisterSpec.php, src/Sylius/Bundle/ApiBundle/spec/DataPersister/ZoneDataPersisterSpec.php, src/Sylius/Component/Addressing/Checker/CountryProvincesDeletionChecker.php, src/Sylius/Component/Addressing/Checker/CountryProvincesDeletionCheckerInterface.php, src/Sylius/Component/Addressing/Checker/ZoneDeletionChecker.php, src/Sylius/Component/Addressing/Checker/ZoneDeletionCheckerInterface.php, src/Sylius/Component/Addressing/spec/Checker/CountryProvincesDeletionCheckerSpec.php, src/Sylius/Component/Addressing/spec/Checker/ZoneDeletionCheckerSpec.php
| Related tickets |                      |
It is possible to delete the resource (zone or province) that is already in use as a zone member. When we delete such a resource, we cannot access the zone edit screen (and probably even more) because we try to load an …
=> [Addressing] Prevent deleting zones and provinces that are zone members

features/addressing/managing_countries/managing_provinces_of_country.feature, src/Sylius/Behat/Context/Api/Admin/ManagingCountriesContext.php, src/Sylius/Behat/Context/Setup/ZoneContext.php, src/Sylius/Behat/Context/Transform/ProvinceContext.php, src/Sylius/Behat/Context/Ui/Admin/ManagingCountriesContext.php, src/Sylius/Behat/Resources/config/suites/api/addressing/managing_countries.yml, src/Sylius/Behat/Resources/config/suites/ui/addressing/managing_countries.yml, src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Zone.orm.xml
| Branch?         | 1.11          |
| Related tickets | https://github.com/Sylius/Sylius/pull/14041                      |
Without orphan removal, even if we delete the zone member, the corresponding province/country cannot be removed because orphans still exist in the database.
=> [Addressing] Enable orphan removal for zone members

features/addressing/managing_zones/adding_zone.feature, src/Sylius/Bundle/AddressingBundle/Form/Type/CountryChoiceType.php, src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneType.php, src/Sylius/Bundle/AddressingBundle/Tests/Form/Type/CountryChoiceTypeTest.php, src/Sylius/Bundle/AdminBundle/Resources/views/Zone/_form.html.twig
| Branch?         | 1.11           |
Right now we’re experiencing a bug-o-feature, where when you disable a country that is a zone member, the members list on the Zone shows empty dropdown and field is unable to be controlled.
Changes made:
- adding disabled countries as zone members …
=> [Admin][Zones] Choosing disabled country as a zone member made possible for admin user

src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml, src/Sylius/Bundle/ShippingBundle/Resources/config/services/checker.xml, src/Sylius/Bundle/ShippingBundle/composer.json, src/Sylius/Bundle/ShippingBundle/test/app/AppKernel.php, src/Sylius/Bundle/ShippingBundle/test/app/config/config.yml
Trying to fix https://github.com/Sylius/Sylius/runs/6776680343?check_suite_focus=true#step:8:18 …
=> [Symfony 6] Fix Shipping bundle

src/Sylius/Bundle/PromotionBundle/composer.json, src/Sylius/Bundle/PromotionBundle/test/app/AppKernel.php, src/Sylius/Bundle/PromotionBundle/test/app/config/config.yml
Trying to fix https://github.com/Sylius/Sylius/runs/6776679932?check_suite_focus=true#step:8:17 …
=> [Symfony 6] Fix Promotion bundle

src/Sylius/Bundle/CoreBundle/Migrations/Version20220614124639.php
| Branch?         | 1.11           |
Now we encounter bug that when we already have some data in the db and we use the prepared migrations they fail with 500 wherever we call the minimum price. It is caused by migration that sets default value to null, we managed to add another …
=> [Migrations] Minimum price migration fixed

src/Sylius/Bundle/CoreBundle/Fixture/Listener/ImagesPurgerListener.php, src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml, src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/shop_configuration.yaml, src/Sylius/Bundle/CoreBundle/Resources/config/services/fixtures_listeners.xml, src/Sylius/Bundle/CoreBundle/spec/Fixture/Listener/ImagesPurgerListenerSpec.php
| Bug fix?        | yes?                                                       |
Currently without removing pictures when loading fixtures, the images directory can grow unnecessarily very quickly.
=> [Fixtures] Add a fixture listener for removing images

src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-auto-complete.js
| Related tickets | fixes #13571
=> [UI] Disable session storage for autocomplete dropdowns

.github/workflows/packages.yml, src/Sylius/Bundle/UserBundle/.gitignore, src/Sylius/Bundle/UserBundle/Authentication/AuthenticationSuccessHandler.php, src/Sylius/Bundle/UserBundle/DependencyInjection/Compiler/RemoveUserPasswordEncoderPass.php, src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php, src/Sylius/Bundle/UserBundle/Security/UserLogin.php, src/Sylius/Bundle/UserBundle/Security/UserPasswordHasher.php, src/Sylius/Bundle/UserBundle/SyliusUserBundle.php, src/Sylius/Bundle/UserBundle/Tests/DependencyInjection/Compiler/RemoveUserPasswordEncoderPassTest.php, src/Sylius/Bundle/UserBundle/Tests/Functional/app/AppKernel.php, src/Sylius/Bundle/UserBundle/Tests/Functional/app/config/config.yml, src/Sylius/Bundle/UserBundle/composer.json, src/Sylius/Bundle/UserBundle/spec/Authentication/AuthenticationSuccessHandlerSpec.php, src/Sylius/Bundle/UserBundle/spec/EventListener/UpdateUserEncoderListenerSpec.php, src/Sylius/Bundle/UserBundle/spec/Security/UserPasswordHasherSpec.php, src/Sylius/Component/User/composer.json
| Branch?         | symfony 6         |
| BC breaks?      | hope no                                                       |
This is fixed here https://github.com/Sylius/Sylius/runs/6986299100?check_suite_focus=true
=> [Symfony 6] Fix user bundle

composer.json
| Branch?         | 1.11 |
I'm proposing adding flex to our allowed plugins, as we are using it and it is in our req/dev. In addition, I've also disallowed `dealerdirect/phpcodesniffer-composer-installer`, as we are not using it directly. 
What is more, I'm …
=> [Maintenance] Composer allow plugins finally sorted out + removal of symfony thanks

src/Sylius/Component/Core/Model/OrderItem.php, src/Sylius/Component/Core/spec/Model/OrderItemSpec.php
| Related tickets | replace https://github.com/Sylius/Sylius/pull/13986, fixes https://github.com/Sylius/Sylius/issues/13532 and https://github.com/Sylius/Sylius/issues/11585                     |
We also should add here behat scenario, but TBH, I don't know how to prepare proper background
=> Fix calculate order item subtotal

src/Sylius/Bundle/CoreBundle/Fixture/Listener/ImagesPurgerListener.php, src/Sylius/Bundle/CoreBundle/spec/Fixture/Listener/ImagesPurgerListenerSpec.php
| Related tickets | fixes #14095                       |
=> [Fixtures] Fix removing images before suite

src/Sylius/Bundle/OrderBundle/Resources/config/services/form.xml, src/Sylius/Bundle/OrderBundle/composer.json, src/Sylius/Bundle/OrderBundle/test/app/config/config.yml
| Related tickets | partially fixes #13274, based on #14066  |
Changes required due to deprecation in Sf 6.0
After fix: https://github.com/Sylius/Sylius/runs/7076277139?check_suite_focus=true
=> [Fix][Maintenance] Cart item data mapper adjusted to be Sf6 compatible

features/product/viewing_products/viewing_product_with_disabled_main_taxon.feature, src/Sylius/Behat/Context/Setup/ProductTaxonContext.php, src/Sylius/Behat/Context/Ui/Shop/ProductContext.php, src/Sylius/Behat/Page/Shop/Product/ShowPage.php, src/Sylius/Behat/Page/Shop/Product/ShowPageInterface.php, src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_breadcrumb.html.twig
| Related tickets | fixes #13713 
When a product's main taxon is disabled, the product page breadcrumb renders it as a link and throws a Not Found exception if it is clicked.
As suggested in #13713, with this PR the breadcrumb will render the main taxon without a link (as a simple `<div>`) when the taxon is disabled.
=> [Product] Render disabled main taxon without link in breadcrumb

docs/getting-started-with-sylius/shop-customizations.rst
| Branch?         | 1.11      |
=> [Docs] Fix logo customization guide

src/Sylius/Bundle/PromotionBundle/Form/DataTransformer/PercentFloatToLocalizedStringTransformer.php
| Q               | A                                                          
|-----------------|--------------------------------------------------------------
| Branch?         | symfony-6
| Bug fix?        | yes                                                       
| New feature?    | no                                                       
| Related tickets | partially #13274 
| License         | MIT                                                          
It throws an error there https://github.com/Sylius/Sylius/runs/7229517957?check_suite_focus=true#step:15:13 on Sylius/Sylius#14079
It's green here https://github.com/Sylius/Sylius/runs/7229800892?check_suite_focus=true
and there …
=> Fix Percent float to localized string transformer
